### ISSUE TITLE
Bug in Linux when renaming Objects

### ISSUE THREAD

**Issue by LeomixGH** [4ian/GDevelop#1000]
## Describe the bug
When you rename an object sanitization occurs after the error is detected.
It may not generate any error in windows but in Linux I freezes the desktop.

At that point only the mouse moves,  click do not work anymore.
The only issue is to Press [ESC]
The first time I though I had to reboot.

#Please double check that the bug is not already reported in the issues list.
Done

## To Reproduce
1. Create a new text object
2. Rename it to "NewObect 03"
3. Then you get the error.

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

Can't screen shots it's frozen 

## Other details
* Mx Linux  & Xfce desktop  (Gdvelop ver: 5.0.0 beta 65)
* Could be occuring when the dialog box pops up and you click anywhere but on the box
as your mouse is on the complete right of the screen

**Comment by LeomixGH** [comment]
Add on
Better Dialog box : No Space allowed when name items
When the error occurs you can not click on the ok button (only [ESC])

The error is corrected after the clic. I mean it gets back to the default value of that object

**Comment by Bouh** [comment]
@LeomixGH are you still experimenting with the issue?
If no response we'll close this issue after 15 days.
