### ISSUE TITLE
Animated mute icon

### ISSUE THREAD

**Issue by PrashantGyawali** [4ian/GDevelop#1008]
Hi!
  
  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.
  
  I cannot confirm that the assets can be used by everybody!!
  PLease make it easier to submit our examples ! I wanted to help and took me an whole hour to figure out how to submit and making github account! :(
Wait How do I send my example ??
What file format is supported??
This is bad 4ian ! Plz make  a better way to send you may be give an email !!

**Comment by 4ian** [comment]
Hi,

You have to create an account (5min) and then for any example, you zip the
file and attach it to your message on Github (2min).

Not that difficult ;) And I guess way faster than doing anything custom,
and way below the time to create a good quality example :)

Anyway, zip your example and attach it to your message here 😊

**Comment by PrashantGyawali** [comment]
oh ! So I had to zip it!! Well what should I zip ? The apk file or the
gdevelop project?

**Comment by PrashantGyawali** [comment]
[ANIMATED MUTE BOTTON.zip](https://github.com/4ian/GDevelop/files/3051197/ANIMATED.MUTE.BOTTON.zip)
[ANIMATED MUTE BOTTON.zip](https://github.com/4ian/GDevelop/files/3051198/ANIMATED.MUTE.BOTTON.zip)

**Comment by PrashantGyawali** [comment]
OK I AM SORRY! I DONT KNOW WHY BUT THE SPEAKER ASSETS DIDNT GET UPLOADED! DID I HAVE TO MOVE THE ASSETS TO THE SAME FOLDER?

**Comment by PrashantGyawali** [comment]
hello take this

**Comment by 4ian** [comment]
Please rather edit your messages and avoid using all capital letters when writing, it looks like you're screaming ;)

**Comment by PrashantGyawali** [comment]
ok! but did you get the example and is it perfectly running?

**Comment by PrashantGyawali** [comment]
Is Gdevelop still developing or is it dead?
Whatever it is it is great!!

**Comment by PrashantGyawali** [comment]
if you feel like something is missing or something in the comments is wrong
then plz edit it  ! !

**Comment by PrashantGyawali** [comment]
Hello sir! I dont know why but The music on games are not being played on
mobile as supposed to like in the preview!! I asked my friend a 1000 times
but still not running! Is that a bug or that section is still under
development?? Without music a game doesnot feel enjoyable!! I wish I knew
how to code but plz sir fix that!!

**Comment by 4ian** [comment]
Please edit your messages, don't write so much message. Also please go to the forums for these questions. :) forum.gdevelop-app.com
GitHub is only for technical, development related discussions and contributions

**Comment by PrashantGyawali** [comment]
Yeah I know sir! Its TECHNICAL so its hard for me

**Comment by PrashantGyawali** [comment]
Sorry  sir

**Comment by PrashantGyawali** [comment]
Did you test the example I sent?
