### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by jurassicjordan** [4ian/GDevelop#1011]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in k
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in t
    in div
    in t
    in t
    in t
    in Unknown
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
```

**Comment by 4ian** [comment]
Seems that there is no stack, it won't be helpful unfortunately :( Closing this for now
