### ISSUE TITLE
jfxr fails to unzip on master

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1014]
## Describe the bug
It looks like after a recent commit, jfxr stopped working because it now fails to unzip for some reason.

My guess is the switch to unzipper
https://github.com/4ian/GDevelop/commit/1dba4bbda80ceafc26c848b70f4b7ad6c57c3c75

Does this happen only to me when using the latest master?

**Comment by 4ian** [comment]
Can you post the full errors?

**Comment by blurymind** [comment]
Ok, I tried recompiling and still when I try to open/create a sound effect via jfxr, electron loads a new broken session of gdevelop instead.

When looking at the public/external folder - it did manage to extract it.
For some reason its not finding it. It's worth noting that this happens on the dev environment version

**Comment by blurymind** [comment]
The issue seems to be due to jfxr not being extracted to a subfolder.
`app\public\external\jfxr\jfxr-editor<contents>`
but instead its extracted like this:
`app\public\external\jfxr\<contents>`

**Comment by blurymind** [comment]
upon further inspection - unzipper doesnt seem to unzip at all xD

**Comment by blurymind** [comment]
Ok this is quite stupid. Unzipper does not work with `/` on windows. It has to be `\\` instead, this is probably why you didnt notice it

**Comment by blurymind** [comment]
closing now as it was merged :)
