### ISSUE TITLE
Facebook Instant score board share, screen share Facebook features

### ISSUE THREAD

**Issue by sanjayaharshana** [4ian/GDevelop#1024]
BEFORE opening a new feature request, please make sure that you:
 * Discussed about it on the discord or the forum,
 * There is not already a suggestion about it in the issues or in the roadmap: https://trello.com/b/qf0lM7k8/gdevelop-roadmap
 * Consider commenting on the roadmap if something is important for you

AFTER opening the feature request, the issue will be closed by a maintainer (@4ian or someone else) and a card will be added in the roadmap if it's relevant and does not exist yet :)

## Description
Is your feature request **related to a problem**? Please describe.

## Solution suggested
**Describe the solution**
A clear and concise description of what could be done.

Explain if you can help implementing the solution.

**Comment by 4ian** [comment]
Please complete the template before submitting a new feature request :) It's not clear from the title what you request exactly?
