### ISSUE TITLE
Security Error when preview in Firefox web browser

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1033]
## Describe the bug
When running a preview in Firefox I get this error message:
```
SecurityError: The operation is insecure.
WebsocketDebuggerClient https://s3-eu-west-1.amazonaws.com/gdevelop-resources/GDJS-5.0.0-beta62/Runtime/websocket-debugger-client/websocket-debugger-client.js:15
    RuntimeGame https://s3-eu-west-1.amazonaws.com/gdevelop-resources/GDJS-5.0.0-beta62/Runtime/runtimegame.js:57
    <anonymous> https://s3-eu-west-1.amazonaws.com/gd-games-preview/1555923161805-164935/index.html:96
<anonymous> https://s3-eu-west-1.amazonaws.com/gd-games-preview/1555923161805-164935/index.html:90
```

## To Reproduce
1. In the web version of GDevelop open any projects using Firefox
2. Launch preview

## Other details
I know the problem has been already reported and considered a problem with Firefox and the issue has been closed. I also realize Chrome is the future but I do stick with Firefox since day 1 and doesn't matter how great and popular the Chromium engine is becoming I continue to do so for my everyday web browsing and it is very inconvenient for me that GDevelop is the ONLY web app that does not work in Firefox. I would like to recommend to reconsider it to look in to this. Even if it something about Firefox, GDevelop is the ONLY thing Firefox has this problem with so it must be something specific about GDevelop that Firefox doesn't like.

Thanks.

**Comment by 4ian** [comment]
Fixed. More generally, GDevelop is built on recent web standards, using some advanced features (WebGL). It should: 

* Work on Chrome and any recent Chromium (next Edge version for example).
* Work on Firefox.
* Safari is lacking proper support for quite a few things and generally lagging behind so support is a non goal for now - even if I hope this can improve with newer versions and when/if we add support for mobile/tablets (iPad/Android) with projects/resources saved on some cloud providers.
