### ISSUE TITLE
Shortcut Clipboard doesn't work

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1036]
## Describe the bug
Use the shortcuts Copy/Paste the events doesn't work.

## To Reproduce
1. Open any project
2. Go to Eventsheet
3. Try to copy with Shortcut few events
4. Paste it where you want, nothing is pasted.
5. Try to paste it in external text editor, nothing is pasted.

## Other details
Maybe a issue after [this commit](https://github.com/4ian/GDevelop/commit/0b3b6f1b946e8166e5bdb479145369b5c3e5cbc6) ?
* GD5 B66, Win10

**Comment by 4ian** [comment]
Indeed! Sounds more like an issue with shortcuts, as the clipboard is working when using the context menu items.

**Comment by Bouh** [comment]
I've tested the commits, all works fine before [this commit](https://github.com/4ian/GDevelop/commit/0a8ba7b838dc3334cc9adeda8d33be1334ac3def).
After this commit the shortcut doesn't work. I hope it's help.

**Comment by 4ian** [comment]
Fixed in master. Got bitten by an edge case of JS semantic.
I'll try to upload a new version with the bug fix not too late.

**Comment by 4ian** [comment]
> I hope it's help.

It was helpful yeah, I was able to quickly see what caused the regression :)
