### ISSUE TITLE
Create an object in a function

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#1038]
I tried to create an object from a function I created in a custom extension but nothing happens.
I understand that the object of the scene are not known by the function, as an external event can only know about the objects of the scene we attached to it. So if my function doesn't know about my object and objects group, how can I spawn something from a function?

**Comment by 4ian** [comment]
If you pass the objects as argument, you should be able to create them. It's done in the example Space Shooter with functions.

For your questions, please ask on the forum - GitHub is only for bug reports following the template. Thanks! :)

**Comment by timotheeficat** [comment]
Ok I'll try it, thank you for your answer !
Sorry I thought it was a bug. I will use the forum or Discord for this kind of questions in the future.
