### ISSUE TITLE
"Create a new game" dialog freezes when "CHOOSE FOLDER" button was clicked

### ISSUE THREAD

**Issue by RednibCoding** [4ian/GDevelop#1039]
## Describe the bug
In the "Create a new game" dialog where you can choose certain templates or an empty project to start with, there is a "CHOOSE FOLDER" button on the bottom right corner. Clicking this button causes the dialog and therefore GDevelope to freeze. Only way to close GDevelope is via Taskmanager. 

Tested on:
- Laptop with Win10 Home Premium 64bit
- PC with Win10 Pro 64bit
Both with and without GDevelope having administrator rights

## To Reproduce
1. Open GDevelope
2. Click CREATE A NEW PROJECT
3. Scroll down
4. Click CHOOSE FOLDER
5. -> GDevelope freeze

## Other details
GDevelope Version 5 beta 65

**Comment by 4ian** [comment]
Thanks for the report :) This is fixed in beta 66 already ;)
