### ISSUE TITLE
Behaviour not detected in the expressions editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1041]
## Describe the bug
In the Expressions blue button, the platformer behaviour doesn't seem to be "detected".
Confirmed with the default platformer example:
![image](https://user-images.githubusercontent.com/25978830/56854415-86122f80-6936-11e9-85e5-f4bbe9bb21f7.png)

Windows 10
GD5b66

**Comment by 4ian** [comment]
Which expression are you using?

**Comment by PascalLadalle** [comment]
I wanted the platformer maximum speed (but the other platformer settings don't seem to work either).

**Comment by 4ian** [comment]
Thanks for the report, I've found the issue and fixed it for next version! :) For now you have to write manually the name of the name of the behavior, for example `PlayerHitBox.PlatformerObject::Acceleration()`
