### ISSUE TITLE
Export issues

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1043]
Several minor bugs related to the export/build process, hope you don't mind me grouping them here.

## Describe the bugs
- The free build counter doesn't get updated unless GD is closed and reopened.
- The upload progress bar is very inaccurate. It fills in a few seconds while my upload process takes a few minutes.
- Clicking outside the export window closes it (which I suspect to be responsible for a timeout error that popped up later, because it closed while I was doing an online build).

Minor bugs, as I said 😄 

Windows 10
GD5b66

**Comment by Silver-Streak** [comment]
@4ian 

This issue is ~2.5 years old. As it doesn't seem like it's been picked up by anyone. Is this something that should be refocused on?

**Comment by 4ian** [comment]
The last issue is fixed, but the first two are good minor problems that could be improved/fixed.
