### ISSUE TITLE
Eventsheet Keyboard Copy&Paste not working

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1044]
## Describe the bug
Copy&Pasting of actions/conditions inside the event sheet is not possible anymore via keyboard.
## To Reproduce
1. Open any project
2. Mark an action or condition with the mouse
3. Hit CTRL+C
4. Mark another event with the mouse
5. Hit CTRL+V
6. Nothing happens
CTRL+C doesn't even seem to copy the action/condition to the clipboard since the context menu entry for `Paste` is still grayed out when trying to insert the action/condition via context menu.

## Other details
* Linux Mint 17.3 Cinnamon 64Bit 
* GDevelop 5 Beta 66

**Comment by 4ian** [comment]
Yup, this was just fixed in beta 67 😄Sorry for the regression

**Comment by Wend1go** [comment]
You fix issues quicker than I can report them. 😁
