### ISSUE TITLE
Problem launching newIDE : Can't resolve '@lingui/core'

### ISSUE THREAD

**Issue by lamenagere** [4ian/GDevelop#1047]
## Describe the bug
Hi there,

I'am actually trying to create an extension for a personal project. I followed the instructions and ran the windows batch linked in the "Quick Install" here: https://github.com/4ian/GDevelop/blob/master/newIDE/README.md#development-of-the-standalone-app

Unfortunately, when I run 'npm start', here is the code I have in the console:
'Failed to compile.
./src/Utils/i18n/GDI18nProvider.js
Module not found: Can't resolve '@lingui/core' in 'C:\Users\...\Documents\GDevelop\newIDE\app\src\Utils\i18n'

For info,
I installed node.js 8.15.0 (because I had some other problems with latest version) and GDevelop 5.0.0-bea68. 

After checking, the file GDI18nProvider.js is in folder 'C:\Users\...\Documents\GDevelop\newIDE\app\src\Utils\i18n'

![Lingui_Bug](https://user-images.githubusercontent.com/11350504/57136507-60a97980-6dad-11e9-92fb-25232e6cb5f6.jpg)

Here is the screenshot of the console.
Can anyone help me ?

**Comment by lamenagere** [comment]
Ok,
Strangely, deleting then reinstalling node_modules made it work.
I guess you can close this issue.

**Comment by lamenagere** [comment]
Ok,
Strangely, deleting then reinstalling node_modules made it work.
I guess you can close this issue.

**Comment by 4ian** [comment]
Strange, if you can reproduce the problem again let me know!
