### ISSUE TITLE
GDevelop fails to start on Windows 10

### ISSUE THREAD

**Issue by Marino108** [4ian/GDevelop#1050]
Hello,
The latest GDevelop version (gdevelop-setup-5.0.0-beta68) won't start. I have downloaded the installation file and tried switching on all compatibility options; It just won't start the installation. The older version of GDevelop (gd4097) works.
Thank you,
Marino

**Comment by 4ian** [comment]
> older version of GDevelop (gd4097

Quite old ^^

GDevelop 5 is based on a different installer - it's an auto installer that create a shortcut of the desktop.
Can you confirm you don't have an antivirus preventing the extraction?

**Comment by Marino108** [comment]
No, I don't think the antivirus is preventing the extraction because no messages show up. BTW, I had the same issue with other software installations. There must be some issue related to Windows 10.

**Comment by Shineonline** [comment]
Has to be your Operating System.

**Comment by 4ian** [comment]
Closing for now as don't have more relevant information.
