### ISSUE TITLE
Timer with underscore won't get trigger

### ISSUE THREAD

**Issue by misterpah** [4ian/GDevelop#1051]
## Describe the bug
Object Timer created with underscore ( _ ) in it's name are not triggered.

## To Reproduce
1. Create action Object timer with underscore in it's name. eg: dodge_timer
2. Create condition Object timer with underscore in it's name. eg: dodge_timer
3. run

## Other details
* Include any OS/browser version/smartphone that you're using
 windows 10

* Which version of GDevelop are you using? The desktop app or the web-app?
Gdevelop 5.0.0-beta68 , desktop application

* Add any other context about the problem here.
It's good if the error is detected at the object timer form.

**Comment by 4ian** [comment]
Can you reproduce this bug in a small example game?
Timer names are strings and should be able to contain any kind of character.
