### ISSUE TITLE
Panel Sprite: Change image results in corners being upside down

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1052]
## Describe the bug
Changing the image of a panel sprite at runtime via "Image name" action flips all corners upside down, except the upper left one.
![image](https://user-images.githubusercontent.com/7413059/57869725-f0b3de00-7805-11e9-8cff-b40ba49f9402.png)

## To Reproduce
1. Create a scene and add a Panel Sprite
2. Assign a texture and set the corner tiles
3. Add an instance of it to the scene (it gets drawn correctly)
4. Create an event to set a new image (Image name)
5. The Panel Sprite gets updated with the new image but the corners are drawn upside down
Only the upper left corner is drawn correctly. (This also happens if you assign a completely different image)

## Example project showing the bug
[PanelSpriteUpsideDownBug.zip](https://github.com/4ian/GDevelop/files/3188003/PanelSpriteUpsideDownBug.zip)

## Other details
GDevelop 5.0.0 Beta 68

EDIT:
On a second thought, it looks like it uses the upper left corner for all the corner tiles.

**Comment by Wend1go** [comment]
More screenshots showing the issue here: 
https://github.com/4ian/GDevelop/pull/1114#issuecomment-503215579

**Comment by 4ian** [comment]
This is (finally 😬) fixed for next version thanks to @Bouh fix! Thanks again @Bouh 👏

**Comment by 4ian** [comment]
FYI, the upside down corner was still a problem it seems, will be fixed, see https://github.com/4ian/GDevelop/issues/1723! :)
