### ISSUE TITLE
rotating the camera doesn't rotate masks

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1058]
## Describe the bug
When I rotate the camera of a layer which has a platform, the platform moves but its collision mask remains behind. (Physics 2.0 behaviour)

[roundshegoes.zip](https://github.com/4ian/GDevelop/files/3214256/roundshegoes.zip)

**Comment by 4ian** [comment]
It's not a bug :) You're rotating the layer: the layer is like a sheet of paper, where GDevelop draws the objects according to their position in the world.  Then, you can ask these sheets of paper (the layers) to be rotated, but it's only impacting what is drawn on screen.

Collisions and the real position of objects won't move. (try to look in the debugger at the position of objects on a layer that has the camera position moved: nothing will move).

What you should do instead is to use the action to rotate the object/put the object around a position.
