### ISSUE TITLE
GDCpp.dll link error

### ISSUE THREAD

**Issue by shinyboy** [4ian/GDevelop#1059]
I am really sorry to bother you.

While I try to compile the GDevelop, I failed to link GDCpp.dll, I have no idea where is the _imp___ZTV15RuntimeBehavior?

Many thanks. Here is  the output of the compiler.

## Describe the bug

[435/731] Linking CXX shared library ..\Output\Release_Windows\GDCpp.dll
FAILED: ../Output/Release_Windows/GDCpp.dll ../Output/Release_Windows/libGDCpp.dll.a
cmd.exe /C "cd . && C:\TDM-GCC-32\bin\g++.exe  -std=gnu++11 -O3 -DNDEBUG   -shared -o ..\Output\Release_Windows\GDCpp.dll -Wl,--out-implib,..\Output\Release_Windows\libGDCpp.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\GDCpp.rsp  && cd ."
GDCpp/CMakeFiles/GDCpp.dir/GDCpp/Runtime/RuntimeBehavior.cpp.obj:RuntimeBehavior.cpp:(.text+0x1): undefined reference to `_imp___ZTV15RuntimeBehavior'
GDCpp/CMakeFiles/GDCpp.dir/GDCpp/Runtime/RuntimeBehavior.cpp.obj:RuntimeBehavior.cpp:(.text+0x3a): undefined reference to `_imp___ZTV15RuntimeBehavior'
C:/TDM-GCC-32/bin/../lib/gcc/mingw32/5.1.0/../../../../mingw32/bin/ld.exe: GDCpp/CMakeFiles/GDCpp.dir/GDCpp/Runtime/RuntimeBehavior.cpp.obj: bad reloc address 0x8 in section `.text$_ZN15RuntimeBehavior7SetNameERKN2gd6StringE[__ZN15RuntimeBehavior7SetNameERKN2gd6StringE]'
collect2.exe: error: ld returned 1 exit status
[440/731] Building CXX object GDCpp/CMakeFiles/GDCpp_Runtime.dir/GDCpp/Runtime/RuntimeObject.cpp.obj
ninja: build stopped: subcommand failed.

Please double check that the bug is not already reported in the issues list.

## To Reproduce

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

**Comment by 4ian** [comment]
Any reason why you're trying to compile GDevelop 4? :) 
Have you tried running GDevelop 5: https://github.com/4ian/GDevelop/tree/master/newIDE?

**Comment by shinyboy** [comment]
> Any reason why you're trying to compile GDevelop 4? :)
> Have you tried running GDevelop 5: https://github.com/4ian/GDevelop/tree/master/newIDE?

Cool, many many thanks for your suggestions. I was so silly to struggle for the deprecated version.
