### ISSUE TITLE
Change object name broken

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1060]
## Describe the bug
The object name doesn't get updated in the object properties/Object list after changing it in the object properties. But even though you can't see the new name in the list, it gets updated in the  eventsheet. So you have two different object names displayed at different places inside the IDE. 
(It only works correctly when you choose "rename" from the context menu)

## To Reproduce
Steps to reproduce the behaviour:
1. Create a new project and add a scene
2. Add an object
3. Add some event + condition/action with the object as parameter
3. Double Click on the object to open its properties
4. Change the object name and hit Apply
-> the name stays the same in the object list and object properties but existing events using the object correctly changed the name.

## Other details
* GD5 Beta 69

**Comment by 4ian** [comment]
So objects list is not properly updated after a change in the name in the Object Editor. I wonder if it's a recent regression or not.

**Comment by Wend1go** [comment]
Just tried to reproduce it in Beta 68. 
It works as it should there.

**Comment by ddabrahim** [comment]
Also when you enter the object name right when you create it, it doesn't update in the object list.

**Comment by 4ian** [comment]
Fixed! This was broken when slightly reworking object internals for custom behaviors
