### ISSUE TITLE
New object names don't save

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1068]
## Describe the bug
In the latest release of GD, when a new object is created, the name you give it is not saved. You cannot rename the object by opening it and editing the name. You must click "rename" to do so after the object is created. 

## To Reproduce
1. Go to a scene in your project
2. Click on the new object icon to create one.
3. Enter all the applicable details; image, text, etc. including your name for the object.
4. See that it is still called "NewObject" after you've clicked "apply".
5. Open the object and attempt to edit the name.
6. Repeat # 4 
7. Right click on the object or choose "rename" from the drop-down menu and enter your name.
8. The name is now saved.

* Please include a link to a game if possible!

This issue is within the object editor.

* If applicable, add screenshots to help explain your problem.

## Other details

* Include any OS/browser version/smartphone that you're using

Windows 8.1 laptop

* Which version of GDevelop are you using? The desktop app or the web-app?

GD Beta 69
Desktop app

* Add any other context about the problem here.

--

![newobjectname1](https://user-images.githubusercontent.com/45985516/58553252-71011880-81e2-11e9-8188-29657e4ef58b.gif)

![newobjectedit](https://user-images.githubusercontent.com/45985516/58553251-71011880-81e2-11e9-92f0-8acbf9c53eb1.gif)

![newobjectrename](https://user-images.githubusercontent.com/45985516/58553253-71011880-81e2-11e9-9dd5-7df0b9acf9bb.gif)

**Comment by Wend1go** [comment]
Shouldn't this have been fixed?
#1060

**Comment by Wend1go** [comment]
Does it still happen in Beta 70?

**Comment by Phenomena3** [comment]
Good question, this is currently the version I have...the program isn't offering the Beta 70 update.

![gdv](https://user-images.githubusercontent.com/45985516/58579520-454d5500-8219-11e9-98aa-52f8096f87e0.png)

**Comment by ddabrahim** [comment]
You can always download the latest version from here:
https://github.com/4ian/GDevelop/releases

Naming problem I had seems to be fixed on my end.

**Comment by Phenomena3** [comment]
It just updated to 70 and it is indeed fixed :)

**Comment by 4ian** [comment]
Got some issues while uploading latest version so auto update was not triggering properly. Should be fixed now! :)
