### ISSUE TITLE
Specifying number of times to REPEAT does not work for javascript code event

### ISSUE THREAD

**Issue by bil-ash** [4ian/GDevelop#1073]
## Describe the bug

Please double check that the bug is not already reported in the issues list.

If javascript code is used as a sub-event of REPEAT event the code is executed multiple times instead of the specified number. It was working properly 3-4 months back(the last time I used it), but I do not remember in which version.

## To Reproduce
The steps to reproduce are mentioned as comments in the event sheet and can be seen after opening the project in GDevelop. The game has been attached as zip file

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using     Windows 10
* Which version of GDevelop are you using? The desktop app or the web-app? Desktop, 5beta69
* Add any other context about the problem here.
This needs to work properly so that (advanced) users can use cordova plugins or electron APIs.

**Comment by bil-ash** [comment]
[game.zip](https://github.com/4ian/GDevelop/files/3240002/game.zip)
Sorry, forgot to upload the zip in the earlier comment. Uploading it here.

**Comment by 4ian** [comment]
Thanks for the zip file. This is not a bug :)

Events are ran at every frame of your game, i.e: 60 times per second.
The repeat event is for repeating things multiple times INSIDE each of these 60 runs of the events per second.

You can see by yourself:
- press a for roughly 1 second. As you're asking to add 10 pixels to the X position of the object, the object will be roughly at a position that is 600 pixels more on the X axis, compared to the beginning.
- press b for roughly 1 second. JavaScript will properly be called roughly 60 times, showing 60*1 = 60 "hello" in the console:

![image](https://user-images.githubusercontent.com/1280130/58689028-e05f3f80-837d-11e9-8389-986a35e810b9.png)

What you're looking for is maybe the "Trigger Once" condition?

**Comment by bil-ash** [comment]
Thanks, will try the 'triger once' condition
