### ISSUE TITLE
Draggable behavior, collision and Phyiscs engine does not work with complex shapes

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1074]
## Describe the bug
Discussion on the forum:
https://forum.gdevelop-app.com/t/click-and-drag-with-overlapping-objects/19008

When using complex shapes like a U for example:
-the mouse over object event detect the object also when the mouse is inside the U
-collision checking register collision when the object is inside a U shape **collision mask**
-draggable behavior pick the U shape even if it below the others when the empty space clicked
-Physics engine throw an error when trying to use physics on the U shape
![Selection_005](https://user-images.githubusercontent.com/24738433/58689482-0afdc800-837f-11e9-8a26-300397cd7b3a.png)

## To Reproduce
1. Add a complex shape like U
2. Edit the collision mask to fit
3. have fun

**OS:**
Linux/Mac/Windows

**Version:**
beta 0.70

If you open the project from the forum, it is the most noticeable with the U shape but the Z shape also play up sometime.

**Comment by 4ian** [comment]
I've not had the time to take a look yet, but a U shape is clearly a concave shape, which should be stated by the IDE as not supported (i.e: you'll get issues like collision is detected inside the shape, so that will both account for the collision and draggable behavior issue).
For the physics engine, I can't remember but quite possible that there is the same kind of limitation (but no warning in the IDE). Have to check.

**Comment by ddabrahim** [comment]
Oh, I did not realized it is a known limitation. I feel bad, I did told the guy GD is capable to support the puzzle game he is making :(

It must be mentioned on the docs.
I guess the only thing can be done is maybe cut the U shape in to two pieces or something...

Thanks.

**Comment by 4ian** [comment]
Note that *multiple collision masks* are supported, so you can create a U with 3 rectangles.
For the physics engine that won't work, you'll have to get 3 objects (but not sure if physics is needed?)

**Comment by ddabrahim** [comment]
No physics is not needed, I was only considering to make my own draggable behavior using Physics engine since the other options did not work. I was hoping Physics can handle this but then I got the error and give up.

I think hew was originally using 2 collision masks for the U and was getting the same error. I'll check, try it with 3 then and let you know if it does not work.

Thanks.

**Comment by 4ian** [comment]
> Physics engine throw an error when trying to use physics on the U shape

For this one, seems that physics engine is broken when added to an object. Will investigate. 
Might be unrelated to the collision masks (remember that physics is using its own shape/collision mask)

**Comment by ddabrahim** [comment]
Yes, that's why I was considering Physics I was hoping it might work since it got it own collision event and collision masks..etc.

Regarding using 3 collision masks, in the original project the guy was actually using 3 collision masks on the U shape and it is still did not work. He is using 2 on the Z shape as well and the Z also play up sometime with the draggable behavior and mouse over object event but not that often.

**Comment by 4ian** [comment]
Physics engine is broken when added for the first time on a scene. Will issue out a fixed version tomorrow or this week-end.

> Regarding using 3 collision masks, in the original project the guy was actually using 3 collision masks on the U shape and it is still did not work.

If that's the case consider making a minimal example so I can test. 3 collision masks should work in theory but it's rarely used so might have some issues.

**Comment by ddabrahim** [comment]
Here you go, 3 collision masks but the draggable behavior still drag it when you click the empty space:
[dragtest.zip](https://github.com/4ian/GDevelop/files/3242503/dragtest.zip)

Thanks.

**Comment by ddabrahim** [comment]
The mouse over object  event also play up when the mouse is over the empty space and so collision checking...

**Comment by 4ian** [comment]
Thanks that was useful. So draggable behavior/mouse over both use the bounding box of the object - meaning that it's not using the collision mask but just the virtual rectangle surrounding them.

Collision works properly though - as it's using collision mask and not just the bounding box:
[dragtest 2.zip](https://github.com/4ian/GDevelop/files/3242535/dragtest.2.zip)

**Comment by ddabrahim** [comment]
Collision had to be something else then, I'm a little scattered.

Thanks for looking in to it.
