### ISSUE TITLE
Copy/paste/duplicate object in object list, copy it with same name

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1076]
## Describe the bug
🚩 In object list when we use duplicate or copy and paste, focus is on the new object, but if we cancel the focus this new object have same name. 
And when we select the object both are selected.

![image](https://user-images.githubusercontent.com/1670670/58706759-3ac6c300-83b3-11e9-9ba7-5eb50ea44d4a.png)

## To Reproduce
1. Create new object
2. Copy it and paste 
3. focus is on it, but cancel this focus by click anywhere
4. See two objects have same name

## Other details
b70, w10

**Comment by 4ian** [comment]
> Create new object
> Copy it
> focus is on it, but cancel this focus by click anywhere
> See two objects have same name

I don't understand how you can have two objects while you've only clicked on Copy?

**Comment by Bouh** [comment]
Sorry for step 2 : copy and paste
But with duplicate issue appear.

**Comment by 4ian** [comment]
Thanks for reporting it, I've fixed it :) Regression due to the internal rework of objects to support custom behaviors.
