### ISSUE TITLE
Jumpthru Platform Behavior

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1084]
## Describe the bug

On newly created objects, the jumpthru platform behavior isn't working after being applied. It also doesn't save as when GD is reopening, the object is changed back to the regular type of platform. Existing platforms that have this setting seem fine as long as it's not changed - I haven't tried since I haven't been editing an example.

Please double check that the bug is not already reported in the issues list.

I used the search filter. 

Related open issues are months old and don't describe what's happening in this case.

## To Reproduce
1. Go to 'create an object'
2. Click on 'behaviors and add platform'
3. Select "Jumpthru platform" as the type and click "apply"
4. Test it on the scene - notice character cannot move through it as usual
5. Check the object editor to ensure that the platform behavior and type is configured correctly
6. See that it is 
7. Save the project, close, and reopen
8. Repeat number 5 except now it will say "Platform" under type.

* Please include a link to a game if possible!

Issue is within the game editor.

* If applicable, add screenshots to help explain your problem.

I've put it on Google Drive instead as it is a large animated GIF showing most of the steps above.
https://drive.google.com/open?id=1kUnyCEe52EUDh5nE-maHkbAkJTozpcz8

## Other details
* Include any OS/browser version/smartphone that you're using

Windows 8.1 laptop

* Which version of GDevelop are you using? The desktop app or the web-app?

GD Beta 72, desktop app

* Add any other context about the problem here.
--

**Comment by 4ian** [comment]
Thanks for reporting this, this is a regression. I'm fixing it and will upload a new version.

**Comment by 4ian** [comment]
Fixed in beta73 :)
