### ISSUE TITLE
Lock "base layer"

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1087]
## Description
When we delete all layers in scene, the all objects disappear, it's normal i know.
But a user on the forum reported that this was a bug because he didn't understand where all the objects were located.
In fact, the objects have not layer assigned after deletion of all layers.
To correct this you have to select each instances and put it back layer on by one by hand.

## Solution suggested
Lock the base layer in IDE to avoid misunderstandings.

**Comment by 4ian** [comment]
Right, the base layer should not be removal at all

**Comment by Bouh** [comment]
Fixed in my PR #1133
