### ISSUE TITLE
[Example]  Platformer with gamepads 2 players

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1097]
## Description
Updated the previous controller example with new extension gamepads, this new example support 2 controllers in same time !

[Platformer_multiplayer_coop.zip](https://github.com/4ian/GDevelop/files/3274329/Platformer_multiplayer_coop.zip)

**Comment by Bouh** [comment]
All is ok with it ?
I'm on [documentation ](http://wiki.compilgames.net/doku.php/fr/gdevelop5/draft-controllers#gamepads_controllers_extension) of this extension, i've listed the new events. What can i add more ?
atm wiki page is in franglais don't worrie i will split it in two page after your recommandations

**Comment by 4ian** [comment]
Sorry forgot about this, adding on my to-do list :)

**Comment by 4ian** [comment]
Adding this now, looks good! A couple of feedbacks:

- Beware of frenglish: "Axes Horizontal" => "Horizontal axis"
- No space before the double colon `Controller 1:`
- Beware of adjectives, they are before the noun: `Connected controllers:`

I know this can be hard to spot, but it's easy to fix and this can be a huge turn off for english readers ;)

**Comment by Bouh** [comment]
Here new version 
[Platformer_multiplayer_coop.zip](https://github.com/4ian/GDevelop/files/3298829/Platformer_multiplayer_coop.zip)

**Comment by 4ian** [comment]
Added for next version, thanks! :)
