### ISSUE TITLE
Touches stay active when closing exported iOS game

### ISSUE THREAD

**Issue by jonas-ey** [4ian/GDevelop#1104]
## Describe the bug
I use the event "The touch/cursor is on...." & "A new touch has started" to track touch events on buttons in my app. The issue only appears in the exported iOS app, not in android (cordova build). The problem is that touches remain active when the app is closed while a finger is still on the screen. When the app is continued it still triggers the event although no touch is made. This leads to problems especially with the iPhone X and above because buttons are constantly being pressed when swiping up to close the app ore swiping down to open control center. When you touch anywhere on the screen after launching the app again, it is recognised as touch on the button.

**Comment by Silver-Streak** [comment]
Hello! I am going through older issues to bring attention back to them or close them out if no longer needed.

Are you still experiencing this issue if you export in b113 or newer? 

I'll close out this issue if I receive confirmation that it is resolved, or if no response is received 30 days from this post.
