### ISSUE TITLE
Color Picker of Particle Emitter out of screen with low-res monitors

### ISSUE THREAD

**Issue by MercurioC** [4ian/GDevelop#1107]
## Describe the bug
Similar to this, not even sure if it's ok to open a new issue but could potentially expose other problems: https://github.com/4ian/GDevelop/issues/978
I'm using a couple of laptops working with GDevelop, one with a 1366x768 res and the other on a full 1080p but with scaling on 150%, and on both Color Picker inside Particle Emitter objects has showed these screen-estate related bugs:

1) First picker cuts out the color table but it's still usable using the Hex and RGB values...
<img width="960" alt="bug1" src="https://user-images.githubusercontent.com/17031164/59552070-8f0c9e00-8f82-11e9-84cc-2454aae704b8.PNG">

2) ...while the second one isn't. It's also not helping that colors can't be copy/pasted, so there's no way to change them in a definite way
<img width="960" alt="bug2" src="https://user-images.githubusercontent.com/17031164/59552090-bc594c00-8f82-11e9-9b16-ae0391bfc2c8.PNG">

3) Also scrolling down on the properties leaves the box in the same position.
<img width="960" alt="bug3" src="https://user-images.githubusercontent.com/17031164/59552174-ca5b9c80-8f83-11e9-9b65-327b291c96ca.PNG">

Tried on full 1080p and worked with no problems of course, maybe it would be more sensible to scale the picker independently from the resolution used? Even if I guess that would be a picky thing to work with...

## Other details
* Latest Win10 and GDbeta73
* 1920x1080 with 150% screen-scaling AND 1366x768

**Comment by Wend1go** [comment]
Since the colour picker in its current form has some issues (displayed off screen, clicks activate the underlying controls), I wonder if it would be better to display it modal as a screen filling popup right at the centre of the screen.

**Comment by 4ian** [comment]
That would indeed be maybe a better solution!
