### ISSUE TITLE
New Issue 

### ISSUE THREAD

**Issue by wild4n** [4ian/GDevelop#1109]
![image](https://user-images.githubusercontent.com/4935831/59553266-e465a100-8fbc-11e9-9fe4-9b988cdce239.png)

**Comment by 4ian** [comment]
Please add descriptions to your issues. This looks unrelated to GDevelop and more likely a graphics card bug. GDevelop is based on Chrome for the underlying rendering.

**Comment by wild4n** [comment]
sorry.
u can see,
in the picture costume cursor and bullet, it is not in accordance with.

**Comment by 4ian** [comment]
Closing without more details it's not possible to debug :/ Seems unrelated to GDevelop
