### ISSUE TITLE
Themes not applied to the Properties panel

### ISSUE THREAD

**Issue by piyushpalawat99** [4ian/GDevelop#1113]
## The bug
When the themes are switched on any tab other than the Scene editor, the Properties panel on the Scene editor does not switch to the theme.

## To Reproduce
1. Go to Events editor
2. Choose the light theme if you're currently on the dark theme or dark theme if you're on the light theme
3. Switch to the Scene tab

![Screenshot (25)](https://user-images.githubusercontent.com/31609516/59555755-ef2c3000-8fd4-11e9-969b-21449e359421.png)

![Screenshot (26)](https://user-images.githubusercontent.com/31609516/59555756-ef2c3000-8fd4-11e9-9900-d539bfffb59a.png)

## Other details
* Noticed the same results for Linux as well as Windows version.
* Using beta 73.

EDIT: The same problem persists for the Objects panel: it doesn't switch to the theme at all. While you can switch the Properties panel's theme by switching it on the Scene editor, there's no way to do it for the Objects editor.

**Comment by 4ian** [comment]
Closing and reopening the scene will "fix" this. Any help to fix this in GD is welcome.

**Comment by 4ian** [comment]
Closing as fixed since a bit of time :)
