### ISSUE TITLE
Obsolete API?

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1117]
A user on Discord reported errors/warnings when uploading his game on the Play Store.
Could this be specific to his project?
See screenshot.
![2_messages](https://user-images.githubusercontent.com/25978830/59777625-4e2fc480-92b5-11e9-94ed-dcb7145faf8a.png)

**Comment by 4ian** [comment]
I created a card for this here: https://trello.com/c/qq0GB2rA/310-update-android-sdk-version-of-build-service

This is just a warning so nothing blocking for now (hence closing) but the Cordova version will have to be updated.

**Comment by 4ian** [comment]
Thanks for reporting :)

**Comment by 4ian** [comment]
I'm gradually rolling out a new online build system: https://forum.gdevelop-app.com/t/updates-to-the-android-online-export/19813

In the next days, you might get the new or the old one. With the new, games will be compatible with the latest Play Store requirements.
Let me know if you have any problem with the export!
