### ISSUE TITLE
Bad color contrast on dark theme default button

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1120]
## Describe the bug
When you are in a dialog with a default button selection, in dark theme, the color contrast is not good. Hard to see the text. 

Please double check that the bug is not already reported in the issues list.

## To Reproduce
Open any project with an object.
Use the dark theme.
Open an object's properties.
<img width="825" alt="Screen Shot 2019-06-20 at 10 09 23 PM" src="https://user-images.githubusercontent.com/8691/59899071-3422de80-93a8-11e9-89f4-6a87d233c63d.png">

The word "apply" is hard to read. 

This was on a mac, using 5.0.0.beta73

**Comment by 4ian** [comment]
Yup it's not ideal - a slightly lighter blue could help.

**Comment by Bouh** [comment]
"Click to add an animation" too :\

**Comment by Bouh** [comment]
I guess this issue can be closed, it's fix in PR #1124

**Comment by 4ian** [comment]
Closing for now as it was updated, let's reopen it later if it's still an issue :)
