### ISSUE TITLE
Import images and other resources when outside project.

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1121]
## Description
Is your feature request **related to a problem**? Please describe.
The problem: When you try to add an image or other resource it tells you "warning this image is outside the project folder, it may not work if its moved!" 

![Screen Shot 2019-06-21 at 8 31 02 AM](https://user-images.githubusercontent.com/8691/59933804-f8673380-93fe-11e9-88ac-cf2117a7f922.png)

## Solution suggested
**Describe the solution**
The solution: Offer to "Would you like to copy this resource to the project folder before importing? YES NO" 
Hitting yes would 1) copy the resource over 2) import the resource

Please look at the Godot Engine as a source for ideas. They have a good way to deal with resources that is not dependent on the host OS.

**Comment by 4ian** [comment]
I'm not convinced this would give more clarity to users. How can we decide? 

> They have a good way to deal with resources that is not dependent on the host OS.

Can you be more a bit more specific? GDevelop resources are not dependent on the host OS - apart if a resource is on another drive (in which case there is no cross platform way to do it anyway).

**Comment by 4ian** [comment]
As this is not strictly a bug, but a usability/feature improvement, I would prefer to have the discussion in the forum for feature requests to keep the GitHub tidy with most important things.

**Comment by triptych** [comment]
Sure. I'll kick off a thread there. And I did file it as a feature request from the UI on the GitHub site.

**Comment by 4ian** [comment]
Fair enough, it's true that it's maybe not clear :/ But as possible I like when feature requests are first going through the forum so as to try to reach a consensus.

**Comment by 4ian** [comment]
As it was added for next version, I'll close this :) Thanks for taking the time to write about this and collect feedbacks.

In case of issue with this in the next version, open a new issue (though there should hopefully be not problem ;))
