### ISSUE TITLE
Panning loses selection

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1123]
## Describe the bug
Slightly annoying little bug in the scene editor. When you select a bunch of instances, then you pan the view - the selection is lost, so you must re-select them.

**Comment by 4ian** [comment]
Pan with space right?

**Comment by 4ian** [comment]
Fixed in 3b454616a571dc575991194973b926a029bf2ab7 :)

**Comment by blurymind** [comment]
Wow that was fast!

**Comment by 4ian** [comment]
Was not too complicated and that will improve user experience a lot :)
