### ISSUE TITLE
electronegativity security report

### ISSUE THREAD

**Issue by DaniellMesquita** [4ian/GDevelop#1125]
Vulnerabilities were pointed.
Please see the attached HTML file.
[gdevelop-security_report.html.zip](https://github.com/4ian/GDevelop/files/3318810/gdevelop-security_report.html.zip)

**Comment by DaniellMesquita** [comment]
@4ian

**Comment by 4ian** [comment]
Can you go a bit beyong just reporting the results of this tool and actually point out if there is anything that looks really suspicious?
From what I've seen, most things seems to be noise.
