### ISSUE TITLE
HTML visible in patch note "What's new?"

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1128]
## Describe the bug
HTML is visible in "What's new?" tab

## To Reproduce
1. Go to 'Help'
2. Click on 'About GDevelop'
3. Click on "What's new?"

![image](https://user-images.githubusercontent.com/1670670/60059932-cdc2f680-96ee-11e9-9384-809d546e3a5b.png)

## Other details
W10

**Comment by 4ian** [comment]
Right, seems supported only on GitHub. Should be fixed soon :)
