### ISSUE TITLE
Strange field in Physics engine behavior in other language than English 

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1132]
## Describe the bug
A strange fields appear in Physic engine behavior (not Physic 2.0) ,
This appear only when the language is different than english.
And the order of this fields change. (It's very ugly, my suggestion is to sort it by declaration order in the extension file😇)

## To Reproduce
1. Add a object with physics behavior
2. Change the language of GD in french or spannish
3. Go back in behavior

Left spannish, middle english, right french.
![image](https://user-images.githubusercontent.com/1670670/60396654-9b792500-9b44-11e9-953a-b1c0432e1b23.png)

## Other details
* GD5 b75, W10

**Comment by 4ian** [comment]
Right, it's a "magic property" that should not be translated (mostly deprecated and unused). Fixed in 90f082847400ec0ee9625448ddd65931072761c8, thanks for reporting!
