### ISSUE TITLE
Filter objects by tags and add object on scene is not working as attend

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1139]
## Describe the bug
When we add a tag to an object, and filter the list of objects by this tag, we have our object, but when we add it to the scene it is not the one intended.

(It takes index from entire object list and not the index from the list once filtered)
Thank to CorianderGames for catch this bug

## To Reproduce
1. Add two object
2. Add 1 tag on second object
3. Filter list, and add object on scene
4. The first object is added instead second

## Other details
* GD5 b75
* W10 electron and web

**Comment by 4ian** [comment]
Yup, both the re-ordering of objects and the drag'n'drop on the scene were completely messed up when the list was filtered (either with tags, search or both).
Should be good in all situations now! Fixed in 01b854b1b93d432762eb46d91b699ecd68926119

**Comment by Bouh** [comment]
About filter(), when we search a new extension, search "konami" witk k in lower case, it's working on electron, but not on web.

**Comment by 4ian** [comment]
Seems not to be working for me on both? Anyway I made search case insensitive so that's not a problem anymore, in cb56364539a4c414252ebe347d0f328ab3b4ddca.
