### ISSUE TITLE
New example: Draggable Platforms

### ISSUE THREAD

**Issue by ExtemTheHedgehog** [4ian/GDevelop#1140]
Hi there, GDevelop Team!

I just wanted to ask if it was okay if I submitted a new example with mostly behaviors in the code. I call the version that I'm submitting "Draggy Cloud" but you can rename it if you want. The object of the game is to use the draggable Cloud sprite to your advantage to platform your way across a world of floating grass. You play as a black brick/block/cube/square that has the "platformer character" behavior, and the cloud has both the "draggable object" behavior and the "platform" behavior. The endings for both winning and losing are pretty silly, and you should try them out for yourselves!
[Draggy Cloud.zip](https://github.com/4ian/GDevelop/files/3352052/Draggy.Cloud.zip)

I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by 4ian** [comment]
Thanks for submitting this :)
A few remarks:
* No need for the for each events
* Images are missing, you should put all of them in the project folder. (next version will copy them for you, for now check out the resources you'll have warnings in yellow).
* We would need better art. Unfortunately, examples with art that looks too "home made" are influencing quite badly the perception of the quality of GDevelop on new users.

**Comment by ExtemTheHedgehog** [comment]
Thanks for the help, 4ian! I'll do better next time! :)

**Comment by 4ian** [comment]
Closing for now to tidy up the list of issues, please re-open if you have an updated version :)
