### ISSUE TITLE
"Failed to compile" when launching GDevelop on Linux

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1141]
## Describe the bug
Linux version seems to have broken after the react upgrade.
When you try to run gd5 on Linux in dev mode, you get this crash and it fails to start:

![eventstreebuglinuxwebpack](https://user-images.githubusercontent.com/6495061/60630324-92f94680-9df1-11e9-9a29-b48649073fc1.jpg)

Another thing I notice is that Linux seems to be more sensitive about the casing of names in its gitgnore file, as a result the file doesn't work on piskel's folder and you get all the pixel stuff included in your changes. The folder is named with lowercase p and in gitignore  it is capital. 
I could look into this tomorrow and include both fixes in one pr?

The bug is in the import on line 27
`import 'react-sortable-tree/style.css';`

**Comment by blurymind** [comment]
strange, the style.css file doesnt seem to exist in the node_modules/react-sortable-tree folder at all.

**Comment by 4ian** [comment]
Have you launched `npm install`? Looks like outdated dependencies.

**Comment by blurymind** [comment]
I used yarn this time

**Comment by 4ian** [comment]
Do `less node_modules/react-sortable-tree/CHANGELOG.md` in `newIDE/app` and tell me if version shown in the file is properly `2.6.2`? This is the one put in package.json and working for me with yarn.
This is also the one that I find in yarn.lock.

Have you run `yarn` to update dependencies?

**Comment by blurymind** [comment]
I ran yarn on both app and electron app. Will need to check tonight

**Comment by 4ian** [comment]
To be sure remove node_modules folder entirely in newIDE/app before relaunching yarn and yarn start.

**Comment by Wend1go** [comment]
I had the same issue with `react-sortable-tree/style.css` today after pulling changes. Deleting `node_modules` and running `npm install` again solved it for me.

**Comment by 4ian** [comment]
Good to know! Might be worth ugprading yarn if you have it or npm (if it is signaling there is an update available) because in theory they should take care of this.

**Comment by blurymind** [comment]
using npm install instead of yarn fixes it. Will close this now :)

should I fix the gitignore issue in a separate pr?

**Comment by 4ian** [comment]
Yes please for the gitignore :)
