### ISSUE TITLE
'Change the size of the window' does not change the window size, only the resolution

### ISSUE THREAD

**Issue by GuestUser834** [4ian/GDevelop#1152]
## Describe the bug
As the title says, the 'Change the size of the window' action changes the resolution of the game but not the window itself. This is the case for shrinking and for enlarging the game window.
Whether the option to 'use this size as the default size for new scene cameras' is set to 'Yes' or to 'No' this is still a problem. (The 'Yes' and 'No' buttons do affect the games viewable area just not the actual window size.) Exported projects have this issue also.
I have talked to others who claim to have the same issue. 

## To Reproduce
1. Go to the 'EVENTS' tab for your scene.
2. Click on 'Add new empty event'
3. Click on 'Add condition' and select a condition such as 'Trigger once' or 'At the beginning
    of scene'
4. Click on 'Add action' and select 'Change the size of the window'
5. Set the width and height to different values to those in the properties panel
6. Click on the 'Launch a preview of the scene' button
7. The game window will stay the same size as before, just with a different resolution

## Other details
* Windows 10
* desktop app

**Comment by 4ian** [comment]
New actions available now are solving this :)
