### ISSUE TITLE
No thumbnail image preview on Linux when add sprites

### ISSUE THREAD

**Issue by Pollito001** [4ian/GDevelop#1156]
When i trying to add a sprite just show icons instead of thumbnails preview
![No thumbnails](https://user-images.githubusercontent.com/4990486/61570261-726bf600-aa59-11e9-98dc-0d93b3669871.png)

**Comment by Wend1go** [comment]
The 'File Open' dialog is provided by the operating system. Manjaros xfce based dialog is prettz basic. On my linux mint machine I get a preview when marking an image, not perfect but better than nothing. KDE has the best support for image previews that I have seen so far, with a preview of each image in the list at once. You can even scale the size of the images inside the open file dialog.

**Comment by 4ian** [comment]
Thanks @wend1go for the in depth explanation :) Can confirm this is operating system related and not something GDevelop can change or influence.
