### ISSUE TITLE
Overflowing text outline 

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1158]
## Describe the bug
It seems that the text outline feature has a minor bug with some letters.
Here, I'm using the default font (black) and a 5 px white outline.
![image](https://user-images.githubusercontent.com/25978830/61634598-edb7ec80-ac91-11e9-95eb-c96e0e18771d.png)

GD5b75

**Comment by Bouh** [comment]
This is an pixiJS problem, but it's not fix in [last v5.1.0 ](https://github.com/pixijs/pixi.js/releases)
https://jsfiddle.net/3nrk51js/
This issue need to be report on pixi repo

**Comment by Bouh** [comment]
[A anwser from pixiJS issue ](https://github.com/pixijs/pixi.js/pull/5947#issuecomment-516947889)
> @Bouh That's related to your settings. Miter limit has to be a greater than zero value, zero itself is ignored by the canvas API. Change that (3 seems to look good), or use a different lineJoin type.

**Miter limit** is a parameters for outline in PixiJS

**Comment by Wend1go** [comment]
I'll look into this at the weekend.

**Comment by 4ian** [comment]
Thanks keep me updated with your findings :)

**Comment by Wend1go** [comment]
I'll test different miter values on different sized text objects. I'd really like to use a hard coded value for this so we don't need to clutter the actions list with stuff that people don't understand at first sight (like the padding action).

**Comment by 4ian** [comment]
Yes we almost certainly want to use a value that works for all/very large majority of texts

**Comment by Wend1go** [comment]
So it looks like the `miterLimit` is adding some kind of bevel to the letters:
![grafik](https://user-images.githubusercontent.com/7413059/62410279-f8ed0f80-b5e3-11e9-934a-8e316577dbe4.png)
![grafik](https://user-images.githubusercontent.com/7413059/62410315-4ec1b780-b5e4-11e9-8855-b9a057db6f9a.png)

A value of "3" like suggested in the pixijs issue indeed seems to work well.
I'll do some more testing with different font files and create a PR.

**Comment by Wend1go** [comment]
The issue should be solved with #1180 (or at least be greatly reduces)
Please close this issue if you are fine with it.

**Comment by PascalLadalle** [comment]
Looks good to me
![image](https://user-images.githubusercontent.com/25978830/62662411-45ce3e80-b974-11e9-8d38-fd9a1e19ac6c.png)
Thanks
