### ISSUE TITLE
Modify Text Var & Function Example

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1161]
For the “Modify Text” action with variable conditions. 

The example consists of a text button menu using instances of the same text object with mouse-over effects inside a function. It's an ideal method for those that prefer to have fewer objects in their list plus want an easier/faster way of changing both the text and most styles through events. Another possible use is for a GUI that has several text objects which need to change frequently such as score, coins, inventory, etc.

I hope it helps someone. 

Please feel free to suggest improvements; maybe needs more comments or further explanation?

http://www.mediafire.com/file/4dqtlmyqhcomce6/Dynamic_Text_Menu_Example.zip/file

Note: 
The text specified via "modify text" isn't visible until preview. 
It will say whatever may be in the text object (in the example, it's 'menu item').

**Comment by Phenomena3** [comment]
Are there problems with this that need to be resolved or something before it will be considered for adding to the website? I noticed that the 'modify text' portion on the wiki page was removed as well, although it is a feature under the text object.

**Comment by 4ian** [comment]
I just looked at it now. It's a good start, thanks for submitting it :) Would be cool if you could take a look at these:
* Maybe add a different image in each screen so that it's obvious that we have changed to a new screen - otherwise we have to look at the title bar which is not obvious on mobile phones.
* You have events with a condition "beginning of the scene" without an action, can you remove them?
* In the function, you have empty comments at the end, can you remove them?
* The colors, purple in the background, dark blue, cyan and white are all very different and I don't think they play too good together. Can we use some colors that are bit nicer on the eye? ;) 
* In the action description => "Actions to modify menu text and styles.". Typo it's action. But also, prefer not saying it's an action. We already know that :) Just tell what it's doing "Handle the interaction with the menu items."
* The action sentence should also reflect this: "Handle the interactions with the menu using _PARAM1_".

With this, I think we'll have a good example! :)

**Comment by Phenomena3** [comment]
Great! Thank you for the feedback, I can indeed make these changes and will post an updated link in my next comment. 

Just a few thoughts...

> * Maybe add a different image in each screen so that it's obvious that we have changed to a new screen - otherwise we have to look at the title bar which is not obvious on mobile phones. You have events with a condition "beginning of the scene" without an action, can you remove them?

Yes, I can do that. 

* I'd like to point out that the title bar isn't the only clue that you've changed scenes...there is an 'active' state on the menu link. I don't know how that looks for mobile users and evidently it didn't convey the intended concept so the image is a good idea, thank you. 

* Also the first event wasn't supposed to be empty. I'm not sure why they are as they were all supposed to change the window title. 

That brings me to the color scheme:

> * The colors, purple in the background, dark blue, cyan and white are all very different and I don't think they play too good together. Can we use some colors that are bit nicer on the eye? ;)

* The background was a shade of blue, but I suppose it's close to the edge of purple... 
* I think, being a neutral color, white gets along fine with most others. 
** Personally, I like the glow around the hovered white text, it's a little intense, but should only be visible on hover. 
* In looking at the old colors, they actually seem too much alike for their purpose as different link states. 
** Perhaps an accent shade from the hot end of the spectrum will balance out the cold of white and blue.

With all of that said, choosing something that is nicer on the eye is going to be very subjective. Everyone perceives color differently and we all have our favorites. If you have a specific combination in mind that you prefer in examples, I can work with that. Otherwise, I can't promise you'll like another selection any better, even if a harmonious palette is used and unfortunately, time is a bit short for guessing.  

> * In the function, you have empty comments at the end, can you remove them?

* Yes. They're there because I found the bottom of the editor to be a bit constricting to work in, then I forgot about them.  Please see someone else's suggestion from the forum about adding some white space after the last event here:

https://forum.gdevelop-app.com/t/event-editor-scrolling/19152

**Comment by 4ian** [comment]
> I'd like to point out that the title bar isn't the only clue that you've changed scenes...there is an 'active' state on the menu link.

Yep, my idea is that an image will help understand that we've actually changed to another scene.

> If you have a specific combination in mind that you prefer in examples, I can work with that

Let's go with simpler black/white colors for example, and a blue for the selected option. You can keep the glow/shadow as it's a good example of using these actions :)

>  Please see someone else's suggestion from the forum about adding some white space after the last event here:

Yeah that would definitely be a welcome improvement.

Thanks for your work on this! :)

**Comment by Phenomena3** [comment]
Sweet, thanks! :)

Okay, so I went with a very dark - almost black - grey on the background to preserve the integrity of both glow on hover and shadow on active, which is now a light blue that I think looks nice with the background. Passive links are plain white with no special effects. 

I threw in some free assets of boxes that I had on hand since they are light on size and all different designs. I figured they'd be fine as long as you can tell it's another scene. All of the other requested changes have been made too.

Here's the new zip, let me know if anything is amiss.

http://www.mediafire.com/file/4dqtlmyqhcomce6/Dynamic_Text_Menu_Example.zip/file

**Comment by Phenomena3** [comment]
Here's another version from my previous post.

- I made the background pure black, to show the glow.
- Changed the shadow color on the active link so it's visible against black, but still subtle.
- Swapped the box images with platform character assets.

http://www.mediafire.com/file/woem6z9jtpj3t75/Dynamic_Text_Menu_Example_-_3.zip/file

**Comment by 4ian** [comment]
Nice! I added the latest one to the next version (4388e073e167eedc624a12bdba218266e0c34e0f). Will be useful for people exploring the usage of functions and text effects :) 

Thanks for your time spent on this!
