### ISSUE TITLE
New instruction editor search bar

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1173]
## Describe the bug
When we search on new searchbar in new instruction editor, window is too lower.

Please double check that the bug is not already reported in the issues list.
![image](https://user-images.githubusercontent.com/1670670/62172230-e055ce80-b331-11e9-9f60-7e02a561f516.png)

## To Reproduce
1. Search "Mouse"

## Other details
W10, B76

**Comment by 4ian** [comment]
This happen with empty objects right? Could only reproduce it on an empty again. I think I have to force the window to be always as tall as possible

**Comment by 4ian** [comment]
Fixed in 543a8e559b5e4dc88f40ee30c12bf949d6cffd2b
