### ISSUE TITLE
Missing action in new instruction editor

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1176]
## Describe the bug
The action "Move the object to a position" in Pathfinding categorie is missing.
Maybe others conditions/actions can be missing too.

## To Reproduce
1. Open the example basic AI with pathfiding
2. use search bar for found the only event with "Perso.X() + Random(60)"
3. Open the action
4. Nothing is focus in list, we can't see the action.
5. We can see only if we search "move"

## Other details
W10 B76

**Comment by Wend1go** [comment]
"Modify the Text" of Text Objects is also missing.
It can be found when using the filter at the op though.

**Comment by 4ian** [comment]
Thanks for reporting this, I missed this! That could be actions that don't have a group name, I'll check.

**Comment by 4ian** [comment]
Fixed in c78ecd27d8b6a6b573e341b9c78dab3252ac8e61 :)
