### ISSUE TITLE
Please Add Folders to keep organized large project

### ISSUE THREAD

**Issue by wild4n** [4ian/GDevelop#1177]
![img1_5](https://user-images.githubusercontent.com/4935831/62224839-8280bf80-b3e1-11e9-9e83-26834ffecafc.png)

like this : )

**Comment by 4ian** [comment]
Feature request already here: https://trello.com/c/Z2fn5lMs/201-allow-to-add-tags-or-folders-to-scenes-external-layouts-and-external-events :) I've renamed it so it's clearer
