### ISSUE TITLE
Nothing happen when add sprites animation

### ISSUE THREAD

**Issue by nice9uy** [4ian/GDevelop#1182]
## Describe the bug
I download GDevelop 5.0.0-beta75, it seem all working properly. And then when i try to update the sotware, After that i can not add some sprites of animation and my computer more working extra, i mean my computer more hot when i tries to update on this software.

![111](https://user-images.githubusercontent.com/25494182/62418419-969f1800-b692-11e9-8af4-5aa9556be21f.PNG)

## To Reproduce
1. New Object -> Click to add animation -> Select image
2. Image can not be add.

**Comment by 4ian** [comment]
This is indeed a bug, only happening if your image is outside of the project folder. To work around this before the new version is out with a fix, copy the image in the folder of your game.

**Comment by 4ian** [comment]
Fixed in 96e1eeee7bd2f0352c015807b0651a5d301c41f8
(This is related to this bug https://github.com/lingui/js-lingui/issues/437)
