### ISSUE TITLE
Can't make ads appear in my game

### ISSUE THREAD

**Issue by Ardeye** [4ian/GDevelop#1192]
## Describe the bug
Ads don't appear in my game.

## To Reproduce
1. Create reward video or banner ad on admob.com
2. Insert app id into the properties, add unit id for some action.
3. Export the game to apk.
4. Start the game on a mobile device and trigger the action.
5. Ads don't appear.

## Other details
* GDevelop Beta79 for linux. Android 9 Snapdragon 710.
* Tried only with test mode enabled. Heard that google can ban you otherwise.
* Waited for 2+ weeks after creating ads on admob.com.

**Comment by 4ian** [comment]
Other games have been able to display ads so this looks like a misconfiguration on your side or at least unlikely to be a bug.
Can you quickly try without test mode? Have you double check the app id and add unit? No extra space/extra quote or something like this? Can you show a screenshot of your events?

**Comment by Ardeye** [comment]
Thank you for reply!
1. Instructions for a video ad unit and an app id.

![1](https://user-images.githubusercontent.com/34892218/63144251-ba4f5000-bffa-11e9-8533-ce8dacf99bd7.png)

2. Admob ad page.
![2](https://user-images.githubusercontent.com/34892218/63144255-bde2d700-bffa-11e9-82ce-1e4473dedab9.png)

3. App Id.
![3](https://user-images.githubusercontent.com/34892218/63144257-c2a78b00-bffa-11e9-9889-e0304befbaec.png)

4. Unit Id.
![4](https://user-images.githubusercontent.com/34892218/63144260-c5a27b80-bffa-11e9-9882-d8dcea20d00b.png)

5. Code. Added beep sound to test. When life goes to 0 it actually beeps but there's no ad.
![5](https://user-images.githubusercontent.com/34892218/63144262-c804d580-bffa-11e9-8d3e-022f377f51ac.png)

6. Screenshot from my mobile device. Test mode is off. When you're out of lives and click to play, the ad should appear instead of loading the play scene. No ad.
![6](https://user-images.githubusercontent.com/34892218/63144266-caffc600-bffa-11e9-914d-690502ad5c94.png)

**Comment by Bouh** [comment]
If you have a apk build i can test on my phone

**Comment by 4ian** [comment]
This all looks correct... @Bouh you've done some work with ads, maybe you would see if there is an issue?

Have you tried in test and without test mode?

**Comment by Ardeye** [comment]
> If you have a apk build i can test on my phone

Thanks for your proposal.
Also added bottom banner to test. This one has test mode enabled for both ads.

https://s3-eu-west-1.amazonaws.com/gd-build/7d10f5b7-40f1-4393-bfcf-e364ba311f92/game.apk

**Comment by Bouh** [comment]
I've decompiled you apk and insert your keys in the example for AdMob and nothing happend.
And this example is working with other ID so problem come from your google admob account i guess.

**Comment by Ardeye** [comment]
> I've decompiled your .apk and insert keys in the AdMob example and nothing happend...
> And this example is working with other keys. Then problem come from your google admob account i guess.

Thank you. I just registered my account on admob and created these ads nearly 3 weeks ago. Nothing else.

**Comment by Bouh** [comment]
I've seen nothing wrong in code or data when event are called. No extra space or extra quote.

You can try with my IDs. i use it only for tests, theses key are keys ID for production so don't use it in your app otherwise I would earn the income from the ads from your game^^

My IDs work well in AdMob example.

App ID 
`ca-app-pub-9428369419901842~1727526901` 
Banner 
`ca-app-pub-9428369419901842/2919121318`
Inter
`ca-app-pub-9428369419901842/8447779230`
Video with reward 
`ca-app-pub-9428369419901842/6935209400`

**Comment by Ardeye** [comment]
> You can try with my IDs.

Yeah, cool. Everything works with your ids. Thank you again. Idk though what should I do now. Just wait or try to contact tech support on admob. Can't find how to contact support directly

**Comment by Ardeye** [comment]
Actually I suppose I haven't filled some information on my admob account. Hope ads will start to appear tomorrow :)

**Comment by 4ian** [comment]
Hope it will work then :) Would be nice if you can screenshot (and hide
your personal information) the page where you've been missing information.
This way we could add it to the wiki as a warning so that it can hopefully
avoid the same issue to other users :)

**Comment by Ardeye** [comment]
> Would be nice if you can screenshot

I somehow managed not to fill in the Payments page :) 
![1](https://user-images.githubusercontent.com/34892218/63206742-d4ecfc00-c0c2-11e9-9298-8677be6d31f0.png)

After that I went to a Home page and got a notification that my account is being approved. Something about 4 hours later ads started to appear in the game. And the notification turned to this.
![2](https://user-images.githubusercontent.com/34892218/63206760-1da4b500-c0c3-11e9-9832-57428f9168a8.png)

GDevelop is more intuitive than AdMob) Thank you all for helping me out!

**Comment by 4ian** [comment]
I've added a section "Setup Payments in Admob" in http://wiki.compilgames.net/doku.php/gdevelop5/all-features/admob

Thanks for the follow up :)
