### ISSUE TITLE
"Fill Opacity" on shaper painter object stuck at 0

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1195]
## Describe the bug
In properties for shape painter object, i can't set "Fill opacity", value is always reset to 0.

# To Reproduce
1. Create Shape painter object
2. Try to change value of  "Fill opacity"
3. When focus is lost value is reset to 0

## Other details
* bug on b79, and actual dev build from master, but not on b75

**Comment by Jose-Moreno** [comment]
Can confirm on Windows 7 Ultimate.

After creation the fill opacity is initially set to 255, but selecting any color and clicking anywhere on the modal window resets the opacity to 0. Even changing other values will reset the opacity to 0.

**Comment by 4ian** [comment]
Thanks for reporting this, fixed in 6b534adb98c2df1720f4646dc943ae5b2130e9d3
For now you'll either have to work around this using events or editing the .json file of your project manually.
