### ISSUE TITLE
Offset when search in event in Extension/function tab

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1197]
## Describe the bug
When i search in event search fields have a mega offset at bottom see screen : 

![image](https://user-images.githubusercontent.com/1670670/63212483-6d0bd500-c105-11e9-8d61-a7b901ca914a.png)

Webapp haven't offset, but search fields can be displayed when no events are present.

![image](https://user-images.githubusercontent.com/1670670/63212519-00dda100-c106-11e9-9632-83a29dd07df8.png)

## Other details
* B79 and lower

**Comment by Bouh** [comment]
This working better now, i close.

**Comment by 4ian** [comment]
👍
