### ISSUE TITLE
Doubled paste of multiple events

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1199]
## To Reproduce
Steps to reproduce the issue:
1. Select two events in the events sheet, using the Shift key.
2. Right-click and Copy.
3. Right-click and Paste.
4. You now have six events (instead of four).

Win10
GD5b79

**Comment by 4ian** [comment]
The number of events by itself is fine: if you're selecting multiple events, you should get the events pasted at these multiple locations. (much like when you're editing in a text editor like Sublime Text or Visual Studio Code: if you're selecting multiple words, you have multiple carets).

But I tried and seems that every was pasted at the position of the first event selected, which is wrong :/

**Comment by PascalLadalle** [comment]
Oh I see... I didn't know about that. 
Indeed, the events get pasted as many times as I have lines selected before pasting.
Not sure I'm gonna need that feature one day, but now I know how to avoid it, at least! 😅 
And yes, I noticed something odd about the position of the pasted events, but it seemed irrelevant at the time.

**Comment by Bouh** [comment]
I start with it : 

![image](https://user-images.githubusercontent.com/1670670/65584587-66347580-df81-11e9-88c6-1c72c317783a.png)



I select all from top to bottom, copy and paste, and i've this : 
![image](https://user-images.githubusercontent.com/1670670/65584561-5cab0d80-df81-11e9-8f9e-da32b8fb6e91.png)
Number of events are false. 

When we expect 
![image](https://user-images.githubusercontent.com/1670670/65584697-91b76000-df81-11e9-8670-86329497c079.png)

If we select from bottom to top the order of events move again : 
![image](https://user-images.githubusercontent.com/1670670/65584844-d3e0a180-df81-11e9-86f3-f635fde268eb.png)

**Comment by Bouh** [comment]
We have also a **crash** sometimes when we copy and paste, and undo and redo, focus is missing and after that if we paste eventsheet freeze, sometimes he crash, and sometimes GD freeze and need to be killed manually.
I've tryed to reproduce bug but seem a bit random :|

Open *Admob* example, open *Interstitials* events.
Select this two events : 
![image](https://user-images.githubusercontent.com/1670670/65586191-068b9980-df84-11e9-9188-944ad4952d01.png)

Copy and paste
CTRL+Z
CTRL+Y
(Repeat x times)
CTRL+V

--------

I was thinking about a log report for crashes, why don't we have a list of the user's last actions instead?
The position of the mouse in the window, when mouse is pressed/released, the keyboard also.
And everything would be listed in a file that you could read and emulate the actions in a development build.

I guess record the 50 last input would be enought, all recorded in a local file and sended only if the user wish when crash windows appear.
Also we need to keep this file easyly findable in the finder/explorer of OS.

**Comment by tristanbob** [comment]
This problem is still around, and I expect it happens often, and to most users.  Here is some more info on what triggers this bug:

### How to Cause problem:

- Select 2 or more events
- Initiate copy (right-click "Copy" OR Control-C)
- **While all the events are still selected**, initiate Paste (right-click "Paste" OR Control-V)
- Too many new events (n^2) will be created (and not in the original order)
-- 2 copied events = 4 new events
-- 3 copied events = 9 new events
-- 4 copied events = 16 new events

### Work-around for the problem:

- Select 2 or more events
- Initiate copy (right-click "Copy" OR Control-C)
- **Create a new blank event**
- **Highlight new event**
- **Initiate Paste (right-click "Paste" OR Control-V)**

However, this work-around **doesn't fix the ordering problem**.  It seems that events are created in the order they are selected.

**Comment by PascalLadalle** [comment]
@tristanbob As explained above, pasting creates a copy of the clipboard **for each highlighted line**.
So, if you select and copy 4 events and want to paste one copy only, you need to deselect them before pasting.
This seems to be a feature developers are used to.
The bug report was kept open for the other issues (paste order and crash)

**Comment by 4ian** [comment]
This multiple paste is a "feature" but I agree it seems more confusing than anything else. Ordering should definitely be somehow fixed.

**Comment by Silver-Streak** [comment]
I believe this entire behavior is changed with 5.1.157. I can no longer reproduce it. Does the newest version solved this for you, @PascalLadalle

**Comment by Bouh** [comment]
Fixed in https://github.com/4ian/GDevelop/releases/tag/v5.1.157
