### ISSUE TITLE
javascript API gdjs.evtTools.object.twoListsTest not working as expected

### ISSUE THREAD

**Issue by andineck** [4ian/GDevelop#1202]
## Describe the bug
I would like to write a custom condition function that checks two lists and found the `twoListTest` function I want to make use of in my function. I provide two lists, but the comparison does not take place.

## To Reproduce

my function:
```js
const objectsA = eventsFunctionContext.getObjects('objectsA');
const objectsB = eventsFunctionContext.getObjects('objectsB');
eventsFunctionContext.returnValue = gdjs.evtTools.object.twoListsTest(gdjs.RuntimeObject.collisionTest, objectsA, objectsB, false);
```
Note: I used gdjs.RuntimeObject.collisionTest as predicate just for simplicity.

`objectsA` and `objectsB` are at runtime both Arrays with `SpriteRuntimeObject`s.

When I debug the `twoListsTest` function, I see the Arrays in `objectsLists1`, but not in the converted `objects1Lists` (length === 0), and therefore no comparison takes place.

http://4ian.github.io/GD-Documentation/GDJS%20Runtime%20Documentation/events-tools_objecttools.js.html#line57

## Other details
I might do something wrong here, but I can't figure it out. 
In order to limit the selected objects in the further conditions and actions, do I have to set the `pick` attribute to true on the selected ones?

**Comment by 4ian** [comment]
This is not working because `gdjs.evtTools.object.twoListsTest` is expecting its arguments to be list**s** of objects, while for each one you provided a list of objects. See the difference? No, it's normal ^^

This is subtle and not greatly documented for now I must admit - ideally I'll add some JSDoc so that you have type information.

These "lists of objects" are stored using `Hashtable`, a helper to store a map of key/values. This is done because the events can actually be applied not only on a single list of objects, but on multiple lists of objects (like when you're running events on a group of objects).

```
const objectsA = eventsFunctionContext.getObjects('objectsA');
const objectsALists = Hashtable.newFrom({ObjectA: objectsA});
const objectsB = eventsFunctionContext.getObjects('objectsB');
const objectsBLists = Hashtable.newFrom({ObjectB: objectsB});
eventsFunctionContext.returnValue = gdjs.evtTools.object.twoListsTest(gdjs.RuntimeObject.collisionTest, objectsALists, objectsBLists, false);

// objectsALists and objectsBLists will be filtered to contain only the objects satisfying the predicate
```

> In order to limit the selected objects in the further conditions and actions, do I have to set the pick attribute to true on the selected ones?

No, ignore the pick attribute it's an implementation detail (I should have named it with an underscore and a longer name to discourage its use) - you can disregard it :)

**Comment by andineck** [comment]
@4ian Thank you very much for the detailed explanation. With your code the predicate is now applied correctly. 

There is only one thing: the filtering of the objectLists does not seem to work properly. 
When I put this code in a Condition function, the subsequent events take all of the objects into account, even though only one of the objects is colliding:

<img width="383" alt="filtering" src="https://user-images.githubusercontent.com/697037/63462694-c7859800-c45b-11e9-8687-eea144bc40a9.png">

In this example the **cards** (`objectsBLists`) only are filtered, when the second line is entered.

**Comment by 4ian** [comment]
The answer is that GDevelop does not expect your function to do any filtering 😢 The `.getObjects` will always return a new list of objects, so filtering this list won't filter the list actually used in GDevelop events.

I can think about a way to make this possible. Though I would like to see if what you're doing could not instead be done with twoListsTest, but instead using a condition inside a custom behavior (create a new behavior, attach it to your Cards, then add a condition function to it. Pass to the function a parameter that is the Player. Finally, in the function, add some JS code that check if your card (called "Object" as a convention: `eventsFunctionContext.getObjects("Object")[0]`) is in collision with the player: `eventsFunctionContext.getObjects("Player")[0]` (or iterate on the array if you're expecting 0 or more "Player" objects). return true or false and GDevelop will filter the cards for which the condition is returning false.

Hope this help. To be fully able to filter lists like a "real" condition written fully in JavaScript (and not embedded in a function and a JS event), I will need to add a new function `getObjectsLists` to `eventsFunctionContext`. The advantage is that you'll be able to directly pass them to twoListsTest, and so filtering will work.

This need changes in code generation so would only work in a new version of GD though. Let me know if a behavior could work instead for you.

**Comment by andineck** [comment]
I guess it could be done with a custom behaviour and condition function. I must admit, I am new to GDevelop (but not to Javascript) and I have to get into this thinking. I will give it a try. 

*What I want to do is having a Player (whose position I can control via websockets), and then navigate this player over different Objects. Only when the Player stays on the same Object for a while, it should trigger an event. I use this for a two dimensional augmented reality prototype.*

On the other side, I think if you could add the new function `getObjectsLists` and with it add the ability to do filtering in Javascript (that has an effect on the other events), this would be great. It would also make it easier to deal with the ObjectLists (Hasthtable).

**Comment by 4ian** [comment]
I'm adding `getObjectsLists`. In the meantime, you can "hack" and access to the lists of objects (the Hashtables) by using `eventsFunctionContext._objectsMap["ObjectNameInTheParameter"]` - replacing `ObjectNameInTheParameter` by the name you actually put in the parameters of your function :)

Should work, let me know if you give it a try. Note that this will need to be updated to use `getObjectsLists` later. Also be sure to make your code defensive and check for it against null/undefined.

**Comment by andineck** [comment]
awesome, thanks for adding `getObjectsLists` and mentioning the hack! The "hack" works like a charm :-) (for now)

**Comment by 4ian** [comment]
Great! For reference, I added here an example of how to do other operations:

```
var objectsLists = eventsFunctionContext.getObjectsLists("Obj2");

// or with the current version:
var objectsLists = eventsFunctionContext._objectsMap["Obj2"];

// Here I manipulate directly the list of objects called "Platform".
// Note that this is DANGEROUS because I know the name "Platform"
// (changing the name of the object will break this and crash the game).
objectsLists.get("Platform").splice(2, 5); // Removing 5 objects from position 2.

// There might be more than one object list, so you may want to query them:
var names = [];
objectsLists.keys(names);
for(var i = 0;i<names.length;++i) {
    // Do something with the list of objects:
    var objectsList = objectsLists.get(names[i]);
    objectsList.remove(2);
}

// The BEST though is to avoid manipulating these Hashtable at all - they might be changed later. Instead, pass them directly to `twoListsTest` or use `getObjects`

eventsFunctionContext.returnValue = true;
```

I took the time to make an example in case it's interesting someone: [Manipulating object hashtables.zip](https://github.com/4ian/GDevelop/files/3527412/Manipulating.object.hashtables.zip) (and also to verify that getObjectsLists is working ;))

**Comment by 4ian** [comment]
Added `getObjectsList` in 13467a9a326a96021bb842179d1bd753d589134d :)
