### ISSUE TITLE
Hi great framework!

### ISSUE THREAD

**Issue by inglesuniversal** [4ian/GDevelop#1209]
Do you have any drag and drop matching game sample?

I need one for educational purposes

Regards

**Comment by 4ian** [comment]
Hi, thanks :)

Let's keep though for actual reproducible bugs, please ask instead on the https://forum.gdevelop-app.com/ that is made for community discussions (or on the Discord).

There is "pairs" example and a Draggable behavior, you can try to leverage both but not sure there is something exactly what you want, you'll have to build it.
