### ISSUE TITLE
Can't import assets in the project

### ISSUE THREAD

**Issue by JanSeW** [4ian/GDevelop#1210]
## Describe the bug
When I try to import an audio file, sprite or something else, the import fails.
The selection dialog opens, I select the corresponding audio file, but nothing happens afterwards, except that the selection menu closes again.
This can be seen in the following clip: 
https://peertube.abi19.eu/videos/watch/5ddd8474-9859-46b4-ad8b-e828b9ae7cd9
It doesn't seem to be a KDE specific bug either, since it also occurs in Gnome.

## To Reproduce
Use a Linux machine with the GDevelop 5.0.0-beta79 and try to import some assets.

## Other details
* Using Manjaro KDE with KDE v5.16.4 and the Linux Kernel v4.19.66
* GDevelop v5.0.0-beta79 straight from the website (no package etc.)

**Comment by 4ian** [comment]
Interesting, looks like the result is like if you had pressed cancelled. Looks like a system related issue, I wonder if it can be related to Electron and that upgrading would help 🤔
Is this KDE version new? Have you tried a few "silly" solutions like double clicking instead of clicking on open (or vice versa?)

**Comment by JanSeW** [comment]
Hey,
I apologize for my late answer.
In the meantime, there was a major update for Manjaro.
But this didn't help. Also other attempts, like a double click or using the "Open" button didn't help. I don't know if it does any good, but that should be the Electron version on my computer: 
Electron v4.2.10 Chromium v69.0.3497.128 Node v10.11.0v8 v6.9.427.31-electron.0

**Comment by JanSeW** [comment]
Okay, I've downloaded the new Beta 80 from the GitHub Release page today and, what a surprise, it works again. I don't know why, but the problem doesn't go on.
Thxalot ^^

**Comment by 4ian** [comment]
Well great then :D
