### ISSUE TITLE
PixiJS v4.8.6 outdated, Google chrome and webview cannot display video anymore

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1212]
## Describe the bug
PixiJS 4.8.6 dosen't display video on Chrome because WebGL texture in Chromium project have been updated.

Google chrome and webview cannot display video anymore with old pixi lib.

## To Reproduce
1. Open video example
2. Run preview over wifi
3. Open game on Chrome or webview
4. Video have sound but no image
5. See warnings in console

I'am wondering if we need update PixiJS with the lastest build.

You can see at left PixiJS v4.8.6 used in game, warning come from line highlighted.
![image](https://user-images.githubusercontent.com/1670670/63650871-a4a2fe80-c74f-11e9-8a2a-e590aada011d.png)

[Error line 5487 from Chronium
](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/modules/webgl/webgl_rendering_context_base.cc?autodive=0%2F%2F%2F#5487)

## Other details
Since Chrome v76

**Comment by 4ian** [comment]
> I'am wondering if we need update PixiJS with the lastest build.

If that is the case, I guess we could find some issues reported on Pixi github?

**Comment by Bouh** [comment]
Maybe  ?
https://github.com/pixijs/pixi.js/issues/5996

**Comment by Bouh** [comment]
They say that sleep brings advices, it works on Chronium ecosystem and on mobile.
