### ISSUE TITLE
Renaming object group

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1213]
## Describe the bug
Similar to #957 , if I click on a group name while renaming it, it opens the group window.

## To reproduce
1. Open the objects group menu, click on the three dots for any group, and choose Rename.
2. Click on the name.

Win10 GD5b79

**Comment by 4ian** [comment]
Good catch, it was inconsistent indeed! Fixed in 2ee065c470e1596fe83c04e7f0c1175b2eea5e4b
