### ISSUE TITLE
Global Variables buttons hidden at the bottom

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1214]
## Describe the bug
If the list of global variables is long, we need to scroll down the list to access the buttons copy/delete/...
These buttons should be always visible, no matter how long the list is, like the Apply/Cancel buttons.

![image](https://user-images.githubusercontent.com/25978830/63653253-a75f1d00-c76a-11e9-883a-87ed62c5b14d.png)

**Comment by 4ian** [comment]
Could be moved to a `MiniToolbar` components for consistency with other editors like Sprite/Text editors

**Comment by leedigital** [comment]
> Could be moved to a `MiniToolbar` components for consistency with other editors like Sprite/Text editors

which is  class to fix it...???

**Comment by 4ian** [comment]
Look at `newIDE/app/src/VariablesList/index.js` and `newIDE/app/src/VariablesList/VariablesEditorDialog.js`.

You can launch the web-app (as explained in the README) and use the [React Debugger](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) to identify the class of an element.

**Comment by leedigital** [comment]
> Look at `newIDE/app/src/VariablesList/index.js` and `newIDE/app/src/VariablesList/VariablesEditorDialog.js`.
> 
> You can launch the web-app (as explained in the README) and use the [React Debugger](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) to identify the class of an element.

thank you very much... :-)

**Comment by geetesh-gupta** [comment]
How to proceed with the issue? 
I will use DialogFile -> VariablesList/VariablesEditorDialog.js and ListFile -> VariablesList/index.js as alias
I have figured out that ListFile has editRow component which actually modifies the variables. To have it always visible on the same row as Apply/Cancel, we have to move the component out of ListFile and write that in DialogFile but it will require passing the onCopy etc. functions from VariableList component which is a child in DialogFile. So, basically I am confused what refactoring is required here?

**Comment by 4ian** [comment]
> So, basically I am confused what refactoring is required here?

I'm not sure! :) (not sure why I removed the label " 🙇‍♀️Careful thinking/design or refactoring needed"... ^^')

I'm not sure we want to move the buttons inside the Dialog footer. Maybe the list could be in a `ScrollView`, and the buttons can stay displayed below the list. Not in the footer of the dialog, but between the list and the footer of the dialog.

**Comment by PascalLadalle** [comment]
Not sure why I mentioned _Global_ variables, but the same thing occurs with scene variables. 
And probably instance variables too, never had enough of these to check.

**Comment by PascalLadalle** [comment]
Oh, and also the same thing in object properties to access Hitboxes and Points and Add animation.
Not sure if it's related, and maybe I flagged it in another bug already. 🤔

**Comment by AlexandreSi** [comment]
Closing this issue as it seems to me that the bug has been fixed.
