### ISSUE TITLE
Global Variable being "(Structure)" after the child event is removed

### ISSUE THREAD

**Issue by Okanegahoshi** [4ian/GDevelop#1218]
## Describe the bug
When setting Global Variables, add a child variable would make the value become "(Structure)".
But the value remains the same way even if the child is removed.
https://imgur.com/scDUgS9
It doesn't change even after re-open the project.

It should become editable after removing the child.
Ideally, it could even store the value that was there (if any) in case of misclicking.

**Comment by triptych** [comment]
Yes! I ran into this earlier today - would love to see a fix.

**Comment by 4ian** [comment]
We might think about improving the UI too to show the variable type (number, text or structure), and allow to switch from a primitive (number, text, in the future boolean) to a structure.
As a first step, removing the only remaining child of a structure should convert it back to a number.

**Comment by mhk19** [comment]
@4ian i would like to work on this issue

**Comment by 4ian** [comment]
Feel free to try :)

**Comment by arthuro555** [comment]
With the variable strict typing changing the interface, this issue should be fixed now

**Comment by 4ian** [comment]
Yep! :)
