### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by Ruhan777** [4ian/GDevelop#1227]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  This is a basic Platformer game ....I have a tutorial on it also
 https://youtu.be/20bkcZcO9UM 

  I confirm that any assets can be used freely by anybody, including for commercial usage.
I didn't know how to export a game for share so I exported normally.You have to open the file in desktop.
  
[Basic Android Game.zip](https://github.com/4ian/GDevelop/files/3606479/Basic.Android.Game.zip)

**Comment by 4ian** [comment]
I'll close this because we need examples but either showing specific features or more complete game but with asset and arts that are unique :)
