### ISSUE TITLE
export 

### ISSUE THREAD

**Issue by twistcharlie** [4ian/GDevelop#1231]
## Describe the bug
 export doesn't work I think only for the windows, Linux and mac 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to export
2. Click on the computer one 
3. Scroll down to  then click export
4. for me after I wait the time it says should be finished soon but 1 day later still 

## Other details
version 5.0.0-beta80

**Comment by 4ian** [comment]
Can you try again now? Should be better

**Comment by twistcharlie** [comment]
okay

**Comment by twistcharlie** [comment]
ty it works now
