### ISSUE TITLE
app-id from adMob crash export android

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1232]
## Describe the bug
When you insert app-id Admob in your project, and all rest of the project are correct, the android export will crash.

We can compile without app-id and it's working.
But this mean admob not working anymore.
I guess problem come from online compilation system. I've tested lot of properties in game.json.
App-id seem the real problem.

And about app-id, we have a tidle ~ .
But on Gdevelop field display a slash bar in pattern.
ca-app-pub-XXXXXXXXXXXXXXX/YYYYYYYYYY
ca-app-pub-1513231741201647~5854500362

## To Reproduce
1. Open empty project, add icons, add app-id, add event for banner
2. Launch export Andoid
3. See error

We can use any project if you insert app-id export will fail.

## Other details
* b80, W10

**Comment by 4ian** [comment]
Looks like a bug in Cordova because GDevelop generated projects have a missing file compared to the blank projects generated with recent Cordova versions, let me try something to work around this.

**Comment by 4ian** [comment]
Should be fixed - admob example is now working :) Seems like a weird bug to a missing package.json file in the Cordova project. Will fix that in GDevelop for next version so that the online service don't have to workaround this.
