### ISSUE TITLE
Skeleton object fails to load

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1238]
This seems like a loading issue for one of the extensions. Opening the skeleton object demo file,I get this

```
Platform "GDevelop JS platform" is unknown.
libGD.js:20 Tried to create an object with an unknown type: SkeletonObject::Skeleton for platform GDevelop JS platform!
libGD.js:20 WARNING: Unknown object type "SkeletonObject::Skeleton"
libGD.js:20 Tried to create an object with an unknown type: SkeletonObject::Skeleton for platform GDevelop JS platform!
libGD.js:20 WARNING: Unknown object type "SkeletonObject::Skeleton"
```

The skeleton object is not listed with experimental objects that can be added, nothing renders when you playtest
![error](https://user-images.githubusercontent.com/6495061/65711676-4f7b4500-e08d-11e9-9673-e1f1036a1d39.png)

**Comment by 4ian** [comment]
This is working for me both in the web-app and desktop app? Are you sure you are on master and relaunched npm install and npm start?

**Comment by 4ian** [comment]
Yeah thinking about it, as you've been working on a branch that was "far" from master, you probably have been using a version of libGD.js that was pretty old. Then when merging master in your branch or going back to master, you did not get the latest version. Go on master and relaunch `npm install`/`yarn` (or just `npm run import-resources`) and your should get it :)

**Comment by blurymind** [comment]
ok I got it to load. It has rendering issues, but loads. Will close this one :)
