### ISSUE TITLE
Tween behavior prevents the game from starting in internet explorer

### ISSUE THREAD

**Issue by GustavoMarciano** [4ian/GDevelop#1239]
## Describe the bug
the tween behavior prevents the game from starting in internet explorer

## To Reproduce
1. create any example 
2. add a the tween behavior
3. create a tween on events

![Capture](https://user-images.githubusercontent.com/23220658/65720400-420a8e80-e07e-11e9-89e5-3d37aac6e5f5.PNG)

## Other details
* Windows10
* beta80 and 78
* Browser IE11

**Comment by 4ian** [comment]
I'm starting to wonder if we should drop IE11 support...
For fixing this, we should include a `Symbol` polyfill.

**Comment by 4ian** [comment]
I've opened an issue on Shifty repo, as it's due to Shifty usage of `Symbol`. If it's too hard to avoid using it, we might have to have extension declaring compatibility toward browsers (so that GDevelop can tell which browsers are supported).

**Comment by GustavoMarciano** [comment]
I would also like to drop IE support
but I always remember Safary is an IE mobile

**Comment by 4ian** [comment]
Safari is not IE right? :) Safari supports for latest web standards is not always great, but at least better than IE11 that is stuck in the old days.

**Comment by GustavoMarciano** [comment]
fixed?

https://github.com/jeremyckahn/shifty/commit/141cb5dcee23c3d49ce18bf70ebd44ca044967a3

**Comment by Bouh** [comment]
[Close because IE11 isn't anymore supported since beta 101](https://github.com/4ian/GDevelop/issues/1237#issuecomment-752744318)
