### ISSUE TITLE
How to make android game

### ISSUE THREAD

**Issue by Ruhan777** [4ian/GDevelop#1255]
Hi!
I am RTBRuhan
  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: https://mega.nz/#!VvR3UAoZ!ue1IjmoH0C30XsKTCYNIiHcH0zzthWWMw03nr2drEKg

I have also made a tutorial on this
https://youtu.be/20bkcZcO9UM

I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by 4ian** [comment]
Thanks for making a tutorial :) For the game itself, I would prefer to have games that are using assets and art that is new from now though.
