### ISSUE TITLE
Idea: add pixijs debug extension to the electron version and other ideas to make the dev experience nicer

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1267]
So apparently it is possible to bundle chrome extensions with electron - unless I am misunderstanding this
https://electronjs.org/docs/tutorial/devtools-extension

so, there are a couple of ways we can take advantage of that:
-  bundle the electron version with https://chrome.google.com/webstore/detail/pixijs-devtools/aamddddknhcagpehecnhphigffljadon?hl=en or  https://github.com/bfanger/pixi-inspector
so when we playtest a game, we have a richer inspector
- bundle the electron app with React dev tools - for IDE developers
https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

Nice to have/ possibly lower hanging - when playtesting the game, remember if the debugger was open before - so we  dont have to open it every time over and over again. Also make it easier to discover it - if running GD  in dev mode, make it appear by default when playtesting

**Comment by 4ian** [comment]
I did not know about Pixi inspector, this looks very very cool and super useful :)

I'm all for bundling it and the React dev tools.

**Comment by blurymind** [comment]
might give this a try tonight if no one is doing it :) it bothers me a bit that GD doesnt remember the state of the debugger (open or not) when you playtest. You have to do ctrl+i every time

**Comment by blurymind** [comment]
@4ian should the newIde keep a copy of the extensions in a folder somewhere it should it be using the one the user has installed in their chrome home dir (as described in the example at electron's doc)

**Comment by 4ian** [comment]
>  I wonder if it's worth copying it somewhere in the newIde's (public?) folder - so we are not asking the user to install it and we always know what version of the extension they are running

Ideally that would be interesting to bundle this yeah. These are electron specific extensions so they should go somewhere like `newIDE/electron-app/app`. Then `BrowserWindow.addDevToolsExtension` should be called with the path to the extension. Note that this should be tested after building the IDE (npm run build) because when packaging for distribution, Electron put all the files in a .asar archive. This might or might not work with `BrowserWindow.addDevToolsExtension`, I don't see any notes about this so this has to be tested.

**Comment by blurymind** [comment]
the pixijs extension is unfortunately not yet supported on electron, but the react one is and works :)

I think the react one is only useful when in dev mode and not much useful  in a build

**Comment by blurymind** [comment]
Now that the react one is in, I sort of wonder if I can do a PR to the pixi one to get it supported for electron. Somebody raised an issue about it a few months back, but I dont think it was resolved. Maybe wait a little to see if they resolve it and when they do, add it

**Comment by blurymind** [comment]
anyways, maybe now that the dev experience is a bit better we should close this issue?
Feel free to reopen it if  you think we need to

**Comment by 4ian** [comment]
If we can get the Pixi extension working with Electron and then integrate it in GD that would be good but it's not a huge priority I guess. Something to keep in mind and watch :)
