### ISSUE TITLE
Error when adding a behavior as parameter to a custom extension

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1276]
## Describe the bug
The IDE shows an error when adding a behavior as a parameter of a custom behavior's function.

## To Reproduce
1. Create a new project (add a scene and a textobject)
2. Add a behavior to the textobject
3. Create a new custom behavior and add a custom function
4. In the function parameters tab add a new parameter
5. Choose "Behavior (for the previous object)" as a type
6. The Editor shows an error and the parameters tab cant be opened again until the IDE is restarted

## Other details
It doesn't matter if an object has been added as a previous parameter or not.

Project file with custom behavior already added:
[BehaviorBug.zip](https://github.com/4ian/GDevelop/files/3782579/BehaviorBug.zip)

Version: 5.0.0-beta82

**Comment by Bouh** [comment]
Yes same here 
https://forum.gdevelop-app.com/t/ajouter-un-behavior-dans-un-parametre-de-fonction-fait-crash/21180

**Comment by Bouh** [comment]
A little addition can be done with thix fix ?
The possibility to get the properties from custom behavior in JS event.

With the expression we can do `Object.Behavior::PropertyHalfPeriodTime()` (example in Flash extension)
It's not possible in JS.

**Comment by Bouh** [comment]
Related to #1304

**Comment by 4ian** [comment]
I'm closing this as this is finally fixed - sorry for missing this bug that was easy to fix.
See the workaround in  #1304 (thanks @Bouh for spotting the duplicate issue).

> With the expression we can do Object.Behavior::PropertyHalfPeriodTime() (example in Flash extension)
> It's not possible in JS or we can't use autocompletion for find it.

Getters are generated as private methods start with `_getXXX` in JS (you can inspect the JS to see that). Though as there is an underscore, it's risky to use that for now. Either we make it public (remove the underscore) (but that mean that the names must be generated the same forever then).

For autocompletions, autocompletion is done using the GDJS and Extensions folder. That would need it to read the events function generated code, it's a larger change (create a card on the roadmap for this if you want)

**Comment by Bouh** [comment]
Or like we use getBehavior("Flash").
Use a method for getProperty("HalfPeriodTime")
?
