### ISSUE TITLE
Load texture from URL

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#1277]
I wonder if there is any possibility of loading a sprite texture or any image from a distant server by URL or HTTP request. I don't mean putting an URL in the texture path in the GD interface, but dynamically loading the texture on run time with a possible dynamically generated URL.
Does the gd:FileStream lib on #312 could help?
I imagine an action loading the texture using a given URL and placing a value in a variable when the texture is loaded.

**Comment by Bouh** [comment]
You have already something like this take a look in the example, search "url"

**Comment by 4ian** [comment]
Note that it's not entirely supported - you have to go and dig a bit into GDJS/Pixi to understand what it's doing.

> Does the gd:FileStream lib on #312 could help?

No that's totally unrelated.
