### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by EduardoGonzalezAvila** [4ian/GDevelop#1280]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in b
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in div
    in t
    in t
    in t
    in Unknown
    in div
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in u
```

**Comment by wild4n** [comment]
me too,
crash everytime,
file autosave.

**Comment by 4ian** [comment]
@wild4n Can you give more details about what exactly you're doing before the crash (what button you're clicking)? 
Ideally, if you send me the game file along with the instructions to make the crash (click here, click here, enter this, boom crash!), I can easily find and fix it. 
Thanks!

**Comment by wild4n** [comment]
@4ian 
[Kids Addition Game.zip](https://github.com/4ian/GDevelop/files/3836472/Kids.Addition.Game.zip)

evertime i try to make sub events is crash and autosave

**Comment by 4ian** [comment]
Thanks for sending the file :) Can you make a screenshot of the exact place
where I should add the subevent to trigger the crash? You can also make a
video or write. I'll fix the bug after.
