### ISSUE TITLE
Missing S3 configuration

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1281]
## Describe the bug
Can't export to online web services.
Keys are missing on this build b82.
Missing S3 configuration

```
Error while uploading the game. Check your internet connection or try again later.
exportStep  : "upload" rawError :  "Missing S3 configuration"

```
## To Reproduce
1. Export example on apk or other online services
2. See error

## Other details
* Only b82

**Comment by 4ian** [comment]
@Bouh Is it in the official distributed version or in development?

**Comment by Bouh** [comment]
It is a user who uses a 32bits version for windows.
Probably one of the versions I build myself.

**Comment by 4ian** [comment]
In this case it's normal as the S3 configuration and some other keys are not in the source code. I'll communicate them to you as you're making "semi official builds" :)

**Comment by Bouh** [comment]
ahaha just how use it, i've already found secret keys ^^
