### ISSUE TITLE
UI fixes for beta 83

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#1295]
Beta 82 introduced a refactoring of the whole app to use an updated UI component library. Some things were not caught before the release, so I list them to fix before beta 83:

Top priority:
- [x] https://github.com/4ian/GDevelop/issues/1292 - "Random" deletion of events due to bad shortcut handling
- [x] [Search in expression selector not working](https://forum.gdevelop-app.com/t/expression-search-issue/21260)

Medium priority:
- [x] https://github.com/4ian/GDevelop/issues/1294 - menu not showing if project is not loaded
- [x] [Graphical glitches](https://forum.gdevelop-app.com/t/user-interface-regression/21351)

**Comment by 4ian** [comment]
@blurymind @Bouh I might delay answers/reviews of Pull Requests until the list of issues here is fixed. Stability of the software is top priority to be able to release a new version.

**Comment by 4ian** [comment]
@Bouh If you have some time, you can take a look at the latest master branch, the expression selector should be fixed. Note that the change implies not to have the expression selector to be able to go outside of the modal. This means that sometime the selector will have to adapt its position and not be directly below/above the edited field.
I think it's ok though as it's working again!

**Comment by Bouh** [comment]
Expression like text or number can be edited on multiline.
Basically in the eventsheet the value in blue (Object) are ok, the others are not ok.
![input_pop](https://user-images.githubusercontent.com/1670670/69282914-aadc3600-0beb-11ea-8064-1ef0e57542d1.gif)

For boolean the popup is a bit large
![image](https://user-images.githubusercontent.com/1670670/69283112-16260800-0bec-11ea-8733-c3b17b5fddbf.png)

The field is a bit cropped look (greater than) g is crop on 1 or 2px at bottom.
![image](https://user-images.githubusercontent.com/1670670/69283176-3c4ba800-0bec-11ea-9bef-db5df308d77b.png)

**Comment by 4ian** [comment]
Give it another try ;) I just changed the InlinePopover so that the height can adapt to the content. If it's really too large, it will show a scrollbar.
Should also make the popup fit exactly the size of smaller fields like booleans.

**Comment by 4ian** [comment]
> Expression search bar is working and placement are better on small screen 

I'm almost thinking on small screens to display the expression selector in a dialog, meaning that it would open a fullscreen dialog like others (well I could keep borders around the dialog to show that it's a "popup"). Not sure how relevant it is to have a "popup" on a small window/phone screen.

**Comment by Bouh** [comment]
Multiline is fixed ✅

(Code in this commit is intersting for me. 
I've also cool stuff for eventsheet, [it's in wip ](https://github.com/Bouh/GDevelop/commit/e208dce90fc3470ee3c95b0274f0d34a097fdbdd)for add dialog for edit colors and values of groups & comments,)

**Comment by Bouh** [comment]
Hum can we put the scrollar in the popover ?
![image](https://user-images.githubusercontent.com/1670670/69284518-18d62c80-0bef-11ea-9f48-b706cdf2d932.png)

**Comment by 4ian** [comment]
Alright fixed, good catch :) I did test with the inset scrollbars of macOS.

**Comment by 4ian** [comment]
I'll probably release a new version tomorrow evening with these fixes.

**Comment by Bouh** [comment]
Yup it's fixed !
For long / medium expressions the input is a bit short, and after few edition update come.

I think we can avoid to release a new b83 just for these bugs.
They do not prevent users from using the software there is always a workaround.

**Comment by Wend1go** [comment]
But we definitely need a new beta for #1292 asap.
This bug is one of the worst things that can happen. I lost an important chunk of logic through this bug and had to search for a long time why things that were working before suddenly stopped working.

**Comment by 4ian** [comment]
I'll upload an update soon

**Comment by Bouh** [comment]
Can check last case & close.
Thank for your time!
