### ISSUE TITLE
Draggable behavior ignore the shape and size of custom hitbox and rotation of object

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1298]
## Describe the bug
It seems like if we edit the hitbox of our object to be smaller or a different shape, the draggable behavior ignore this and we can drag the object at any point of the original hitbox which is the size of the image.
The draggable behavior also seems to ignore rotation of an object and we can drag the object at any point of the original rotation.

It is a problem when you have empty, transparent parts and the object is not a square shape and you don’t want the user to be able to drag and move the shape when it is clicked around the object on an empty transparent place but only if the user actually click the object.

Forum:
https://forum.gdevelop-app.com/t/bug-draggable-behavior-ignore-the-shape-and-size-of-custom-hitbox-and-rotation-of-object/21532

## To Reproduce
1. rotate something
2. use draggable behavior

* Please include a link to a game if possible!
[hitbox-test.zip](https://github.com/4ian/GDevelop/files/3883939/hitbox-test.zip)

## Other details
GDevelop 5 beta83 Desktop
Windows 10 64bit

**Comment by 4ian** [comment]
Right currently the draggable behavior is using the object position and width/height but not the hitbox. We should update the behavior to use the hitboxes, checking if the point of the touch/cursor is inside. 
I'm reworking the object spatial handling so this could be done at this point.

**Comment by Silver-Streak** [comment]
@4ian 
I'm seeing you have an older PR on this that is still open. Seeing your related issues, I definitely agree this is similar to the issues people are having (or quality of life/experience issues) with "Cursor/Touch is on" detection.

Is there anything that needs to be done to bring attention back to this?

**Comment by 4ian** [comment]
My PR was solving this but this could be solved independently right now, actually not ton of work to just fix this!
