### ISSUE TITLE
Behavior parameter editor crash

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1304]
## Describe the bug

When adding a behavior parameter in a function, the editor shows the attached error message.

Please double check that the bug is not already reported in the issues list. ✔✔

## To Reproduce
1. Go to a function or behavior extension
2. Go to function configuration
3. Click on "parameters" 
4. Attempt to add a behavior for the previous object
5. See error

* Please include a link to a game if possible! **N/A**

* If applicable, add screenshots to help explain your problem.

![functionbehaviorerror](https://user-images.githubusercontent.com/45985516/69935854-181d8000-14a4-11ea-938c-64b6e3f8e40e.png)

![functionbehaviorerror2](https://user-images.githubusercontent.com/45985516/69936112-bf021c00-14a4-11ea-9196-19cdd686ebcb.png)

## Other details

* Include any OS/browser version/smartphone that you're using

Windows 8.1 Laptop

* Which version of GDevelop are you using? The desktop app or the web-app?

Beta 83 desktop app

* Add any other context about the problem here. 

This has happened more than once with several existing functions/behaviors. 
I created a new one for the example above.

**Comment by 4ian** [comment]
Thanks for the report! I can reproduce the issue, I'll fix that ASAP :)

**Comment by 4ian** [comment]
Fixed for next version: https://github.com/4ian/GDevelop/commit/656f05e81e704b80e450407203fe9d2c7dd1da51

A "workaround" is to: choose "Objects" as type, choose an object type like Sprite or Text in the second select field (but **not "any object"**) then choose "Behaviors" as type in the first select field. Finally select the proper behavior type :)
This is because there is a crash when the second select field value is empty.

**Comment by Phenomena3** [comment]
Thank you for the workaround. It does allow me to add behaviors now, but I wanted to let you know that they aren't being applied as expected. Come to think of it, since this crash started happening, all of my custom behaviors have been temperamental. 

Sometimes my weapons don't shoot in one direction, but do shoot in the other three and other times it's health or death related. This time, I am trying to spawn specific items from an NPC and tweening them to a position - they weren't working as I intended from a function/behavior, but they seem okay in a regular / external event sheet.

Restarting the preview usually helps, but the issue still occurs.

**Comment by 4ian** [comment]
It's hard to action this without being to reproduce the issue - could be a lot of things. There should not be any difference between two previews if you don't do any changes. Are you using anything in particular in your behaviors, like creating objects, testing collision?

The only thing I can think of is that the code generated from your behaviors would be too late to be generated - but that seems unlikely on the desktop app as it's done directly using the filesystem which is fairly quick.

In any case, this crash is a simple "mistake" in the UI and has no effect whatsoever on the behavior themselves.

**Comment by Phenomena3** [comment]
I know, I'd send you my game files, but there's a lot of content and it would too easy to get lost even with comments that explain where to find something related. Maybe it's just too much for one game or it's my laptop that can't handle it.

> Are you using anything in particular in your behaviors, like creating objects, testing collision?

Yeah, it varies depending on the behavior. I find that functions/behaviors are easiest to work with when they involve as few objects as possible and sometimes prefer to use the regular non-behavior functions. Honestly, I'm thinking it could be attributed to lag from too many Chrome processes, my CPU, and so on. :\
