### ISSUE TITLE
Game Crashes After Multiple "Change Scene"

### ISSUE THREAD

**Issue by shinobirozs** [4ian/GDevelop#1311]
## Describe the bug
I was playing around with the Downhill Bike Demo on the example games and I found out that if you click the Retry button 10++ times [to Change Scene] the game will crash without any error messages. I tried it in both on a mobile device and chrome browser and the issue is there. I am suspecting some memory leaks on the Physics on reload.

## To Reproduce

1. Play Downhill Bike Demo
2. Click Retry button 10++ times
3. App/Browser/Mobile Browser will crash

## Other details
* Android, Web Browser, Mobile Browser
* GDevelop Desktop App was used

**Comment by 4ian** [comment]
Good catch, I can reproduce the issue! There is surely indeed a leak somewhere.

**Comment by shinobirozs** [comment]
@4ian, 

I'm glad I can help, hope it can be resolve soon. I have this prototype game in progress that heavily requires it. 

**Death Bike Stranding**
![Icon-256](https://user-images.githubusercontent.com/29979672/70142929-52219880-16d5-11ea-8c31-2bdf618ffbd1.png)

**Comment by Silver-Streak** [comment]
@4ian I wanted to bring attention to this because I am able to reproduce this still with the downhill bike example. Hitting the Esc key ~20 times rapidly will cause it to freeze, even when running from the browser app.

It *does* seem exclusive to that example, however. my main game I can literally spam the restart scene button for a whole minute without any issues.

**Comment by Bouh** [comment]
A trigger once is missing, it could be a good start ^^

**Comment by Silver-Streak** [comment]
Sure enough. Added a trigger once into the Esc key event and it seems to have solved the issue. Score one for @Bouh 😄

**Comment by 4ian** [comment]
Would be still interesting to dive why this was crashing, maybe a very small memory leak that is multiplied by the 60 restarts per second

**Comment by Bouh** [comment]
Extreme large panel sprite to load and setup at startup.
Some instances exceed a size of 5k in the editor, and some instance with collision are duplicated, it doesn't help to optimize the collisions. I let you dive deeper in the dev tools.
