### ISSUE TITLE
List Symbols Incorrectly Displayed in UI

### ISSUE THREAD

**Issue by shinobirozs** [4ian/GDevelop#1312]
## Describe the bug
Some list symbols are incorrectly displayed on the UI.

![image](https://user-images.githubusercontent.com/29979672/70108605-ad776a80-1684-11ea-858c-1b2d818d7379.png)

## To Reproduce
1. Go to 'Value of a global variable'
2. Click on 'Sign of the test'
3. See error

## Other details
* GDevelop Mac

**Comment by 4ian** [comment]
Yep this is fixed for next version :)
