### ISSUE TITLE
Can't start the electron dev version of gdevelop

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1318]
## Describe the bug
When I start the electron-win dev version of gdevelop, it does not work. The console displays GDevelop is starting, the electron window opens and nothing else ever happen. After investigating, I found in the network tab that the index file fails to load because of "Connection Refused".

## To Reproduce
I have no idea

## Other details
Windows 10, latest version of the master branch (without moddifications) of gdevelop, node js 8

**Comment by 4ian** [comment]
> The console displays GDevelop is starting

As long as this is not showing this, GDevelop won't start:
![image](https://user-images.githubusercontent.com/1280130/70854839-21054d00-1eb9-11ea-943e-306fc0d76466.png)

This is quite long the first time you start it because there are a lot of JS files to compile. Can you try to:
- Go to newIDE/app/src/locales and delete all folders except for "en" (and keep the LocalesMetadata.js file).
- Relaunch `npm start`
- Wait for up to 5/10 minutes and see if the compilation finishes. If yes, you can open the electron app.

**Comment by arthuro555** [comment]
I already had the compilation. But I always get those warnings tho:
Compiled with warnings.

./node_modules/react-mosaic-component/lib/util/OptionalBlueprint.js
Module not found: Can't resolve '@blueprintjs/core' in 'D:\Users\pc\Desktop\GDevelop\newIDE\app\node_modules\react-mosaic-component\lib\util'

./node_modules/react-mosaic-component/lib/util/OptionalBlueprint.js
Module not found: Can't resolve '@blueprintjs/icons' in 'D:\Users\pc\Desktop\GDevelop\newIDE\app\node_modules\react-mosaic-component\lib\util'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

Is this somehow related?

**Comment by 4ian** [comment]
> . But I always get those warnings tho:

No worries about them, they are harmless :)

When this is displayed you can open `http://localhost:3000` in your browser or open the desktop app with `npm run electron-win` (or linux or mac according to your OS).

**Comment by arthuro555** [comment]
That is what I’ve already done, I’ve done it again as you said and ( not a big surprise ) It still doesn’t works.

**Comment by arthuro555** [comment]
It is unclear you need the development server to be active to be able to launch the electron development version. It should be fixed in the readme. Thank you anyway! Now I can finally develop JS Extensions hehehe

**Comment by 4ian** [comment]
>  Now I can finally develop JS Extensions hehehe

Great! 😄

> It is unclear you need the development server to be active to be able to launch the electron development version. It should be fixed in the readme

Turns out it's already there in bold 😉

![image](https://user-images.githubusercontent.com/1280130/70862134-1c2fb000-1f30-11ea-99e6-c8bd6b581760.png)

But I guess you've not seen this because it's not part of the list of commands, I'll add it here too.

**Comment by arthuro555** [comment]
I’ve seen this, but the problem is that I thought by reading that this compiles the ide and I only need to run it to compile the ide then use the elctron version. What is unclear is that you have to KEEP it running.

**Comment by 4ian** [comment]
https://github.com/4ian/GDevelop/commit/1b3f7309b03fa9172e5e51d3ddc8c035ef78ca30 Better? :)

**Comment by arthuro555** [comment]
Yes, Thank you!
