### ISSUE TITLE
game settings / project file type - can only use single file option

### ISSUE THREAD

**Issue by eshell** [4ian/GDevelop#1328]
When trying to select multiple files for project file type, it keeps reverting to "choose an option". If i press apply then open game settings again, it's reverted to single file (default).  I'm not sure what the differences are, or if i even need it as i'm just learning right now. Just thought it may needed to have been brought to your attention that you can't select the 2nd project file type.

Windows 10 version.

**Comment by 4ian** [comment]
Thanks for reporting this :) This is indeed a bug that was fixed for next version! Hopefully should be released in the next days/weeks. 
Closing this as fixed.
