### ISSUE TITLE
Piskel integration bug with drawing tablet

### ISSUE THREAD

**Issue by vipertail67** [4ian/GDevelop#1337]
## Describe the bug
When i use a drawing tablet on the piskel integration the pen is sliding it left and right.
## To Reproduce
1. Go to 'Edit With piskel'
2. Click on 'canvas with drawing pen'
3. Scrolls automatically left and right when i use the drawing tablet.

## Other details
* windows 10
* GDevelop 5 The desktop app

**Comment by blurymind** [comment]
Strange :)

What tablet brand are you using?

Does this happen when you use piskel at the piskel website?

**Comment by vipertail67** [comment]
Im using Huion H420 and it works perfectly fine in the piskel desktop app. Just not inside the GDevelop integration of piskel. Sure i can just use the desktop app and then move it inside the gameproject folder but then the whole integration thing would be useless.

**Comment by blurymind** [comment]
Is there a scrollbar inside the window? I am a bit confused about this bug. Can you link me to piskel desktop app that you are using? Also make a screenshot of even better a gif of the bug

**Comment by vipertail67** [comment]
I will record a video of the bug. It will take some time. But that should be more precise.

**Comment by blurymind** [comment]
Thank you

**Comment by Silver-Streak** [comment]
There's been some pretty significant changes to the integrated version of Piskel over the last few releases.

Is anyone else still experiencing this in b115?

I will close this issue out if no response (or if no one can reproduce it) is received by 9/6.
