### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Sdstranger** [4ian/GDevelop#1343]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in t
    in div
    in div
    in t
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in M
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in a
    in Unknown
    in t
    in u
    in t
    in div
    in t
    in t
    in t
    in Unknown
    in div
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in a
```

**Comment by 4ian** [comment]
Unfortunately not enough context to see what went wrong :/ Closing this!
