### ISSUE TITLE
GDevelop has completely frozen

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1346]
## Describe the bug
GDevelop has completely frozen.
The electron File, Edit, View, Window and Help buttons work. All calls to React are dead, e.g. View > Show project manager
Calls to electron are ok, View > Toggle Developper Tools.
The debugger opens but absolutely everything is empty.

When closing GD the message for saving is not even displayed.

## To Reproduce
I selected the action on the image.
I edited Input.variableString(Type) in the quick popover.
I paused with space my music on another application.
I was AFK less than 10min, when I came back I put the music back and GD was frozen.

![image](https://user-images.githubusercontent.com/1670670/71589905-eb9e6780-2b26-11ea-8638-790d58b2c351.png)

## Other details
* B83

**Comment by 4ian** [comment]
> The debugger opens but absolutely everything is empty

This seems to indicate an issue more related to Electron/Chromium/V8 than GDevelop itself :/
One case where the software can be unresponsive is an infinite loop, but I see little reason for this too happen (and usually the debugger is still somewhat responsive).

Note that Electron version might get a bit old, we should probably update it soon.

**Comment by 4ian** [comment]
I'll close that unless there is a way to always reproduce this. Electron update is a card on the roadmap too.
