### ISSUE TITLE
Build Service creates broken Zip files

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1347]
Nick8712 reported this today on Discord:

I am a GDevelop user and I need help with the newest update. There is an issue where the build service builds MacOS and Windows Game incorrectly. My computer is unable to unzip it properly and when it does, the folder is missing files. I have never had this problem before and I just started experiencing it yesterday.

**Comment by 4ian** [comment]
Thanks for reporting this! I'm in the process of updating workers to clean them/restart them regularly, so this kind of issue should hopefully disappear completely when it's done :)

**Comment by Nick8712** [comment]
Glad to see it's been fixed
