### ISSUE TITLE
Expression editor not showing properly

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1350]
## Describe the bug
Expression editor not showing properly

## To Reproduce
- Open intruction editor
- Click on Expression editor
- Choose someting like "number to text", this open another expression editor.
- See the problem

The editor in editor are bugged.

![image](https://user-images.githubusercontent.com/1670670/71736791-49e28780-2e52-11ea-85a9-3b3728279fac.png)

## Other details
B83

**Comment by 4ian** [comment]
For now I don't have a better solution to this as popover are very difficult to handle. 
We can maybe force a minimum height for this dialog though?

**Comment by Bouh** [comment]
You have Modifier on Popper  component, you can use   `boundariesElement: 'scrollParent',`
https://material-ui.com/components/popper/#scroll-playground

**Comment by 4ian** [comment]
I recall testing multiple solutions (different boundariesElement and with/without portal) but each had some issues. I went for the one without portal to avoid issue of misplacement. We could try  'scrollParent' but I'm not sure that we want the dialog to have scrollbars created :/ (in particular the action/condition editor dialog).

**Comment by 4ian** [comment]
I've fixed this in beta 85 by having a minimum height for the dialog. Not ideal but better than having not enough space.
