### ISSUE TITLE
Particle object not working correctly

### ISSUE THREAD

**Issue by hook2r7e** [4ian/GDevelop#1353]
## Describe the bug
The newest update affects the particle object. If a particle object is set to a color and the newest updates runs, the particle color will not be the same as what is set in the particle object. For example, I have a particle object set to a green color, after the update, the particles show up as some shade of purple. If I check the particle object, the color is still set to green but they show up as the purple color.

Please double check that the bug is not already reported in the issues list.

## To Reproduce
To see the bug in action, play Geo Dash from the examples online. You will see the particles are white in color in the online version. Then play the Geo Dash in the new updated desktop version. You will see the particles are purple in color even though the particle object has them set to white. That is what I am experiencing in all of my games in the new desktop app.

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

**Comment by 4ian** [comment]
Thanks for reporting this, I've identified the issue. Will fix that soon.

**Comment by 4ian** [comment]
Fixed in beta 86
