### ISSUE TITLE
Network - Send Request Using Get Method NOT Working on Mobile

### ISSUE THREAD

**Issue by shinobirozs** [4ian/GDevelop#1355]
## Describe the bug
The `Network->Send a request to a web page` is working and can send http requests in the development machine during `Launch a preview of the scene` but does not work properly on the compiled .apk installed on **new** android version/phones.

![image](https://user-images.githubusercontent.com/29979672/71936533-b065fd80-31e4-11ea-87a4-87ecfe3c60f9.png)

## To Reproduce
1.  Add  `Network->Send a request to a web page` step to send request to a `http` url
2. Click `Launch a preview of the scene` 
3. The request was `successful`
4. Compile the game for android, install on an android device and run
5. The request was `not successful`

## Game Link
https://play.google.com/store/apps/details?id=com.residentevil.zombies
Click on **High Score** to test
![image](https://user-images.githubusercontent.com/29979672/71945192-195b6e80-3201-11ea-9133-a9fb9a4c76c5.png)

## Other details
* Gdevelop Desktop App [Mac]

## Test Report
*  Issue is happening on Samsung Note 8 phone
*  Issue is happening on Samsung Galaxy A tablet
*  Issue is happening on Samsung Galaxy S10 phone
*  Issue **NOT** happening on Lenovo k320t LTE phone 😲
*  Issue **NOT** happening on Samsung Note 5 phone 😲

**Comment by shinobirozs** [comment]
I did some digging and found out that it might be because of phones running on Android 9 above will not process requests without encryption `(http)` and will only work on `https` requests.

I found one solution to overcome this by  setting `android:usesCleartextTraffic="true"` on you `AndroidManifest.xml` 


> android:usesCleartextTraffic="true"

I hope we can configure that on GDevelop as `compile parameters/configuration`. 

Thanks.

**Comment by 4ian** [comment]
Many thanks for the investigation and finding a potential solution :)
Well the best one is as you did to move any server, that the app/game is connecting to, to https - it's becoming more common and easier these days and browsers might start warning about non https websites in the future.

This being said, might be worth adding an option somewhere - we would need a platform specific options tab maybe.

**Comment by shinobirozs** [comment]
@4ian,  yeah it seems that `https` is the future. games that will be using `http` and `local servers` will be just affected. if you need, please feel free to close this issue. I will be logging a separate issue for adding options on online build. Thank you.

**Comment by 4ian** [comment]
As you've made another issue I'll close this one then. Thanks :)
