### ISSUE TITLE
Automatically re-open the last opened project 

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1356]
So I recently added a feature like this to my svete+electron app and this is something that really makes it nice to use it imo. Basically the idea is:
If you are using electron and you closed the app without closing the project before that, next time you start it, electron remembers your last opened project and  utomatically loads it - so you are straight in it without the need to navigate to its folder.

If you close the project and then close the app, when you start it, the next time you start it - you are offered the standard dialog to create/open a project. This also happens if the autoload fails to load the project because it was moved (path changed)

This is kind of something we take for granted in most programming Ides and some other game engines. With vscode or gitkracken for example, when you open it, you are straight back in your project - you dont have to navigate to it.

Additionally nice to have would be a file> recent menu where one can reopen one of the 5 last edited projects

**Comment by Bouh** [comment]
> Additionally nice to have would be a file> recent menu where one can reopen one of the 5 last edited projects

I vote for it and the rest too!

**Comment by blurymind** [comment]
That would make extension development much nicer too, since we will no longer have to navigate to the test project over and over on each refresh

**Comment by 4ian** [comment]
I would be keen to have it in this order:
1. A file > recent menu. Note that this menu can also be displayed when we click on an arrow that is on the right of the "Open a project" button in the Start page (it's not supported by Material-UI as a "Split button": https://material-ui.com/components/buttons/#split-button).
2. Then if it's something that is interesting, we can add a preference "If the editor is closed while a project is opened, automatically re-open it at the next startup". Alternatively a button in the start page to quickly re-open the last opened project (but a preference might be better)

Note that we can do this without being electron specific :) The list of "recent" projects can be saved in preferences - which are saved in localstorage in the web-app (precisely, this will be a list of [`FileMetadata`](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ProjectsStorage/index.js#L10-L13)).

There will be a function to add in the [storage providers](https://github.com/4ian/GDevelop/tree/master/newIDE/app/src/ProjectsStorage) that can take a FileMetadata and open it if it's compatible with the storage provider. In less cryptic words, this means that we will be able to store in this list of recent projects a file opened from Google Drive (or later from Dropbox, OneDrive, etc...). 
When we click on the button to open a project, we'll re-open the file with the "StorageProvider" that was used to open it the first time.

How does that work with Electron?
=> The storage provider for local files in Electron is this one: https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/index.js

Two last things:
* If you want to prototype this, you can do by just thinking about traditional paths - but I encourage you to take a look at the "storage providers". They are accessible in MainFrame as `storageProviders` props:

https://github.com/4ian/GDevelop/blob/ee1e67a3677447d583c3bbbf0aece55cc4dd8b55/newIDE/app/src/MainFrame/index.js#L145

* Can we create a card for this on the roadmap? :)

**Comment by blurymind** [comment]
added card here
https://trello.com/c/EUCMh9Po/394-add-option-to-autoload-previously-opened-project-when-starting-the-ide-similar-to-vscodes-default-behavior

**Comment by 4ian** [comment]
So I think in this case what we need is something a bit more evolved:
re-open the project that was opened *and* the tabs that were opened as well
as set active the proper tab that was last active at the time the software
was closed?

**Comment by blurymind** [comment]
> So I think in this case what we need is something a bit more evolved: re-open the project that was opened *and* the tabs that were opened as well as set active the proper tab that was last active at the time the software was closed?

Yes indeed if it also remembers the ui's state that would be a huge improvement too 👍  We might already have an issue raised for the tab state somewhere.
