### ISSUE TITLE
Not able to disable Allow Again Jumping through action 

### ISSUE THREAD

**Issue by Level0gamedev** [4ian/GDevelop#1358]
## Describe the bug
Platform Behavior / Option to "Allow again jumping" does not have the option to disable it. Currently user only has the option to allow jumping again for double jump etc, but no way to take that ability away. Compare with De/Activate Behavior action.

## To Reproduce

1. Click on Add Action in any event
2. Choose Platform Behavior / Options
3. Click on Allow again jumping
4. Try to disable Allow again jumping

**Comment by 4ian** [comment]
This seems like a misunderstanding of the action. This action tell the platformer object that, even if it's mid air, a new jump can be started from now.

You can use this action in your event to give the permission to the object to jump again even if mid air. This is useful for a double jump, or a triple jump or any number of extra jumps in the air (as long as your events are calling this action to allow a new jump).

There is nothing to disable there => if you want to disable a double jump, don't ever call this action :)

**Comment by 4ian** [comment]
I guess we have to update the description of the action as it's not clear. Would you be able to suggest an alternate one given my previous explanations? Thanks! :)

**Comment by 4ian** [comment]
I've updated the description for next version:
https://github.com/4ian/GDevelop/commit/7a1ce790d4020bcc808f4e736073cf69aeb9f991

Hopefully should be clearer :) Closing this issue but let me know if there is something else.
