### ISSUE TITLE
Options/Customizations/Configurations for Online Android Builds

### ISSUE THREAD

**Issue by shinobirozs** [4ian/GDevelop#1365]
## Description

GDevelop online build feature is great and it will be lovelier if we would have the features below.

1.  As a user I should be able to add/customize/configure parameters on the `AndroidManifest.xml` for online android builds to support special builds described in issue #1355[](https://github.com/4ian/GDevelop/issues/1355)

2.  As a user I should be able to add an **existing** public key certificate `.keystore` for online builds so we can port/migrate existing android mobile games to GDevelop. 

## Solution suggested
It can be configured on the Properties page. 

![image](https://user-images.githubusercontent.com/29979672/72213209-8b93c200-3525-11ea-87e2-23299252f258.png)

## Alternatives considered
Alternatively, the files can just be placed on the root folder and the Online build should be able to pick it up.
![image](https://user-images.githubusercontent.com/29979672/72213243-0eb51800-3526-11ea-9916-d7547b617135.png)

Hope it can be a useful feature for all of us. 

Cheers,
Rozs

**Comment by 4ian** [comment]
Both suggestions would indeed be great to have. Probably need to introduce something like "Android specific settings", that could be used for other platforms too.

**Comment by 4ian** [comment]
Added both suggestions to the roadmap on Trello: 
https://trello.com/c/mdOMXgIv/396-add-support-for-changing-the-androidmanifestxml-for-online-android-builds
https://trello.com/c/RGXD3pNJ/397-allow-to-use-an-existing-user-provided-keystore-for-online-android-builds

Closing this as I try to keep only bug issues opened but discussion can continue!
