### ISSUE TITLE
 Effects are not working after game is exported

### ISSUE THREAD

**Issue by GustavoMarciano** [4ian/GDevelop#1367]
## Describe the bug

Effects are not working after game is exported

## To Reproduce
Add a efffect my case is Drop Shadow
Export the game to  local folder

GAME:
https://gustavo-marciano.itch.io/iara

DEV
![IaraSS1](https://user-images.githubusercontent.com/23220658/72273984-1cdc6480-360a-11ea-8410-3b954bd0ad80.jpg)

AFTER EXPORT
![ssBUG](https://user-images.githubusercontent.com/23220658/72272747-e867a900-3607-11ea-9eb9-de81167e55aa.PNG)

**Comment by Silver-Streak** [comment]
I was able to confirm this as well. Shaders appear to be ignored on export.

**Comment by 4ian** [comment]
🤦🏻‍♂️I literally forgot to activate effects export for exported games!

Fixed for next version, I'll try to release it soon. Effects will work exactly the same as in previews :)
