### ISSUE TITLE
Better access to scene/object/global variables in js blocks

### ISSUE THREAD

**Issue by Level0gamedev** [4ian/GDevelop#1372]
## Description
The current way of accessing variables via js is cumbersome and far from accessible to new programmers. If someone would like to take a jump from visual programming to java script, GD5 would feel quite daunting. For example, to get a global variable currently, a user has to do the following:
```
let newVar = runtimeScene
  .getVariables()
  .get("_varValue")
  .getAsNumber();
```

While the same can be achieved by using `GlobalVariable(_varValue)` inside the visual programming when using the **Σ123** button.

## Solution suggested
Make the functions accessible/generated via the **Σ123** accessible in the js blocks.

**Comment by arthuro555** [comment]
I think this is a bad idea. This would mean make functions and runtimeGame (to access the variables) globally accessible. This would make cheating easier, and also the current method has a coherent structure. In my opinion, if anything like this would be implemented, it would be a direct shortcut function getVariableValue(variableName) in 
  -> RuntimeGame
  -> RuntimeScene
  -> RuntimeObject
That does following:
  1. Gets the variable using this.getVariables().get(variableName)
  2. Determines it's type and use the correct function to access it's value
  3. Return the value

**Comment by Level0gamedev** [comment]
Even if I value accessibility over any concerns about "cheaters" in game, I am ok a direct shortcut function. As long as it is not cumbersome to call variables from within js block I am happy. 

Also, @arthuro555 created a quick extension for this behavior on GD5 discord. This could be incorporated into extension repo and/or be the base of implementation of this enhancement.

**Comment by 4ian** [comment]
The extension is nice to use, but remember that any code is a liability => events are guaranteed to work on newer versions, but if you have JS code you have to update it if functions have been changed :) 

In particular I've seen that the code in Discord is using `_str` => this is dangerous, this is a private member and should never be used outside of gd.Variable. At any time this can be refactored/renamed and disappear on next version of GDevelop.
Never ever use something that starts with an underscore. At best you're likely that it works, at worse you might be breaking some internal state and then reporting bug that should not even exist.

So please please please always use the public interface, which are the documented function not starting with an underscore. In your case, there is something called `isNumber()`. It's made for this! :)

Thanks!

**Comment by arthuro555** [comment]
BTW @Level0gamedev all the functions for every Expression is accessible, but what you don't know is that the editor adds hidden arguments to the functions, so using them as in the editor probably won't work. Anyways, GlobalVariable's function is located here: gdjs.evtTools.common.getVariableNumber
As you see, this is more complicated as using the default way, as you have to pass the reference to the variable. And forcing exposition of sensitive data on everyone is not a good ide, so use the extension I made for you. Here is the updated version without the use of internals:
[EZJS.zip](https://github.com/4ian/GDevelop/files/4066169/EZJS.zip)

**Comment by arthuro555** [comment]
@Level0gamedev 4ian refused the merge of the shortcuts. See his reasons in the PR comments from the PR above.

**Comment by arthuro555** [comment]
If there are no more problems, I suggest that this issue get closed

**Comment by 4ian** [comment]
I'll close for now as I strongly recommend keeping with the "official" APIs. It may sometimes be a bit verbose, but exposing the GDevelop expressions to Javascript will mean that we have JS code that will do what the GDevelop expressions are doing which is... calling the "official" APIs :) So a bit of a loop. 

I would prefer discussing improving the existing APIs.
