### ISSUE TITLE
JSDoc Incoherence

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1375]
### The problem:
In commontools.js the property of gdjs.evtTools is declared as class, but in objecttools.js, it is declared as a namespace. I think, as there is no instanciation, that this should be a namespace and not a class. 

If there is no specific reason for this design, I propose we make them all namespaces because else it's incoherent

**Comment by 4ian** [comment]
I'm fine with namespace 👍
It's totally not a class as we don't instanciate it and can't be translated
to a ES6 "class"

**Comment by arthuro555** [comment]
Thank you for making this clear!
