### ISSUE TITLE
Edit hitbox & edit point use float & predefined values are wrong

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1384]
## Describe the bug
Is this screen there are two problem.
- Value is depending the zoom on mask preview, and du to this zoom we have float number very long.
- Predefined value are understandable.

Image size 16x16px

![image](https://user-images.githubusercontent.com/1670670/72570905-7076d880-38be-11ea-8419-7bc93c43fad8.png)

## Other details
* B88

**Comment by 4ian** [comment]
We should indeed round up the floats to 2 decimal places.
But your shape *is* convex right? If you put an "elastic" around the polygon, there is a hole. So it's concave :)

**Comment by Bouh** [comment]
Ooops misstanding these two terms.

There is another thing, when i create a new Quadrilaternal shape for hitbox the predefined values are not useable and understandable because i use a 16x16px sprite.

![image](https://user-images.githubusercontent.com/1670670/72571452-eaf42800-38bf-11ea-8a8f-2f39d70ffd0c.png)

**Comment by 4ian** [comment]
Right in this case we could either clamp the values or make it a percent of the size of the sprite?

**Comment by Bouh** [comment]
Pixel value is fine.
The values should just use the size from sprite.

(User is not allowed to drag&drop point outside the bouding box in preview)

**Comment by Silver-Streak** [comment]
@Bouh @4ian is this fixed? Since the change to the collision mask editor layout, I can no longer get bizarre floats, and I cannot make sizes larger than the base sprite.

Are we good to close this out?

**Comment by Bouh** [comment]
Big float is still present but it's less annoying because now we can see them.
Before
![image](https://user-images.githubusercontent.com/1670670/131913037-23b95f41-4af2-4c57-8647-866f495162fe.png)

After
![image](https://user-images.githubusercontent.com/1670670/131912993-2e1e6713-38d8-4cef-aa84-677d4291d8f5.png)


Closing thx for spot this issue 👍
