### ISSUE TITLE
Game with Text extension crashes on Firefox

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1392]
## Describe the bug
Using the text extension makes the game crash on Firefox while loading at 100%.

## To Reproduce
Create test game with Text extension and export it to HTML5. Then open without modifying (itch.io etc probably change stuff in the files) into Firefox. It will crash. Then open on chrome. You will notice it suddenly works.

See test game on:
http://emit-moul.rf.gd/

## Other details
Nobody tried to reproduce it yet (my PC is still broken :cry: )
Found by roracle on Discord.

**Comment by 4ian** [comment]
Seems that it's indeed linked to the text rendering, I can reproduce this on Firefox 70.0.1:

![image](https://user-images.githubusercontent.com/1280130/72756025-ec756700-3bc3-11ea-8411-2a7324b3390a.png)

Seems like an issue around Pixi/WebGL/Firefox. Is there anything special set up for the text? Is removing the text clearing the problem?

**Comment by arthuro555** [comment]
Sorry that I took time to respond. There wasn't any problem with a single text object with only modified text, but the crash occurs since addition of a second one with a size modifier.

**Comment by arthuro555** [comment]
I cannot replicate the bug anymore, I am closing it assuming the update to pixi v5 fixed this.
