### ISSUE TITLE
collision when dragging an object to an object does not work correctly.

### ISSUE THREAD

**Issue by vinurd** [4ian/GDevelop#1402]
collision when dragging an object to an object does not work correctly.

## To Reproduce
1. Go to '.To start, I made a scene where one object, if it touches another, a transition to another scene occurs. Next, I copied the scene. Removed objects and conditions. Created a new object and a new condition. But on the stage, exactly the same transition occurs if you drag an object to the same place. Although there is no object.

* Please include a link to a game if possible!
https://dropmefiles.com/g0pLd

## Other details
* windows 10 64 bit
* version of GDevelop 5.0.0 betta 88

**Comment by 4ian** [comment]
There is an object, it's just that it's hidden behind the others :) 
Use the list of instances to find it

![image](https://user-images.githubusercontent.com/1280130/73590905-1f7efb00-44e0-11ea-9fd9-2c038aada1d1.png)
![image](https://user-images.githubusercontent.com/1280130/73590916-2c035380-44e0-11ea-98a4-e8e289dfe0aa.png)
