### ISSUE TITLE
payment problem

### ISSUE THREAD

**Issue by vinurd** [4ian/GDevelop#1405]
from Russia it is very difficult to pay in the manner presented on the site. Not all cards are accepted. It would be great if paypal

**Comment by Silver-Streak** [comment]
Hello! I am going through older issues to bring attention to them if they are resolve them, or close them out if I can answer them.

At this time, all payments are made through Stripe. The GDevelop team doesn't have control over what transaction methods stripe allows. Other methods may be available in the future if Stripe allows them or if providers are changed in the future.
