### ISSUE TITLE
a problem with the copy of objects and their actions

### ISSUE THREAD

**Issue by vinurd** [4ian/GDevelop#1414]
## Describe the bug
a problem with the copy of objects and their actions

## To Reproduce
I made a sphere revolving around the center, in a timer. I multiplied a sphere with a center (3) All three spheres are attached to one center. Although they have other centers. I have already done using object groups. Nothing helps.

It’s impossible to make this moment more operational. You just want to propagate the objects and that they would carry out the same logic but with those objects that were copied. It will greatly simplify life.

screenshot 
https://ibb.co/XCmCv9h
https://ibb.co/RQ8jM5b
https://ibb.co/Jm22nQ0
https://ibb.co/5YLsC0S

**Comment by 4ian** [comment]
Please open a thread on the forum, these GitHub issues are only for confirmed bugs. Other members will be able to help you on the forum. Thanks!
