### ISSUE TITLE
Extract the events in a function + Dark theme : unreadable extensions list

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#1415]
When using GD5 with the Dark theme, and right click on some events to "extract the events in a function", the first field, wich is a list labeled "Extension (storing the function)" is totally unreadable if some extensions already exist. 

Take a look on this screenshot, my four extensions are here, but names are unreadable:
![image](https://user-images.githubusercontent.com/8144048/73923874-d954dd80-48cb-11ea-92e7-7f66ebce246d.png)

## Other details
GD5b88 on win10x64.

**Comment by 4ian** [comment]
Can you confirm this works with the default theme? Is Windows configured with a dark theme? Because this is a native selector provided by the system.

**Comment by KinkGD** [comment]
Yes my windows is configured with the dark theme, and yes, the issue is here too with Gdevelop default theme.

I switched to normal "light" windows theme color, and restarted Gdevelop. Unfortunately, same thing with both default and dark theme of Gdevelop : 
![image](https://user-images.githubusercontent.com/8144048/73977131-07690a80-492a-11ea-85f0-36c14d907037.png)

**Comment by Bouh** [comment]
Sorry to bother you, i see all my extensions in this list.
Have you fill the Name in ` Edit extension Options`, button is on top of yours function list.
In this options you need fill the input called `Name displayed in editor`.

I've also checked if name given when you use <Create  New Extension> is readable, and yes it is.
I've tested on Dark and Light theme works fine here.
![image](https://user-images.githubusercontent.com/1670670/73995776-f2a46b00-4959-11ea-9584-63d2e3f09bbd.png)

**Comment by KinkGD** [comment]
Bouh, you are right !

I was thinking this menu should have listed functions names just like there are named in the project manager in the "Functions/behaviors" submenu. I've never filled the Name field in Edit extension Options.

A bit confusing no ? Maybe I missed a debates on it, but why does extension have different names in the editor and in the project manager ?

**Comment by 4ian** [comment]
It's clearly confusing. This UI should show the name if filled, or the internal name (shown in the project manager) otherwise.

**Comment by 4ian** [comment]
Fixed in beb1cf0631632b5093ed9cc3f851c864b9ec22a2 :)

**Comment by Bouh** [comment]
? 
How overflowX corrects this issue, it's not the right one I think :)

Related to https://github.com/4ian/GDevelop/pull/1408#issuecomment-581202479
For : 
> Can you remove the scroolbar-x when you edit value in Popper component on you gif ?
> Scrollbar appear when focus is active on input.

**Comment by 4ian** [comment]
Sorry I meant aa30052dca285f5b30724f7786ca3f6b95fe7803 ;)
