### ISSUE TITLE
Browser page scrolls when playing top-down HTML5 game

### ISSUE THREAD

**Issue by paulera** [4ian/GDevelop#1417]
## Describe the bug
When playing an HTML5 top-down game from an iframe (hosted in itch.io in this case), the scrollbar responds to keyboard actions, making impossible to play the game unless switching it to fullscreen.

Game link: https://paulera.itch.io/itroubled

Game source: https://github.com/paulera/itrouble-game

## To Reproduce
* Scenario: desktop or laptop running Google Chrome or Firefox. Keyboard to play the game.
* Open the game page: https://paulera.itch.io/itroubled
* Click the "Run game" button.
* Press SPACE during the intro screen to start the level.
* During gameplay, try to move around with the arrows.

### Expected result
When pressing arrows to move, or spacebar to advance scenes, the player expects the page scroll to stay where it is, so I can always see the game when playing.

### Observed result
The page scrolls during the gameplay (responding to arrows and spacebar), making it impossible to play.

## Environment
* GDevelop 5 Beta 88
* Exported to HTML5 project and published uploading as ZIP to itch.io
* Brave Browser - Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
* Windows 10

## Fun facts
* Even clicking the iframe after starting the game, doesn't fix the issue. The page always scrolls.
* This same bug happens for another game built with GDevelop: https://moxvallix.itch.io/st-ufo-adventure
* Running the game in fullscreen mode works fine: https://itch.io/embed-upload/1940180

**Comment by arthuro555** [comment]
I might have a workaround. Try to make that in a Js event. It needs to be executed once only. 
```js
document.onkeydown = function(e) {
    if (e.preventDefault) {
        e.preventDefault();
    };
    e.returnValue = false;
    document.onkeydown(e);
    return false;
};
``` 
It's a bit hacky and untested but should disable scrolling. I don't think the game should disable scrolling on the whole page though.

**Comment by 4ian** [comment]
Thanks for the detailed bug report :) 

> I don't think the game should disable scrolling on the whole page by default though.

It's a good question... arguably if the event are captured by the game, it means that it's focused and so should be safe to prevent scrolling. But we still want to allow people to use arrow keys and any key in general when the game is embedded as an iframe - something to do with the focus?

**Comment by PascalLadalle** [comment]
For [this game](https://gleeson.itch.io/shrubnaut), for example, you need to click on the page outside the game for the space bar to work (scroll), even though that key isn't used in the game.
I think this should be the standard behaviour.

**Comment by arthuro555** [comment]
If it is standard it cannot be disabled. That is why IMO the best would be to add an action or game property (the last ones are a pain to add tho) for toggling this behavior.

Arthur.

________________________________

**Comment by Bouh** [comment]
Fixed in https://github.com/4ian/GDevelop/pull/2589
