### ISSUE TITLE
cordova-build shown in the UI could be named Android Export instead

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1421]
## Describe the bug
When you select export Android for get an .APK, in build list we see an cordova-build in progress.

Should be called Android or apk export, for something associate with Android export.
I know you use cordova behind for build the apk and that's why wee see cordova but it can be a source of misunderstood.

## Reproduce
Click on
![image](https://user-images.githubusercontent.com/1670670/74184962-072d7f80-4c48-11ea-9b4f-951f97dd7c5b.png)

Wait and see in build list.
![image](https://user-images.githubusercontent.com/1670670/74184938-fda41780-4c47-11ea-8a94-68a27fe7b2d5.png)

## Other details
beta 88

**Comment by Kalovelo** [comment]
👋 Hello! 👋
Could I work on this issue?

@4ian

**Comment by Bouh** [comment]
Yes sure you can @Kalovelo, no need to ask, you're free to start what you want :)
Open source allow to work on what you want, so don't hesitate and when you have an possible fix open your own PR 🤓

**Comment by 4ian** [comment]
Still useful in case you want to do something quite large or want to make sure people are aware you're trying something. But yeah feel free to go ahead! :)

**Comment by Kalovelo** [comment]
I updated the build title by adding "apk" into parenthesis ( result : "cordova-build(apk)" ).
I changed localhost to gdevelop-app-local but a CORS problem occurred so I had to test it using storybook.
Do you consider the new name change suitable?
I will proceed with the PR as soon as possible!
