### ISSUE TITLE
Breakout example

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1433]
As per the Trello card, here is an updated version of the breakout.
I fixed a few bugs, I added some features to make it more enjoyable, I used lighter resources and I made a bonus version with Physics 2.0 which I find much better.
[NewBreakout.zip](https://github.com/4ian/GDevelop/files/4209085/NewBreakout.zip)

**Comment by 4ian** [comment]
Thanks!
I think we could fix some strange behaviors of the ball by reworking the Bounce behavior - which does not work well when the ball is colliding multiple bricks. Apart from that, looks nice :)

**Comment by 4ian** [comment]
Finally had the time to update the game for next version. It's also updated in the web-app right now: https://editor.gdevelop-app.com/?project=example://breakout (you may have to clear your cache).

Thanks for improving this! :)
