### ISSUE TITLE
Examples not work

### ISSUE THREAD

**Issue by Torguen** [4ian/GDevelop#1434]
## Describe the bug
On the web, some examples do not work, they are not loaded.

## To Reproduce
Run the example "Controller input" or "Find diagonals"
![1](https://user-images.githubusercontent.com/19652075/74602666-70c7e680-50ab-11ea-8890-b7a7efa1226f.png)
![2](https://user-images.githubusercontent.com/19652075/74602668-732a4080-50ab-11ea-8a9f-bcd8041f9f4e.png)

## Other details
* Include any OS/browser version/smartphone that you're using
win10 64
chrome ver 80

* Which version of GDevelop are you using? The desktop app or the web-app?
web-app

* Add any other context about the problem here.

**Comment by arthuro555** [comment]
Indeed, but there also isn't any controller input example. Maybe it is meant to be the multiplayer-platformer-with-gamepad example? This sone isn't on the website at all. Anyways, the problem doesn't come from the gdevelop software so it should be moved to https://github.com/4ian/GDevelop-website as it isn't a software issue but the website that has outdated links apparently.

**Comment by 4ian** [comment]
Fixed the links, the website was outdated. Ideally we would have a CI on GDevelop-website repository that would update the ExamplesInformation.js file (by getting it from this repository) every day and push the changes (if any).
