### ISSUE TITLE
GDevelop.js doesn't seem to be working correctly in a node environment.

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1435]
I am not sure if I didn't do something right but this example code doesn't work:
```
const gd = require('libGD.js')();
let project = new gd.Project();
```
With an error telling that the apply method of the class is undefined, while typing the following example code in the inspector console on a blank HTML file that only loads libGD.js through a script tag works: 
```
let p = new gd.Project();
```
Is this an issue with GDevelop.js or am I doing something wrong? This should work as it seems to be used the same way in https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/setupTests.js .

Edit: little additional note I also tried to set a 15 seconds timeout to the second line to be sure the gd module loaded completely but I still get the same error.

**Comment by 4ian** [comment]
It's a promise like interface:

```
const initializeGDevelopJs = require('libGD.js');
initializeGDevelopJs().then(gd => {
  const project = new gd.Project();
  // Do whatever you want.
});
```

See scripts for example:
https://github.com/4ian/GDevelop/blob/master/newIDE/app/scripts/extract-reference-document.js
https://github.com/4ian/GDevelop/blob/master/newIDE/app/scripts/update-examples-information-from-resources-examples.js
(etc)

**Comment by arthuro555** [comment]
Oh, ok thank you, I will try that. But why does it works without any promise like interfaces on the browser?

**Comment by 4ian** [comment]
It does not work without promise :) The promise is launched, waited for, and then a global `gd` object is set so that it can be used everywhere (mainly for historical reasons).

See the file you've linked, it's doing exactly what I'm describing.

**Comment by arthuro555** [comment]
Ok thank you very much for your time! I have a small question left however. How do I let GDevelop.js know where Runtime files are? So that I can use export for example. Do I have to make it a node module like import GDJS Runtime does?

**Comment by 4ian** [comment]
You have to:
- Know the path to the `newIDE/app/resources/GDJS/Runtime` folder (that was copied by import-GDJS-Runtime.js). You probably know this because you know where you script is located.
- Pass it to `gd.Exporter`, as second argument.

You also need to pass a `gd.AbstractFileSystemJS` to `gd.Exporter` as first argument. See how it's done here:

https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/Export/LocalExporters/LocalCordovaExport.js#L84-L88

**Comment by arthuro555** [comment]
I meant "Can I choose the path to the runtime files", because I don't want my app to run in a react app, so putting it into the resources folder isn't what I want

Arthur.

________________________________

**Comment by 4ian** [comment]
Then you need to do an "import-GDJS-Runtime" for your app too yes :)

**Comment by arthuro555** [comment]
Yes but how? How can I tell gd the location of the runtime files?

**Comment by arthuro555** [comment]
Oh wait NVM my email programm cutter off the end of your message about finding GDJS and passing it to the exporter :man_facepalming: sorry and thank you for answering my questions!
