### ISSUE TITLE
Object name not renamed triggers an error

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1436]
## Describe the bug
If you right-click on an object and choose Rename, but do not rename the object, it triggers a same name error, [like it used to do with scenes](https://github.com/4ian/GDevelop/issues/958).
![image](https://user-images.githubusercontent.com/25978830/74614688-59741200-511a-11ea-84b4-a01a3d17cda9.png)

**Comment by 4ian** [comment]
@Bouh @arthuro555 If anyone want to pick this, should be a quick fix! ;)

**Comment by Bouh** [comment]
Oh yeah i see this too, sorry for that and thank you @arthuro555  for this fix!

**Comment by arthuro555** [comment]
I guess this can be closed now?

**Comment by 4ian** [comment]
Yes, fixed for next version. Thanks! :)

**Comment by Bouh** [comment]
Sorry the new fix from #1437 isn't the solution.
I've campare the current build with the lastest from master and i'have a problem.

When i rename the object,
Change tab and come back,
The focus is still active for rename the object.

In the current build:
I rename, i change tab, the message `Another object or group with this name already exists.` and focus is erased.

**Comment by 4ian** [comment]
You're right, the fix was not properly done, the condition should have been added after the setState
