### ISSUE TITLE
Selecting an item doesn't close the pop-up ("autocomplete" component issue)

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1441]
Somewhat similar to #859 

Actual result:
In the event list, after editing a field, the textbox remains open. Return does not work. As a result, tab navigation is lost (not disabled, the current position is lost). Esc deletes the value, which I find unusual.

Expected result:
When clicking on a field with a dropdown list (objects, variables...), the box should disappear once an item has been selected from the list or Enter or Esc has been pressed.
When clicking on a field which accepts carriage returns, the box should disappear once Esc has been pressed.

![image](https://user-images.githubusercontent.com/25978830/74774015-459feb80-5293-11ea-85fa-dbcf27b2fb2f.png)

Side question: do we really need carriage return in number fields? 🤔 

Edit: I'm using Esc to delete now, it's quite convenient 😅 still...we need a way to exit that box in number/text fields.

**Comment by 4ian** [comment]
> Esc deletes the value, which I find unusual.

Yes the autocomplete component is a bit unusual, I want to replace it at some point (that will also solve compatibility with iOS/Android/touch screens) by https://material-ui.com/components/autocomplete/

**Comment by HarsimranVirk** [comment]
Hey, I'm trying to contribute for the first time.

> Yes the autocomplete component is a bit unusual

I can't figure out exactly which component this is in the code. Is it the SemiControlledAutoComplete component in UI code?

**Comment by 4ian** [comment]
Hi and welcome!

> I can't figure out exactly which component this is in the code. Is it the SemiControlledAutoComplete component in UI code?

Yes. SemiControlledAutoComplete is currently a React component based on `Downshift` and showing a material-ui `Textfield` with `Popper`. Downshift is a bit hard to customize on some things (like the Esc button, it's not customizable at all), and have some issues on mobile (text getting reset). So I would like to have it changed to be instead based on Material-UI autocomplete: https://material-ui.com/components/autocomplete/

This is the list of props of SemiControlledAutoComplete:
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/UI/SemiControlledAutoComplete.js#L113-L134

The new component should re-implement these :)
You can run the storybook: https://github.com/4ian/GDevelop/tree/master/newIDE#development-of-ui-components there is a list of stories (visual "Test cases") for the autocomplete for you to verify that it works well.

**Comment by HarsimranVirk** [comment]
Hello again, I tried implementing the Autocomplete but I'm stuck on this error. Storybook logs this:
`Object(...) is not a function
TypeError: Object(...) is not a function
    at useAutocomplete (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:30126:101)
    at Autocomplete (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:29285:91)
    at renderWithHooks (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:191050:18)
    at updateForwardRef (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:192569:20)
    at beginWork (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:193773:16)
    at performUnitOfWork (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:197424:12)
    at workLoop (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:197464:24)
    at renderRoot (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:197547:7)
    at performWorkOnRoot (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:198454:7)
    at performWork (http://localhost:9009/vendors~main.deb221014619c0345c3a.bundle.js:198366:7)`

Also the webpack logs this warning:

`WARNING in ./node_modules/@material-ui/lab/esm/useAutocomplete/useAutocomplete.js 229:23-36
"export 'useControlled' was not found in '@material-ui/core/utils'
 @ ./node_modules/@material-ui/lab/esm/useAutocomplete/index.js
 @ ./node_modules/@material-ui/lab/esm/Autocomplete/Autocomplete.js
 @ ./node_modules/@material-ui/lab/esm/Autocomplete/index.js
 @ ./src/UI/SemiControlledAutoComplete.js
 @ ./src/EventsSheet/ParameterFields/StringWithSelectorField.js
 @ ./src/EventsSheet/ParameterRenderingService.js
 @ ./src/EventsSheet/InstructionEditor/InstructionParametersEditor.js
 @ ./src/EventsSheet/InstructionEditor/index.js
 @ ./src/stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true`

What can I do to solve it? Also thank you for such a quick response ^_^

**Comment by 4ian** [comment]
Take a look first at if you can solve the issue by yourself by Googling - because I don't know more about this autocomplete than you do, apart from me reading the docs :) 
Take a look at this: https://github.com/mui-org/material-ui/issues/19360

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by AlexandreSi** [comment]
@PascalLadalle Do you consider this issue still relevant?

**Comment by PascalLadalle** [comment]
@AlexandreSi Nope, pressing the Return key closes the selection pop-up. 👌
