### ISSUE TITLE
copy-pasting quotes

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1445]
Maybe related to #855 ?
It just happened consistently, but after closing and reopening the two instances of GD, I'm unable to reproduce it.
The issue was that copy-pasting an event that contained quotes added quotes and backslashes to it. It first happened when pasting from one instance to another, but then it would do it within the same instance.
Hero.PointX("Barrel") would become (I should have noted 🙊 ) something like Hero.PointX("\\"Barrel"\\").
That's all I have 🤷‍♂

**Comment by 4ian** [comment]
Mmm, would look like a bad application of the adapter for legacy games that use to miss the quotes... but sounds really strange. Let me know if you can consistently reproduce this.

**Comment by 4ian** [comment]
I'll close this as we don't have way to reproduce this but please re-open if you know how to trigger this.
