### ISSUE TITLE
Topdown and keystroke limit

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1446]
A nasty naughty bug. 😞 
The topdown behavior seems to be limiting the number of concurrent keystrokes to **two**, in most cases.

I have a player with topdown behavior and a classic firing using Space key condition and object creation action.
The problem is that the player won't fire if I use diagonals (press two arrows at the same time) **unless** the two arrows are Up and Right, and it won't do diagonals if I start firing before moving, again **unless** the two arrows are Up and Right.

I reproduced it using the zombie laser example, same thing.
![image](https://user-images.githubusercontent.com/25978830/74884040-8d497480-5372-11ea-9fe2-f8c15e63306a.png)

![image](https://user-images.githubusercontent.com/25978830/74883524-6d658100-5371-11ea-9dee-3d124750cc1a.png)
![image](https://user-images.githubusercontent.com/25978830/74883888-3c398080-5372-11ea-99e4-d9697c53eb09.png)

**Comment by 4ian** [comment]
You're sure it's not the keyboard that have a key pressed limitation?

**Comment by PascalLadalle** [comment]
Wrong github it seems, should have posted that on my keyboard manufacturer's 😅 
I can do tons of combinations, but not arrows and space, except for up and right...

**Comment by 4ian** [comment]
Ok good to know :) 👍
