### ISSUE TITLE
Action to release the ladder in platformer object extension

### ISSUE THREAD

**Issue by shadow00dev** [4ian/GDevelop#1448]
simulate release ladder action

can there please be a simulate release ladder action for gdevelop 

the reason I ask:

it will be very helpful

**Comment by Silver-Streak** [comment]
Isn't that just simulate jump? I don't think there is an actual "release ladder" action in the game to simulate.

**Comment by 4ian** [comment]
Added on the roadmap. See other improvements to the platformer engine that can be done on the roadmap: https://trello.com/b/qf0lM7k8/gdevelop-roadmap?menu=filter&filter=label:Feat%3A%20platformer%20engine
