### ISSUE TITLE
collisions do not disappear when a block is destroyed

### ISSUE THREAD

**Issue by vinurd** [4ian/GDevelop#1451]
the blocks have a collision of the platform. Destroyed by the touch of the other block and subtract the variable life. The block disappears.But the conflict remains. I wrote on the forum about the error. There's silence.
Please double check that the bug is not already reported in the issues list.
https://forum.gdevelop-app.com/t/the-collision-of-the-platform-object-is-not-removed-although-the-object-has-disappeared/22836/6

file game: https://dropmefiles.com/I9Ar2
lesons2 - video  https://youtu.be/6K3JUEKDszg?t=2123

**Comment by 4ian** [comment]
Please reproduce a clear example first on the forum and get another community member to validate that there is an issue. Collisions are something implemented since a very long time, it's unlikely there is a bug.
