### ISSUE TITLE
Object ID Process Automation

### ISSUE THREAD

**Issue by vinurd** [4ian/GDevelop#1452]
I've been working with the designer for a long time and I keep running into the same problem. ID / Yes I found a solution through variables. They work. But I have to ride an incredible bike. Not everyone will be able to repeat it. And here in the next project there was a question of 1000 objects.With which the player must determine the collision and only with them should the action occur. The problem is visible in the video recorded on creating the farm game.
https://youtu.be/QsYZWirBrHA

in this tutorial, I'm creating this incredible way to check 15 objects for a collision and that would only work with the one that caused the collision. This is an incredibly time-consuming process. But the most important thing is that there is no automatic ID. you have to register everything with your hands. And here is the question of objects should be 1000.
I ask you to solve this problem with the ID and definition of object interaction. Make it easier. If it's real.

**Comment by 4ian** [comment]
Please ask these questions on the forum, GitHub is only for development related discussions and verified bugs. Thanks! :)
