### ISSUE TITLE
 Top right icons not updating properly when opening Yarn file

### ISSUE THREAD

**Issue by wapiti4** [4ian/GDevelop#1456]
## Describe the bug
This is as written in forum: [https://forum.gdevelop-app.com/t/bug-top-right-icons-not-updating-properly-when-editing-a-yarn-json-file-in-external-event/22867](url)

When opening a JSON in Yarn Builder from an External Event page, going to another tab will not update the buttons as it should : 
![image](https://user-images.githubusercontent.com/54391800/75111218-6a6cd800-5672-11ea-9c2d-8c30242df0c7.png)
Note the selected tab is on events of a scene, but there is no preview/debug button - these buttons belong to External Events.
Selecting any tab will update the buttons properly again.

## To Reproduce
1. Create a blank new project, a Scene, and an external Event
2. Open the new Scene from left menu (so it displays on tab)
3. Go to the External Event, choose “NewScene” when asked where to use it
4. Create a new event, and create a “Load dialogue tree from JSON File” action, edit the JSON file (not neccesarily have to edit anything, just closing it)
5. Go to any other tab other than the External Event. The buttons will not update until you click on another tab.

A gif (hope that's ok):
![bug1](https://user-images.githubusercontent.com/54391800/75111237-97b98600-5672-11ea-8477-5ecd9c9edbe4.gif)

## Other details
Screenshot symptom has occured in another way, but I don't remember it / can't reproduce. 
This is done in Windows beta88 desktop app.
I've used search but didn't find this yet - apologies if duplicate.

**Comment by Silver-Streak** [comment]
This appears to be fully resolved, buttons are updating as expected even after editing yarn files for me now in 5.1.157
