### ISSUE TITLE
Field hidden in part in Function editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1461]
Inside the function editor, I can't see the whole input field of my root-level Repeat event.

When the right pane takes more than half of my monitor:
![image](https://user-images.githubusercontent.com/25978830/75117658-b2402f00-5673-11ea-8d5a-dc81a74e54b5.png)

When the right pane is less than half of my monitor:
![image](https://user-images.githubusercontent.com/25978830/75117665-cab04980-5673-11ea-832b-5cb9fcefbf0d.png)

**Comment by 4ian** [comment]
I'm not exactly sure how the size of the pane has an influence on this, could you make larger screenshots to be sure?

**Comment by PascalLadalle** [comment]
You are right, it's not related to the size.
Further testing reveals it's hidden by the Behaviors title bar, no matter the size of the panes.
![image](https://user-images.githubusercontent.com/25978830/75119265-7c09ac00-5681-11ea-89ef-c1f7ce20e34b.png)

**Comment by Bouh** [comment]
The mosaic-window-toolbar draggable use an a-index of 4
![image](https://user-images.githubusercontent.com/1670670/84945904-281b4b00-b0e8-11ea-936d-3fa1562d9bfe.png)

Then we can just increase the z-index of the InlinePopover to 5.
![image](https://user-images.githubusercontent.com/1670670/84946005-4c772780-b0e8-11ea-891b-1b8a3f5d0308.png)
If it's ok i can open an PR for it.

**Comment by 4ian** [comment]
That sounds reasonable! 👍

**Comment by Bouh** [comment]
This issue can be closed.
