### ISSUE TITLE
Ghost collision mask

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1463]
From user 'vinurd' on the [forum](https://forum.gdevelop-app.com/t/the-collision-of-the-platform-object-is-not-removed-although-the-object-has-disappeared/22836):
![image](https://user-images.githubusercontent.com/25978830/75119294-bf641a80-5681-11ea-88bf-ad71dcdbac12.png)
When this specific block is deleted, the hitbox remains, even though the instance is deleted (confirmed in debugger). Instance UID is 114. 
Testing collision Player-rock shows that Player is not in collision with rock when it is standing on this "ghost".
![image](https://user-images.githubusercontent.com/25978830/75119362-9abc7280-5682-11ea-9a81-30a42d75f452.png)

Nothing special in the json for that object:
![image](https://user-images.githubusercontent.com/25978830/75119309-f0dce600-5681-11ea-9c41-9d2859a05561.png)

Project link:
https://dropmefiles.com/ZXHrj

I tried a few things, including removing all Cyrillic letters from the project, no luck.
vinurd said that if he deletes that rock, the bug is moved to another one.

**Comment by 4ian** [comment]
Can you explain the exact steps to reproduce the issue? I've not being able to have the issue, getting this Rock destroyed does not produce a ghost for me.

(if possible when posting a project like this, specify the scene name, and what to do, this greatly improve the time for me to inspect these bugs. Thanks!)

**Comment by Bouh** [comment]
I've spend 2 hours on this and i've found nothing.
The eventsheet should be simplify, remove useless events not related to punch, rocks and player.
Same for objects on scene. Keep the minimum.

**Comment by PascalLadalle** [comment]
I didn't need to do anything special to trigger the bug, just moved the player straight to that rock, clicked several times to punch/delete it and jumped on the ghost. 
Strange that the bug doesn't occur with you. 🤔 
Here's a video from vinurd: https://www.youtube.com/watch?time_continue=60&v=nyoAlImRDWE&feature=emb_logo

I agree that the events aren't very clean, but the instance is deleted, so the collision should be impossible...right?

**Comment by Bouh** [comment]
I had the problem, I spent two hours trying to figure out why he was there.
The user should delete anything that is not useful for the bug.
I no longer debug complete projects there is too much possible interference. And it's a waste of time searching through all the events and scenes.

**Comment by zatsme** [comment]
Long time no see 😃

I just had to try this as I remembered from last year, maybe longer, the same issue from before.

I cannot find the old forum post/issue but I tested this and it's as before....

Rock in the example has 2 sets of animations. the first anim 0 is 59px X 64px whereas all the other ones are 64 X 64px

Change the initial Rock anim to 64x64 and the problem goes away!

4ian I can't remember what the outcome was, but maybe its some restriction in pixi?

Zat 😄

**Comment by PascalLadalle** [comment]
Yes, I remember that issue, it was flagged in the official platformer example, if my memory serves me right.
Well done 👍 
So it's not only inside a single animation, the size must match in all the animations.

If it can't be fixed, can we have a warning, below the object name or next to the Help button, either always (easier), or only when different sizes are detected?
And we should update the resources of the platformer example to avoid issues for people experimenting with it.

**Comment by 4ian** [comment]
Interesting, might be more like a edge case in the platformer behavior :) Any chance you can reproduce this in the platformer example or in this game but with something that automatically shows the bug?

**Comment by PascalLadalle** [comment]
I think that's the bug zatsme was talking about: https://github.com/4ian/GDevelop/issues/909
Not quite the same, but related to different sprite sizes.
