### ISSUE TITLE
Top down movement behavior does not allow moving North-West

### ISSUE THREAD

**Issue by pringon** [4ian/GDevelop#1465]
## Describe the bug

After enabling `Allow Diagonals` you are able to move diagonally in any direction except North-West (up + left).

## To Reproduce

1. Create an example isometric game
2. Launch a preview of the game
3. Press left arrow key
4. Press up arrow key

## Expected behavior

The character starts moving towards NW (diagonally top-left)

## Resulting behavior

The character keeps moving left.

## Other details
* This is a browser issue
* OS: `Linux arch 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux`
* Browser: `Chromium 80.0.3987.106 Arch Linux`
* Which version of GDevelop are you using? Web app

**Comment by wapiti4** [comment]
Do you mean this isometric example game? That works fine for me.
![image](https://user-images.githubusercontent.com/54391800/75218162-5b05a000-57d4-11ea-8752-04c2d0122081.png)

Suggest you to check if your keyboard has a problem with Up+Left: in this page, just press the two keys together, and see if they are grey at the same time. 
http://keyboardchecker.com/

**Comment by pringon** [comment]
You are right. Sorry for that will close this now. :D
