### ISSUE TITLE
Upgrade exported games to latest Electron version

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#1469]
We should upgrade to the latest Electron version. This might solve some crash issues/incompatibilities and is a good idea to be on the latest versions.

Thing to do:
- [ ] Check the release notes between the current Electron version and the new one
- [ ] Verify if there is anything notable or API that must be updated.
- [ ] Upgrade in the package.json
- [x] ~~Check if the whole app seems to work well (in particular: preview, test multiple games, debugger, export to Android and macOS/Linux/Windows).~~ Already done for the IDE.
- [ ] Check if we can also upgrade Electron for the games (`GDJS/Runtime`)
- [ ] Do (or ask someone) to do a test on Windows/macOS/Linux.

**Comment by jerrybuks** [comment]
can I work on this?

**Comment by 4ian** [comment]
Yes feel free to go ahead and give it a try :)

**Comment by jerrybuks** [comment]
okay, I'm on it

**Comment by jerrybuks** [comment]
@4ian I did the update for both the Editor and the GDJS electron update, but I keep getting this error when I try to run a game 
  
![Screenshot from 2020-03-08 07-27-38](https://user-images.githubusercontent.com/39066907/76157808-7f377a00-610e-11ea-87a5-ac6ad253e1bc.png)

**Comment by 4ian** [comment]
This error is in the web-app, so totally unrelated to Electron - ignore it. This being said, have you run the app with Electron ? 😉

**Comment by jerrybuks** [comment]
@4ian the electron-app runs and works fine, but it also throws this error, when I click the run button, for a game
![Screenshot from 2020-03-08 19-34-06](https://user-images.githubusercontent.com/39066907/76168915-04a14580-6174-11ea-83f2-19e863cdc89a.png)

**Comment by 4ian** [comment]
Very strange. Is this working when you don't update electron?
BrowserS3GDJSFinder should NOT be used in the electron version. Can you investigate why it's used? It should be used only for the web-app.

Unfortunately I won't be able to help very much without knowing more. You have to investigate a bit more by yourself to understand why this is happening :) Check if the current version works. If yes, understand why BrowserS3GDJSFinder is even used => in electron, it should NOT be used.

**Comment by jerrybuks** [comment]
> Very strange. Is this working when you don't update electron?
> BrowserS3GDJSFinder should NOT be used in the electron version. Can you investigate why it's used? It should be used only for the web-app.
> 
> Unfortunately I won't be able to help very much without knowing more. You have to investigate a bit more by yourself to understand why this is happening :) Check if the current version works. If yes, understand why BrowserS3GDJSFinder is even used => in electron, it should NOT be used.

I think in development, the web-app is being served to electron, from the Readme file  for Gdevelop 
newIDE, it says - "You can run the standalone app with Electron. Make sure that you've launched npm start (or yarn start) in app folder before (see above) and keep it running (in development, the app is served from a local server, even for the standalone app)."

**Comment by ssangervasi** [comment]
Regarding this task:
> Check if we can also upgrade Electron for the games (GDJS/Runtime)

I went looking for this issue because I recently built my game and found that it was broken because I used some newer JS features that aren't supported in the built electron. I had specifically tested whether these features were supported in the gdev _preview_ environment and wrongly assumed the built version would match.

As of writing, here's the `process.versions` GDevelop is using:
```js
{
  "chrome": "80.0.3987.165",
  "electron": "8.2.5",
  "node": "12.13.0",
}
````
And here's what ended up in my electron build for windows:
```js
{
  "chrome": "66.0.3359.181",
  "electron": "3.0.9",
  "node": "10.2.0",
}
```

From digging around in the repo it makes sense that we end up in 3.0.9 because of this [package.json](https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/Electron/package.json). And I think the exporting code is [here](https://github.com/4ian/GDevelop/tree/master/GDJS/GDJS/IDE). But the builds are run [remotely](https://github.com/4ian/GDevelop/blob/85cfb644c368fb32e5efde773a512fe02d3b95e7/newIDE/app/src/Utils/GDevelopServices/Build.js#L41) so I'm not sure what it would take to bump the runtime version and kick off test builds using it.

**Comment by 4ian** [comment]
Thanks for checking :) Bumping the version in package.json should be all that is needed to do to use the latest version, including the remote builds.
In addition to this, we should check if there is something to update in the [main.js](https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/Electron/main.js) file (there is at least something to uncomment) and in the game engine/extensions (searching for `electron` reference). Should not be too complex, and would be a very good thing to do!

**Comment by Silver-Streak** [comment]
@4ian Looking through old issues, it appears this was merged to master a while back. Should this issue be closed?

**Comment by 4ian** [comment]
Totally! Thanks for checking :)
