### ISSUE TITLE
Unable to drag and drop objects into scene using laptop mousepad

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1473]
## Describe the bug
Using the integrated touchpad on my laptop, I'm unable to drag and drop objects from the right hand object list into the scene.

Please double check that the bug is not already reported in the issues list.

## To Reproduce
Using an HP Pavilion laptop, open a project, then open a scene which contains objects on the right. 
Attempt to drag an object from the object list to the scene,
Nothing happens. Object can be selected, and objects on the scene already can be moved around but objects cannot be dragged from the object list to the scene.
The only workaround is to click on the object, then right click on the scene and choose "add foo to scene" which seems to know right where the mouse is and places it there.

![73UcVVgqw4](https://user-images.githubusercontent.com/8691/75517537-cce81000-59b3-11ea-8283-b69de1406559.gif)

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using - HP Pavilion windows 10 laptop
* Which version of GDevelop are you using? The desktop app or the web-app? - GDevelop 5.0.0-beta88
* Add any other context about the problem here. - this seemed to work a few days ago. Perhaps there was a code push regression?

**Comment by 4ian** [comment]
Is it a touchscreen? Can you try to start drag'n'dropping on the object icon rather than on the object text?

**Comment by triptych** [comment]
Yes, I tried all sorts of combinations - strangely enough after I plugged in a mouse, everything started working again. I need to look at better steps to reproduce and I'll update the ticket.

**Comment by 4ian** [comment]
Right ok, because GDevelop check if your device is touch enabled and if so the drag'n'drop is only possible from the icon (so that you can still scroll the list on touch devices)

**Comment by triptych** [comment]
My laptop is an "all-in-one" which means the screen is tappable, but I also
have a keyboard and trackpad / mouse.

**Comment by triptych** [comment]
I see this working now if I use the icon. However, I would suspect that some folks might not know this.  Perhaps allow for a "long press" to also select an element? Or some kind of hint about this behavior? I think because I switch back and forth when I use a mouse it works to drag from text, and didn't realize that using the track pad is interpreted as touch as well.  Instead of having a feature disabled for touch, perhaps adding the icon for dragging that a touch device can use specifically?  https://www.iconfinder.com/icons/211736/drag_icon .  Or if the drag is mostly horizontal - regardless of touch or not - interpret is as a drag to scene action instead of a scroll?
