### ISSUE TITLE
Issues while renaming an object

### ISSUE THREAD

**Issue by geetesh-gupta** [4ian/GDevelop#1475]
## Describe the Bug
Similar to #1437 
Until the current name is changed, the field doesn't exit as shown in this video https://gofile.io/?c=0WFBPW . 

## To Reproduce
1. Go to 'a new project'
2. Right Click on any object name 
3. Click on rename option
4. Press Enter without changing the name
4. See error - it does not exit the field until renamed.

**Comment by 4ian** [comment]
Thanks for reporting it, this is a regression from a recent fix to avoid displaying an error message if trying to exit the renaming without having changed the name of the object.
