### ISSUE TITLE
Piskel editor's Hash error

### ISSUE THREAD

**Issue by Quarkstar** [4ian/GDevelop#1482]
## Describe the bug

I am trying to build GDevelop with the latest commit `6155606d20830dfb01299f815fb72c92afc380c4`.
I found that the hash of piskel-editor downloaded from https://github.com/4ian/GDevelop  is `b8e4d57b160ff93d3680168cd271af795412ea6c4c0da321aee2946345c7fb75` and the excepted one is `e02f67866b338b4cc577e1ffa48f55f52cd520ed751dccc6f0931e3c1b995de0`.

## To Reproduce
1.  cd newIDE/app && npm install

**Comment by 4ian** [comment]
This is working on my mac, needs some double check about why this is wrong

**Comment by Quarkstar** [comment]
Thanks for you reply!

### more tests 
I have tried it in win10 and ubuntu18.04 with node -v10 and results is the same.
1. Directly download piskel-editor.zip with browser from https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta82/piskel-editor.zip
2. unzip it with `unzipper` module in javascript and linux-unzip 
3. get hashcode by running the  following code
```javascript
const { hashElement } = require('folder-hash'); 
var basePath = 'piskel-editor'
hashElement(basePath, { algo: 'sha256', encoding: 'hex' }).then(
    folderHashResult => {
    const actualFolderHash = folderHashResult.hash;
        console.log(actualFolderHash);
        return;
});
```
And I get  `b8e4d57b160ff93d3680168cd271af795412ea6c4c0da321aee2946345c7fb75` in both cases.
Is there something wrong with my environment?

**Comment by 4ian** [comment]
I think there is nothing wrong :) Might be an issue on macOS actually, something like a file not extracted the same way.. if you wish you can make a PR that fix the hash, and I'll also give it a try.

**Comment by Quarkstar** [comment]
Yes, I would like to fix it. Thank you!
