### ISSUE TITLE
Tooltip for "Properties" and "Objects" panels is "[object Object]"

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1484]
## Describe the bug
Tooltip for "Properties" and "Objects" panels is "[object Object]"

## To Reproduce
Open a project and view a scene.
Make sure the properties panel is open.
Mouse over the title "Properties"

![GDevelop_5_SZoCntxooT](https://user-images.githubusercontent.com/8691/75616155-89e88280-5b02-11ea-95fe-63a838f62069.png)

I can't take a screenshot with the tool tip at the same time.

## Other details
Windows 10 laptop.
beta88
desktop version

**Comment by gautamv95** [comment]
I would like to work on this, can you suggest me correct names for each of these tooltip fields?

**Comment by 4ian** [comment]
Sure, you must first investigate why "[object Object]" is shown. Probably just hide the tooltip or show a description that we can decide on for each panel (in this case, feel free to go ahead with your ideas, and we can discuss in the PR if these descriptions can be improved)

**Comment by blurymind** [comment]
I assume it's trying to read what is an object as a string for some reason

**Comment by 4ian** [comment]
Yep, there is an object passed to a `title` or some other attribute somewhere - might be inside react-mosaic.

**Comment by ozata** [comment]
I am checking this issue out.

**Comment by aman-dave** [comment]
Hello,
I have solved the above-mentioned issue.
@4ian kindly look at the PR!

**Comment by aman-dave** [comment]
@4ian @blurymind 
I tried solving the issue but there seems to be a roadblock.

The issue arises as we are passing title in various `app/src/{Scene, Resources}Editor` as:
`title: <Trans>Objects</Trans>`
Basically, converting the normal "Objects" string into an object.

When I console logged `editor.title` in `app/src/UI/EditorMosaic/index,js` , it gives:
```
>$$typeof: Symbol(react.element)
...
>props:
>    > id: "Properties"
...
``` 
After seeing this, I passed title as `editor.title.props.id` in <MosaicWindow> and it worked, which can be seen in the screenshots attached in the PR. But I forget to run the tests and as you can see it failed the FLOW test.
The failed test case says: 
```
Cannot get title.props because:
 • property props is missing in $Iterable [1].
 • property props is missing in Boolean [1].
 • property props is missing in Number [1].
 • property props is missing in React.Portal [1].
 • property props is missing in String [1].
 • property props is missing in null [1].
 • property props is missing in undefined [1].
```

I tried searching for solutions to this, but I can't find anything concrete. 
Reference: https://github.com/facebook/flow/issues/1964, 

The library we are using for MosaicWIndow (https://github.com/nomcopter/react-mosaic) expects `title: string`

**Comment by HarsimranVirk** [comment]
> I assume it's trying to read what is an object as a string for some reason

Yes, this is exactly what is happening. 

> Yep, there is an object passed to a title or some other attribute somewhere

title is a `<Trans>` component, and the div's title cannot read it and shows object instead. 

![Screenshot from 2020-03-04 02-37-39](https://user-images.githubusercontent.com/39851078/75820335-2d1aef80-5dc2-11ea-8d96-2e7f790e4142.png)

`const Div = (props) => {`
` <I18n>`
`   {({ i18n }) => (`
`     <div title={ i18n._(props.title)}>`
`        { i18n._(props.title) }`
`      </div>`
`   )}`
` </I18n>`
`}`

title: <Div title={t`Properties`}/>
title: <Div title={t`Objects`}/>
title: <Div title={t`Objects Groups`}/>

This can fix the issue, should I implement it @4ian @blurymind ?

**Comment by 4ian** [comment]
See my comments on https://github.com/4ian/GDevelop/pull/1490 :)
