### ISSUE TITLE
Misalignment of the context/pop-up menu

### ISSUE THREAD

**Issue by modiprabal** [4ian/GDevelop#1492]
## Describe the bug
A UI error, on right click on object while creating a project, pop-up menu is far away from cursor/object. A screenshot is attached showing the error.
![Screenshot from 2020-03-04 03-01-45](https://user-images.githubusercontent.com/42889548/75822698-66555e80-5dc6-11ea-999b-735023ea739a.png)

## To Reproduce
1. Go to 'Create a new project.'
2. Right click on any object.
3. See error.

## Other details
* Using Chrome version 80.0.3987.106-1 on Ubuntu 18.04
* Using web-app of GDevelop version 5

**Comment by 4ian** [comment]
Not sure what the cause is, seems related to `ElementWithMenu` used along with `ListItem`? Needs some research, I think it used to work better before.

**Comment by modiprabal** [comment]
@4ian I will try to look into the problem. If you are saying it worked better before, I will check out the previous versions and find where the problem started.

**Comment by 4ian** [comment]
I'm not entirely sure though ;) But can be a good idea to check a few version back (a few months ago, a few weeks ago, etc...).
