### ISSUE TITLE
Upgrade to Box2d.js 2.3.1 wasm version

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#1493]
See the associated card on the roadmap: https://trello.com/c/4iXuaS7F/410-upgrade-to-box2djs-231

We should upgrade to latest version of Box2d.js, the 2.3.1 (https://github.com/kripken/box2d.js/tree/master/build).

Questions to solve:
- [ ] Is it ok to go with the WebAssembly version - or do we stick to asm.js?
- [ ] As we're upgrading the Physics engine, games can behave slightly differently. Should we add an option to allow old games to stay on the old, legacy version?

Check that:
- [ ] Everything still works (try the example using physics, check that all methods used in the source code by the Physics behavior on `Box2d` object are defined by the new version (might have been some renaming - even if I don't think so).
 
Test on:
- [ ] Android
- [ ] iOS
- [ ] Desktop: Chrome, Firefox, Safari.

This should give better performance and solve bugs like reloading multiple times a scene with physics that can crash the game (because of a memory leak or mishandling of memory in the current version of Box2d.js I think!)

**Comment by zatsme** [comment]
Firstly I thought this was a JS, so what needs updating in GD Core 🤔

Secondly, could we consider this as its the same library, but written in JS and includes fluid dynamics from liquid fun. 😁

https://github.com/flyover/box2d.js

Testbed.. 

https://cdn.rawgit.com/flyover/box2d.js/master/Box2D/Build/Testbed/index.html

This would be a great update to physics 👍

**Comment by 4ian** [comment]
There might be some tiny changes to do to allow the export to choose between the old version of Box2D or the new one, according to some settings.

> Secondly, could we consider this as its the same library, but written in JS and includes fluid dynamics from liquid fun. 😁

Interesting! Can be another enhancement. Though it's 4 years old so you probably want to use: https://github.com/flyover/box2d.ts
It also needs comparison in terms of performance, between this version and the one we're using that is using asm.js (or wasm potentially in the future).

**Comment by zatsme** [comment]
Of course we would use the latest version 👍 , as long a GD can support the script, I thought we were limited to ES5 style JS ?

After we upgrade current physics to v2.3.1, the code is 5 years old, so if we can use this new library it would give all the existing functionality and the liquidfun additions and is currently updated and supported 👍

Perhaps you can add a trello for this and maybe point me in the right direction as to how we call this library from a GD5 Extension 🙏 

In the meantime I will test the 2.3.1 version against the current one 😄 

Zat.

**Comment by 4ian** [comment]
>  as long a GD can support the script, I thought we were limited to ES5 style JS ?

In extension and GDJS yes. But you would not put the TypeScript files of the Box2d library, you would copy the generated JS file. Browsers/JS engines can't run Typescript, it must be compiled before :) 

> Perhaps you can add a trello for this and maybe point me in the right direction as to how we call this library from a GD5 Extension 🙏

Let's consider this part of https://trello.com/c/4iXuaS7F/410-upgrade-to-box2djs-231 :) 

I would advise to start with the existing extension (`Extensions/Physics2Behavior`), replace the `box2d.js` file with either Box2d.js 2.3.1 or the new library, and see if it works out of the box (maybe some adaptations for 2.3.1) or needs changes in `physics2runtimebehavior.js` (most probable because even if the interface will be more or less the same, some things might be done slightly differently).

**Comment by zatsme** [comment]
I have been looking at this for 7 hours now 😱

Neither of the two 'upgrades' are drop in solutions so I thought I might as well try to get the newest and most functional one working 😋

I have made some progress, at least it's not crashing each time I run it, but it's not working either.  I have made extensive changes to the runtimebehaviour for physics2 as theres a lot of differences and I think I've made some mistake somewhere as the actual bodies are nowhere to be seen on screen lol, but at least the scene loads without errors.

Will keep at it, much debugging to do 😄 

Zat.

**Comment by 4ian** [comment]
If it's too different from the existing version, we might have to think at making an alternative, experimental extension ("Physics3") :)

> Neither of the two 'upgrades' are drop in solutions so I thought I might as well try to get the newest and most functional one working 😋

Let's make sure it's actively supported/maintained.

**Comment by PawBud** [comment]
> If it's too different from the existing version, we might have to think of making an alternative, experimental extension ("Physics3") :)
> 
yup, you are right  I will try doing that and if there are some small bugs I will upload a PR with my doubts, I think this way the library will be imported faster.

**Comment by PawBud** [comment]
I think it is better to go with the wasm version @4ian ; I realized that after reading this blog: https://medium.com/@torch2424/webassembly-is-fast-a-real-world-benchmark-of-webassembly-vs-es6-d85a23f8e193
