### ISSUE TITLE
Error In Building standalone app

### ISSUE THREAD

**Issue by utkarshshri1016** [4ian/GDevelop#1496]
![Capture](https://user-images.githubusercontent.com/56174665/75997701-bf87d400-5f25-11ea-977a-2a3f317d392a.JPG)
## Description
The above mentioned error occurs when I try to build the Standalone app of GDevelop 5.

## To Reproduce
1. Go to '\newIDE\app'.
2. On Bash start npm here . It opens the website version.
3. Now go to '\newIDE\electron-app'.
4. On Bash run 'npm run build' here .
5. Now go to '\electron-app\dist\win-unpacked' and run GDevelop 5.
6. See Error.

## Other details
* Occurring in Windows 10. But as far as i know it can happen in other OS also.
* Error only in Desktop version. The Website version is working fine.
* Electron is already installed in the system.

**Comment by 4ian** [comment]
> Electron is already installed in the system.

Which version and what do you mean by Electron installed? Electron should be packaged with GDevelop - there should be no way to replace it with another version.

Have you run the development version with `npm run electron-win`? Is it working?

This error seems due to an incompatible Electron version being used with GDevelop.

**Comment by utkarshshri1016** [comment]
> Have you run the development version with `npm run electron-win`? Is it working?
>
When I run it it shows this error.
![Capture](https://user-images.githubusercontent.com/56174665/76058828-61013b00-5fa3-11ea-9d70-9b9408d9070f.JPG)

**Comment by 4ian** [comment]
Can you confirm the version of `electron` being installed with npm?

**Comment by utkarshshri1016** [comment]
@4ian It is 8.1.0

**Comment by 4ian** [comment]
You should not have this version - you should have version 4 that is in package.json 
Being compatible with Electron 5+ is the subject of this issue: https://github.com/4ian/GDevelop/issues/1469

If you run with a newer version, it won't work unless you do the work of changing the code for the new APIs - but this should not be reported as a bug :)
