### ISSUE TITLE
After migrating to new GDevelop version - project would not work due to missing extensions

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1502]
## Describe the bug
I had created a project that used "CursorType" in the previous version of GDevelop.
After updating I immediately opened my existing project and tried to preview it.
It failed - displaying a black screen after loading to 100%.
When I opened the inspector it was complaining about not having functions for "Cursor Type". I opened the cursor type js exported  file in the inspector and it was blank. 

I wish I had taken a screen shot!

However, after going to extensions and opening the CursorType control panel, then replaying the scene it works. 

Somehow, there was some glitch in migrating the project to the new version. I don't know if this was unique to CursorType, but steps to reproduce would be:

Create a new project in beta 88.
Add the CursorType extension.
Save the project.
Upgrade GDevelop to beta 89.
Immediately open the existing project and go to the first scene.
Launch a preview of that scene.

I don't have a way to "downgrade" my GDevelop so I cannot reproduce now. And I don't know why opening the CursorType control panel fixed the issue :(

**Comment by 4ian** [comment]
> CursorType control panel

Do you mean you click "CursorType" in the project manager to open the extension in a tab in the editor? If yes that probably solved the issue because when you leave the tab (to go to a scene editor or another editor), the code for the extension is re-generated.

Looks like for some reason the code for the extension was not generated 🤔

**Comment by triptych** [comment]
Yes, that's what I meant. 
![GDevelop_5_TSZAhkfBq0](https://user-images.githubusercontent.com/8691/76150704-31653800-6062-11ea-8ac6-b0e830676506.png)

**Comment by 4ian** [comment]
Right so now the question is: how it is even possible that extension code was not generated 🤔 I'm unsure how this could be related to a GDevelop update.

**Comment by triptych** [comment]
Is there a way to "downgrade" my gdevelop app back to a previous version? Then i could try to reproduce .
I do know that the project worked before I upgraded. I manually upgraded, opened the project and it failed on preview as I mentioned above.

**Comment by 4ian** [comment]
You can download previous versions from the GitHub releases page :) Should be enough to give it a try

**Comment by triptych** [comment]
Thanks I'll try to recreate the issue.

**Comment by triptych** [comment]
Unable to reproduce. If I see it happen again I'll capture the errors.

**Comment by 4ian** [comment]
Alright thanks for checking!
