### ISSUE TITLE
please add a condition named....

### ISSUE THREAD

**Issue by twistcharlie** [4ian/GDevelop#1504]
please add a condition that would maybe be named 
any key released (it would be like key released but instead of 1 key it will be all keys)

also if you know a simple way to do this please tell me

**Comment by PawBud** [comment]
Can you please elaborate? with questions like what is the use of this condition and in which component do you want to "fit" it?

**Comment by 4ian** [comment]
Please use the forum or the Discord channel first - GitHub is only for structured development discussion. Thanks!

**Comment by twistcharlie** [comment]
but I want it to be added its a request 
@4ian

**Comment by 4ian** [comment]
As discussed please do a request by following exactly the template and all that is required :)
