### ISSUE TITLE
Accessibility: Add a context menu to scenes under project panel for scene variables

### ISSUE THREAD

**Issue by triptych** [4ian/GDevelop#1505]
## Describe the bug
Please see this thread:

https://forum.gdevelop-app.com/t/creating-editing-scene-variables-feature-request/23191

The ask is that when you right click on a scene from the Project view you see an "Edit Scene Properties" option.

Here's the context menu:
![image](https://user-images.githubusercontent.com/8691/76153508-c4fa3100-6081-11ea-8e9b-38e42fd22170.png)

this is to make it consistent -  just like the context menu under the Objects panel:

![image](https://user-images.githubusercontent.com/8691/76153516-da6f5b00-6081-11ea-8d7d-bc60bd2359b6.png)

The popup you see is just the same as if you right-clicked on a blank space in the scene:

![image](https://user-images.githubusercontent.com/8691/76153544-26ba9b00-6082-11ea-8f2e-4278b04ad2f9.png)

Note the "Edit Scene Variables" button there. 

This would allow for the discovery of editing scene variables just like object variables and global variables.

**Comment by PawBud** [comment]
I would like to work on this issue. Can you please guide me ?

**Comment by 4ian** [comment]
Look at `ProjectManager/index.js` and `ScenePropertiesDialog`.
Looks where ScenePropertiesDialog is used and how/if you should move its usage.

**Comment by PawBud** [comment]
Understood @4ian. If I have any more issues then I will mention them here.

**Comment by PawBud** [comment]
@4ian can you please elaborate more. I have been trying it for some time and I just need some help.
Thanks :)

**Comment by 4ian** [comment]
Have you located where ScenePropertiesDialog is used? Do you understand how it's opened? 
If you used React before, do you have an idea about what to do? (if not, read some React tutorials before attempting anything ;)).

**Comment by PawBud** [comment]
Sure thanks a lot for helping @4ian

**Comment by PawBud** [comment]
I am aware of it @4ian it is just that somehow the index.js inside the _MainFrame_ is showing errors as I try to resolve the errors in ProjectManager/Index.js

**Comment by PawBud** [comment]
any idea how to resolve it? I can share the precise errors that I am getting while trying to import the ScenePropertiesDialog if needed :).

**Comment by jimil749** [comment]
@4ian I was just tinkering with code and tried to implement the ScenePropertiesDialog like done in the `SceneEditor/index.js` and just found one minor issue. Inside of `ProjectManager/index.js` layout is not defined which is required by ScenePropertiesDialog. 
I tried defining layout in props but of no use (Like done in `SceneEditor/index.js`). I tried to console log the layout props which yields 'undefined'. What I'm asking is that where is the 'layout' prop coming from and how to use it.

**Comment by PawBud** [comment]
well, technically it is defined as 

> layout: glayout.

**Comment by PawBud** [comment]
Moreover, how were you able to add it in the Properties menu @jimil749?

**Comment by jimil749** [comment]
> well, technically it is defined as
> 
> > layout: glayout.

I think its gdLayout, but even after doing that, it logs undefined on the console! The value into layout props is undefined for some reason, that I'm not able to figure out currently



> Moreover, how were you able to add it in the Properties menu @jimil749?

Look at `ProjectManger/index.js' and check where the other menu items are rendered! :)

**Comment by PawBud** [comment]
I definitely tried everything but I couldn't really make the Scene Properties Dialog run for some reason, although I will keep trying.

**Comment by PawBud** [comment]
any updates @jimil749 @4ian. Could anyone of you add a context menu for SceneVariables?

**Comment by PawBud** [comment]
@4ian I tried my best to solve this bug but unfortunately I couldn't come up with a solution. Can you further guide me?

**Comment by 4ian** [comment]
I have lots of other things to review and to do myself in a limited time every day so I would prefer a suggestion from you that I can then advise.
Here, you need to identify which React components must be opened, identify where to open them, what are the props they need and how to pass them. It's a good exercice that is fairly common in React: finding components and props, understanding what they do, seeing what you have in your state.

**Comment by PawBud** [comment]
Oh ok sure, yea .. is it ok if I post some screenshots explaining what I am trying to do & what its output is?

**Comment by 4ian** [comment]
You can ask questions but do this in a PR so that I can see your code and ask questions as focused as possible :)

**Comment by PawBud** [comment]
Thanks a lot. I will post the screenshots in a new PR as you advised.

**Comment by NilayMajorwar** [comment]
@Somtozech Are you still working on this issue? I want to try this one.
