### ISSUE TITLE
Naming inconsistency in newly created scenes

### ISSUE THREAD

**Issue by Dilshaad21** [4ian/GDevelop#1507]
## Describe the bug
The naming when new scenes are created is not consistent with the previous one.

![Screenshot from 2020-03-08 15-02-10](https://user-images.githubusercontent.com/45489945/76160248-736ba800-614e-11ea-807c-4537987c963d.png)

## To Reproduce
1. Go to Project
2. Click on Add a New Scene

**Comment by geetesh-gupta** [comment]
Hi @Dilshaad21, I don't think it is a bug but I think it can be an enhancement.
By default, I think it is set to create NewScene# with # incrementing every time a new scene is created. This can be updated to create a new scene with the name same as the scene name after which this new scene is created by appending an incrementing number to it. 
I will try to work on it. @4ian what's your opinion?

**Comment by Dilshaad21** [comment]
@geetesh-gupta the issue is that when a new scene is created it is also named as `NewScene`. Rather it should be named as `New scene2`.

**Comment by geetesh-gupta** [comment]
I saw your PR, it's good but I would like to suggest instead of hardcoding 'New scene', the name can be made to be picked by current index of the old element from the scenes list and then incrementing/appending next count to it.

**Comment by Dilshaad21** [comment]
I think there's no need to increment it from previous name of the scenes, as by default newly created scenes must be named as `New scenes` which the user can change later on if required.

**Comment by geetesh-gupta** [comment]
The point why I am suggesting this because currently it will create new scenes like this, if added from inbetween the list.

![image](https://user-images.githubusercontent.com/34645022/76161450-bb43fc80-6159-11ea-85bc-c783cd71497a.png)
So, as can be seen that these names are not structured.
I agree with you that it is not required, but it can be a good enhancement.

**Comment by Dilshaad21** [comment]
@geetesh-gupta got that. It can be done using sorting.

**Comment by 4ian** [comment]
The title of the issue if vague. Can you update it?
