### ISSUE TITLE
Request for Export Popup to close when clicked out of its area

### ISSUE THREAD

**Issue by utkarshshri1016** [4ian/GDevelop#1517]
## Description
It will be nice if the 'export the game' popup closed itself like any popup does i.e. when we click outside of its area. 
The list of instances and layers editor do already close themselves when clicked outside of its area.

![image](https://user-images.githubusercontent.com/56174665/76340945-60113600-6322-11ea-8f2f-3aa508528e77.png)

I believe It will make the application more user friendly .

**Comment by amanbora** [comment]
Would like to work on this issue for gsoc 2020, I'm new to Gdevelop so I might need some guidance initially

**Comment by utkarshshri1016** [comment]
I am also willing to work on this. But I will need some help.

**Comment by geetesh-gupta** [comment]
I was currently working on another issue involving Dialogs and I found out that this issue can be solved using some modifications in the Dialog component. So, I would like to suggest you explore the Dialog component in the UI folder.

**Comment by gautamv95** [comment]
Hey, I would like to work on this issue

**Comment by 4ian** [comment]
You can start working on anything that you like without asking permission - but be sure to look at other issues that might be more strategic :)
