### ISSUE TITLE
Disabling auto-update in preferences didn't work 

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1518]
## Describe the bug
After reinstalling version 88 in connection with investigating a different bug, I turned off the auto-update feature in preferences in case I needed to do anything else with 88 (which is the case now). Upon reopening GDevelop later, I noticed that the program was automatically updated to 89 anyway.

Please double check that the bug is not already reported in the issues list.

I searched for a similar issue; there were no relevant results.

## To Reproduce
1. Reinstall version 88
2. Disable auto-update feature in preferences
3. Close and reopen GDevelop
4. Check for updates and see version 89

* Please include a link to a game if possible! N/A
* If applicable, add screenshots to help explain your problem. N/A

## Other details
* Include any OS/browser version/smartphone that you're using

Windows 8.1, Laptop, Chrome

* Which version of GDevelop are you using? The desktop app or the web-app?

89, but it was supposed to be 88 temporarily for bug reporting as per the description.

* Add any other context about the problem here.

I don't know if time passage made any difference. When I closed GDevelop, it was before bed, so there were several hours between when I closed it on version 88 and when I reopened to find 89. I will try to get some video footage if necessary while working on my new report for the text bug.

**Comment by PawBud** [comment]
I presume you are already working on this issue @Phenomena3?

**Comment by Phenomena3** [comment]
@PawBud I just reported it; don't have the knowledge to fix it.

**Comment by Phenomena3** [comment]
Here are some screenshots. Note the time at the bottom-right.

Here, I installed version 88 to gather info for the other report. 
![gdv88](https://user-images.githubusercontent.com/45985516/76486002-7a1b4900-63f4-11ea-8f8a-22f01de51aca.png)

Disabled auto-update
![changepref](https://user-images.githubusercontent.com/45985516/76486076-ab941480-63f4-11ea-8988-6acac8496a6b.png)

Closed and reopened 7 minutes later, and it is now version 89
![gd88to89updateprefoverrided](https://user-images.githubusercontent.com/45985516/76486012-80112a00-63f4-11ea-898a-27b120ade719.png)

**Comment by PawBud** [comment]
Firstly Thank you so much for reporting this issue, unfortunately I can't undertake to resolve the issue although I can assure you that someone will get on it right away.

**Comment by Phenomena3** [comment]
No problem, you weren't expected to fix it.

I'm sure 4ian or another contributor will look and respond when they have time.

**Comment by Silver-Streak** [comment]
I am no longer able to reproduce this error (I have 5 different versions installed including current, and the older ones retain the setting if I disable it), so I'm closing this out.

If someone is still able to reproduce this on 5.1.157 or newer, please feel free to open a new issue.
