### ISSUE TITLE
Multitouch default expression incorrect to the syntax checker

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1533]
## Describe the bug
In a position field, I picked the _Touch X position_ from the expression button, I left the layer and camera fields empty, and it triggers an error.

![image](https://user-images.githubusercontent.com/25978830/76688447-35c6bd80-662d-11ea-9d7d-ddabbd9c8d9f.png)

Win10 64-bit
GD5b89

**Comment by 4ian** [comment]
Yes, we should probably not add these empty parameters when they are:
- optional
- at the end of the expression
- and empty :)

**Comment by 4ian** [comment]
If anyone is interested to look at this => `FormatExpressionCall.js` is surely a good starting point.

**Comment by rishabhabhani** [comment]
Could you describe a way to replicate this error?

**Comment by PascalLadalle** [comment]
Click on Add action
Choose the Create an object action
Click on the blue button on the right of the X position field.
Choose Multitouch.
Choose Touch X position.
Don't fill the layer and camera fields.
Confirm.
> 
> Could you describe a way to replicate this error?

**Comment by GarrySan** [comment]
I wanted to take up this issue.
I cloned, installed the node modules inside the newIDE and did `npm start`, this launches the browser but I get `dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate`.

Please help.

**Comment by PawBud** [comment]
did you do it inside the `newIDE\app` directory?

**Comment by ssangervasi** [comment]
I picked this up and addressed it with PR #2024

**Comment by 4ian** [comment]
Thanks @ssangervasi!
