### ISSUE TITLE
Unable to open load dialog when clicked another button multiple times

### ISSUE THREAD

**Issue by geetesh-gupta** [4ian/GDevelop#1534]
## Describe the bug
Unable to open `load audio` dialog when clicked another button (e.g. in my case `No` button) multiple times until the event action dialog reopened. 

## To Reproduce
1. Create new `Platformer` project
2. Click on `New Scene (Events)` tab
3. Scroll down to 'Change the animation according to what the player do.' section
4. Click on the audio as given in the screenshot
![image](https://user-images.githubusercontent.com/34645022/76695688-508a4800-66a8-11ea-8003-cef6b519bc18.png)
5. Click on `Choose the audio file to use`
6. Click on `Choose a new audio file`
7. The load dialog will open
8. Click `Cancel`
9. Click on `No` button twice as given in the screenshot below
![image](https://user-images.githubusercontent.com/34645022/76695695-6e57ad00-66a8-11ea-8dd6-d8a149cb8f25.png)
10. Click on `Choose the audio file to use`
11. Click on `Choose a new audio file`
12. The load dialog will not open 

Check the below gif for the overall problem:
![loadFileDialog](https://user-images.githubusercontent.com/34645022/76695849-07d38e80-66aa-11ea-8a85-8fb1a3866ea0.gif)

## Other details
OS Details: Windows 10 Home Single Language | Version 1909 | OS Build: 18363.719
App Details: Desktop app of GDevelop version 5.0.0-beta89 based on GDevelop.js 4.0.98-0-release

**Comment by PawBud** [comment]
I can verify that the same is happening in ubuntu too.
OS Details: Ubuntu 18.04.4 LTS.

**Comment by 4ian** [comment]
This might be solved with the new autocomplete: https://github.com/4ian/GDevelop/pull/1453 that @HarsimranVirk is working on. Could you verify on editor-beta.gdevelop-app.com?

**Comment by geetesh-gupta** [comment]
It's working correctly on editor-beta.gdevelop-app.com

**Comment by HarsimranVirk** [comment]
> Could you verify on editor-beta.gdevelop-app.com (where this new autocomplete branch was published)?

@4ian I suppose this is the old autocomplete (old in the sense that it is before I used hooks, and even before HOC withStyles). Editor-beta needs to be updated I believe.

> It's working correctly on editor-beta.gdevelop-app.com

We might have to check it again afterwards :)

**Comment by HarsimranVirk** [comment]
> We might have to check it again afterwards

I've checked on my local machine and it works fine. We still have to check it on the editor-beta just to be sure. It might have a lot of bugs other than this too :)
