### ISSUE TITLE
Spinner under "All your builds" dialog spins forever in case of no builds

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1541]
## Describe the bug
The spinner under "All your builds" dialog spins forever in case of no previous builds. 

Expected behaviour :
It should spin for few seconds and alert the user that there are no builds.

## To Reproduce
1. Create a new project
2. Export project
3. Click "See all my builds" in the export dialog
4. See bug

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.
![Screenshot 2020-03-17 at 1 45 33 PM](https://user-images.githubusercontent.com/42793024/76836187-6a698d80-6856-11ea-9ad7-8b109c310f49.png)

## Other details
* Include any OS/browser version/smartphone that you're using - Mac OSX Mojave, Firefox 74.0 (64-bit)
* Which version of GDevelop are you using? The desktop app or the web-app? Web-app
* Add any other context about the problem here.

**Comment by pranavmodx** [comment]
I checked ExportDialog.js but I failed to see any spinner component. The ExportDialog component is rendered in both LocalApp.js and BrowserApp.js but there too I don't see anything meaningful passed as props.
What am I missing here? @4ian Can you help me out?

**Comment by 4ian** [comment]
Are you sure you're looking at the proper dialog? Search "This is the list of builds" in the codebase.

**Comment by 4ian** [comment]
Also check how `userProfile` is used in the codebase :) This only happens if the user is no connected

**Comment by pranavmodx** [comment]
Thanks for the prompt reply. The issue seems to be fixed now. Please review it.
