### ISSUE TITLE
Could Not Launch Preview error

### ISSUE THREAD

**Issue by PawBud** [4ian/GDevelop#1543]
## Describe the bug

It has been around 3 days since this error keeps popping up whenever I try to click the preview button. The error says it all hence I don't really see the need to describe it any further. 

## To Reproduce
1. Go to _Scene_ _Editor_
2. Click on _launch_ _a_ _preview_ _of_ _the_ _scene_ at the top right
3. See the error

**Screenshot of the error**
![Screenshot from 2020-03-17 17-27-05](https://user-images.githubusercontent.com/48093317/76854545-49646500-6875-11ea-9b94-e8ccee77fdd8.png)

## Other details
* Chrome version: **Version 80.0.3987.132 (Official Build) (64-bit)**
*The error was seen on the web-app & _**not on the desktop app**_

**Comment by 4ian** [comment]
Is this happening on editor.gdevelop-app.com?

**Comment by PawBud** [comment]
no its the local build @4ian

**Comment by PawBud** [comment]
Any suggestions as to how I can fix this bug ?

**Comment by xAtishayx** [comment]
I'm having same issue.

**Comment by 4ian** [comment]
This is fixed! This was an oversight on my side. Thanks for your patience :)
