### ISSUE TITLE
Missing keyboard shortcut for exporting project

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1547]
## Describe the bug
Not exactly a bug but a possible enhancement. There is currently no keyboard shortcut for exporting a project. It would be nice if there was one.

## To Reproduce
1. Go to File Menu
2. Observe there's no shortcut for Export

## Screenshot
![Screenshot 2020-03-18 at 10 52 48 AM](https://user-images.githubusercontent.com/42793024/76928143-a3613b00-6906-11ea-8c66-a1329bd70c0b.png)

## Other details
* Mac OSX Mojave
* Desktop app

**Comment by 4ian** [comment]
What should be the shortcut, if any?

**Comment by pranavmodx** [comment]
How about Command/Control + E?
