### ISSUE TITLE
Loss of tab navigation when renaming variables

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1561]
## Describe the bug
After typing a variable name in the variable editor, hitting Tab should switch to the value field, but Tab navigation is reset to the top of the window, making navigation very inconvenient when the variable list is long.

## To Reproduce
1. Go to any variable editor
2. Add a variable
3. Click on the name field
4. Hit tab (expected result)
5. Click on the name field
6. Rename the variable
7. Hit tab (loss of navigation)

**Comment by 4ian** [comment]
Yep I agree this is especially frustrating. Might need something to re-focus the variable that was selected :) 
Some careful React investigation to do there.

**Comment by pranavmodx** [comment]
Actually, this works sometimes. But other times it doesn't. 
It doesn't work when you finish typing the name and directly hit Tab.
It works when you click the name field again and then hit Tab.

**Comment by tushartiwariofficial** [comment]
Would like to work on this issue. I'm new to open source project contribution and GDevelop so I might need some guidance initially. Can u just tell me where and which files I need to start from?. Thank you very much.

**Comment by 4ian** [comment]
Unfortunately I can't offer guidance for everyone. Read the README to get started with the development environment, then try to find the file by searching in the source files. For example, search the name of the dialog.

**Comment by PawBud** [comment]
> Yep I agree this is especially frustrating. Might need something to re-focus the variable that was selected :)
> Some careful React investigation to do there.

what do you mean by refocusing here @4ian?

**Comment by Minisonny** [comment]
Is this caused by the difference in using the `TextField` directly instead of going through `SemiControlledTextField`? I see that the variable box use `TextField` directly cus it is not expected to be changed regularly, and onChange is missing :/

**Comment by PawBud** [comment]
I am not able to figure out as to what am I supposed to put inside the onChange prop even though I checked out other dialogs. @Minisonny

**Comment by Minisonny** [comment]
Actually now I realize it is because there is a `setState` inside `onBlur` prop of the VariableList that cause the whole dialog to rerender every time we press Tab to finnish renaming. This only happens with the name field, the value field doesn't seem to rerender the dialog.

**Comment by PawBud** [comment]
So I did a lot of digging around & concluded that We can use `shouldComponentUpdate`, but it states [https://reactjs.org/docs/react-component.html#shouldcomponentupdate](url) here that it can cause a lot of bugs, Hence I would like any suggestions from you on this @Minisonny. 
1. I also tried to basically copy the `onChange` prop, convert the `TextEditor` component to `SemiControlledTextField` and remove `onBlur` completely.  It was really not working out as done in the `value` field but it didn't work out.
2. Next, I also tried to change `onBlur` to add the functions of `onChange` but that did not work out as well.

I think 2 option is doable with some help, I am not sure if I did the required changes to `onBlur` perfectly.

**Comment by Minisonny** [comment]
Hi, I also think we can do something with `shouldComponentUpdate` or make some kind of context. And yeah, I don't think `shouldComponentUpdate` is recommended, but it works pretty well as I tried to use it. Also, if you change the name and use Tab to the value field and change it and Tab once more time, the dialog will rerender because there is a `forceUpdate` call. You may try to disable that in `onChangeValue` in the `VariableList`. It should work but I'm not sure how this would affect the variables and the way they store values.
Anw, in I bet what you did do not work because currently there exists only the function to change value, not the name, being passed to SemiControlledTextField.

**Comment by PawBud** [comment]
> Hi, I also think we can do something with `shouldComponentUpdate` or make some kind of context. And yeah, I don't think `shouldComponentUpdate` is recommended, but it works pretty well as I tried to use it. Also, if you change the name and use Tab to the value field and change it and Tab once more time, the dialog will rerender because there is a `forceUpdate` call. You may try to disable that in `onChangeValue` in the `VariableList` and return false to `shouldComponentUpdate`. It should work but I'm not sure how this would affect the variables and the way they store values.
> 
> Anw, in I bet what you did do not work because currently there exists only the function to change value, not the name, being passed to SemiControlledTextField.

@4ian, what is your opinion on this?

**Comment by Minisonny** [comment]
Actually not not rerender the value field is a really bad idea :)

**Comment by PawBud** [comment]
> And, in I bet what you did do not work because currently there exists only the function to change value, not the name, being passed to SemiControlledTextField.

I did add a new function :)

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
