### ISSUE TITLE
Ladder speed

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1563]
A user on the Discord (and another on the forum last year) said he wanted to change the ladder climbing speed.
Right now, the ladder climbing speed of the platformer behavior is fixed.
The only way to change it is changing the time scale, which is quite impractical in most situations.
It should be possible to change it like the moving speed and other parameters.

The related files are in GDevelop/Extensions/PlatformBehavior and the related lines are:
![image](https://user-images.githubusercontent.com/25978830/77215473-85692580-6b14-11ea-9564-37372dde8e31.png)
That 150 should be replaced by an attribute which should be declared in the file PlatformerObjectBehavior.cpp. Looks fairly easy... I think. 😁

**Comment by 4ian** [comment]
Oops that's a very old thing that I totally missed! You're right looks not too difficult to add, a good exercice to see how properties can be declared for behaviors :) 
Thanks for reporting!

**Comment by arthuro555** [comment]
This issue can be closed as it has been solved with #1578
