### ISSUE TITLE
Module not found error 

### ISSUE THREAD

**Issue by PawBud** [4ian/GDevelop#1565]
## Describe the bug
The snapshot below described the error clearly 

## To Reproduce
1.Compile the code

![Screenshot from 2020-03-21 12-02-03](https://user-images.githubusercontent.com/48093317/77221051-17504d00-6b6c-11ea-8333-a0f3847f33f9.png)

**Comment by ozata** [comment]
In GDevelop/newIDE/app, could you:
`
git checkout master
git pull
npm install
npm start
`

**Comment by 4ian** [comment]
Remember to `npm install` after updating your master branch :)
