### ISSUE TITLE
Taking forever to build libGD.js under npm start

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1569]
## Describe the bug
It is taking to forever to build libGD.js under npm start. Unable to start server and apps.

## To Reproduce
1. Run npm start
2. See inexplicable build time.

## Screenshot
![Screenshot 2020-03-21 at 3 10 00 PM](https://user-images.githubusercontent.com/42793024/77223905-c26e0000-6b86-11ea-9c5c-2911d66c2094.png)

## Other details
Mac OSX Mojave

This is happening after I synchronized my forked repository with the main repository. It worked fine before.
I tried uninstalling all dependencies and reinstalling them. But it keeps giving the same log as in the screenshot above.

**Comment by pranavmodx** [comment]
@4ian Any idea why this might be?
I'm not able to test anything. It is really hindering my contribution efforts. :(

**Comment by ozata** [comment]
I was having the same problem.
What I did to solve:
1 - Close all terminals and VSCODE(Might be active terminals in there)
2 - You could clear browser cache (I didnt)
3 - in ./newIDE/app
```
git checkout master
git pull
npm install
npm start
```
4 - in electron-app 
`npm start electron-mac`

**Comment by pranavmodx** [comment]
Thanks @ozata but I had done all these. Still those errors had persisted. 
I did it again after more PRs got merged and now it works just fine. 
I don't know how, but if it works it works :D
