### ISSUE TITLE
Confusing prompt for cutting object - same as deleting

### ISSUE THREAD

**Issue by pranavmodx** [4ian/GDevelop#1573]
## Description
While cutting objects the prompt displayed is the same as for deleting objects which is confusing and seemingly redundant.

## To Reproduce
1. Open a project
2. Try deleting an object
3. See prompt

## Screenshots
![Screenshot 2020-03-21 at 7 19 27 PM](https://user-images.githubusercontent.com/42793024/77227892-797b7300-6ba9-11ea-8827-f4b12698ca24.png)
![Screenshot 2020-03-21 at 7 19 49 PM](https://user-images.githubusercontent.com/42793024/77227890-797b7300-6ba9-11ea-8772-bebf67f511b4.png)

## Other details
Mac OSX Mojave
Desktop App

**Comment by 4ian** [comment]
We could update it to be "cut" instead of remove... but still, you're cutting an object, so it's getting removed, so it's important to warn the user - especially because this is making events invalid.

**Comment by pranavmodx** [comment]
But the same object could be pasted back right? Would this still result in events becoming invalid?

**Comment by 4ian** [comment]
You still need to ask users if they want to remove events associated to the object, because they if they remove the object they might (or might not) want to keep the events.
