### ISSUE TITLE
Some problems with the search feature 

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1576]
Few bugs I noticed with the search feature.

Ctrl+f:
- Unless I select an event in the sheet, the shortcut doesn't work. For example, if I switch to the scene editor and switch back to the events, the shortcut doesn't work.
- Same goes when the search bar is open. I need to click on an event for the shortcut to work again.

Searching:
After typing the search string, pressing Return should run the search, but I have to hit tab first to move focus to the Search button. 

Vewing results:
Clicking once on the search button runs the search and displays the number of hits. It would feel natural that (unless the search string has been changed) further clicks on this button would scroll through the hits like the right arrow button below.

**Comment by 4ian** [comment]
> After typing the search string, pressing Return should run the search, but I have to hit tab first to move focus to the Search button.

Should be easy to add! :) 

> Ctrl+f:

It's a question of handling the focus, it's a bit harder to get right.

> Clicking once on the search button runs the search and displays the number of hits. It would feel natural that (unless the search string has been changed) further clicks on this button would scroll through the hits like the right arrow button below.

Good idea, should be also easy to add

**Comment by jimil749** [comment]
Also I think the search bar should have an exit button (or a cross) to exit. Pressing Ctrl+F again (that too does not work when an event is not selected) seems pretty cumbersome.

**Comment by 4ian** [comment]
Not sure about this. Sublime Text has a search bar that can be dismissed with Escape. I think that would be a better solution.

**Comment by jimil749** [comment]
That could also be a solution, but currently that is not implemented, need to press Ctrl + F to exit the search bar.  I'll try to implement the changes! :)

**Comment by jimil749** [comment]
Hey @4ian, I made the Enter key working and also made click on search scroll the list of searched items. Also added the ESC key to close the search panel, but has one issue, it won't close until a text is searched or until an event is focused (just like search won't open until an event is selected). Stuck here, any suggestions? : \

**Comment by 4ian** [comment]
Hard to say without seeing the code :) Push on a branch on GitHub and put the link to your commit.
