### ISSUE TITLE
Some data in clipboard crash the eventsheet after right click.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1577]
## Describe the bug
This data below if you copy this in clipboard and use right click in eventsheet, the eventsheet crash always.

`{"000kind":"GDEVELOP_EventsAndInstructions_CLIPBOARD_KIND-jsBdHbLy912y8Rc","content":{"eventsList":[{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::Standard","conditions":[],"actions":[{"type":{"inverted":false,"value":"AddForceVers"},"parameters":["AI","Player","150",""],"subInstructions":[]},{"type":{"inverted":false,"value":"RotateTowardPosition"},"parameters":["AI","Player.PointX("Center")","Player.PointY("Center")","0",""],"subInstructions":[]}],"events":[]}],"eventsCount":1,"actionsList":[],"actionsCount":0,"conditionsList":[],"conditionsCount":0}}`

## To Reproduce
1. Go to eventsheet
2. Copy code 
3. Right click in the eventsheet

## Other details
* unknown user not capable to send me the info...

**Comment by 4ian** [comment]
This JSON is not valid, hence the error.
Ideally we would protect against JSON not parsed properly (in practice for speed of checking the content of the clipboard, I decided to just check in the clipboard string if the `GDEVELOP_EventsAndInstructions_CLIPBOARD_KIND-jsBdHbLy912y8Rc` string is present at the proper position, and if yes it is considered as valid.)

**Comment by Bouh** [comment]
- User haven't edited the events code.
- Beta 89
- I wait more info about where he get this events.

**Comment by 4ian** [comment]
Ok let me know!

**Comment by Bouh** [comment]
Well i've found how he get a corrupted the content.
He copy the event, and paste it on Discord, discord remove the \ before double quote.
so the content is corrupted.

The next user copies json code from Discord to GD, and it crashes.
That's why.

On top the events.
On Left the json bugged,  content from copied content from Discord.
On right my json from my events, pasted and re copied in a notepad.
![image](https://user-images.githubusercontent.com/1670670/77260475-8de26d00-6c88-11ea-8360-d4d3462cf058.png)

So nothing wrong in GD, just two people sharing content corrupted by a chat software.
Maybe GDevelop should parse the code, but it's not really neccessary, this is not very common.
