### ISSUE TITLE
Browser Zoom is overlapping with the Scene Zoom

### ISSUE THREAD

**Issue by xAtishayx** [4ian/GDevelop#1581]
## Describe the bug
Using shortcuts of Zoom In or Zoom Out (Ctrl + + and Ctrl + -) results in zooming in and out of the browser window instead of scene zoom.
Or am I wrong this shortcut is only for electron app?

## To Reproduce
1. Go to 'https://editor.gdevelop-app.com/'. 
2. Use shortcut to Zoom In or Zoom Out.

![image](https://user-images.githubusercontent.com/42544589/77304119-02192100-6d1a-11ea-9838-cad86a0256d0.png)

## Other details
* OS- Ubuntu/ PopOS
* Browser- Chrome

**Comment by 4ian** [comment]
Yep I don't think we can override the browser zoom, we should probably remove these shortcuts from the menu, at least for the web-app

**Comment by xAtishayx** [comment]
Also in desktop ElectronApp, Scene Zoom In and Zoom Out shortcuts (Ctrl + + and Ctrl + -) are not working only scroll is working

**Comment by 4ian** [comment]
Let's remove these shortcuts then, or fix their implementation.

**Comment by PawBud** [comment]
Is changing the accelerator enough to resolve this issue?, I tried it and it doesn't work so what more do I need to do to resolve the issue @4ian?

**Comment by blurymind** [comment]
One thing I want to keep is the ability to zoom without using any keyboard
on the electron version. Scrolling zooms and holding a key + scroll pans on
h or v axis

**Comment by Silver-Streak** [comment]
@4ian I have confirmed these shortcuts are still there on the web version in 5.1.157, and this behavior is still the same.

I'd recommend changing those shortcuts from Ctrl+add or minus and switching them to soemthing else (maybe Ctrl+up Ctrl+down?)

**Comment by Bouh** [comment]
At the moment 5.1.159 this is no longer reproducible on web app on Windows with Chrome.
I guess this is fixed.

**Comment by Silver-Streak** [comment]
Confirmed fixed for me too. If the author or no one else reports still experiencing the problem in 158 or newer within the nexst 48 hours, I say we close this issue out.
