### ISSUE TITLE
Update to Bouncing ball and rope example

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#1584]
Hi,

Whilst looking into the physics upgrade I noticed that due to recent gfx changes regarding screen sizing etc my ball and rope example needed fixing a little!

[Bouncing ball and rope.zip](https://github.com/4ian/GDevelop/files/4371856/Bouncing.ball.and.rope.zip)

I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by PawBud** [comment]
I am sorry but can you please elaborate on your issue. A brief explanation should be ample.

**Comment by 4ian** [comment]
Done in e7348f08c497fbfbdfa73372545a5be4654e42d5, thanks for the example update! :)
