### ISSUE TITLE
Cannon Ball

### ISSUE THREAD

**Issue by THE-GEM-TUTORIALS** [4ian/GDevelop#1590]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.
 
  I confirm that any assets can be used freely by anybody, including for commercial usage.
  
[Cannon Ball.zip](https://github.com/4ian/GDevelop/files/4388472/Cannon.Ball.zip)

**Comment by 4ian** [comment]
Added :) A few comments:

* Don't use Always condition, just don't put any conditions.
* Don't collapse the groups in these short examples. All events must be visible.

Thanks for the example!
