### ISSUE TITLE
Flappy Bird example update

### ISSUE THREAD

**Issue by THE-GEM-TUTORIALS** [4ian/GDevelop#1594]
Here is the new update
[Flappy Bird Clone.zip](https://github.com/4ian/GDevelop/files/4395560/Flappy.Bird.Clone.zip)
I removed the dialogue which shows load autosave. and added some improvements

**Comment by PawBud** [comment]
I am sorry but how is this an issue, I think this belongs either in the forum or the PR page @THE-GEM-TUTORIALS

**Comment by 4ian** [comment]
No this is fine, there is a button in the software to submit new examples. If you want to help, you can do the PR to update the example :)

**Comment by PawBud** [comment]
Ohh, thank you for notifying me :).

**Comment by 4ian** [comment]
Updated in 017f8cf554cd71473a5edcdb4c5d15ef1af997d0
