### ISSUE TITLE
error with file watchers in dev environment w electron

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1606]
## Describe the bug
I keep getting this warning

```
{/home/fox/DEV/GDevelop/GDJS/Runtime: Error: ENOSPC: no space left on device, watch '/home/fox/DEV/GDevelop/GDJS/Runtime'
    at FSWatcher…, /home/fox/DEV/GDevelop/GDJS/Runtime/Cocos2d: Error: ENOSPC: no space left on device, watch '/home/fox/DEV/GDevelop/GDJS/Runtime/Cocos2d'
    at F…, /home/fox/DEV/GDevelop/GDJS/Runtime/Cordova: Error: ENOSPC: no space left on device, watch '/home/fox/DEV/GDevelop/GDJS/Runtime/Cordova'
    at F…, /home/fox/DEV/GDevelop/GDJS/Runtime/Electron: Error: ENOSPC: no space left on device, watch '/home/fox/DEV/GDevelop/GDJS/Runtime/Electron'
    at …, /home/fox/DEV/GDevelop/GDJS/Runtime/FacebookInstantGames: Error: ENOSPC: no space left on device, watch '/home/fox/DEV/GDevelop/GDJS/Runtime/FacebookInstantGa…, …}

```

The thing is I have over 2 gb left in home and plenty on root. What is worse, when I get this warning, editing the code of the ide or extensions doesnt update gdevelop that is running, I have to literally stop it and wait for it like 5 minutes to restart to see my changes

I dont get the warning in the server, I get it on electron

## Other details
Linux

**Comment by blurymind** [comment]
This could be some funkiness with my manjaro. I noticed I have a folder named ¬ set to root. Deleting it seems to have stopped this

**Comment by 4ian** [comment]
Definitely looked like some permission/weird file system issue (like a read only file system).

**Comment by blurymind** [comment]
reopening this, as I'm getting the issue again. This time that folder doesnt even exist

**Comment by blurymind** [comment]
I have a strong feeling that it has to do with my max file watchers setting on linux
```
cat /proc/sys/fs/inotify/max_user_watches
16384
```

**Comment by blurymind** [comment]
This was indeed the issue. Closing this now
