### ISSUE TITLE
Installer is failing on Windows

### ISSUE THREAD

**Issue by jeremyglebe** [4ian/GDevelop#1616]
## Describe the bug
Upon removing GDevelop from my system and wanting to later re-install it (I was demonstrating how to install it for students) I am finding that the installer now gets frozen and won't complete the process.

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Delete GDevelop from Windows 10 machine
2. Run the installer

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.
[Imgur](https://imgur.com/oMbZUFy)

**Comment by 4ian** [comment]
Might be a file that is being used by the operating system and so can't be deleted. Can you try to restart and reinstall?

**Comment by jeremyglebe** [comment]
I managed to solve this shortly before you commented. I'm sorry I didn't update it sooner. It seems that Windows Defender is picking up the most recent installer as a virus. I've searched extensively and I am extremely confident this is a false positive. (Not your fault) I don't know if there is a way to prevent this issue that you could implement. However, as a temporary fix, I shut off defender and ran the installer. It seems that the reason I didn't have this issue when I first installed the program was because I was installing an older version, which then updated as I used it. I tested it and b84 is not considered a virus, but b88 and on are.
