### ISSUE TITLE
Topdown in collision with two objects

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1633]
There seems to be a bug which is visible in the bomber example:
https://editor.gdevelop-app.com/?project=example://bomb-the-crate
![image](https://user-images.githubusercontent.com/25978830/78832844-3cf2a880-79ec-11ea-8363-0d326b8052d9.png)
If you go here and press right, the character gets blurry/shaky due to being in collision with two objects at the same time.
I tried "move player away from unmovables" without success.

Full details here:
https://forum.gdevelop-app.com/t/collision-issues-when-top-down-object-is-pressed-against-2-static-objects-pics-files-test-game/23950

**Comment by 4ian** [comment]
Interesting, great demos in the forum thread!
I think the separate actions is not working well when dealing with 2 objects at the same time (which also give weird results for the bounce behavior). Would need to think about a smart way to fix this.

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by AlexandreSi** [comment]
I tested it, and it seems to me that @D8H 's work on #3236 fixed those collisions with multiple obstacles.
