### ISSUE TITLE
When imported, square sprites are always blurry

### ISSUE THREAD

**Issue by fadedcafe** [4ian/GDevelop#1634]
## Describe the bug
When you import a sprite, especially as a tiled sprite, any sprite whos width and
height are the same, will be smoothed (or blurry), regardless of smoothing settings.

## To Reproduce
1. Open any scene
2. Click on 'add new object'
3. Click on 'Tiled sprite' from the list of new object types.
4. In the box that pops up, click within the 'select an image' field
5. Click 'Choose a new image' in the drop down list that appears
6. Select any image or sprite that fulfills the requirements. Must be power of 2 in dimensions, and share the same width as it does height.
7. Open or import it into GDevelop
8. Hit 'apply'
9. Drag and drop the new object into the scene
10. Observe how it is blurry.

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Using windows 10, GDevelop 5.0.0-beta89 based on GDevelop.js 4.0.98.0-release

**Comment by fadedcafe** [comment]
I'd like to emphasize again, smoothing settings are being ignored. I double checked both the global setting and the per-sprite resource setting.

**Comment by Bouh** [comment]
I close this issue.
The problem seem solved.


Resolution game: 100x100px
Mode: Nearest on game settings,
Image: 10x10px, without smoothing.

![image](https://user-images.githubusercontent.com/1670670/104850447-6fbcbc00-58ef-11eb-924c-11a881c299bf.png)

**Comment by 4ian** [comment]
Thanks for checking! Might be a matter of making sure objects are on round pixels too.
