### ISSUE TITLE
Editor field focus issue

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1652]
Not sure if it's related to the crashes, but on b90, _sometimes_, I can't get _focus_ on the fields.
I mean that when I click on the field, it opens in edit mode, but it's in read-only mode.
![image](https://user-images.githubusercontent.com/25978830/79167820-a6a5f480-7de8-11ea-9754-0691462176d6.png)
The highlight remains **grey** and keyboard doesn't work. I try other fields and none is really active.
It seems switching to another program and coming back fixes it.
I'm uninstalling b90 for now.

Edit: I'll stay on b90 as I'm unable to reinstall b89, the install hangs undefinitely (after uninstalling b90 and rebooting)
Might be related to a ghost?
![image](https://user-images.githubusercontent.com/25978830/79168704-d6ee9280-7dea-11ea-8183-995d443a3d1d.png)

**Comment by 4ian** [comment]
Yep this is an issue, see #1646
Should be fixed soon in an update, for now you can stay on beta 89 or when it happens just focus another window and then back the GDevelop window to regain focus.
