### ISSUE TITLE
Cannot input events' parameters

### ISSUE THREAD

**Issue by Quarkstar** [4ian/GDevelop#1653]
## Describe the bug
Cannot input parameters of repeat and for-each events. 

## To Reproduce
1. Create a new repeat event(or for-each event)
2. Click on 'Click to choose how many times will be repeated'
3. No response and cannot input a number.
![repeat](https://user-images.githubusercontent.com/32167255/79178974-32e00800-7e39-11ea-99dc-967ffebd03a1.gif)

## Other details
- Environment: 
  - Linux ubuntu18.04 Both on web-app(Firefox) and electron-app (Dev)
  - https://editor.gdevelop-app.com/

**Comment by 4ian** [comment]
I'm on it

**Comment by 4ian** [comment]
Fixed! Might be either because of a material-ui update or Electron update that this stopped to work - there was already a hack to make it work. Thanks for reporting this! :)

**Comment by Quarkstar** [comment]
Thank you!
