### ISSUE TITLE
Object Deletion Stops The Ability To Type - Beta 90

### ISSUE THREAD

**Issue by TerraPrimal** [4ian/GDevelop#1655]
## Describe the bug
I first thought this bug was due to me duplicating a scene, however I am able to replicate it in a fresh new project.

When the bug occurs you're no longer able to type anything into any fields within the GUI, short cuts such as CRL + S still work.

## To Reproduce
1. Create a new project.
2. Create a new scene.
3. Create 2 new objects (I just used sprites)
4. Delete one of the objects.
5. Unable to type in any fields. Even when you double click on the existing objects name so it's highlighted you're unable to type.

## Other details
* Windows 10
* Desktop App, Beta 90 (4.0.98-0)

EDIT:

Looks like the wizards on discord know: https://i.gyazo.com/faeb97bde2a7a16061e6e3732766902d.png

**Comment by 4ian** [comment]
Thanks for reporting anyway! :) Will make a new version soon.
