### ISSUE TITLE
GDevelop editor does not show pitch in action Play sound on channel

### ISSUE THREAD

**Issue by HiranChaudhuri** [4ian/GDevelop#1659]
## Describe the bug
When using the "Play sound on a channel" action I have to specify a pitch parameter.
This pitch parameter is not shown in the editor summary. I always have to edit the action to see the actual value.

## To Reproduce
GDevelop 5.0.0-beta89
Ubuntu 18.04.4 LTS

Create an event. Regardless of the condition, add the "Plaz sound on a channel" action. Check the entered parameters and the overview display.

**Comment by PascalLadalle** [comment]
Hi,
This is not a bug. 
If you create your own extension, you will see that you have the choice of displaying or not each parameter in the event line.
Pitch is not used much, so it's not displayed in the event line.
If you think it should be added to this event line, you should request it on the forum, and if enough people vote for it, the devs will add it.

**Comment by HiranChaudhuri** [comment]
I see. It seems there are a number of features in GDevelop that are not intuitively understood.
We can close this issue.

**Comment by 4ian** [comment]
I've added a card in the roadmap: https://trello.com/c/9wbfvC1I/434-allow-action-condition-sentences-to-display-optional-parameter-if-they-are-filled-for-example-the-pitch-of-a-sound-music
