### ISSUE TITLE
Empty external event sheet produce a linkage error if included by another one/a scene

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GDevelop#166]
Empty external event sheet produce a linkage error if included by another one/a scene.

**Comment by 4ian** [comment]
Can't reproduce, on v4 branch at least. But I had to fix this: https://github.com/4ian/GD/commit/c6ae338b7757fd75dd1e42f87140d857452691ea to get compilation working on v4, it's strange that we did not noticed it before.

**Comment by victorlevasseur** [comment]
Maybe some old includes were remaining in the Release_Windows version of my development folder.
I can send you a private message on the forum with the game that cause the issue (a user send it to me). Note that the event link is a sub-event on a standard event.

**Comment by 4ian** [comment]
Having the game would help yep :)

**Comment by victorlevasseur** [comment]
Sent to you by PM on the forum.

**Comment by victorlevasseur** [comment]
Did you managed to reproduce the issue ?

**Comment by 4ian** [comment]
I did, but I have to investigate more to see exactly what's going on here.
