### ISSUE TITLE
Resize Window event actions broken in Preview since b90 or 91

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#1660]
## Describe the bug
The event action **Change the size of the game window** no longer works when previewing a game.

## To Reproduce
1. Open any game.
2. Add a new event with any condition or no condition.
3. Add the **Change the size of the game window** action. Ensure the toggle is set to **No** and select any resolution OTHER than the game's default.
4. Preview the game.
5. Trigger the condition. The window resolution will not change.

If you export the game and build it with electron, the event DOES work, so this seems to be isolated to preview.

Here's an example project:
[BrokenResPackage2.zip](https://github.com/4ian/GDevelop/files/4484154/BrokenResPackage2.zip)
Using the R or T keys should resize the window, but do not.

Here's an example of the project built:
https://support2.lsdsoftware.com/dropmeafile/a8a0bbe0ac/f3932ca5b1
Using the R or T keys resizes the window.

## Other details
OS: Win10 Pro 
GDevelop: b91

**Comment by 4ian** [comment]
Good catch, I missed this. Fixed in 770aad567284577bf92cb0d79c25b50a5f34167c
Thanks for the nice bug report and examples :) 

I will make a new update soon with this fix.

**Comment by Bouh** [comment]
This fix also the action "Quit the game".
I've tested this fix few minutes ago, and we can now quit the game and use fullscreen action.

More generally this fix all instructions related to window.

[Another thing seem have change](https://forum.gdevelop-app.com/t/cannot-use-quit-the-game-action-after-update-beta-91/24185/4?u=bouh), during the migration to electron v8, the sound.
This need to be tested.

**Comment by 4ian** [comment]
Yes this fixes all features calling into `electron` or `electron.remote` :) 
Electron wants to discourage direct usage of these modules in the JavaScript of the renderer process (i.e: the game). In the future, we might have to convert all of this into events, that are handled by the Electron main process.

But for now, the fix should make all the electron stuff work like before :) It works both for Electron 8 (preview) and Electron 3 (export) (Electron 3 should be upgraded to Electron 8 later).

I'll release b92 later today or tomorrow I hope with this fix.

**Comment by Bouh** [comment]
Profiler is broken incurrent master, always because electron v8.2.1 i guess.
Profiler work great in b89.

**Comment by 4ian** [comment]
Good catch!! But this is not because of Electron update ;)

> Nothing to show in the console.

In the editor no, but in the game yes :) 
![image](https://user-images.githubusercontent.com/1280130/79466649-23112100-7ffd-11ea-8a82-3ee77bb06d20.png)

`runtimegame` was renamed to `runtimeGame` in #1637 but not everywhere: 
![image](https://user-images.githubusercontent.com/1280130/79466696-36bc8780-7ffd-11ea-95d1-04afb30ba5e2.png)

If you want, take a look at websocket-debugger-client.js
We want to fix this too before releasing the new version :)

**Comment by Bouh** [comment]
@arthuro555 this is for you :p

**Comment by arthuro555** [comment]
Yes 4ian commented that issue to me already.

**Comment by arthuro555** [comment]
I made #1662 real quick to fix the issue
