### ISSUE TITLE
The download links for Windows and MacOS on the website are broken

### ISSUE THREAD

**Issue by zQueenBlossom** [4ian/GDevelop#1661]
Hi! I don't really know where to adress this so I'm going to do it here.

I am preparing a tutorial on GDevelop and I went on the website to feel how it was for a beginer to download and install the game engine. Then, I discovered that the download links for Windows and MacOS are broken, resulting in a 404 error. The website links doesn't match the github URLs.

For example, the broken link on the website for Windows is: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta91/gdevelop-setup-5.0.0-beta91.exe

The github ULR for Windows is: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta91/gdevelop-5-setup-5.0.0-beta91.exe

I hope you fix this quickly to avoid the potential frustration of new users not being able to download the game engine!

Best regards.

**Comment by jbdhibd** [comment]
I need help too. My gdevelop was not working so i wanted to redownload. Then that happens. This has been irritating me for so long. Can you please fix it quickly? Gdevelope has a space in my heart and i cannot let it go. Pls fix. :(

**Comment by 4ian** [comment]
This is fixed, thanks for letting me know! 👍👍

**Comment by zQueenBlossom** [comment]
I'm glad I helped
