### ISSUE TITLE
Game not closing upon calling ''Quit the game"

### ISSUE THREAD

**Issue by Alex25820** [4ian/GDevelop#1663]
## The bug
When starting a game through the editor the game no longer quits upon calling "Quit the game". This has worked fine before but after updating to 5.0.0-beta91 from beta90 or beta89 (not entierly sure which version I had before) this no longer works.

I am calling the function using "key is pressed". This has worked just fine before but not anymore.

## To Reproduce
1. Create an event.
2. Call "Quit the game" upon "key is pressed".
3. Start the game through the editor by pressing "Launch a preview of the scene".
4. Press your specified key.
5. The game won't close.

## Other details
* I am on a MacBook Air running version 10.15.4.
* GDevelop 5.0.0-beta91 desktop app.

**Comment by Bouh** [comment]
Thank you for your bug report!
[This is fixed](https://github.com/4ian/GDevelop/commit/770aad567284577bf92cb0d79c25b50a5f34167c) for the next update :)

**Comment by 4ian** [comment]
Should be fixed in beta 92
