### ISSUE TITLE
"Share same collision masks" is broken

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1666]
If you disable the option, changing the animation reenables it. 😕 
Noticed it in a personal project, and confirmed it in the platformer example and on the web editor with two examples.
(somehow, the drop-down menus don't show on the recording...)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25978830/79611574-330f2a80-80fb-11ea-8aef-84e0e97334fd.gif)

GD5 beta 92

**Comment by 4ian** [comment]
It's a bit surprising but not a "bug" per se, you have to make a change to the collision mask to have the option actually persisted. These options do not exist in the object, they are just boxes activated or not according to if all collision masks are the same.

**Comment by PascalLadalle** [comment]
Somehow, I absolutely wanted to disable it in the first one before editing the second one. 😅 
Seems like a non-issue indeed. 🤦‍♂️
