### ISSUE TITLE
Yarn condition "Branch title has been visited before"

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1673]
The condition doesn't seem to be working, or I don't understand how it works.
The wiki says;
![image](https://user-images.githubusercontent.com/25978830/79672203-332d2a00-81d0-11ea-8c8b-fa322a3ae3ae.png)

I expect the condition to remain **false** until a **second** visit of a branch. But the condition is **true** during the **first** visit.
As an example, the event below displays the current branch title on first visit:
![image](https://user-images.githubusercontent.com/25978830/79672233-62439b80-81d0-11ea-8390-88926be21208.png)
Same result with an empty field (which is underlined red and shouldn't be since the field is **optional**)

**Comment by PascalLadalle** [comment]
Workaround:
![image](https://user-images.githubusercontent.com/25978830/79672628-28749400-81d4-11ea-8071-7fc351c3d826.png)

**Comment by blurymind** [comment]
I believe it will become true upon being visited. Not much surprise there :)

**Comment by 4ian** [comment]
I think it's the "has been visited before" that is misleading. Should we change this?

=> "The branch title to check if it has been visited before - or is being visited now."

**Comment by blurymind** [comment]
Yes I agree, the wiki should be updated to clarify it becomes true upon
being visited. Or perhaps I can add a bit of logic to make that condition
true while we are not on it.

The idea when I made it was to trigger game events to activate after an NPC
has given you a bit of info. It was not to use it during the active
dialogue

**Comment by blurymind** [comment]
I have updated the documentation now to say
```
 **Branch title has been visited before**

Check if a branch has been visited by the player before. This becomes true upon that node's visitation. Use this to trigger events in your game, based on what they read without the need to set and get yarn state variables.

Parameters

branch title - The branch title to check if it has been visited by the player before.
```

**Comment by PascalLadalle** [comment]
I understand now.
The **before** is the misleading part. _Before_ means in the past, but this condition works in the present too (first visit VS second visit, as explained in my first post).
I suggest:

>  **Branch title has been visited **
> 
> Check if a branch has been loaded. This condition becomes true as soon as a **branch** has been accessed. Use this condition to trigger events in your game based on what the player has read without the need to set and get yarn state variables.
> 
> Parameters
> 
> branch title - The branch title to check.


(I change the "visited by the player" because if you load a branch without displaying it, it will still count as visited, I suppose)

**Comment by blurymind** [comment]
@4ian I can update this in my pr with dialogue tree fixes so it is true only if the currently parsed title is not the one we are checking for. That way it will truly be before and not be true while the player is seeing it.

Would that be a welcome change to the api?

Alternatively I can keep it as is and remove the "before" word from the extension's condition

**Comment by PascalLadalle** [comment]
Current visit avoids using a command/tag, previous visit avoids using the variable workaround I pasted above... It's easy to fix either way. 🤷 

(FYI, I wanted to use the condition to skip the scrolling of a long dialogue (end section of GDSolver) after the first visit.)

**Comment by blurymind** [comment]
I will update the wording of this condition in the extension to exclude "before" then

**Comment by blurymind** [comment]
I have now added the following to my PR:
https://github.com/4ian/GDevelop/pull/1671

- an example of how to use this condition (what its supposed to do) in the example project (+ resgresion test to catch if it breaks)
- renamed it to @PascalLadalle 's suggestion
