### ISSUE TITLE
Bug with draggable objects

### ISSUE THREAD

**Issue by GabrielVinicios** [4ian/GDevelop#1675]
## Describe the bug
Having two draggable objects, in different Z positions. I put one of then upon the other. When I try to drag the upon object, the underneath object is that moves.

## To Reproduce
1. Creat two sprites
2. Put Images in both
3. Add the Behavior "Draggable" in both
4. Put one upon the other.
5. Then, try to drag this object. The object that is draged is the other. 

* Please include a link to a game if possible!
You can see a simple example I have made: https://games.gdevelop-app.com/game-9df59900-7d7f-49c4-85fb-af0989957cca/index.html

## Other details
GDevelop 5.0.0 beta 92 (desktop app)
Windows 10 (updated)

Thank you!

**Comment by 4ian** [comment]
Currently the draggable behavior has no concept of priority. It just takes whatever object comes first in memory. Could be reworked to use z order, but not entirely trivial to do.

**Comment by GabrielVinicios** [comment]
> Currently the draggable behavior has no concept of priority. It just takes whatever object comes first in memory. Could be reworked to use z order, but not entirely trivial to do.

Yes, using Z order, I think, is the correct way to fix this issue. Very annoying, since I am doing some educational games that uses draggable elements a lot. Thanks!

**Comment by arthuro555** [comment]
I think the best way to go is using a manager. When a draggable object is created/activated it adds itself to the manager and on deactivated/destroyed he removed himself from it. The manager would then use a callback pre-event and with the array of draggables use 
```js
draggableObjectList.sort((a,b) => {
	if(a.zOrder>b.zOrder) return 1;
	if(a.zOrder<b.zOrder) return -1;
	return 0;
});
```
To sort the list in the order of z orders and then just iterate over that list and do what behaviors pre-event did until now.

**Comment by arthuro555** [comment]
>

**Comment by GabrielVinicios** [comment]
> I think the best way to go is using a manager. When a draggable object is created/activated it adds itself to the manager and on deactivated/destroyed he removed himself from it. The manager would then use a callback pre-event and with the array of draggables use
> 
> ```js
> draggableObjectList.sort((a,b) => {
> 	if(a.zOrder>b.zOrder) return 1;
> 	if(a.zOrder<b.zOrder) return -1;
> 	return 0;
> });
> ```
> 
> To sort the list in the order of z orders and then just iterate over that list and do what behaviors pre-event did until now.
> 
> The manager would use object uid (already present mechanic) to delete an item of the draggable list.

Is a manager, a group? I have tried doing something like you said, but with no success. Can you build a simple example of what you said? Thanks!

**Comment by arthuro555** [comment]
I wasn't giving a workaround but tips for the person who will create the fix

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by D8H** [comment]
This issue was fixed by:
* https://github.com/4ian/GDevelop/pull/3066
