### ISSUE TITLE
Important/regularly reported issues in beta 92

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1685]
## Describe the bugs
- ~~Preview cannot be open. - Link[1](https://forum.gdevelop-app.com/t/preview-problem/24392) [2](https://forum.gdevelop-app.com/t/preview-dont-work-on-desktop/24104) [3](https://forum.gdevelop-app.com/t/2-bugs-or-not/24326)  #1683~~ - hopefully fixed.
- Download button for game.zip (exported game) dosen't work, (but the link can be downloaded with the direct link) Same for [Log file](https://imgur.com/5WALV9r).  Can be fixed with a QR code, https://trello.com/c/53fE5tFg/419-show-a-qr-code-for-preview-on-lan-wifi-mobile-exports

I can't find the post of the users for download the game.zip. But it's the problem with download logs. 
One user was using firefox, and another Opera GX as default browser. According to them even after a factory setting on the default browser on internet explorer or edge, it doesn't solve the problem.

- ~~User complain about admob dosen't work like before (b89), there is sound issue, some ads not working.~~ - Link [1](https://forum.gdevelop-app.com/t/not-solved-yet-gdevelop-update-broke-my-games/24361) [2](https://forum.gdevelop-app.com/t/audio-echo-after-interstital-ad/24383/5)
- ~~User cannot launch GDevelop. (Mac 2008 mojave)~~ - **4ian: Seems to work on High sierra/Mojave/Catalina when testing on a few macs.**
- Cannot be run on Ubuntu 20.04 - Link [1](https://forum.gdevelop-app.com/t/how-to-install-run-gdevelop-5-on-ubuntu-20-04/24410)
- ~~Sound is automatically mute in preview (mixer windows/sound panel) ?~~ - Link [1](https://forum.gdevelop-app.com/t/solved-audio-does-not-work-in-preview/24229/11) **4ian: will consider this as not reproducible unless we have more reports**
- ~~“Advanced Bloom" effect broke the preview,~~ [FIXED](https://github.com/4ian/GDevelop/commit/21e034863e0529c82913b52e887b09cfe515aa6a)
- ~~Web-app cannot export games, but user can try and encounter an error.~~ - Link [1](https://forum.gdevelop-app.com/t/workaround-exist-dirname-undefined-exporting-html5-to-zip/24294/4) - FIXED

## Other details
* After b89

**Comment by 4ian** [comment]
Thanks for compiling this list!

> Preview cannot be open. Link 1 2 3 #1683

Very strange, we definitely want to find why and fix this.

> Download button for game.zip (exported game) dosen't work, (but the link can be downloaded with the direct link)

What do you mean by direct link? Is it on Windows? Clicking on the Download button seems to work for me (macOS, development version).

> User cannot launch GDevelop. (Mac 2008 mojave)

I'll check on Mojave.

> Sound is automatically mute in preview (mixer windows/sound panel) ? Link 1

We would need more user reports to confirm if it's a real issue.

> Web-app cannot export games, but user can try and encounter an error. Link 1

I fixed the web-app games export in https://github.com/4ian/GDevelop/commit/980081516a4d1c40c9d419f5cb418da10fc7c43e - I'm unsure why this broke :/ Might be a Node.js version update on my local computer.. Weird.

Anyway, I checked and all online exports should be working :)

**Comment by Bouh** [comment]
> What do you mean by direct link? Is it on Windows? Clicking on the Download button seems to work for me (macOS, development version).

I've recreate the link with the GUID generate for the project. The GUID provide by the api, found in network panel of the debugger.
Yes work fine to me too on windows, but some users also on windows can't.
Maybe the issue is cause by adblocker or other ads blocker.

**Comment by 4ian** [comment]
> User cannot launch GDevelop. (Mac 2008 mojave)

I've just tried on macOS High Sierra, Mojave and Catalina (:D) and all seem to launch the app properly and are able to run a preview. Might be a security warning (though the app is signed because otherwise MacOS is almost totally preventing users to run it).

> Yes work fine to me too on windows, but some users also on windows can't.
> Maybe the issue is caused by adblocker or other ads blocker.

I wonder if it's an Electron issue, a bit like what happened on macOS (windows could not be opened).
Might be worth updating to the latest versions of Electron with bug fixes released a few days ago.

**Comment by Bouh** [comment]
[Another user cannot run GD.](https://forum.gdevelop-app.com/t/how-to-install-run-gdevelop-5-on-ubuntu-20-04/24410)

**Comment by 4ian** [comment]
Seems like a matter of setting the executable permission, let's discuss on the forum thread.

**Comment by 4ian** [comment]
Preview issue is hopefully fixed by 0b5980d0b667be98a8763f4d66354857753aa653

**Comment by Silver-Streak** [comment]
@Bouh should this still be open?

**Comment by 4ian** [comment]
I'm closing this, I think everything is handled and the QR code feature has a card: https://trello.com/c/53fE5tFg/419-show-a-qr-code-for-preview-on-lan-wifi-mobile-exports
