### ISSUE TITLE
Ctrl+x not working in Yarn editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1689]
Inside the Yarn editor, Ctrl+x cuts the text, but doesn't save it to the clipboard.

GD5 beta92

**Comment by blurymind** [comment]
That is a yarn bug for the yarn tracker :)

**Comment by blurymind** [comment]
Please can you close the issue on here. It has nothing to do with GD. Now that you opened it there more yarn devs can see it too

**Comment by 4ian** [comment]
Thanks for opening the other issue, I'm closing this then :)
