### ISSUE TITLE
Sprites with Physics2 Behaviour not deleted properly

### ISSUE THREAD

**Issue by bongodoctor** [4ian/GDevelop#1697]
## Describe the bug
When using the delete object action on sprites that have Physics2 behaviour, sometimes although they disappear from the screen and can no longer be interacted with using collisions (physics or standard) they still exist as a 'ghost' Physics2 objects and continue to move around the screen and other objects bounce off it as though it is there. The effect is as if there is a hidden or invisible object on the screen - although you cannot delete it or perform any action on it via collisions etc. This happens occasionally not consistently - maybe 1 in 10... 

Please double check that the bug is not already reported in the issues list.

## To Reproduce
Create four wall sprites to contain sprites with static physics behaviour. Adds lots of sprites with physics2 behaviour at random position with random directional forces (e.g. a rectangle of bouncing balls). Then create another sprite with similar properties that will delete the original spites on collision. After a while the sprites will start to be deleted, but occasionally you will notice the original sprites suddenly changing direction as though they have been hit by another moving particle. Once these particles exist there is no way to remove them from the game without restarting the scene.

* Please include a link to a game if possible!

https://tinyurl.com/Anti-Matter-1-0-6

**Comment by PascalLadalle** [comment]
Did you check in the debugger how many instances exist VS how many you can count on screen? 🤔 
I was able to reproduce the issue this time. After a few minutes of idling, some of them got stuck along the walls and kept bouncing against ghosts stuck to the walls too.
I'm still betting on something not being finished or removed and preventing the deletion, but if not a tween, what?...

**Comment by bongodoctor** [comment]
I know it is perplexing - I am assuming it is a delete bug - deleting the
sprite but not the physical properties/object  - I did run the debugger and
it tallied with the number I could see on the screen - it cannot interest
with any other particles - even the ones that delete stuff - even pressing
return when you lose doesn't delete them even though that command deletes
all sprites by name. I would be happy to share the game and resources
folder if you think it might help you are someone solve the issue... ?

**Comment by 4ian** [comment]
Ideally if you have a very simple game (a few objects and events, no more) where you can see the issue after a bit of time, that would be greatly useful to reproduce and fix the bug.

**Comment by bongodoctor** [comment]
Ok will make a copy and cut out most of the events, then I can post the
code/game back here - would be great to get a fix for this :)

**Comment by bongodoctor** [comment]
I have reduced the game to the minimal amount of events possible - just two kinds of sprite created - press F11 to switch to fullscreen, press return to restart the cycle: https://s3-eu-west-1.amazonaws.com/gd-games/game-424f2335-3b10-4d53-9250-0f03e1e6a59d/index.html I have watched it carefully for about 20 minutes and I haven't seen any 'ghost sprites' yet - this suggests it isn't just a simple bug in the deletion of Physics2 objects (which I am sure someone would have already spotted) - it must only happen under certain specific conditions... Here is all of the code: 
![Screenshot from 2020-04-27 21-33-36](https://user-images.githubusercontent.com/63129963/80418699-b553d780-88cf-11ea-91d4-9b374a4e8ecb.png)

**Comment by 4ian** [comment]
Alright, so yeah might be related to a more complex scenario. In theory
when the object is deleted the behaviour should also delete the equivalent
physics object. Might be a case when it does not happen... But I would be
curious why.

**Comment by bongodoctor** [comment]
I will do more experiments during the week and post any findings here - my
next step will be toggling blocks of code disabled one at a time and see if
one (or more) of them is causing the anomoly...

**Comment by bongodoctor** [comment]
I have been testing by removing different code blocks and watching the screen for 'ghost sprites' - I haven't been able to narrow it down to a specific block or line of code. But I am starting to suspect it might be related to changing the scale of sprites. If I remove the spawns that change the scale of sprites there seems to be no 'ghost sprites' - so I am wondering how physics2 behaviours interact with sprite scale changes? Is is possible that if the scale of the sprite is say 0.5 or 1.5 of the original then the sprite is removed by the collision but not the physics2 object because that is still the original size? Gonna try removing all scaling actions and see if that resolves it...

**Comment by bongodoctor** [comment]
Ok I have now identified the cause and can reproduce lots of 'ghost sprites' at will :) The issue is cause by have a delete 'spritename' followed by a create 'spritename' in the same action block - see picture attached. For some reason this creates an invisible version of itself which cannot be deleted or interacted with (other than bouncing off other sprites). Still don't understand why this would happen. Game sample here: https://s3-eu-west-1.amazonaws.com/gd-games/game-30b7fecc-b475-4f36-a0f4-fd39b1ed60ba/index.html - everytime a sprite is created a 'ghost sprite' is also created - leave it for a few minutes and there will be loads...
![Screenshot from 2020-04-29 15-35-50](https://user-images.githubusercontent.com/63129963/80609631-3c1fc600-8a30-11ea-9d75-6f64f8a0e405.png)

**Comment by arthuro555** [comment]
This could be a bug coming from box2d and the fact that an object Gest deleted and the next I start recreated. Maybe try [physics 3](https://forum.gdevelop-app.com/t/try-out-the-physics-3-prototype/23999?u=arthuro555) with the updated box2d to see if it fixes your problem

**Comment by bongodoctor** [comment]
I will definitely give it a try! Using Linux but that should be an issue - once in place I assume it will show up in the behaviours list under Physics2?

**Comment by arthuro555** [comment]
Uhm It should appear as physics 3
But then this link contains only the extension and not some modfications made to the ide to make support of it better :/

**Comment by tristanbob** [comment]
This sounds very similar to this bug, which has been fixed. 

https://github.com/4ian/GDevelop/issues/3525

Please test this and let us know if the problem still exists.

If we don't hear anything, we will close this issue.  Thanks!

**Comment by Silver-Streak** [comment]
Closing as resolved with #3525 and no new reports of issue.
