### ISSUE TITLE
Yarn - arrow sign -> causes crash

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1704]
I checked the yarnspinner wiki and they mention a "->" shortcut.
I tried to use it and it crashes the dialogue or the game.
Has this been implemented in GDevelop and not working, or reserved but not implemented? Or I'm not using it right somehow? 
I didn't see it mentioned in the GDevelop wiki.
For @blurymind I guess 🙂 
![image](https://user-images.githubusercontent.com/25978830/80403491-f47a2c80-88bf-11ea-8554-a66af5675b50.png)

**Comment by blurymind** [comment]
You are again creating a hug at the wrong tracker without doing any research

**Comment by blurymind** [comment]
Parser code done with jison is confusing, otherwise I would have fixed it by now. Perhaps you can put a bounty on the bug and attract more developer eyes on it? :)

**Comment by blurymind** [comment]
This is not a yarn bug, but a bondagejs bug that is already reported here
https://github.com/hylyh/bondage.js/issues/31

**Comment by 4ian** [comment]
It's still understandable that people suffering from this might search in the GitHub issues first... maybe I can create a new label for these kinds of bugs - so that even we close them, after making sure that there is an equivalent bug in bondage.js repository, we can easily find them?

**Comment by blurymind** [comment]
The shortcuts actually do work. The bug is not that they don't. But you
have to indent the text with tab, otherwise bondagejs sees it as a syntax
error and crashes.
I can do a pr to it to try and fix that but it could be time consuming and
my previous one hasn't been merged yet

**Comment by blurymind** [comment]
Maybe we should add a known problems section to the wiki, I think its a good idea to notify peoplein advance about things like this

**Comment by 4ian** [comment]
> Maybe we should add a known problems section to the wiki, I think its a good idea to notify people in advance about things like this

Yep totally!
And a few links to it in the rest of the doc.

**Comment by blurymind** [comment]
I have added a known issues section to the wiki, to notify  users in advance about this external to gdevelop problem as well as others
http://wiki.compilgames.net/doku.php/gdevelop5/all-features/dialogue-tree

**Comment by PascalLadalle** [comment]
> 
> You are again creating a bug at the wrong tracker without doing any research
> [hylyh/bondage.js#31](https://github.com/hylyh/bondage.js/issues/31)

Ehm... I do my research, but within the scope of the software I'm using, GDevelop. I check the forum, the wiki, and I play with the events to try and isolate the bugs I have.
I'm **not** a dev, I can hardly read javascript or use the ctrl-shift-i tool.
I tried to clone GDevelop to bring "easy" contributions, but outside of text typos, it's a nightmare to understand for a _muggle_ like me. 
 
It would seem strange to me to open a bug on an external element tracker without first making sure that the problem doesn't come from the software I'm using that element in. 🤔 
If my toaster dies and I see that the power cord is damaged, I won't call the power cord manufacturer, I'll call the brand who sold me the toaster (not such a great parallel, I know).

I don't get why opening a report here _first_ to check the GDevelop side is a problem, but feel free to close it. 

PS: the _useful links_ don't work.

**Comment by blurymind** [comment]
@hylyh describes at the linked bug how bondagejs is is expecting it to work.
The unit test of bondagejs actually have a yarn json file here
https://github.com/hylyh/bondage.js/blob/master/tests/yarn_files/shortcuts.json

Use it as an example of how to do shortcuts

**Comment by PascalLadalle** [comment]
Yeah, not a priority. After all, the feature is not in our wiki or example project. 
I just happened to see the feature while reading the yarn docs and decided to give it a try.
As long as the issue is mentioned in our wiki, it's fine by me. 👌

**Comment by 4ian** [comment]
Glad to see that documenting this should be enough :) 

I know it's sometimes frustrating on both sides (getting to be told "it's not GDevelop fault" or getting issues made in GDevelop while it's better managed in the downstream project that we're using) but I think we should continue to encourage opening issues (it's a kind of documentation), as long as we're proactive in triaging them (adding the label as I did) - so that they are not polluting too much the other issues that are entirely GDevelop related.
