### ISSUE TITLE
Tween instructions problem / Right-click editor and behavior-related instructions

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1715]
I have object A with tween behavior attached.
I add a first tween action: tween scale of A to 1.2 as "somename".
Then, I copy-paste that action, and change the values to a new tween name and to scale 0.8.
I add some conditions to avoid conflict, and I try.
And that second action won't work until I double click on it to open it "fully".
I just need to double-click on it and close it, and then the tween works as expected.
Quite frustrating because I triple-checked the values, tried and tried again, and when I double-clicked on the event by mistake, it fixed the whole thing. 😒 
It seems to happen with both conditions and actions.

Possibly related to that report, but not sure, since this time, the behavior is attached to the object: https://github.com/4ian/GDevelop/issues/1198
Not sure if related to that other tween bug I flagged recently.

Here's an example project, if it works on your side...
[bugtweencopypaste.zip](https://github.com/4ian/GDevelop/files/4564954/bugtweencopypaste.zip)
Open preview and release space key, no tween.
Go to events, double click on the tween actions and click ok.
Now preview again, the tweens work.

**Comment by Bouh** [comment]
With a diff tool on the json code when we copy paste the instruction we can see the Tween behavior is missing.

On left when i open the project. | On right after open and close with OK button the instructions wihout change the parameters.
![image](https://user-images.githubusercontent.com/1670670/80842484-fd416a00-8c01-11ea-82d6-cc4ec4e5acb5.png)

**Comment by Bouh** [comment]
This missing parameter can be possible only if you create the event first, and after add the behavior to the object.

**Comment by PascalLadalle** [comment]
Oh, I think I got it.
It happens when I create the tween event by using the right-click menu. Can you replicate now?
I must have copy-pasted before fixing the first event so it propagated?

**Comment by 4ian** [comment]
I think the issue is indeed the right click editor not filling the behavior
parameters.

**Comment by Bouh** [comment]
Another report about it, this is defenitively the behavior when the right click is used with the new fast instruction editor.

[Reported by an user on forum](https://forum.gdevelop-app.com/t/simulate-keys-not-working-properly-in-5-0-0-beta95/25461/2)

**Comment by Bouh** [comment]
@blurymind

**Comment by 4ian** [comment]
Right this is really a bad looking bug as hard to debug. I'll take a look

**Comment by 4ian** [comment]
Fixed for next version :)
