### ISSUE TITLE
Text in event groups is not replaced

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1716]
The replace feature of the events sheet doesn't work on event groups.
_Search_ detects the string, but _replace_ doesnt replace.
![image](https://user-images.githubusercontent.com/25978830/80823033-2222e680-8bdc-11ea-996b-1fc58974ba37.png)

Maybe somewhat related to #970 ?

GD 5 beta 92

**Comment by Bouh** [comment]
For text comment this work ?

**Comment by PascalLadalle** [comment]
Nope, not working for comments either, indeed.

**Comment by PascalLadalle** [comment]
Same issue in repeat blocks, it seems: https://forum.gdevelop-app.com/t/3-bugs-not-replacing-in-repeat-blocks-autosaved-files-and-nested-variables-issues/25521

**Comment by PascalLadalle** [comment]
Fixed
