### ISSUE TITLE
Dialogue extension : unable to use nodes with only one option(answer)

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#1719]
Hello, i'm not sure this is really a bug, but it's an issue:

When using a node with a single option (answer), the option isn't displayed and the previous node is played instead. We had [a talk on the forum about this](https://forum.gdevelop-app.com/t/dialogue-extension-issue-with-node-containing-only-one-option-answer/24476)

My plan is to adopt the dialogue extension to replace my homemade dialogue system used in my project Swamp (already 6 languages in the demo even more in the final game). For this, i have to use a lot of nodes with only one single answer like "go back", "Good bye",etc. It's a bit strange that yarn seems to impose a minimum of 2 options. Is it possible to fix this and make the nodes works as well with one or X options ?

To reproduce, just check the linked project, and compare how the the first and second Json files displays: http://s000.tinyupload.com/index.php?file_id=40659194908272531636

**Comment by blurymind** [comment]
Yarn syntax treats single options as links to other nodes to continue to.
It is intended that way so you can conditionally jump to nodes depending on
variables

**Comment by blurymind** [comment]
It's not a bug, you can even see it in the demo project. Perhaps you can
build something with the event sheet to achieve what you need

**Comment by KinkGD** [comment]
Ok, thank you :), i close this so.
