### ISSUE TITLE
AND incompatible with "compare" conditions

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1729]
This returns true:
![image](https://user-images.githubusercontent.com/25978830/80918791-f54f0a80-8d66-11ea-96bf-cddf61edf2e3.png)

But this returns false:
![image](https://user-images.githubusercontent.com/25978830/80918746-d81a3c00-8d66-11ea-9523-c8301041e5cc.png)

Even this returns false:
![image](https://user-images.githubusercontent.com/25978830/80918765-e5cfc180-8d66-11ea-89db-168e4f18165d.png)

GD5 beta 92
reported on [the forum](https://forum.gdevelop-app.com/t/bug-with-advanced-condition-and/24649/3)

**Comment by 4ian** [comment]
Can you attach a very simple example game? (I know this sounds dumb, but everything that can help me to verify bugs in less than 30s is helpful).

**Comment by PascalLadalle** [comment]
Here goes:
[bugAndoperator.zip](https://github.com/4ian/GDevelop/files/4570918/bugAndoperator.zip)

**Comment by 4ian** [comment]
Thanks! I think I identified the issue (incompatibility between AND and almost only this condition) and fixed it. Will finish the fix and should be working well in the next version :)
