### ISSUE TITLE
Please document setBackgroundColor()

### ISSUE THREAD

**Issue by HiranChaudhuri** [4ian/GDevelop#1735]
Looking at the documentation of runtimeScene.setBackgroundColor() at
https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/gdjs.RuntimeScene.html#setBackgroundColor
I see this:

> setBackgroundColor()
> Change the background color
> 

This unfortunately does not specify how the background color has to be specified. Is it a string? Is it a number? From examples I see it is three numbers, and their range seems to be 0-255...

**Comment by 4ian** [comment]
Indeed! Should be easy to fix, feel free to submit a PR with the added annotations (and getBackgroundColor would need some love too).

**Comment by HiranChaudhuri** [comment]
While I am willing to do so I am an absolute novice to JavaScript. I just read the generated documentation.
Where can I read how the necessary annotations have to be written?

**Comment by 4ian** [comment]
Ah sure I was assuming you were familiar with JavaScript and RGB colors.
I documented this, see the changes here as an example if you want to do the same in the future:
https://github.com/4ian/GDevelop/commit/11c29f444e6261d26994ec287510c851e00c7853

The online documentation should be automatically updated in ~1 hour. :)

**Comment by HiranChaudhuri** [comment]
Thank you for that. It seems the annotations are pretty similar to Javadoc but not the same. Is there somewhere a specification?

Another thing I stumble over is "a hexadecimal number". Would that not be  a string? Or are you referring more to a 24bit value made up of the bits rrrrrrrrggggggggbbbbbbbb?
Sorry, this may sound pedantic, especially since such documentation would help if done on each and every method. This likely is a project of its own.

I can try to write such chunks every now and then but definitely would need someone to verify the content.

**Comment by 4ian** [comment]
>  It seems the annotations are pretty similar to Javadoc but not the same. Is there somewhere a specification?

Yes, it's called JSDoc: https://jsdoc.app/

> Another thing I stumble over is "a hexadecimal number". Would that not be a string? 

No it's a number, as it's represented in memory by a number (even if most people think of it as a string like `#AB10BB`).

> Or are you referring more to a 24bit value made up of the bits rrrrrrrrggggggggbbbbbbbb?

Yes this is it :)

> I can try to write such chunks every now and then but definitely would need someone to verify the content.

Sure, feel free to submit PRs :) I'll comment if there is something false - I'm actually quite pedantic when it comes to write good documentation :D But as you mentioned this is a long task so help is welcome.

**Comment by Kushagraw12** [comment]
Is this issue still open? Can i work on it? Please help me start!

**Comment by 4ian** [comment]
It's fixed in 11c29f4. Feel free to start by reading the Readme and finding any open issue that you would like. "Good First Issues" are a good thing to check out: https://github.com/4ian/GDevelop/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%91%8Cgood+first+issue%22
