### ISSUE TITLE
ITMS-90809: Deprecated API Usage- Unable to submit to App Store Connect

### ISSUE THREAD

**Issue by ZapChase** [4ian/GDevelop#1736]
App Store Connect email response

 New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 
## To Reproduce
1. Submit from Xcode to App Store
2. Receive email from App Store with above text.

**Comment by arthuro555** [comment]
Please discuss such issues on the forum first and port it to GitHub when other users confirm it's a real issue with GDevelop. You would have seen that this problem has nothing to do with GDevelop but is just you using an outdated Cordova version (see my answer on the forum).

**Comment by ZapChase** [comment]
I just used cordova  9.0.0 and the issue persists.

**Comment by arthuro555** [comment]
Again this is not the place to talk about this. Here is a place for gdevelop issues, not cordova.

**Comment by 4ian** [comment]
This is still probably something that we have to workaround inside GDevelop.
Thread on the forum: https://forum.gdevelop-app.com/t/itms-90809-deprecated-api-usage/24746

@ZapChase If you can try the workaround explained by @arthuro555 that would be greatly helpful :) Thanks!

**Comment by ZapChase** [comment]
I will try what was added in forum post / documentation. And not touch this thread again. Thank you for your patience.
