### ISSUE TITLE
CircleCI fails

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1739]
Circle CI is not working properly apparently since it keeps failing on each comit since a while ago. This can be a problem for example for users who want to use the nightly version and makes GDevelop "look bad" (code checks always failing like we are incapable of writing clean/working code)

**Comment by 4ian** [comment]
Yep that's a memory issue. I contacted the CircleCI and tried to find a way to use less memory when building the IDE (like something to limit the number of parallel processes used by Node.js), but seems that nothing is working. We would need a larger machine with 4GB+ ram, which is only in the paid plans :/

**Comment by arthuro555** [comment]
(This is only a suggestion) Maybe the GDevelop Paid plans can cover costs for a paid circle ci plan?

**Comment by 4ian** [comment]
There are a bunch of costs associated with AWS servers, the website hosting, the forum hosting, etc... so as much as possible I prefer to stay on the free plans of CIs. If there are no other options, I'll get a paid plan for Circle CI.

**Comment by arthuro555** [comment]
I don't know how much it costs and everything, but if you decide that it won't be possible to continue with circleci without paying a subscription, maybe an alternative would be to use some selfhosted ci like jenkins? Again I have no idea if it would cost more or less I am just throwing that idea.
