### ISSUE TITLE
Key not valid but working

### ISSUE THREAD

**Issue by mxslam** [4ian/GDevelop#1745]
![image](https://user-images.githubusercontent.com/59655284/81501474-dc9ba300-92d8-11ea-9484-365472525139.png)
this condition is working but it is not valid on the screen

**Comment by pranavmodx** [comment]
@mxslam Could you be more specific - as in how to reproduce the bug?

**Comment by mxslam** [comment]
![image](https://user-images.githubusercontent.com/59655284/82073463-93cd5b00-96d9-11ea-9a00-3b938b4a4513.png)
NumpadAdd/NumpadSubtract is not a valid key string but this condition is working

**Comment by PawBud** [comment]
Would you mind sharing your project, @mxslam? I would like to test it on my dev version just to check if the Numpad keys are actually working or if I need to make further changes to accommodate the new key bindings. It will be easier for me that way!

**Comment by 4ian** [comment]
Should be fixed by #1758, thanks all!
