### ISSUE TITLE
Show completions and expression selector button for layer parameters

### ISSUE THREAD

**Issue by Keevle** [4ian/GDevelop#1749]
![](https://i.imgur.com/cq8crYx.png)

Currently Layers are preset with the available names,That's cool,But i'd like to be able to also use strings via programming to determine a layer like "Camerazone.Layer" =layer i'm supposed to be doing something on like i'm able to do with these other layer related variables(Camera angle/layer angle) 
![](https://i.imgur.com/lJ8hxXV.png)

**Comment by 4ian** [comment]
It's not obvious because we should add the `"ABC"` button on the right, but layer parameters are actually string that can use any function like other strings :)
I'm renaming this issue to add the button to the `LayerField`.

**Comment by AlexandreSi** [comment]
Closing this issue as it seems to have been done in #2663
