### ISSUE TITLE
Renaming of a scene on beta94 blocks gdevelop

### ISSUE THREAD

**Issue by dark00shadow** [4ian/GDevelop#1756]
## Describe the bug
the bug is that scene renaming will not work as in gdevelop not work and just shuts in a way 

##Error Message

https://www.dropbox.com/s/ztnshw0mu0k0rz0/error%20message%201.txt?dl=0

## To Reproduce/ Video
https://www.dropbox.com/s/kcvq6b8nmp8xeh1/2020-05-15%2017-23-37.mp4?dl=0

## Other details
I'm using beta 94
I'm using windows 10

**Comment by HarsimranVirk** [comment]
@4ian seems like a regression of MainFrame. As far as I remember renameLayout didn't have anything related to closures (newState/newProps).

**Comment by 4ian** [comment]
Yep almost certainly a regression - might be my recent MainFrame refactoring. I'll take a look later today unless you want to check what's going on. I suspect a silly mistake somewhere :)

**Comment by 4ian** [comment]
Found the regression, will push a fix soon.

**Comment by 4ian** [comment]
This is solved for next version. I'll try to push a beta 95 soon. In the meantime, prefer to temporarily use beta 93 if you need to rename a scene. Thanks for reporting the issue!
