### ISSUE TITLE
no isometric features (please implement isometric grid and normalize diagonal movement)

### ISSUE THREAD

**Issue by banti101** [4ian/GDevelop#1764]
there is no implementetion of any isometric game features.... as its a 2d game engine.
1/ no way of normalize diaonal movement.... even if it can be done in some way, no good tutorial nither any documentetion...
2/no isometric grid option.
3/no light.

**Comment by 4ian** [comment]
Please use the forum to formulate your requests first please or vote on the roadmap :) 
Someone will then create cards where you can vote. Thanks!

**Comment by banti101** [comment]
There is no option to vote for this issue... No one is taking about this...
But isometric ability is must for a 2d game engine... Please make a card on
this issue.

**Comment by blurymind** [comment]
There is a card on the Trello board. Search for isometric. Honestly some of
the other things you are listing have nothing to do with it with isometric
gameplay. They make it feel like something you would write to santa
