### ISSUE TITLE
Congratulations on this wonderful and exciting project!!!

### ISSUE THREAD

**Issue by inglesuniversal** [4ian/GDevelop#1766]
May your creativity keep growing and help developers like me, gain inspiration from the time you devote and bring to life these amazing and revolutionizing tools you create with hard work, persistence and love for what you do!

Best regards and STAY SAFE!

Meet you for a beer in London in the coming months :)

**Comment by 4ian** [comment]
Thanks! Appreciate your kind words 😄

Stay safe too :)
