### ISSUE TITLE
 Strange movement

### ISSUE THREAD

**Issue by Ducking0** [4ian/GDevelop#1767]
## Describe the bug
I have two objects.
They should be moving at the same speed but they are moving at different speed.
![Screenshot_17](https://user-images.githubusercontent.com/65650593/82424473-e7e78f00-9a8d-11ea-815f-f201bef35f24.png)

I also made test in new Project.
![Screenshot_1](https://user-images.githubusercontent.com/65650593/82425907-d606eb80-9a8f-11ea-96d9-f54c297d5076.png)

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. create a Platformer project.
2.Make the same code as in the example
3.Make objects in example 
touch each other.
4.Run the game
5.See the bug
test:
https://drive.google.com/open?id=1xvV0eCd77bomW9K7_BrpqDJladIk_FaO

## Other details
* Windows 7 x64 
* Working on Dekstop and Web
* Please help

**Comment by Ducking0** [comment]
Please Help!

**Comment by 4ian** [comment]
Please don't spam, one message is enough :)
Have you asked first on the forum so that other members can verify you've not done an error before reporting here as a bug?

**Comment by Ducking0** [comment]
no

**Comment by 4ian** [comment]
Please do it on the forum first then, and re-open this only if their is a verified bug confirmed by another community member. Thanks!
