### ISSUE TITLE
Panel Sprite Blurs Even with No Antialiasing

### ISSUE THREAD

**Issue by VATstudios** [4ian/GDevelop#1774]
My pixel platformer game uses panel sprites as platforms, but even with No Antialiasing they are still blurred when I run the game. It's not too big a deal but it makes the platforms look weird. I'm on the latest version of Gdevelop.
![image](https://user-images.githubusercontent.com/29460573/82856340-f806d080-9eca-11ea-9a9b-1d5517aa84a9.png)

**Comment by 4ian** [comment]
Can you please report this on the forum so that other members can see with you if you're not missing a setting (coordinates not rounded, texture smoothed, antialiasing activated in project)?

**Comment by PascalLadalle** [comment]
It would seem that the issue occurs when the camera is zoomed.
Normal:
![image](https://user-images.githubusercontent.com/25978830/167897062-6c5136ce-f438-4a1f-9261-db16f62a9353.png)
x2:
![image](https://user-images.githubusercontent.com/25978830/167897099-712450ea-8bb9-4a21-8757-af2273351129.png)
x4:
![image](https://user-images.githubusercontent.com/25978830/167896798-2b3d7e2c-72d5-4b24-9de9-a8f13c310e6d.png)

[source](https://forum.gdevelop.io/t/panel-sprites-9-patch-anti-aliasing-issue/39661)
