### ISSUE TITLE
code view to see your code as js 

### ISSUE THREAD

**Issue by sfn101** [4ian/GDevelop#1775]
I don't know if it possible or not but it will be cool to have the ability to read and edit the code behind the game it will be helpful for people  that try to learn coding to and for pro-coders to be faster

**Comment by 4ian** [comment]
Let's discuss this first on the forum before opening an issue on GitHub, as this is a large feature request and I'm not sure it would be bringing much usefulness. You can create a thread on the forum to get other members views about this :)
