### ISSUE TITLE
[new example] the classic snake game

### ISSUE THREAD

**Issue by sfn101** [4ian/GDevelop#1776]
hi I noticed there is no snake game example in Gdevelop  and I tried to find one online but I couldn't so I made one it is only a event no code needed, it has a fake grid movement  and full commented

btw it is my first time using Gdevelop I hope you like it 

[ google drive ](https://drive.google.com/open?id=1bb5OxW4r9GO_ubIsTzmrt4qJEREmtHgs)

**Comment by Midhil457** [comment]
Hi @sfn101. Sorry for the late reply. Seems that the link you provided is giving a 404 error. Can you share a new link?

**Comment by 4ian** [comment]
It's fairly old, I'm closing the issue and a new one can be re-opened later if needed.
