### ISSUE TITLE
GDevelop Web App: Scene Disappears after switching to another tab

### ISSUE THREAD

**Issue by PawBud** [4ian/GDevelop#1786]
Alright, So Recently when I did `npm start` on the dev web app of GDevelop and I found this happening. 

![2020-06-03-18-26-10](https://user-images.githubusercontent.com/48093317/83654487-d1d3e580-a5da-11ea-9677-a4f27193507f.gif)

Let me explain if it's not clear.
**Steps to reproduce:-**
1. `cd newIDE/app && npm start`
2. wait for the development version to start.

Click on the `new Events` or the `Start Page` tab or for that matter click any tab that basically routes you away from the `Scene` tab. when you return to the `New Scene` tab (In this case), then the whole scene turns gray and nothing is visible no matter what you do until you open any of the tables or lists from the toolbar. Only then the scene is displayed. 

The issue doesn't end there; If you close the table/list the area becomes grey(not the full scene like before). This is fixed when you open another table/list and close both.

@arthuro555 suggested that I should re-install the `package.json` and the `node-modules`.I did that but the issue persisted. Moreover, I re-installed the whole repository and ran it on the `beta-95` branch after installing the necessary modules. And the gif above is the result. 

OS version:-  
OS:-  ubuntu 18.04 LTS

@4ian I am extremely sorry if I am doing something wrong; you may certainly close this issue if that's the case.It's just that I have not been able to work on any of pending PR's or issues due to it.

Cheers :)

**Comment by PawBud** [comment]
I am sorry for the weird squares on the gif; something was wrong with obs Studio

**Comment by 4ian** [comment]
Is this issue happening on editor.gdevelop-app.com?
What is your browser?
Is this issue happening on the development desktop version?
Can you paste what's shown inside the Chrome developer console? Is there any error or warning?

**Comment by PawBud** [comment]
> Is this issue happening on editor.gdevelop-app.com?

Yes, it is now that you mention it!
> What is your browser?

Google Chrome
Version 83.0.4103.61 (Official Build) (64-bit)
> Is this issue happening on the development desktop version?

No, it's not
> Can you paste what's shown inside the Chrome developer console? Is there any error or warning?

https://drive.google.com/file/d/1JAA9aIO8RexKGDtEbGHR3LqcFmPAoqt-/view?usp=sharing. I think gif will lower the quality hence drive should do the job!

**Comment by Bouh** [comment]
This happend to me too under chrome Version 83.0.4103.61 (Build officiel) (64 bits) but not on Version 83.0.4103.97 (Build officiel) (64 bits) on editor.gdevelop-app.com

Version 83.0.4103.61 (Build officiel) (64 bits) - bugged like in the video.
Version 83.0.4103.97 (Build officiel) (64 bits) - work fine.

[Here an video.](https://streamable.com/ni6rjz)
[Here the log file.](https://pastebin.com/raw/cb1vrfqg)

**Comment by 4ian** [comment]
Thanks for the video, very useful. Should be consider this as a Chrome bug then? Seems not like something we can fix from GDevelop.

**Comment by PawBud** [comment]
Yup; I think I'll keep it as a forum topic if you don't mind? Since if another user experiences the same then I guess the topic will help?

**Comment by 4ian** [comment]
Yes could be useful, also will help getting feedbacks from other users if they are impacted.

**Comment by PawBud** [comment]
you may close this issue if you would like to do so!

**Comment by PawBud** [comment]
Discussion regarding this issue may take place over [here](https://forum.gdevelop-app.com/t/gdevelop-web-app-scene-turns-grey-after-switching-to-another-tab/25512)
