### ISSUE TITLE
Optimization Suggestion: Code generation caching

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1788]
Problem:
Everytime you generate code, it regenerates everything. Especially with bigger games compilation can be very long (up to 3 minutes per preview).

Solution:
Caching Generated code and reuse it instead of regenerating the whole code.
That would mean, for every thing that has code to genearte (A layout, an event sheet, an Event), add a "dirty" property and a "codeCache" property. Modifying anything on it would set the dirty flag to true. Code generation will regenerate the code and store it in codeCache only if dirty is true, else it will just return the cachedCode.

**Comment by 4ian** [comment]
Added on the roadmap: https://trello.com/c/VwXaDiTK/443-speed-up-preview-launching-after-making-some-changes-in-events-by-only-regenerating-code-of-changed-event-sheets ;)

I was actually thinking of doing this for hot-reloading, but that's actually a new feature/optimization that is a bit more complex that what it could look like (you have to use UnsavedChanges to spy on changes, mark events/external events as dirty, then use the DependenciesAnalyzer to check for each layout if it's depending on the changed events/external events) (then you have to reset this if the project is changed, etc... caching things is always leading to risk of forgetting to reset something and ending up with weird bugs).

I'll close this but discussion can continue.
