### ISSUE TITLE
Deleting global children crashes GDevelop

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1789]
## Describe the bug
The GDevelop window becomes blank when deleting the children of a global variable structure.

## To Reproduce
Create a Global variable.
Click on the + to create a child.
Click on Apply to save.
Go back to the Global variables, tick the child and click on Delete.

Console output:
![image](https://user-images.githubusercontent.com/25978830/83691211-1919a080-a5f2-11ea-9052-9a9abddb801f.png)

Tested on [MacOS ](https://forum.gdevelop-app.com/t/solved-project-stopped-opening/25371/7)and Windows 10

The macOS user reported that his project json file was emptied by GDevelop twice (0 byte size). It shouldn't be related, but could it? 😕 
I tried saving after the crash, but it didn't work for me, the asterisk remains next to the path.

**Comment by Bouh** [comment]
Version tested for this issue:
b92 - ok
b93, b94, b95 - bug

**Comment by 4ian** [comment]
Thanks for reporting! This is now fixed.

> The macOS user reported that his project json file was emptied by GDevelop twice (0 byte size). It shouldn't be related, but could it? 😕

Should not be the case, but I wonder what could be the result of trying to save after such a crash. I can try to add a safeguard checking if the project to save is empty and if yes abort the saving.
