### ISSUE TITLE
Overwriting of builtin extensions possible

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1793]
## Describe the bug
When you create an eventFunctionExtension, you can name it like a with GDevelop bundled Extension and it will override that extension.

## To Reproduce
1. Create a new events Functions extension
2. Rename it to "Sprite"
3. See how it replaced the extension (through the event sheet or seeing in the console the loading message saying `(replacing existing extension)`.

## Possible fix
Refuse to Rename to an existing extension's name (revert renaming and display an alert)

**Comment by 4ian** [comment]
Interesting ^^ Wonder how badly this can break the app. We should indeed consider builtin extensions when checking the name of the extension - we're already validating that an existing (events based) extension with this name is not existing.
