### ISSUE TITLE
Can't activate behaviors in extensions unless the function parameter name is the same as the behavior

### ISSUE THREAD

**Issue by Genhis** [4ian/GDevelop#1796]
## Describe the bug
It is not possible to activate behaviors in extensions (either from a behavior itself or an external function) unless the function parameter name is the same as the behavior.

## To Reproduce
1. Create a new behavior `Test`
2. Create a global function (action type) accepting an object and the behavior `Test` and name your parameters `Object` and `Behavior`
3. In the function, activate the behavior
4. Run the function as part of your scene events
5. The behavior does not activate

Attached `game.json` as txt: [game.txt](https://github.com/4ian/GDevelop/files/4740849/game.txt)

## Workaround
Rename your function parameter `Behavior` to `Test` - the behavior now activates correctly. Unfortunately, this is not possible in behavior internal functions, such as `onCreated`, because the `Behavior` parameter name is built-in.

## Other details
- Windows 10
- GDevelop 5.0.0-beta95

**Comment by 4ian** [comment]
Good catch! There is indeed an issue with names of behaviors not propagated properly in functions. I'll take a look, it's not great to have this not working.

**Comment by 4ian** [comment]
Fixed for next version :) Thanks for reporting it and thanks a lot for the example game - it was very useful. Behaviors in extension should work better in the next version.
