### ISSUE TITLE
Found a bug with force position

### ISSUE THREAD

**Issue by dark00shadow** [4ian/GDevelop#1797]
## Describe the bug
what is the bug: https://www.dropbox.com/s/jmhz0xs7zfio9pl/BugVideo001.mp4?dl=0 4

since Idk what to say ill give the video(i know this won't make sense but hope this helps)

**Comment by 4ian** [comment]
It's hard to understand precisely what the bug is. Please report it on the forum and see with the other members if you can make a small game showing exactly the issue. Thanks!

**Comment by dark00shadow** [comment]
> It's hard to understand precisely what the bug is. Please report it on the forum and see with the other members if you can make a small game showing exactly the issue. Thanks!

I DID

**Comment by dark00shadow** [comment]
> It's hard to understand precisely what the bug is. Please report it on the forum and see with the other members if you can make a small game showing exactly the issue. Thanks!

LOOK ON THE FORUM I DID PUT IT THERE but idk how to make the issue ill test in another project i thinks its force(i can  give my project that is quite small)

**Comment by dark00shadow** [comment]
> It's hard to understand precisely what the bug is. Please report it on the forum and see with the other members if you can make a small game showing exactly the issue. Thanks!

here is the eaxmple https://www.dropbox.com/s/0czhb2jzlzg760g/EXAMPLE.zip?dl=0
