### ISSUE TITLE
Accidente mientras usas un editor

### ISSUE THREAD

**Issue by benjaminkkiu** [4ian/GDevelop#1798]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in j
    in div
    in r
    in div
    in s
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in E
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in H
    in r
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Z
    in b
```

## Other details
* IDE version: 5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta95 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Not enough information unfortunately, closing now!
