### ISSUE TITLE
Tween "is finished playing" condition never triggers

### ISSUE THREAD

**Issue by CJCShadowsan** [4ian/GDevelop#1799]
Tween "is finished playing" conditions never trigger when using X/Y position transition.

Was aiming to 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to a sprite
2. Add a tween behaviour to it
3. Add an event to move the position of the sprite to a location
4. Add a sub-event with a condition to wait for completion of the tween with an "is finished playing" element - it never works.

![image](https://user-images.githubusercontent.com/16232240/83973278-2d54ea80-a8dd-11ea-9a55-e34e809891e8.png)

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Win 10
* GDevelop 5.0.0-beta95 desktop app

**Comment by Wend1go** [comment]
You are only checking for the "has finished playing" condition when "The cursor/touch is on Home". As soon as the mouse cursor leaves the button, the condition wont be checked anymore.
Try to "unindent" the sub event so that it has the same level as the parent event and it should work as expected.

**Comment by CJCShadowsan** [comment]
> You are only checking for the "has finished playing" condition when "The cursor/touch is on Home". As soon as the mouse cursor leaves the button, the condition wont be checked anymore.
> Try to "unindent" the sub event so that it has the same level as the parent event and it should work as expected.

I wish it was...

![image](https://user-images.githubusercontent.com/16232240/84014982-152faa80-a973-11ea-9bd8-164b39177879.png)

That still results in no scene change at the end of that tween.

**Comment by Wend1go** [comment]
This works perfectly fine on my side, could you share your project please?

**Comment by CJCShadowsan** [comment]
You were correct the first time - if I move the event outside of the subevent tree to effectively just listen for the "homechange" tween, then once it finishes it runs.

Case closed - thanks for the help!
