### ISSUE TITLE
Tab system main menu example

### ISSUE THREAD

**Issue by RIR360** [4ian/GDevelop#1801]
### Tab system main menu example for Gdevelop (PC)
I hope this example will help the user to create a straight forward and clean main-menu for their game. 

**What's in it:**
* Use of instance variable
* Clean User Interface
* Mouse hover and active state button animations
* Tab system menu (by hiding and showing layers)
* Tween animation
* Helping comments on the event-sheet

**Download the files:**
[Tab_menu_by_RIR.zip](https://github.com/4ian/GDevelop/files/4746739/Tab_menu_by_RIR.zip)

 _I confirm that any assets can be used freely by anybody, including for commercial usage._

**Comment by 4ian** [comment]
Looks nice! :) I'll add this (or anyone wanting to make a PR).

**Comment by 4ian** [comment]
Added for next version! :)
