### ISSUE TITLE
Layer Effects seems to have a rendering bug related to boundary box

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#1802]
## Describe the bug
When using the Advanced Bloom layer effect in Gdevelop, it seems to only render to the sprite's boundry box. This behavior is not seen in the PixiJS Advanced Bloom filter example

## To Reproduce

1. Steps to reproduce the behavior:
2. Create a new project, I've used the Platformer example.
3. Create a new layer
4. Add the Advanced Bloom effect to that layer.
5. Select one of the coin instances.
6. Move it to that new layer. 
7. Run a preview.
8. You'll see the coin has bloom...that cuts off exactly where the boundary box is for that coin.
![image](https://user-images.githubusercontent.com/24237149/84051130-4ceb2200-a974-11ea-877a-eb41dce94c1d.png)

Here are the settings for the bloom filter in the above screenshot:
![image](https://user-images.githubusercontent.com/24237149/84051355-a5baba80-a974-11ea-8736-e4fd84b09b86.png)

Compare this to the PixiJS Filter demo: https://pixijs.io/pixi-filters/tools/demo/

![image](https://user-images.githubusercontent.com/24237149/84051446-cc78f100-a974-11ea-9e63-d4363e441ae5.png)

Even if you pump up the bloom scale/brightness, you never cut off in the example.

## Other details
Windows 10 64 Bit
GD5 Beta 95 - Desktop

**Comment by Silver-Streak** [comment]
As a note: I confirmed this behavior also occurs with the Glow filter, so this seems to be something specific to GD5 implementation of these filters.

**Comment by 4ian** [comment]
Can you try after adding a background image to the platformer? Some effects might behave strangely if there is nothing behind.

**Comment by Bouh** [comment]
This is due to the pixi container used for layers.
The container wrap the objects on the layer, objects on opposite are used for doing the bounding box of this containers.
So on your screen your coin is alone on the layer right ?

As we can see with the pixi tool. the container stop on top, and the glow is cropped.
![image](https://user-images.githubusercontent.com/1670670/84055973-dcfd8b80-a9b5-11ea-8632-c407103a9d05.png)

**Comment by Bouh** [comment]
Same thing with one object on a layer.
![image](https://user-images.githubusercontent.com/1670670/84056287-4c737b00-a9b6-11ea-9ad4-174e786fcad8.png)

The container fit the object. that why effect is cropped.

**Comment by Silver-Streak** [comment]
@4ian :
> Can you try after adding a background image to the platformer? Some effects might behave strangely if there is nothing behind.

Yep, no change. 
![image](https://user-images.githubusercontent.com/24237149/84057167-e6b6cd00-a97c-11ea-8564-c315b05b6801.png)

@Bouh :
> This is due to the pixi container used for layers.
> The container wrap the objects on the layer, objects on opposite are used for doing the bounding box of this containers.
> So on your screen your coin is alone on the layer right ?
> 
> As we can see with the pixi tool. the container stop on top, and the glow is cropped.

Is there a reason why the PixiJS example doesn't do it this way? Or rather, is there a benefit to GDevelop for doing it this way?

**Comment by Silver-Streak** [comment]
Additional info: 

Adding another sprite to the glow layer (in this case, moving my BG image to the glow layer) does fix this, but it would make it pretty impossible to use most filters/layer effects this way since you rarely want everything to glow:

![image](https://user-images.githubusercontent.com/24237149/84057949-1adebd80-a97e-11ea-9a5f-ca2231725367.png)


Adding the BG to that layer and Hiding the sprite via events does not work. Back to the same issue as originally mentioned: 
![image](https://user-images.githubusercontent.com/24237149/84058004-2f22ba80-a97e-11ea-9f72-2dfc52c367ae.png)

Adding a sprite that is just transparent pixels to that layer does work: 

![image](https://user-images.githubusercontent.com/24237149/84058066-4d88b600-a97e-11ea-936a-bd3d74aada00.png)


I obviously don't understand enough of how this works, but is this something that could be fixed by making the container always be the same size as the Camera, if there is a layer effect applied? (or some kind of toggle for this?)

**Comment by Bouh** [comment]
The effects on the demo are apply  with two different ways. 
On fish only (filters on object, this isn't yet in GD), or on the layer.

And because there is only one layer in the demo, this one contain everything the background, the fish and the water overlay, then the effect are show correctly.

**Comment by Silver-Streak** [comment]
> The effects on the demo are apply with two different ways.
> On fish only (filters on object, this isn't yet in GD), or on the layer.
> 
> And because there is only one layer in the demo, this one contain everything the background, the fish and the water overlay, then the effect are show correctly.

The 1 layer thing makes sense on why the demo works, Thanks.

However, even if we add filters on objects, since the containers are only the size of objects, wouldn't this issue still occur? Wouldn't that mean effects such as Bloom/Glow/etc will never work properly if the user doesn't want it to apply to every single object?

**Comment by 4ian** [comment]
Thanks both for investigating this. I recall something like adding a customizable paddings to objects in PIXI to avoid this kind of issues, but not sure if it's something that exists or not.

**Comment by Bouh** [comment]
You mean the [filterArea](https://pixijs.download/dev/docs/PIXI.Sprite.html#filterArea) ?
We can specify a pixi Rectangle,use the dimension of the original sprite, and add manually a padding on it.
