### ISSUE TITLE
Extensions aren't loaded after reloading.

### ISSUE THREAD

**Issue by HarsimranVirk** [4ian/GDevelop#1831]
This is more or less an issue targeted at devs, project files don't open at all after reloading. Auto-open isn't triggered at all, manually opening a file results in an indefinite loading state. This is maybe related to the recent refactoring of mainframe? (Might be because `openFromFileMetadata` was wrapped in a `useCallback` I guess). I haven't followed up with the mainframe for a long time now so I don't know exactly what's happening :) 

EDIT: Looking at the console, even extensions aren't loaded,  is it a windows specific thing (never happened on linux before)?

EDIT 2: It's windows specific, doesn't happen on linux.

**Comment by 4ian** [comment]
Strange it's working well on macOS too. I wonder if it's related to another issue - @Bouh reported issue with reloading too. I'll take a look

**Comment by Bouh** [comment]
Yes it's was this issue we have talked by email, [and in this PR](https://github.com/4ian/GDevelop/pull/1724#issuecomment-622996034).

**Comment by 4ian** [comment]
Can reproduce it indeed: 
![image](https://user-images.githubusercontent.com/1280130/85231584-64a0bc80-b3f0-11ea-9d5c-a0f6ed0ccc63.png)

I'll add more logs to try to understand what's going on.

**Comment by 4ian** [comment]
Very very strange, seems like there is an infinite loop of promises somewhere leading to a stop of the whole app. Using the debugger to stop the app seems to indicate a loop in Firebase:

![image](https://user-images.githubusercontent.com/1280130/85231959-8cddea80-b3f3-11ea-9b8c-d6aba2a86c1a.png)
![image](https://user-images.githubusercontent.com/1280130/85231985-aa12b900-b3f3-11ea-9f10-88069fe6cb96.png)

This seems similar to this issue reported recently: https://github.com/firebase/firebase-js-sdk/issues/3222

Though there is no actual requests being made (at least not shown in the debugger). The issue mentions only the problem on Windows and not macOS/Linux, which is also our case here. It also mention onAuthStateChanged that we use.

**Comment by HarsimranVirk** [comment]
Strange, but either way I guess there's nothing we could do from our side then :) Let's not waste anymore time on this, hopefully it will be resolved by firebase ;)

**Comment by 4ian** [comment]
Might not be related to Firebase actually, I've disabled it in Authentication.js and any callback (fs.readdir, etc...) is never called. It's like something is running or preventing callbacks/promise to be called. As soon as you launched something needing a callback, it's blocked (loading extensions launch readdir, which is asynchronous, so it's blocking).

**Comment by 4ian** [comment]
Same issue with Electron 8.3.3 and 9.0.4 - I was thinking of an Electron issue but no. Also compiling libGD.js without wasm (`npm run build` instead of `npm run build -- --dev` in GDevelop.js) does not solve the issue.
Definitely weird.

**Comment by 4ian** [comment]
After more inspection turns out it's all the file related (`fs`) functions that stop to work. @arthuro555 found this issue which seems related to Electron: https://github.com/electron/electron/issues/22119
