### ISSUE TITLE
Internationalization dosen't work, it's always stuck on EN

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1839]
## Describe the bug
We can't change the languague of the software in b97.
You can select, but the IDE is say in EN.

I think the locales are not the lastest version because the percentage show ~77% but we are almost on 100% in FR.
## To Reproduce
Try to change the language.

## Other details
* b97 everywhere

**Comment by 4ian** [comment]
Indeed! Not sure what broke exactly, but something to investigate.

**Comment by Bouh** [comment]
b95 work fine
Not test on b96

**Comment by 4ian** [comment]
For some reason the translations were almost all empty. This is fixed now, I'll release a new version soon!
