### ISSUE TITLE
"Trigger Once" condition is shared across instances of custom behaviour

### ISSUE THREAD

**Issue by osmiumforge** [4ian/GDevelop#1843]
## Describe the bug
When I have multiple instances of a custom behaviour, the trigger once condition only runs for the first instance
Please double check that the bug is not already reported in the issues list.

## To Reproduce

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

**Comment by 4ian** [comment]
That seems to be indeed an issue, each instance should have separately working "Trigger Once" conditions. I'll see what I can do.

**Comment by 4ian** [comment]
Should be fixed in next GDevelop version. I'll try to release one soon :)
