### ISSUE TITLE
New example - which is the language of the current user ?

### ISSUE THREAD

**Issue by mxslam** [4ian/GDevelop#1850]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: [lang.zip](https://github.com/4ian/GDevelop/files/4871016/lang.zip)

  I confirm that any assets can be used freely by anybody, including for commercial usage.
  
The code in JS :

 `var userlang = navigator.language; `
`runtimeScene.getVariables().get("lang").setString(userlang);`

use the expression VariableString(lang) and the result will be "fr", "en" ...

**Comment by PascalLadalle** [comment]
Nice!
But maybe it would be more useful as an extension, if it's only this snippet?

**Comment by mxslam** [comment]
oh yes maybe ! i will try do to it

**Comment by mxslam** [comment]
here ! sorry for the delay 
[Extension_lang.zip](https://github.com/4ian/GDevelop/files/5212152/Extension_lang.zip)
