### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Eliathx** [4ian/GDevelop#1854]
I've got no idea how to reproduce it so this won't be of much help, sorry. I was just using layers (not so many, just three) and the editor crashed. Luckily the project saved so progress was not lost

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in j
    in div
    in r
    in div
    in s
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in E
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in H
    in r
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Q
    in b
```

## Other details
* IDE version: 5.0.0-beta97-e8a1af0ef1d81d3689fe139bcb8a06dd3447e239
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta97 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
No error stack so hard to make a diagnostic. Closing this but let me know if you can reproduce the issue :)
