### ISSUE TITLE
Flicker ghost image

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1869]
Source topic:
https://forum.gdevelop-app.com/t/horizontal-vertical-flip-for-shapes-rotated-45-degrees/26249/2

The user is rotating and flipping a sprite as part of a custom flip.
All the events are placed under a Trigger once. Yet, we see the object being rotated for a frame, and then flipped.
Attaching zipped video to illustrate.
[Preview of Project 2020-07-15 00-38-13_Trim.zip](https://github.com/4ian/GDevelop/files/4931430/Preview.of.Project.2020-07-15.00-38-13_Trim.zip)
Sample project:
[testFlipRotate.zip](https://github.com/4ian/GDevelop/files/4937283/testFlipRotate.zip)

If all the events are under a trigger once, I think only one frame should display, so there should not be any flicker.

**Comment by Bouh** [comment]
The problem doesn't exist anymore in 5.1.158.
