### ISSUE TITLE
It just crashed :(

### ISSUE THREAD

**Issue by Kyle8530** [4ian/GDevelop#1889]
it just crashed bruh

**Comment by Bouh** [comment]
Hello @Kyle8530 can you help us to find what was the issue ?
We need more details, what were you doing before the crash?

**Comment by Kyle8530** [comment]
> Hello @Kyle8530 can you help us to find what was the issue ?
> We need more details, what were you doing before the crash?

I was working on a shooter game, but when I clicked the tab "new scene" it just froze. Then I didn't know what happened so I spam clicked it more and it crashed.

**Comment by Bouh** [comment]
Thank you for this, it will be a good start for debugging :)

**Comment by 4ian** [comment]
Closing for now as it seems we don't have steps to reproduce this.
