### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Broadlolypop** [4ian/GDevelop#1905]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in j
    in div
    in r
    in div
    in s
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in E
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in K
    in r
    in t
    in Unknown
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in J
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in ee
    in b
```

## Other details
* IDE version: 5.0.0-beta98-b9ba8e1b7b43f7f56f2fb7696742c604e2d8507d
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.13.6,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta98 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Would you be able to explain how to trigger this bug? I could fix it then :) Thanks!

**Comment by Broadlolypop** [comment]
Hello 4ian yes so like I said before I was pixelating a ladder sprite on Gdevelope but right as I clicked save sprite the screen said an error occurred and said to report the problem here

**Comment by 4ian** [comment]
Would you be able to make a short video of this so that I can understand exactly what buttons are pressed?

**Comment by Broadlolypop** [comment]
Well see I don’t have anything to toggle around with on the screen but I can send these pictures if they help

**Comment by Broadlolypop** [comment]
![image](https://user-images.githubusercontent.com/66677293/89131656-c33c7880-d50e-11ea-9c91-d9c531d73621.jpg)

**Comment by Broadlolypop** [comment]
![image](https://user-images.githubusercontent.com/66677293/89131670-dea78380-d50e-11ea-8be2-f9e634c90e13.jpg)

**Comment by Broadlolypop** [comment]
![image](https://user-images.githubusercontent.com/66677293/89131678-f252ea00-d50e-11ea-941e-1b0a4fdadbf0.jpg)

**Comment by 4ian** [comment]
I still don't understand what are the steps to reproduce the crash :) 
Can you write down like it?
1. Click this button called "Create New Project"
2. Click this button
3. Then do this.
4. Then click this button

Thanks!

**Comment by Broadlolypop** [comment]
ok
1. make a sprite 
2. when done click the button at the top right of the sprite editor "save"
3. give this sprite a plaform behavior that will let you go up just like a ladder

(i think what could have caused the crash is that while editing the sprite i was constently resizing the canvas to find the perfect size)

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash, I tested the steps you listed and am not able to reproduce this crash.

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment]
Closed due to no response.
