### ISSUE TITLE
Refactoring the Events Search Bar

### ISSUE THREAD

**Issue by PawBud** [4ian/GDevelop#1909]
So, I was tinkering around with the events editor and noticed that the Events search bar did not have a close button. I am aware that the search bar can be closed by re-clicking the search button, But the search button might be so much easier. 
![Screenshot from 2020-08-04 12-17-55](https://user-images.githubusercontent.com/48093317/89262875-e6ba0d00-d64d-11ea-80e8-543772f79075.png)
The problem is that the search bar in its current state will look much more congested with a close button. I asked on [Discord](https://discordapp.com/channels/258623956158906368/258623956158906368/740098760427962489) and a user suggested that the button can be placed to the immediate left of the arrows.   

Moreover, one can clearly see the difference between the size of the `Search` & `Replace` buttons. This also introduces the inconsistencies between the length of the text field itself. I am aware that [this PR](https://github.com/4ian/GDevelop/issues/1902) might fix this, but it's just something I thought we need to look at.

Lastly, if this is not needed, then I will be happy to close this issue(More of a feature implementation).

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/89286074-dd32a400-d651-11ea-9821-73d02f277825.png)

**Comment by PawBud** [comment]
Nice, @Bouh that's how I imagined it to be. :)
