### ISSUE TITLE
Vibration doesn't work on android package

### ISSUE THREAD

**Issue by Joonel** [4ian/GDevelop#1922]
## Describe the bug
Vibration doesn't work on android app. (but it works via web game, I checked) 

## To Reproduce
I am using usual vibration (not pattern)
Vibration is set as buttons` feedback.

## Other details
checked on Android 10, Pixel 2 XL. last update. & samsung s8 android 9. is not device problem...
last beta98 gdevelop version

**Comment by Joonel** [comment]
this issue is old, it seems that devs won`t fix it...

**Comment by 4ian** [comment]
Can you add a link to the existing issue? 
GDevelop being open-source, we need contributors to help fixing this once it's reported. You can help by putting a bounty on it using a website like bountysource.com

**Comment by Joonel** [comment]
> Can you add a link to the existing issue?

I don't understand what link you're talking about so I put [this one](https://editor.gdevelop-app.com/?project=example://device-vibration)

> GDevelop being open-source, we need contributors to help fixing this once it's reported. You can help by putting a bounty on it using a website like bountysource.com

I pay 2 euros per month & I think issues like this must be fixed for 3 mo. at least...

**Comment by 4ian** [comment]
Unfortunately GDevelop is not getting for now enough funds to hire full time employees that would take care of issues like this. Like any open-source project we rely on contributors and people that can help, and we must prioritize between feature requests/roadmap/bug fix. 

I do think it's important to fix this bug though :) This needs changes to support per extension Cordova plugin though (something that @arthuro555 started a while ago), which means a few days of work at least, so I can't promise anything.

**Comment by arthuro555** [comment]
That PR is still awaiting review btw

**Comment by 4ian** [comment]
Thanks, reviewed! As this seems near completion, I think we can merge this soon and get a fix for this in the next days, and release in the next weeks.

**Comment by 4ian** [comment]
Fixed for next version :)

**Comment by Joonel** [comment]
@4ian thank you!
