### ISSUE TITLE
[$80 Bounty] Add support for RTL languages

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#1924]
GDevelop has some translations for "right to left languages" (such as Persian, Arabic, Urdu, ...), but the layout is blocked in a "left to right" position even when selecting them.
Instead, we should have a parameter for these languages that activates a "Right To Left" ("RTL") layout. This is documented here for material-ui: https://material-ui.com/guides/right-to-left/

It seems that we need to implement an option for languages to be RTL. Then, when activated/selected:
* `dir="rtl"` is added to `body`
* the material-ui theme is set to rtl
* maybe use `jss-rtl` (to be verified)
* verify if there are some components that need manual handling of RTL.

---

This issue is linked to this [Trello card](https://trello.com/c/98dbgQWc/448-add-support-for-rtl-languages-in-gdevelop-layout). A bounty is present on this issue, that is awarded if your make a PR that is merged after code review that properly implements RTL support for GDevelop: https://www.bountysource.com/issues/92320507-bounty-add-support-for-rtl-languages

**Comment by rapperdinesh** [comment]
@4ian I wish to work on this issue.

**Comment by 4ian** [comment]
You can freely start working on this :) (as well as anyone else if someone thinks they can do it!)

**Comment by Bouh** [comment]
Work done:
https://github.com/4ian/GDevelop/pull/1997
https://github.com/4ian/GDevelop/pull/1946
https://github.com/4ian/GDevelop/pull/1945
