### ISSUE TITLE
Web requests freeze scenes

### ISSUE THREAD

**Issue by giusreds** [4ian/GDevelop#1933]
## Describe the bug
When I send a web request, the current scene freezes until the request ends (some seconds).

## To Reproduce
Add a web request action in a scene and test.

https://giusreds.github.io/molise-run

In my game, it appens in the main menu, where I use web request to provide highscores... Test yourself trying the link above...

**Comment by giusreds** [comment]
I found a workaround, sending the xHttp request in a JavaScript block, as asynchronous.

**Comment by 4ian** [comment]
This is a proper workaround, glad you could unblock you :) Next version of GDevelop will have an updated action that is not blocking the game, and storing the result in a variable when done (or in an "error" variable in case of error in the request).
