### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by yidirm** [4ian/GDevelop#1934]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in j
    in div
    in r
    in div
    in s
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in E
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in K
    in r
    in t
    in Unknown
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in J
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in ee
    in b
```

## Other details
* IDE version: 5.0.0-beta98-b9ba8e1b7b43f7f56f2fb7696742c604e2d8507d
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta98 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by yidirm** [comment]
Hi , I think it's a ram problem, but to answer your question I started Spotify then it crashed. but for the moment the problem has disappeared. thank you

**Comment by PawBud** [comment]
@yidirm then shall this issue be closed?

**Comment by yidirm** [comment]
yes, thanks guys @Bouh  @PawBud ( Merci)
