### ISSUE TITLE
External link not loading on Safari (iOS)

### ISSUE THREAD

**Issue by giusreds** [4ian/GDevelop#1943]
## Describe the bug
Links to external URLs present in a game won't load on iOS Safari, loading the HTML exported game. That doesn't happen on Android or on Chrome for iOS.

## To Reproduce
1. Add a *Open file or URL* event
2. Export the game as HTML and host it on a web server
3. Load the game page from Safari on iOS device

Test it on [MY GAME](https://giusreds.github.io/molise-run), clicking the *INFO* button on the main menu.

## Other details
* iOS 13, iPhone 6s & iPhone 11

**Comment by hacknorris-notyetbanned** [comment]
:D i also have problems with iOs, you aren't alone :D it's due to apple, not you ;) (but idk why my game work ;/ on 14.3 and made with older gd version )
