### ISSUE TITLE
Probable issue: NPM dependencies not working in previews

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1947]
## Describe the bug
I didn't test yet but I am 99% sure that npm dependencies wouldn't work in the IDE as it would require having the node module in the newIDE/resources folder to load that module. Runtime should be fine tho as with npm install the dependency is bundled.

## Potential solutions
There are two options: 
1. Bundle npm dependencies with the ide (using some script that auto install the needed deps before building)
2. Detect when an extension with npm deps is used, and download needed deps to some cache if not already present in that cache and load modules from there

1 would make the ide bigger and longer to build, but 2 would make some features require internet connection (to download additional packages)

We could also just not support npm dependencies on the local editor, like on the web editor but it wopuld be a shame and confuse some advanced users that know that previews run on electron too.

**Comment by 4ian** [comment]
Before going further down in the rabbit hole: can you give an example of an hypothetical npm dependency what would cause problem?
Think about what they are used for. :)

**Comment by arthuro555** [comment]
Let's say I have a npm dependency that adds additional platform dependent APIs wrapped for windows mac and linux. Users would expect that as long the game is running in a window the game works (as well in previews as in exported games) but it would only work in exported games, and users would think they did something wrong and not think of trying to export the game.

**Comment by 4ian** [comment]
I understand the problem, but my question was more: do you have a specific example, a real npm package name in mind?

It's definitely sure that everything that works in an exported game should work in a preview - the contrary would be counter intuitive and not user friendly. But I need a real example, because currently this issue seems just an hypothetical problem that we don't have for now :) And we risk over engineering a complex solution, only for something that will never be used or will be used once.

**Comment by arthuro555** [comment]
I was thinking about maybe using fs-extra for the filesystem extension (has a nice copying API), about #1931 , and for integrating greenworks (SteamWorks API node native module bindings)

**Comment by arthuro555** [comment]
I mean the issue is still technically there... But it doesn't impact anything as of now. Should it be closed or not? IDK.

**Comment by 4ian** [comment]
If it does not impact anything, is it still a problem? ;) 
Let's maybe continue the discussion on the discussion related to a specific extension needing this?

**Comment by arthuro555** [comment]
Well there isn't one in particular as of now but if a new contributor wanted to create one that use an npm module they'd be unpleasantly surprised to have this issue.
