### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by fathealrmali** [4ian/GDevelop#1949]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **https://fb.gg/play/2798219297090913**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by fathealrmali** [comment]
![NewObject2-1](https://user-images.githubusercontent.com/69422659/91525125-154f9e80-e901-11ea-9720-96b81250c78f.png)

**Comment by 4ian** [comment]
You must give the project file, not sure an image or a link ;)

**Comment by fathealrmali** [comment]
> You must give the project file, not sure an image or a link ;)

where i can find

**Comment by Wend1go** [comment]
You can just drag and drop the file into the text box here and it will upload it to Github automatically.
