### ISSUE TITLE
Auto-Save backup & Externals-Events

### ISSUE THREAD

**Issue by mxslam** [4ian/GDevelop#1957]
## Description

If you load a backup GD file project all the externals events of the current project will be erased with no possibility to choose/recovery the old externals events.

## Solution suggested

- The main file project must contain all the externals-events or a possibility to recover them.

Or 

- A backup file is needed for the externals events who not depending of the main file project.

**Comment by Silver-Streak** [comment]
I can't reproduce this. I have a project with about 22 external event sheets currently, and all of them remain updated via the autosave.

**Comment by mxslam** [comment]
Im talking about the [fileproject].json.autosave , it contain the main project + all the externals events, so if you open this & saving, all the externals events will be erased even that was not necessary to update them

**Comment by Silver-Streak** [comment]
Still not able to reproduce. 

To be clear: 
I just opened up a project with a ton of external events, updated events on 2 of the external event sheets, ran a preview to generate an autosave, then closed GD5 without saving. 

Opening up the project again, and telling it to open the autosave, shows the external events updated.

Opening up the project.json.autosave file still shows the external events data within the autosave.

**Comment by mxslam** [comment]
1- save your project with modification
2- close and open a old autosave
3- save as the project with a different name
4- check if the modification of the first step will be erased 

Sorry if i'm not very clear, the problem is there no independent backup for the externals events so if you open a old autosave it can update to a very old version of your externals-events with no possibility to recover them.

**Comment by Silver-Streak** [comment]
Hmm...if you open autosave it's going to ignore prior manual saves, that's what it is meant to do.

However, autosaves are also ignored if you've manually saved after the autosave is created. Are you backing up autosaves somewhere and then reloading old ones? I don't think that's their designed usage/goal.

**Comment by Silver-Streak** [comment]
I just did some additional testing:
1. Created a project with the platformer example.
2. Make changes to the EnemyManagement external event.
3. Hard save.
4. Make changes to EnemyManagement external event
5. Run preview.
6. Close project.
7. Open autosave.
8. Save in another folder.
9. Ensure the changes to Enemy management in step 4 were still reflected (they were)
10. Reload the hard save in the original folder. Ensure the changes to Enemy Management in step 2 were reflected (they were)

So I'm either not understanding your problem, or there isn't a problem and the autosave is working as it should.
