### ISSUE TITLE
B99 Web app, resource for the example Light are in "AccessDenied"

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1959]
## Describe the bug
The resources from the [example Light](https://editor.gdevelop-app.com/?project=example://lights) on the web-app are unable to load because the access are "AccessDenied"

## Other details
* B99 
* Web-app

**Comment by 4ian** [comment]
Should be fixed! The latest resources were not deployed it seems, though this should be part of the deploy process for the web-app... anyway, fixed now :)
