### ISSUE TITLE
corova build android

### ISSUE THREAD

**Issue by fathealrmali** [4ian/GDevelop#1968]
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Users\fathe\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=C:\Users\fathe\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: C:\Users\fathe\AppData\Local\Android\Sdk
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jdk1.8.0_261\bin\java.exe -Xmx2048m -Dfile.encoding=windows-1256 -Dus
r.country=SA -Duser.language=ar -Duser.variant -cp C:\Users\fathe\AppData\Local\Android\Sdk\gradle-6.6.1-all\gradle-6.6
1\lib\gradle-launcher-6.6.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.6.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by 4ian** [comment]
For help using Cordova, please ask on the forum or search online - this is not related to GDevelop :)
