### ISSUE TITLE
UX Annoyance: Changing instance variable from default looses focus after first character input

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#1989]
## Description
If you have an object with an instance variable with a default value, when you try to change that value on an instance of that object in the properties panel the field associated with that instance variable will lose focus as soon as you type one character.  This can be really annoying when you are trying to add a string value.

## To Reproduce

- Add any object to a scene
- Right click on the object in the object panel and choose "Edit object variables"
- Add a new variable named "var" with a value of "foo" and click apply
- Drag the object from the panel to the scene to create a new instance
- Open the Properties Panel if not already
- Click on the instance of the object in the scene
- Find "var" in the properties panel
- Double click on the default value "foo" to select the text
- Type "bar"
- The value will now be set to just "b"

... at this point you can now edit "b" to be "bar", but you have to re-click into the field

## Other details
* Windows
* 5.0 b100

**Comment by 4ian** [comment]
Agree that this kind of infuriating! I've fixed it in 16f3a1901d289b7740a88e4734674738b821a1b4, will be in the next version :) 
Thanks for the very clear report
