### ISSUE TITLE
Tiled sprites offset my 1 pixel

### ISSUE THREAD

**Issue by Sapper-Morton** [4ian/GDevelop#1993]
Tiled sprites seem offset by 1 pixel from top and left. The effect is best seen when placed with normal sprites, like landscape. See screenshot below.

![capture_001_19092020_125851](https://user-images.githubusercontent.com/23439320/93676229-d9999600-fab4-11ea-8f17-d5aa5a3067de.jpg)

## To Reproduce
1. Create tiled sprite with normal sprites and place them on game area.

## Other details
Windows 10 GDevelop 5.0.0 Beta 100

**Comment by Bouh** [comment]
It really helps us to debug with an example.
Can you provide an simple project ?

This is tiled sprite or 9 patch ? because isn't the same object.

**Comment by Sapper-Morton** [comment]
I made a simple scene demonstrating the error. The land blocks at the bottom are built with sprites and tiled sprites. The black block in the sky is just sprites. There's no strange behaviour between plain sprites, just tiled ones.
[TileTest.zip](https://github.com/4ian/GDevelop/files/5250530/TileTest.zip)

**Comment by Bouh** [comment]
You have not enabled the pixel perfect mode in game settings, and all your assets are smoothed, that's why the texture bleed on the edges.

Project manager > Game settings > Properties > Scale mode
and
Project manager > Resources > Find your assets un uncheck the Smooth case.


![image](https://user-images.githubusercontent.com/1670670/93689434-c85d8300-face-11ea-8f85-022639f1c179.png)

**Comment by Bouh** [comment]
Note in the the scale mode as an effect only in exports and preview, it's not visible in editor.

Btw this is something to do in the engine. It's should be easy to implement. If someone want take a look!
//TODO

**Comment by Sapper-Morton** [comment]
Thanks. It was weird because this appeared in beta100. I previously used beta98 and it didn't have the same problem.

**Comment by Bouh** [comment]
https://github.com/pixijs/pixi.js/issues/7166

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
