### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by StevicNinja** [4ian/GDevelop#1996]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in a
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in s
    in n
    in t
    in n
    in Unknown
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta100-23d64aa676eaf789ce31d5176b23f212f3b8031d
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.14.6,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta100 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
hi @StevicNinja 
Can you tell us under what circumstances this crash occurred?
We would need more information to be able to identify this error.

**Comment by StevicNinja** [comment]
I’m really sorry guys...The error just appeared when I was doing a whole bunch of stuff. I cannot quite remember the specifics. 

The ooold Sent from my iShoePhone trick!
