### ISSUE TITLE
Graphical glitch when resizing the objects editor

### ISSUE THREAD

**Issue by TheGemDev** [4ian/GDevelop#1999]
## Describe the bug
please follow the steps to reproduce this :)

## To Reproduce
1. Go to the objects editor and make sure you have enough objects to make you scroll. 
2. then open the layers editor.
3. scroll down in the objects editor till you can see the add new object button.
4. then close the layers editor after this you should see some blank spaces above. (check the image below) this would only go away once you close and reopen the objects editor.

## Other details
![ddddddddd](https://user-images.githubusercontent.com/53819287/94337274-362f1080-ffe1-11ea-80da-720fdfa5a5ef.PNG)

**Comment by Bouh** [comment]
Confirmed
![fail_list_refresh](https://user-images.githubusercontent.com/1670670/94374851-80aeab00-010f-11eb-87c4-c04304533781.gif)

**Comment by VolDemorT-acer** [comment]
The display of the objects is handled by a List component of third party library "react-virtualized" ,now I am just confused if we can fix this .I will try with a dummy list using "react-virtaulised" package in codesandox or locally ,to check if the issuse still persists when we change the height of list.If the issue still remains ,there's nothing much to be done .

ps : I am new to opensource;And this is repo is huge so I may have missed something

**Comment by HarsimranVirk** [comment]
It could be a react-virtualized issue, [https://github.com/bvaughn/react-virtualized/issues/1533](), seems pretty similar to what we have at GDevelop 🤔.

**Comment by dkapur17** [comment]
@TheGemDev @4ian I have come up with a pretty straightforward solution for this, but uses `document.querySelector` to fetch some information from the DOM. If that's not an issue then I can open a Pull Request for this.

**Comment by dkapur17** [comment]
@TheGemDev @4ian I have come up with a work around for this. Though it uses `react-dom` to fetch some information directly from the DOM. If that isn't an issue then I'll open a PR with the changes.

**Comment by 4ian** [comment]
Open the PR and we'll see directly in the code :)

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by Silver-Streak** [comment]
This appears to have been resolved quite some time ago, and i can no longer reproduce it with the steps above. Closing out, but feel free to reopen if someone is still experiencing this on 5.1.157 or newer.
