### ISSUE TITLE
Show the descriptions of expressions are in the expressions selector.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2003]
## Description
Currently the description of expressions are not visible in the editor, except in the description field in the extensions and when we have the focus on the current expression already typed in an expression field.
These descriptions are useless because no one can read them before write them.

![image](https://user-images.githubusercontent.com/1670670/94829248-9d4a2c00-040a-11eb-866d-a951a3205076.png)
![image](https://user-images.githubusercontent.com/1670670/94829378-beab1800-040a-11eb-903e-3caba224a75d.png)
![image](https://user-images.githubusercontent.com/1670670/94829391-c4086280-040a-11eb-9c10-94ba9fd0b5e3.png)

## Solution suggested
I suggest to show the description of an expression in the expression selector and in the properties of expressions.

![image](https://user-images.githubusercontent.com/1670670/94829739-219caf00-040b-11eb-9bab-f80b3df240ae.png)
![image](https://user-images.githubusercontent.com/1670670/94829993-64f71d80-040b-11eb-8b71-fed5139159ff.png)
![image](https://user-images.githubusercontent.com/1670670/94830150-8eb04480-040b-11eb-98ce-d4a6a173b183.png)

**Comment by 4ian** [comment]
Sounds like a good idea indeed!
