### ISSUE TITLE
Adding more components

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2008]
The gdevelop Needs more components and features to show its real power and i see that the components are not geeting updated that much 

for example 

look at this
![Screenshot (252)](https://user-images.githubusercontent.com/59413955/95015135-1a73dc00-066b-11eb-918b-bfb58a31808c.png)
![Screenshot (246)](https://user-images.githubusercontent.com/59413955/95015139-1f389000-066b-11eb-8002-8868a0e21679.png)

![Screenshot (249)](https://user-images.githubus
![Screenshot (251)](https://user-images.githubusercontent.com/59413955/95015131-16e05500-066b-11eb-80d7-b95c3b0fc3bb.png)
ercontent.com/59413955/95015129-12b43780-066b-11eb-82db-c4fc08719a37.png)

![Screenshot (247)](https://user-images.githubus
![Screenshot (250)](https://user-images.githubusercontent.com/59413955/95015130-13e56480-066b-11eb-92c4-18a4ab430311.png)
ercontent.com/59413955/95015126-0def8380-066b-11eb-8ce6-ae3f4bca619e.png)
![Screenshot (248)](https://user-images.githubusercontent.com/59413955/95015128-11830a80-066b-11eb-8e2c-b0b0b375cb8e.png)

But when i look The gdevelop its like this:

![Screenshot (254)](https://user-images.githubusercontent.com/59413955/95015200-6757b280-066b-11eb-8dca-371488126f37.png)
![Screenshot (253)](https://user-images.githubusercontent.com/59413955/95015201-69217600-066b-11eb-92ea-0b8d6ca002a7.png)

Its just basic stuffs but to make the engine more power full these things should be added:

1. IFRAME component for making ides or ingame web browser
2. A canvas ye that html canvas to make a drawing softwares
3. Multiplayer in-build no need for a nodeJS server
4. File chooser or somthing like that
4. NW.js support
5. Adding UI components like slider,Buttons,Lists,progressbar,and microphone and camera access.

These are the things which everyone wants and no engine even unity or unreal have provided it.To do it we should do from scratch or tell someone to do it for high money so please add them.

**Comment by 4ian** [comment]
GitHub is for technical discussions - please first go on the forum to discuss this and vote on the existing card on the roadmap: https://trello.com/b/qf0lM7k8/gdevelop-roadmap

Please also get more familiar with GDevelop :) NW.js is not needed because we use another solution.
Most "components" in GDevelop are not in objects too but are available as actions/conditions without the need for an object.

Thanks!

**Comment by Bibekz-dev** [comment]
but we need iframes and canvassssssssssssssssssssssssssssssss????????????????

**Comment by PawBud** [comment]
@Bibekz-dev https://github.com/4ian/GDevelop/issues/2005#issuecomment-703457724 same can be applied here
