### ISSUE TITLE
Gdevelop webapp native api file system access

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#2014]
It was just announced that chrome now supports granting access to writing to opened files 
https://www.youtube.com/watch?v=GNuG-5m4Ud0

This can potentially open the possibility to use gdevelop's webapp and PWA to open and writeto projects on the operating system.

Perhaps something to consider for the trello board?

As a side note some goodies got in for native joypad support too

**Comment by 4ian** [comment]
Ah it's finally out! Very interesting :) 
I've made a card here: https://trello.com/c/MEAeScbO/457-use-the-native-filesystem-api-chrome-86-to-allow-opening-saving-locally-a-project-from-the-web-app

Closing this now but if anyone wants to try something with this, the storage implementations are here: https://github.com/4ian/GDevelop/tree/master/newIDE/app/src/ProjectsStorage

Note that it's not a super easy task, there are potentially adaptations needed to existing code to see how to integrate things.

**Comment by 4ian** [comment]
Closing as card added on the roadmap.
