### ISSUE TITLE
New Example | Darknate Room Test

### ISSUE THREAD

**Issue by HackLinTemp** [4ian/GDevelop#2023]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: http://www.mediafire.com/folder/bth5jr7ogc36c/Darknate+Room+Test

  I confirm that any assets can be used freely by anybody, including for commercial usage.
  
![android-icon-96](https://user-images.githubusercontent.com/70800682/95684312-098a1400-0bf1-11eb-92d5-bf749762ca21.png)
This is Darknate

**Comment by HackLinTemp** [comment]
Enjoy :)

**Comment by Midhil457** [comment]
Hi, @HackLinTemp. Sorry for the late reply. Can you describe what your example is about? and also how it works? Thanks!

**Comment by 4ian** [comment]
This is quite old too, I'm closing the issue and a new one can be re-opened later if needed :)
