### ISSUE TITLE
Add CORATA [Open Source and free canvas engine]

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2028]
Its afully functionable text engine really neat and clean and is in Canvas https://github.com/danielearwicker/carota 
Look at the example and you can also inspect it and see its purely canvas if u add this your requests will be completed and it will also help others a lot better then text input. Github is at http://github.com/danielearwicker/carota

**Comment by 4ian** [comment]
Please discuss first on the forum or on the roadmap before opening GitHub issues, these issues are only for technical discussions :) Thanks!
