### ISSUE TITLE
not saving save file

### ISSUE THREAD

**Issue by imagineeeinc** [4ian/GDevelop#2029]
## Not saving save file

when I save on windows it doesn't save the .json file, but when I save as it does
## To Reproduce
1. click ctrl + s
or
1. click file
2. click save

## Other details
* Windows 10 version 2004
* GDevelop 5.0 beta 100

**Comment by 4ian** [comment]
I think the save is working well, nobody else had any issue. At least when I'm testing on Windows it works well. Do you have any error message showing?

**Comment by Bibekz-dev** [comment]
nope never happened to me

maybe delete it or restart pc and try again

**Comment by 4ian** [comment]
I'll close this, please check first on the forum and post if you have the exact conditions that allow to reproduce a bug, with screenshots. Thanks!
