### ISSUE TITLE
Event Sheet doesn't rerender on resize

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2030]
## Describe the bug
The events don't rerender on window size change until some other rerender event happens (like a click):   
![2020-10-14 18-12-57](https://user-images.githubusercontent.com/19349038/96016672-4d775600-0e49-11eb-8d5e-d6b2628d6e5d.gif)

## To Reproduce
1. Go on the event sheet
2. Resize the window
3. Click an event to see the UI refreshing

## Intended behavior
The UI should rerender as soon as the window is resized.

## Other details
* GDevelop beta 100 release local editor
* Windows 10

**Comment by 4ian** [comment]
The reason behind this is that the `ResponsiveWindowMeasurer` component used to measure the window size is not listening for resize of the window. We could add this - forcing a re-render when it's detected - but it would be good to ensure this does not affect performance (throttling?).
