### ISSUE TITLE
The increase in unnecessary size

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2032]
When i export the game to any platform it export unnecessry things with it like for example i have an white box and a 4 pixel long ground where the box have a MovementBehaviour and if i export the game its size will be 40 mb or above it will also have unnecessary modules and extentions and also all data from the game,etc whiuch are not needed.

Please help, i expect this game size to only be 1mb or less.

**Comment by Bouh** [comment]
Hello you can find help about that by asking your questions to users on the forum.
Quick anwser, all assets in resources tab will be included in the game.
Same for the extensions if an object in the object list use the shape painter for example, the extension shape painter will be included.
If you want reduce the size of the exported game clean your assets.
