### ISSUE TITLE
Texture in Light Object bug

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2048]
## Describe the bug
In the beta 101, an texture cannot be render in the light object even with webgl 2 and 1.
The last [PR 1979](https://github.com/4ian/GDevelop/pull/1979) on Light have introduce this bug.

Here a white square as texture light:
On beta 100, result expected:
![image](https://user-images.githubusercontent.com/1670670/96476827-079a0380-1236-11eb-903f-68fb4d719f52.png)

On beta 101, bugged:
![image](https://user-images.githubusercontent.com/1670670/96476877-18e31000-1236-11eb-9dc8-1d8b5a09a2f0.png)

[Test_Light_project.zip](https://github.com/4ian/GDevelop/files/5403183/Test_Light_project.zip)

## Other details
b101 only

@HarsimranVirk @4ian

**Comment by HarsimranVirk** [comment]
@Bouh does it render any texture at all? I feel like we've broken the texture rendering somehow, either way I'll look at it :+1:

**Comment by Bouh** [comment]
No image works.

**Comment by 4ian** [comment]
Let me know @HarsimranVirk if you can debug this/need help - probably a mistake that caused a regression. We also have an issue of some shader issues on iOS/some Android mobile devices, I'll also try to help on this maybe we're using something not supported by some GPUs.

**Comment by Bouh** [comment]
If the renderTexture from the layer is missing the rest of the code bug. Even with the return:

```JS
gdjs.LayerPixiRenderer.prototype._updateRenderTexture = function () {
  if (!this._pixiRenderer) return;

```

![image](https://user-images.githubusercontent.com/1670670/97110991-7d8de700-16dc-11eb-9189-391f8001d9dc.png)

**Comment by HarsimranVirk** [comment]
> If the renderTexture from the layer is missing the rest of the code bug. Even with the return:

Seems pretty weird to me, renderTexture can't be `undefined` (although it can always be `null`, since that's the default framebuffer).

> Bug report by an user, not reproductible...

True, I couldn't reproduce, might be something very specific to pixi I guess.
