### ISSUE TITLE
Zooming is interpreted as double click on touchscreens.

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2050]
## Describe the bug
On touchscreens, zooming is considered as double clicking, and opens the object properties panel after the zooming is over.

## To Reproduce
1. Open a project on a smartphone, for example the game feel design
2. Select an instance on the scene
3. Click once on the selected instance: as expected nothing happens.
4. Double click on the selected instance: as expected, the object data opens
5. Now zoom in or out. It will behave as if you had double clicked on the selected instance, which is not expected.

## Other details
* Android 8, Redmi 5
* Web app, beta 101
* Brave browser build 1.15.72, based on Chromium 86.

**Comment by 4ian** [comment]
Just to clarify, by zooming you mean the "pinch to zoom" with 2 fingers? It's possible that it's also triggering a click, surely something to cancel to avoid considering it as a click or a long press!

**Comment by arthuro555** [comment]
>  by zooming you mean the "pinch to zoom" with 2 fingers?

Yes, exactly.

**Comment by 4ian** [comment]
Ok found the culprit, PixiDoubleClickEvent.js is too naive and will consider two separate touch events ending as two taps, so a double click. I'll see to fix that :)

**Comment by 4ian** [comment]
Fixed in e7bc5e866522c04dba5c83ab82f234b569c8ae67 :)
