### ISSUE TITLE
use Multiple canvas as scenes

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2064]
canvas is the main thing in gdevelop but there ius only one canvas and thousands of  scenes using it and the canvas stores multiple data at once which brings problems Like :
Deselect as a global object
Data overflow and effects and lightning bugs

So i know it increases the size and memory usuage a bit, but please try to add this feature

**Comment by 4ian** [comment]
Please first discuss features on the forum or suggest them on the roadmap :) 
The problem you mention are not related to this.
