### ISSUE TITLE
Platformer - With Controller Support

### ISSUE THREAD

**Issue by Official-IceCreeperPE** [4ian/GDevelop#2065]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Official-IceCreeperPE** [comment]
pls open i added example

**Comment by Wend1go** [comment]
Your zip seems to only contain the images. Couldn't find a project file.
