### ISSUE TITLE
Does not start scene preview (Não inicia visualização de cena)

### ISSUE THREAD

**Issue by WillyFerreir** [4ian/GDevelop#2066]
Não inicia visualização de cena

Estou a 1 mês criando um jogo para dispositivo móvel!
Ontem eu fui iniciar a visualização de cena e apenas ficou carregando até crashar
Tentei exportar o jogo, a Gdevelop travou, fiquei tentando mas não consegui 
Criei um novo arquivo e tudo funcionou normal, mas no arquivo do meu jogo tenho esse problema 

Estou um pouco triste pôs ontem eu ia 
terminar meu jogo. Por favor me ajudem :(

já criei outros jogos pra móvel com a Gdevelop e nunca tive esse problema.

Sistema operacional: Windows 10 
Uso aplicativo Desktop 
Versão: Gdevelop 5.0.0-beta99 baseado no Gdevelop.js 4.0.98-0-release

![Captura de Tela (4)](https://user-images.githubusercontent.com/73534677/97304646-c8be0c00-183a-11eb-933b-8eae908d24fe.png)
 
Does not start scene preview

I am creating a mobile game for 1 month!
Yesterday I went to start the scene visualization and just kept loading it until it crashed
I tried to export the game, Gdevelop crashed, I tried but I couldn't
I created a new file and everything worked fine, but in my game file I have this problem

I'm a little sad put yesterday I was going
finish my game. Please help me :(

I've already created other mobile games with Gdevelop and I never had this problem.

**Comment by 4ian** [comment]
Can you send me your project folder zipped to my email address? You can find it on http://github.com/4ian - I'll then take a look at what is wrong. Thanks!

**Comment by 4ian** [comment]
In rope3 scene you have a link to rope3 scene. So it creates an infinite loop in GDevelop, making it crash.
To fix that, be sure to not include events from the same scene, and do not create loops like this.

![image](https://user-images.githubusercontent.com/1280130/97550788-0309e380-19ca-11eb-99d0-f421d370e6f4.png)

Also be sure to verify other scenes too! I just checked scene "rope3".
You may want to consider using link to avoid repeating the same events in all scenes (but be careful with them ;)).

I'll try to make a bugfix to avoid crashing GDevelop in these cases.

**Comment by WillyFerreir** [comment]
Thank you!

I was very grateful, may God bless you
You helped me a lot!
All the best for u.

Enviado do Email para Windows 10

De: Florian Rival
Enviado:quinta-feira, 29 de outubro de 2020 06:36
Para: 4ian/GDevelop
Cc:WillyFerreir; Author
Assunto: Re: [4ian/GDevelop] Does not start scene preview (Não inicia visualização de cena) (#2066)

In rope3 scene you have a link to rope3 scene. So it creates an infinite loop in GDevelop, making it crash.
To fix that, be sure to not include events from the same scene, and do not create loops like this.

Also be sure to verify other scenes too! I just checked scene "rope3".
You may want to consider using link to avoid repeating the same events in all scenes (but be careful with them ;)).
I'll try to make a bugfix to avoid crashing GDevelop in these cases.
