### ISSUE TITLE
EXAMPLE TO LIGHTS

### ISSUE THREAD

**Issue by felipe0307811** [4ian/GDevelop#2067]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: https://games.gdevelop-app.com/game-259a0906-a335-4a00-af81-97b6c17f6764/index.html.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by 4ian** [comment]
You need to share the sources, not the exported game.

**Comment by Bouh** [comment]
This is the light example with other colors.
Not very interesting.
