### ISSUE TITLE
Iframes in gdevelop

### ISSUE THREAD

**Issue by Bibekz-dev** [4ian/GDevelop#2070]
please please i discuseed it i will die waiting for it please sir 4iann add it pleaseeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEeeeeeeeeeeeeeeeeee

**Comment by 4ian** [comment]
Please @Bibekz-dev stop spamming Github with this. We're here for technical discussions, and we develop new features when enough people are asking for them. Your demand here is both not explained at all and not asked by the rest of the community. This can evolve, but only if there is a high demand from users.

As a side note, I'm **not happy at all** with this kind of message. I'll lock the conversation and hope you won't do that ever again. Thanks.

**Comment by Bibekz-dev** [comment]
mk :(
