### ISSUE TITLE
Collision between sprites of certain measures are not detected 

### ISSUE THREAD

**Issue by frikiloko** [4ian/GDevelop#2074]
## Describe the bug
Hello, the collision doesn’t work between a sprite of 64x64 pixels and another sprite of 192x192 pixels. It’s a diagonal collision with default system (detecting borders). If we put the sprites brushing diagonally as in the image the collision is not detected, maybe this is the intended behavior but this is only happens between a sprite of 64x64 and another of 192x192, in whatever other size just 64x64 and 192x193 for example the colision is detected, or placing the sprites in the borders but no diagonally.

https://forum.gdevelop-app.com/uploads/default/original/2X/8/82561a1ebed111bd567526f2023e53b9754328d8.png

## To Reproduce
Download the project attached or make this:
Just place the sprites 64x64 and 192x192 in a diagonal colision just like the picture:
https://forum.gdevelop-app.com/uploads/default/original/2X/8/82561a1ebed111bd567526f2023e53b9754328d8.png
Make a colision event with borders activated between them
Put any action if the event is true like destroy sprite
Run the game and check if the collision works (it doesn't work) 

* Please include a link to a game if possible!
http://www.mediafire.com/file/dod3qku1y09ad6f/My_project4.rar/file

## Other details
 GDevelop version 5.0.0-beta101
Windows 10.

**Comment by Bouh** [comment]
Something that was not completely ported from GD4 from C++ to Javascript because the collision system has been rewritten.
I can reproduce and confirm this is issue.

If someone is ready to fight with the collision system feel free to inform you on it before give a try for fix it.

**Comment by 4ian** [comment]
This might be some rounding issues somewhere in the Polygon/collision handling code :)

**Comment by frikiloko** [comment]
I know another similar bug, I post it in another thread.
