### ISSUE TITLE
IDE complains about an asset not being in the project folder if it is in a subfolder

### ISSUE THREAD

**Issue by nailuj29gaming** [4ian/GDevelop#2076]
## Describe the bug
When trying to use a sprite that is in a subfolder of the project folder, the IDE tells me that the selected file is outside the project folder, and suggests I make a copy of it in the project folder.

## To Reproduce
1. Open any project
2. Create a folder with an image in it inside the project folder
3. Create a sprite and select that image for an animation

## Other details
* Windows 10 64 bit version 2004 build 19041.572
* Desktop IDE

**Comment by 4ian** [comment]
I can't reproduce this, are you sure about it? Creating a subfolder with an image and selecting it works ok for me without extra warnings.

**Comment by Bouh** [comment]
Unable to reproduce too on Windows 10, desktop IDE.

**Comment by nailuj29gaming** [comment]
@4ian I am using a non default project directory, and unzipped the images from a tutorial while the IDE was running. If you want, I can provide a screencast.

**Comment by 4ian** [comment]
A screencast would be very useful. Please also include screenshots of the
folders in the windows explorer/finder :)

**Comment by nailuj29gaming** [comment]
@4ian I could not recreate this when I tried to do a screencast.
