### ISSUE TITLE
WindowTitle() Expression returns undefined and stops previews from loading

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2077]
## Describe the bug
Another user had asked about comparing the current Window Title. After some testing, it appears the WindowTitle() expression is not functioning at all as a string or integer. 
Using it in an event leads to previews not loading (full black screen, no loading screen).

## To Reproduce
1. Add a text object "Text" to the scene.
2. Add a new event.
3. Add the action to Change the Text of "Text": set to WindowTitle()
![image](https://user-images.githubusercontent.com/24237149/97995200-d419b600-1dab-11eb-94bb-053f06ba4922.png)
4. Run the preview, it will not load.
5. You can also try setting a string variable to WindowTitle() instead of the above event. The preview will load, but the variable returns Undefined.
Console debugger shows some errors around not being able to find length of the text object. 
![image](https://user-images.githubusercontent.com/24237149/97995291-f1e71b00-1dab-11eb-9e49-0365eb8e7005.png)

## Other details
* Windows 10 Pro
* GD5 Beta 101. I've tested both the desktop and browser version.
* Example Project attached below.
[My project3.zip](https://github.com/4ian/GDevelop/files/5481699/My.project3.zip)

**Comment by 4ian** [comment]
There is indeed a missing return in https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/events-tools/windowtools.js - should be easy to fix

**Comment by 4ian** [comment]
Fixed in bc56f820b3babf5d50cfdefbcbda1d30b914c161, thanks for reporting!
