### ISSUE TITLE
P2P Game Template

### ISSUE THREAD

**Issue by tomekk2006** [4ian/GDevelop#2084]
[Multiplayer Template.zip](https://github.com/4ian/GDevelop/files/5520642/Multiplayer.Template.zip)
Use this template to create your own multiplayer game.

**Comment by arthuro555** [comment]
After opening, the first thing I see is an event with a beginning of the scene condition and no action. I'd recommend you clean up your project file, it's meant to be an example and should therefore be something polished ;)

**Comment by Bouh** [comment]
Close there is now a [P2P Networking Example](https://editor.gdevelop-app.com/?project=example://p2p-networking)
With clean events.
