### ISSUE TITLE
Dark themes: Event handles barely visible

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#2086]
## Describe the bug
The handle to hide sub events is barely visible in the Nord theme.
![image](https://user-images.githubusercontent.com/7413059/98784695-c98a9c80-23fb-11eb-8ed2-b5ee303a7ba7.png)
(See the handle left of "UI Handling")

**Comment by Wend1go** [comment]
Same for all dark themes

**Comment by Manas502** [comment]
Can I take up the issue?

**Comment by 4ian** [comment]
Sure feel free to go ahead!

**Comment by Manas502** [comment]
Hey @4ian can you guide me a little on where I can find Nord theme styles?

**Comment by 4ian** [comment]
https://github.com/4ian/GDevelop/tree/master/newIDE/app/src/UI/Theme/NordTheme

Though in this case, use the debugger to identify where/how is rendered the arrow, and then check how you could style it.
See
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/EventsTree/style.css and 
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/UI/Theme/Global/EventsSheet.css

**Comment by Silver-Streak** [comment]
Looks like this was fixed a while back.
![image](https://user-images.githubusercontent.com/24237149/216802962-8e0f21b9-998a-486b-b765-5f0b68659005.png)
