### ISSUE TITLE
Sprite opacity is affected by culling.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2087]
## Describe the bug
The opacity of a sprite offscreen are is not updated because the culling is active then the visible attribute of pixi is set to false.
This affect the instances, the opacity stay to 0 when the sprite is in the bound of the camera.

## To Reproduce
Use this projet:  [game.json.zip](https://github.com/4ian/GDevelop/files/5525076/game.json.zip)

1) Use up and down keys for see the instances.
2) Press spacebar and see one instance set to opacity 50.
3) Use the up or down key for see the other instance.
4) **Problem is here, the instance is invisible.**
5) Press spacebar again, the instance use now opacity 50.
6) Go back to step 3

[Initial bug report on the forum.](https://forum.gdevelop-app.com/t/transparency-range-objects-not-loading-correctly/28609)

## Other details
Tested on b98, b101

**Comment by 4ian** [comment]
Thanks for reporting and for the example game! Should be fixed now, by removing an old, buggy workaround :) (was partially done in a previous PR)

**Comment by PascalLadalle** [comment]
Similar issue, perhaps related?
https://forum.gdevelop-app.com/t/tiled-sprite-problem/28920/9

**Comment by 4ian** [comment]
Not related to opacity, but indeed surely a culling problem. Might be worth opening a different issue with your reproduction case :)
