### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Alessi0777** [4ian/GDevelop#2091]
=> It happened five minutes ago, it was a sudden... please HELP! i've passed the last 2 hours, i dont want to close the program and lose anything... S.O.S

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in a
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in h
    in h
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta101-f0392cfede2c8b68b2c9d652001d999eac819299
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19041,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta101 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash?

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment]
Closed due to no response and no steps to reproduce the issue.
