### ISSUE TITLE
Stop billing me please

### ISSUE THREAD

**Issue by noxidsoft** [4ian/GDevelop#2095]
There is no place to stop my subscription on the website. I thought closing my wiki account would halt it, but not sure if that worked. I could find no other place to ask this. 

@4ian please check username: noel.dixon_noxidsoft.com

Please halt/cancel my subscription.

**Comment by 4ian** [comment]
You can do it the exact same way where you originally subscribed :) 
Go to your profile in GDevelop and choose the free subscription. See the screenshots at the end of this page: http://wiki.compilgames.net/doku.php/gdevelop5/interface/profile

Thanks!

**Comment by noxidsoft** [comment]
Just a note, I said I closed my account already. There was no "free subscription" option in my account profile that I could see, you need to check what people are actually looking at. I'll come back to this thread if you charge me again, and I'll probably have to call my bank to block your charges.

**Comment by 4ian** [comment]
> I said I closed my account already.

You closed your wiki account, that's not your GDevelop account. Did you look at the page that I linked?
You have to go in GDevelop, then in your profile, then choose the free subscription, like explained here:

![image](https://user-images.githubusercontent.com/1280130/99229588-20221d00-27e6-11eb-9557-b762408c197e.png)

I went ahead and cancelled your subscription by myself, but I would really like to understand if there was an issue in the explanations written on the page I sent you.

**Comment by noxidsoft** [comment]
Yes, this was the link / profile I was talking about:
http://wiki.compilgames.net/doku.php/gdevelop5/interface/profile

There was no such option as per your image above available to me.
Thank you for closing it for me, much appreciated.
