### ISSUE TITLE
ObjectVarToJSON does not work as expected

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2097]
## Describe the bug
Calling ObjectVarToJSON does not seem to return a stringified JSON blob at all.

## To Reproduce
Attached [objectvartojson-bug.zip](https://github.com/4ian/GDevelop/files/5543385/objectvartojson-bug.zip)
1. Created a text object for Global, Scene, and Object demonstration
2. Defined a Structure name "DoubleArrayOfInt" in Global variables, Scene variables, and on the "Object" object
3. I used the copy function to ensure the structure definition was the same in all three places
4. The scene logic replaces the text for each object with it's corresponding call to the three ToJSON methods
5. Global and Scene look as expected, Object just get a value of "0"
![objectvartojson-bug](https://user-images.githubusercontent.com/251967/99200986-4b692580-276e-11eb-8735-162d8838f020.jpg)

## Other details
* Windows
* GDevelop 5.0 b101

**Comment by krunkster** [comment]
I created the following extension to work around the issue:
`const object = eventsFunctionContext.getObjects("Object");
const varName = eventsFunctionContext.getArgument("Variable");
let json = "{}";

if (object.length != 1) {
    console.log("Warning: Recieved more than one object reference!");
}

try {
    let variable = object[0].getVariables().get(varName);
    json = gdjs.evtTools.network.variableStructureToJSON(variable);
} catch (ex) {
    console.log("Error in ObjectVarToJSON: " + ex);
}

eventsFunctionContext.returnValue = json;`

This works exactly as I expected the built-in expression to work.

**Comment by 4ian** [comment]
Good catch, this is indeed not working as intended! I'm looking now.

**Comment by 4ian** [comment]
Fixed for next version :) Your workaround seems to be fine in the meantime.
Thanks a lot for the attached project, was very useful to quickly reproduce and fix this.
