### ISSUE TITLE
Manual Compile Admob Not Working Anymore

### ISSUE THREAD

**Issue by Cromarko** [4ian/GDevelop#2110]
I am trying to update my current apps on the app store but ads are not showing up with manual compile anymore. Android export with Gdevelop shows ads; my code implementation is correct. My live games on the App store already do show ads.

I am trying to make updates to my games but new .apk and .ipa don’t show ads through manual implementation.

I used the following:

Compile through Phonegap
Compile through MacOS Cordova then export through XCode
Compile through Windows Cordova command line
My ads always showed up in Phonegap builds but not anymore. Are there any new steps in Gdevelop, config.xml I am missing?

**Comment by 4ian** [comment]
Can you precise:
- if the problem is on Android or iOS?
- What are the error messages, if any, for XCode?

**Comment by arthuro555** [comment]
I am pretty sure I saw someone say on the forum that the old AdMob plugin we use UIWebView, that might be the cause of the problem.

**Comment by 4ian** [comment]
Correct, we need to update this for iOS.

**Comment by TheGemDev** [comment]
> Correct, we need to update this for iOS.

i found this 
https://github.com/admob-plus/admob-plus
It's the successor of cordova-plugin-admob-free, which is currently used by gdevelop. which provides a cleaner API and build with modern tools.

**Comment by 4ian** [comment]
@TheGemDev yes we'll need to switch to this plugin, it seems the best solution available.

**Comment by TheGemDev** [comment]
> @TheGemDev yes we'll need to switch to this plugin, it seems the best solution available.

I would try to work on it :)

**Comment by 4ian** [comment]
Feel free to give it a try! I think it might work a bit differently for showing ads (no need to preload?) and setting the admod ids.
