### ISSUE TITLE
Text cursor position in the events sheet

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2111]
When clicking on a field to edit it, the position of the text cursor is not consistent in all fields:
- Value/Text: left of the text. (with some exceptions, like tween easings)
![image](https://user-images.githubusercontent.com/25978830/100133535-30da2f00-2e87-11eb-9ce7-6842f096ec19.png)

- Name (object, variable, etc): right of the text. 
![image](https://user-images.githubusercontent.com/25978830/100133599-43546880-2e87-11eb-9a8f-9738c7914d72.png)

Names (and easings) are available through dropdown menus, so it might be related to that? Either way, I think it should be consistent.
Ideally, I would like the content of fields to be always highlighted when I click on the field. That way, whatever I want to do, I only need one keypress: left to go to the beginning, right to go to the end, backspace to erase (and access the dropdowns), or simply write the new name/text/value.

GD5b101

**Comment by chauhanprakhar** [comment]
I would like to work on this issue but I need some help with this because I am new to this organization.

**Comment by PascalLadalle** [comment]
@chauhanprakhar Please be more specific about what help you need.
Feel free to join us on the Discord, on the #engine-development channel.
And make sure to read this page: https://github.com/4ian/GDevelop/blob/master/newIDE/README.md
