### ISSUE TITLE
Interface - Toolbar - Add assigned keyboard shortcut for actions

### ISSUE THREAD

**Issue by e1e5en-gd** [4ian/GDevelop#2115]
## Description
Add an assigned keyboard shortcut to tooltips for buttons in parentheses.
Example:
![image](https://user-images.githubusercontent.com/7114353/100475319-da255d00-30f3-11eb-8da4-b67b42a58713.png)

**Comment by arthuro555** [comment]
Please put your feature requests on the [forum](https://forum.gdevelop-app.com/c/gdevelop-general/feature-requests) 😉

**Comment by e1e5en-gd** [comment]
Done - [topic](https://forum.gdevelop-app.com/t/interface-toolbar-add-assigned-keyboard-shortcut-for-actions/28967).
Close request?

**Comment by Bouh** [comment]
[This feature was added to the Trello board.](https://trello.com/c/spxx5qqO/478-display-the-shortcut-in-tooltips-of-buttons)
