### ISSUE TITLE
Tetris

### ISSUE THREAD

**Issue by san-codequest** [4ian/GDevelop#2117]
Hi!

This example is a Tetris with an animation of falling blocks. Almost all concepts of modern Tetris such as SRS (Super Rotation System) or ghost piece are implemented in 99.9% Visual Script :)
[Tetris_201201.zip](https://github.com/4ian/GDevelop/files/5617150/Tetris_201201.zip)

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by 4ian** [comment]
Wow, very impressive @san-codequest !
Really impressed with how complete the game is, and the great attention to details, various comments, extensions and logic you've been implementing 👍 
Love the music too 😄

Looking at the game it's ~9mb compressed, most of it which should be the mp3 which is 8.9mb uncompressed. I'll see if I can make a version with a slighlty worse encoding to make it smaller.

Apart from that I guess we can directly add this as an example. I've seen you made a few extensions that we could think of reworking and publishing later, and also looking at how you handle the customizable keys, we should definitely work at some point on an `InputMapper` extension :) 

Great job! Again, very impressed by the result. It looks rock solid.

**Comment by san-codequest** [comment]
@4ian Thanks for the compliment and it would be a great honor to see my example at GDEVELOP 😁

**Comment by 4ian** [comment]
Added for the next version :) (1b8521b99147b0208fcb9ecaed013f6727ba3130)
Thanks and, again, great job!
