### ISSUE TITLE
cursor is NOT on multiple instances

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2121]
The inverted condition "cursor/touch is on object" doesn't seem to work with several instances or an object group, even with a Pick all, even with a for each.
In the platformer example, I added:
![image](https://user-images.githubusercontent.com/25978830/100949275-2adcf180-350a-11eb-827c-f4da6fbc1d60.png)
Am I missing something? 😕

**Comment by 4ian** [comment]
The reverse of this condition will pick objects that are not being touched - but it won't be true only in the case of no objects at all being touched by the cursor.
If you want this behavior, I recommend using a fake cursor object and checking the inverse of "collision between FakeCursorObject and Checkpoint". 
As this condition is using two object lists and is inverted, it will be true only when there is at least one object from the first list (FakeCursorObject) that is not in collision with ANY of the second list (Checkpoint).

I agree this is a bit confusing, not sure how to make this clearer.

**Comment by PascalLadalle** [comment]
Yes, the filtering logic is sometimes hard to grasp, and the invert makes it ten times worse. 😖 
But shouldn't _Pick all_ change the result? And shouldn't the inverted cursor condition apply an "ANY" like the collision condition?
I had tried a fake cursor, but it didn't work because I have multiple layers and camera motion, so using the cursor would have been an easy way out.
Looks like I finally fixed it with this:
![image](https://user-images.githubusercontent.com/25978830/101012237-1b3dc700-3563-11eb-902e-5d6e5d4e2973.png)
God knows how much time I spent on this 😨

**Comment by 4ian** [comment]
> But shouldn't Pick all change the result?

Why would it change the result? Pick all just select all objects from the scene - whatever you did before.

>  And shouldn't the inverted cursor condition apply an "ANY" like the collision condition?

Possibly - for now this is not the case. It could be used as this:
```
Condition: (inverted) cursor/touch is on Button
Action: set animation of Button to "normal"

Condition: (inverted) cursor/touch is on Button
Action: set animation of Button to "hovered"
```

In this case, you don't want to have the "inverted" acts as any. Because you want a button to be "hovered" when the cursor is on them, and them go back to normal as soon as the cursor is not on it anymore - regardless of others.

Note that you can do convert this to a "any" by yourself, using a variable:
```
Condition: none
Action: set variable IsOnACheckpoint to 0

Condition: Cursor/touch is on checkpoint
Action: set variable IsOnACheckpoint to 1

Condition: if variable IsOnACheckpoint is equal to 0
Action: Whatever action if want
```

**Comment by PascalLadalle** [comment]
> Why would it change the result? Pick all just select all objects from the scene - whatever you did before.

I hoped _Pick all_ might "force" mass selection of all instances/objects on the next conditions, to convert that ANY to ALL, but I understand now that it doesn't change the _filtering mode_ of the next conditions, so to speak.

Thanks for the explanation and variable workaround!
