### ISSUE TITLE
Panel Sprite render is offset on Android OS

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2124]
## Describe the bug
When using Panel Sprites (9-patch) I noticed that on both Android browsers, and using and exported version of my project for Android that the render looks really ugly.  More specifically it looks to be offset incorrectly and often filled with a black void (perhaps the background color?)

Here's a screen shot with the issue circled:
![android-panel-sprite-issue](https://user-images.githubusercontent.com/251967/101294575-e12c2980-37dd-11eb-9864-b7e680182d6c.jpg)
It looks much worse in my game, because I use panel sprites for all of my UI buttons.
But the following micro project demos the issue well:
[android-panel-sprite-bug.zip](https://github.com/4ian/GDevelop/files/5649643/android-panel-sprite-bug.zip)

## To Reproduce
1. Create a panel sprite
2. Add it to a scene
3. Do a network preview and view it on an android device
4. OR export project to android and load the APK on your device

## Other details
* Android 5.1? (Fire OS 5.6.8.0)
* Tried on Chrome Browser and Silk Browser and Native APK
* I don't have a non-Fire OS android device to test on... so there's a possibility this only affects older versions of Android?

**Comment by krunkster** [comment]
FYI I have not heard complaints from testers on more standard Android releases... so I think this might just be an issue with Fire OS.

**Comment by 4ian** [comment]
This could be a GPU issue, and knowing that Fire OS 5.6.8 is based on Android 5 which is starting to be fairly old, I'm not sure we can easily reproduce or fix this :/
