### ISSUE TITLE
Tetris update

### ISSUE THREAD

**Issue by cronosauria** [4ian/GDevelop#2126]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

Hi, @4ian 
I have attached the Tetris game.json.
I want to show users more organized code.

Improvements:
-Added more comments.
-SRS-related codes have been polished.
-Fixed a bug where "reset high scores" was not applied immediately.
-Added delayed input handler behavior.
-Added a credit for myself in the intro 😃

[game.zip](https://github.com/4ian/GDevelop/files/5658321/game.zip)

**Comment by 4ian** [comment]
Updated! Thanks, really nice work 👍
