### ISSUE TITLE
Provide the ability to return the "zoom" property of a camera

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2130]
## Description

Currently, if you want to know the zoom level of a camera, you have to calculate it manually.  Something like this:

CurrentZoom = SceneWindowWidth() / CameraWidth("",0)

## Solution suggested

Provide the ability to return the zoom property of a camera, just like we do for: [CameraWidth, CameraHeight, CameraX, CameraY, CameraRotation]

![Screenshot 2020-12-10 115012](https://user-images.githubusercontent.com/8879811/101816172-ea6b0e00-3add-11eb-9dd6-e38efd1534cd.jpg)

**Comment by 4ian** [comment]
Definitely, should not be too hard to add!

**Comment by rs4231199** [comment]
@4ian I'm looking to start contributing to GDevelop. Can I try fixing this issue?

**Comment by 4ian** [comment]
Of course! Feel free to work on this and open a PR if you have a solution :)

**Comment by dkapur17** [comment]
@4ian, I'm looking to get started contributing to this repo. I've spent a few days going through the codebase and have added this feature into my local branch. I was wondering if for the PR, should I make a new branch for this feature and then make the PR or just make the PR to the master branch?

**Comment by 4ian** [comment]
Usually on your own repo you do it in a branch (so you can switch between features easily). Then you open a PR that will be done on this repository master branch.

**Comment by dkapur17** [comment]
@4ian I did work on it in a new branch and it seemed to be working fine in the IDE as well so I merged it to my master branch before pushing. I hope that isn't a problem.

**Comment by 4ian** [comment]
Closing as added for next version. Thanks @dkapur17!
