### ISSUE TITLE
[$150 bounty] MQTT client extension

### ISSUE THREAD

**Issue by lapieandalpie** [4ian/GDevelop#2135]
--- I realize this is a fringe feature, so I am happy to pay for it to be added. It was recommended on the forum to post it here in order to add it to the bounty list ---

Request:
An mqtt client extension tied into gdevelop gui to alow login to server, subscribe and publish of topics. 

The primary reason I'm keen to see an mqtt client in gdevelop is to create games integrated with small iot devices. I've started running school workshops introducing kids to gdevelop and being able to tie together what they've learned about arduino/esp32 with gdevelop would allow them to create enhancements like remote button panels and led strips that react to the game states, relays that unlock from game events, etc. (and hopefully spark new coders)  The kids already use arduino micros in keyboard emulation to make joystick/button panels for gdevelop and they (and myself) are really excited about creating games that extend beyond the screen/around the room/building/world. 

The target user in my case would be kids using gdevelop to build local "group play" games/escape room style games such as a real world "among us" style game with multiple gdevelop "stations" as well as iot devices like light/sensor/rfid readers/relay controllers all sending simple status and state messages to each other via a local or internet mqtt server.

The problem? the pvp and get/post solutions are a big step for new-to-programming devs who are creating games "without using code" and difficult/complex to to integrate with iot devices.

The solution?
There are some robust mqtt js/node clients.  If someone were able to package one up as a gdevelop extension (if this is possible)  and add a simple interface for server address/ login/ password / topic subscribe / topic publish and a method for subscribed topics to be accessed as variables, not only could all the above be easily implemented, but it could also be useful for other user functions, such as a simpler chat or turn based mechanic to be added by novices.

![mqttexample](https://user-images.githubusercontent.com/57111577/101994601-783a3980-3d28-11eb-8a53-cdf5ad90dd28.jpg)

I'm happy to pay a bounty, write the wiki about mqtt and create a sample project if someone is able to implement it. Cheers!

**Comment by arthuro555** [comment]
@4ian What is your opinion on this? It could be also useful for multiplayer in general, but we would need to do some more testing to see if it is better than sockets.io. I don't think having many libraries for networking is a good idea, as it might confuse users on which they should use. Maybe this should be proposed as an events functions extension?

**Comment by 4ian** [comment]
This seems very specific indeed and IoT related so this would probably not qualify for an "official" extension but that could surely be an extension published on the community extension registry as you suggest. 

@lapieandalpie If you're interested in offering a bounty for this, you can do some using bountysource: https://www.bountysource.com/teams/gdevelop/issues?tracker_ids=3677421
(or another similar website, I've just tried bountysource so far).
or hire a freelancer?

I imagine one could pack an existing Node.js/browser JS client into an extension (or load it from a CDN - I usually don't encourage this but this can be a temporary solution) and then expose feature (all using JavaScript events).

**Comment by lapieandalpie** [comment]
Cheers, guys.  I've put $150 on the issue bountysource.  Hopefully that'll spark somebody to look at it.

**Comment by arthuro555** [comment]
That definitely sparks my interest! I'm looking into it ;)

**Comment by lapieandalpie** [comment]
Awesome, Arthuro!

**Comment by lapieandalpie** [comment]
2 questions:  1. how do we access a suscribed topic? (I was hoping that the subscription function could name a global variable to place the received data... is that possible?)   like "subscribe to topic foo to be saved to global variable bar"
and 2. the field in "connect to mqtt server" is "host port".  Can you clarify if this is the port or the full server address including port?

**Comment by 4ian** [comment]
Sorry I did not meant to close the issue yet. I suggest that:
- you both discuss to make sure @lapieandalpie understand how to use the extension. Possibly @arthuro555 makes some fixes if needed.
- ideally, take these questions and put them in a wiki article as documentation :) (an help page URL will be available in the next version of GDevelop for extensions)

@lapieandalpie will then close the issue so that the bounty can be claimed.

**Comment by arthuro555** [comment]
> how do we access a suscribed topic?

Once you subscribed to a topic, you can listen to it with the On Message condition. When a message is received, it will trigger that condition, and you can get the data with the `MQTT::GetLastMessage` expression. Kind of like this:
![image](https://user-images.githubusercontent.com/19349038/102246218-c9038b00-3efe-11eb-9056-8ef75e0414f8.png)

> the field in "connect to mqtt server" is "host port"

Whoops, didn't mean to leave it like that, I forgot to write the actual description. What you enter is the host without any protocol. You can also enter a port if you wish. For example, just `localhost` can be valid, it will connect via websocket to the default http port (`ws://localhost:80`). You can also add the port like this: 
![image](https://user-images.githubusercontent.com/19349038/102247528-5c898b80-3f00-11eb-9276-fb937b9581bd.png)

The port 8081 is used as it is the port of the test mosquitto server for secure websockets. If you want, you can disable tls by disabling the secure connection and using the port 8080, as you can see on http://test.mosquitto.org/. The exact port depends on your broker server.

**Comment by lapieandalpie** [comment]
I've only been able to glance at it (I'm still at work), but I'm super impressed with how thoroughly you've tied it all together and integrated it into gdevelop.  It (without any testing yet) looks to be exactly what I was hoping for. Cheers!

**Comment by lapieandalpie** [comment]
Hey Arthuro!  I haven't had a chance to test with my local mqtt servers but i recreated your connections to mosquitto and it worked great!  I'm going to mark the issue closed so you can claim your bounty.  Hopefully if there are any problems you can help with them, but it looks like you nailed it!  Thanks!

**Comment by arthuro555** [comment]
If you want to contact me/ask questions/request changes, you can find me on the discord server of GDevelop and on the GDevelop forum 😉
