### ISSUE TITLE
Tetris Update

### ISSUE THREAD

**Issue by cronosauria** [4ian/GDevelop#2138]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.
  
Improvements:
- Fixed a bug where SRS did not work because of typos caused by the previous fix.
- The color of the L and J pieces has been changed to match the original.

I included the reduced mp3.
Thank you too :)

[Tetris_201216.zip](https://github.com/4ian/GDevelop/files/5700532/Tetris_201216.zip)

**Comment by 4ian** [comment]
Updated, thanks!
