### ISSUE TITLE
Include object behaviors in function ? 

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GDevelop#2142]
## Description
As far as I know, we can't use object behaviors in function

What Im trying to make is like a function that use the "tween" behavior to make an object float
So then I would just have to tell the object as a parameter to make the object float

The problem is, you can't add behaviors in the function to be able to use them then

I was able to create a tween action by copy pasting it from an other scene, but then if I edit the event, it's telling me "The bahavior is not attached to this object. Please select an other object or add this behavior." and so far is a normal alert as Im not able to add the behavior to the object

## Solution suggested
Let the possibilities to add behaviors in functions ?

**Comment by 4ian** [comment]
You should be able to ask the object to have a behavior by adding one or more behavior parameter after the object:
![image](https://user-images.githubusercontent.com/1280130/102469985-b5b60400-4053-11eb-9503-7e32d2b2a626.png)

Is this solving your issue?

**Comment by Jeje2201** [comment]
Dam.. I was blind I guess
Might update the wiki about to let other people know about this 

Thanks @4ian ❤️

**Comment by Jeje2201** [comment]
@4ian Is there a reason why this parameter is not accessible in the behavior properties ? 

![image](https://user-images.githubusercontent.com/19387127/102716610-43585480-42dd-11eb-915f-0af583027114.png)

Because then if I want to create a Behavior function that run all time

![image](https://user-images.githubusercontent.com/19387127/102716624-5c610580-42dd-11eb-80e1-f4c82354bd86.png)

I can't create condition and action based on an other behaviors

**Comment by 4ian** [comment]
> Is there a reason why this parameter is not accessible in the behavior properties ?

It should be. There should be an action (or condition or expression) for the property but it's only accessible inside the behavior itself.
If you want to expose this to other behaviors, you can make an expression (or condition, or an action) to access it/modify it.

In doStepPreEvents and the other lifecycle methods, you can't get any parameter, so you can only use the **Object** (and the Object behavior). But the properties should still be accessible.
