### ISSUE TITLE
Stack Exchange page

### ISSUE THREAD

**Issue by hacknorris-notyetbanned** [4ian/GDevelop#2154]
maybe you'll also make a page on stack-exchange? it's good, i have account if to ask ;)

**Comment by 4ian** [comment]
Careful about the title of your posts, please use a proper one :) We don't have a specific stack exchange page but anyone can I think add the "gdevelop" tag.

**Comment by hacknorris-notyetbanned** [comment]
okay ;) last time, nomore

**Comment by hacknorris-notyetbanned** [comment]
idk if it's a good idea but i think that if sharing and as i see ur rich, so maybe share also in microsoft store, ubuntu store or even app store for mac os?
