### ISSUE TITLE
I18n request

### ISSUE THREAD

**Issue by yu-tang** [4ian/GDevelop#2168]
Internationalization support is needed for the term "Instant."
See below image. Left: English, Right: Japanese.
![instant](https://user-images.githubusercontent.com/578576/103464522-a0d9b000-4d77-11eb-917c-696b573e3cdb.png)

**Comment by Bouh** [comment]
Thank you for this report!

If someone want give a try this is a good first issue, feel free to start and submit a PR.
You should edit this file

[`newIDE\app\src\EventsSheet\ParameterFields\ForceMultiplierField.js`](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/ParameterFields/ForceMultiplierField.js#L41)

Probally remove the function `makeNonBreakable` and the import, and wrap the word 'Instant' in a `<Trans>` tag.

**Comment by Manas502** [comment]
Could you possibly elucidate a bit more about the issue?

**Comment by INNOVATIVEGAMER** [comment]
I applied fixes as you said but the text "instant" is not getting translated by <Trans> tag.
@Bouh I think we also need to provide translations for "INSTANT" word in i18n provider.

**Comment by Bouh** [comment]
If the word isn't yet translate in the dev en it is because instant word
isn't yet on crowdin.

**Comment by 4ian** [comment]
To verify something is included in translations, choose the language "Pseudolocalization" (in development mode only):
![image](https://user-images.githubusercontent.com/1280130/103479728-f04bca80-4dcf-11eb-8fc7-74dddcaf627d.png)

Then to see something that you added, like Instant, run in newIDE/app: `npm run extract-all-translations` then `npm run compile-translations`. Then refresh the editor and you should see the word "Instant" to be "pseudo translated", like Permanent on this screenshot:

![image](https://user-images.githubusercontent.com/1280130/103479763-2b4dfe00-4dd0-11eb-8a43-5dab2a3f6453.png)

**Comment by yu-tang** [comment]
Hi @Manas502,
I am translating GDevelop to my language on Crowdin for a while.
The term "Instant" does not appears in source strings, so we localizers can do nothing for this now and the term is remained as in English regardless of what your locale settings.

One more thing, I want to make sure that the term has two versions. One for Condition/Action editor (image top), and one for Event editor with embedding in sentence (image bottom). I suspect these source strings come from the different files/contexts.

**Comment by Bouh** [comment]
@yu-tang `Instant` and `an instant` are two different string.

@INNOVATIVEGAMER for **an instant** you can edit [this file](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/ParameterFields/ForceMultiplierField.js#L102).
As you can see there is a bunch of other string to translate, `a permanent`, `a multiplier`...

**Comment by INNOVATIVEGAMER** [comment]
So as @yu-tang mentioned , his team is working on translations. I think for now I shall add `<Trans>` tags at 

1.Button label
2.Return text of renderInlineForceMultiplier

and make a PR . What do you think @Bouh on it ?
