### ISSUE TITLE
Special characters messing with GDevelop

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2175]
A [user on the Discord](https://discord.com/channels/258623956158906368/258659467887902730/795728593019731989) reported issues (no shortcut on Desktop, not visible in Start menu, and no Preview function), possibly related to this character being in the user's data path:
https://en.wikipedia.org/wiki/Dotted_and_dotless_I

**Comment by 4ian** [comment]
Can you post the user report as a screenshot?

**Comment by PascalLadalle** [comment]
![image](https://user-images.githubusercontent.com/25978830/103586401-4a8a7f80-4ee5-11eb-897c-dba5d0d76d0d.png)

**Comment by 4ian** [comment]
I wonder if this can be reproduced with any non ASCII character. The installer is made by `electron-builder` (https://www.electron.build/) so I wonder if it's something they have fixed already.
