### ISSUE TITLE
Backward compatibility after updating an extension

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2187]
## Describe the bug
Update an existing extension can have consequences on it.

- First one is if you have added a custom function inside not included in the original extension, the function will be removed with a bad visual feedback. **Draw_life_bar** function is removed.
[Video 1](https://streamable.com/2br1sj)

   Suggestion:  Update only the existing function/behavior

- Second one is a bad bugged visual feedback because during the update the selection on a function is disabled.
[Video 2](https://streamable.com/d2a3cx) 

   Suggestion: Close the extension tab, or select the first function/behavior.

## Other details
* B103 and lower
* w10

**Comment by 4ian** [comment]
So there are indeed 2 problems there :)

1) When we update an extension, we change "under the hood" the extension and this means the UI can get out of sync, which is dangerous as this expose potential access to deleted memory (i.e: crash or memory corruption). When an extension is updated, we should probably close the extension tab to be 100% safe, or as you said ensure to select again the behavior/function/behavior method to be 100% sure that we're not showing deleted stuff.

2) We also have the issue of backward compatibility. I think in the future we should develop something that analyze the "public interface" of an extension (this means the behavior, behavior methods and functions, as well as their parameters) and warn if there are some changes : 
"The updated extension don't have 3 functions? Check them if you want to keep them (not recommended): ..."

It's in a way the same issue as updating a library in usual programming: you either have to keep the old, deprecated functions in your library, or make a breaking change. In an ideal world, GDevelop could adapt your project according to rules that are set (rename expression XYZ to ABC...), but to keep things simple we could at least add a warning.

**Comment by INNOVATIVEGAMER** [comment]
https://github.com/4ian/GDevelop/blob/b475a2ed9625d268b6924fd88cde306d666aa514/newIDE/app/src/AssetStore/ExtensionStore/index.js#L119-L121

I think before calling onInstall method we should add a code which closes the extension tab associated with the selectedExtensionShortHeader. But how can we reference to that tab from here ?
Here we have only the data related to extension from selectedExtensionShortHeader like name of the extension.

**Comment by INNOVATIVEGAMER** [comment]
as @4ian mentioned two issues,
I have solved the first issue which closes the extension tab before start of the installation.
Shall I make PR or I need to solve second issue also ?
I think second issue is more complex and needs attention in separate PR. :)

**Comment by 4ian** [comment]
It's almost always better to make small separate PRs, so feel free to open the first one :)

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
