### ISSUE TITLE
building Sever

### ISSUE THREAD

**Issue by KairoMartins18** [4ian/GDevelop#2188]
how to create a payment and build server that works with Gdevelop?

**Comment by arthuro555** [comment]
Could you elaborate please? Also, note that the github issues are for discussing the development of GDevelop and reporting bugs/bad UX. If your question is about GDevelop generally, you should try the [forum](https://forum.gdevelop-app.com/) instead.

**Comment by 4ian** [comment]
I'm closing as GitHub is for technical discussions only, not for help about using the app. Thanks!
