### ISSUE TITLE
Add a preference to show the menu bar in previews

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#2190]
... and by default hide it in the preview window :) 

This will avoid issues with the menu bar being shown and distorting the image for games that have a need for a specific resolution. It's also looking more like a real export.
For people wanting to use the console/debugger, they can go in the preferences to enable the menu.

Technically:

* To hide the menu bar: `browserWindow.setMenu(null)` should work
* A new preference should be added in `PreferencesContext`/`PreferencesProvider` and a toggle in the preferences dialog.

**Comment by 4ian** [comment]
As this might be not too complex, I leave it if someone wants to try it.

**Comment by arthuro555** [comment]
I saw that some repos have such issues labeled as "first timers only", so that experienced contributors leave those to newbies for them to learn the codebase. Would it be a good idea to introduce one as well, or should issues marked as good first issues be generally left for newbies?

**Comment by Bouh** [comment]
From my point of view there are two types.
The easy issues that are not very important even though it's good to fix them. 
Like the translations and the little graphical problems of the interface, this kind of little things.
And the more important/critical/expected ones. Nasty bugs/unexpected behavior like Prevent filename collisions, the bigger bugs, it can be interresting to focus on them before a new release.

Personally, even if I know I can solve one of the problems, I wait a few days, to give the opportunity to the others, and not be overwhelmed with my current PRs (i try).

[Even there will be enough for everyone ^^](
https://github.com/4ian/GDevelop/labels/%F0%9F%91%8Cgood%20first%20issue)

**Comment by rs4231199** [comment]
I'm working on this.
