### ISSUE TITLE
Doubled extension prefix

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2195]
When editing an expression with the Dialogue extension, the prefix gets doubled:
![image](https://user-images.githubusercontent.com/25978830/104039192-583a5080-51d6-11eb-8f53-95e7567b2ef3.png)

Reproducing steps:
Click on a text field, write "tags", press Return. 
Realize you wanted "BranchTag()", so hit backspace three times and press Enter.

**Comment by Bouh** [comment]
![to_delete](https://user-images.githubusercontent.com/1670670/104040138-94ba7c00-51d7-11eb-9b99-ef62d1f1f143.gif)

**Comment by D8H** [comment]
Maybe this issue is solved by this PR: https://github.com/4ian/GDevelop/pull/2702
Because the the way the autocompletion is inserted has changed, but I'm not sure how to reproduce it.

**Comment by 4ian** [comment]
I believe this is fixed, I remember testing and could not reproduce this. The way you reworked autocompletions means it should be fool proof there, because there is not a "fake" parser used when inserting completions - the completions now contain the position where they must be inserted :)
