### ISSUE TITLE
Color expected but "0" found

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2197]
Each time a text object is modified, it triggers this warning in my Firefox console.
![image](https://user-images.githubusercontent.com/25978830/104106082-3e227000-52b3-11eb-9922-a23a86c7ce9f.png)

It even does it with the splash screen percentage loading.
For instance, adding this line to the Firebase example (analytics scene) adds one warning per second:
![image](https://user-images.githubusercontent.com/25978830/104106060-159a7600-52b3-11eb-97ae-c5634a370768.png)

Should it be ignored?

**Comment by Bouh** [comment]
I thought it was a message from GDevelop, but it looks more like a message from Firefox itself.
No idea of the origin I don't know Firefox, i'm sure it not from GDevelop, all warning messages in the console are in English.
And after a fast check i've found zero warning in GD about colors. Here few examples;

- You entered a text, but a number was expected.
- You entered a text, but this type was expected: ...
- You entered a number, but a text was expected (in quotes).
- You entered a number, but this type was expected: ...
- Missing a closing parenthesis. Add a closing parenthesis for each opening parenthesis.
- You must add the operator + between texts or expressions.
- No operator found. Did you forget to enter an operator (like +, -, * or /) between numbers or expressions?
- More than one term was found. Verify that your expression is properly written.
- You must wrap your text inside double quotes
- You must enter a number / text
- You've entered a name, but this type was expected: ...
- Missing a closing bracket. Add a closing  bracket for each opening bracket
- etc...

**Comment by PascalLadalle** [comment]
Yes, it's a message from Firefox.
Looks like Firefox is expecting a font color parameter that is not sent.

But if I use a FPS counter for instance, this warning triggers every frame. Can such warnings impact performance?

**Comment by 4ian** [comment]
Should be fixed when we upgrade Pixi.js: https://github.com/pixijs/pixi.js/pull/7042

I'll close this as it will be automatically fixed and is harmless :)

**Comment by Bouh** [comment]
If upgrade Pixi.js to 5.3.5 is require for this fix.
5.3.5 has broke TilingSprite, and as we have issues with [TilingSprite in GD](https://github.com/4ian/GDevelop/issues?q=tiling+) with Pixi.js 5.3.0.
I recommend to upgrade to 5.3.7 which is also require for fix a lot of problem with BitmapText.

**Comment by 4ian** [comment]
> I recommend to upgrade to 5.3.7 which is also require for fix a lot of problem with BitmapText.

Sounds good, we'll do that either in the BitmapText PR or before as a standalone PR :) Thanks!
