### ISSUE TITLE
Mouse wheel not working on Firefox

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2200]
This is the snippet I use for wheel zoom on my current project:
![image](https://user-images.githubusercontent.com/25978830/104128768-b186b900-5369-11eb-948c-8206acc38ed0.png)

I'm not sure if this is because of beta103, but it's broken.
Works fine on preview, works fine on Chrome, doesn't work on Firefox.

Example project attached for your convenience.
[BrokenWheelZoom.zip](https://github.com/4ian/GDevelop/files/5792924/BrokenWheelZoom.zip)

**Comment by Bouh** [comment]
Firefox's debugger didn't trigger the mousewheel when i make a breakpoint in the dom event list.
But it triggered on Chrome.

**Comment by PascalLadalle** [comment]
You're right, it's not just the zoom. 😨 
I was misleaded by the recent camera zoom change. 😅 
This doesn't work either:
![image](https://user-images.githubusercontent.com/25978830/104130400-dcc0d680-5370-11eb-80ed-aa7d1414fbb3.png)

**Comment by 4ian** [comment]
This is because we wrongly use `onmousewheel` (in `runtimegame-pixi-renderer.ts`) and it's not standard: https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event
We should use this one instead: https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event (`onwheel`)

Should not be too complicated I think!

**Comment by rijusougata13** [comment]
hey there is 3 file with same name as `runtimegame-pixi-renderer.ts` ...
`GDevelop\newIDE\app\resources\GDJS\Runtime-sources\pixi-renderers`,
`GDevelop\newIDE\app\node_modules\GDJS-for-web-app-only\Runtime-sources\pixi-renderers`,
`GDevelop\GDJS\Runtime\pixi-renderers
`.
do i have to make changes in all of them ?

**Comment by 4ian** [comment]
No, just one and the other are generated files. I'll let you search which one is the correct one :)

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by Bouh** [comment]
Thanks for the project file!
Tt now fixed & tested on Chrome, Firefox, Edge.
