### ISSUE TITLE
Add Shape Painter expressions and actions

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2202]
## Description

Shape Painter objects are missing some actions and expressions that would be useful.

### New Actions:
 - [ ] (Setup) "Shape position relative to object position" (bool).  
   - This should be similar to how "Clear between frames" is done

![Screenshot 2021-01-10 122640](https://user-images.githubusercontent.com/8879811/104133487-2691c880-5341-11eb-9a31-ebb074d2d601.jpg)

### New Expressions:
 - [ ] Outline size (number)
 - [ ] Outline color (string)
 - [ ] Outline opacity (number)
 - [ ] Fill color (string)
 - [ ] Fill opacity (number)
 - [ ] Clear between frames (bool)
 - [ ] Shape position relative to object position (bool)

![Screenshot 2021-01-10 121827](https://user-images.githubusercontent.com/8879811/104133488-2b567c80-5341-11eb-8d88-935062774c71.jpg)

**Comment by tristanbob** [comment]
@Bouh This is what you asked me to tag you in.  :)

**Comment by Bouh** [comment]
Thank you for this list i'm on it!
