### ISSUE TITLE
Javascript events autocomplete is broken

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2204]
## Describe the bug
Since the conversion to TS, Monaco doesn't recognize any GDJS api:
![image](https://user-images.githubusercontent.com/19349038/104304326-887e3980-54cb-11eb-9fb4-1e7948d9dfd3.png)
![image](https://user-images.githubusercontent.com/19349038/104304361-9338ce80-54cb-11eb-8d06-dcc40cf0eb71.png)

## To Reproduce
1. Go on any project
2. Add a javascript event
3. Type some gdjs APIs, and notice how there is no autocomplete and hovering over the variable says the type is any

## Other details
* GDevelop development version from master at commit a946f01542c9d44c398e6b968724d879efdcaf91
* electron-app

**Comment by 4ian** [comment]
Ah good catch! I think is simply forgot to change the part scanning files
to search for .ts extensions

**Comment by 4ian** [comment]
Actually the fix was more complex. Fixed in 9bcac613ed6cc11555dcd14bb58d08cb4790c1e7
