### ISSUE TITLE
Library objects with incorrect size

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2209]
![image](https://user-images.githubusercontent.com/25978830/104516629-f5412300-55f4-11eb-9630-c5dda3c8e29e.png)

The default size of the first one is 128 per 128 instead of 64 per 64.
There's also the problem of floor tiles being 128 per 128 when the actual platform is 20 per 128, so all users have to edit either the image file or the hitbox to use them as floor.

**Comment by 4ian** [comment]
It's true that the green substance floor could be trimmed though I think.

**Comment by PascalLadalle** [comment]
I know that the asset was created like this, but if all users have to edit the object called floor to use it as floor in GDevelop, it seems logical to edit the base object.
If we could trim automatically all extra transparent space from the library objects, it would make them more ready-to-use for a majority of cases, I think.
