### ISSUE TITLE
Game freezes when using Pathfinding Destination function.

### ISSUE THREAD

**Issue by tailubabi** [4ian/GDevelop#2224]
## Describe the bug

Using the `Pathfinding::DestinationX()` function always freezes my game. Several workarounds that I've made (adding "For Each", "Trigger Once", etc.) didn't seem to solve the problem. I assume the `Pathfinding::DestinationX()` function might have a problem.

## To Reproduce
1. Apply "Pathfinding" behaviour to an object "ObjectName".
2. Create a tiled sprite "tile" and place it on the scene, covering the entire game screen.
3. Scene Variable "ObjectCount" set to 0.
4. Condition: Timer "spawn" is greater than 0 second, Scene Variable "ObjectCount" is < 10, Trigger once.
    Action: Create object "ObjectName" at `RandomInRange(tile.X(),tile.X()+tile.Width());RandomInRange(tile.Y(),tile.Y()+tile.Width())`, Scene Variable "ObjectCount" add 1, Reset timer "spawn".
6. FOR EACH "ObjectName" object.
    Condition: Timer "objectWalks" is greater than Random(10)
    Action: (Pathfinding)Move "ObjectName" to `RandomInRange(tile.X(),tile.X()+tile.Width());RandomInRange(tile.Y(),tile.Y()+tile.Width())`, Reset timer "objectWalks".

5. **FOR EACH "ObjectName" object.
    Condition: Compare the X position of "ObjectName" < `ObjecName.Pathfinding::DestinationX()`
    Action: Flip horizontally "ObjectName" : yes**

![bugreport](https://user-images.githubusercontent.com/77589412/104856062-db7c4480-5942-11eb-9932-75beea32d777.PNG)

## Other details
My OS: Windows 10 Home 64-bit (10.0, Build 19042), 4 GB RAM, Intel Core i3-1005G1
GDevelop version: 5.0.0-beta103

**Comment by 4ian** [comment]
Could you share a problem showing the problem? Should make the fix easy to do. Thanks! :)

**Comment by PascalLadalle** [comment]
I note the same issue in the pathfinding project I work on.
![image](https://user-images.githubusercontent.com/25978830/104859202-c217d000-5923-11eb-8f60-304016db0375.png)

![image](https://user-images.githubusercontent.com/25978830/104859191-b4fae100-5923-11eb-97d4-b88f84572dad.png)

**Comment by HarsimranVirk** [comment]
`this._path` is a js array, I'm not sure about the purpose of the `back()` function here (which is not an inbuilt js array function), @4ian can you provide some context?

**Comment by 4ian** [comment]
Almost certainly some code that was never verified properly and that is a residue from the port from C++ of this extension, years and years ago :) 
Should be easy to fix (and a good reason for using types/TypeScript!):
- change path to have type `Array<FloatPoint>` instead of `any`. With `type FloatPoint =  [number, number]`.
- see that the `.back()` should now be flagged as errors by TypeScript.
- fix them by replacing by `[this._path.length - 1]`
