### ISSUE TITLE
Copying & pasting in events appears to be broken

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2233]
Copying & pasting in events appears to be broken
Here I am also using ctrl-c and ctrl-v not working, (ctrl-z works though)
version nightly commit (ff55b8b6a05c3ce7821dc5e28b77f3779b7f3a4a)
![TUP98bRgsv](https://user-images.githubusercontent.com/75917656/105572069-15b65f00-5d12-11eb-8157-e21a59c7ccbe.gif)

Reinstalled the same nightly this is what's in the clipboard when copying a action: {"000kind":"GDEVELOP_EventsAndInstructions_CLIPBOARD_KIND-jsBdHbLy912y8Rc","content":{"eventsList":[],"eventsCount":0,"actionsList":[{"type":{"inverted":false,"value":"Arreter"},"parameters":["Player"],"subInstructions":[]}],"actionsCount":1,"conditionsList":[],"conditionsCount":0}}
This is what I copied to clipboard
![Screenshot_2021-01-22_100419](https://user-images.githubusercontent.com/75917656/105572062-0f27e780-5d12-11eb-944b-6aeb5f4ce89e.png)

Tested it on another PC that has a fresh (2 or 3 weeks) install of Windows 10 has the same issue.

I also still get this disabling behavior bug sometimes
![IS2kwSPyPA](https://user-images.githubusercontent.com/75917656/105572071-1818b900-5d12-11eb-8b5e-7267ce0e2f1a.gif)
clicking anywhere changes the index back to 0

**Comment by 4ian** [comment]
> Copying & pasting in events appears to be broken

Indeed! I broke it while reworking the clipboard handling to avoid crashes - verified all the rest but not that 😬
Thanks for reporting this :) 

Should be fixed now. 

Be sure to download it from the CircleCI "workflow" is finished with success:
![image](https://user-images.githubusercontent.com/1280130/105578759-547fff80-5d7a-11eb-8012-b2b5b5917d9d.png)

I've tested and in theory the behavior selection is fixed (it will allow you to choose another behavior). I'll close this issue but please reopen it if you can reproduce the issue again in the latest version :)
