### ISSUE TITLE
Tilemap can be open with Yarn editor

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2253]
## Describe the bug
Json files from Tilemap object can be open with Yarn editor. 
And make the object in the IDE invisible.

![image](https://user-images.githubusercontent.com/1670670/106392687-3f971200-63f3-11eb-9678-3b1d59a24d67.png)

## To Reproduce
1. Go to Tilemap object properties
2. Click on Edit button near to a Json file input.
3. Save in Yarn editor
4. See the object is now invisible on the scene.

## Other details
* B104

**Comment by 4ian** [comment]
Yep it's suboptimal/confusing. We need I think to switch to have different resource type, with different extensions (.yarn?). At least not to show the improper editors.
(cc @blurymind)

**Comment by blurymind** [comment]
Its because both use json files. I am thinking maybe gdevelop can use
netadata to mark different json files as yarn or tiled?

There is a .yarn format that yarn can export, however its just a text file
that bondagejs can't parse as easily without doing something with the data

**Comment by blurymind** [comment]
LocalResourceExternalEditor.js has a kind token, which is hardwiring it to open all json files with yarn. This is obviously going to be problematic, so I wonder how can we get around it.

A suggestion is to make it aware of where it was called from somehow (what extension wants this resource), but I am not sure how to do that properly

**Comment by D8H** [comment]
This issue has been fixed.
