### ISSUE TITLE
Diaogue Tree: save/load, boolean are restored as strings ? 

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#2254]
## Describe the bug
I think i've found a bug in the dialogue Tree extension. I [talked about the issue here](https://forum.gdevelop-app.com/t/dialogue-tree-how-to-check-whats-going-on-with-load-dialogue-state/30220/5?u=kink). 

I'm not 100% sure the problem is not on my side (because i make a jSon conversion of a strucutred var, and json parsing from local storage), but my last test reinforce my opinion (numbers are not converted to string). 

I cannot provide sources files of where i've found the issue. I think explanations here and from the forum might be sufficient to understand and catch the issue.

Basically: using boolean In yarn works fine unless you save/load the dialogue state. If you save the state variables to a structured variable, then save it to local storage (wich is one of the purpose, saving game !), then load it in a new game session (load from storage/load dialogue state variables), the result: 
- string variables are restored as string
- number variables are restored as number
- **Boolean are restored as string**

This makes both yarn and gevelop boolean related conditions fails the check: scripts in yarn dialogue nodes, and event conditions.

My workaround is to totally avoid to use Boolean, since Gdevelop use only number and string variable types.

**Comment by arthuro555** [comment]
🤔 #2137 should allow fixing this issue easily once it is done.

**Comment by 4ian** [comment]
Yeah I was thinking that it is surely because the thing that is saving/loading the Dialogue Tree "state" is saving this state from a JS object to a variable - which is currently not handling booleans. When booleans are handled, they will be properly saved, and so restored.

**Comment by KinkGD** [comment]
cool, i'm not crazy :)

I've learnt a lot with this issue, spending my whole saturday on it to catch the mistake.

**Comment by blurymind** [comment]
Could this pr fix it
https://github.com/4ian/GDevelop/pull/2137

**Comment by 4ian** [comment]
Yes that's what arthuro555 posted ;) It should be fixed as variables will be able to store real boolean values :)

**Comment by blurymind** [comment]
has that been merged in now? Perhaps we can close the issue

**Comment by 4ian** [comment]
That should be solved in beta106 in theory yes!

**Comment by KinkGD** [comment]
I confirm, it's corrected with b106, thanks ! I'm closing the issue.
