### ISSUE TITLE
Infinite loading when opening an autosave

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2262]
Infinite loading I think it only happens from loading saves generated by the preview

![ezs2YqmFtQ](https://user-images.githubusercontent.com/75917656/106672823-f7502f00-656d-11eb-87fb-d5d7c994c305.gif)
![Screenshot 2021-02-02 142938](https://user-images.githubusercontent.com/75917656/106672829-f9b28900-656d-11eb-8eaf-39b6ad90e13f.png)

Windows 10
GDev Preview 104 beta

**Comment by Bouh** [comment]
I had already had this problem, I had compared the file with one of my backups which was working 100%.
And it was identical
The structure of the file was not affected.

However an error in libGD.js was present.
Opening the same file after restarting the application opens the project correctly.

**Comment by 4ian** [comment]
Really strange. If it happens again, go in the Debugger Console, then in "Sources" tab, then click the "Pause" button and show a screenshot (or more) of the Stacktrace.

**Comment by Entr0py404** [comment]
I wasn't sure if this image would be adequate.
![Screenshot_2021-02-05_213541](https://user-images.githubusercontent.com/75917656/107371563-a4acd080-6aa1-11eb-96f8-091917f47a79.png)

**Comment by 4ian** [comment]
I guess it's too late, but the interesting part would have been the full content of the "Call Stack" on the right. Unless it was all that was written there?

**Comment by arthuro555** [comment]
I sometimes get this issue when I open the wrong project and quickly open the correct one. Maybe (just a guess) it is caused by the IDE loading 2 projects at once?
