### ISSUE TITLE
various errors in function editor

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2263]
Hi again I have been trying to find the bug that causes the function editor 
to freeze the whole ide (but not the toolstrip tool bar) and found these errors instead

![Screenshot 2021-01-31 141248](https://user-images.githubusercontent.com/75917656/106673631-1c916d00-656f-11eb-9b8a-64e78a55d5d2.png)

it will give the error no vailed target on drag even without the too many requests error too
https://puu.sh/Hd3x1/3ac12e6dff.webm

this one is not really a bug more of a this is happening
https://puu.sh/Hd3xy/8507b32f48.webm

I'm sorry for all the bug reports in the same day

Windows 10
GDev Preview 104 beta

**Comment by 4ian** [comment]
>  found these errors instead

These errors are not dangerous, you can safely ignore them.

> it will give the error no vailed target on drag even without the too many requests error too

Yes it also a bit verbose but should be safe to ignore I think - even if this one is a bit more concerning.

> this one is not really a bug more of a this is happening

The drag'n'drop is indeed not perfect and should be reworked, but this also should not create any dangerous bug.

**Comment by Entr0py404** [comment]
Okay thank you
