### ISSUE TITLE
Interface - Object Editor - Animation

### ISSUE THREAD

**Issue by e1e5en-gd** [4ian/GDevelop#2264]
**Automatic creation of animations when multiple images are selected**

## Description
Now you can select several images for one animation at once and load them.
A proposal to make it possible to create a separate animation for each when choosing several pictures. So it is convenient to load, for example, a set of items and switch from through animation.

**Comment by Bouh** [comment]
There is already a multi selection when you import images files, and images are added in an animations.

**Comment by e1e5en-gd** [comment]
@Bouh, the idea behind the development of the functionality is that you can choose how to add these images: load everything into one animation or create a separate animation for each image. Do you think that no one will need it?

**Comment by 4ian** [comment]
We could use a convention inspired by the asset store: 
- Images with no convention, or numbers like this image1.png, image2.png, etc... are added as a single animation.
- Images named like this image_animation1_1.png, image_animation1_2.png, image_animation2_1.png, image_animation2_2.png, , image_animation2_3.png... would be added in two animations called "animation1" and "animation2".

**Comment by e1e5en-gd** [comment]
@4ian, I will try to follow the pattern. I thought that this amount of text would be enough to describe the proposal.

Regarding the file names, I would suggest an easier way: when selecting multiple files, display a message to the user "Add selected files to animation or create an animation for each file?".
