### ISSUE TITLE
Do not clear selection when clicking on the mouse wheel

### ISSUE THREAD

**Issue by e1e5en-gd** [4ian/GDevelop#2267]
## Description

Do not clear selection when clicking on the mouse wheel

**Comment by 4ian** [comment]
Please discuss suggestions on the forum before opening anything here :) Thanks!

**Comment by e1e5en-gd** [comment]
@4ian, Sorry, but I wrote about this on the forum: https://forum.gdevelop-app.com/t/moving-selected-objects-to-different-distances/29218

**Comment by 4ian** [comment]
Right this is a good start. It's usually good to wait for other members to validate the request before posting it on the GitHub - discussion is important :) 
Then, make sure to follow the template when writing an issue here - you can't just write a single sentence. Thanks!

**Comment by e1e5en-gd** [comment]
The post was written in early December, I did not wait for a single answer. I'll stick to the template. Excuse me :)

**Comment by 4ian** [comment]
Sorry I missed the date of the original post. Fair enough then, my bad! :) 
Still be sure to stick to template, I know it's a pain but it's useful to understand the context - I could not understand by just reading your issue and we have tons of issues to handle, so it's important to be precise :) Especially considering that sometimes the solution can be discussed.

**Comment by e1e5en-gd** [comment]
Should I create a new request or edit this?

For example like this:

## Description
When moving objects with the mouse across the scene, sometimes it is necessary to move around the scene; for this, use the mouse with the mouse wheel held down. This resets the selected objects on the scene.

## Solution suggested
Do not clear selection when mouse wheel is pressed.

**Comment by 4ian** [comment]
Yes that's much better this way. Let's create a new issue so that it's not polluted with the previous discussion :)
