### ISSUE TITLE
TileMap object action "Set the TileMap JSON File..." does not work

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2271]
## Describe the bug
Using the "Set the TileMap JSON File..." action on a TileMap after creating it does not actually update the tile map. The TileMap object will only seemingly use the TileMap JSON file that it was defined as in the scene.

## To Reproduce
[tilemap-set-map-bug.zip](https://github.com/4ian/GDevelop/files/5922244/tilemap-set-map-bug.zip)
The attached reproduction has a tilemap object defined in the scene
The events create an instance of that tile map at the begining of the scene
When the scene is touched/clicked the TileMap object is updated to use a new JSON file
But the TileMap object is NOT updated

I think this must be a bug, otherwise why would there be an action to modify this?

## Other details
* Windows
* GDevelop Desktop 5.0.0-b104

I'm really excited about using TileMaps, but it's going to be very inefficient if I have to create a specific TileMap object for every level I want to load.
If you are interested you can see how I'm planning to use TileMaps here:
https://forum.gdevelop-app.com/t/use-tilemaps-efficiently/30339

**Comment by blurymind** [comment]
Hmm interesting,  this actually worked ok in the demo project I used when developing it 🤔 I will try to have a look tomorrow

**Comment by blurymind** [comment]
@4ian could this be because an instance of the tilemap is created using the event sheet at the start of the scene?

@krunkster what happens if the instance is created one second after the start of the scene? I bet its something to do with resource loading in GD

**Comment by 4ian** [comment]
> could this be because an instance of the tilemap is created using the event sheet at the start of the scene?

No this is not related, objects are handled the same way.

If I open the example, put the TileMap on the scene, then change in its properties from level1.json to level2.json, it is also not working! The first tilemap is still shown.
So there is a problem in the tilemap helpers I think.

See:
![image](https://user-images.githubusercontent.com/1280130/106874121-1ca77f00-66cd-11eb-8a23-d519779b3d05.png)

But still the old tilemap:
![image](https://user-images.githubusercontent.com/1280130/106874152-24672380-66cd-11eb-826a-d3a92f0314a5.png)

**Comment by blurymind** [comment]
Thanks @4ian I must have broken it along the way. Will try to pr a fix tonight if it hasnt been fixed already :) 👍

**Comment by blurymind** [comment]
lol, that was a pretty silly bug 😸 
Fix here
https://github.com/4ian/GDevelop/pull/2273

**Comment by krunkster** [comment]
I really appreciate the fast fix on this! Since it's so new I'm still trying to figure out how to best leverage the feature efficiently, so I'm glad the map data is mutable on the object.
