### ISSUE TITLE
Sprite blend mode=2 (multiply) makes the sprites 100% black

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2272]
## Describe the bug

Sprite blend mode=2 (multiply) makes the sprite 100% black

## To Reproduce
1. Create a scene with a sprite
2. Use an action to change that sprite to blend mode = 2 (multiply)
3. The sprite will now appear to be solid black object

## Example game

https://victrisgames.itch.io/gdevelop-sprite-demonstration

## Video

(Problem seen at 27 seconds)

https://user-images.githubusercontent.com/8879811/106919990-e0bdeb00-66c7-11eb-89bb-08397403af8e.mp4

**Comment by blurymind** [comment]
Can you share the example project? This will help us tremendously to test for regressions 😄

**Comment by Bouh** [comment]
Without effects on layers the result still black?

**Comment by Bouh** [comment]
After some test in GD, blendmode action have not the same result than blendmode from effects layer.
The blendmode from action make sprite black if you use an effects with it.
As you can use blur effect of layer for your driller and you use the action blendmode the result is bugged.

We have to reproduce it in a sandbox for report it to Pixi team.

**Comment by Bouh** [comment]
Report to Pixi
https://github.com/pixijs/pixi.js/issues/7224

**Comment by tristanbob** [comment]
Great observation @blurymind and great work @Bouh!   

I just set up this same example game using the blend mode effect on the layer (instead of the sprite). 

1) The sprites are no longer solid black on mode=2 (yay)
2) When sprites overlap (on the same layer) the blend mode has no effect.  I guess this makes sense.  The background sprite is on another layer and you can see it under the sprites.
3) Blend mode 1 and 3 remove the drop shadow effect (perhaps intentional or design limitation)

Because of 2. above, I'm not going to update my sprite demo game with layer effects.  If/When pixi fixes this bug and it is rolled into GDevelop, we can come back and test my game again.

**Comment by Bouh** [comment]
No fix are required.
See the explanation from Pixi team

> This is working as intended, but I can see what this is confusing.
> 
> In general, for filters to work, Pixi does a "snapshot" of your display object to another surface then applies the filters to that. Because blend modes are a post-process, when you use multiply to your original container of sprites Pixi doesn't know what to multiply the pixels to when it does the snapshot because blend modes take into account the pixels below the object. What you actually need to do is add the blend-mode to is the filter, which will apply it to the snapshot the the original source.
> 
> Now, this would work if you your bunnies weren't on an opaque background, like this because there's some information about _what_ to multiply.
> https://jsfiddle.net/bigtimebuddy/to5k9z0s/
> 
> In that case, we create an opaque background, add multiply to the bunnies, then blur. Everything is 👍

**Comment by tristanbob** [comment]
Thanks for helping find this information.  I'll close the issue.
