### ISSUE TITLE
Tilemap not working on webapp, module are missing

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2277]
## Describe the bug
Tilemap not working on webapp, module are missing

![image](https://user-images.githubusercontent.com/1670670/106980782-182ca600-6761-11eb-8211-504486359f05.png)

>Unable to load module "pixi-tilemap-helper". Are you sure you registered it using ObjectsRenderingService.registerModule? This is mandatory for the web-app to have the file bundled.

>Unable to load module "pako/dist/pako.min". Are you sure you registered it using ObjectsRenderingService.registerModule? This is mandatory for the web-app to have the file bundled.

## To Reproduce
1. Disable cache browser
2. Reload the page, be sure to use b104
3. load an example with tilemap object
4. There is no object tilemap or isn't working in IDE.

## Other details
* b104
* webapp

**Comment by 4ian** [comment]
Thanks for reporting! Fixed in  https://github.com/4ian/GDevelop/commit/79b8e19da56fe1659387445b9f1989b984caf98f and re-deployed the web-pp.
