### ISSUE TITLE
Hitbox of tiled sprite platform not resized with events

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2280]
A tiled platform resized with "Change the width" action keeps the original hitbox.
I thought this had already been reported, but I can't find it.
Example attached. Play the scene and walk on the growing platform.

[My project13.zip](https://github.com/4ian/GDevelop/files/5935708/My.project13.zip)

GD5b104

[source](https://forum.gdevelop-app.com/t/changing-the-size-of-a-tiled-sprite-with-events-doesnt-work/30361/2)

**Comment by 4ian** [comment]
Wow, weird that it was indeed not reported before! Sorry for the delay. Thanks for the example game, I'll fix the issue :)

**Comment by 4ian** [comment]
This is now fixed for next version :)
