### ISSUE TITLE
Condition "ParticleEmitter does not emit anylonger" doesn't trigger

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2285]
## Describe the bug

When using the Condition "ParticleEmitter does not emit anylonger", it doesn't trigger even when an emitter runs out of particles.

## To Reproduce

- Create a particle emitter using default settings
- Change "Number of particles in tank" to "100"
- Create a condition for "ParticleEmitter does not emit anylonger" with an action to change the background color
- Preview game (the emitter will stop emitting but the background color doesn't change)

## Other details

- Tested on GDevelop 5 Beta 104

## Video

https://user-images.githubusercontent.com/8879811/107173246-9c12a800-6984-11eb-8246-659c7ecbff28.mp4

**Comment by Bouh** [comment]
There is also a bug in how many particles are created.
If you setup 1 particule in Tank properties, you start the preview nothing happens, there is an offset of 1 on this parameter.

**Comment by Bouh** [comment]
And

```JS
 getTotalParticleCount(): integer {
      return this.emitter.totalParticleCount;
}
```
Return undefined.

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by AlexandreSi** [comment]
Thanks for reporting this bug, the particle emitter needed a good clean!
