### ISSUE TITLE
RPG-dialogue tree example

### ISSUE THREAD

**Issue by potato-gamer-coder** [4ian/GDevelop#2287]
Hi!
  
  I'm potato coder
  I'd like to submit a new example to be added to GDevelop because when I was searching for RPG-dialogue tree example I didnt find one so I made this for people whos searching for this.
  Here is the link to download it: 
https://drive.google.com/drive/folders/1aAV4tg8F-dWj5fvs7UhQJElFPpqk9Hir?usp=sharing
  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by potato-gamer-coder** [comment]
> Hi!
> 
> I'm potato coder
> I'd like to submit a new example to be added to GDevelop because when I was searching for RPG-dialogue tree example I didnt find one so I made this for people whos searching for this.
> Here is the link to download it:
> https://drive.google.com/drive/folders/1aAV4tg8F-dWj5fvs7UhQJElFPpqk9Hir?usp=sharing
> I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Midhil457** [comment]
Hi @potato-gamer-coder I just checked out the project. It works and is great!

I did find some problems with it,

- You should add some comments in your script telling what that events is for, what it is doing, why it is doing it, etc...

- It is not recommended to use spaces in variable names. Ex: Not "Player Name" but PlayerName

:)

**Comment by potato-gamer-coder** [comment]
@Midhil457 okay ,thanks!
I'll add the stuff! ^_^

**Comment by potato-gamer-coder** [comment]
@Midhil457 finished updating if you have time I'll be glad if you tried it 👉👈

**Comment by Midhil457** [comment]
Hi, @potato-gamer-coder , I will be reviewing it this weekend! <3

**Comment by potato-gamer-coder** [comment]
thanks @Midhil457 !

**Comment by 4ian** [comment]
Thanks both 👍👍

**Comment by Midhil457** [comment]
Hi, I checked out the redone project. And the comments are great! They tell what it does clearly

It is recommended to not use spaces in variables as it could break in the later versions, which might be terrific

Also, there is a small typing mistake, it is plays not playes 
![image](https://user-images.githubusercontent.com/73597906/111902906-98833e00-8a65-11eb-9a09-088b492a7895.png)

:)

**Comment by potato-gamer-coder** [comment]
@Midhil457 you see the invalid sprites their all from an undertale fan game I was doing then instead of doing it again I just copied the folder and made this

**Comment by Midhil457** [comment]
Hi, I just reviewed it and the invalid paths are gone, 

But, these problems are still not fixed,

- Please don't use spaces in variable names as it could break your example in the future updates

- I just noticed that you are not declaring variables that are being used, please do declare them as this can be more optimized and viewer of this example might get confused, like said here http://wiki.compilgames.net/doku.php/gdevelop5/all-features/variables#using_variables_without_declaring_them

**Comment by Midhil457** [comment]
Hi, I just reviewed it again and it is now fine,

But, again:

- You are not still declaring the variables, please do add them to the scene variable list
      
![YDE1](https://user-images.githubusercontent.com/73597906/113250542-4d2b2400-92de-11eb-8267-ba22b88f93a1.png)

- It would be great if you changed the 2nd animation (That black blob) of the text face to something similar to the first animation (That witch face). I thought the animation was glitch out. Maybe change it to the witch face getting excited and not a black blob.

- There is still an unused timer "howdy", please remove it
     
![YDE2](https://user-images.githubusercontent.com/73597906/113250806-cfb3e380-92de-11eb-913b-93410c8b6872.png)

:)

**Comment by potato-gamer-coder** [comment]
@Midhil457 updated thanks for viewing it!
^_^
hope this one be good!

**Comment by Midhil457** [comment]
Hi, so I just reviewed the project and it works great!

The 2 "At the beginning of the scene " could be merged and one could be made a sub-event.It was a small change,so I did it

Here:  [yarn-example.zip](https://github.com/4ian/GDevelop/files/6257450/yarn-example.zip)

I think this can be added, @Bouh ?

**Comment by potato-gamer-coder** [comment]
@Midhil457 okay thanks updated!
^_^
I think now its in the best condition

**Comment by 4ian** [comment]
Thanks again @potato-gamer-coder and @Midhil457! I've added the example to the next version :)

**Comment by potato-gamer-coder** [comment]
@4ian you're always welcome!
^_^

**Comment by blurymind** [comment]
Thank you for working on this! Happy to see the extension is being used and hopefully more people are telling stories with Gdevelop :)
