### ISSUE TITLE
rpg dialogue tree example

### ISSUE THREAD

**Issue by potato-gamer-coder** [4ian/GDevelop#2288]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it:
 **https://drive.google.com/drive/folders/1aAV4tg8F-dWj5fvs7UhQJElFPpqk9Hir?usp=sharing**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Bouh** [comment]
https://github.com/4ian/GDevelop/issues/2287
