### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by panacanadianpeep** [4ian/GDevelop#2291]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta105-aa70df7ab2340cc09148aa3566b18961e2670eea
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36,

**Comment by Bouh** [comment]
@panacanadianpeep Can you tell more about this bug?
How did it happen? What are you trying to do just before it crash?

**Comment by panacanadianpeep** [comment]
@Bouh Sorry for the late reply, didn't see the message until now. The bug happened online in the editor, when I was about created something in the editor. I was trying to apply 2D platformer movement.

**Comment by Silver-Streak** [comment]
Hello!

Are you still experiencing this issue? Can you provide the steps to reproduce the crash?

I'm going through older/stale issues that have pending actions. I'll close this out if we don't hear back from you by next Friday (8/13/21) or if we receive confirmation that it is no longer occurring.
