### ISSUE TITLE
Wrong TileMap selection box/visibility issue when maps have empty space

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2293]
## Issue Description
When using a TileMap with lots of empty space (commonly due to fixed sized levels) the tilemap will often be hidden from view.

I believe this is due to an optimization in the engine that tries to hide objects that are "off screen".
When using a TileMap with a lot of empty space you can see in the IDE that the "size" of the object in the scene editor is only as big as the tile content in the tile map NOT including the empty space.

## Workaround
If you have a map with a lot of empty space, try adding a "dummy" or placeholder tile in the corners of the map to trick the engine into "seeing" the true height of the tilemap.

## To Reproduce
[tilemap-visibility-issue.zip](https://github.com/4ian/GDevelop/files/5952558/tilemap-visibility-issue.zip)
The above reproduction has an artificially low resolutions to exacerbate the issue.
There are two tile maps in the scene.
Both maps are a fixed size of 33 tiles tall, 100 tiles wide, tile size of 8x8px
The first map has a roman numeral I and only tiles on the bottom of the map
The second map has a roman numeral II and tiles along the top of the map
Both are in the scene and visible in the IDE
When you preview however the first map will not be visible

## Other details
* Windows
* GDevelop 1.0.0 b105

**Comment by 4ian** [comment]
> I believe this is due to an optimization in the engine that tries to hide objects that are "off screen".

Correct, this is called "culling".

> When using a TileMap with a lot of empty space you can see in the IDE that the "size" of the object in the scene editor is only as big as the tile content in the tile map NOT including the empty space.

That's indeed a nice way to see the problem.

@blurymind We should fix this with a high priority because it's impacting users and a real rendering issue.

Thanks for the repro game! :)

**Comment by blurymind** [comment]
I will have a look tonight :)

**Comment by blurymind** [comment]
This is the ticket on pixi-tilemap btw
https://github.com/pixijs/pixi-tilemap/issues/108

**Comment by blurymind** [comment]
If tiled exports x,y coordinates of tiles on their atlas and on the tilemap, I will be able to create a much better fix for this bug.

Bjorn mentioned that there is a ticket for that here
https://github.com/mapeditor/tiled/issues/2863
