### ISSUE TITLE
Just a mistake in writing of description for admob-id

### ISSUE THREAD

**Issue by SSadlowski** [4ian/GDevelop#2295]
## Describe the bug
In Project Properties Screen, the example of admob App ID under the text entry field should be with ~ instead of / between XXXXXXXXXXXXXX and YYYYYYYY.

## Screenshot
![grafik](https://user-images.githubusercontent.com/78820674/107416993-6c46da00-6b15-11eb-9eca-ae6bf2d83c5d.png)

## Other Details
Version: GDevelop 5.0.0 Beta-105

**Comment by tristanbob** [comment]
For reference, both the IOS and Android instructions show that you are right (the "/" needs to be changed to "~"):

https://developers.google.com/admob/ios/quick-start
https://developers.google.com/admob/android/quick-start

**Comment by rockingrohit9639** [comment]
Hi There, I want to contribute to this project. Can you please guide me to this issue?

**Comment by rockingrohit9639** [comment]
Hi There, I want to contribute to this project. Can you please guide me to this issue?

**Comment by 4ian** [comment]
Please follow the README and dig in the codebase to find where this is :)

**Comment by ishansinghal9810** [comment]
is this issue still open actually i am also looking to getting started with the same issue :sweat_smile:

**Comment by 4ian** [comment]
If an issue is marked open and you can't see any PR for it, then yes it is.

**Comment by ishansinghal9810** [comment]
:+1:

**Comment by ishansinghal9810** [comment]
#2297 i have created up a pull request for the same please review it # #
