### ISSUE TITLE
The core isn't complete or compiled for b105 desktop

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2298]
## Describe the bug
In public b105 on desktop the libGD.js and gd.js aren't complete, normalize is missing.
Why I start my GD in local and compile the whole thing, normalize is usable.
Something miss on desktop or haven't yet updated on a distant lib.

## To Reproduce
1. Open desktop b105
2. Try to use normalize() expression
3. 
![image](https://user-images.githubusercontent.com/1670670/107491105-0301ae00-6b8b-11eb-834a-1f69126e5e77.png)

## Other details
* Only on Desktop for beta 105

**Comment by 4ian** [comment]
I think this is obsolete now?
