### ISSUE TITLE
No Email Verification when a user registers for android packaging

### ISSUE THREAD

**Issue by ishansinghal9810** [4ian/GDevelop#2299]
When a user tries to export the game to android we ask for an account and allow the user to create an account right these but a user can create an account with the wrong or not existing email address or with someone else's email address which is not used previously which can lead to a bypass of the limit of exports for android for free accounts

## To Reproduce
1. Create a sample project
2. Click on Export and then choose android
3. Scroll down and click on  Create an account and then enter any random email address
4. The account will be registered for you and you can use it

![Screenshot from 2021-02-10 15-09-03](https://user-images.githubusercontent.com/77291131/107492217-2c820000-6bb2-11eb-99e3-d9c67d578368.png)

I created this dummy account which I don't own even exists or not and the build is successful

## Other details
* Using Chrome and popOs
* Using GDevelop 5 and issue lies on both the web app and the desktop app as well
* I Don't know is it a bug or not but I think it will be good to open an issue 

If this is a valid bug I will be happy to fix it

**Comment by 4ian** [comment]
This is not a bug per se but maybe later we'll enforce email verification for accounts, that are handled by Firebase. I discourage creating too much accounts because otherwise you'll be flagged by Firebase spam detectors.
In the meantime, I think it's fine to keep it like this as long as there is no abuse.

**Comment by ishansinghal9810** [comment]
Ok so if you want we can close this issue or if you want it to be here for future reference

**Comment by 4ian** [comment]
I'll close for now to avoid cluttering the existing issues. Thanks :)
