### ISSUE TITLE
Old admob app id remains in project file

### ISSUE THREAD

**Issue by SSadlowski** [4ian/GDevelop#2301]
## Describe the bug
In Beta 104 there has been a change in handling the admob id. It is now possible to insert the Admob-App-ID for Android as well as the ID for iOs. In existing projects the Admob-ID had to be added again to the project. The old entry is not visible anymore in Game Properties but still reimains in .json Project File. It becomes visible when opening the project file via texteditor.

## Screenshot
![grafik](https://user-images.githubusercontent.com/78820674/107641647-26545800-6c74-11eb-9018-c9738bf3138e.png)

**Comment by 4ian** [comment]
Indeed, it's staying there - won't cause any bug but you might want to manually clean it.

**Comment by SSadlowski** [comment]
No that won't cause any bug, but something else with the new admob extension. See here: https://forum.gdevelop-app.com/t/compiled-android-apps-crashing-since-gd-5-0-0-beta-104/30508/3 I will open a seperate case if I find the problem...

**Comment by 4ian** [comment]
The old app id should be ignored by the updated admob extension. But it the new App id is not specified properly, you might get a crash at startup. In this case, I recommend opening the logs of the device (either in Android Studio "logcat" tab or by running `adb logcat` in a terminal) and starting the game. You can then see if in the (very verbose) logs, the information written during the crash.

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, could you please guide me?

**Comment by 4ian** [comment]
@85ayush You've just spammed dozens of issues with a similar message. This is not ok, and not a proper etiquette. You're free to help on anything by just submitting code through a Pull Request - please do some research about this. The documentation and README are already there to guide you - we won't guide every single person, you have to do it by yourself.

Please don't spam ever again the repository! Thanks.
