### ISSUE TITLE
GDevelop 5 trailer

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#2302]
Hello everyone ! I made a trailer for GDevelop 5 I hope this will be the official trailer.
Go check it out [on YouTube](https://youtu.be/6g4ucuPy4Rs) !

**Comment by 4ian** [comment]
Thanks for working on this :) Let's present it on the Discord/forum please, GitHub is only for technical discussion :)

**Comment by Bouh** [comment]
I've a already a trailer more complete i finish my bitmap object and the end of the beta with for publish it. Stay tuned!
