### ISSUE TITLE
Particle friction is not working.

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [4ian/GDevelop#2313]
## Describe the bug
The "Friction on particles" of the particles emitter object is not working.

## To Reproduce
1. Create a particle emitter using default settings.
2. Change "Friction on particles" to a larger number.
3. Preview the game, you can see that the particles are not slowing down.

https://user-images.githubusercontent.com/68310169/108294606-7e8ddb80-71d9-11eb-879b-021d0543cf76.mp4

## Other details

- Tested on GDevelop 5 Beta 105 (Desktop app and Web app)

**Comment by AlexandreSi** [comment]
Pixi does not support a friction concept for its particle emitter.
I think the best is to remove this parameter.
Any thoughts on this @4ian?

**Comment by 4ian** [comment]
Thanks for checking! Yes let's remove it, having it is creating more confusion than anything else.
