### ISSUE TITLE
Tilemap does not animate tiles when they are flipped/mirrored

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2314]
## Describe the bug
In Tiled you can flip any tile by pressing "x" or "y" and it will mirror the tile on that axis.  This works as expected for static tiles, but not for animated tiles.

I really expected this to be a limitation documented on the wiki here:
http://wiki.compilgames.net/doku.php/gdevelop5/objects/tilemap

But I didn't see it listed there, so I'm opening this a bug.

## To Reproduce
[tilemap-mirrored-animation-issue.zip](https://github.com/4ian/GDevelop/files/6005844/tilemap-mirrored-animation-issue.zip)
In my example you will see all the types of flipping labeled.
Only the non-flipped tiles are animated properly.
If you open "example.json" in Tiled you will see all the tiles animated properly.

## Other details
* Windows
* GDevelop 5.0 b105

**Comment by 4ian** [comment]
Sorry for the delay, and thanks for the game it was very useful and the solution was almost immediate :) 
I've fixed this for next version in 78914dc0044b25d7fee8adc85b31a8d63e621914. Animated rotated/flipped tiles will work like the non-flipped ones.
