### ISSUE TITLE
Yarn dialogue tree editor is misfunctionning

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#2319]
Hey!

Since beta 104 (and also b105), the Yarn dialogue tree editor bundled in Gdevelop is unusable. 

The issue happens when trying to edit an existing json file. To check on your own, you can try to create a new game from the example "dialogue tree" and try to edit the "npcs.json" file. 

Nodes aren't displayed, if you are lucky after scrolling a lot mouse wheel, you might catch a view of some arrow that should be visible between nodes, but nodes anret's visible, and so cannot be edited.

Here is a short clip, made by editing the json file from the bundled example: 
![yarn](https://user-images.githubusercontent.com/8144048/108610316-0c81e600-73d5-11eb-8611-9f1f4624f8b4.gif)

Same issue on every json files made with yarn with previous version in all my projects.

**Workaround : use the lasted "stable" yarn editor release, outside gdevelop: https://github.com/YarnSpinnerTool/YarnSpinner/releases/tag/v1.2.0**

**Comment by 4ian** [comment]
@blurymind Do you think we should update YarnSpinner again?

**Comment by blurymind** [comment]
Interesting, how do you reproduce this? It could be either the version or
the way its bundled

**Comment by blurymind** [comment]
We should update it again, but also make sure there isn't something wrong
with the bundling.

Do you get any console errors when this happens?

**Comment by 4ian** [comment]
> Same issue on every json files made with yarn with previous version in all my projects.

In theory we should be able to reproduce this using an example?

**Comment by blurymind** [comment]
The yarn json format hasn't changed at all, but I will try to reproduce
this. Maybe it doesn't happen when in dev mode?

**Comment by KinkGD** [comment]
Yes, I faced the issue for the first time with my own files. But the same
issue occurres with the json files frolm the example. You should probably
be able to reproduce it like explained with the example.

Just to be sure that it's not related to my computer, I just reproduced it
on my laptop (windows 10 too).

Le dim. 21 févr. 2021 à 11:31, Florian Rival <notifications@github.com> a
écrit :

**Comment by blurymind** [comment]
I cant reproduce this bug :(

**Comment by KinkGD** [comment]
How can i try to help you with it ?

**Comment by blurymind** [comment]
Well does it really crash on the example project? If not, please share the
project that does crash it

**Comment by KinkGD** [comment]
I edited my previous post, you probably missed it by email ^^ b106 is not impacted anymore.
But as i told before, on b105 and b104, every projects are crashing it. 

My gif in the initial post was taken from your original example.

**Comment by blurymind** [comment]
Ok so are you saying that gdevelop no longer has this issue and something
in the update fixed it?
Supposedly we can close the issue?

**Comment by KinkGD** [comment]
supposedly... yes.

Just re-tried last versions:
- b103 OK
- b104 KO
- b105 KO
- b106 prelease OK

Let's wait next stable release to confirme @4ian ?

**Comment by KinkGD** [comment]
No problem anymore with beta107, i'm closing this issue.
