### ISSUE TITLE
yarn dialogue bug

### ISSUE THREAD

**Issue by potato-gamer-coder** [4ian/GDevelop#2370]
when I click on an color, command or link/choice in yarn dialogue it type for the command "<< >> >>" instead of "<< >>"

## To Reproduce
1. Go to yarn dialogue
2. Click on a new node
3. Click on color, command or link/choice

* windows
* the latest version of GDevelop I'm using The desktop app
* Add any other context about the problem here.
* what it types
![Capture](https://user-images.githubusercontent.com/78294622/108627337-e460aa00-7409-11eb-9c5c-09af10871a9b.PNG)
what it supposed to type
![Capture2](https://user-images.githubusercontent.com/78294622/108627342-e88cc780-7409-11eb-8263-d78920e179eb.PNG)

**Comment by 4ian** [comment]
Seems like an issue that should be reported in https://github.com/YarnSpinnerTool/YarnEditor :) I'm closing as this is not directly linked in GDevelop.
