### ISSUE TITLE
Asset store submission: 286 music files from FreePD.com (entire main catalog)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2378]
## Notes

I paid FreePD.com to download their WAV files and then converted them to AAC using Free:AC + Fraunhofer FDK AAC encoder, with the quality setting to 3 (out of 5).  

~~There are 4 files that are 85-113 MB in size (due to long length).  The rest are under 15 MB, and most of the files are 5-10 MB.~~

## File

FreePDMusic.zip (~629 MB)
https://drive.google.com/file/d/1uzhKfTUNlM9fsKIeGTwDO2Gw5zhy5AFt/view?usp=sharing

## License

License:

This music is all licensed CC0 1.0 Universal Public Domain Dedication.
https://creativecommons.org/publicdomain/zero/1.0/legalcode
FreePD.com - 100% Free Music - Free for Commercial Use, Free Of Royalties, Free Of Attribution, Creative Commons 0

Artists: 

https://freepd.com/artists.php

**Comment by 4ian** [comment]
Thanks for submitting these! The licensing looks good. I might not serve from the asset store the biggest files because it's not reasonable to have musics that are more than a few megabytes - even 10 MB is pretty big (~5MB is okish for a game, 1-2MB is ideal).
I'll point the artist name link to the https://freepd.com/artists.php page :)

**Comment by tristanbob** [comment]
1. I am fine with removing the biggest files.  Can you add a max file-size on your guidelines? 

2. Do you want me to convert these using a lower quality setting to reduce their size?  (I have a choice of 1 to 5, these were done with 5)

**Comment by 4ian** [comment]
> Do you want me to convert these from WAV to AAC using a lower quality setting to reduce their size? (I have a choice of 1 to 5, these were done with 5)

Give it a try with 2 or 3 - if we can get a decent size reduction without much quality impact, it's a huge win. I've adapted the guidelines to explain this :) 

> Will the root folder "music" automatically be added as a tag? I hope so; it is useful to differentiate "music" from "sound effects".

Yes I can certainly keep it!

**Comment by tristanbob** [comment]
Here are some details on what those quality settings represent.  I expect that most music and sound effects will be stereo, so the maximum bit rate using quality=5 is 192 kbps.

"The bitrate limit for each variable bitrate mode. HE and HEv2 will often end up with actual bitrates far below these limits."

![Capture](https://user-images.githubusercontent.com/8879811/108737339-bf466700-74ef-11eb-9cb2-38dde4360b30.PNG)

http://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC#Bitrate_Modes

**Comment by 4ian** [comment]
Let's split in half and use Level 3? I've read that 64 kbps should fit most listeners, but for games 48 kbps stereo is surely fine.

**Comment by tristanbob** [comment]
I found this site helpful in understanding what each bitrate sounded like. 

http://nigelcoldwell.co.uk/audio/

I agree the quality setting of "3" (2x48=96 kbps) provides a very high-quality sound.  I am not an audiophile, but I only noticed a reduction in quality when listening to the 56 kbps AAC file (specifically the snare drum on the last song). 

Caveat:  This site uses an AAC codec from a 2008 version of iTunes with a Constant Bit Rate.  The modern codec I used (Fraunhofer FDK AAC encoder) and Variable Bit Rate should perform as good or better.

I will re-encode the WAV files tonight using a quality setting of 3 and update my link.

**Comment by 4ian** [comment]
Sounds good, thanks!

**Comment by tristanbob** [comment]
I have updated my download link above with the new Zip file.  I went ahead and removed the 4 super large files.  The largest file is now ~7 MB, and the average size is ~2 MB (623 MB / 286 files).

**Comment by 4ian** [comment]
Thank you! It's on my todo, this will be great addition to the store :)

**Comment by 4ian** [comment]
Added :) This makes me think that this is for now only accessible in the web-app. I have to make the resources accessible from the desktop app too.
