### ISSUE TITLE
Updating the Center and Origin Points break collision mask positioning.

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2379]
## Describe the bug

When you update an object's center point, origin point, or both, the hitbox is impacted, but not 1:1 (as far as I can tell).
The user has no way to know where this new hitbox will be, either.

- What I would expect to happen:
    - The hitbox remains accurate to how it appears, position wise, in the hitbox editor.
- What actually happens:
    - The hitbox appears to move somehow based off the other points moving, but not 1:1, almost like it's being skewed based off the origin point vs the center point.

This came up on the forums back in May 2020, but it doesn't look like we ever had a bug report filed on it:  https://forum.gdevelop-app.com/t/sprites-with-modified-points-do-not-collide-correctly/24785/7

VegaTato on the discord brought this back up, and I was able to reproduce it.

## To Reproduce
1. Create two objects.
2. Update the center and/or origin points of one object. E.g. move the center to the left.
3. Set up events to test for collision between unmodified object1, and modified object2.
4. Preview the game and have object1 try to collide with object2. Object1 will be able to move a portion of the way into object2 before collision is detected,

Here's some screenshots. The hitbox is not modified and is the full size of the object.
Events:
![image](https://user-images.githubusercontent.com/24237149/108653775-f3d50700-748c-11eb-8270-108909c8e423.png)

Points on modified object: 
![image](https://user-images.githubusercontent.com/24237149/108653792-ff283280-748c-11eb-8d74-98f24a95ed52.png)

Touching the object, no collision detected:
![image](https://user-images.githubusercontent.com/24237149/108653733-e0c23700-748c-11eb-913b-074ab1a19da0.png)

Collision finally detected:
![image](https://user-images.githubusercontent.com/24237149/108653751-e9b30880-748c-11eb-8e90-5e56aa99b435.png)

Example project:
[PointCollisionIssue.zip](https://github.com/4ian/GDevelop/files/6019385/PointCollisionIssue.zip)

## Other details
* Windows 10 Pro
* B105

**Comment by Silver-Streak** [comment]
Some other notes:

This *seems* like it should have been directly fixed by https://github.com/4ian/GDevelop/pull/719, but definitely is not fixed. 

It also seems like it'd be fixed with this: https://github.com/4ian/GDevelop/commit/7d7bde12d0a3e7e1e775f9e83e98146d2f83a0d1#diff-d16728c52bfa385890eba30ddc08ba22R77-R83 but is not.

It also seems like it could be related to here, but this doesn't seem to indicate any change around collision boxes: https://github.com/4ian/GDevelop/issues/1194

**Comment by 4ian** [comment]
That's weird indeed, let me double check that.

**Comment by 4ian** [comment]
There is indeed a bug where moving the center will sometimes dismiss collisions. I'll fix that asap.

**Comment by 4ian** [comment]
Thanks for the game to reproduce the error, it was very very useful 👍

**Comment by Silver-Streak** [comment]
> Thanks for the game to reproduce the error, it was very very useful 👍

Glad we could figure it out, it slipped my mind after seeing it on the forums.
