### ISSUE TITLE
OR not selecting all object's instances if the true subcondition is not related to the object

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GDevelop#241]
As said in http://forum.compilgames.net/viewtopic.php?f=20&t=7449, the OR condition has some defects.

Consider an event with an OR condition with one of its subcondition related to an object and another not. If the event is executed because of the second one (and the first one is false for all instances of the object), none of the object instances are selected and the actions related to this object will not act on any of the instances. 

**This should not be the case : as the event is executed because of the second condition, the list of object's instance should not be restricted and the action should act an all instances.**

I attached an example : In the "ORCondition" scene, if the variable everything is = 1, all instance of TextObject should be set to "TRUE" but its not the case.

[AdvancedConditionsBugs.gdg.zip](https://github.com/4ian/GD/files/93087/AdvancedConditionsBugs.gdg.zip)

**Comment by victorlevasseur** [comment]
Bump

**Comment by 4ian** [comment]
I've not the time to look at it now - working on another feature right now. Code generation would need a bit of clean up to properly handle all case and being simpler at the same time.
