### ISSUE TITLE
ForEach() does not include objects that were created the same frame (when using an Extension function)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2414]
## Describe the bug
ForEach() does not include objects that were created the same frame (when using an Extension function)

## To Reproduce
See project file.  Includes a test using normal events (no problems) and a test using an extension function (causes problem).

## Live Game
https://games.gdevelop-app.com/game-959d24dc-50bd-4d65-9fdd-47e0acee60c4/index.html

## Project files
[ChainOfObjects-BugTest.zip](https://github.com/4ian/GDevelop/files/6097829/ChainOfObjects-BugTest.zip)

## Video
https://user-images.githubusercontent.com/8879811/110252697-e6675480-7f43-11eb-88da-0014d8e1c1e8.mp4

**Comment by arthuro555** [comment]
The issue seems to be coming from the fact that `runtimeScene.getObjects` return always the latest objects list including the newly created objects, while eventsFunctionContext returns the objects from when the events function was called, before creating the objects. Not sure if it is intended behavior or not.

**Comment by 4ian** [comment]
> The issue seems to be coming from the fact that `runtimeScene.getObjects` return always the latest objects list including the newly created objects, while `eventsFunctionContext.getObjects` returns the objects from when the events function was called, before creating the objects. Not sure if it is intended behavior or not.

Correct. I think we should: 
1. Update createObject so that we add the created objects to the objects lists passed as parameters.
2. Remove the optimization that precompute object arrays for the `eventsFunctionContext.getObjects`. I'm not even sure it's that useful.

**Comment by tristanbob** [comment]
Thanks for fixing this so fast, guys!  This was holding me back to finish this object chain extension.  :)

**Comment by tristanbob** [comment]
I can confirm that the nightly build has this fix and it works as expected.
