### ISSUE TITLE
Asset store submission - GrafxKid

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2419]
Assets:
[GrafxKid.zip](https://github.com/4ian/GDevelop/files/6101185/GrafxKid.zip)
Character Pack 1 - 7
Mini FX, Items & UI

Trello card: https://trello.com/c/WgXv6gB5/35-grafxkid

**Comment by 4ian** [comment]
Thanks! The license is not clear on the Trello card, can we clarified what license this was placed under by the author, or ask them? :)

**Comment by Entr0py404** [comment]
Its CC0 1.0
When I emailed him he said because I was unsure he said "I'm okay with this, as long as my free sprites are forever free. And if possible, link to my grafxkid.itch.io page"
But then I downloaded his art and it says 
License:
GrafxKid’s publicly released pixel art assets fall under the CC0 1.0 Universal Public Domain License.

CC0 1.0 terms - https://creativecommons.org/publicdomain/zero/1.0/

**Comment by 4ian** [comment]
Ok if the license bundled with the assets is CC0 1.0 and the author confirmed he's also fine with this distribution, this should be good :) 

Nitpicking, when a folder contains only a single object and has the folder has the object name, you can move all the object files in the parent folder.
<img width="611" alt="Moving files" src="https://user-images.githubusercontent.com/1280130/110451703-5ef12100-80bc-11eb-8bb1-412353ed52af.png">

**Comment by Entr0py404** [comment]
[GrafxKid (With Fix).zip](https://github.com/4ian/GDevelop/files/6109684/GrafxKid.With.Fix.zip)
Understood because folders will create tags folders for single objects will create undesired tags.
I noticed I did this the other day with pixel adventure pack's fruits folder.
![Screenshot 2021-03-09 083605](https://user-images.githubusercontent.com/75917656/110497568-ce164780-80b3-11eb-9244-28c5aef450c6.png)

**Comment by Entr0py404** [comment]
Should I do it to the Character Packs as well?

**Comment by 4ian** [comment]
Let's keep the characters separated as they can have their own objects/FX :)

**Comment by 4ian** [comment]
Added to the asset store! Thanks for this high quality submission 👍👍 And for checking with the artist that it's ok to have their available :)
