### ISSUE TITLE
Freeze when changing object animation number in properties panel

### ISSUE THREAD

**Issue by Oneil974** [4ian/GDevelop#2423]
## Description
I got a freeze when I change the animation number of some object
There are some error on console too

## How to Reproduce
1. Drop an object with multiple animations
2. Click on the object
3. Change the number of animation

## Other details
* I use a custom build of GD about 3 days
* I use windows 10
![gd_error_animation_number_2](https://user-images.githubusercontent.com/11059074/110603198-304c7680-81a0-11eb-8fb2-fb34f92ff9a1.jpg)

**Comment by 4ian** [comment]
Thanks for reporting and including that you're using a custom build, this was an important information :) 
This is indeed something that was solved very recently: https://github.com/4ian/GDevelop/commit/975fa7e2b7a082f065d34d17d2dec4afe53f7d00

It should work if you get the build from the latest version of the `master` branch.

**Comment by Oneil974** [comment]
Oh ok sorry I'll try a new build.

Thanks
