### ISSUE TITLE
Foolproofing GDevelop

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2429]
I just looked at a beginner's project, and there were so many issues with it...
First, a ton of unused resources. These show up red if you know the ctrl-shift-i trick, but otherwise, you won't know about them until you try to export.
Second, an object with animations of different sizes. We know this causes issues, so why not prevent it, or warn?
Third, an animation with no hitbox. Custom hitbox was set, then removed. But the button to reset the default hitbox was not pushed. This triggered preview freeze/crash.
Hopefully, we can do something about these.
Unused resources could be removed automatically, no? Or perhaps we could color the "Resources" tab in red to attract attention to it, when there are such unused resources?
And the OK button could be greyed out if an animation doesn't have any hitbox. What do you think? 🤔

**Comment by 4ian** [comment]
> Second, an object with animations of different sizes. We know this causes issues, so why not prevent it, or warn?

It depends on what kind of issue, but we could add a hint (message on screen) if the object has the platformer behavior. 

> Third, an animation with no hitbox. Custom hitbox was set, then removed. But the button to reset the default hitbox was not pushed. This triggered preview freeze/crash.

That's a bug to fix. We should revert to the default hitbox.

> Unused resources could be removed automatically, no? Or perhaps we could color the "Resources" tab in red to attract attention to it, when there are such unused resources?

Not that easy, but I think it would be more a way to tell that they are unused resources in a "Diagnostic Report" that would give you this kind of messages, as well as malformed events.
We could also indeed create a visual effect (red color, icon...) to attract the user attention on this - but we need to keep in memory this kind of "diagnostic report" to do so.
