### ISSUE TITLE
New Physics 2.0 actions: "Apply force in a direction" and "Apply impulse in a direction"

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2433]
## Description

When Physics 2.0 forces are not being used, game devs can specify which direction a force should be applied.  This action is called "Add a force (angle)".

![Screenshot 2021-03-14 132521](https://user-images.githubusercontent.com/8879811/111081445-027d6f80-84c9-11eb-8d91-b14e4abb09dc.jpg)

When using Physics 2.0 forces, there is no equivalent action.

![Screenshot 2021-03-14 132431](https://user-images.githubusercontent.com/8879811/111081466-1923c680-84c9-11eb-8d33-98f00e2c3a1c.jpg)

## Solution suggested

Create two new actions:

~~- [ ] Apply force in a direction~~
~~- [ ] Apply impulse in a direction~~

**Comment by 4ian** [comment]
That should be the "polar" force/impulse. We can rename them to `Apply impulse/force (angle)` maybe as it's currently not obivous what they do?

**Comment by tristanbob** [comment]
Wow, I should have looked closer.  I assumed those actions were for rotational forces, but that is Torque.  I agree, some wording changes would help people like me.

- Apply polar force => Apply force in a direction (angle)
- Apply polar impulse => Apply impulse in a direction (angle)
- Apply torque => Apply rotational force
- Apply torque => Apply rotational impulse

(I'm not sure if we can offer both an impulse and force, because there is currently only one action for Torque)

**Comment by 4ian** [comment]
> (I'm not sure if we can offer both an impulse and force, because there is currently only one action for Torque)

This is called Apply angular impulse. I'll update this too.

**Comment by 4ian** [comment]
Should be good now!

![image](https://user-images.githubusercontent.com/1280130/111086370-ac81e980-8513-11eb-9757-c85712d34058.png)
