### ISSUE TITLE
[$45 bounty] Empty while block stuck loading game 

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2437]
## Describe the bug
An empty while event in an empty project crash the game.
I can't see errors in debugger or console because i think there is an infinite loop.
So here the code from the temp folder:

```JS
gdjs.New_32sceneCode = {};
gdjs.New_32sceneCode.stopDoWhile2 = false;


gdjs.New_32sceneCode.conditionTrue_0 = {val:false};
gdjs.New_32sceneCode.condition0IsTrue_0 = {val:false};


gdjs.New_32sceneCode.eventsList0 = function(runtimeScene) {

};gdjs.New_32sceneCode.eventsList1 = function(runtimeScene) {

{


gdjs.New_32sceneCode.stopDoWhile2 = false;
do {if (true) {
if (true) {

{ //Subevents: 
gdjs.New_32sceneCode.eventsList0(runtimeScene);} //Subevents end.
}
} else gdjs.New_32sceneCode.stopDoWhile2 = true; 
} while ( !gdjs.New_32sceneCode.stopDoWhile2 );

}


};

gdjs.New_32sceneCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();


gdjs.New_32sceneCode.eventsList1(runtimeScene);
return;

}

gdjs['New_32sceneCode'] = gdjs.New_32sceneCode;

```

![image](https://user-images.githubusercontent.com/1670670/111186862-b9561a00-85b3-11eb-8837-cc8b7db8836c.png)

## Other details
* b105, b106
[Source: forum](https://forum.gdevelop-app.com/t/empty-while-block-stuck-loading-game/31343)

**Comment by arthuro555** [comment]
As I said on the forum this is intended behavior. No conditions means always in GDevelop, and 4ian said before that [events without actions should be kept](https://discord.com/channels/258623956158906368/644542295248470046/779683629319847966), so this is intended to be literally `while(true) {}`. 

While I agree with slash's proposition on the forum to display a warning when not putting any condition about not being able to break out of the loop, i wouldn't label this a bug but a small convenience enhancement

**Comment by Bouh** [comment]
In this case it is a blocking behavior that makes the game unusable.
Even if it is intended by the user to add an event, it can be forgotten.
The user doesn't delete it and the game doesn't run anymore.
This is both the user's fault for not paying attention, and the engine's fault for not escaping unnecessary things.

**Comment by Bouh** [comment]
Whether it's a bug, an oversight, a missing feature or a misunderstood feature. Here it is unusable and blocks the user. 
The solution is not a new diagnostic feature but the escape of the empty  ​while events.

**Comment by 4ian** [comment]
While this works "as designed", I'm fine if we add a special case "do not generate any code" in case of an event that would be entirely empty (no while condition, no conditions and no actions), as I agree this is surprising.

**Comment by 4ian** [comment]
Bounty added! :)
