### ISSUE TITLE
Submitting a game example, to recreate a combat system similar to the game Titan Souls.

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#2438]
Hi, local goof-ball here. ;)

  I'd like to submit a new example to be added to GDevelop. 
  
  It's a top down action boss fight that includes events, explanations, and examples of the following:
  -Dash
  -Pick up and throw an object
  -Health bars
  -Top down controls and collisions
  -Top down Z-ordering
  -Particle effects
  -Hidden objects and modified collision boxes
  -Sound effects

  All art and sound effects were created by me, and therefore; 
  I confirm that any assets can be used freely by anybody, including for commercial usage.

Hope someone finds this example useful,
HelperWesley. ;)

[Titan Souls game example By HelperWesley.zip](https://github.com/4ian/GDevelop/files/6150366/Titan.Souls.game.example.By.HelperWesley.zip)

**Comment by Silver-Streak** [comment]
This looks rad...but as a heads up I think the approvers need the project files, not the compiled game. 😄

**Comment by HelperWesley** [comment]
I didn't realize lol. Here's the original folder zipped instead.

[Titan Souls game example By HelperWesley (2).zip](https://github.com/4ian/GDevelop/files/6152507/Titan.Souls.game.example.By.HelperWesley.2.zip)

**Comment by 4ian** [comment]
Nice! I think we could make the boss a bit faster to give a bit more challenge - and also at the same time have the rock make more damage. Currently I have a feeling it's not too difficult, but fairly long?

**Comment by HelperWesley** [comment]
That's fair. Let me tweak the speeds and damage a bit.

**Comment by HelperWesley** [comment]
Ok, so now:
-Boss takes 5 hits to kill, no5 10.
-Player dies in 3 hits, not 5.
-The boss falls and rises faster.
-The boss only spends 0.5 seconds on the ground instead of 1 second.
      (So you have 0.5 second window to hit the boss instead of a full second)

I didn't want to make the example game too complicated, so I made the boss stationary. Would you prefer it moved around the scene? I just felt like that would be too complicated for an example game.

[Titan Souls game example By HelperWesley(3).zip](https://github.com/4ian/GDevelop/files/6152932/Titan.Souls.game.example.By.HelperWesley.3.zip)

**Comment by arthuro555** [comment]
I optimized the events a bit, here is the optimized version: [Titan Souls game example By HelperWesley optimized.zip](https://github.com/4ian/GDevelop/files/6212378/Titan.Souls.game.example.By.HelperWesley.optimized.zip)

Overall I think it is a good example, I would add a bit more "polish"/game feel elements though:
- The boss should have a health cooldown, else it can be spam hitted and killed almost instantly
  - You could add one to the player as well, though it isn't 100% necessary thanks to the trigger once on the hit condition
  - Maybe while the cooldown is happening you can use the flash extension to give a visual clue?
  - You could use the Health behavior, it does hit cooldown for you out of the box and showcases usage of extensions.
- You could maybe add a camera shake when it hits the ground to make his crushing more impressive
- You could add a knockback when the player is hit
- You could try to clamp the camera to not go "out of bounds"

**Comment by HelperWesley** [comment]
Well then..... now I think I might take 1 more crack at it and make it a little something more. 👍

Thanks for the optimization changed and suggestions @arthuro555

**Comment by HelperWesley** [comment]
Alright, took a little longer than I thought, and I added a little more than I thought.

But here's the new Titan Souls example game with added feature:
-2 More stages to the boss fight
-A couple tiny bug fixes
-Some screen shake
-Damage Cooldowns for the boss so they can't take more than 1 shot per time on the ground.
-A respawning health restoring pick up
-And Improved visuals(lol)

[Titan.Souls.game.example.By.HelperWesley.optimized.By.Arthuro.And.Reworked.By.HelperWesley.zip](https://github.com/4ian/GDevelop/files/6225467/Titan.Souls.game.example.By.HelperWesley.optimized.By.Arthuro.And.Reworked.By.HelperWesley.zip)

**Comment by HelperWesley** [comment]
Going to do 1 final thing(For real this time)

I'll make the bosses shadow effect things is passes over. And then it'll really be the final version. 👍

**Comment by HelperWesley** [comment]
Alright, this is the last version.

Update:
-Shadow. (lol)

Genuinely though, I think this game example could be useful for people who want to make games like these using Gdevelop. I've gone through the events and added comments to everything, and @arthuro555 has gone through and optimized the events to improve performance. Showcasing mechanics, and some best practices within the engine.

And as a side note:
There are tonnes of examples of platformer games, or top down phone games, but this showcases something more that can be made using Gdevelop and might encourage more people to pick up/stick with the engine as well.

I hope you guys think this example game is worth adding to the list. @4ian @Silver-Streak 👍

[Titan.Souls.game.example.By.HelperWesley.optimized.By.Arthuro.And.Reworked.By.HelperWesley.zip](https://github.com/4ian/GDevelop/files/6244700/Titan.Souls.game.example.By.HelperWesley.optimized.By.Arthuro.And.Reworked.By.HelperWesley.zip)

**Comment by 4ian** [comment]
Looks great! I'll add to the list of examples, it's a great one.

**Comment by arthuro555** [comment]
If I may, i think before adding it a little resource cleanup is necessary. There are some unused leftover resources and i see a lag spike when the boss first hits the ground, i suspect it is because the sound played at this moment is not preloaded.

**Comment by 4ian** [comment]
Giving you or @HelperWesley the opportunity to do that then? And i'm adding it afterwards :)

**Comment by arthuro555** [comment]
Here is the project with the cleanup and audio preloading: 
[Titan Souls game example By HelperWesley cleaned up.zip](https://github.com/4ian/GDevelop/files/6251717/Titan.Souls.game.example.By.HelperWesley.cleaned.up.zip)

**Comment by 4ian** [comment]
Added in 515308ed9dff06c33e759218ecec89a6274891a6! Thanks both for your work on this, great example! 👍
