### ISSUE TITLE
gdevelop fails npm start on linux

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#2439]
## Describe the bug
After building master app, I run npm start as usual and get 
`runtimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -s ASSERTIONS=1 for more info.`

Manjaro linux
## To Reproduce
1. On manjaro linux, nodejs 10 dubnium, run npm start after npm install in newIde/app

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

**Comment by 4ian** [comment]
Is this in the terminal or in the browser? Can you try to upgrade to Node.js 12 or 14?

**Comment by blurymind** [comment]
Compiles fine in terminal. Fails to load in browser.  Will give it a try

**Comment by 4ian** [comment]
Actually the error message seems to indicate that the server returns a "404" when it tries to load libGD.js: https://github.com/WebAssembly/spec/issues/1031

Can you try remove node_modules, and npm install again? Can you check the content of newIDE/app/public, and confirm there is a libGD.js and a libGD.wasm file?

**Comment by blurymind** [comment]
Tried it and also tried upgrading to node 14, still no luck
![problem](https://user-images.githubusercontent.com/6495061/111686507-0e4a9800-8821-11eb-99a1-b4fb635eb722.png)

**Comment by 4ian** [comment]
Can you paste here the full output of `npm install`? I'm searching for the lines confirming libGD.wasm was downloaded.
Can you paste here too the content of the newIDE/app/public folder?

**Comment by 4ian** [comment]
Ok I found the issue, fixed in #2448. Sorry for the time loss! You can now pull master and it should work after a npm install.
Don't forget to check all that I'm asking in my messages ("confirm there is a libGD.js and a libGD.wasm file"), that could have speed up the fix ;)

**Comment by blurymind** [comment]
That fixed it, thanks :)
