### ISSUE TITLE
Day & night cycle using a layer effect example

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2440]
A day & night cycle using a layer effect example

[Day and night cycle with layer effect.zip](https://github.com/4ian/GDevelop/files/6280706/Day.and.night.cycle.with.layer.effect.zip)

**Comment by Midhil457** [comment]
Hi, I just reviewed the project. It works great! But, I did find some problems

- The object variable "LNopacity" isn't a great name for a variable as it doesn't tell it's use. Maybe changing it's name that better suits it's name

- A text object that tells the time left till Day and Night could be useful as it can show people how they can add something similar to a clock system in their game. And it could also help show that the example works, as I first thought the project was broken as it didn't change to night.

:)

**Comment by Entr0py404** [comment]
LNopacity is the layer effect name abbreviated light night and the value that's being changed is opacity.

How about LightNight_opacity.

For the second one that would require using a different system entirely, based off of time delta.

It being an example the user is expected to look at the coding. one glance will show that it has timers in it and, the name also implies it as well being day and night cycle.

**Comment by Midhil457** [comment]
> How about LightNight_opacity ?

That should be fine!

> Maybe a on scene text note would be suitable ?

That would also be fine! 

:)

**Comment by Midhil457** [comment]
Also, (I forgot to add it in the last message. I know it has been a month 😅)

I found that you can do the same thing with just one timer instead of two. I don't know if it makes any difference other than using less events

![Timer](https://user-images.githubusercontent.com/73597906/117531418-feb92580-afff-11eb-838f-69092977a10b.png)

:)
