### ISSUE TITLE
Beta 106: Raycasting Stopped Working, not sure why.

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2450]
## Describe the bug
First off, I am sorry there isn't a lot of information with this issue. I am still trying to track down what is causing the issue and have yet to be able to replicate the results in a new project.

I updated GDev to 106 and noticed our enemies that use raycasting had stopped working, at first I thought I might have accidently changed something since the previous build (of the project) however the code remained the same. I reverted back to 105 and the enemies worked again.

The issue is it's as if the ray cast isn't detecting what it should be "seeing", and no results are being stored. I tried replicating the two objects in a fresh project with any extra code stripped out and it works fine (which is quite annoying). I then tried disabling all of the Logic for the enemies that use the raycasting in the real project and just use the basic example from the test project but it was still failing to work.

I went as far as replicating the hitboxes, and points for the two objects, having the events in an external event, using an external layout in the test project and still it disappointingly worked.

As this project is under NDA, I can only share so much at this point, however everything relevant should be below.

## Enemy Code:
`If it see's the player, it updates it's _canSeePlayer var to 1, otherwise it's 0.`
`If it's _canSeePlayer var is 1, tint RED.`
`If it's _canSeePlayer var is 0, tint WHITE.`
*_obj_enemies is a group of enemies._
*_The currentDirection is just to change the angle of the Ray Angle._
*_Detection is for the hitbox not the model visible._
*_I have tried making the hitbox visible in 106, no change._
![](https://i.gyazo.com/1877b3b06654a4781b00d2b117638335.png)

## Build 105
![](https://i.gyazo.com/40c879ae683dc9072108e3e9ffb712b5.gif)
_Works perfectly_

## Build 106
![](https://i.gyazo.com/97377295fedd4e5482667974f532a74d.gif)
_No detection at all. No var being stored in raycastingPosX/raycastingPosY_

## Test Project Build 106
![](https://i.gyazo.com/ae16b19b76bca5e3bb8202017495da5d.gif)
_Replicated the object group, the hitbox, the enemies, the points on the two objects and have the code at the most basic level._

## Test Project Build Code
![](https://i.gyazo.com/b3e9e31cbd3106cbde1afdddd7349cab.png)

## Moving the Test Project Code Into Real Project
![](https://i.gyazo.com/3239a4afa6232dd60c2107df72fe6d58.gif)
_Reverting back to 105 does have this test code working in the real project._

## Hit Boxes & Points
The obj_player_hitbox uses the default hitbox and the below points.
![](https://i.gyazo.com/3b3289f83ba55160b8b760df33e77df5.png)

The chainsaw model uses the below hitbox and points.
![](https://i.gyazo.com/2e7c0c488a69bdff6d0f3cb9a17df3e3.png)
![](https://i.gyazo.com/58e7461044a19fd833eaa8aa4fe62c5a.png)

At this point I am not sure what could be causing this issue and it's quite annoying that the test project is working... I know there was an update to raycasting in 106 "Fix collision (and raycast) not always triggered with sprite having a non default center." but I am not show how this would break even the basic test.

Any thoughts/ideas would be great.

**Comment by 4ian** [comment]
Interesting, the fix of raycast should not have been breaking stuff like this (and as you said the example project is working), so it's weird...
Is there a way you can add actions to see if the raycast condition is working? I'm afraid that it would work but the rest of the events would make it look like it did not (even if as you said it's working in the previous version).

**Comment by 4ian** [comment]
Also, what if you try to copy the exact objects that you have in the test project? Maybe there is a configuration (like corrupted hitboxes or weird point positions), that would make the condition fail?

**Comment by ddabrahim** [comment]
it seems to me if you cast ray to position of group and check the ray against a group is kind of broken in 106.
I have modified the basic pathfinding example, added 5 different enemy tanks in a group and cast ray from the position of the group, against an other group and in 106 it is sometime works, sometime don't, very difficult to reproduce. One time IA may never move, an other time IA5 never move, an other time IA and IA5 move only if you get further away but does not move if you are closer to them or they randomly stop when they are not supposed to.
Have no idea what is happening but I think it got something to do with casting ray from object groups and test against an object group.

If I open the same project In 105, it works perfectly all the time.

Here is the modified project I tried and kind of broken in 106:
[RayCastTest.zip](https://github.com/4ian/GDevelop/files/6172717/RayCastTest.zip)

**Comment by 4ian** [comment]
Very nice @ddabrahim, thanks for this augmented example. I'll take a look then to see what's happening.

**Comment by AtomicCrocStudios** [comment]
> it seems to me if you cast ray from position of group and check the ray against a group is kind of broken in 106.
> I have modified the basic pathfinding example, added 5 different enemy tanks in a group and cast ray from the position of the group and test against an other group. In 106 it is sometime works, sometime don't, very difficult to reproduce. One time IA may never move, an other time IA5 never move, an other time IA and IA5 move only if you get further away but does not move if you are closer to them or they randomly stop when they are not supposed to.
> Have no idea what is happening but I think it got something to do with casting ray from object group and test the ray(s) against an object group.
> 
> If I open the same project In 105, it works perfectly all the time.
> 
> Here is the modified project I tried and kind of broken in 106 but works perfectly in 105:
> [RayCastTest.zip](https://github.com/4ian/GDevelop/files/6172717/RayCastTest.zip)

Thank you for looking into it ddabrahim and providing a bit more info other then the "it's not working" post I made :D

**Comment by 4ian** [comment]
Fixed :) An error in the raycasting logic would make them fail for certain coordinates. You should be able to get the link to the nightly builds that will be built soon with the fix:

* [Windows](https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop 5 Setup 5.0.0-beta106.exe)
* [macOS](https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop 5-5.0.0-beta106-mac.zip)
* [Linux](https://gdevelop-releases.s3.amazonaws.com/master/latest/gdevelop-5.0.0-beta106.tar.gz)

Let me know if it works better :)

**Comment by ddabrahim** [comment]
It did fix the problem on my end :)
Thanks a lot 👍

**Comment by AtomicCrocStudios** [comment]
I can also confirm that this latest version fixed the issue in the real project. Thank you for the quick fix @4ian !
