### ISSUE TITLE
b106 - Raycasting regression

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2458]
## Describe the bug
Ugh... this one made me think I was losing my mind. I was able to make a simple looking demo, but I can't figure out what combination of things is causing this regression (it's new to b106 and does not happen in b105).

Imagine a platformer game where you want to determine which surface you are walking on.
I've implemented this using groups to represent the types of platforms and I raycast from the bottom of the player when it is "on the floor" to match against those groups.
Since the player object is often on the floor the surface detection from the raycast should be fairly accurate and responsive.
Starting in b106 it's just unreliable and intermittent.

The multiple groups is somehow important I think.

## To Reproduce
[RaycastRegression.zip](https://github.com/4ian/GDevelop/files/6178494/RaycastRegression.zip)
I recommend loading in b105 first to see how accurate and reliable the surface detection is.
Essentially it's a basic platformer with three types of platforms: Ground, Ice, Wood
There are two object groups:
Platforms: Ground, Ice, Wood
JumpThrus: Ice, Wood
Their behaviors map logically to the groups.
The demo above has two text monitors at the top for indicating if the player object is on the floor or not as well as what surface the player is currently standing on.
The surface is determined using two ray casts whenever the player is "on the floor"
The first is against the "Platforms" group the second against the "JumpThrus"
Both raycasts are done from the center of the player's X and the player's Y + player's height, at 90 degrees for 16 pixels... so straight down from the center of the player's feet.
Uses the default controls (so arrow keys / space bar)

In b106 walking along the bottom will sometimes update the surface between ground / wood / ice... and sometimes not. Jumping onto a new surface will typically update the first time, but not the next time.
It's REALLY weird and BROKEN.

## Other details
* GDevelop 5.0.0 b106
* Windows

**Comment by 4ian** [comment]
Sorry about the time lost! :( 
It's fixed already: https://github.com/4ian/GDevelop/issues/2450

I'll make a new version in the next days.
Meanwhile, use the nightly build:

* [Windows](https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop%205%20Setup%205.0.0-beta106.exe)
* [macOS](https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop%205-5.0.0-beta106-mac.zip)
* [Linux](https://gdevelop-releases.s3.amazonaws.com/master/latest/gdevelop-5.0.0-beta106.tar.gz)

**Comment by krunkster** [comment]
Doh! Next time I'll search the closed issues as well as the open issues.
