### ISSUE TITLE
My Game Was Not Run In Mobile 

### ISSUE THREAD

**Issue by prantkeshari677** [4ian/GDevelop#2461]
![Screenshot_2021-03-22-15-34-14-40](https://user-images.githubusercontent.com/76613399/111976278-75b95e00-8b27-11eb-83bf-5e71250dccae.jpg)

I Made A game in gdevelop .
and then I export them for android, 

and install them on android mobile, this app is installed successfully, and also an icon of this app is shown.
but  
when I click on this app, it did not open (nothing happen), 
then I try many time for opening the app,
After 4-5 times trying, one pop-up message is shown (see my first attachment).

 
and then I think this is a problem of my mobile
, so I install them on another mobile.

and this problem is also shown on another mobile.
but when I export this game for our laptop (window), he runs successfully.
plz, solve this problem.

Game Link - https://builds.gdevelop-app.com/c4e37d05-fdcb-4d12-a5cd-4f9913150922/game.apk

Android Phone use by Me - 
Name - Realme Narzo 20 Pro
Version - Baseband & Kernel
Version - 10
Processor - HelioG95
Ram - 6.00 GB

Gdevelop info -
Gdevelop 5 (desktop version)

**Comment by Bouh** [comment]
Hello
I can't install it on my phone, did you have added some options or configurations in cordova or something else (permissions, ads, external code, etc...)?
Can you try a new export on the androir build service?

**Comment by prantkeshari677** [comment]
i Am 

> Hello
> I can't install it on my phone, did you have added some options or configurations in cordova or something else (permissions, ads, external code, etc...)?
> Can you try a new export on the androir build service?
> If you can and if you want we can take a look on the project file (game.json) if needed to be sure.

I Am Not Sure, but I try for displaying ads in my game and I try some time by different method. but I am not success .
And I am not know how to resolve this problem(like some changes in game do by me, I Not know what I do in Cordova(etc),but I know (I do Change in program file))
and I export this game more than 9-12 time.
Yes I want because I am not professionalism (I am Only Student).
so plz solve this problem .
If You Have Any Question.
PLz Tell Me

**Comment by prantkeshari677** [comment]
Can Anyone Reply me?😒
