### ISSUE TITLE
ToJSON expression return the wrong value.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2472]
## Describe the bug
jumpingj noticed a bug with the new version 107.
With the ToJSON function empty string fields are stored in the Json with “0”. So, I expect “” and instead I read “0”

Bouh:
Is there unit test to check that?

## To Reproduce
![image](https://user-images.githubusercontent.com/1670670/112719440-5476ba00-8ef9-11eb-9034-03aa0a73c06e.png)
![image](https://user-images.githubusercontent.com/1670670/112719446-58a2d780-8ef9-11eb-9964-191755de7b58.png)

[Original report on forum](https://forum.gdevelop-app.com/t/vers-107-bug-json-trasformation/31597)

## Other details
* b107

**Comment by 4ian** [comment]
> Is there unit test to check that?

I don't think, and we should totally add one :) I'm looking at this
