### ISSUE TITLE
Sound playback behaves oddly when at reduced volumes - Started sometime after b105

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2490]
## Describe the bug
When rapidly playing a sound at a reduced volume (~10%), the volume will glitch momentarily to be max volume or much higher than the set volume.

## To Reproduce
1. Create a project in B105
2. Add a "Play Sound on Channel" event with a condition of a key pressed (or mouse clicked) plus trigger once.
3. Select the desired .wav file.
4. Set the sound to play at 10%
5. Export to web and open the page.
6. Rapidly activate the event. The sound will play at the expected volume.
7. Open this same project in b108
8. Export to web again and open the page. 
9.  Rapidly activate the event. The sound will randomly play at a much louder volume or glitch out.

I have confirmed this happens both on local and web export for me with my example project. I did also attempt setting preload as sound, preload as music, and both, in b108.

Project file: 
Example project saved from B105: 
[TestSoundProjectB105.zip](https://github.com/4ian/GDevelop/files/6232344/TestSoundProjectB105.zip)

Exported using B105:
https://games.gdevelop-app.com/game-841d2e35-770a-40b5-b500-75d3a41f9a4a/index.html

Exported using B108: 
https://games.gdevelop-app.com/game-02abe421-b47d-4d96-ad21-a19fcf9c4768/index.html

## Other details
OS: Windows 10 64 Bit
GD5 Versions: B105 and B108
Context: Reported on the forums here https://forum.gdevelop-app.com/t/sound-effects-becoming-clipped-or-very-loud/31599/20. Posting here as I can reproduce the problem, and I'm not 100% sure that we can open an issue on the Howler.js github without being able to guarantee it is an issue with Howler, and neither the user nor I know enough about the GD5 code to confirm that.

**Comment by 4ian** [comment]
Thanks for the detailed report. Very clear! 

> Posting here as I can reproduce the problem, and I'm not 100% sure that we can open an issue on the Howler.js github without being able to guarantee it is an issue with Howler, and neither the user nor I know enough about the GD5 code to confirm that.

That's almost certainly a regression due to a refactoring of the music handler. 
(as you said, it's not a good idea to open an issue on Howler github without proving first in an example that it's Howler or a dependency that is problematic).

@arthuro555 Would you be able to have a quick look?
I can also look, it's certainly a timing issue where we apply the volume too late, i.e: after the sound started playing.

**Comment by arthuro555** [comment]
I wonder if this could fix it:

**Comment by 4ian** [comment]
> I wonder if this could fix it:

Mmmm, not sure I understand, this would remove the on/once call on the Howl, and directly execute the handler... but the handler is only supposed to be called when a certain "event" (of type HowlEvent) is happening, right? This may solve some issue but also create a bug as on/once are not working anymore as designed?

The problem probably comes from the fact that we're setting loop/volume/rate only when the "play" event is called, which is too late (when "play" is emitted, the sound has already started playing):
![image](https://user-images.githubusercontent.com/1280130/113461011-a6946f80-9412-11eb-9cb2-774cdeb0e5a7.png)

We should probably do directly the setLoop/setVolume/setRate?

**Comment by arthuro555** [comment]
> We should probably do directly the setLoop/setVolume/setRate?

That wouldn't work if the sound wasn't loaded before, as play() will not play the sound but load it then play it:
```ts
    play(): this {
      if (this.isLoaded()) {
        // ...
      } else this._howl.once('load', () => this.play()); // Play only once the howl is fully loaded

      return this;
    }
```

If the sound is not playing yet, then the setters won't work at all as they wouldn't have an ID, therefore we need to only set those once the sound is playing. As it seems howler only triggers the play function once after registering it (as everything seems to work as expected) when the sound is already playing, calling the function directly should have the same effect except that it wouldn't have to wait for Howlers event handling system to trigger.

**Comment by 4ian** [comment]
Your solution seems to work :) I'm just unsure about if we should do exactly this, because basically we're changing the semantic of on/once a bit (if I call `.on('play', something)` on a sound that is paused, something will be executed, which seems wrong).

**Comment by arthuro555** [comment]
In that case, maybe we can do this:
```diff
diff --git a/GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts b/GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts
index 366b18b43..f623b9be6 100644
--- a/GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts
+++ b/GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts
@@ -249,7 +249,7 @@ namespace gdjs {
     on(event: HowlEvent, handler: HowlCallback): this {
       if (event === 'play') {
         if (this._id === null) this._onPlay.push(handler);
-        else this._howl.on(event, handler, this._id);
+        else if(this.playing()) handler(this._id);
       } else if (this._id === null)
         this.once('play', () => this.on(event, handler));
       else this._howl.on(event, handler, this._id);
@@ -263,7 +263,7 @@ namespace gdjs {
     once(event: HowlEvent, handler: HowlCallback): this {
       if (event === 'play') {
         if (this._id === null) this._oncePlay.push(handler);
-        else this._howl.once(event, handler, this._id);
+        else if(this.playing()) handler(this._id);
       } else if (this._id === null)
         this.once('play', () => this.once(event, handler));
       else this._howl.once(event, handler, this._id);
```

**Comment by 4ian** [comment]
> maybe we can do this:

This is still changing the behavior of `.on('play', something)` in case the sound is paused for example (`something` would never get called, because never added on the howl).

> Or even if you prefer this, though I am not sure if it would solve the issue:

It could work, this means we're "just" calling the handler synchronously if we detect that the sound is already playing. And don't change anything in the rest of the case (if a sound is paused/stopped, not loaded, we do as before, and the handler will be called later). 
I'll try that :)

**Comment by 4ian** [comment]
Opened a fix :) Seems to work well
