### ISSUE TITLE
[$125 bounty] Add a project setting for Pixel Rounding - To enable Project-wide Pixi.settings.ROUND_PIXELS

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2504]
## Description

I would like to see a new checkbox toggle/setting added to enable Pixel Rounding for your project. 

As discussed here: https://forum.gdevelop-app.com/t/project-wide-toggle-for-pixi-settings-round-pixels/31673

## Solution suggested
I would like to see a new setting (checkbox or otherwise) added to the Project Properties panel. Enabling this setting would enable the Pixi.Settings.ROUND_PIXELS flag for the entire project. (https://pixijs.download/release/docs/PIXI.settings.html#ROUND_PIXELS)

We already have a "round pixels" toggle for the platformer behavior, but that only impacts that specific object. This toggle would ensure that everything is impacted, including camera, positioning, and movement, not just for objects. As mentioned in Pixi's documentation:
 “Advantages can include sharper image quality (like text) and faster rendering on canvas. The main disadvantage is movement of objects may appear less smooth.”. 

Eliminating subpixel rendering can be very beneficial for any project, but especially for those with retro-style movement and graphics.

## Alternatives considered

Document where and how people can manually modify their various exported .js files to enable the toggle. Not a recommended solution as it can lead to error and be highly confusing for new users.

**Comment by D8H** [comment]
I heard something about pixel perfect. I think It's a rounding at the big pixels and it's not the same as pixel rounding + scaling because effects are usually rendered on native pixels.
Maybe this is something to consider.

**Comment by Silver-Streak** [comment]
> I heard something about pixel perfect. I think It's a rounding at the big pixels and it's not the same as pixel rounding + scaling because effects are usually rendered on native pixels.
> Maybe this is something to consider.

Not sure what you're referring to, as far as what I can find in Pixi's documentation, there isn't pixel perfect. Pixel Rounding as it exists (and as I'm requestion) eliminates subpixel (float) x/y positions and width/height. This makes it behave more natually to old 2D systems like NES/SNES/ETC.

If there's something else that you're aware of/referring to, I'd love to see more details on it.

**Comment by D8H** [comment]
Yes, I don't know about Pixi.
I think the general idea of pixel perfect is that the big pixels of the sprites are all aligned. For instance, a 4x4 big pixel can't be on the screen at (23 ; 47) because the purpure is to fake low resolutions for the pixel art part.
But it's a game designer choice, I just wanted to pin-point it in case both can be done easily at the same time.

**Comment by Silver-Streak** [comment]
> Yes, I don't know about Pixi.
> I think the general idea of pixel perfect is that the big pixels of the sprites are all aligned. For instance, a 4x4 big pixel can't be on the screen at (23 ; 47) because the purpure is to fake low resolutions for the pixel art part.
> But it's a game designer choice, I just wanted to pin-point it in case both can be done easily at the same time.

ahhh, okay, yes that's a much larger thing. At a high level Pixel rounding can help with that a little (to eliminate float locations). The rest is harder as it would require you to have the players define what qualifies as 1 "pixel", in your case 4x4.

The best way to accommodate that right now would be to start at a smaller resolution with similar pixel scale assets, and then use scaling instead of changing the resolution, I think? 

Not quite the scope of this feature.

**Comment by 4ian** [comment]
I think it makes sense to expose this, I've looked at the implementation in Pixi.js and it's indeed rounding the coordinates of the vertices of objects rendered on screen - i.e: this is a rendering thing only, not impacting the logic of the game. Might be useful for games that wants a pixel perfect rendering - even if this will only partially help (as mentioned, if the game is using a setup where "one" pixel in the game = "more than one" pixel in images, this will still allow "sub pixel" rendering). 

Maybe this could actually be extended in the future to allow rounding to more than one pixel (but would need some changes in Pixi, or expose PIXI.settings.RESOLUTION, which can be having other side effects).

**Comment by Silver-Streak** [comment]
I have opened a small bounty on this, as this seems important the more I work on pixel based games.  
https://www.bountysource.com/issues/97649068-add-a-project-setting-for-pixel-rounding-to-enable-project-wide-pixi-settings-round_pixels

Separately, [the issue linked here](https://github.com/4ian/GDevelop/issues/2664) may need to be fixed before this feature can be implemented.

**Comment by Silver-Streak** [comment]
As I've seen more people have use for this on the forums and the discord, I have had a chance to bump up the bounty on this a bit. It is now at $75 USD.

**Comment by Bouh** [comment]
This is something that the pixi team also does on their side.
https://github.com/pixijs/pixijs/pull/7495

**Comment by Silver-Streak** [comment]
As I've been working through my advanced platformer example, and my main game, I begin to realize how needed this is. Especially for smaller resolution games, floating positions/scales/etc can have a large negative impact on graphical quality.

With that in mind I've bumped this up another $25 in hopes of finding someone to take this up.

**Comment by Silver-Streak** [comment]
Bumped this up a bit more (probably the last I can do for now), so it is now at $125.

**Comment by ClementPasteau** [comment]
The option has been added and will be available in the next release :)

**Comment by 4ian** [comment]
@Silver-Streak what do you want to do with the bounty (Clement and I won't claim bounties :)). Maybe claim it, I approve and you put it on other issues (or cash it, but you'll lose a bit of money with the fees I guess)?

**Comment by Silver-Streak** [comment]
@4ian is there another big item that we think would be good for a bounty rather than a feature/function you all are working on?

The other big things I can think of are:

- Integrating LDtk into the GUI (already a bounty, should I just add more to this?)
- More scaling options (https://colececil.io/blog/2017/scaling-pixel-art-without-destroying-it/ or https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look would probably be super helpful for retro style games)
- Better Finite State Machine support/visualization? Some type of flow/node chart for these could be super useful, but no clue how big of a change that would be.
- Tags as virtual folders in the object list? We have talked about this one quite a bit and better organization of the object list is a common request, but I'm not sure this is right for a bounty.
- A direct/more native way to integrate/interact with Steamworks/greenworks? Arthuro has done fantastic work in this area, but the level of complexity is beyond most users.

Also, should I avoid new bounties on Bountysource? Should we move to rysolv or something else?
