### ISSUE TITLE
Linux preview opens games of other users

### ISSUE THREAD

**Issue by miniat-amos** [4ian/GDevelop#2507]
Defect occurs when more than one Linux user runs GDevelop on the same system.  If user A is the first to generate a preview on the system, other users thereafter may not be able preview their own games.  Instead, they can see the preview of user A's game until either the system is rebooted (clearing the /tmp directories) or an admin removes the /tmp/preview, /tmp/GDTemporaries, and /tmp/GDGeneratedEventsFunctions directories.

I'm using GDevelop 5.0.0-beta 108 based on GDevelop.js 4.0.99-release

To replicate the error...
1. Once the system is booted, user A launches GDevelop and previews a game
  -- user A's game is previewed
2. User A closes GDevelop and logs out
3. User B launches GDevelop and previews some different project
  -- User A's game is previewed again instead of B's game

I believe the cause of this error is that (at least on Linux) GDevelop creates the directories mentioned above instead of randomly generated temporary directories.  In the replication steps above, user A's preview attempt, for example, creates the /tmp/preview directory and the files it contains with read-only access to all users.  When user B attempts to preview, they cannot replace the preview directory or write other files because they do not have write permission, but GDevelop does not complain.  Instead it mysteriously opens the existing project in the preview directory.

I discovered the bug when working on the Platformer tutorial to see if it was something one of my kids would be interested in.  When they logged in to try the same tutorial, they kept getting my version.

**Comment by 4ian** [comment]
Thanks for reporting! 
It's indeed something not expected and not properly handled not to have write permission in these temporary directories.
I think a solution could be to first clean these directories when the software is closing and then if we detect they are not writable, use new empty directories.

**Comment by miniat-amos** [comment]
The use of system wide temporary directories may even be avoidable.  The preview directories could be created in the user's project folder instead of a system-wide shared temporary folder.  The user's instances of GDevelop would always have permissions to these directories and they would be inherently hidden from other system users.  In my university environment, for example, student A may be creating a game to blow off steam about a grumpy professor (say me :-) ), and if I had access to it, I could take it all the wrong way.  In that sense, exporting previews to shared directories is a security issue.

Exporting previews to the project directory would solve the security issue and eliminate the need to check for the directory or even delete it for that matter.  New attempts to preview after changes to the project would overwrite what is already there.

I'm not a Javascript developer myself, but I'll see if I can't attempt a fix and submit a pull request.

**Comment by 4ian** [comment]
Yeah that's fair, we could potentially use a folder inside the user folder. 
If you want to take a look, search for `os.tmpdir()` in the codebase. They should be all in `LocalXXX.js` files, that are used for previews, for code generated for behavior/functions, or for exports. 
We could replace these by a util function that would identify a suitable directory. Starting by one in the user folder, and falling back to the os.tmpdir in case nothing else is successful.

**Comment by Oxey405** [comment]
Is anyone taking care of this issue ? Beacause I think I can !

**Comment by 4ian** [comment]
Feel free to take a look! :)

**Comment by miniat-amos** [comment]
A utility function for identifying a temp directory for the project and its exports seems like a good plan.  There are least two methods in the codebase used to find the shared system temporary directory right now: `os.tmpdir()` and `filesystem.getTempDir()`.  If this is an accident, the utility function could standardize the approach.

Thanks for taking a shot at it @Oxey405
