### ISSUE TITLE
5.0.0-beta108 fails to compile SFML on FreeBSD

### ISSUE THREAD

**Issue by PaddyMac** [4ian/GDevelop#2512]
I downloaded the GDevelop source code for 5 beta 108, ran cmake in a build directory, and ran make. The compilation failed while compiling SFML. The thing is, this is apparently a problem with GDevelop because I downloaded the SFML code from git master and compiled it by itself, and it compiled successfully. A cmake option to use an external, system library would be nice. I'm running FreeBSD 13-RC5.

[gdevelop5-beta108.txt](https://github.com/4ian/GDevelop/files/6261935/gdevelop5-beta108.txt)

**Comment by Bouh** [comment]
SFML isn't used since GD4.
GD5 and all beta use Pixi.JS as graphic library.
Did you follow the [right README?](https://github.com/4ian/GDevelop#getting-started)
