### ISSUE TITLE
New example: A more advance Bomberman-like with level selection and bonuses

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2531]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: https://www.dropbox.com/s/tnvg04bgb2ztfrs/SansFoieNieLOie.zip?dl=1

  I confirm that any assets can be used freely by anybody, including for commercial usage.
 
The related PR: https://github.com/4ian/GDevelop/pull/2530

![65d99522658f6839a5062cbe9498143ba791fa82](https://user-images.githubusercontent.com/2611977/114283546-8f750380-9a4a-11eb-841e-d8373fe67ce8.png)

**Comment by 4ian** [comment]
Very nice! Added in 1ad0ab9881ccc6556ec3cad512babee917b64ade :)
