### ISSUE TITLE
I have a bug when displaying a Sprite and a Tiled Sprite, both objects use the same image

### ISSUE THREAD

**Issue by achubutkin** [4ian/GDevelop#2538]
## Describe the bug
Hello everyone, 

I have a bug when displaying a Sprite and a Tiled Sprite, both objects use the same image. The bug is that tiled sprites have a border between tiles only then z-order index of Tiled Sprite greater than z-order index of Sprite.
[My project38.zip](https://github.com/4ian/GDevelop/files/6298427/My.project38.zip)

## To Reproduce
1. Create new project and set project properties (for example): 
- game resolution to 896 (width) and 640 (height)
- game resolution resize mode to "Change width to fit the screen or window size"
2. Create new scene.
3. Setup grid settings to 128 (cell width) and 128 (cell height).
4. Create Sprite object with 128x128 size and set image with 128x128 size.
5. Create Tiled Sprite with 128x128 default size and set the same image as for Sprite (one image for both objects).
6. Add Sprite and Tiled Sprite object to scene. Use snapping to fit neatly to the grid. 
7. Set z-order index of Sprite to 2 and z-order index of Tiled Sprite to 3. 
8. Run project and you will show borders on Tiled Sprite. 

If you set the same index for all objects, then the borders will disappear. Or if you copy your image and rename it and set the image for Tiled Sprite, then borders will disappear.

## Other details
Please, see ready to run project.
[My project38.zip](https://github.com/4ian/GDevelop/files/6298399/My.project38.zip)

**Comment by achubutkin** [comment]
I have two ways to work around this behavior in my project. Different files of the same image for Sprite and Tiled Sprite (this slightly increases the size of the game). Or I make the small Tiled Sprite and hide it under the Sprite (making the index of Tiled Sprite  smaller than the Sprite).

**Comment by Bouh** [comment]
This kind of problem is typically a problem related to PixiJS and their TilingSprite, in movement or not.
https://github.com/pixijs/pixi.js/issues/7166

- I've run GDevelop with PixiJS 6.0.1, same result.

**Comment by Bouh** [comment]
[I agree the fact we should round all the positions/scales/rotations](https://github.com/4ian/GDevelop/issues/2504).
Because this can be a problem for us.
![image](https://user-images.githubusercontent.com/1670670/114448097-68960900-9bd3-11eb-95e9-612cbbacd921.png)

**Comment by achubutkin** [comment]
Thank you very much for your answer @Bouh ! If I understand correctly, is this error when the sprite moves?

**Comment by Bouh** [comment]
Not necessary, it' s a concern UV of the texture, and value not rounded.

**Comment by achubutkin** [comment]
Oh, I got it. Many thanks!
