### ISSUE TITLE
Instances picked for a group have side effects on other groups

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2545]
### Context
* A user wants to link neighbors Bubble instances.
* He defines another group OtherBubble that is the same as Bubble.
* He iterates on Bubble with a "for each instance" and test points to find nearby OtherBubble.

### Expected
* Links are created
* Groups allow to pick multiple selections of instances in one context.

### Actual
* No link is created because Bubble and OtherBubble has the same selection.

### A stupid example to illustrate
I want to express: "Is there a bubble no matter its color at the right of a yellow one?".
https://www.dropbox.com/s/eo4vk7azvtkgsu9/BimBamTest.zip?dl=1

For instance, with this event...
![Events](https://user-images.githubusercontent.com/2611977/114631450-e41fb500-9cbc-11eb-93cb-21f2b0e2976a.png)

...and this initial state...
![InitialState](https://user-images.githubusercontent.com/2611977/114631483-ee41b380-9cbc-11eb-83a3-77edc279b89a.png)

...clicking on every bubble will delete only these 3.
![FinalState](https://user-images.githubusercontent.com/2611977/114631508-fa2d7580-9cbc-11eb-9aa0-fc452dc3866e.png)

So only when the Bubble is BlueBubble and not when the Bubble is YellowBubble.

A click on the green cross won't delete the bubble with a red cross because the condition on YellowBubble also constrains Bubble.
![Yellow](https://user-images.githubusercontent.com/2611977/114631524-03b6dd80-9cbd-11eb-883d-117fd18ab8c1.png)

## Alternatives considered
Like in this match-3 example https://github.com/4ian/GDevelop/issues/2566, the graph can be built with 2 layers:
* visible bubbles linked to theirs shadow bubbles
* shadow bubbles linked to the neighbors visible bubbles

But this doesn't seem intuitive.

**Comment by 4ian** [comment]
Did you close because you found another solution? :)

**Comment by D8H** [comment]
I opened a discussion instead: https://github.com/4ian/GDevelop/discussions/2653
