### ISSUE TITLE
Configuration sometimes doesn't load in beta 108

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#2547]
## Describe the bug
Sometimes when you start GDevelop the configuration (Language, Theme) are just completly reset.

## To Reproduce
This glitch happens when the window is not focused

## Other details
* I am on ubuntu 20.04
* I am using the GDevelop 5 beta 108

**Comment by Bouh** [comment]
This is know when there is multiple GDevelop app open in same time.

**Comment by willianholtz** [comment]
I really have a problem using Arch Linux, as the background color is not saved, and neither is the grid color.
And it is not because I use two instances of the software, even because I don't use it!
