### ISSUE TITLE
Music sometimes doubled

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2550]
A user reports on the forum that upon launch of the preview, about half of the time, two music files play at once.
I confirmed this on my side.
Related to the new stereo features, perhaps?
Also, I often get a "pop" at preview launch, with a music file that used to work fine in GDevelop.

GD5b108

https://user-images.githubusercontent.com/25978830/114780179-548b0c80-9d77-11eb-920d-441c17ec22dd.mp4

[source](https://forum.gdevelop-app.com/t/launching-a-preview-of-a-scene-causes-2-audios-to-play-at-once-occasionally/31937)

**Comment by 4ian** [comment]
> Also, I often get a "pop" at preview launch, with a music file that used to work fine in GDevelop.

This thing is fixed for next version.

Pinging @arthuro555, might be because of the refactoring of the sound manager. Though not entirely sure what would make two songs to start at the same time 🤔

**Comment by 4ian** [comment]
I wonder if in your case this could be because of the first condition that could alternate very quickly between true and false at the beginning of the sound. So the trigger once would still fire (because there was a frame during which the condition was true, false, then true again).

**Comment by 4ian** [comment]
Would you be able to share the project and sound? :)

**Comment by PascalLadalle** [comment]
I hadn't saved the test project, so I made another from scratch, instead of using a template like I did yesterday, and it's much more occasional than yesterday, not sure if it's a coincidence... I got the bug maybe 2 times out of 10.

[doublesound.zip](https://github.com/4ian/GDevelop/files/6321388/doublesound.zip)

**Comment by arthuro555** [comment]
That seems to be the issue indeed: 

Experiment code:
![image](https://user-images.githubusercontent.com/19349038/115032099-37fee980-9ec9-11eb-82fa-287de3a8c4f7.png)


Experiment results after reloading the game a few times: 
![image](https://user-images.githubusercontent.com/19349038/115032057-2c132780-9ec9-11eb-8229-bac3a386a0ce.png)

**Comment by arthuro555** [comment]
My bet is that it is caused by the fact that loading is considered playing:
https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts#L110-L111  
```ts
playing(): boolean {
      return (
        (this._id !== null ? this._howl.playing(this._id) : false) ||
        !this.isLoaded() // Loading is considered playing
      );
    }
```
I think howler doesn't directly plays it when it finishes loading. So the Howl is loaded, but the HowlerSound not yet playing, causing the playing condition to return false.

**Comment by arthuro555** [comment]
Without that change, I could replicate the bug 2 times in ~30 tries, with that change I couldn't replicate it once after ~200 tries. Submitting a PR now.
