### ISSUE TITLE
Project Name: Animated Scenes Example

### ISSUE THREAD

**Issue by Dreamkingmovies** [4ian/GDevelop#2551]
Hello!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: _Files are attached_
  I confirm that any assets can be used freely by anybody, including for commercial usage!
  
My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Example.zip](https://github.com/4ian/GDevelop/files/6314361/Scene.Animation.Example.zip)

**Comment by Dreamkingmovies** [comment]
@4ian @Bouh

**Comment by Dreamkingmovies** [comment]
Hello!

I'd like to submit a new example to be added to GDevelop. 

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene. 

Definition 2: Example showing how to make Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Example.zip](https://github.com/4ian/GDevelop/files/6314819/Scene.Animation.Example.zip)

**Comment by Midhil457** [comment]
Hi, I just reviewed the project and it works great and I really like the animations. 


There is a unused object "NewObject". If it needs to be used, rename it to something else and maybe not "NewObject".

![SceneAnimation5](https://user-images.githubusercontent.com/73597906/114827240-0fea8a00-9de6-11eb-9112-116cccd3ac7c.png)

There are some events . Having a empty event is not really useful

Here are some I found (On both the scenes):
![SceneAnimation4](https://user-images.githubusercontent.com/73597906/114827372-3a3c4780-9de6-11eb-816f-ac44193c2c7e.png)

![SceneAnimation2](https://user-images.githubusercontent.com/73597906/114827543-6fe13080-9de6-11eb-8b38-f53ffea41f7b.png)

Maybe change this text's colour to something more visible. As it is not very readable with the white Background (On both the scenes).
![SceneAnimation3](https://user-images.githubusercontent.com/73597906/114827450-56d87f80-9de6-11eb-89bf-85af1351c794.png)

There is a small tying error here (On both the scenes):
![SceneAnimation1](https://user-images.githubusercontent.com/73597906/114827771-ba62ad00-9de6-11eb-9e4a-d9669203548c.png)

Maybe also add a comment at the start of the events sheet telling to add the tween behaviour to the objects that has to be tweened. People may forget about that and maybe get confused.

:)

**Comment by Midhil457** [comment]
Also maybe fill in the properties panel with the author name, version, etc... It can be found it the Projects manager

**Comment by Dreamkingmovies** [comment]
Hello!

I'd like to submit a new example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to make Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Example.zip](https://github.com/4ian/GDevelop/files/6319285/Scene.Animation.Example.zip)

**Comment by Midhil457** [comment]
Hi, I reviewed the example and most of the issues are now fixed!

But, still there are some problems:

- There are there BG images in the game folder. Please do remove the unused ones

![SceneAnimation5](https://user-images.githubusercontent.com/73597906/115012156-1acc1a00-9ecd-11eb-97d6-dc04b7725370.png)

- There are still some empty events. Do remove them

![SceneAnimation6](https://user-images.githubusercontent.com/73597906/115012651-b78eb780-9ecd-11eb-9150-3b1a0022e2bf.png)

- There are still some group's names that are not very visible because of their color

![SceneAnimation1](https://user-images.githubusercontent.com/73597906/115012251-3d5e3300-9ecd-11eb-9a34-da09fec55be9.png)

-This text's color is still not changed in the scene "Level Select"

![SceneAnimation2](https://user-images.githubusercontent.com/73597906/115012359-5f57b580-9ecd-11eb-915f-d13920a35654.png)

- There is a typing mistake in the game's name

![SceneAnimation4](https://user-images.githubusercontent.com/73597906/115012425-6f6f9500-9ecd-11eb-965d-55d1d1fa6c42.png)

Most of these are tiny problems. But, as this is an example, it needs to be all good.

:)

**Comment by Midhil457** [comment]
Also, please include the whole project when sharing it, making it easier for reviewing and adding it to GDevelop

**Comment by Dreamkingmovies** [comment]
Hello!

I'd like to submit a new example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to make Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
Scene Animation Example.zip
[Scene Animation Gdevelop Example.zip](https://github.com/4ian/GDevelop/files/6325425/Scene.Animation.Gdevelop.Example.zip)

**Comment by Midhil457** [comment]
Can you provide the whole game folder including the assets in the zip, to make that only the needed assets are in the project

:)

**Comment by Dreamkingmovies** [comment]
> Can you provide the whole game folder including the assets in the zip, to make that only the needed assets are in the project
> 
> :)

I Dont understand

**Comment by Midhil457** [comment]
When, you make a project, GDevelop creates a project folder. Where the assets,.json file, autosave is kept. You will have to zip it and share it so that we can check if only the needed assets are used. Like how for your first version, you included that whole game

**Comment by Dreamkingmovies** [comment]
*Sorry for the long wait. I have been very busy, I do have the zip archive ready for review.


Hello!

I'd like to submit a new example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to make Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Tutorial.zip](https://github.com/4ian/GDevelop/files/6377839/Scene.Animation.Tutorial.zip)

**Comment by Midhil457** [comment]
Hi, I just reviewed the project

- There is still an unused object "NewObject", do remove it if not necessary

- There are some empty events in the event sheet, please remove them

- There are some of typing mistakes in the comments, like inportant > important, resonable > reasonable, Titled sprite > Tiled sprite, scorlling > scrolling, interactible > interactive, recongize > recognise, behavoir > behaviour. Maybe paste the comments in an text editor or a text box that has spell checking , and you might be able to find and fix the mistakes.

:)

**Comment by Dreamkingmovies** [comment]
Hello!

I'd like to submit a new example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to make Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Tutorial.zip](https://github.com/4ian/GDevelop/files/6398547/Scene.Animation.Tutorial.zip)

**Comment by Midhil457** [comment]
Hi, I just reviewed the project and I think almost all of the problems are fixed now

But, I did find that there are still some typing mistakes in the comments and also in the texts in the scene, like inportant > important, behavior > behaviour, templete > template. There might be more, so do check through all the comments and the texts.

To maybe easily find the typos, just copy-paste the comments and texts into an textbox or text editor that has spell checking, maybe here: https://www.reverso.net/spell-checker/english-spelling-grammar/

:)

**Comment by Dreamkingmovies** [comment]
Hello!

I have edited my example and im ready for my example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to m

ake Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)
[Scene Animation Tutorial.zip](https://github.com/4ian/GDevelop/files/6407234/Scene.Animation.Tutorial.zip)

**Comment by Midhil457** [comment]
Hi,

-  I you still haven't fixed the game name
- 
Not scences, it is scenes

![Scences](https://user-images.githubusercontent.com/73597906/116772689-6acee300-aa6e-11eb-83b9-a876eaf4286d.png)

I know it is a small thing :sweat_smile: 

:)

**Comment by catpenguin95** [comment]
Very effective at showcasing the tween behavior. 
![image](https://user-images.githubusercontent.com/83555473/116826715-447e7580-ab4a-11eb-9138-f8bead4a666c.png)
Maybe the comments could be formed together into one? 
Very nice though!

**Comment by Dreamkingmovies** [comment]
**I have fixed all the problems :) 

"FIle Attached"**

Hello!

I have edited my example and I'm ready for my example to be added to GDevelop.

Definition 1: My Gdevelop Example is about Startup and Switching Animations for the scene.

Definition 2: Example showing how to m

ake Startup and Switching animations to use for a scene.

Here is the link to download it: Files are attached
I confirm that any assets can be used freely by anybody, including for commercial usage!

My discord is Thewavinace#7960 (Fell free to ping me. I am usually active on discord.)

[Scene Animation Tutorial.zip](https://github.com/4ian/GDevelop/files/6430836/Scene.Animation.Tutorial.zip)

**Comment by Midhil457** [comment]
Hi, I just reviewed it and it looks great and I think this can now be added

:)

**Comment by Dreamkingmovies** [comment]
@Bouh @4ian Sorry for pinging but I am ready for review!

**Comment by 4ian** [comment]
Thanks, I think it looks good. Added to examples! :)
