### ISSUE TITLE
After deleting the last linked object, Count() returns 1 linked object (should return 0 linked objects)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2560]
## Describe the bug

After deleting the last linked object, Count() returns 1 linked object.  It should return 0 linked objects.

## To Reproduce

1. Create an event:
  - Condition: "Take into account all Object A linked to Object B"
  - Action: Update a text object with "ToString(Count(Object A))"
2. Create Object A
3. Create Object B and link it to Object A
4. Repeat step 3 multiple times
5. The text object should show the correct amount of linked objects
6. Start deleting Object B instances
7. The text object should show the correct amount of linked objects
8. Delete the very last instance Object B
9. The text object will show 1 linked objects (but it should show 0)
 
## Game
https://games.gdevelop-app.com/game-23ee9184-523b-42d4-9a88-466c5f7878c9/index.html

## Video
https://user-images.githubusercontent.com/8879811/115120414-992ac980-9f6a-11eb-91ce-ecb99b3270b9.mp4

**Comment by tristanbob** [comment]
This is not a bug.  If there are 0 linked objects, the condition won't be met so the Action to change text never executes.

The way to solve this is by moving the TakeIntoAccount from a Condition to an Action (this is the first time I have found a reason to use it this way):

![image](https://user-images.githubusercontent.com/8879811/115123321-b3b86f00-9f79-11eb-842c-b2da0f8843dd.png)

Thanks @arthuro555 for your help on this!

**Comment by 4ian** [comment]
We could probably add an explanation in the condition description :)

**Comment by arthuro555** [comment]
Or maybe rename the condition version to something along the lines of "The object is linked", to imply that this is an actual condition and not "object picking magic"?

**Comment by tristanbob** [comment]
> Or maybe rename the condition version to something along the lines of "The object is linked", to imply that this is an actual condition and not "object picking magic"?

I think rewording this condition is a good idea.  "Take into account" could mean almost anything!  It is not obvious what the condition means or does.  

I like the wording "Pick ___ that are linked to ___" since the primary purpose IS picking instances.  This wording change would go well with my Feature Request to eliminate the Action option and replace the logic with a boolean:  #2561
