### ISSUE TITLE
New example: Bust-A-Move clone (match 3 game)

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2566]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to
* download it: https://www.dropbox.com/s/pudd3md7xojbyu6/BimBam.zip?dl=1
* play it (controls are arrows and LShift or mouse): https://games.gdevelop-app.com/game-248d7a98-f826-44b4-96f8-d498e36359c6/index.html
* watch it: https://user-images.githubusercontent.com/2611977/115282856-f7ae9e00-a14a-11eb-90d2-410e824fdf6c.mp4

  I confirm that any assets can be used freely by anybody, including for commercial usage.

It uses custom extensions
* a SnapToGrid for hexagonal grids (https://github.com/4ian/GDevelop-extensions/issues/131)
* a FireBullet with a fix to have the bullet back in the context (https://github.com/4ian/GDevelop-extensions/issues/124)
* a "Can reach through links" used by the match-3 system (https://github.com/4ian/GDevelop-extensions/issues/122)
* a turret movement behavior (https://github.com/4ian/GDevelop-extensions/issues/121)
* some helper conditions on mouse movement (https://github.com/4ian/GDevelop-extensions/issues/123)

![BimBam](https://user-images.githubusercontent.com/2611977/116734049-349d4f00-a9ed-11eb-9ee6-f5bd7c74542b.PNG)

**Comment by blurymind** [comment]
Wonderful demo. Nice work 👏

**Comment by Midhil457** [comment]
Hi, I just reviewed the project and it was fun and I really loved the colours!

Some problems that I found:

- There is a unusual bug that I found that makes the balls fall even if there are no pairs near. It happened on both the web build and also in the editor. here is an video showing it: 

https://user-images.githubusercontent.com/73597906/115357265-16a84100-a1da-11eb-8603-b78705bbb331.mp4

- There is an unused object called **Mark**. I think it is for some back-end stuff and not a visual object. I might be wrong. Anyway, maybe adding a comment explaining what that object does might help

- I found that there is a lack of comments. Especially in the extensions. There are some complex extension and some that also use JavaScript. So, adding some comments explaining it might help

- A small thing, but the readme.md has only one sentence in it. If it is not useful, maybe remove or add some extra info, But, as it is an example, it might not be important.

:)

**Comment by Bouh** [comment]
The extensions create new variables, the rules for the variables scoped in an extension is to prefix it with underscore. Like a private variable in coding languages.
[Here the best pratices to follow for the extensions](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).

**Comment by D8H** [comment]
Thanks for the reviews :smile:
I updated the file.

>     * There is a unusual bug that I found that makes the balls fall even if there are no pairs near. It happened on both the web build and also in the editor. here is an video showing it:

In the video it looks like the bubble snap over another bubble, but I couldn't reproduce it so far.
There is also a rare bug where the bubbles snap on the screen edge because the grid size is 32 pixel and the collision mask size is 30. I put a bigger margin.
The Turret extension has an issue on stop angles. It doesn't show on this example, but I need to rewrite it.


>     * There is an unused object called **Mark**. I think it is for some back-end stuff and not a visual object. I might be wrong. Anyway, maybe adding a comment explaining what that object does might help

I moved the comment nearer the Mark creation.

>     * I found that there is a lack of comments. Especially in the extensions. There are some complex extension and some that also use JavaScript. So, adding some comments explaining it might help

I added some. Tell me if one could be needed somewhere.

>     * A small thing, but the readme.md has only one sentence in it. If it is not useful, maybe remove or add some extra info, But, as it is an example, it might not be important.

The readme for examples is actually a short description that is displayed in the examples list.


>     The extensions create new variables, the rules for the variables scoped in an extension is to prefix it with underscore. Like a private variable in coding languages.

I added the double underscore. I find it more readable with a prefix in lower case rather than camel case because the important part of the name stands out more.

**Comment by Midhil457** [comment]
Hi, I just reviewed it and the documentation is better.

But, I still found that some portions are still not documented. Just having a small comment briefly going though what a external event/function does, is more than enough. people might get confused at first seeing all those events. So, just telling a brief description might help.
Like this part, it might be confusing at first
![BimBam1](https://user-images.githubusercontent.com/73597906/115539317-74ac5580-a2ba-11eb-8a70-0d9bd2993c56.png)


- "Staid" should be "Stayed"
![Stayed](https://user-images.githubusercontent.com/73597906/115539259-5fcfc200-a2ba-11eb-80ef-f0bfabc891b1.png)

:)

**Comment by D8H** [comment]
Thanks a lot for the tests and reviews Midhil, I rewrote the snap action to use an hexagonal grid. I think this should solve the bug you found.
I made a new build: https://games.gdevelop-app.com/game-8ef7c8a1-cdc0-418a-a385-84620394db70/index.html

I also updated the extensions reviewed by Florian inside the project.

**Comment by Midhil457** [comment]
Hi, I just reviewed the project

- It should be "mouse is"

![MouseIs](https://user-images.githubusercontent.com/73597906/116361858-1124a980-a81f-11eb-9fbd-9d51b32a56bc.png)

- Adding something about the logic behind this might be helpful for some

![BimBam1](https://user-images.githubusercontent.com/73597906/115539317-74ac5580-a2ba-11eb-8a70-0d9bd2993c56.png)

- Just a tiny thing, renaming these two resources.

![NewObjects](https://user-images.githubusercontent.com/73597906/116361841-0d912280-a81f-11eb-8edd-0d54975dfc80.png)


:)

**Comment by D8H** [comment]
Sorry, I forgot about that. I upload a new version.

**Comment by 4ian** [comment]
Awesome demo :) I'll add it.

**Comment by 4ian** [comment]
Added! 👍 Thanks @D8H and @Bouh, @Midhil457 for the review!
