### ISSUE TITLE
Play Sound: Sound file is playing before volume is being applied.

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2579]
## Describe the bug
When playing a sound that starts almost instantly (example within 0.010 seconds) the sound can be heard playing for a small moment even when at 0 volume.

In our game we set the sound level via a Global Var and thought this was the cause, however even setting the sound to 0 it still can be heard.

This is not an issue if there is a silent period at the start of the audio file (example after 0.020 seconds), but as you can imagine some times that small difference can be enough to make something look out of sync (example walking animation, feet touching ground and sound playing).

I have created an example using two sounds. One starts at 0.06 seconds, the other 0.020 seconds. The latter does play any sounds. The example has 3 keys as shown below.
Audio File (Audacity): https://i.gyazo.com/55a0246c15319025c6257f1581738a02.png
![](https://i.gyazo.com/d165360374fa6e2854b85025be154632.png)

https://games.gdevelop-app.com/game-29e46dfc-9141-477b-afbd-6376868ecfe9/index.html
1. The first one is a basic implementation. Holding space will have you hear the sound.
2. The second is with some checks, it too still plays a sound.
3. The third is a basic implementation as well, but using the sound file with a longer silence at the start (0.020 seconds)

## To Reproduce
1. Create a play sound action with a sound that starts instantly.
2. Set volume to 0.
3. Play sound.
4. Hear sound :(

## Other details
* Windows 10, Chrome.
* Beta 108

EDIT: This happens when you set the volume to any level (eg: 5, 15, 25, etc). Using 0 as an example as there should be 0 sound.

**Comment by 4ian** [comment]
Yep this is a regression in beta108. We'll publish hopefully soon-ish a version beta109 with the fix :) 
Thanks for reporting!

**Comment by 4ian** [comment]
You can also try the latest nightly version to get the fix now:
- Windows: `https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop 5 Setup 5.0.0-beta108.exe`
- macOS: `https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop 5-5.0.0-beta108-mac.zip`
- Linux: `https://gdevelop-releases.s3.amazonaws.com/master/latest/gdevelop-5.0.0-beta108.tar.gz`

**Comment by AtomicCrocStudios** [comment]
> * https://gdevelop-releases.s3.amazonaws.com/master/latest/GDevelop 5 Setup 5.0.0-beta108.exe

Can confirm it's fixed in the nightly build. Thanks a ton 4ian!
