### ISSUE TITLE
One asset from store is not available

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2584]
## Describe the bug
This asset is not working in web-app and cannot be fetched on desktop.
![image](https://user-images.githubusercontent.com/1670670/116268304-7c1da400-a77d-11eb-9838-75de8b31cf37.png)

Here the missing sprites for the animation
![image](https://user-images.githubusercontent.com/1670670/116268396-9061a100-a77d-11eb-9458-8c177b9d5db1.png)

The name of these resource and the animation use a `+` in the name. This can be the problem?
And for sure these assets cannot be downloaded on the desktop app.

![image](https://user-images.githubusercontent.com/1670670/116268601-c3a43000-a77d-11eb-8131-861dae86eefd.png)

We can't fix it without access.

## Other details
* B108, desktop, web-app

**Comment by Bouh** [comment]
When the Abandon button is pressed, what is the next step, is the missing reference to these files are imported in resources or not ?
If no i think we could improve the error message.

` There were errors when fetching resources for the project. Click on Abandon for not import the reference of these missing files in your project.
`

**Comment by 4ian** [comment]
Yes we should rename the button to "Continue with missing resources" or something like this.
The "+" is indeed an issue, I'll change this!

**Comment by Bouh** [comment]
This is done? 
(I looking for close some issues)

**Comment by 4ian** [comment]
Fixed yes!
