### ISSUE TITLE
New example: Snap example refresh

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2586]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to
* download it: https://www.dropbox.com/s/h2njg7wz3q8a48v/snap-object-to-grid.zip?dl=1
* try it: https://games.gdevelop-app.com/game-8a318576-f160-4617-9f82-c12cca1cedf8/index.html

  I confirm that any assets can be used freely by anybody, including for commercial usage.

This uses
* A new version of the snap extension that adds offsets (https://github.com/4ian/GDevelop-extensions/issues/132)
* An new extension to snap on 3 kind of hexagonal grids (https://github.com/4ian/GDevelop-extensions/issues/131)

![SnapScreenShot](https://user-images.githubusercontent.com/2611977/116274523-0caab300-a783-11eb-8aec-6a905bbecb63.png)

**Comment by Midhil457** [comment]
Hi, I just reviewed the project and it works great!

But, I found a few issues

- You have only documented the first scene. Do document all as some might not open the first scene and see the explanations

- Changing the variable "i" to something that better describes it's use would be great

- Better name for the project would be SnapToGrid and not just Snap (In the project properties)

:)

**Comment by D8H** [comment]
Thanks, I made the changes. The comments were from the previous version. I think they mostly paraphrase the events. I removed the ones I found useless and copy/paste the other ones in each scene.

**Comment by 4ian** [comment]
Looks very nice! Great job. I'll add it :)

**Comment by Midhil457** [comment]
> Looks very nice! Great job. I'll add it :)

I think you forgot to add this 

:)

**Comment by D8H** [comment]
I should do PR on the examples repository.

**Comment by 4ian** [comment]
Closing as added on the other repository
