### ISSUE TITLE
Text Entry is broken in `master`

### ISSUE THREAD

**Issue by hedlund** [4ian/GDevelop#2605]
## Describe the bug

Basically, text entry does not work when using GDevelop built from `master`. I have tracked down the culprit to be commit 50278b1ab262bd3f0c63153f0dc7819282c18f35.

If running the latest `beta108`, Text Entry works as expected. When built from `master`, Text Entry does nothing. Reverting 50278b1ab262bd3f0c63153f0dc7819282c18f35 and then building from master resolves the issue.

Note: I have only tested this in the Preview.

## To Reproduce
1. Create a Text object and add to scene.
2. Create a Text Entry object and add to scene.
3. Connect the Text Entry to the Text object using a `Change text of TextObject: set to TextENtryObject.String()`
4. Run in preview, and see that keyboard input does **not** change the text.

## Other details
* OS: Windows 10
* Which version of GDevelop are you using? Desktop built from `master`

**Comment by Bouh** [comment]
A basic solution, [in place here](https://witly.fr/test/test.html).

![image](https://user-images.githubusercontent.com/1670670/116917187-9ad4dc80-ac4e-11eb-89db-7780a7898e2a.png)

**Comment by 4ian** [comment]
> I wonder if there is a better solution than check the keys.

I wonder too. 
For now, this is also breaking the shortcuts in the preview, like the ones to open the debugger. We could argue it's the game job to handle these and notify its electron process to do something, but for now let's go back to the solution with the key code for the arrow keys. This will work because arrow keys are not used in shortcuts, and not used by text entry (and if selection handling is added one day, it should be handled using the input manager) (we could even argue that the text entry should be rewritten to use input manager entirely).

**Comment by Bouh** [comment]
> This will work because arrow keys are not used in shortcuts, and not used by text entry (and if selection handling is added one day, it should be handled using the input manager) (we could even argue that the text entry should be rewritten to use input manager entirely).

Oof i see the keycode are directly capured by `window.event` in Text Entry object :grimacing:  
I think it's great have to use the input manager for each input. After all, this is the role of the manager.

I keep this refactoring todo in mind, for the raining days. It's an interesting thing IMO.

**Comment by 4ian** [comment]
> I think it's great have to use the input manager for each inputs. After all, this is the role of the manager.

Yes :) 
There might be some update to do to the manager to be able to handle "text entered", which is more complicated than just keys (for example, there can be dead keys, for accented characters or chinese/korean/japanese characters, etc...).
In the long term, maybe the text entry is not an ideal object and should be replaced by a real "edit text" widget.

**Comment by Bouh** [comment]
> In the long term, maybe the text entry is not an ideal object and should be replaced by a real "edit text" widget.
Cool idea, don't forget it add a [Trello card](https://trello.com/b/qf0lM7k8/gdevelop-roadmap-ideas) !
