### ISSUE TITLE
New example: Unit movement for tactical games

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2612]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to
* download it: https://www.dropbox.com/s/tw7ipq4v6l9nf9e/tactical.zip?dl=1
* watch it: https://user-images.githubusercontent.com/2611977/117200816-33ed2a00-adec-11eb-90a8-91963989ff92.mp4
* try it: https://games.gdevelop-app.com/game-f415635d-f911-4817-8211-ecc5e7e2c7a9/index.html

I confirm that any assets can be used freely by anybody, including for commercial usage. I used Google icons that are free to use.

This example show how to
* move units the way most tactical games do:
  * highlight reachable cells for the selected unit
  * move the unit with a path finding movement behavior to go to the selected cell
* make a fog of war
* use a different path finding cost for each unit class (maritime, ground and air units) 

This example use these extensions:
* An updated Linked Object Tool that add new conditions and a path finding movement behavior (https://github.com/4ian/GDevelop-extensions/issues/140)
* A variable copier to copy structure variables (https://github.com/4ian/GDevelop-extensions/issues/139)

![Tactical](https://user-images.githubusercontent.com/2611977/117210813-77e62c00-adf8-11eb-88c1-680b573a4bc2.png)

**Comment by Midhil457** [comment]
Hi, The example looks and works great! 

I found an unused yellowselection.png file

Other than that it's all great and I didn't find any other issues

:)

**Comment by Midhil457** [comment]
It does make sense. But, having something that doesn't have any use out of the box is weird. Many people would be happy to just scribble a new object using piskel for experimenting.If you really want people to use it, you can set it up as an object and inform the user that they can experiment with it. 

:)

**Comment by D8H** [comment]
I think you're right I will remove it.

**Comment by Midhil457** [comment]
Hi, 
I forgot to include this issue I found :sweat_smile: , Maybe declare the scene variables, instead of declaring them in the event sheet?

- Another thing I found this time is a tiny spelling mistake, I think it is "if" and not "is"

![Is](https://user-images.githubusercontent.com/73597906/117563465-b06d5a80-b0c3-11eb-8b16-e6649593dd7a.png)

:)

**Comment by 4ian** [comment]
Very nice and well commented example. 
Thanks @Midhil457 for the review.

I went ahead and added the example in its current state :)
