### ISSUE TITLE
Edit Points - Share Same Points overriding all animation points

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2631]
## Describe the bug
You know when you swear you have changed something, only come back and fix it again. That's me right now.

In the new editor, it seems that for a split second the "Share same points for all animations" gets enabled (even if disabled) which results in all animations sharing the points.

At this point, I'd suggest anyone using 109 to not change any objects points unless you want them over-ridden :(

## To Reproduce
1. Have 2 separate animations. First one with an extra point.
2. Disable "share same points" on both animations
3. Close apply changes.
4. Re-open object + points.
5. See it enabled for a split second and all points applied to other animations.

Video showing the issue on test project: https://www.youtube.com/watch?v=6JzctEbHt3o
The test project attached. [Animation Bug.zip](https://github.com/4ian/GDevelop/files/6456186/Animation.Bug.zip)

## Other details
* Windows 10
* 5.0.0-beta109

**Comment by 4ian** [comment]
Seems like a regression indeed. This is following the refactoring of the collision/points editor.
I'll take a look (unless @nilaymaj can do it faster than me) and release a fixed version then.
