### ISSUE TITLE
Draw collisions hitboxes and points not following on layers

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2632]
If you have layers that follow an object and use the action 'Draw collisions hitboxes and points' it doesn't follow for those layers.

![Screenshot 2021-05-10 214159](https://user-images.githubusercontent.com/75917656/117759775-33cca000-b1d9-11eb-8a8b-33787b6ae3ac.png)

GDevelop version: 109
OS: Windows 10

**Comment by Bouh** [comment]
Please attach a project to reproduce the problem as requested in the template when opening a new issue.

I can't reproduce the problem, I tested several examples with multiple layer, Platformer, shooter and endless up runner works fine.
