### ISSUE TITLE
New example: City Builder

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2638]
Hi!

I'd like to submit a new example to be added to GDevelop.
Here is the link to
* download it: https://www.dropbox.com/s/6wwjfg75pyqm1qz/CityBuilder.zip?dl=1
* try it: https://games.gdevelop-app.com/game-143f99ba-13aa-4378-b1c3-50ce38efbb20/index.html

I confirm that any assets can be used freely by anybody, including for commercial usage.

It shows how to evaluate distance by roads to define rules for city builders.

This example use these extensions:
 * an updated Linked Object Tool that allows to get the distance and combine several search to build complex rules (https://github.com/4ian/GDevelop-extensions/issues/144).
 * the Isometry Helper to snap objects on a grid (https://github.com/4ian/GDevelop-extensions/issues/102)
 * the Mouse Movement without any change (https://github.com/4ian/GDevelop-extensions/issues/123)

![CityBuilder](https://user-images.githubusercontent.com/2611977/117895318-6603fd80-b2be-11eb-8cd8-e00c69821f83.png)

**Comment by Midhil457** [comment]
Hi, I reviewed the project and it was great and it works great.

I did found some problems,

- There are some typos in the comments, I found some, but I think there are more
Not sqares, neigborgs
![City2](https://user-images.githubusercontent.com/73597906/117954122-545d3d00-b334-11eb-935c-aba9e6e7b1bd.png)

- There is an empty events with only an condition

![City3](https://user-images.githubusercontent.com/73597906/117954131-558e6a00-b334-11eb-95a8-f3b370f651e7.png)

- I also suggest adding some comments just explaining what some parts do in simple terms. It took me a lot of time,to understanding some parts :sweat_smile:

:)

**Comment by D8H** [comment]
Thanks for the review. I made the changes and made a pass on the typos.
Is it the part on the city evaluation that needs more explanations? (It's fresh in my mind so I may not see what could be hard to understand, but there is already long comments)

**Comment by Midhil457** [comment]
I had a hard time figuring out how links work in the game/extension or how exactly links get to the neighbours that is being searched. When a condition checks for at most 12 links, it doesn't explain how that that number is calculated/checked. And also the cost system. You could say, I didn't understand how the whole link objects extension works :sweat_smile: 

:)

**Comment by D8H** [comment]
I see, it's hard to understand graphs on the fly if you have never used it before. I will prepare a wiki page for this extensions with diagrams.

**Comment by Midhil457** [comment]
Hi, I reviewed the project and I wasn't able to find any issues. I do have some suggestions

- Using a single object with animations representing the Palette Items instead of multiple objects added to a group. But, I wasn't able to fully making it work while testing. So, I am not sure if it is possible

- Also, as you have finished the wiki page, maybe you could include the link to the wiki so that people can learn how the linking system works. It could be helpful for someone who found it from the example list

:)

**Comment by D8H** [comment]
>     * Using a single object with animations representing the Palette Items instead of multiple objects added to a group. But, I wasn't able to fully making it work while testing. So, I am not sure if it is possible

It would need more events and be less intuitive in the instances editor. I don't mind having a lot of objects if it makes the events easier to understand.

>     * Also, as you have finished the wiki page, maybe you could include the link to the wiki so that people can learn how the linking system works. It could be helpful for someone who found it from the example list

Yes, I did it yesterday silently.

**Comment by Midhil457** [comment]
I wasn't able to find any comments that showed the wiki page's link. Did I miss it?

**Comment by D8H** [comment]
I thought you were talking of this:
![Help](https://user-images.githubusercontent.com/2611977/118357283-93c89b00-b579-11eb-8f8f-e84562a61f8b.png)

It's true that's not the 1st thing that's used when reading a project. I added a note before the link action.

**Comment by Midhil457** [comment]
That's great! But, I did find it hard to find the comment where you have added it. It would have been more visible if you added it in a comment with more visible colours (something like green) As this example is centred around linking. It would make sense to add it at the top, but the current place is still fine

:)

**Comment by Midhil457** [comment]
Hi, If you are still interested in adding it to the library, you may open a issue in the new repo

:)

**Comment by D8H** [comment]
Right, thanks you, I opened this: https://github.com/GDevelopApp/GDevelop-examples/issues/69
