### ISSUE TITLE
[Platformer behaviour] Low value of Acceleration causes jitter

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#264]
A low value of acceleration causes jitter when the platformer character collides with a wall.
Increasing the value to a very hight number reduces the jitter.

Bug report (contains example project):
http://compilgames.net/forum/viewtopic.php?f=20&t=7211

Confirmation:
http://compilgames.net/forum/viewtopic.php?f=19&t=7858

**Comment by Silver-Streak** [comment]
@4ian This seems like it would be for GD4, is this still a going concern or are we good to close this out?

**Comment by 4ian** [comment]
Let's close this, we can always re-open something else with a repro if this happens in GD5.
