### ISSUE TITLE
Crash while using an editor on a hard worked project!

### ISSUE THREAD

**Issue by Official-IceCreeperPE** [4ian/GDevelop#2654]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

I was making Isometric Minecraft with the help of the Isometric Example then a few hours later or working, the editor crashed and I tried to open other old projects but they wont open, its crashed yesterday and I never open GDevelop 5 since.
I checked my projects folder and all the porjects are fine but I'm still scared that all of a sudden the projects are corrupted and
all that hard work **GONE**

I started using GDevelop 5 in 2020 maybe in june, idk anymore, I just know I started using it in 2020. I moved from Sketchware(On android) to GDevelop 5(Windows 10 Pro)

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta105-414e825a58af5b5d709e64a43aa2718489a48475
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.16299,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta105 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash?

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment]
Closed due to no response.
