### ISSUE TITLE
Object reordering goes wrong

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2656]
In the objects list, if you drag an object somewhere higher than its current position, it works fine.
If you drag it below its current position, it goes one spot too far.
If you have A, B, C, D and try to move A between C and D, you get B, C, D, A.

Reported [on the forum](https://forum.gdevelop-app.com/t/bugs-gdevelop-interface/32670)
Confirmed on beta110

**Comment by Oxey405** [comment]
Hello ! Could we have screenshots ?

**Comment by PascalLadalle** [comment]
@Oxey405 Sure.
From left to right, initial position, expected result, actual result.
![image](https://user-images.githubusercontent.com/25978830/125301603-6d31a100-e32b-11eb-956f-af48db375a5a.png)
