### ISSUE TITLE
Changing color (background/object/...) doesn't register RED value from variables when inside quotes

### ISSUE THREAD

**Issue by ElairyxOfficial** [4ian/GDevelop#2675]
## Describe the bug
When changing the color or tint of an object, background etc. the red value is not registered if it comes from a variable and put in quotes.

## Details
These "events" color the object cyan (0;255;255)
(example images below)
> Scene variable: x = 255
> Color object: "\\"" + VariableString(x) + ";" + VariableString(x) + ";" + VariableString(x) + "\\""

These "events" color the object white (255;255;255)
(example images below)
> Scene variable: x = 255
> Color object: VariableString(x) + ";" + VariableString(x) + ";" + VariableString(x)

I think it should be unified so either both methods work or that the expression wrapped in "\"" isn't allowed anymore to avoid confusion (or possibly other bugs around it).

## To reproduce
Steps to reproduce the behavior: (example images below)
1. Create a scene variable in the events (e.g `x`) and set it to `255`
2. In an event without condition, change the background color to `"\"" + VariableString(x) + ";" + VariableString(x) + ";" + VariableString(x) + "\""` (copy/paste highlighted expression)
3. Realize that the screen is not white but cyan :(
4. Replace the background color expression with `VariableString(x) + ";" + VariableString(x) + ";" + VariableString(x)` (copy/paste highlighted expression)
5. Realize that this works and now you have a white background :)

## Project example and images
— Required events —
![GDC_events](https://user-images.githubusercontent.com/83909121/119512692-d5282a00-bd73-11eb-97be-01febf960840.png)

— Example screenshot **with** quotation marks —
Note how the red value in both examples (left/right) is very big
![GDC_withquotes](https://user-images.githubusercontent.com/83909121/119513275-5da6ca80-bd74-11eb-9f91-71b29155990e.png)

— Example screenshot **without** quotation marks —
Colors like yellow, red, gray, blue etc. work here
![GDC_withoutquotes](https://user-images.githubusercontent.com/83909121/119513293-61d2e800-bd74-11eb-8753-58c900cfb438.png)

— Project files —
[Download files .zip (6 KB)](https://github.com/4ian/GDevelop/files/6539837/color.bug.zip)

## Other details
**Personal details:**
2021/05/25 (6am PST)
Windows, Desktop application
*GDevelop 5.0.0-beta110 based on GDevelop.js 4.0.99-0-release*

**Other notes:**
Reproducible in the web-application (Chrome/Win).
Web-app: *Version 5.0.0-beta110*

**Comment by 4ian** [comment]
I think the real thing  here is for the action to not accept a color that is not entirely well formed (i.e, in the shape R;G;B).

Out of curiosity, why did you try to add quotes inside the color string?

**Comment by ElairyxOfficial** [comment]
Sorry, I don't think I fully understood your first sentence, did I phrase something badly?

For the quotes, when choosing a color with the color picker, it automatically adds the quotes so I simply assumed those were necessary and hence I replicated the format. - However, thinking about it right now, I can imagine the quotes are just the string literals so it's a string and not a number whereas "VariableString()" doesn't return a number but a string which would make sense that the quotes aren't needed with this method 😅

**Comment by 4ian** [comment]
> Sorry, I don't think I fully understood your first sentence, did I phrase something badly?

Not at all. I was explaining that in case the color is not properly formatted (like when you add extra quotes by mistake), GDevelop should not change the color at all (rather than applying only one or two components of the color properly).

> However, thinking about it right now, I can imagine the quotes are just the string literals so it's a string

Exactly :) Maybe we could set up some warnings about this in the editor directly.

**Comment by 4ian** [comment]
I've added a warning when a quote is detected inside the text :) 
![image](https://user-images.githubusercontent.com/1280130/119558791-c6546e00-bd99-11eb-8c8c-44dd87da33dd.png)

Will maybe save some time to other users or you in the future :)

**Comment by tristanbob** [comment]
Your example should probably only include numbers between 0 and 255, right?  (It shows a "300")

**Comment by 4ian** [comment]
Ah good catch 😅

**Comment by ElairyxOfficial** [comment]
Looks great, thank you!

**Comment by ClementPasteau** [comment]
Hello! 

I've taken a quick look to understand what is happening underneath the object you are using when it is rendered.
The behavior noticed is coming from the function `setColor` here: https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/pixi-renderers/spriteruntimeobject-pixi-renderer.ts#L142

It is simply splitting the string into 3 parts and setting them for the colors.
Having a color with remaining quotes could be handled, by simply adding a `.replace('"', '')` (tested with the provided example, and it works great) but I'm not sure this is a good idea, as this behavior could also happen in any other color field in the app, so we'd have to manage this everywhere in the codebase to be consistent.

I think the warning you've added @4ian is sufficient to warn people the format is not correct and we can close this issue?
