### ISSUE TITLE
Show variables references from an external events sheet in autocompletion

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2680]
#### Context
* The preference "Suggest names of variables used in events but not declared in the list of variables" is enable.
* Some variables are referenced in an external events sheet without being defined in the variable list.
* This external events sheet is linked to the main event sheet.
* The user is writing a variable name in a variable field of the event sheet.

#### Actual
* Only defined variables and references from the main event sheet appear in the autocompletion (even in the external events sheet).

#### Expected
* Variables referenced in an external events sheet should appear in the autocompletion.

### Technical solution
From this comment: https://github.com/4ian/GDevelop/pull/2665#issuecomment-848225037
> This could be done by improving the analyzer by using `GetExternalEventsDependencies` from `DependenciesAnalyzer` (and `GetScenesDependencies`) to identify linked external events and run the variables collection logic on these too (much like done in WholeProjectRefactorer).

**Comment by 4ian** [comment]
Thanks for opening this 👍 Using `DependenciesAnalyzer ` is I think the way to go. It should be what is used to work on events generally speaking (though maybe we could integrate it into the `ArbitraryEventsWorker` at some point, to avoid doing 2 passes on events - but that's not a problem here).

**Comment by Bouh** [comment]
Can you confirm this issue is solved with the linked PR just above?
If yes you can close it 💯
