### ISSUE TITLE
Invalid instruction added when exiting instruction selector

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2682]
## Describe the bug
When you have the preference "apply the dialogue when clicking outside of it" and click outside of the instruction selector, it applies even though it shouldn't be possible and adds an invalid instruction.

## Video of the bug

https://user-images.githubusercontent.com/19349038/119683285-d0cb4200-be43-11eb-80bd-3926c3180f5e.mp4

## To Reproduce
1. Go to Preferences
2. Set backdrop click behavior to apply changes
3. Go to the event sheet
4. Press on add action or add condition on an event
5. Click the backdrop
6. See invalid instruction that has been added

**Comment by Bouh** [comment]
The original PR is https://github.com/4ian/GDevelop/pull/2484
Idk what I've missed

**Comment by 4ian** [comment]
![image](https://user-images.githubusercontent.com/1280130/119694743-6b785080-be45-11eb-981e-45b37c41bec0.png)

onSubmit (aka, the action of "Ok", i.e "Apply") should not be done if the instructionType is empty. If it's empty, `onApply` should undefined/null. `Dialog` will then, seeing that onApply is null, automatically fallback to call `onRequestClose` (i.e: it will cancel).
Do you want to fix this? Should be just an extra condition in the prop.

**Comment by Bouh** [comment]
The instructions are simple but I can't make it working on my side.
I lose my time to try and retry, I get the same result (an empty unknown event) or I got crash because onSubmit isn't a function.

**Comment by arthuro555** [comment]
I think all you have to do is `onApply={onSubmit}` -> `onApply={instructionType && onSubmit}`?

**Comment by Bouh** [comment]
Oh yes, I was ready to use return with an inline if, and call onSubmit when neccesary.
I thought too much complicated, thx!
