### ISSUE TITLE
Admob Ads not displaying after update

### ISSUE THREAD

**Issue by Cromarko** [4ian/GDevelop#2703]
Admob ads not displaying. 

## To Reproduce
Sample project such as admob doesn't display any test ads at all. Even with manual compile or using Gdevelop's compiler.

## Other details
I am using Gdevelop5-beta110. I am also using my previous project but when compiled they don't display any ads or test ads at all. Apps compiled using old version of gdevelop work fine.

**Comment by 4ian** [comment]
Have you updated your admob app id for Android and for iOS in the game properties? Have you checked they don't have extra quotes? 
Can you run your app on a phone and paste here the logs from the phone (you can run "adb logcat" in a terminal if you have the Android SDK installed).

**Comment by Cromarko** [comment]
Yes, I updated my Android and iOS. No extra quotes were put.

Sorry, but I don't own an Android phone. My apps work fine with old version of gdevelop with cordova-plugin-admob-free.

**Comment by Cromarko** [comment]
I even tried "https://github.com/admob-plus/admob-plus/tree/master/examples/cordova" which is stuck at connecting to device. It used to work a few months before.

**Comment by 4ian** [comment]
Alright that's strange. I can give a look. Do you want to send me your project by email? You can find my email on my GitHub profile.
Let me know!

**Comment by Cromarko** [comment]
Ok sent them.

**Comment by Cromarko** [comment]
Test ads randomly started showing up after one day, I think Admob was updating something on their end. Sorry for wasting your time.

**Comment by 4ian** [comment]
Ok, weird but good to know! Thanks for following this up.
