### ISSUE TITLE
Example update - Text entry

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2705]
I edited the description text, and added another scene with comments for mobile input.
[My project30.zip](https://github.com/4ian/GDevelop/files/6594456/My.project30.zip)

[source](https://forum.gdevelop-app.com/t/android-virtual-keyboard-issue/33124/3)

**Comment by Midhil457** [comment]
Can you open a PR in https://github.com/GDevelopApp/GDevelop-examples

Now examples have a seperate repo

:)

**Comment by 4ian** [comment]
You can close this issue and re-open it in GDevelop-examples repository (I unfortunately can't transfer as it's another "organisation").

**Comment by Bouh** [comment]
I close this issue [continue here](https://github.com/GDevelopApp/GDevelop-examples/issues/31).
