### ISSUE TITLE
Clean code by removing dependency on SFML and the deprecated native game engine

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#2708]
We've been fully using the JavaScript based game engines for years now, so it's time to clean the codebase a bit:
- Removing SFML as it's not used anymore.
- Cleaning most part of the GDCpp Runtime (i.e: the native game engine). It's not developed nor used anymore. 
  - We can still keep interesting standalone parts (the polygon collision detection for example), though it might be worth cleaning it and just keeping references to the git history should we have the need for it later).
  - It might be interesting to keep these parts because we could have a try at compiling them to WebAssembly, so that the game engine could be in the future a hybrid JS/wasm engine.

This would allow to:
- reduce the codebase size, useful for newcomers and avoiding confusion.
- remove the compilation issues that exist on Linux because of the old version of SFML using deprecated GL apis.

Technical notes:
- This will also help to remove the unused dependencies in extensions like an old Box2D version, SPARK particle engine and all outdated C++ implementations of extensions.

**Comment by arthuro555** [comment]
Personally, I would just fully remove the C++ code, if we want to add some wasm I think rust is (as of now at least) better for targeting wasm, as it has official high quality tooling, which also creates typescript definitions and wasm module loading code for us, it also has a minimal runtime for small file sizes meaning faster loading times and it is also notorious for being fast.

**Comment by 4ian** [comment]
Do you mean the C++ code of GDCore (which might be C++, but is not a problem for now and would be huge to rewrite for no clear reason?) or of the runtime - in which case yeah I'm also open to other languages, depends on the language safety/size/performance/tooling :)

**Comment by arthuro555** [comment]
I was commenting on this part of the original comment:
> It might be interesting to keep these parts because we could have a try at compiling them to WebAssembly, so that the game engine could be in the future a hybrid JS/wasm engine.

**Comment by Bouh** [comment]
The period of transition between the old and new instruction editors will be in 15days of 2 years...
It's time to remove the old instruction editor.
It will be necessary to think about it when one of them fails because maintain two systems isn't sustainable in the long run.

**Comment by Bouh** [comment]
It's also time to remove the [compatibility code for old versions](https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Project/Layer.cpp#L73) and drop the **Beta** versions.

**Comment by 4ian** [comment]
Not removed SFML yet but should not be far from being able to do that! :)

**Comment by tberthel** [comment]
Why were the cpp native builds removed?

**Comment by 4ian** [comment]
The old engine (that only supported Windows/macOS/Linux) was deprecated, unused, not updated and unmaintained since many years now - it was removed because of this. Supporting only one engine (GDJS) in a single language is much more efficient/agile for us - and the current game engine is actually better on many things and more advanced.
Note that "native" parts can always be added later, either through modules compiled to WebAssembly or an approach like Cocos Creator (embedding a JS engine, doing native rendering).
