### ISSUE TITLE
Object.VariableChildCount() returns 0 if the arg is an array

### ISSUE THREAD

**Issue by LeopoldTal** [4ian/GDevelop#2754]
## Describe the bug
`SomeObject.VariableChildCount(SomeObjectVariable)` always returns 0 if `SomeObjectVariable` is an array.

## To Reproduce

[Full demo](https://github.com/4ian/GDevelop/files/6679362/demo.json.zip)

1. Create an object `MyObject`
2. Add an array variable `MyArray` to this object
3. Add some items to the array
4. Display `MyObject.VariableChildCount(MyArray)`
5. This should display the number of items in the array, but instead displays 0.

## Other details
* GDevelop 5.0.0-beta110 on OS X
* The bug does not affect scene variables (whether arrays or structures).
* The bug does not affect structure object variables.

**Comment by 4ian** [comment]
Good catch! 😬 This is fixed for next version (965f7aab3282ee33b478f9a5f681293a2c8aaa10), hope you can workaround this for now!
