### ISSUE TITLE
Buttons "edit collision masks" and "edit points"  to the top!

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#2755]
Is it possible to change the "edit collision masks" and "edit points" buttons to the top? We often need to edit something related to the character, and there are a lot of "sprites" and scrolling right at the end is tiring and unproductive.

I believe this is simple and easy to solve.

It would look more or less like the picture!

![03](https://user-images.githubusercontent.com/23488207/122644951-1e0e9c80-d0ee-11eb-8b9a-302d87dd087d.png)

Thanx!

**Comment by tristanbob** [comment]
@willianholtz great job identifying this problem (I have experienced it also).   It makes no sense to require scrolling to use those buttons.  

My vote is to copy your mock-up with them at the top, however, they could also live at the bottom, as long as they are outside of the scrolling area and always visible.

**Comment by 4ian** [comment]
It's true that this needs to always scroll down is frustrating. I've updated to always show the buttons on the bottom, always visible:
![image](https://user-images.githubusercontent.com/1280130/122901273-4cd28000-d345-11eb-951d-337424d8eaf2.png)
![image](https://user-images.githubusercontent.com/1280130/122901309-565be800-d345-11eb-878c-e792968e29d7.png)

**Comment by Bouh** [comment]
Same is needed for behaviors list ;)
