### ISSUE TITLE
Automatic import (more) metadata about extension into wiki

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2757]
## Description

GDevelop has dozens of useful Extensions, but many users are not aware of what they are and what they do.  The GDevelop wiki automatically adds info about every extension, but it only has very sparse details about the extension; just the short description: http://wiki.compilgames.net/doku.php/gdevelop5/extensions

## Solution suggested

On the wiki, increase the amount of information provided about each extension.  This content already exists in the GDevelop extension registry, the wiki update script needs to be modified to transfer and format it.  

### Basic info
- Extension name
- Extension icon
- Short description
- Description 
- Version
- Tags
- Help Page URL
- Author

### Bonus info
- Behavior names
  - Behavior description
  - Behavior object type
  - Property Names
  - Property Type
  - Property Label
- Functions (both behavior and standalone)
  - Function Name 
  - Function Description
  - Function type
  - Function Parameter name
  - Function Parameter description

**Comment by Midhil457** [comment]
Agreed, but won't the page get really long if the info for all the extensions are included into one page, making it difficult for anyone who is trying to find an extension from that page. The table of content for the extension page is already really long

Also how/when are wiki pages updated? Through any scripts that run on every release?

**Comment by 4ian** [comment]
Yes that's a good idea, should be easily doable by updating https://github.com/4ian/GDevelop/blob/master/newIDE/app/scripts/extract-extensions-document.js to create one help file per extension (instead of a single page for now).

**Comment by tristanbob** [comment]
I think this is done now that extensions show the full description in the wiki.
