### ISSUE TITLE
[Bug] piskel buttons

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#2759]
I'm not sure if it's something related to the GD code, but as it's built in, I decided to post it here...

![fix this](https://user-images.githubusercontent.com/23488207/123152746-4aeae880-d43b-11eb-98bd-19bb8b83b00c.png)

Piskel's screen has a few buttons above, which I've identified in red. There is a button over the other there, and I use it a lot myself to be able to select the folder that the image will be. I don't know if it's something directly related to the GD, but it's definitely something that should be fixed.

I don't know if it's just me, because I use linux and I don't know if the same happens on Windows machines!

This happens both in fullscreen and in windowed mode.

**Comment by Midhil457** [comment]
It looks fine on windows 10, and on linux (cinnamon) if I remember correctly
It might be because of how your desktop environment renders windows or something

![GDGuiBug](https://user-images.githubusercontent.com/73597906/123225831-ba6edf80-d4f0-11eb-9046-8760b1877170.PNG)

**Comment by willianholtz** [comment]
No friend, there are four buttons there. An a to selects the folder where the file will be saved.

**Comment by Midhil457** [comment]
I saw your problem. But, it seems that it doesn't happen to me. I have seen something like this happen, but not sure where and when.

Also could you specify the OS, desktop environment, GDevelop version

:)

**Comment by willianholtz** [comment]
Windows 7 Versão GD 5 110 
Arch Linux (KDE) GD5 110

old versions of GD also happened that!

Whenever I need to save a new file to a specific folder, I have to be a surgeon to click the button. LOL

In Arch linux, I tried switching environments to see if it was a problem with some kind of font, or even KDE itself. But the same!

**Comment by Bouh** [comment]
@blurymind Is an update of Piskel is possible?

**Comment by blurymind** [comment]
I can try to reproduce it and fix it :) its not piskel, but more like the wrapper code, possibly the css

**Comment by blurymind** [comment]
So it doesnt seem to happen on manjaro linux
![image](https://user-images.githubusercontent.com/6495061/127126102-81b35d09-60d8-41ff-9856-795e84eadf0f.png)


Why is this different for some people? What is your screen resolution and dpi? Perhaps electron does something funky with that?

**Comment by willianholtz** [comment]
Create a new object, add an animation, open on piskel.
This "bug", doesn't show up if you re-edit

**Comment by blurymind** [comment]
> Create a new object, add an animation, open on piskel.
> This "bug", doesn't show up if you re-edit

Thank you, that was the ticket - I was able to replicate it and a made a pr here
https://github.com/4ian/GDevelop/pull/2844

was nice and easy one :)
