### ISSUE TITLE
Scaling multiple selected objects at once doesn't scale their relative distance

### ISSUE THREAD

**Issue by l0drex** [4ian/GDevelop#2763]
## Describe the bug
When selecting multiple panel sprites and then attempting to scale that group scales every selected sprite, but not their position. I expected that scaling to behave like all those sprites where in one image and I would scale that image.

## To Reproduce
1. Go to a scene containing multiple panel sprites
2. Select multiple objects
3. Scale them by dragging one of  the corners
4. The selected objects scale, but every one on their own instead of also changing their position.

## Other details
* System: Manjaro KDE
* GDevelop v5.0.0-beta110

**Comment by 4ian** [comment]
Should be fixed by these on going changes: https://github.com/4ian/GDevelop/pull/2751
