### ISSUE TITLE
Multiplayer Platformer with Key System and more!

### ISSUE THREAD

**Issue by teamtuftuf** [4ian/GDevelop#2773]
Hi!

  Heres a example for a Multiplayer Platformer with Key System and a bit more.
  Im gonna Update this Project. 
 
(https://github.com/4ian/GDevelop/files/6750048/Multiplayer.Platformer.with.Key.System.and.more.zip)

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Bouh** [comment]
Hello, @teamtuftuf the examples submission has moved [here](https://github.com/GDevelopApp/GDevelop-examples).
Can you please open your submission on the other repository and following the suggested template for a new example.
Thank you for your example we will take a look at when the new issue will be open up on the other repo.
