### ISSUE TITLE
Empty Music category shows up in Asset Library when adding a new object

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2777]
## Describe the bug

In both the desktop and web app, if you add a new object and select the Asset Library, the "Music" category is displayed.
It is entirely empty (as it should be since Music isn't an object), but this leads to confusion for users.

Separately, you can currently only add music in the web app. Not sure if I need to submit a separate issue for that or not, but the option is not available to add from the asset library in the desktop clien.t

## To Reproduce
1. Access any scene.
2. Click **Add a new object**.
3. Click the **Search Asset Store** tab.
4. The music category will be displayed. Clicking on it or any subcategory will be empty.

![image](https://user-images.githubusercontent.com/24237149/124199845-8a4bb180-da99-11eb-8893-fb81964e56f6.png)

## Other details
* Win 10 pro
* Which version of GDevelop are you using? , both desktop client and web app.

**Comment by 4ian** [comment]
Yeah that's terrible! 😬 I'll try to think about how we can hide these categories (it's not immediately obvious, as these are sent by the server)

**Comment by 4ian** [comment]
Should be fixed now :)
