### ISSUE TITLE
Opening the door with the key

### ISSUE THREAD

**Issue by yunuselcan** [4ian/GDevelop#2778]
Hi!

  I'd like to submit a new example to be added to GDevelop.

[DoorKeyExample.zip](https://github.com/4ian/GDevelop/files/6754707/DoorKeyExample.zip)

**Comment by Bouh** [comment]
Hello, @yunuselcan 

The examples submission has moved [here](https://github.com/GDevelopApp/GDevelop-examples).
Can you please open your submission on the other repository and following the suggested template for a new example?

Thank you for your example we will take a look at when the new issue will be open up on the other repo.
