### ISSUE TITLE
Animation Editor displays incorrect framerate on high refresh rate monitors.

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2779]
## Describe the bug
I recently switched to a 240hz monitor. I noticed today that while all of my animations in my projects look accurate when previewing the game, when I go to edit the animation speed, they play SUPER fast. (Likely 4x fast)

## To Reproduce
1. Have a 240hz monitor
2. Edit an object's animations
3. Preview the animation in the editor to see it play super fast.
4. Preview the game. The animation will play "normally" or "much slower" than the preview.

Here's a video showing both sides of it. https://streamable.com/2my25r

## Other details
* Windows 10 Pro
* Which version of GDevelop are you using? B110. I have tested both on the desktop and web app.
Setting my monitor's refresh rate to 60hz does work as a workaround.

**Comment by 4ian** [comment]
Thanks for reporting, this was hardcoded to 60hz. Fixed for next version :)
