### ISSUE TITLE
Must convert to API 30 of Android 11 or else no publication possible !

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#2783]
Hi GDevelop ! I am affraid GDevelop android builds system need an upgrade to Android API 30 !
As said in the notification on the google play store console...
![API30 french](https://user-images.githubusercontent.com/61246500/124383328-31b02a80-dccc-11eb-8813-f69fc37fd413.PNG)

May I can help make this feature ?

-Oxey405

**Comment by 4ian** [comment]
Thanks for calling this out, I'll do the changes in the next version of GDevelop that should be released in the next days/weeks :)

**Comment by Oxey405** [comment]
> Thanks for calling this out, I'll do the changes in the next version of GDevelop that should be released in the next days/weeks :)
> This means right now updating cordova build to use the android app bundle packaging. API 30 can wait a bit more.

Ok thanks for the answer ! I close the issue because it is irelevant now
