### ISSUE TITLE
Animation list bug

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2784]
Cant reorganize animations in the animation list.

https://user-images.githubusercontent.com/75917656/124390713-b2a5fc80-dca1-11eb-961d-69138ff123b6.mp4

Win10 desktop app 110 nightly commit [23c2b847075ad322ca5c9994cca036b92f7c95de](https://github.com/4ian/GDevelop/commit/23c2b847075ad322ca5c9994cca036b92f7c95de)

**Comment by Oxey405** [comment]
OK I'm going to try to correct this issue, I'll let you informed !
Any ideas however ?

**Comment by Entr0py404** [comment]
@Silver-Streak Guessed it might be commit [24c13e1022ba95496ad3f58f3a50dc21e77a22b2](https://github.com/4ian/GDevelop/commit/24c13e1022ba95496ad3f58f3a50dc21e77a22b2)

So I tried that commit and the one before it and he seems to be correct
it works on the commit that was before it, and no commits after

**Comment by willianholtz** [comment]
@4ian, with this commit of yours, is this problem fixed too?

search bar below:

![01](https://user-images.githubusercontent.com/23488207/124492738-40114b80-dd8b-11eb-8ebb-f982c67e9785.png)

![02](https://user-images.githubusercontent.com/23488207/124492740-40a9e200-dd8b-11eb-9f9c-52813aab1894.png)

**Comment by 4ian** [comment]
No that's a different problem.

**Comment by 4ian** [comment]
Good catch @Entr0py404 that's clearly a regression since my latest commit here. I'll see to fix that before the next release!

**Comment by 4ian** [comment]
Fixed! Thanks again @Entr0py404 for reporting this :)

**Comment by tristanbob** [comment]
FYI - I tested this on the newest nightly and the dragging of animations works wonderfully.  Good job!

https://user-images.githubusercontent.com/8879811/125100242-1c554a80-e096-11eb-99bd-4b8c26b1e7a6.mp4
