### ISSUE TITLE
Please add ability to zoom in the event sheet.

### ISSUE THREAD

**Issue by KSKgames** [4ian/GDevelop#2791]
It would be really nice to be able to zoom in event sheet with ctrl+z. Maybe there already is a zoom feature like this, but I just don't know how to turn it on or something.

**Comment by 4ian** [comment]
Please let's open a discussion first on the forum or on the Discord - GitHub is usually only for technical discussions or for enhancements that already have been discussed in the community, following the template.  Thanks!
