### ISSUE TITLE
Adding an extension to GDeveop game soft locks game when you run it

### ISSUE THREAD

**Issue by DerpChest** [4ian/GDevelop#2792]
When I use any sort of extension and using a event or action involving the extension, the game completely freezes. No errors or anything (I don't see any errors.). I am using the lates Version Of GDevelop 5.

**Comment by 4ian** [comment]
Can you please send the game as a zip that is showing this problem?

**Comment by DerpChest** [comment]
nvm, it is just one Custom Extension that is causing the problem. Let me contact the extension dev.
