### ISSUE TITLE
Remove The Kongregate Extension from The Extension Library

### ISSUE THREAD

**Issue by DerpChest** [4ian/GDevelop#2797]
Kongregate does not accept games any more, which makes the extension useless. Probably add a gamejolt or newgrounds API extension to GDevelop 5 instead.

**Comment by arthuro555** [comment]
This should be moved to GDevelopApp/GDevelop-extensions

**Comment by Bouh** [comment]
Continue on https://github.com/GDevelopApp/GDevelop-extensions/issues/181

**Comment by arthuro555** [comment]
(issues can be moved without closing them and reopening them)

**Comment by Bouh** [comment]
> (issues can be moved without closing them and reopening them)

Not from [/4ian](https://github.com/4ian/GDevelop) to [/GDevelopApp](https://github.com/GDevelopApp/GDevelop-extensions)

**Comment by arthuro555** [comment]
Ah, right 👍
