### ISSUE TITLE
Lack of processing or Gdevelop bug?

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#2800]
Sometimes, when we put several enemies on the screen, or we put them in some places, they disappear from the game;

[Video Here](https://youtu.be/sQLy7_5-YJI?t=2)

Note that when executing, the enemy I put in the game appears normally, the second time too, but the third time I move the Enemy, it doesn't appear, it just disappears. And this happens with several enemies in the game.

Could this be an error in enemy creation, or point of origin?

![Screenshot_20210711_231411](https://user-images.githubusercontent.com/23488207/125220905-bfc47c00-e29d-11eb-80d7-22d241431376.png)

I have a lot of enemies in my game. With the tests I did throughout development, I could see that this happens randomly, as sometimes the same enemy (from the same instance) works normally.

See below for another test I took:

**There are two enemies here**
![Screenshot_20210711_231744](https://user-images.githubusercontent.com/23488207/125221338-7b85ab80-e29e-11eb-9e31-35800b552bb1.png)

**on the first attempt**
![02](https://user-images.githubusercontent.com/23488207/125221352-817b8c80-e29e-11eb-836d-4e03c9d20c20.png)

**on the second attempt**
![03](https://user-images.githubusercontent.com/23488207/125221371-85a7aa00-e29e-11eb-83a4-426de7f89945.png)

Well, I hope it's not my computer's lack of processing for this, but even so, the details of my machine are:

CPU: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
Ram: 8GB
SSD 240GB
VGA: Radeon HD 6450, 1GB
Arch Linux 5.12.15

**Comment by arthuro555** [comment]
Next time, if you are not sure if it is a bug, please report it on the forum not on github.
I'd say the most likely thing is something in your events, lack of process power shouldn't randomly delete enemies and I don't see how GDevelop could accidentally randomly delete enemies. Not to say the possibility doesn't exists. If you have a project that can pretty reliably replicate the problem, please share for us to look into.
