### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by Grif946** [4ian/GDevelop#2801]
Hi!

  I made a new design for Platformer example added some more grass made new structures. 
[Platformer.zip](https://github.com/4ian/GDevelop/files/6802605/Platformer.zip)
here is the example.

**Comment by Bouh** [comment]
Welcome @Grif946 
The new place for submitting an example is here:
[https://github.com/GDevelopApp/GDevelop-examples](https://github.com/GDevelopApp/GDevelop-examples)
