### ISSUE TITLE
Double Jump With Sound

### ISSUE THREAD

**Issue by Dead-Pianist** [4ian/GDevelop#2805]
[Double_Jump.zip](https://github.com/4ian/GDevelop/files/6812851/Double_Jump.zip)
Hi!

its a simple Platformer double jump with sound :)

I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Midhil457** [comment]
Hi, the examples need to be submitted here, https://github.com/GDevelopApp/GDevelop-examples/issues

:)

**Comment by Dead-Pianist** [comment]
Thanks for informing me!! the example submit button brought me here

**Comment by Midhil457** [comment]
This was a recent change, so the submit button hasn't been updated yet :)

**Comment by Silver-Streak** [comment]
Thanks for posting this. Closing this out so it can be submitted through the examples repo Midhil posted. Make sure to include the required info on the template there, and someone will take a look.
