### ISSUE TITLE
Mislabeling of Movement Conditions in Common conditions.

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2811]
## Describe the bug
The new Pathfinding conditions are showing up under the Common Conditions for all objects section, within the Movement subsection. Their icon and description do not indicate they are for pathfinding behavior objects, but they *only* work with pathfinding objects.

## To Reproduce
1. Open any project.
2. Add a new event.
3. Add a new condition. 
4. Expand the **Common conditions for all objects** section.
5. Expand the **Movement** section. You will see the new conditions. 

![image](https://user-images.githubusercontent.com/24237149/125886922-6b4fad29-1874-458a-a458-b047562cc6cb.png)

I've tested with a few of them, and none of them count as true unless you've selected an object with the pathfinding behavior.

@arthuro555 did some checking and found that they are categorized differently in the source, so it's likely due to them not being listed as Pathfinding related.  https://github.com/4ian/GDevelop/commit/ade075f076f3ef3eadcc8e9b27e91292f871a777

I would recommend updating the categorizing these explicitly as Pathfinding conditions, and ensuring they share the icon with the other pathfinding conditions. A few people on Discord and the forums had been confused on why these conditions weren't working because they were trying to use them with normal forces or other behaviors.

## Other details
* Vivaldi 4.0.2312.38 / Windows 10 Pro
* Tested both the desktop and the web app with beta 111 and 112

**Comment by arthuro555** [comment]
That's pretty weird, according to the source code it should categorize by extension already and put it in "Common conditions for all objects" only if the extension is `BuiltinObject`, and I am pretty sure that the pathfinding is its own extension 🤔 

https://github.com/4ian/GDevelop/blob/7b2c7b4a00dce013acfd470a39e3af51f878ba66/newIDE/app/src/InstructionOrExpression/EnumerateInstructions.js#L218-L227

**Comment by Silver-Streak** [comment]
Davy also mentioned that these shouldn't be from their Pathfinding conditions, either. Is it possible they just don't detect anything and/or have been broken for a while if they are meant to be used on forces? I was getting no results/always false/etc using forces and any other behaviors, as well.

(Forum user zizabel originally reported issues with animation switching here: https://forum.gdevelop-app.com/t/trying-to-make-character-change-between-start-of-walk-to-walk-animation/33858/17, I did some testing and couldn't get Stopped/Speed/angle conditions to ever trigger anything via forces or other behaviors either, which lead to this conversation)

**Comment by 4ian** [comment]
That's very weird, these conditions should be gone (they have been renamed to clarify these are using forces only).
I can't reproduce in the development version so that's even weirder.

**Comment by 4ian** [comment]
Actually, I can't reproduce this in beta 112. I only see this:

![image](https://user-images.githubusercontent.com/1280130/125959151-ff19692d-7f9a-4def-b115-a08305725c96.png)

And same using the new action/condition editor when you enable it in preferences.
Can you confirm the version of GDevelop that you have?

**Comment by 4ian** [comment]
This is a test game working well in beta 112, adapted from an example:

[Test game.zip](https://github.com/4ian/GDevelop/files/6831180/Test.game.zip)

See notably these conditions:
![image](https://user-images.githubusercontent.com/1280130/125960332-9f577b28-1a93-4208-8c68-5d97433ca903.png)

All of them seem to work well.

**Comment by Silver-Streak** [comment]
I updated the title to remove confusion from the pathfinding extensions. I'm going to retest locally, as I just realized I'm running b110 on my machine (although I'd assume web was b112? I'll confirm that as well)

**Comment by 4ian** [comment]
Web app is lagging behind, I'm updating it now.

**Comment by Silver-Streak** [comment]
Confirmed. In b112 I can properly detect stopped, speed, and angle via forces. 
Also they indicate that they are for forces only as well.

Unfortunately, going back to b110 I can no longer reproduce the other behavior, either, but I'd say that the updated naming already solves this issue once the web app is updated.

**Comment by Silver-Streak** [comment]
I can no longer reproduce the original issue (conditions not activating under any scenario), so either it was fixed inadvertantly in 112, or I was just foolish and messed up the condition set up when I was testing. 😄 

Either way, the naming is definitely fixed. Closing this out.
