### ISSUE TITLE
By removing an effect on a layer camera are added exponential

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2812]
## Describe the bug
By removing an effect on a layer a camera is added exponential!
It happened only when there is one layer.

## To Reproduce
1. Go to Layers
2. Add an effect to the layer
3. Don't Apply change but Cancel it
4. Save as
5. Check the game.json, a new camera has been added.

https://user-images.githubusercontent.com/1670670/125958649-e0dfe068-cdff-430b-8db7-3c7a0b320e47.mp4

## Other details
* b112, b111, b110

**Comment by Bouh** [comment]
A user face it to 100 000 cameras with this issue. It's critical @4ian

**Comment by 4ian** [comment]
Nice catch 😬 Fixed now. I'll release a new version tomorrow or monday. You can recommend to use the nightly build that is built now, that will automatically clean project files with more than 50 cameras.
