### ISSUE TITLE
Set color of light color parameter doesn't have a color picker

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#2816]
## Describe the bug
Set color of light doesn't have a color picker for easily picking the color
![Color](https://user-images.githubusercontent.com/73597906/126039241-2a1bf44d-bbd0-40fc-9ecd-8283c24f3f86.PNG)

## To Reproduce
1. Go to the event sheet
2. Open the action editor
3. Search for `light` and select `set color of light` action from the list
4. See that a color picker is not there along side the second parameter

## Other details
* Win 10
* Desktop, beta112

**Comment by 4ian** [comment]
Thanks for reporting this, a parameter is not configured properly. I'll let Clément look at this.
Hint, the Bitmap Text object is properly configured ;)  
https://github.com/4ian/GDevelop/blob/18f22470ca65de7d9e6096bce5962556d376684b/Extensions/BitmapText/JsExtension.js#L240-L253

**Comment by ClementPasteau** [comment]
Thanks for reporting! It is now fixed.
