### ISSUE TITLE
GDevelop logo on splash screen taking the whole window

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#2825]
## Describe the bug
The GDevelop logo on the splash screen fills the whole window and gets blurry when the game uses high resolution(Not noticeable in the screenshot, but noticeable when seeing it irl). It looks fine when using the default resolution
## To Reproduce
0: Create a project with a high resolution (2560 x1440)
1. Go to `properties`
2. Click on `loading screen` tab
3. click the `Run with loading screen button`
4. The Gdevelop logo will take up the whole screen and gets blurry (Not noticeable in the screenshot, but noticeable when seeing it irl)

![Screenshot (3)](https://user-images.githubusercontent.com/73597906/126356758-453f7367-2594-41c4-9d8c-cf5b95820478.png)

## Other details
* desktop version beta113
* desktop app

**Comment by Bouh** [comment]
It's an image, could be better to convert it into SVG

**Comment by 4ian** [comment]
For now, I've added a maximum width in 287a17b6344ba0047f042d07187419e67849975b :)
