### ISSUE TITLE
Asset store submission (GentleCatStudio: RPG Items)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2832]
GentleCatStudio's [RPG Items.zip](https://github.com/4ian/GDevelop/files/6861459/RPG.Items.zip)

Trello card: https://trello.com/c/KnOLOa4t/58-gentlecatstudio-16x16-pixel-art-rpg-items

**Comment by 4ian** [comment]
Looks great! Added, should appear in the assets library in the next hours :)
