### ISSUE TITLE
Arrow keys move the whole web page for HTML embedded game

### ISSUE THREAD

**Issue by drearyweary** [4ian/GDevelop#2834]
## Describe the bug
The keyboard arrow keys will move the entire web page for HTML games embedded in an iframe.

## To Reproduce
1. Upload or pick any GDevelop HTML game on itch.io or a personal site where the game is embedded via an iframe.
2. Ensure the web page is long enough to have scrollbars.
3. Click focus inside the game and use the keyboard arrow keys for up and down. The whole page will move accordingly. Ideally, the movement focus should only be limited to the game and only when the focus is on the web page should the whole page move with the arrow keys.

## Other details
This was originally reported on the forums and closed with [PR #2589](https://github.com/4ian/GDevelop/pull/2589) in beta 110, but it is still causing the behavior as of beta 112. I've tested it on Chrome and Safari, but another user [has reported it on Firefox](https://forum.gdevelop-app.com/t/arrow-keys-on-html-embedded-game-still-moving-the-whole-page/33377).

It has something to do with the preventDefault() function in runtimegame-pixi-renderer.js

**Comment by 4ian** [comment]
> It has something to do with the preventDefault() function in runtimegame-pixi-renderer.js

Yes, we had to remove the fix of #2589 because it was interfering with the text entry object. We should probably rework this object so that we can then enable the fix again.

**Comment by MechanicalPen** [comment]
The weird thing about this is I way poking around the generated javascript to try and work around this bug (I don't really get typescript yet sorry) and I noticed the following code.

```js
      document2.onkeydown = function(e) {
        if (defaultPreventedKeys.includes(e.keyCode)) {
          e.preventDefault();
        }
        manager.onKeyPressed(e.keyCode, e.location);
      };
      document2.onkeyup = function(e) {
        if (defaultPreventedKeys.includes(e.keyCode)) {
          e.preventDefault();
        }
        manager.onKeyReleased(e.keyCode, e.location);
      };
```

And I thought. "well that should work, shouldn't it?" But `defaultPreventedKeys` is an array defined as
```js
  const defaultPreventedKeys = [
    "ArrowUp",
    "ArrowDown",
    "ArrowLeft",
    "ArrowRight"
  ];
  ```
  and, at least on Firefox 92.0.1 e.KeyCode is a numeric value. changing the array to;
  
  ```js
    const defaultPreventedKeys = [
    "ArrowUp",
    "ArrowDown",
    "ArrowLeft",
    "ArrowRight",
	37,
	38,
	39,
	40
  ];
  ```
  Got the arrow keys to stop scrolling the background when the game is focused. At least on Firefox 92.0.1 and when embedded into itch.io. I have no idea what the proper fix should be but maybe this can help lead someone to a nicer solution.

**Comment by blurymind** [comment]
Do you see any scrollbars? Sounds like a css issue this

**Comment by ClementPasteau** [comment]
This should be fixed in the next release! Thanks @MechanicalPen for spotting the mistake! 🎉
