### ISSUE TITLE
Asset store submission (ghostpixxells:  Pixel Mart & Free Pixel food)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2845]
Pixel Mart: [Pixel Mart.zip](https://github.com/4ian/GDevelop/files/6889084/Pixel.Mart.zip)

Free Pixel food: [Pixel Food.zip](https://github.com/4ian/GDevelop/files/6889083/Pixel.Food.zip)

Trello card: https://trello.com/c/qW8PXpQe/50-ghostpixxells-pixel-foods

**Comment by 4ian** [comment]
Looks great! Added and should be online in a few minutes :)
