### ISSUE TITLE
Asset store submission (Arks: Dino Characters)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2846]
Arks's [Dino Characters.zip](https://github.com/4ian/GDevelop/files/6892057/Dino.Characters.zip)

Trello card: https://trello.com/c/BMr1qJn0/48-arks-dino-characters

**Comment by Entr0py404** [comment]
I updated the zip because poor packaging

**Comment by 4ian** [comment]
Looks great! Added and should be online in a few minutes :)
