### ISSUE TITLE
Asset store submission (Shikashi's: Fantasy Icons Pack)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2848]
Shikashi's [Fantasy Icons Pack v2.zip](https://github.com/4ian/GDevelop/files/6889276/Fantasy.Icons.Pack.v2.zip)

Trello card: https://trello.com/c/3eQCPYST/40-shikashis-fantasy-icons-pack-229-unique-icons-and-55-recolours-32x32-icon-size

**Comment by 4ian** [comment]
Looks great! Added and should be online in a few minutes :)
