### ISSUE TITLE
Asset store submission (0x72: Dungeon Tileset 2)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2849]
0x72's [Dungeon Tileset 2.zip](https://github.com/4ian/GDevelop/files/6892874/Dungeon.Tileset.2.zip)

Trello card: https://trello.com/c/OBBay8iC/39-asset-packs-by-0x72

**Comment by Entr0py404** [comment]
I updated the zip because of poor packaging

**Comment by 4ian** [comment]
Thanks for all your submissions, I'll take a look at them today ;)

**Comment by 4ian** [comment]
Added and should be online in a few minutes :)
