### ISSUE TITLE
Asset store submission (Alex's: 16x16 RPG Item Pack 1 & 2)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2850]
Alex's [RPG Item Pack.zip](https://github.com/4ian/GDevelop/files/6889588/RPG.Item.Pack.zip)

Trello card: https://trello.com/c/9wfnNPGo/59-alexs-assets-16x16-rpg-item-pack-1-2

**Comment by 4ian** [comment]
Looks great! Added and should be online in a few minutes :)
