### ISSUE TITLE
Instruction editor have a bugged scrolling list of parameters.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2853]
## Describe the bug
The list of parameters in the "new instruction editor" (he have 2 years old it's still new^^?) have a bad UX when we have to scrolling.

## To Reproduce
1. Add a lot of parameters in an instruction from the extension editor
2. Try to use it and fill all parameters.
3. See the issue with the scroll.

In image:
![image](https://user-images.githubusercontent.com/1670670/127737189-d0343b88-0056-40bb-9e6b-9ee45df1b498.png)

Or in video at [3:39](https://youtu.be/46Qp1WXbZMI?t=219).

https://youtu.be/46Qp1WXbZMI?t=219

[Original bug report](https://forum.gdevelop-app.com/t/extension-issue/34145)

## Other details
* b114
* W10

**Comment by 4ian** [comment]
Thanks for reporting, I've fixed this and another related scroll bug.
