### ISSUE TITLE
Asset store submission (rmocci: Pixel flag packs)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2888]
rmocci's [Pixel flags.zip](https://github.com/4ian/GDevelop/files/6950079/Pixel.flags.zip)

Trello card: https://trello.com/c/qFuNA23A/66-rmocci-pixel-flag-packs

Note: Sexuality flags where removed from the Special folder, personally I don't have a problem with the flags 
I removed them to avoid any issues within the community.

**Comment by 4ian** [comment]
Thanks! 👍 I've also re-organized folders to add "America" and fixed some names that were not properly spaced.
[Pixel flags.zip](https://github.com/4ian/GDevelop/files/6963097/Pixel.flags.zip)

Looks good, should be online soon. Thanks again!
