### ISSUE TITLE
Asset store submission (route1rodent: 16x16 RPG characters)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2889]
route1rodent's [RPG Characters.zip](https://github.com/4ian/GDevelop/files/6950166/RPG.Characters.zip)

Trello card: https://trello.com/c/5zG07BwR/67-route1rodent-16x16-rpg-characters

Note: The folder (Old Style/Guides) has "nude" characters, these are no clothes blank characters guides to make new characters.
also, I wasn't sure if (New Style & Old Style) should be renamed to (Modern & Retro) or something to that effect.

**Comment by Entr0py404** [comment]
I forgot to mention from now on I am using my own tool I made for splitting the sprite sheets. I was using Aseprite before, please let me know if there are any issues or discrepancies with these assets.
![Screenshot 2021-08-08 043334](https://user-images.githubusercontent.com/75917656/128630686-cb2baf4d-f44c-45ad-81b7-1ddeb64b6da0.png)

**Comment by 4ian** [comment]
> The folder (Old Style/Guides) has "nude" characters, these are no clothes blank characters guides to make new characters.

Let's not include them, so that we keep in the asset store only "ready to use", finished assets :) 

> New Style & Old Style) should be renamed to (Modern & Retro) or something to that effect.

Might be a good idea to use Modern/Retro :) 

> I forgot to mention from now on I am using my own tool I made for splitting the sprite sheets

Nice! I'll double check then before adding them :)

**Comment by 4ian** [comment]
Added, should be online soon-ish :) Thanks a lot! 👍
