### ISSUE TITLE
Variable dropdown menu no longer works properly since b111

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#2903]
- [x] New created variables(all types) are only available in the dropdown menu after the current condition/action has been closed and reopened.

- [x] New and existing object-variables are not available in new conditions/actions before they have even been closed and reopened once after creating.

- [ ] When adding an expression, new and existing object-variables are never available in the dropdown menu.

- [ ] When you change the object in an object-variable conditions/actions, it shows the variables for the object with which the event was opened in the dropdown menu. (should be a result of the previous problem)

Tested in b114 and b115

**edit: In b116 the first two issues are solved. The others now work if you close and reopen the action/condition and also if you open the variable manager and close it with APPLY, not with CANCEL.**

**Comment by Bouh** [comment]
Hello
Most of these issues seem aren't, in settings there is an option to enable.
![image](https://user-images.githubusercontent.com/1670670/129281804-96b68f9f-c61b-4c73-ad17-eef49f3d3a3b.png)
Or I misunderstanding the problems.

**Comment by jack-ii** [comment]
Thanks, I have tested it and can confirm that all the problems are still there, no matter if the Suggest names option is on or off.

**Comment by 4ian** [comment]
First two issues should be solved in the next version :)

**Comment by jack-ii** [comment]
I tested b116 and updated my report.
If you are bored you can also take a look at this :)
![01](https://user-images.githubusercontent.com/81538128/132501841-95a54162-03ac-4c56-b634-f12118cf81df.png)
https://jackii.itch.io/gdevelop-code-faq?secret=1

**Comment by Silver-Streak** [comment]
@jack-ii  Generally, You will need to open issue reports for other issues that are unrelated rather than linking to off site lists.

The majority of other things you have listes are exisiting feature requests on the forums, but please feel free to search the feature request forum and post any you don't find there.
