### ISSUE TITLE
Alpha channel settings has gone missing in Grid Options Color Picker

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#2918]
## Describe the bug
Starting in B115, the Alpha channel for grid options has gone missing. 

This appears to be a regression of some kind, potentially related to the changes done to have those settings persist now?

## To Reproduce
1. Load any project in B115
2. Click on the **Toggle/edit Grid** button.
3. Click **Setup grid**
4. Click the color picker. There will only be RGB options.
![image](https://user-images.githubusercontent.com/24237149/129456070-fbacafb4-256f-4708-a230-fbba792c8798.png)

5. Repeat these steps in b114. You will have RGBA available, and alpha works appropriately.
![image](https://user-images.githubusercontent.com/24237149/129456065-1dfeed85-773c-4ac3-8b30-18be79ac72d9.png)

## Other details
OS: Windows 10 Pro 
GD5 version: B114 and B115
This was reported by user MashyZ on the forums, and I've been able to reproduce it: https://forum.gdevelop-app.com/t/grid-setup-in-scene-editor-no-longer-has-alpha-options-on-color-picker/34457/

**Comment by 4ian** [comment]
It was disabled because it was never persisted and never really meant to be an option... This being said if you think it serves a purpose this can be re-added (and saved properly).

**Comment by Silver-Streak** [comment]
Based off the conversation with the user on the discord and forums, it sounds like alpha is very useful for people needing a very small grid, from a visibility standpoint.

It sounds like persistence may still be bugged in general based off: https://github.com/4ian/GDevelop/issues/2922

So if it's viable to add this back while that is being worked on, I'd bet it could be valuable.

**Comment by 4ian** [comment]
I've added back alpha, with proper persistence of the setting :) (and fixed the other issue, which was only for the black color).
Thanks for reporting!
