### ISSUE TITLE
Grid color error still persists

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#2922]
## Describe the bug

As described in the last change log:
"Fix color of grids in scene editor not properly persisted"

and closed here: #2898 

The grid has not yet been fixed.

https://www.youtube.com/watch?v=Ew_tQdYzqqk

- IDE version: 5.0.0-beta115
- Arch: x64,
- Platform Name: linux,
- System Version: 5.12.15-arch1-1,
- User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta115 (sorry) Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
This should work if you close the scene to force UI settings to be saved. But yes that a bug overall!

**Comment by 4ian** [comment]
Turns out that the grid color is properly persisted, but just not for the black color ;) I'm fixing this!
