### ISSUE TITLE
Multiple Button Presses Not Registering: Arrows + Character

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#2934]
## Describe the bug
Like most things, I first through it was my logic but I was able to replicate the issue in a basic project.

When pressing Left + Down + a, the a key IS NOT registered.
When pressing Right + Down + a, the a key IS registered.

When pressing Left + Down + s, the s key IS registered.
When pressing Right + Down + s, the s key IS NOT registered.

If you swap out the a or s key above with another key such as Space or LControl it registers fine. I am not sure how many other keys this happens with but there is clearly something _funky_ going on.

## To Reproduce
1. Open the test project, run a preview.
2. Press Left + Down + a and see that the action under that event is not fired.
3. Try the other combos to see the inconsistencies.

[Multiple Buttons Pressed.zip](https://github.com/4ian/GDevelop/files/7004404/Multiple.Buttons.Pressed.zip)
https://games.gdevelop-app.com/game-85074648-9b6b-4561-8693-6b333b2cd7e3/index.html

## Other details
* Windows 10
* Beta 115

**Comment by 4ian** [comment]
Might be related to your keyboard or your OS. Give a try at: https://en.key-test.ru/

For example using my Macbook Pro + external keyboard, I can press up to 6 keys ("6 Key rollover": https://www.keyboardco.com/blog/index.php/2016/03/what-is-nkro-our-guide-to-rollover-anti-ghosting-and-choosing-the-right-keyboard/). In your example, I can successfully press the arrow keys and then "a" and then "s" or even "a" and "s" at the same time and the texts are properly updating.

**Comment by Bouh** [comment]
For me with Azerty or Qwerty keyboard its works too.

**Comment by AtomicCrocStudios** [comment]
> Might be related to your keyboard or your OS. Give a try at: https://en.key-test.ru/
> 
> For example using my Macbook Pro + external keyboard, I can press up to 6 keys ("6 Key rollover": https://www.keyboardco.com/blog/index.php/2016/03/what-is-nkro-our-guide-to-rollover-anti-ghosting-and-choosing-the-right-keyboard/). In your example, I can successfully press the arrow keys and then "a" and then "s" or even "a" and "s" at the same time and the texts are properly updating.

Really interesting, I never considered it might be an OS or even limitation of this keyboard (fairly generic low cost Logitech). I'll look into it further on my end. Glad to know it's not a GDev issue.

Thanks again!
