### ISSUE TITLE
The platformer object bounces of the walls and grounds if its hitbox is smaller than the object itself

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GDevelop#294]
Seen in native game.

**Comment by victorlevasseur** [comment]
Bump @4ian

**Comment by 4ian** [comment]
That's strange because everything should be done according to the hitbox. Have you a test game so I can quickly check?

**Comment by victorlevasseur** [comment]
http://forum.compilgames.net/viewtopic.php?f=16&t=8285&p=58608#p58607
or
http://forum.compilgames.net/viewtopic.php?f=16&t=8314&p=58723#p58723

**Comment by victorlevasseur** [comment]
Any progress made ? (it seems GDevelop detect the collision at the right time but the new position given to the object after it is incorrect)
