### ISSUE TITLE
Restrict Behavior String property Condition Operators to "="

### ISSUE THREAD

**Issue by ClementPasteau** [4ian/GDevelop#2979]
## Describe the bug

Behavior String property conditions have too many operators, when only "=" and "≠" should be available

## To Reproduce
- Create a new extension
- Add a behavior to it
- Add a behavior property of type "String"
- Add a function to the behavior
- Add a condition to the function checking the property just added
- Notice that the condition has multiple operators available for the string (as if it was a number)

![image](https://user-images.githubusercontent.com/4895034/131115860-15da420b-d881-4bcc-adf7-8973442d0681.png)

## Other details

- Problem is coming from `MetadataDeclarationHelpers.js` and `InstructionMetadata.cpp` -> function `UseStandardRelationalOperatorParameters` is used for both number and string

**Comment by AlexandreSi** [comment]
@4ian you mean to use the parameter `optionalObjectType` of `AddParameter` to store this type? I guess we'll have to rename this parameter if that's the case
