### ISSUE TITLE
Custom size at zero add NaN in object properties

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2983]
## Describe the bug
When I check the custom size for a sprite and trying to resize with the handle, the sprite is fuckup, NaN appears for position X and Y and custom size, and the mouse is stuck with the rectangle selection for select objects on the scene.

## To Reproduce

https://user-images.githubusercontent.com/1670670/131191440-fe25920e-84fd-4077-bfc8-3e9c4cac17cb.mp4

## Other details
 All build

**Comment by willianholtz** [comment]
I reported this bug a while ago!

https://github.com/4ian/GDevelop/issues/2829

**Comment by 4ian** [comment]
Wow, pretty bad bug indeed, I'll take a look first thing when I can.

**Comment by 4ian** [comment]
Should be good now, an instance with a size of 0 can now be resized without problems.

**Comment by Bouh** [comment]
Perfect, it work fine 👍
