### ISSUE TITLE
Asset store submission (Narehop: PS4 Pixel Controller Buttons)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2987]
Narehop's [PS4 Pixel Controller Buttons.zip](https://github.com/4ian/GDevelop/files/7071201/PS4.Pixel.Controller.Buttons.zip)

Trello card: https://trello.com/c/705HHYRN/6-ps4-pixel-controller-buttons

**Comment by 4ian** [comment]
Added! 👍
