### ISSUE TITLE
Asset store submission (EgorDorichev: Pixel Buttons Set)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2988]
Egor Dorichev's [Pixel Buttons Set.zip](https://github.com/4ian/GDevelop/files/7071227/Pixel.Buttons.Set.zip)

Trello card: https://trello.com/c/ULNYlEX2/7-pixel-buttons-set

**Comment by 4ian** [comment]
Thanks!

* Renamed some Button_Xxx images to Controller Button_Xxx
* Also fixed a typo Contrl => Control
* For Key_0, Key_1, I've renamed to Key_0_1.png, Key_1_1.png, etc... to force the 0, 1 to be detected as animation name and not the sprite index :)
