### ISSUE TITLE
Asset store submission (Simple Wares: 65 button asset pack)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2989]
Simple Wares [65 Button Asset Pack.zip](https://github.com/4ian/GDevelop/files/7071244/65.Button.Asset.Pack.zip)
 
Trello card: https://trello.com/c/Vye7TZw6/80-simple-wares-gui-65-button-asset-pack

**Comment by 4ian** [comment]
Looks good, thanks! 👍 Added to the asset store :)

**Comment by Entr0py404** [comment]
Sorry I don't mean to bug you but the assets that where accepted the other day are not showing up so I thought I would bring it to your attention in just in case

**Comment by 4ian** [comment]
Ah good catch the pipeline was failing. I set up an alert so that next time I don't miss this :) Thanks!
