### ISSUE TITLE
Asset store submission (OptimusDu: Pixel Arcade Buttons & Pixel Arcade Stick and Buttons Expansion)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2992]
OptimusDu's [Pixel Arcade Stick And Buttons.zip](https://github.com/4ian/GDevelop/files/7073303/Pixel.Arcade.Stick.And.Buttons.zip)

Trello card: https://trello.com/c/gccvRDpB/81-optimusdu-pixel-arcade-buttons-pixel-arcade-stick-and-buttons-expansion

**Comment by 4ian** [comment]
Added, thank you! 👍
