### ISSUE TITLE
Asset store submission (Karwisch: PX UI - Basic)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2993]
Karwisch's [PX UI Basic.zip](https://github.com/4ian/GDevelop/files/7073306/PX.UI.Basic.zip)

Trello card: https://trello.com/c/IPTeAND4/79-karwisch-px-ui-basic

**Comment by 4ian** [comment]
Thanks for this!

I've done these changes:
- Adjectives (Blue, Green, etc..) first before the names.
- Checkbox Negative, Checkbox Blank => Make a single object called Checkbox, with Blank/Negative/Checked animations
- Pannel => panel

I've added this and should be online soon-ish :)
