### ISSUE TITLE
Object timers should have the word "object" in the description

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2999]
## Description

When trying to use a timer, users can easily get confused between a scene timer and an object timer.  One way to improve this is by making it obvious which type of timer is being referenced.  Scene timers already have the text "scene" in the description, but object timers do not.  See screenshot:

![Screenshot 2021-09-01 103926](https://user-images.githubusercontent.com/8879811/131710882-deaec3ca-e9bd-4c9e-94e3-7232a6837d3a.jpg)

## Solution suggested

**Describe the solution**

Add the word "object" to descriptions of all object timer actions and conditions (and perhaps expressions?)

**Comment by ClementPasteau** [comment]
Thanks for the fix @Bouh ! :)
