### ISSUE TITLE
Value error highlight exceeds text field [Visual Bug]

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3003]
## Describe the bug
When having a long error that goes over multiple lines, the error highlight exceeds the input field.

## To Reproduce
Steps to reproduce the behavior. Note that this is just one example and only the one shown in the image below. You can reproduce this with basically any input field.

1. Change scene variable value
2. Enter `sedutperspiciatisundeomnisistenatuserrorsitvoluptatemaccusantiumsddolorem` as value
(or use anything else that is long enough to exceed one line and is in the wrong format/data type)
3. Look closely at the end of the first line

![image](https://user-images.githubusercontent.com/83909121/132052579-d4500c55-9df2-436b-a0a4-2158896e6ace.png)

The error does not necessarily have to be one full line, it only needs to be 1) connected (no space character between important characters) and 2) be in multiple lines.

Note that some line/character highlights seem to be inconsistent. Here, the last few characters are not marked, even though the "value" is just one "word". Unfortunately, I haven't been able to find a pattern to when it's inconsistent or not.

## Other details
\* No project example needed.
GDevelop 5.0.0-beta115 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by Bouh** [comment]
Might be a Material-UI problem?

**Comment by 4ian** [comment]
I don't think so, the highlight is home made and probably the styling is not properly "aligned" with the text field :)
