### ISSUE TITLE
Rolling Ball Asset Pack by Kenny.nl

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3007]
Trello: https://trello.com/c/PJ7eoEk9/45-kenney-rolling-ball-assets

Zip: 
[RollingBallPack.zip](https://github.com/4ian/GDevelop/files/7109826/RollingBallPack.zip)

https://www.kenney.nl/assets/rolling-ball-assets
license: CC 1.0

![Preview](https://user-images.githubusercontent.com/73597906/132096452-bf610567-362a-4139-ac96-25f9f27a14bb.png)

**Comment by 4ian** [comment]
Thank you! Added in the asset store, should be online soon :)
