### ISSUE TITLE
Comment / Group options disappears when editing name [Visual Bug]

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3008]
## Describe the bug
When editing the name of a comment or group, a right click will open the options window but the text editing doesn't allow that so it's closed instantly again.

## Important note
A comment or group can only be selected without editing the name by clicking the very top or very bottom pixels or by clicking the left grip used to drag the element to a different position in the code when the name is being edited (editing state).

## To Reproduce
1. Create a comment or group
2. Edit the name of it
3. Right click to open options panel
4. Panel instantly disappears again

https://user-images.githubusercontent.com/83909121/132096927-42536ef2-232e-4074-b82a-b0f1131193b3.mp4

## What is shown in the video 

LMB on Event, selected
RMB on Comment, selected
\* Options panel opens
LMB outside options panel
\* Options panel closes
RMB on Group, selected
\* Options panel opens
LMB outside options panel
\* Options panel closes

Carefully selected Comment
RMB on Comment, selected
\* Options panel opens
LMB outside options panel
\* Options panel closes

LMB inside Comment
Changed name from "Comment" to "Comment1"
Repeated RMB on Comment and Group
\* Options panel opens
\* Options panel instantly closes
Repeated RMB on Group
\* Options panel opens
\* Options panel instantly closes

## Other details
\* No project example needed.
GDevelop 5.0.0-beta115 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by AlexandreSi** [comment]
Hi @Elairyx7301,
Have you tried it in the last version (120)? I can't reproduce it here, but i'm on Mac so I don't know if Mac is to blame.

**Comment by Elairyx7301** [comment]
Interestingly enough, it does not happen for me in the web application. A right mouse button click will exit input state and show the options for that element. Therefore, it has to be a issue that is Windows specific, it seems like it's maybe going into the same direction as what I've described - Windows is handling RMB presses differently when entering a text that other an other OS/browser

**Comment by Elairyx7301** [comment]
Apparently, this is a Windows issue that has nothing to do with GDevelop or how it handles inputs etc.. I think it's really strange that Windows cancels the action - maybe because Windows is trying to open its own option panel which will not work?

Anyway, this seems not to be GDevelop caused this so I will close the issue then 🙂
