### ISSUE TITLE
[Platformer] The character sometimes decelerates at slope junctions

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#3013]
## Describe the bug
At slope junctions, the character decelerates as if it collides an obstacle and continue without the velocity it has.

## To Reproduce
1. Climb the slop
2. Look at the "Moving/Not Moving" label
3. At slope junction, it will probably switch to "Not Moving"
4. The character decelerate as if it collides an obstacle and continue without the velocity it has.
5. It's a bit random depending on the position the character has when it collides the other platform

https://www.dropbox.com/s/4pb6kiav6qeilck/PlatformTest.zip?dl=1

## Other details
* Windows 10 and electron
* GDevelop beta 155 but this is not a regression

## Solution
* An easy fix would be to use the same margin as for platform following `Math.abs(this._requestedDeltaX * this._slopeClimbingFactor)`. This would make a regression that let the character passes some small cliff which is a less important issue (a feature maybe?) in my opinion.
* The behavior could look at the intersection of platform hitboxes, calculate the angle between the intersection edges and decide if it's a slope or a wall.

**Comment by 4ian** [comment]
Yes good catch, this should not have such a stop when moving from one slope to another while going up (when going down, things are all right it seems).

> An easy fix would be to use the same margin as for platform following Math.abs(this._requestedDeltaX * this._slopeClimbingFactor). This would make a regression that let the character passes some small cliff which is a less important issue (a feature maybe?) in my opinion.

It seems to me that this would be the proper fix. This means that the slop climbing factor is used for moving to one floor to another, which make sense - so could be a feature rather than a bug indeed. I think it's unlikely to be considered as a regression.

> The behavior could look at the intersection of platform hitboxes, calculate the angle between the intersection edges and decide if it's a slope or a wall.

Seems way more complex, and I think we could easily run into edge cases (Things like "my wall works well but if I rotate it by 1 degree, now the algorithm somehow consider it's a very steep slope, help!").

**Comment by D8H** [comment]
> > An easy fix would be to use the same margin as for platform following Math.abs(this._requestedDeltaX * this._slopeClimbingFactor). This would make a regression that let the character passes some small cliff which is a less important issue (a feature maybe?) in my opinion.
> 
> It seems to me that this would be the proper fix. This means that the slop climbing factor is used for moving to one floor to another, which make sense - so could be a feature rather than a bug indeed. I think it's unlikely to be considered as a regression.

Yes, I prefer this solution too. The only thing I'm a bit worry with this, is that the cliff height that can be crossed is dependent to the character speed so  some obstacle can be passed only at full speed. But, I think this is not a real issue because the maximum crossable cliff height will still be small and platformer usually don't use small step to make it clear to the player where they must jump.

**Comment by 4ian** [comment]
> The only thing I'm a bit worry with this, is that the cliff height that can be crossed is dependent to the character speed so some obstacle can be passed only at full speed

That's fair. I wonder if we should somehow have a slightly different logic, using for example a minimal step of 1px to compute this "margin"?

**Comment by Silver-Streak** [comment]
Any chance this "Minimum margin for slope deceleration" could be a behavior property, set to a much better default value, to allow the players to deal with edge cases if needed?

**Comment by D8H** [comment]
> Any chance this "Minimum margin for slope deceleration" could be a behavior property, set to a much better default value, to allow the players to deal with edge cases if needed?

The maximum is dependent of the max slop angle property. Using a minimum of 1 won't do any harm and it could avoid rounding errors. Setting it to more should not be useful in theory. If we spot issues, we can raise it a bit.

**Comment by ClementPasteau** [comment]
Hey @D8H - Am I mistaken thinking this issue is fixed with the latest Platformer updates?

**Comment by D8H** [comment]
> Hey @D8H - Am I mistaken thinking this issue is fixed with the latest Platformer updates?

You're right, I think the issue can be closed.
