### ISSUE TITLE
Most/all effects not working on objects unless they are also on a layer with the same effects

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#3025]
## Describe the bug

In the new B117, some effects are not working when added to an object. The same effects work fine when added to a layer. The effects WILL start working if you add the same effect to a layer (any layer).

From my testing, these are not working on Objects but do work when you also add them to a layer (Even a hidden one).  I did some testing and EVERY effect I tested from the top of the list down to RGB Separation seems to effected by this (I stopped testing at that point.

Some folks on the Discord reported this behavior, which had me start testing to discover this behavior. Tristan did additional testing on a new project and it works fine. So it seems to be something about applying it to existing projects?

## To Reproduce
1. For easiest set up, open the Not-A-Vania example. It has 2 layers that have effects on them already, but no objects. The effects are Black and White (Death effect layer) and Outline (Dash layer)
2. Add an object effect to the Hero object. Try anything (like RGB Separation).
3. Start the preview. The effect is not visble.
4. Exit the preview.
5. Change one of the existing layer effects to RGB separation, such as the one on the Death effect layer. It does not need the same settings as the object layer, just the same effect.
6. Run the preview. The effect will now be visible.
7. You can repeat this with any object and any effect. From my testing, if the effect doesn't also exist on at least one layer (even a hidden layer), it will not display on the object. The layer effect can be disabled via events on the layer, but will STILL work on the object.

## Other details
* Windows 10 Pro
* Test both on the web client and on a local install of B117

**Comment by Bouh** [comment]
[Here is a list of effects and their issue](https://github.com/4ian/GDevelop/pull/2901#issuecomment-898365492) (maybe not updated)
Feel free to copy this list here and update it with your observation.

**Comment by Silver-Streak** [comment]
|Effect name  | Status ❌/✅  | Issue |	
|--|--|--|
|Adjustement  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Advanced bloom| ❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. Needs padding on both  |
|ASCII  | ❌ |  Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Beveled edges  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Black and White  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Blending mode  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. - Effect may be better served with a drop-down list for the mode rather than an number |
|Blur (Gaussian)  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. Not seeing any issues on sides of scene. |
|Blur (Kawase)  | ❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. Not seeing any issues on sides of scene. |
|Brightness  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Bulge Pinch  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  |
|Color Map  | ❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  |
|Color Replace  |❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  |
|CRT  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  |
|Drak Night  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  |
|Displacement  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project.  (Used example displacement map from wiki) |
|Dot  |❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. (Just going to mention I hadn't messed with this before, this effect has some really need style-uses)  | 
|Drop shadow  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. - Had to add padding to avoid crop |
|Glitch  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Glow  |❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Godray  |❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. (doesn't like alpha channel (layer and object)) |
|Light Night  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Noise  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Old Film  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. I feel like it may need a padding parameter? |
|Outline  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. Needs padding of at least 2 to avoid being cropped |
|Pixelate| ❌  | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Radial Blur  |❌  | Greyed out/not available |
|Reflection  |❌   | Technically doesn't reflect if on object at all, but animation and distortion works on new project, doesn't work on existing project without also existing on a layer. |
|RGB split  |❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Sepia  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. |
|Tilt shift  | ❌ | Tested: No display on existing project without also existing on a layer. Displays fine on new project. This seems like it is cut off and needs a padding parameter |
|Twist  | ❌ | Greyed out/not available |
|Zoom blur  |❌  | Greyed out/not available |


Note: To test this, I just opened a new project with the Not-A-Vania example, opened the stage scene, and applied the effect to the Hero object. Then I just hit preview. 

To test on a new project, I created a blank project, added an object from the asset library, added the effect, then hit preview. All testing (today) done on the web app/demo only. B117.

**Comment by Bouh** [comment]
For me no need to edit layers.
Stil with not-a-vania example.

1 - Add an effect on an existing object, run preview, effect isn't visible.
2 - Close the preview, create a new object.
3 - Add the same effect on this new object.
4 - Run preview, the effect is now on the objects.

**Comment by Silver-Streak** [comment]
> For me no need to edit layers.
> Stil with Not-A-Vania example.
> 
> 1 - Add an effect on an existing object, run preview, effect isn't visible.
> 2 - Close the preview, create a new object.
> 3 - Add the same effect on this new object.
> 4 - Run preview, the effect is now on the objects.
> 
> Aside it happened for me only on Not-A-Vania example.
> Shooter, platformer, works fine.

Interesting. I wonder if it only impacts existing projects that already have existing layer effects, with existing objects? As soon as something new is added, it works fine (on the new object). 

I want to say this seems likely, because if you go to the scenes without any existing effects (like the start screen) you can apply object effects without any modifications.

What's interesting: Going to that other scene, if you add an object effect to something, then add the SAME object effect to the Hero object in the stage scene, that *also* works similar to adding the effect to a layer effect.

Other things I tried:
Deleting both layer effects (No change)
Deleting both layers (No change)
Deleting an object in the scene (No change)
Testing effects on other objects in the stage scene (also doesn't work for any existing object)

However, similar to you, adding a new object lets the effect work immediately on the new object. If the effect is the same as the one applied to Hero/another existing object, it will start working on that object as well.

**Comment by 4ian** [comment]
Fixed in 24c74af79b041207a688d45690fa9a375f008f29

There was a particularly nasty bug in the code that would, probably/according to the memory content/how unlucky you are, skip the first objects (in particular if you had layers). This is fixed and will be in the next release (hopefully soon!).

Workaround: try to put your objects that have effects... at the end of the list of objects :) This can help.
