### ISSUE TITLE
Game preview [fullscreen] disappears to background upon focus regain

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3034]
## Describe the bug
A game preview that is in fullscreen disappears/moves to background when clicking back into GDevelop after another program has focus.
(Doesn't happen when game is not in fullscreen)

## To Reproduce
1. Create new project (optional)
2. Create event: "``Beginning of scene`` | ``Fullscreen: yes``"
3. Preview game
4. Click in other program / application (Chrome, Text Editor, etc.)
5. Click back into fullscreen game preview
6. Preview is in focus but disappears

(Might be avoidable with "always | bring to front" (?) but feels "hacky")

## Video

https://user-images.githubusercontent.com/83909121/132990808-7ee332d3-1712-456c-9f29-0722513709a3.mp4

Log:
Starts preview
Clicks on other program (2nd monitor)
Clicks back into GDevelop preview (LMB once)
Brings preview back with Alt+Tab

## Other details
Windows, Desktop application
*GDevelop 5.0.0-beta117 based on GDevelop.js 4.0.99-0-release*
2-Monitor setup

**Comment by Bouh** [comment]
- This bug does not apply to the desktop export.
- I don't know if this has importance, but when the advanced preference settings "Always display the preview window on top of others" is disabled the preview windows stay in the first plan.
![image](https://user-images.githubusercontent.com/1670670/132992084-aa4afd02-e416-4193-a51c-f777459b5d8f.png)
