### ISSUE TITLE
Image of loading screen

### ISSUE THREAD

**Issue by UlisesFreitas** [4ian/GDevelop#3035]
## Describe the bug
Hi mates can anyone check if this is happening too

![immage-doesnt-exists](https://user-images.githubusercontent.com/2497411/133000095-bde269e0-8861-4cd2-ad61-44b80a9566ab.png)

Refer to this thread to see that this happen to others too.
https://forum.gdevelop-app.com/t/is-this-a-bug-custom-splash-image/35022

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. When you add a custom image and later 
2. go to Resources and remove all unused images and 
3. go back to the loading screen you can clearly see that says the resource doesn’t exist in game

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Windows 10
* GDevelop 117

**Comment by 4ian** [comment]
Thanks for reporting! This is definitely an issue to fix, and fairly easy to do. 

@ClementPasteau Can be a good first issue for Alexandre :) Hint: `Project::ExposeResources`/`LoadingScreen` to fix in the C++ codebase.
