### ISSUE TITLE
Custom collision masks should start with the default collision mask (instead of 32x32)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3037]
## Description

The default collision mask matches the size of the object (AABB).  When user creates a new collision mask, a 32x32 collision mask appears in the center of the object.

This will cause some users to think the default hitbox was 32x32 (this is what I concluded)

![Screenshot 2021-09-10 223214](https://user-images.githubusercontent.com/8879811/133000322-67427a0a-754a-475a-bf4b-bfbd665576a8.png)
![Screenshot 2021-09-10 223134](https://user-images.githubusercontent.com/8879811/133000325-e72c6775-928c-41af-b98d-1d844b0bed7a.png)

## Solution suggested

When a user creates a new collision mask, make it the same size and location as the default hitbox (the outside corners of the object).

**Comment by 4ian** [comment]
Would make sense indeed!
