### ISSUE TITLE
How to backup gdevelop 5 project?

### ISSUE THREAD

**Issue by secretic** [4ian/GDevelop#3039]
**Hi everyone!**
I was creating my project in GD5, later I accidentally opened its file .json through notepad and after that the project became corrupted. I would use autosave, but it is also damaged....

**Comment by blurymind** [comment]
I would recommend hosting your project on github. Gdevelop itself has no
git integration, but you can use a free client such as gitkracken or even
vscode to commit changes to github. That way it will be easy to revert them
later on.
