### ISSUE TITLE
Add color picker for color tweens

### ISSUE THREAD

**Issue by ElairyxOfficial** [4ian/GDevelop#3040]
## Short Description

"Object color tween" action has no color picker.

## Description

When using a color tween, the final color ("To color") field requires a string for the color in the "r;g;b" format.
There is no color picker so choosing the correct color is difficult or requires to copy/paste the rgb string from another color picker.

## Solution suggested

Add color picker to "color tween" action

## Current action options

![colorPicker](https://user-images.githubusercontent.com/83909121/133101743-f54c3b13-b9c8-442e-b285-9e1a9a240350.png)

## Solution Example Mockup

![colorPickerMockup](https://user-images.githubusercontent.com/83909121/133102473-cfc47d7a-6746-4f14-95ae-1616678a1082.png)

**Comment by 4ian** [comment]
Good idea, should be a matter of updating a parameter! 
@AlexandreSi could be a good first issue ;)

**Comment by SriSatyaT** [comment]
Is anyone working on this issue? If not I want to give it a shot.

**Comment by AlexandreSi** [comment]
I planned to work on it tomorrow, but if you want to work on it, I'd be happy to help and review!

**Comment by AlexandreSi** [comment]
@SriSatyaT I just merged a change for this issue, feel free to ask any question on it, I'll try my best to answer it!
