### ISSUE TITLE
Zoom in the eventsheet

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3041]
A quick win for a good first issue can be to add the zoom in/out in the event sheet.

## Description
Actually, there is no way to increase the size of the font in the event sheet unless we're in a browser but the whole page is zoomed.

## Solution suggested

In `<Eventsheet>` component we can add a font style size in **em** unit to increase or decrease the size of the whole event.
With the  `<Eventsheet>` component we have to put on a listener for `Ctrl+Mouse wheel Up / Down`, linked to the font size on the component.

- [ ] Control would be `Ctrl+Mouse wheel Up / Down`
- [ ] This zoom value should be saved in the local preference.
- [ ] Event sheet must be updated in the meanwhile.
- [ ] There is some CSS to fix for the comments and groups.
- [ ] Must prevent the default behavior for the browser.

Here the idea:

https://user-images.githubusercontent.com/1670670/133116656-72303956-9ce7-4159-a85b-39cbd8d47c38.mp4

**Comment by Silver-Streak** [comment]
I love this idea.  

Just to call out: As a general rule of accessibility, you should always have a keyboard alternative for mouse scrolling in your controls. This is to cover for users who are using accessibility input options without scrollwheels, or those with laptops that do not have virtual scroll wheels on their touch pads.

Something like ctrl + plus/minus key would likely cover that, too.
