### ISSUE TITLE
Effects do not work for objects that share the same resources in different scenes.

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [4ian/GDevelop#3044]
## Describe the bug
Effects do not work for objects that share the same resources in different scenes.

This issue may be similar to # 3025.

## To Reproduce
1. Add a sprite to scene A.
2. Add a sprite to scene B using the same resources as scene A.
3. Add an effect to the scene B sprite and place it in the scene.
4. When I preview Scene B, the effect is not working.

_The order of the list of scenes is:
Scene A
Scene B_

## Other details
* Windows 10
* Test both on the web client and on a local install of B117

**Comment by Silver-Streak** [comment]
This looks like it could be related to the same thing here. https://github.com/4ian/GDevelop/issues/3025
To confirm, can you try adding an empty layer with the same effect on scene B and see of it displays?

That should indicate to the devs if the new fix in the next version will solve this too.

**Comment by PANDAKO-GitHub** [comment]
When I added an empty layer with the same effect to scene B, the object effect worked.

I hope the new version solves this problem.

**Comment by Bouh** [comment]
You can test the new version with the [nightly build,](https://github.com/4ian/GDevelop/blob/master/newIDE/docs/Nightly-Builds-and-continuous-deployment.md) let me know.
Make a backup of your game before, nightly build can break games.

**Comment by PANDAKO-GitHub** [comment]
I have confirmed that this issue does not occur with nightly build (117).😊

**Comment by 4ian** [comment]
Thank you for confirming! Closing this then :)
