### ISSUE TITLE
[Asset] Cards and Dices by Kenney.nl (Not Reviewed)

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#3047]
* Source: https://www.kenney.nl/assets/playing-cards-pack
* Package: https://www.dropbox.com/s/eh8eg60acft4u3i/Playing%20Cards%20Pack.zip?dl=1
* Ticket: https://trello.com/c/PJ7eoEk9/45-kenney-rolling-ball-assets

The original card margins are cropped so default hitboxes will work directly.

**Comment by 4ian** [comment]
> The original card margins are cropped so default hitboxes will work directly.

Yep that's the best thing to do for now!

I've renamed Large Cards to Large Card (as it's a single object). Added a "pixel art" tag and fixed Kenny => Kenney in the license.

Otherwise looks great, thanks for packaging this 👍
