### ISSUE TITLE
Extension long description bug

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#3067]
## Describe the bug
in extension, if you have 2 functions, go to first one and add long description to its parameters, and then jump to the next function and you will see you also got Long description created in there, and to make this disappear you just go to config and then back to parameters section and they will be gone

## To Reproduce
1. Create new extension
2. Create 2 new functions
3. Go to function number 1
4. Add 3 parameters
5. Go to function 2
6.  Add 3 parameters
7. Got to function 1
8. Add long description for all parameters
9. Go to function 2
10. You will find that you also got long description in their even tho you only made them in function 1
11. To make them gone go to Config page
12. And then back to parameters
13. They will be gone from function 2

* Example link:
[Long description extension bug.zip](https://github.com/4ian/GDevelop/files/7191328/Long.description.extension.bug.zip)

![long description bug](https://user-images.githubusercontent.com/81715237/133920629-64a3f5bb-7f13-4c6d-837a-ea5243d6e64b.gif)

* Windows 10 pro
* GDevelop 5.0.0-beta 117 / Desktop

**Comment by 4ian** [comment]
Agree this was a bit confusing to have these long description fields shown even after changing to another function. Fixed for next version!
