### ISSUE TITLE
Disabled action/condition highlight exceeds event box [Visual Bug]

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3070]
Not a big bug but still looks rather odd.

## Describe the bug
When selecting an action (or condition) that has multiple lines in the event sheet that is inside an disabled event, the component highlight will partially exceed the appropriate box.

## To Reproduce
1. Create an event
2. Add an action like ``set variable to``
-> Condition will also work but is less visible
3. Enter very long value
-> Goal is that the event sentence is multi lines
4. Disable the event
5. Select/Click on the action
6. The action highlight exceeds the event box - or here the action box

## Images
![disabledEvent](https://user-images.githubusercontent.com/83909121/134025093-b92715be-e530-4953-ae41-a6e2a9421a1e.png)

Note that when the ``=`` symbol is in a new line as well, it will show another outline:
![image](https://user-images.githubusercontent.com/83909121/134025676-57ede331-ec45-48e8-be1e-68ef5603701a.png)

## Other details
\* No project example required
GDevelop 5.0.0-beta117 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by ClementPasteau** [comment]
Took a quick look at ouf curiosity.
It's really strange, it seems like the combination of:
- the DOM elements present (<img>, <span> ...)
- the low `opacity` applied on the `<span>`
- the `outline-style: auto` applied on the `<div>` by the browser, through the `:focus` prop
creates a bug :)

Couldn't find a good reason as to why!

**Comment by Elairyx7301** [comment]
Thank you ClementPasteau for the research! 👍
Seems like no one really knows how to fix this and I don't mind, since it's nothing serious or impacting and solely visual. I will close this issue now, anyone can ping me here or in the Discord if needed :)
