### ISSUE TITLE
Sudden editor crash when moving/removing specific extension parameter

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3093]
I have no idea why this happens or what could cause it. I'm sorry for the lack of information I can provide but I thought I still submit it, maybe one of the more experienced can see something suspicious or faulty. Parameters, method names etc. might look weird because I was in the middle of work.

## Describe the bug
The editor crashes when deleting this specific extension parameter. After unsuccessfully trying to move the parameter up/down in the list, most parameter option functionalities seem to be broken and upon deleting the "faulty" parameter, the editor crashes.

## No guide how to reproduce
I have no idea how this happened in the first place. I moved parameters around, rephrased labels, added and removed parameters - the usual and basic stuff, nothing special.

## Video

The video shows the crash in the custom "CameraZoom" extension / "CameraZoomCamera" action at the very bottom.

https://user-images.githubusercontent.com/83909121/134699726-d5576742-627d-4674-aed0-45c85683c839.mp4

## Game Files

[camZoomExtension_crashFiles.zip](https://github.com/4ian/GDevelop/files/7226796/camZoomExtension_crashFiles.zip)

## Other details
Can't be reproduced "just like that" in a blank project by adding 8 parameters and trying to move the 8th one.

GDevelop 5.0.0-beta117 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by tristanbob** [comment]
This has happened to me and a few others.... in fact I think it is the same as this:

https://github.com/4ian/GDevelop/issues/2729

**Comment by 4ian** [comment]
Very nice video, I was able to reproduce an error that is leading to a crash 
![image](https://user-images.githubusercontent.com/1280130/134704720-1ed552e2-6ecd-44cd-8157-63779c807a7d.png)

I'll take a look now

**Comment by 4ian** [comment]
Fixed :) I would recommend avoiding moving up parameters that you newly created. If you do, please be sure to save first, close/reopen the project and then attempt the move.

**Comment by 4ian** [comment]
Also thanks a lot @Elairyx7301 because it really helped narrowing down the problem!
