### ISSUE TITLE
Dialogue Tree Extension: DialogueTree::Variable only returns the correct value if dialogue is running

### ISSUE THREAD

**Issue by MechanicalPen** [4ian/GDevelop#3097]
## The bug
When using the Dialogue Tree extension's expression DialogueTree::Variable("someVariableName"), the expression gives a value of 0 unless the condition Dialogue is running would return true. This makes it difficult to use dialogue variables to control game state.

## To Reproduce
1. use Dialogue Tree to run dialogue
2. have that dialogue branch set a Yarn variable
3. end the dialogue (Dialogue is no longer running)
4. attempt to use that variable in an expression
5. See that the expression gives 0

## Other details
* The Set dialogue state variable action does not work this way; dialogue variables can be set at any time during the game. At the very least setting a dialogue variable and getting a dialogue variable should behave consistently.

**Comment by blurymind** [comment]
Yes unfortunately the action  sets it directly to the running instance of
bondagejs. This is what is used by the parser to evaluate the dialogue flow
unfortunately.  You do however have actions to get it and set it, so in
theory should be able to store it to a variable before stopping it and
restore it from the same variable too.

One simple fix for this would be to make gdevelop keep the state while the
game is running and set it to yarn.

There is also the fact that the instance of bondagejs doesn't really get
destroyed between dialogue interactions. If that happened, the demo game
wouldn't really work as expected.

I am not sure why you are manually stopping it. To be fair I haven't looked
at the dialogue tree extension for some time now. Maybe I should revisit it
again soon

**Comment by MechanicalPen** [comment]
The expression DialogueTree::Variable uses `gdjs.dialogueTree.getVariable` to do its job. `gdjs.dialogueTree.getVariable` checks `this.dialogueIsRunning` and if dialogue isn't running, returns ''. Simply replacing `this.dialogueIsRunning` with `this.runner && this.runner.variables` fixes this issue for me so that's what I ended up doing.

I am not manually stopping dialogue at any point; dialogue finishes and then in some other game scene (not in dialogue) I want to use "Compare dialogue state boolean variable" to show or hide a sprite. Using dialogue variables for game state as well as dialogue is very convenient.

**Comment by blurymind** [comment]
I guess it makes sense. Would you mind making a pr with your change? I will
help review it if it helps.

**Comment by MechanicalPen** [comment]
I actually just monkey patched the method in my game as I'm in the middle of a game jam. I'll attempt to submit a PR over the weekend.

**Comment by MechanicalPen** [comment]
https://github.com/4ian/GDevelop/pull/3127

**Comment by 4ian** [comment]
The fix looks good, thanks for submitting this! 👍 Closing this issue now that this is solved.
