### ISSUE TITLE
Empty Authors/Usernames bug

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3113]
### Empty author names
Empty author names can be added by:
1) Type fast and press enter before the search result come
2) Input wrong user names

The other problem is that if there is a empty author name and the project properties is re-opened, all the authors are remove, no matter if the usernames are valid. **The valid usernames are only removed when there are more than two empty usernames**
 
Video provided below:

https://user-images.githubusercontent.com/73597906/135487446-c20436e0-c993-40da-b08e-e0ed6a969a09.mp4

### Empty Usernames

There can be empty usernames/ with spaces like seen in the video below

**If it's an empty username, it won't come up in the author search (Not shown in video)**

https://user-images.githubusercontent.com/73597906/135487435-cb66a7d6-b133-4c80-a55b-3462fb86f007.mp4
## Can't get my username back
I was changing my username to empty, with only spaces, etc.. back and forth and recording the bug with the empty username. Now I can't get my user name back (`Leo Red (Midhil)`), is there any solution? It is definitely a bug

![myusername](https://user-images.githubusercontent.com/73597906/135488745-c3bc83d7-3fa8-48cc-95be-4ea00313681f.png)

## To Reproduce
The step to reproduce can be seen in the videos :)

## Other details
* Linux Mint 20.2
* beta118

**Comment by 4ian** [comment]
Thanks for the (very detailed) report! We'll take a look with @ClementPasteau to robustify this 👍👍

**Comment by 4ian** [comment]
Actually, your username seems to be properly Leo Red (Midhil) already - can you double check by re-opening your profile page?

**Comment by Bouh** [comment]
Why not using [this](**url**) `bool Project::ValidateName(const gd::String& name)` as for object and scene name?
It should be a problem if people add fancy ASCII art? Or there is no incidence?

**Comment by Midhil457** [comment]
> Actually, your username seems to be properly Leo Red (Midhil) already - can you double check by re-opening your profile page?

Now it's fixed. I think Clement fixed it.

Another bug, if I am correct. On Linux (AppImage) The user isn't logged in after re-opening Gdevelop. 

:)

**Comment by Bouh** [comment]
Non-ASCII chars fixed in:
https://github.com/4ian/GDevelop/pull/3115
https://github.com/4ian/GDevelop/pull/3120

**Comment by Bouh** [comment]
> Another bug, if I am correct. On Linux (AppImage) The user isn't logged in anymore after re-opening Gdevelop.

On Windows too!
Even after cleaning my preferences files, after each opening of GDevelop app the account is logout.

**Comment by arthuro555** [comment]
> Another bug, if I am correct. On Linux (AppImage) The user isn't logged in anymore after re-opening Gdevelop.

Same for me. Also, this description in the project properties is not properly formatted (No majuscule and dot), and gives a very unprofessional look:
![image](https://user-images.githubusercontent.com/19349038/135719027-c0f29aec-ca2c-454b-834d-2e4c6554609b.png)

**Comment by ClementPasteau** [comment]
Thanks for spotting this @arthuro555 - We'll tidy it up 👍

**Comment by ClementPasteau** [comment]
re-opening to investigate Windows & Linux account logout on refresh
