### ISSUE TITLE
Setting object effects parameter BUG when creating and destroying an object many times in a row.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#3126]
## Describe the bug

When creating a sprite that has an effect (tested with Brightness or Adjustment) and then destroying it many times in a row.
After a few repeats the last created sprites effect that should be set as a value between 0 to 1 is not working properly.

## To Reproduce

The example creates an object and then changes the brightness value that is the angle from the object to mouse cursor divided by 360 and added with 0.5 to make the value in the range 0 to 1.

the first iteration works as intended, then create and destroy the object a few dozen times and then the last object will go from 0 to 1 in only 45 or so degrees instead of the full 360 degrees.

The brightness effect setting returns to normalish when you create many more objects in a row and delete them all at once.

I have recreated this issue and tried discussing it in discord and seems that it's not working properly.

Attached is the example project and a video showing the problem.

![image](https://user-images.githubusercontent.com/90930609/135663833-4830bdd5-faba-4373-a841-f559559a0c6f.png)

https://user-images.githubusercontent.com/90930609/135663260-5856599f-f81c-44dd-ab67-482ea0cff92d.mp4

[Brightness bug example.zip](https://github.com/4ian/GDevelop/files/7269081/Brightness.bug.example.zip)

## Other details

OS Windows 10
GDevelop version 118

**Comment by Silver-Streak** [comment]
This appears to be a duplicate issue of https://github.com/4ian/GDevelop/issues/3062

@Bouh @4ian can you confirm? I'd like to merge out the info and close the duplicate if so.

**Comment by 4ian** [comment]
99% sure this is linked - there seems to be issue with some effects values though I'm not sure why yet.

**Comment by Silver-Streak** [comment]
@VanCastar Thanks for posting this bug. I'm going to merge your info with #3062 and close this one out.
