### ISSUE TITLE
That "get a quote" form is supposed to send an email to support@mule2gopro.com which it didn't when I tested it. It doesn't appear to go anywhere but need that corrected to send an email to us.

### ISSUE THREAD

**Issue by yiniam** [4ian/GDevelop#3134]
## Describe the bug

Please double check that the bug is not already reported in the issues list.

## To Reproduce

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Which version of GDevelop are you using? The desktop app or the web-app?
* Add any other context about the problem here.

**Comment by Bouh** [comment]
@4ian please ban @yiniam for opening 3 new bug report with SPAM.

**Comment by 4ian** [comment]
Yep, done!
