### ISSUE TITLE
Rotated instance coordinates are not rounded (even if told to by behavior)

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3143]
## Describe the bug
When rotating (and moving) any object in the scene editor, the coordinates are not rounded.
This not only applies to regular objects/instances but also to the ones with the "Platform Character" behavior added and the "Round Coordinates" option enabled.

## To Reproduce
1. Create an object
2. Instance it in the scene
3. Rotate it
4. Move it
5. See 13-digit x/y coordinate values

## Video

https://user-images.githubusercontent.com/83909121/136261409-e48463f2-ddcd-46ac-a163-711eda24aee6.mp4

## Is it a feature?

Is there a good application for using rounded coordinates in the first place? I might be able to see having instances at coordinates .5 or .25 but to me those seem like very rare uses and other than that I can't seem to find other cases where such would be necessary - I'm welcoming being taught differently for the sake of it :)

## Other details
GDevelop 5.0.0-beta119 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by 4ian** [comment]
This is a mostly buggy/not working feature that is actually being removed as part of a general improvement of the Platform behavior here: https://github.com/4ian/GDevelop/pull/3009 ;)

**Comment by Elairyx7301** [comment]
Thank you @4ian for the fast reply! Sorry, I didn't see that issue before posting but nice to hear that it's already in the works! Maybe there also should be a "Round Coordinate" option for all objects but I think that's a topic for another day :v
I will close this issue then :)
