### ISSUE TITLE
Pressing a letter in the project manager breaks it

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3160]
It seems that pressing any letter while the project manager side menu is opened breaks the menu.
As you can see, the scene list is emptied while the project has a scene.
![image](https://user-images.githubusercontent.com/25978830/136668717-baae2c03-60ac-4d11-8569-43b0638cc7a5.png)

GD5b119
[source](https://forum.gdevelop-app.com/t/keyboard-shortcuts-project-manager/35498)

**Comment by AlexandreSi** [comment]
It seems to me that pressing a letter when the project manager activates the search/filtering feature. Or is it another issue you see?
![image](https://user-images.githubusercontent.com/32449369/136748982-e43f4653-ef9f-4729-9bad-c49d5bf5be96.png)
