### ISSUE TITLE
Endless loop of inclusion when including events into the same scene

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#3186]
## Describe the bug
Hello ! There is a bug when previewing and compiling that makes an endless loop of events inclusion.
Basicly, you can include events of scene A into scene A so when compliing GDevelop tries to include scene A into scene A wich include scene A into itself etc... (a little bit like inception)

## To Reproduce
1. Create a scene (let's call it "sceneA")
2. click on "Choose and add an event" in the top bar.
3. Choose to include events from sceneA
4. Click on Preview
5. Watch as GDevelop gets into an endless loop of including scene into itself
## Screenshot
![screenshot of the way to do the bug](https://user-images.githubusercontent.com/61246500/138493239-9abf18ce-79a8-452f-b655-d80ca002b675.png)

## Other details
* WIndows 10
* Desktop v. 5.120
* Easy to fix issue

#3228

**Comment by AlexandreSi** [comment]
Closing this issue as you seem to have fixed the issue yourself! Congrats!
