### ISSUE TITLE
User isn't logged when the app start

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3189]
## Describe the bug
The user isn't recognized when debugger and exports are used before we open the profile.

## To Reproduce

1 - Log in the user
2 - Close GDevelop and open up again
3 - Make an export or use the debugger even with a pro plan subscription message appearing.
4 - Open the profile the login is in process in a short time and succeeds.

https://user-images.githubusercontent.com/1670670/138523951-4bc660f3-8518-4d90-bcab-8cb8de607a65.mp4

## Other details
[Original bug report](https://forum.gdevelop-app.com/t/account-authorization-during-export/35808)
GD 5.0.120 and Nightly build

**Comment by 4ian** [comment]
Closing as fixed for next version
