### ISSUE TITLE
Add "toggle" action to settings that only have 2 states (such as "visibility")

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3195]
## Description

When users want to change the state of a setting that has two values, they must add extra events to detect if the state was toggled.  

![Screenshot 2021-10-23 150008](https://user-images.githubusercontent.com/8879811/138571645-73cc74b9-8d16-42c3-8103-44bad478be22.png)

## Solution suggested

Add an action to "toggle" the state for all settings that only have two states
- Object visibility (show/hide)
- Layer visibility (show/hide)
- Behaviors (enabled/disabled)
- Others?

**Comment by Bouh** [comment]
Partially done, it's available for boolean variables.
![image](https://user-images.githubusercontent.com/1670670/149673531-2eae0b1f-e50d-4d96-a733-22793ab543c8.png)

As this is a request and not an issue I convert it to a discussion.
