### ISSUE TITLE
[New Asset Pack] Kenney Isometric Pack

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3206]
Art: https://www.kenney.nl/assets/isometric-blocks
Artist: https://www.kenney.nl/
License: https://creativecommons.org/publicdomain/zero/1.0/ (CC 1.0)
Zip: 
[Kenney-Isometric-Pack.zip](https://github.com/4ian/GDevelop/files/7426488/Kenney-Isometric-Pack.zip)

![Preview](https://user-images.githubusercontent.com/73597906/139075634-089ca662-0f92-4002-95c1-5ae843a22530.png)

**Comment by 4ian** [comment]
@Midhil457 Sorry for taking so long on these! I'll add them today hopefully to the asset store ☺️ Thanks for packaging this!!

**Comment by Bouh** [comment]
@4ian let me give a try to add this asset pack ;)

**Comment by Bouh** [comment]
This assets pack has been correctly added, thank you @Midhil457 !
![image](https://user-images.githubusercontent.com/1670670/140567749-8a921c36-3f17-4580-b73b-e32c368c53c3.png)
