### ISSUE TITLE
Improve readability of the "+" event menu

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3209]
## Description

The "+" (plus) menu lets users insert special event types.  

There are a couple of entries with ambiguous names:
- "Group" (could be confused with object groups)
- "Link" (it is not obvious what is being linked)
 
There are two redundant entries that have dedicated buttons a few pixels to the left:
- "Standard event"
- "Comment"

## Solution suggested

Provide additional wording on ambiguous types:
- "Group" => "Event group"
- "Link" => "Link external event"

Remove redundant entries:
- "Standard event"
- "Comment"

![Screenshot 2021-10-28 090605](https://user-images.githubusercontent.com/8879811/139286497-47336119-ed8d-41b8-b7a0-3540b36140ec.jpg)

**Comment by tristanbob** [comment]
I think this is complete, based on @Midhil457 pull-request being merged.

**Comment by 4ian** [comment]
I think this is good now yeah, thanks @Midhil457!

> How can the order of the actions in the drop down be changed? The order of the actions doesn't have any relation with how it is in the file. It would make sense to have the most used on top than at the bottom

It's indeed arbitrary (according to how it's stored in memory or declared in the C++ I guess). 
You could do some sorting in the menu directly:
 https://github.com/4ian/GDevelop/blob/d6d4569dbf8a2acc04f36fdea1dc5adea36d3f08/newIDE/app/src/EventsSheet/Toolbar.js#L57-L66

If you want to do something it could be there (sort them, add a divider between some, make some categories?).
