### ISSUE TITLE
Improve wording on particle emitters

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3216]
## Description

Wording on particle emitters is not intuitive.

![Screenshot 2021-10-29 201330](https://user-images.githubusercontent.com/8879811/139516953-ffaa8cb5-3490-4759-8643-da82856d29b5.png)

## Solution suggested

Particles kind -> Particle type

Point -> Circle
Line -> Rectangle
Texture -> Image

**Comment by Bouh** [comment]
You can start in this file:
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ObjectEditor/Editors/ParticleEmitterEditor.js#L58-L69

**Comment by tristanbob** [comment]
Thanks for the tip!  I'll create a PR.

**Comment by tristanbob** [comment]
Closing this as PR is created: https://github.com/4ian/GDevelop/pull/3217

**Comment by Bouh** [comment]
Please consider:
https://github.com/4ian/GDevelop/pull/3217#pullrequestreview-795114822
