### ISSUE TITLE
Improvements to Instances List

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3219]
## Description

The instances list provides great information but is missing some basic capabilities. 

![image](https://user-images.githubusercontent.com/8879811/139564107-d6dd03fa-9472-4fe7-b5e5-da9fe5680d49.png)

## Solution suggested

- Add the ability to sort by clicking on the names of the columns (clicking twice reverses the sort)
- Add the ability to select an instance and hit the delete key (and confirm delete)
- Add the ability to lock/unlock by clicking on the lock icon
- Add the ability to multi-select (great for mass deletion)
--Not sure what to do with Properties panel... either disable it or make changes apply to all selected items?

**Comment by 4ian** [comment]
All good ideas!

> --Not sure what to do with Properties panel... either disable it or make changes apply to all selected items?

That's already how the properties panel is working ;) You can select multiple instance sand changes will apply to all of them.

**Comment by Bouh** [comment]
Adressed in #3343
