### ISSUE TITLE
Light with Texture doesn't work properly when touching Light obstacle object 

### ISSUE THREAD

**Issue by ukStream1** [4ian/GDevelop#3224]
## Describe the bug
Light with texture doesn't work properly when coming in contact with Light obstacle object
https://gfycat.com/singlecriminalabalone

![image](https://user-images.githubusercontent.com/1670670/143503823-088a60f9-4190-4e75-bbe0-6ef2a83e8e2d.png)

## To Reproduce
1. Add Light
2. Set it's texture (I set light radius to 50 and created a yellow circle sprite in Piskel)
3. Create an object and add Light Obstacle Behaviour
4. When two come in contact, the light doesn't work like it's supposed to (Shown in the video)

## Other details
* Windows 8.1 x64
* GDevelop Desktop build 121

**Comment by ukStream1** [comment]
IDK if this is a bug or not but when the Light obstacle is directly above the light, it renders like this: https://gfycat.com/scholarlysomecats

**Comment by 4ian** [comment]
Thanks for reporting this. Can you try with a larger texture to see if it only happens when the texture is smaller than the light radius? Thanks!

> IDK if this is a bug or not but when the Light obstacle is directly above the light, it renders like this:

Technically not a bug, though we could improve stuff so that obstacles are "filled" and so not showing light inside then.

**Comment by ukStream1** [comment]
> Thanks for reporting this. Can you try with a larger texture to see if it only happens when the texture is smaller than the light radius? Thanks!

It seems I made a mistake, apparently Piskel made 64x64 image (in the video i linked above), I downsized it to 32x32 and 50x50 and the bug still happened..

**Comment by Bouh** [comment]
I bump this issue with a reproduction project made by a member on the forum
Download: [Reproduction project.zip](https://github.com/4ian/GDevelop/files/7605359/Reproduction_project.zip)

Seem the sprites bleeding in the light mask area only for sprite with a texture touching the image bounds.

![Sans-titre-1](https://user-images.githubusercontent.com/1670670/143503335-a1d7ef97-0843-410a-88d9-2b50738816f5.gif)
