### ISSUE TITLE
create object makes 5 objects unintionally 

### ISSUE THREAD

**Issue by InfamousKnight** [4ian/GDevelop#3225]
## Describe the bug
in the event sheet, create object makes like 5 of them automatically despite not being told to do so

Please double check that the bug is not already reported in the issues list.

## To Reproduce
In the scene editor, make a text display with  NewObject as the name(or anything just remember what it was called)
Go under the event sheet(scene events)
make some keyboard event
make the action createobject
Run it
press the key you specified
Notice how bold the text is. If you space it out with variables, it will come out as like 5 of them

## Other details
* Include any OS/browser version/smartphone that you're using
* Windows 10
* Which version of GDevelop are you using? The desktop app or the web-app? 
* Desktop app on GDevelop 5

What it should do is only create 1 not 5

**Comment by Bouh** [comment]
What is your condition?
Because while you press the key the condition is valid and the action will be triggered, so multiple objects can be created, if you want only one, add a condition Trigger Once..

**Comment by InfamousKnight** [comment]
Thanks!
