### ISSUE TITLE
Vibrating/Bouncing Sprite

### ISSUE THREAD

**Issue by mmutee** [4ian/GDevelop#3231]
## Describe the bug
Sprite object (with "Platform Character" behavior) vibrates/bounce when in collision with Tile object (with "Platform" behavior).

This is how it looks like:
![output](https://user-images.githubusercontent.com/15348404/140792773-7156fc1a-e6b8-4a0d-b961-1d966dbca4a8.gif)

## To Reproduce
* Make a Tile Object and create a floor with it. Attach "Platform" behavior to it.
* Make a 64x64 sprite object and attach "Platform Character" behavior to it. 
* Click "Edit Collision Mask" and enter these settings: 
![collision mask_](https://user-images.githubusercontent.com/15348404/140791634-ecab0a29-56c6-49e6-9b0f-50eb03fe8eac.png)
* Click "Edit Points" and insert the following:
![edit points_](https://user-images.githubusercontent.com/15348404/140791837-98f82406-ea5e-4a49-9894-ec64e76a0ce3.png)
* Place the sprite object in game area, above the floor made with the above mentioned Tile object.
* Now preview/run the game in Gdevelop editor
* If you tweak the "collision mask" or "edit points" settings, the problem disappears.

## Other details
* Gdevelop 5.0.120 Desktop application on Windows 7 64bit.

## Project file to demonstrate the issue
[bouncing_sprite_bug.zip](https://github.com/4ian/GDevelop/files/7499078/bouncing_sprite_bug.zip)

**Comment by 4ian** [comment]
Hi, thanks for reporting this - can you include the project file in a zip attached in your first message? Thanks!

**Comment by mmutee** [comment]
Just did that.

**Comment by Bouh** [comment]
It doesn't happen to me with the project in the bug report, or nothing more if a reproduce on my own :/
![snowman](https://user-images.githubusercontent.com/1670670/140810541-e44fce87-9231-4562-87fd-c26ed8a57070.gif)

**Comment by Bouh** [comment]
Maybe @D8H 's works on platformers will fix this possible issue?
https://github.com/4ian/GDevelop/pull/3009
https://github.com/4ian/GDevelop/pull/2603
https://github.com/4ian/GDevelop/pull/2574

**Comment by mmutee** [comment]
I am not on the very latest update, perhaps that could be the reason. Another thing I wanted to point out is that this happens on "Platforms" only. On Objects where collision/separate-objects is being used, the jittering stops.

**Comment by 4ian** [comment]
This seems like an issue that could arise from the way the platform works/try to round coordinates.. should indeed by solved by the work of D8H on the updated platformer engine! Would be good to check.
