### ISSUE TITLE
'Not' condition breaks on automatic object selection

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#3233]
## Describe the bug

When using an object condition that uses GDevelops built-in object selection mechanism, it never triggers, when it should. This doesn't affect object conditions that do the object picking "manually", like the "cursor on object" condition.

## Cause

The cause is as far as I see due to two conflicting assumptions (but those assumptions are just my assumption of what's happening, they may be wrong :p).

The not condition sets the return value that needs to be negated to true by default, since no condition = always true, and it assumes that if there are subconditions, they will override it to their return value.

In the other hand, the default automatic object selection assumes that by default the return value is false, and never explicitly sets it to false, it only sets it to true each time an instance meets the condition.

## To Reproduce

1. Make a Not condition with the cursor on object condition
2. Make a not condition with point in object condition
3. See how the latter never triggers when the first one works as expected
4. Look in the sources debugger tab at how the generated code never sets the return value of the later to false, only to true constantly, meaning that the inverted return value will always be false.

## Project reproduction

[autojump.zip](https://github.com/4ian/GDevelop/files/7529542/autojump.zip)

**Comment by 4ian** [comment]
Can you share here the project? :)

**Comment by arthuro555** [comment]
Whoops totally forgot to upload the project here it is: 
[autojump.zip](https://github.com/4ian/GDevelop/files/7529542/autojump.zip)

**Comment by willianholtz** [comment]
Maybe I've never understood what the "not" function is all about and I've always used it wrongly, but if this is really a bug, and I'm using it believing it was supposed to be that way, this example of mine is completely wrong. And if I'm wrong my game will need to be changed urgently.

Example:
[Not.zip](https://github.com/4ian/GDevelop/files/7547356/Not.zip)

ps: use the yellow block (drag) to make the player follow you, go out of sight to return your movement

**Comment by arthuro555** [comment]
Can someone update the tags? I have sent the reproduction project.

**Comment by 4ian** [comment]
Great investigation and fix @arthuro555!
