### ISSUE TITLE
Font selector doesn't open and "time scale" issues

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3242]
# List of bugs and inconsistencies
A list of a few bugs, inconsistencies and missing functionalities I've noticed in the past few days. Note that not all have to be bugs or are intended the way they currently are and I am sorry if I didn't see here mentioned issues as already submitted and I feel like this is a better place than the Discord. If anything on the list is intended, maybe it could need improvement to make it more intuitive or clear to users.

### Content:
**1:** Font selector doesn't open anymore
**2:** Missing expression for scene time scale
**3:** Inconsistent action groups for time scale
**4:** Confusing action naming inside expression builder
**5:** Missing space character in Rotate action *(little detail)*

---

## 1. Font selector doesn't open anymore

When selecting a font for a text, the panel used to select a font file from the explorer doesn't show up anymore making selection of fonts unnecessarily difficult (122b1).

https://user-images.githubusercontent.com/83909121/141656591-37b05563-03ef-4eb4-a726-e01430d3a6a6.mp4

---

### `››` 2. Missing expression for scene time scale

The expression to get the scene time scale is missing in the expression list *[› image 1]*. Since the layer time scale is independent from / isn't changed by the scene time scale, asking for a (e.g. base layer) layer time scale will not work.

**Current workaround:** Set scene time scale to variable and get variable value instead
**Workaround quality:** Poor but working
**Suggested solution:** Add a scene time scale expression

### `››` 3. Inconsistent action groups for time scale

"Change time scale" action is in category or group: "Timers and time"
"Change layer time scale" action is in category or group: "Layers and cameras/Time" (as only entry of the group)
For me it doesn't matter much since I always search for actions (/conditions etc.) but maybe those two actions can be move so that they are in the same group. I see this can be difficult and this issue isn't at a high priority, just throwing that into the room, possibly for discussion.

### `››` 4. Confusing action naming inside expression builder

The method '**LayerTimeScale**(*Layer*)' *[› image 1, expression suggestion]* is called "Time scale" *[› image 2]* in the list inside the expression builder and can easily be confused to be related with the "Change time scale" action *[› image 3]*.

**Suggested solution:** Change name from "Time scale" to "Layer time scale".

## 5. Missing space character in Rotate action *(little detail)*

The "Rotate" action is missing a space character, since the value should always be separated from the unit. I would fix and submit a PR myself but I really don't know what I'm doing just yet when it comes to GitHub and the GDevelop structure.

![image](https://user-images.githubusercontent.com/83909121/141657973-8cfd6267-54e6-4dcf-a00d-d177220d7fb2.png)

**Suggested solution:** `XXX deg/second` instead of `XXXdeg/second`

---
Related images for issue two to four:

![image](https://user-images.githubusercontent.com/83909121/141658018-3612d6e4-01cf-44e3-be17-33e857d7f868.png)

---

## Other details
GDevelop 5.0.**122-beta1** based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by Bouh** [comment]
Thanks to split the bugs in differents bug reports.
It's ok to open multiple reports.

**Comment by Elairyx7301** [comment]
Alright, I will split it into two issues when I'm at the computer again, thanks
