### ISSUE TITLE
Editing Object Variables in Object properties

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3244]
## Description
Currently to edit object variables, user has to right click and click `edit variables`. Which is very difficult to find for new users. It would make sense to have it in the object properties. Like shown here:

![variables](https://user-images.githubusercontent.com/73597906/141677049-a23e4da2-6791-4c24-947d-4be1721a3efc.png)
## Solution suggested
I am happy to do it myself, The screenshot shows my attempt at it. But, I have having some issues figuring out how to get the object variables and other things I should make sure of and who the `VariablesList` works. It would be great if someone could help me. Currently when the tab is opened, it results in a crash (obviously)

**Comment by Bouh** [comment]
I agree, it don't have really sense to make it available by the context menu while other options are in the object edition.

**Comment by 4ian** [comment]
Agree variables should be there - it's part of what an object is, and it's already in the right click menu so for consistency they should be there.
