### ISSUE TITLE
Font selector doesn't open anymore

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3247]
## Describe the bug
When selecting a font for a text, the panel used to select a font file from the explorer doesn't show up anymore making selection of fonts highly difficult and exhausting (122b1).

## To Reproduce
1. Go to the scene editor
2. Add/Create a "Text" object
3. Click inside the "Font: " panel
4. See the "Select font..." option doesn't appear

https://user-images.githubusercontent.com/83909121/141656591-37b05563-03ef-4eb4-a726-e01430d3a6a6.mp4

[NoFontSelector.zip](https://github.com/4ian/GDevelop/files/7539751/NoFontSelector.zip)

## Other details
GDevelop 5.0.**122-beta1** based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows
Regular build, no nightly version

**Comment by ClementPasteau** [comment]
Thanks for noticing and raising the issue, I've reproduced it and it's indeed a regression. I'm taking a look.

**Comment by ClementPasteau** [comment]
This will be fixed for the non-beta release, thanks @Elairyx7301 !
