### ISSUE TITLE
We need "Every x seconds" function

### ISSUE THREAD

**Issue by FerrLui** [4ian/GDevelop#3251]
## Description
  I know we can do anything with timers, BUT  with this function it will be more and more faster.

## Solution suggested

**Describe the solution**
 Simply add "Every x seconds" function like in "Construct "

**Comment by arthuro555** [comment]
Already exists as an extension. Additionally, note that feature requests should go [on the forum](https://forum.gdevelop-app.com/c/gdevelop-general/feature-requests/35).
