### ISSUE TITLE
On Destroy condition

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3265]
## Description

A On Destroy which triggers when an instance is deleted can be very helpful. Ex: to play a die animation when the player dies. Many extension have access to delete an object and can be annoying to make events to make it work with those unplanned situations. A OnDestroy can simiplify a lot. It can be implemented once and it will work everytime

**Comment by 4ian** [comment]
I would tend to rather advise to transform whatever you want to do at the object destruction into a behavior, if that's possible?
Do you have an example of use case apart from the die animation? (which should rather be done with a Health behavior I guess?)

**Comment by Oxey405** [comment]
You can just test if the number of object is = 0 once.
