### ISSUE TITLE
Toggle for automatically starting timers

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3282]
## Short summary

Add a toggle to timers that prevents them from starting automatically at the beginning of the scene (if those timers are used in the events).

## Description

Even though that it can be really handy that timers are started automatically, many users seem to be confused about it and this behavior can be rather counterintuitive for many but especially new users.

Often, users want to only start a timer when a certain event happens/occurs. This would currently require to pause the timer at beginning of scene, resume for the event, let the timer run and have another condition make the logic work or reset the timer for as long as event conditions are not met.

## Solution suggested

After discussing it with community members, we've come to the conclusion that it would be best to add a toggle switch or boolean to timers allowing the user to avoid having timers started automatically by the engine if they are used in the code to reduce confusion and extra workarounds for timers that only want to be started with a certain condition, event or with a delay.

The decision was a toggle with [default: no] so already existing games and projects aren't affected by this huge change to the core of timers.

## Potential visual mockup (frontend)

![image](https://user-images.githubusercontent.com/83909121/143087692-8c4c2e28-3138-40ad-92f4-d08a9114f2a9.png)

## Alternatives considered

Give a hint to the user that timers are started automatically at beginning of scene.

### Original issue: #3065

**Comment by Elairyx7301** [comment]
Are there any comments about this feature or idea? Is this change likely to happen or not?

**Comment by D8H** [comment]
Hello Elairyx, just to let you know a PR is opened for this.
