### ISSUE TITLE
Not logging in or signing up

### ISSUE THREAD

**Issue by ArezalGame89** [4ian/GDevelop#3288]
## Describe the bug
Whenever i try to sign up for the account in-app
it just doesn't do anything, no errors and no crashes
is this an region issue? please help.

## To Reproduce
1. Go to 'Login or create an account'
2. try to log in or sign up with correct details
4. yep

## Other details
* I'm using Windows 10
* Desktop App V5

**Comment by AlexandreSi** [comment]
Hi @ArezalGame89!

Can you try again to log in/sign up, but this time, before doing so, open the console with `Ctrl+Shift+I` or `F12`, make sure the console is selected.

![image](https://user-images.githubusercontent.com/32449369/143406260-0529622a-0d3d-432b-8c8b-56e9546df3f5.png)


If it still doesn't work, there should be a red or orange message. Can you copy-paste it here?

**Comment by ArezalGame89** [comment]
> Hi @ArezalGame89!
> 
> Can you try again to log in/sign up, but this time, before doing so, open the console with `Ctrl+Shift+I` or `F12`, make sure the console is selected.
> 
> ![image](https://user-images.githubusercontent.com/32449369/143406260-0529622a-0d3d-432b-8c8b-56e9546df3f5.png)
> 
> If it still doesn't work, there should be a red or orange message. Can you copy-paste it here?



Here you go;
![image](https://user-images.githubusercontent.com/86628069/143418620-0a843aa2-0dba-4238-819f-7a279aa52709.png)

**Comment by ClementPasteau** [comment]
Hi @ArezalGame89 !
Thanks for reporting the issue.
It looks like the request is being blocked for some reason.

In which country/region are you trying to access the app?

I think it could come from either your PC configuration or your network.
Would you be able to:
- connect to another wi-fi / internet ? For instance putting your phone on hotspot. -> check if this is still a problem
- try the app on another device (another laptop maybe?) -> check if this happens as well
- try to login from the web editor (https://editor.gdevelop-app.com / top-left icon / my profile) -> check if it works

That would help us help you! 
Thanks

**Comment by ArezalGame89** [comment]
> Hi @ArezalGame89 ! Thanks for reporting the issue. It looks like the request is being blocked for some reason.
> 
> In which country/region are you trying to access the app?
> 
> I think it could come from either your PC configuration or your network. Would you be able to:
> 
> * connect to another wi-fi / internet ? For instance putting your phone on hotspot. -> check if this is still a problem
> * try the app on another device (another laptop maybe?) -> check if this happens as well
> * try to login from the web editor (https://editor.gdevelop-app.com / top-left icon / my profile) -> check if it works
> 
> That would help us help you! Thanks

Well, I'm connected to my mobile hotspot
I'm in Asia-Iran.
Will try another device, sure.
Will try to get in web, also sure.

**Comment by Oxey405** [comment]
https://en.wikipedia.org/wiki/Internet_censorship_in_Iran
GDevelop is hosted on a Google Cloud Server. Google is blocked in Iran.

**Comment by ArezalGame89** [comment]
> https://en.wikipedia.org/wiki/Internet_censorship_in_Iran GDevelop is hosted on a Google Cloud Server. Google is blocked in Iran. You could use a VPN or a proxy to redirect your connection to France or United Kingdom for example. It could also be possible that your mobile hotspot is not working correctly. I don't want to be involved in any legal things tho, I don't know if it's legal to use a VPN in Iran tho !

used a VPN, it works. it has been working for 9 years
