### ISSUE TITLE
Admob without overlay - Aspect ratio issue

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3307]
Following [this fix](https://github.com/4ian/GDevelop/pull/2223#issuecomment-981618490), we seem to have a problem with the way ads are displayed, because the overlay setting has been removed and banners now resize the games, which produces black bars.

![image](https://user-images.githubusercontent.com/25978830/143898290-adcca6a5-d9d1-48e2-baaf-945d7b2766b0.png)

More details [here](https://forum.gdevelop-app.com/t/admob-banner-width-exceeds-game-width/35823).

**Comment by devgiordane** [comment]
In the cordova plugin documentation, there is an offset option that makes the banner overlap the webbiew, I tried to make a change in the banner configuration, and pass the offset parameter For the moment of creating the banner, I am waiting for the Review, and I hope, improvement of the banner options, my solution is actually implemented in a worse way, but I tried to give direction

**Comment by Bouh** [comment]
Thanks now since few versions the banner overlap the game.
