### ISSUE TITLE
Add "Camera Zoom" condition

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3314]
## Description

There is no camera zoom condition, only a camera expression. This feels strange because there are conditions for every other or most other main camera parameters like X position, height, angle etc. and only zoom is missing. I think this should be added because for example newer users likely aren't familiar with the expressions available, search for "zoom" in the conditions and won't find anything when there actually is an expression for it.

## Solution suggested

Add a CameraZoom(*Layer*, *Camera*) condition

## Image

![image](https://user-images.githubusercontent.com/83909121/144251568-a6f9b4c6-88f0-459d-897c-d4f688156c4a.png)

**Comment by Oxey405** [comment]
I'll work on it this week end !

**Comment by Elairyx7301** [comment]
Any progress @Oxey405? Can this issue be closed?

**Comment by AlexandreSi** [comment]
I can provide a few steps if you need any help

**Comment by Elairyx7301** [comment]
@AlexandreSi I'm sorry for the mention here but I might be able to take a look at this myself and I'd be happy about a hint, mainly concerning which files need changes for this, since I'm not completely sure about how the code structure works, yet.
Thanks in advance :)

**Comment by AlexandreSi** [comment]
@Elairyx7301 sorry for the delay, here is your hint:

- Files that should be changed:
  - Core/GDCore/Extensions/Builtin/CameraExtension.cpp
  - GDJS/GDJS/Extensions/Builtin/CameraExtension.cpp
  - GDJS/Runtime/events-tools/cameratools.ts

**Comment by Elairyx7301** [comment]
Thank you! 👍
I might also not be able to look at it in the next dozen days or so but I really want to give it a try.
