### ISSUE TITLE
"Play sound" action skips if used repeatedly in 5.0.122

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#3315]
## Describe the bug
It appears that the "Play Sound" action is skipping repeated uses in 5.0.122. It will play the sound file correctly the first time, then not play anything the second or third time. This might be related to the default volume that was set to fix the other known sound issues?

Interestingly, "Play Sound on a channel" is not impacted at all, so this exists as a valid workaround. I have confirmed this behavior doesn't occur if reverting to .121 or older.

## To Reproduce
1. Add an event with a trigger condition (press any key + trigger once, timer, etc) and the "Play a sound" action.
2. Preview the game.
3. Trigger the sound. The first time will play, the 2nd and 3rd time will not, then it will start playing normally again.

Another user reported it and provided a test project, I cleaned it up a bit after being able to reproduce it, available here: [Audio Test.zip](https://github.com/4ian/GDevelop/files/7635320/Audio.Test.zip)

## Other details
OS: Windows 10 Pro 
GD5 Version: 5.0.122
This was reported in this thread: https://forum.gdevelop-app.com/t/audio-playback-bug/36625 
Thanks to user Rasterisko for their sample video and test project.

While obviously this should be fixed, I wonder if this is a good instance to mark this event (and the play music events) as legacy, to guide users to use the play sound on a channel events instead. 

No strong feelings either way, just a thought since the sound channel is better for 99.9% of scenarios than non-sound channel, and play sound file is better than play music in most cases as well, this could lead to better utilization by newer users.

**Comment by ClementPasteau** [comment]
Thanks for raising this @Silver-Streak and cleaning the project 🤗 
I'll take a look, wether we deprecate it or not, we shouldn't break things...
We may have introduced a regression when fixing the initial glitch when playing a sound in 5.0.122.

**Comment by 4ian** [comment]
Just to clarify a few things, there is nothing legacy or deprecated here:

- The difference between a music and a sound is that music will be streamed in memory, while a sound is loaded entirely in memory when played. Technically this means using HTML5 audio for musics, but it's a technical detail and should not matter. In practice you should use music actions for long audio files, and sound actions for short ones.
- The "play sound" (outside of a channel) and "play music" (outside of a channel) are not deprecated. While using Play music outside of a channel is maybe less useful, using play sound to quickly run a sound effect (like when you collide an enemy of fire a firearm or do an attack) is perfectly fine and recommended.
- The play sound and play musics on a channel are useful to keep track of the sound/music. Usually it's a good idea to use those for background musics or sound effects that you want to manipulate later or loop.

If there are limitations related to usage of HTML5 audio for musics we should address this though. But in the meantime nothing is deprecated and I would even recommend to use "play sound" by default (it's one of the most basic action: just play a sound effect!). In short:

- Play sound: perfect for short lived sound effects.
- Play sound on channel: useful if you have a persistent sound effect that you want to tweak (like the sound of the shield of the player).
- Play music: usually less useful, but can be used for longer sound effect/atmosphere musics (though using a channel might be a good idea).
- Play music on a channel: perfect for long lived, long audio like a background music.

**Comment by Silver-Streak** [comment]
@4ian Sorry, I didn't mean to indicate that they _were_ deprecated (Although I thought Arthuro had mentioned that "play music" did use a legacy method of playing audio due to using HTML5 audio instead of WebAudio playback methods, mostly for compatibility).

I meant to ask/imply more that maybe they _should_ be treated as deprecated (or at least play music). "Play music" and "Play music on a channel" doesn't (or at least didn't) loop audio correctly. My understanding is that due to its method of playing, audio files played using that method will always have a slight pause when loops occur even if preloaded, as well as requiring interaction with the window/game before it can play for the first time. This was even after the rework Arthuro did.  

Unless something has changed around the music actions playback (Last I tested was somewhere around 110), due to this behavior, the action is not super useful for most scenarios where a user would want to play music in a game. It leads to lots of 

Play sound _should_ be fine, I was just suggesting deprecating the non-channel action if this was more of a hard issue to fix, since it could teach better-game wide practices for user.

Let me know if the above is incorrect anywhere as well, as I want to ensure I'm informing users correctly.
