### ISSUE TITLE
When object is deleted by tween action, that tween activates on other object instances (Regression in v122, not present in v121)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3316]
## Describe the bug

When an object with a Tween is deleted, the Tween becomes active on another instance of that object.

https://user-images.githubusercontent.com/8879811/144277176-4b4f0748-c6ee-40fa-ade0-9e7f3a5dd1a2.mp4

## To Reproduce

0. Install GDevelop v122.  This problem doesn't exist on v121.
1. Create an object and add tween behavior
2. Add a tween action and configure Tween to delete object when complete
3. Object will tween and then delete (properly)
4. However, another instance of that object gets the Tween activated on them (wrongly)

## Other details

Windows 10

**Comment by 4ian** [comment]
> This problem doesn't exist on v121.

Looks like a regression on the Tween :/ I'll take a look, thanks for taking the time to report this!

**Comment by 4ian** [comment]
@tristanbob Any chance you share the project with me? This can speed up the debug a lot :)

**Comment by tristanbob** [comment]
Yes, of course.   I did my testing in a new scene of Slime Dunk; here is a fully separate project:

[TweenDeleteBug.zip](https://github.com/4ian/GDevelop/files/7636920/TweenDeleteBug.zip)

**Comment by tristanbob** [comment]
I can confirm that v123 no longer has this bug on my project.  Thanks 4ian!
