### ISSUE TITLE
IDEA: Hive Blockchain extension

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#3319]
I am currently working on an extension that gives access to the Hive blockchain.
Developers will be able to create a very straight forward login mechanism where players can authenticate themselves via their [Hive Keychain Wallet](https://hive-keychain.com/). 
It will be possible to send and receive Hive and Hive backed Dollars (HBD) crypto currencies or access information from the blockchain via [dHive](https://github.com/openhive-network/dhive). 
If there is demand, I could also add the possibility to create blog posts, add voting etc.

This extension would enable developers to create play2earn games or add in-app purchases in via the Hive crypto currency.
I already have a working prototype.

@4ian I have two questions:
- Am I guessing right that you would prefer it to become a standalone extension in [GDevelop-extensions](https://github.com/GDevelopApp/GDevelop-extensions)?
- For the example project, I was thinking about adding the possibility send tips in Hive/HBD cryptocurrency. If you are interested, you would need to create a Hive-Wallet for GDevelop. That could be another source of income for the project in the future.

What do you think?

**Comment by arthuro555** [comment]
Personally, I'd stay away from cryptocurrencies as they are pretty controversial and controversy could hurt GDevelop at this most critical stage of development where the GDevelop company is starting. I mean making a standalone extension for users that are into that is fine but a built-in feature or adding an integrated way to donate cryptocurrencies to GDevelop is IMO not a good move.

**Comment by Bouh** [comment]
I switch this issue to a discussion :)
I love crypto but it preferable as an user extension I guess because I agree with Arthuroo on this point, we should think carefully about this.
