### ISSUE TITLE
Clean unused videos delete all videos

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3356]
## Describe the bug

If we remove unused videos in the resource panel, all videos are deleted.

## To Reproduce
1. Open an empty project
2. Create a video object, select a file.
3. Place the video object on scene
4. Go in resource tab
5. Clean unused video
6. See the unique video has been deleted

## Other details
* [Original issue on forum](https://forum.gdevelop-app.com/t/remove-unused-videos-deletes-all-videos/36912)
* 5.0.123 
* Desktop & Webapp

**Comment by 4ian** [comment]
Thanks for reporting, fixed for next version (and for JSON resources too!).
