### ISSUE TITLE
Debugger/Preview/Publish icons are not centered when using the extension editor

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3380]
## Describe the bug

Debugger/Preview/Publish icons are not centered when using the extension editor

![Screenshot 2021-12-17 203801](https://user-images.githubusercontent.com/8879811/146627690-00e2f34e-534e-4817-a244-d1fa3cf69bff.png)

## Other details
* Windows 10
* GDevelop 5.0.124

**Comment by ClementPasteau** [comment]
Thanks for spotting this!
We actually spotted it as soon as the release got out.
The fix has been merged into master and will be live for the next update 👍

**Comment by tristanbob** [comment]
That's great!  I'll try keep a better eye on the PRs. :) 

Fixed by #3374
