### ISSUE TITLE
The "create a new project" dialog no longer allows to create a blank project

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#3382]
## Describe the bug

The create new project dialog no longer allow to create a blank project.
A tab is missing?

## To Reproduce
1. In the menu, "File > Create a new project..."
2. The dialog open
3. There is no way to create a blank project

![CreateProject](https://user-images.githubusercontent.com/2611977/146680098-7bf9e95d-d778-44dc-a6b4-de636f933832.png)

## Other details
* desktop app v124

**Comment by Bouh** [comment]
Some more feedback about it:

![image](https://user-images.githubusercontent.com/1670670/146681665-c017ee49-1e92-4ca1-802f-a51101382a7b.png)


![image](https://user-images.githubusercontent.com/1670670/146681567-f92295cc-6814-423f-94c1-468aa827cae9.png)
![image](https://user-images.githubusercontent.com/1670670/146681577-c7869af8-4658-4549-9bfb-a62a37e97747.png)
![image](https://user-images.githubusercontent.com/1670670/146681585-1dc8ae05-ca55-4c91-8a6e-8e6921c6582e.png)
![image](https://user-images.githubusercontent.com/1670670/146681647-8731329a-0300-4a1f-9ea5-d21526dea9b2.png)

**Comment by Silver-Streak** [comment]
General recommendations I would make on this:
1. The create an empty project link should be made into a button (similar to Open on the modal) not just a link of text.
2. The same button should be added to the upper right of the modal.

**Comment by 4ian** [comment]
Let's go for a raised button instead of a flat button, and we can add the button into the modal too - that should be hopefully enough to avoid confusion! :)

**Comment by Elairyx7301** [comment]
I feel like the least change needed would be making the "create blank project" link more visible or into a raised button, as already mentioned. However, in my personal opinion, this type of project is the most commonly used and picked type of new project so could even deserve a big(ger) panel or an entry in a separate row in the list, for example change it from `template; tutorial; showcase` to `blank project; template; tutorial; showcase`.

**Comment by AlexandreSi** [comment]
Hi all,
I'm closing this issue since the version 5.0.125 reintroduced a button on this dialog.
We didn't realize we had removed this possibility.
Thanks for your feedback!
