### ISSUE TITLE
Find/replace will find matches in comments and event groups, but will not replace the text

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3385]
## Describe the bug

Find/replace will find matches in comments and event groups, but will not replace the text in those items.

## To Reproduce
1. Create a comment and event group with the words "player"
2. Use the search and replace tool to search for "player"
3. You will see the comments and event group are highlighted and counted in the "results" counter
4. Click "REPLACE" and notice that comments and event groups are not modified

## Video

https://user-images.githubusercontent.com/8879811/146714759-f824880a-bdab-4490-aef9-dd25a7d93cf3.mp4

## Other details
* Windows 10
* GDevelop 5.0.124

**Comment by AlexandreSi** [comment]
Hi again @tristanbob!

I am not sure that the feature "search and replace in text events" has already existed. And if I'm not wrong, the UI is misleading as the `Text` checkbox is ticked.

**Comment by tristanbob** [comment]
We either need to add the ability to replace text in comments and event groups, or we need to stop finding matches in those event types.

**Comment by AlexandreSi** [comment]
I'm confident this "replace in text events" feature has never existed.

Maybe it's time to resolve this TODO:
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/EventsSearcher.js#L106-L107

In any case I think the "Search in text events is a nice feature" to quickly find a section "Enemy movement" for example
