### ISSUE TITLE
Sharing button in export is unusable on Windows

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3393]
## Describe the bug

In the web app *only* clicking on `Share `button open a Windows's popup immediately closed.
While it works fine on desktop app.
![share](https://user-images.githubusercontent.com/1670670/147005715-0153b6e1-4363-49b0-9f0c-0e957b4c4c54.gif)

## Other details
- 5.0.124
- Web app only

**Comment by ClementPasteau** [comment]
Thanks for raising this @Bouh 

I've tried it on my windows, and with Chrome and this popup comes up.
![image](https://user-images.githubusercontent.com/4895034/147065442-d88dcc06-dda3-42d9-b17d-075aa89c76d8.png)

I believe this means that your machine's sharing function isn't working properly, and it's not related to GDevelop.

If this is a common problem on Windows though, we could decide to not trigger the native sharing functionnality and revert back to the popup.
Let's see if others have the same issue?

**Comment by Bouh** [comment]
I don't understand the point of a native feature that does the job less well than a basic solution with the GDevelop popup.

I want to believe that my system is broken, but we should be free from this kind of bug with the popup and having a 100% working solution, specially for this important feature that make the user base growing.

Moreover our GD popup takes away a piece of code to maintain, because this sharing navigator call is plugged into an nth API. (of course a basic call but it's one more, less is better)

**Comment by 4ian** [comment]
Can you share your Chrome version and Windows exact version?

**Comment by 4ian** [comment]
Can you share your Chrome version and Windows exact version? We can also maybe catch an exception, if there is one, and display our own dialog?

**Comment by Bouh** [comment]
> Can you share your Chrome version and Windows exact version? We can also maybe catch an exception, if there is one, and display our own dialog?

- Chrome Version 96.0.4664.110 (Build officiel) (64 bits)
- Windows 10 Famille, Version 20H2, 19042.1415

This sharing feature is ok natively on Windows, (I never used it before btw pretty useless to me)
![dd](https://user-images.githubusercontent.com/1670670/147250380-a0f0a485-ce0b-43d0-832e-afb624af1a29.gif)

**Comment by AlexandreSi** [comment]
@Bouh is the issue still present with the new version that's been granted by Microsoft?

**Comment by Bouh** [comment]
I get a better dialog with A copy button, share button, and open the game.
So it's fine I can now copy the URL, thx! :D 

![image](https://user-images.githubusercontent.com/1670670/149530847-c6d4ab66-b7d3-46fd-8601-efe7fc9c85e5.png)
