### ISSUE TITLE
Separate Object Inconsistencies - Top Down Collisions

### ISSUE THREAD

**Issue by AtomicCrocStudios** [4ian/GDevelop#3399]
## Describe the bug
I am not sure if this is a bug or I am just going about handling this incorrectly.

I have been trying to handle top-down collisions smoothly with multiple objects in an RTS type of scenario with the use of pathfinding behaviour and noticed that the Separate Object action seemed to have some inconsistencies on what could be moved or not. I ended up creating a separate project with 4 different objects that just used the Draggable Behaviour, On Collision Check and Separate Object.

It seems some objects seem to have a higher priority to separate objects then others, for example in the projected linked; in SCENE 1 the purple block can move any other block out of the road, however the yellow block can only move the pink one.

I tried 3 separate ways to check collisions.

SCENE 1: Ever object has a check against another object.
SCENE 2: Every object has a check against a group (with all objects within it)
SCENE 3: Every object has a check against a group (with all objects within it) but also checks if it's being dragged.

---

SCENE 3:  Works the best, but only against other objects and not it's self meaning every new unit would have it be a separate object.

What I am trying to achieve is objects (units) moving out of the way for each other with the one selected (or in this case being dragged) is moving. I can achieve this with physics 2.0 behaviour, however I lose the ability to use pathfinding and/or move an object to an X/Y coordinates at a constant speed, then stop.

URL: https://games.gdevelop-app.com/game-ccec12c4-21fc-4da7-af7d-14251f419177/index.html
Download Project: [Separate Instances 2.zip](https://github.com/4ian/GDevelop/files/7767939/Separate.Instances.2.zip)

## Other details
* Windows 10
* 5.0.124

**Comment by Bouh** [comment]
I would add on **Scene 1** I can see the separate action working fine betweens Yellow/red/purple, but with purple/orange we have a tiny overlap.

![dd](https://user-images.githubusercontent.com/1670670/147247142-ef2e8211-5bf0-47d8-b068-979ef8e855c7.gif)



cc @D8H

**Comment by D8H** [comment]
This is to be expected. This is the same issue as when an object is blocked between 2 obstacles that leave a hole smaller than the object: it vibrates.

Physics engines have algo to resolve multiple solid that are colliding with each other. Here, it's just 1 to 1 and call order has an impact on the final result.

A naive workaround is to loop N times on separate until no object moves.
