### ISSUE TITLE
Fullscreen preview recently broken for some Linux distros?

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3414]
A user on the forum complains that fullscreen preview used to work in his environment (up to 5.0.121), and doesn't anymore.
OS: Linux Mint 20.2
The preview window only shows the exit button, no minimize or maximize buttons. Pressing F11 doesn't resize the window.
![image](https://user-images.githubusercontent.com/25978830/147607575-9a37b72e-ce6e-4133-a67d-ad8ace8eed28.png)

Has there been any recent change that may have caused this?

[source](https://forum.gdevelop-app.com/t/f11-toggle-fullscreen-doesnt-work-on-linux-mint-20-2-uma/37092)

**Comment by willianholtz** [comment]
I use linux and it never happened. Arch Linux with KDE environment. Maybe it could be Gnome bug!
The only problem I have with this is changing the game resolution from full screen to windowed in realtime, and vice versa.
![fullscreen](https://user-images.githubusercontent.com/23488207/147612973-8f7ebbdb-5413-4f00-94a4-3d3f3c44dfc5.png)
But I believe this has nothing to do with the related bug!

**Comment by Midhil457** [comment]
I use the same distro as the reporter's. And I haven't experienced it yet, I have all the window options (close, minimize,etc..). And I am able to fullscreen with F11

**Comment by Bouh** [comment]
There was a small update on the windows but it doesn't affect anyone normally, and moreover the change took place in 5.0.122, so it's not related.
He should test the latest version 5.0.124.

**Comment by PascalLadalle** [comment]
Thanks for the feedback everyone, I'll get back to him for further troubleshooting.

**Comment by Bouh** [comment]
It seems not a GDevelop bug, but more related to the Operating System they use.

**Comment by PascalLadalle** [comment]
According to the user, preview works fine in 5.0.121 and is broken in subsequent releases.
It might be hardware-related rather than OS-related.
User has an Amd ATI radeon Powercolor HD 7770.

> BlackJaguarGX64
5.0.121 does work but 5.0.122 and latest doesn’t. When only in preview mode. And exported it hasn’t f11 hotkey but does have minimize and maximized button.

On a side note, it seems I'm no more able to reopen issues.

**Comment by willianholtz** [comment]
> 

I just remembered that I had the same problem a while ago with LDTK until I reported it to them, and the problem was with my Hardware that I was using at the time was a Radeon 6570. Linux has some difficulty with AMD graphics and therefore glitchs happen
