### ISSUE TITLE
Timed out exports still showing as loading/building

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3448]
A Discord user reports that his builds from yesterday still appear as loading:
![image](https://user-images.githubusercontent.com/25978830/148688921-9e355883-16ea-4d0d-8432-b5d93339a7e8.png)
I assume they timed out, and GDevelop just doesn't realize it.
Could we do something about that? Giving a real status report of whether the build is uploading, building or failed? Or perhaps a Cancel button?
User was concerned that the concurrent uploads were eating his bandwidth. Perhaps we could put a queue mechanism to avoid multiple concurrent uploads, if there is not one already? I guess multiple uploads make it more likely for all builds to fail, for slow connections.

**Comment by ClementPasteau** [comment]
Thanks for reporting @PascalLadalle 
That is indeed weird 🤔 The builds must have failed and we're not displaying it properly in the interface.
I'll investigate this week
