### ISSUE TITLE
Scene Editor Crashes While Using

### ISSUE THREAD

**Issue by Bloomzeye** [4ian/GDevelop#3449]
## Describe the bug!
As I use GDev, my scene editor will turn blank and show a small white error box with a face in the upper left corner. At that point, I am unable to interact with my objects in the active scene. This usually happens after I preview my game, as I'm editing the events, or a few moments after I open the program.

![Screen Shot 2022-01-08 at 2 00 04 PM](https://user-images.githubusercontent.com/59886508/148703729-21605478-108e-4470-93c9-1e034f382460.png)

## To Reproduce

1. Open GDevelop
2. Edit some objects on a scene, or events
3. Preview game
4. The error white box image will appear immediately or after a few tries.

## Other details
* My system: macOS High Sierra, version 10.13.6
* GDev version: 5.0.124 - Downloaded desktop app
* Used to happen a few times when I first used the app, then I noticed it started happening more frequently after the current update.

**Comment by AlexandreSi** [comment]
Hi @Bloomzeye!
Thank you for taking the time to report this issue.

We will need more info on this bug to fix it, so next time it happens, could you open the Dev tools (Cmd + Option + i) and see if there are any red messages in the console? If that's the case, can you copy-paste them here?

**Comment by 4ian** [comment]
Looks like a WebGL crash! In addition to what Alexandre asked, what's your macbook version and configuration? :)

**Comment by Bloomzeye** [comment]
Thank you both for responding! 

@AlexandreSi Someone in the discord did suggest for me to open the Dev tools, and I did see errors about WebGL when I did. I don't have a screenshot for it, but I'll be sure to take one when it happens again.

**Comment by Bloomzeye** [comment]
@4ian In addition to Other Details, I have a Macbook Pro - late 2011, Processor: 2.8 GHz Intel Corei7, Graphics: Intel HD Graphics 3000 512 MB, Memory: 8 GB 1333 MHz DDR3 (not sure if you need more or less info)

**Comment by Bloomzeye** [comment]
@AlexandreSi So I just updated GDev to 5.0.126, and after no crashes yesterday and today, it just crashed on me. Here's the info from the inspector. There were no red errors, just warnings about WebGL and DevTools.

- WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost 
- DevTools failed to parse SourceMap: file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.53f8a07a.chunk.js.map

**Comment by AlexandreSi** [comment]
Thanks for the details!

I can see 2 hypothesis to your problem:
- Either the version of electron we use has problems handling WEBGL contextes (see https://github.com/electron/electron/issues/4380)
- Either your computer doesn't meet requirements for WEBGL to correctly work. 

You seem to be the first user to experience this issue (so far) so I tend to think the second option is the most probable one (unfortunately for you). We will keep an eye on that though in the future.

**Comment by Bouh** [comment]
> - Either the version of electron we use has problems handling WEBGL contextes (see https://github.com/electron/electron/issues/4380)

Electron has just been updated, please download the latest version.
If you see again this crash feels free to open a new issue.
