### ISSUE TITLE
Template asks for new name, inconsistent dialog title

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#3497]
## Describe the bug
Opening a template will ask for a project name despite it already having one. I think when opening a template it is easier to distinguish in the "Recent projects" list etc. and more intuitive since asking for a new project name is not what I would expect when opening a template.

Moreover, in the web version, the dialog reads "New Project" while the desktop version reads "Project settings". I think it should be unified (content and letter cases). I plead for "Project settings" if this dialog is left in since opening a template is not a new project and when explicitly selecting "Create new project", the user most likely knows that this will be the name for the new project, in my opinion.

## To Reproduce
1. Go to the "Home" tab
2. Select an template
3. Click "OPEN"
4. See the dialog box

### Desktop version
![image](https://user-images.githubusercontent.com/83909121/149635010-962efae1-9a84-4d4d-b8a8-ce7f3673ad0c.png)

### Web version
![image](https://user-images.githubusercontent.com/83909121/149634866-1fbb6142-9fbe-4e8f-a17c-1a5be795f115.png)

Also, "Quick Support" and "Scattered Test" are a pretty funny but nice names.
Making random game names was a very cool idea. Thank you for that :p

## Other details
GDevelop 5.0.126 based on GDevelop.js 4.0.99-0-release
PC / Desktop GDevelop version, Windows, regular build, no nightly version
and GDevelop 5.0.126 web version, Google Chrome

**Comment by ClementPasteau** [comment]
Hello 👋 

I believe that the name is now consistent across web and desktop.
I'm not sure I agree with the idea of removing the name field though. You are technically creating a new project, which is based on a template. The field helps you customise it at this stage or you can continue without customising it.

We could imagine defaulting it to the Example's original name, but at the risk of people forgetting to modify it when they publish it.

**Comment by Elairyx7301** [comment]
Oh, alright. I see the issue and the thought process with an behind it and I fully understand it.
Thank you @ClementPasteau, I will close the issue then 👍
