### ISSUE TITLE
Bitmap Text Rendering Artifacts When Scaled

### ISSUE THREAD

**Issue by charburgx** [4ian/GDevelop#3516]
## Describe the bug

![bmtext_issue](https://user-images.githubusercontent.com/16108792/150264091-e4530988-4963-436d-8516-50a677a18ce1.png)

When bmtext gets scaled, rendering artifacts as seen here can occur.

This seems to happen because the bounding boxes of the font atlas are not defined accurately, and therefore some of the surrounding characters are spilling over.

**The video on this topic is blocked until this feature gets fixed.**

## To Reproduce
1. Create any bitmap text
2. Scale it

https://games.gdevelop-app.com/game-ed24e1a0-1182-4ff0-9bb8-3afe150f5a4c/index.html

In this game, here is the font files used: [bell3.zip](https://github.com/4ian/GDevelop/files/7901952/bell3.zip)

## Other details

Occurs on Windows 10, using GDevelop 5.0.124 Desktop edition.

**Comment by Silver-Streak** [comment]
I can't seem to reproduce this. 

You might just need to add padding between characters to your bitmap text from whatever application you created it with. I've scaled this one up to 4x and have it work fine. It's a CC0 font so here's a copy of the exported files.

[MonoGrambmf.zip](https://github.com/4ian/GDevelop/files/7902069/MonoGrambmf.zip)


1x scale:
![image](https://user-images.githubusercontent.com/24237149/150267487-f544dbb6-2ad4-4b93-b170-40af937d7035.png)


5x scale: 
![image](https://user-images.githubusercontent.com/24237149/150267528-5e9674ab-6cc7-4678-aea1-ad39f90a7097.png)

**Comment by charburgx** [comment]
Ah, yes padding fixes it. My bad!
