### ISSUE TITLE
Animation number error

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#3518]
If the Animation field in the properties panel is empty, it shows "1.50995e+08".
![04](https://user-images.githubusercontent.com/81538128/150372890-2790db4a-0347-4776-b0fa-a95391d78edf.png)

**Comment by AlexandreSi** [comment]
Hi @jack-ii 
Thanks for taking the time to report this.

Do you have a project that you can share where this happens? There is only a zero on my side.

**Comment by jack-ii** [comment]
Yes default is a zero but if you remove the zero... 
It's not terrible, but it just looks buggy.

**Comment by AlexandreSi** [comment]
Sorry to hear that.
The problem is I cannot reproduce it. Maybe there is something not usual about your config (preferences, version of GDevelop, computer OS). Can you give more details ?

**Comment by AlexandreSi** [comment]
Oh sorry, I just understood what you meant. I'll have a look!

**Comment by Bouh** [comment]
@AlexandreSi More details on scientific value here.
https://github.com/4ian/GDevelop/pull/2425#issuecomment-855299733
