### ISSUE TITLE
Identical action appears twice

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#3519]
The identical action is displayed twice when you search for "Create an Object".
![01](https://user-images.githubusercontent.com/81538128/150373242-f6e4d9de-7f5c-47c1-bd3d-4a85a93b6d8d.png)

**Comment by 4ian** [comment]
Are you using the new action and condition editor, and not the old, deprecated one (check your preferences)? 

It seems to work properly for me: 
![image](https://user-images.githubusercontent.com/1280130/150384594-4a82b1af-49b1-42bc-b324-5ac55f4961aa.png)

**Comment by jack-ii** [comment]
Yes I use the old editor and yes the new one doesn't have the problem.
Buuut I and many others would like to continue using the classic one.
If it's hard to fix it for the old one, it's okay, I just wanted to say it.

**Comment by 4ian** [comment]
Sure, thanks for checking 👍

Speaking of the old editor, apart from the habit, is there any reason you like it better than the new one?
The new one is almost basically the same but allow you to explore by objects first.
If you're a regular user and like to search like you did in this thread, then fear not! The new editor search is working the same, and you get the same result as in the old one:
- A list of all the actions/conditions matching your search (whether they are linked to an object or not).
- When you select one, you can enter the parameters as before - including the object if the condition/action is linked to an object.

![image](https://user-images.githubusercontent.com/1280130/150413948-be1aa7a4-3185-4b46-8e99-d4e15c032d42.png)

So on the search side, this should make the new editor experience almost exactly the same as the old one - except that if you know that you want to act or test an object, you can select it first and see only the action/condition related to this object :)

**Comment by jack-ii** [comment]
I was happy with the old one and never really tested the new one and I had no idea the issue could be related to the editor used. But now I use the new one and everything is good :)

Then I have another mini task.

- [ ] Fix the help button links in Bitmap Text, Tilemap and Light Objects

All other objects are already correct.
Tested with 5.0.127.
