### ISSUE TITLE
Remove duplicate Tiled Sprite Object Angle action

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#3522]
- [ ] Remove "Angle" in Tiled Sprite Object actions.
The condition is already removed.
There is a universal action/condition for sprite and tiled-sprite.

- [ ] Rename "Size and angle" to "Size" in the Tiled Sprite Object condition and action category.

**Comment by Bouh** [comment]
I agree these actions are in double.
![image](https://user-images.githubusercontent.com/1670670/150553832-a3817df2-fea4-483a-b66e-ab51620cc923.png)

**Comment by 4ian** [comment]
Fixed, thanks!
