### ISSUE TITLE
Exported assets have different permissions

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3548]
A forum user reports that larger images are exported with different permissions, causing display issues when embedded in a website.
![image](https://user-images.githubusercontent.com/25978830/150837239-41d205d5-f1f7-4ff6-a56f-00fb5e7c83c9.png)

[source](https://forum.gdevelop-app.com/t/permissions-of-png-when-exporting-to-html5/37663)

**Comment by Remonvs** [comment]
Please close this bug report. This was due to my error. Not Gdevelop.
