### ISSUE TITLE
Problem when passing from beta105 release to beta106 and beyond

### ISSUE THREAD

**Issue by Owildescar** [4ian/GDevelop#3552]
## Describe the bug
Hi guys,

I retook my game project a few weeks ago, but I am stuck with the 105 release. 
My games works perfectly until 105 version, but from 106 and beyond, the game crashes when loading one of the scenes I have made (actually my core game scene). 
There is no error message  on the developer tools console, it just seems that the game changes properly screen size but nothing more.

Thank you very much for helping! 
Adrien

## To Reproduce
1. Click on "Start Game"
2. Click on "Click on first level (green square)"

* Please include a link to a game if possible!
Working game with release 102 (but no bug to report until 105) : 
https://games.gdevelop-app.com/game-1cb8103b-22c8-4864-be66-0b842e23da92/index.html

Not working game with release 106 (but same problem with current releases of Gdevelop) 
https://games.gdevelop-app.com/game-3be7f181-cd78-4a12-86a6-4e4d2c16a5be/index.html

## Other details
* I use the desktop app

**Comment by 4ian** [comment]
There is indeed no crash, but your custom JS code has an infinite loop. You can find this by opening your browser debugger and hitting the pause button:
![image](https://user-images.githubusercontent.com/1280130/151050318-e9c95ada-8daf-4870-b9e0-6d84030c8f2c.png)

The `if` is never true so `m` is never changed and it runs forever. I'm unsure why this is caused in beta105 and after, but I see that you're using private properties starting with an underscore.
*Never ever do* that because this is **guaranteed to break** in the future versions. Always use public properties and public methods, like `getVariables`, `getValue()` etc... You can find them all here: https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/index.html :)

**Comment by Owildescar** [comment]
Hi Florian,

Thank you for such a quick response, and your advice...

I guess that I will not upgrade Gdevelop to the latest version as my JS
code unfortunately has thousands of lines like that, calling variables
starting with underscore.  :/

Best regards and thank you again for your time
Adrien



Le mar. 25 janv. 2022 à 21:02, Florian Rival ***@***.***> a
écrit :

**Comment by 4ian** [comment]
I would still try to study why the infinite loop is happening. Is there some type mismatch?
I would also make a safety backup of the project.json and then in a text editor I would open the project.json and try to replace all the _variables with `getVariables()`, and so on to try to get back to a state where you use less private properties.

But you need to understand why this is creating an infinite loop. It must be not that complicated. Once you know why, you can fix your code and try again with a newer version :)

**Comment by Owildescar** [comment]
Hi Florian,

Thank you so much for the advices. You are right, I will definitely look
and find why it's looping... And also you are right, I slept on it, and
it's maybe not so much of a big deal replacing all the bad callings. I'll
try the way you explained.

Thank you again and I wish you a very good day!
Adrien

Le mer. 26 janv. 2022 à 00:33, Florian Rival ***@***.***> a
écrit :

**Comment by Bouh** [comment]
Good continuation with your game, we close because it is not a bug related to the engine.
If you need more help you will find it on the forum and on the discord.

**Comment by Owildescar** [comment]
Merci les gars,

Pour l'histoire, j'ai remplacé les ._variables comme conseillé par Florian,
et il n'y a plus de problème de boucle infinie...

Voilà!
A bientôt peut-être!
Adrien

Le dim. 30 janv. 2022 à 12:46, Aurélien Vivet ***@***.***> a
écrit :
