### ISSUE TITLE
Improve starting scene selection

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3560]
## Description

Currently, when a game starts, the scene that plays is based on its position in the list of scenes.  This is not obvious to many new users.

## Solution suggested

- [ ] Provide a visual indicator of the scene that is the "starting scene"
 -  Small icon on the starting scene (could be placed left of text, or left of triple-dots)
 -  Hovering on that icon shows a tool-tip "Starting scene"

- [ ] Allow users to specify the starting scene
 - Right-click on scene name allows users to select "Make starting scene"

## Screenshot

![Untitled](https://user-images.githubusercontent.com/8879811/151588007-41ec4eee-ac62-4f96-b099-3e2d302b40c4.png)

**Comment by 4ian** [comment]
Totally agree we need 1) an indicator and 2) the choice to change the first scene.
We can probably find an icon for this on https://materialdesignicons.com/

**Comment by PascalLadalle** [comment]
As long as we can't drag-n-drop to reorder scenes, I recommend the second suggestion.
If we can drag-n-drop, I would prefer a special header slot for the starting scene.
This has been requested a number of times, I believe. Including a [long time ago](https://forum.gdevelop-app.com/t/setting-default-scene-w-out-reordering/9978). 😅

**Comment by Bouh** [comment]
I suggest adding a text, an icon/symbol can be interpreted differently while the text is clean and can be translated.

![image](https://user-images.githubusercontent.com/1670670/151664285-c7ef1285-281c-42c4-831a-af6c52d52445.png)

**Comment by tristanbob** [comment]
I actually like @Bouh and @PascalLadalle idea (special formating of the top scene) better than my idea of adding an icon.  Their idea makes it easy to understand, and since people read top to bottom (I think) it is more intuitive for the top scene to be the starting scene. 

I also agree with @PascalLadalle that scenes need the drag+drop behavior that GDevelop uses for other areas (such as functions and behaviors.).

**Comment by AlexandreSi** [comment]
Hi there!
Well, as you all mentioned, this issue addresses 2 features: 

1. the possibility to drag and drop items in the project manager
2. the possibility to chose the starting scene

I'll work on point 2. with a minimum effort (@tristanbob suggestion) as I feel like we will soon change the project manager more deeply. I don't want to work too much on something that will eventually be reworked.

**Comment by 4ian** [comment]
Agree with this, the drag'n'drop would be great but let's for now do the minimum work to choose the starting scene.

**Comment by AlexandreSi** [comment]
Here is what I got so far:

![image](https://user-images.githubusercontent.com/32449369/151785068-513ca33e-bbc3-46c7-86da-a141ec27044d.png)

I guess it would be better having it on the right side of the row

**Comment by 4ian** [comment]
Might be worth investigating if we can put it near the name or on the right hand side, because this is indeed not really an "icon" but, like the Private indicator for functions, an indicator of a property.
