### ISSUE TITLE
Inverted Raycasting condition ignores additional Collision Masks on the same object

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#3563]
## Describe the bug
If a sprite object has multiple collision masks in the same object (to deal with shapes that would otherwise be convex), the inverted raycasting condition will only find points within the _newest created_ collision mask, instead of all of the collision masks of the object.

## Long Version/Why this matters
I am working on a point and click adventure game template/example for the engine. 
Currently, there is not an easy (or really, any) way to replicate proper point and click adventure game movement in the engine.
In classic and modern adventure games, there is a defined "valid movement area" and if you click anywhere within it, the character will pathfind to that point. This is doable in the engine. 

However, in those same games, if you click _outside_ the valid movement area, the character will pathfind to the closest moveable area that _is_ valid. Right now there is not a way to do this in the engine.

The closest way I and anyone on the discord have found to accomplish this _should_ be by defining the movable area as the collision mask of the background, then set up an inverted raycast to find the last point that is still valid for the background sprite object. This almost works, except in most cases players are going to need to set up numerous collision masks within the same object to accommodate non-convex areas that are valid for movement. As mentioned above, the raycast will only find valid points within one collision mask of an object, and only the newest one.

## To Reproduce
1. Create a sprite object. (We'll call this "Destination")
2. Add a custom collision mask of any shape.
3. Add an additional custom collision mask of any shape (overlapping or not).
4. Add another sprite object of any kind (we'll call this "Start").
5. Place both on the scene.
6. Add a text object. 
7. Add it to scene.
8. Add an event with an "Left mouse button is down" condition and inverted raycast that tests from the "Start" object against the MouseX/Y position, against the "Destination" object. Add an inverted "Point is inside object" using the MouseX/Y points and the "Destination" object.
9. Have the action update the text object to show the X/Y variables from the raycast.
10. Preview the scene and click outside the Destination object. No matter where you click, it will only show X/Y locations within the last created collision mask. It will treat the other collision masks as if they were part of another object.

* Here's an online export of an example set up really quickly: [Online Example](https://liluo.io/games/ead6eddb-6600-47f9-b08a-d62ab2fa9ea3)
* Here are the collision masks: 
![image](https://user-images.githubusercontent.com/24237149/151668252-8520f621-64a1-444f-8ae1-c971584a69dc.png)
* Here are the events: 
![image](https://user-images.githubusercontent.com/24237149/151668267-ff2aca41-f500-4193-93bf-6fb9b9d9297f.png)
* Here's a copy of the project: 
[RayCastTest.zip](https://github.com/4ian/GDevelop/files/7964065/RayCastTest.zip)

## Other details
* Windows 10 Pro 64-bit
* Tested on both desktop and web demo versions of 5.0.126
* This may be related to https://github.com/4ian/GDevelop/issues/3498

**Comment by 4ian** [comment]
Thanks for the reproduction project! Very very useful. This is indeed a pretty annoying bug. I'm fixing this :)
