### ISSUE TITLE
Project title - loss of focus

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3570]
If I create a new project with File/Create/Create a blank project, when trying to write in the fields, I keep losing focus at every letter I type, in both fields.
![image](https://user-images.githubusercontent.com/25978830/151708765-9a135358-dde2-4374-9ed8-78d97578e068.png)

No issue using the Create a blank project button on the homepage, so the Examples menu may be stealing focus when open?

**Comment by Bouh** [comment]
Probably already fix by https://github.com/4ian/GDevelop/pull/3512

**Comment by ClementPasteau** [comment]
Confirmed this is fixed 👍

**Comment by AlexandreSi** [comment]
Thanks for reporting this @PascalLadalle! I fixed it indeed, it will be ok in the next release that should arrive soon

**Comment by PascalLadalle** [comment]
Oopsie, sorry. I did think it rang a bell. 😅 
Good job! 👍
