### ISSUE TITLE
Platformer fall speed affects jump height

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3575]
A user on the forum wants a gliding effect, but setting a very low fall speed increases noticeably the jump height.
I assume it's acting as a brake during the jump, and I wonder if this force should only be triggered when max jump height has been reached, to avoid this side effect.

On a side note, shouldn't we rename "jump speed" with "jump height" or "jump force"?

[source](https://forum.gdevelop-app.com/t/changing-the-maximum-falling-value-of-platform-object-behavior-to-a-small-value-is-directly-influencing-the-jump-height/37815)

**Comment by Bouh** [comment]
Hope the platformer expert @D8H can help you with it.

**Comment by D8H** [comment]
I guess this issue can be closed.

The forum question was answered with the following example and the mention of the "abort jump" jump action.
https://editor.gdevelop.io/?project=example://platformer-jump-evaluator
