### ISSUE TITLE
"Scan in the project folder for images" function of Resources will create copies of matching resources

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3590]
## Describe the bug

"Scan in the project folder for images" function of Resources will create copies of matching resources.  See video.

https://user-images.githubusercontent.com/8879811/152084909-2b794759-d647-4eef-8e3e-e9967f6ac2a5.mp4

## To Reproduce
1. Go to 'Resources'
2. Right click on an image and choose "Scan in the project folder for images" 
3. New resources will appear with a number appended to the file extension

Thankfully, the right-click "Remove unused images" deletes the extraneous resources.

## Other details
* Windows 10
* GDevelop 5.0.127

**Comment by 4ian** [comment]
Interesting, can you check if the file are exactly the same between the resources? Notably if they are using a slash or backslash?

**Comment by 4ian** [comment]
Thanks for reporting, I've fixed what should be causing this issue!
