### ISSUE TITLE
Expressions autofill bug

### ISSUE THREAD

**Issue by HelperMuzan** [4ian/GDevelop#3591]
## Describe the bug
The autofill for string expression even shows number expressions.

## To Reproduce
1. Go to any action or condition that requires the user to fill out string expressions.
2. Write the expression with parenthesis included.
3. Move the cursor over the expression.

* If applicable, add screenshots to help explain your problem.
Without parenthesis
![0iT4h2G](https://user-images.githubusercontent.com/85349700/152158488-3f4ff573-f85a-4e10-8088-cec091b9266e.png)
With parenthesis
![COtmBOm](https://user-images.githubusercontent.com/85349700/152158590-fec78a78-91da-4ba9-955d-bb52376cd158.png)
![KcujqKA](https://user-images.githubusercontent.com/85349700/152158624-48d157e7-7243-4b36-b307-635d82682104.png)
![GDevelop_AYvqYE8O4h](https://user-images.githubusercontent.com/85349700/152158677-3782904e-fcc3-4d1a-be16-668fe16c351b.png)

## Other details
* Include any OS/browser version/smartphone that you're using
Windows 10
* Which version of GDevelop are you using? The desktop app or the web-app?
Desktop App
* Add any other context about the problem here.
The same seems to happen on number expression autofill too.

**Comment by willianholtz** [comment]
I believe you are trying to get an integer variable and not a string.
In the last image you use round, but don't use ToString(Round())

**Comment by Bouh** [comment]
As you can use the convert expression I think it's legit to have both in the auto-suggestion of expressions.
