### ISSUE TITLE
Groupe name of functions are not indented under the extension name

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3600]
## Describe the bug
Functions can have group name, but this name is used as a category in the instruction editor but not under the extension name.
I was hyped with this demo of [this PR](https://github.com/4ian/GDevelop/pull/3366) :
![image](https://user-images.githubusercontent.com/1670670/152599461-7537347c-f92b-44b7-8396-1c050c19a07c.png)

But I get this list without indentation under the extension name:
**Global variables** should be indented under **Extended variables support**.
![image](https://user-images.githubusercontent.com/1670670/152599636-7c2b6110-ff7c-4aec-8539-c850092ffb4e.png)

If you wanna try here the extension used in the screenshot.
[test-Extension.zip](https://github.com/4ian/GDevelop/files/8006094/test-Extension.zip)

cc @D8H 

## Other details
* 5.0.127
* W10

**Comment by arthuro555** [comment]
It works fine for me on the latest nightly build already:

![image](https://user-images.githubusercontent.com/19349038/152640961-516d83a3-5d60-4b19-9112-eff5c33c0ea9.png)
![image](https://user-images.githubusercontent.com/19349038/152640979-324c9386-9889-4e12-9d43-4eab25457eae.png)

**Comment by D8H** [comment]
Yes, Florian fixed it with:
* https://github.com/4ian/GDevelop/pull/3583

**Comment by Bouh** [comment]
Nice to heard that thanks :)
