### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by GamerGab02** [4ian/GDevelop#3617]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at sa (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:252630)
    at Pa (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:257354)
    at Da (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:261044)
    at https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:274313
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:285080)
    at Ou (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:274247)
    at Eu (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:274023)
    at wu (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:273368)
    at Iu (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:274747)
    at In (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:206434)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/63.b67a71f2.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in t
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ul
    in ForwardRef
    in ForwardRef
    in n
    in div
    in ForwardRef
    in div
    in Unknown
    in t
    in n
    in div
    in a
    in o
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in C
    in div
    in n
    in l
    in n
    in ForwardRef
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.127-2c4fa1d1c20c40d4fca8316c2076d39a6e96cdfa
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43,

**Comment by GamerGab02** [comment]
Buongiorno a me continua a crashare l'editor quando schiaccio una condizione nella parte nuove condizioni.
![Immagine 2022-02-11 130712](https://user-images.githubusercontent.com/99482150/153588834-52eff6a7-2b01-4afd-b7b5-2ef6755f75da.png)
Qui per intenderci.
Grazie.

**Comment by Bouh** [comment]
Hello @GamerGab02 
Your interface is odd, any chance you used Google Translate on the page?
We know that browser feature can cause bug.

If you use Google Translate, you can avoid to use it, GDevelop is translated in lot of language, just go on the homepage of GDevelop editor, and on bottom right you can change the language settings.
![image](https://user-images.githubusercontent.com/1670670/153659354-edb1e35b-77d8-4e3b-954c-7aec35db8161.png)

**Comment by GamerGab02** [comment]
Si io ho usato Google Translate da ora in poi userò la funzione Gdevelop
Grazie mille

**Comment by Bouh** [comment]
Same bug as [#3609 ](https://github.com/4ian/GDevelop/issues/3609#issuecomment-1035155247)
