### ISSUE TITLE
Objects with broken resources are not visible in scene editor

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3658]
## Describe the bug

An instance on the scene with a broken resource is invisible.

✔ - On left an object without resources, 'res/unknown32.png' is used.
❌ - On Right an object with a resource but the path is wrong or/and the asset cannot be loaded successfully, 'res/unknown32.png' should be used too in the scene editor, and we might fix the thumbnail too.
❌ - Invisible instance has by default 1x1px dimensions (I rescaled it on my capture), which is small, why not up to 32x32 like for the default object dimensions in the object properties dialog. 

![image](https://user-images.githubusercontent.com/1670670/154468260-f25e30eb-ce3c-46e8-a3ef-5dcfeeec92ee.png)

## Other details
Everywhere
All versions

**Comment by 4ian** [comment]
You're right, we should at least show the same `res/unknown32.png` (or an updated version) in this case.

Note that the game engine would display a different invalid texture (a very small bright pink texture), but here the idea is to make it clear there is a missing resource somewhere :)

**Comment by osmaneTKT** [comment]
Hi, it seems the issue is resolved because I can't reproduce the bug @4ian  @Bouh

**Comment by Bouh** [comment]
> Hi, it seems the issue is resolved because I can't reproduce the bug @4ian @Bouh

Indeed, thank you for your attention to this point.

**Comment by osmaneTKT** [comment]
@Bouh , is there an uncomplicated issue to work on? I'd like to make my first contribution but am hesitant to dive into something too difficult because it's for a course requirement.
