### ISSUE TITLE
Publish on the game's page when we're not the owner of the game

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3660]
## Describe the bug

I exported a project but I'm not the owner, and I can see the button to push the update of the game to the game's page (on liluo I guess).

![image](https://user-images.githubusercontent.com/1670670/154478422-31c85f33-b687-4c91-a6a1-09562d07d751.png)

## To Reproduce
1. Open a project where you're not the owner
2. Publish > share with friends > generate a link
3. See the button to Publish the game to the game's page

## Other details
* 5.0.127

**Comment by ClementPasteau** [comment]
Good catch, this button should not appear here. 

Even if this will not happen that often, this is confusing for the users.
I also suspect that the button will error when you click on it.
