### ISSUE TITLE
Keyboard clears all events!

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3674]
If that wasn't supposed to happen, it's a critical bug! Look:

https://user-images.githubusercontent.com/23488207/154775604-ee901167-1285-454a-a989-b404b34b2ca2.mp4

Pressing any key while events are open!

Windows and Linux, version 127!

**Comment by ukStream1** [comment]
It's not a bug, when you pressed a key, it started searching events (and started filtering), look at the bottom left of the IDE, there is a search bar and whatever you typed is being typed in the search form.

![image](https://user-images.githubusercontent.com/92215551/154783071-089e72d5-a589-4d8f-a604-3bcf6e5eb2da.png)

**Comment by willianholtz** [comment]
Wow, for a moment I thought I had lost all my events, so I closed gd! Good to know!
Sorry for the open issue!
