### ISSUE TITLE
add the missing fade audio/music volume action in Gdevelop

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#3688]
![Screenshot_85](https://user-images.githubusercontent.com/98941240/155297078-be5932df-0b07-4949-9b46-1536c0baff77.png)
## Description

I always wondered whether there was a better way to fade audio/music since updating the volume level with a variable can be choppy, and after a few months I discovered that Arthuro mentioned that it exists in the code but does not show up in Gdevelop
and this can only be accessed by using a javascript event.
Javascript code in mention:
runtimeScene.getGame().getSoundManager().getSoundOnChannel(1).fade(0, 1, 1000);

After waiting many months to see whether it was fixed, it never was nor was it ever reported so I decided to open it up.

## Solution suggested

add an action for the code that exists but is not used. I believe this will be a very useful action for controlling the volume levels smoothly once implemented properly

**Comment by Oxey405** [comment]
Hello ! I promise nothing but I can try to see what I can do to fix that !

**Comment by ClementPasteau** [comment]
Hey @Oxey405 thanks for giving it a try!

Let us know if you need a bit of guidance on where to start :)
