### ISSUE TITLE
Loading example project freezes

### ISSUE THREAD

**Issue by pencilmalon** [4ian/GDevelop#3715]
Fix it please

![gfgfgf](https://user-images.githubusercontent.com/100098699/156249865-6a83c3ec-1675-41dc-ad53-171a6c2f1b3b.png)

**Comment by PascalLadalle** [comment]
Please confirm the exact version of GDevelop you use, and the example you're trying to load.
Also confirm that you tried to close and reopen GDevelop, and that you made sure you are connected to the Internet before opening it.

**Comment by pencilmalon** [comment]
ok nvm  itt works
