### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by LayaNett** [4ian/GDevelop#3716]
=> I'm not sure what's happening, every time I try to do a project, blank or tutorial, I immediately get an error message. I'm brand new so I don't have any past projects, and once I get this message, I can't do anything else unless I completely close GDevelop and reopen it. The videos and other's published projects work fine, I can go on those, but for some reason I can't start my own project. And sometimes I won't even get an error message, I just can't do anything. It does nothing but load. I tried redownloading GDevelop
but that made no difference. 
When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: Failed to get 'documents' path
Underlying stack: Error: Failed to get 'documents' path
    at electron/js2c/browser_init.js:6745:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)

    at electron/js2c/browser_init.js:6748:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)
```

## Component stack (don't write anything here)
```

    in Unknown
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.128-60088ebafd094b00260d3ec7f199186160317b02
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.128 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @LayaNett 
Thank you for reporting this crash. Can you give us a little bit of background on what you're trying to achieve before the crash?

**Comment by ClementPasteau** [comment]
same issue as #3700

**Comment by ClementPasteau** [comment]
this should be fixed for next release 👍
