### ISSUE TITLE
Eliminate confusion at game export

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#3729]
- [ ] Rename the button PUBLISH ON STORES to PUBLISH YOUR GAME, like the name of the next window that opens.
Or better EXPORT YOUR GAME

![05](https://user-images.githubusercontent.com/81538128/156892147-296c21a7-283e-423c-b55c-92b52b9bb9a7.png)

There is no upload to stores. Many who want an exe or apk don't think about the stores.
publish, build, blah.. all they want at this point is Export :)
Today we had the third angry(!) forum threat because someone couldn't find the online build options anymore after the rework.

___

What do you think about exporting the manually HTML5 build optional as .zip/.7z?
It would be much easier to load it on itchio, etc.

**Comment by 4ian** [comment]
Thanks for reporting this :) 

> Today we had the third angry(!) forum threat because someone couldn't find the online build options anymore after the rework.

Do you have a link to this thread?

**Comment by jack-ii** [comment]
> Do you have a link to this thread?

No, it was closed and unlisted by Silver-Streak.

**Comment by arthuro555** [comment]
We get such reports *all the time* on discord and on the forums. The topic in question is probably the folowing: https://forum.gdevelop.io/t/alright-gdevelop-is-getting-kinda-stupid-with-the-installations/38513?u=arthuro555
