### ISSUE TITLE
Can't download GD5 update while sharing 4G with Android WiFi hotspot

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#3734]
## Describe the bug
I found an interesting bug while trying to update GD5 using the WiFi hotspot of my Android phone which uses 4G.
The update results in an SSL error. See the following screenshot :

![image](https://user-images.githubusercontent.com/9526774/157043165-31869db4-3b61-46f3-961f-60e8c6fd71d0.png)

GD is not the only software to have this issue, this seems quite common. SSL is a bit touchy while I'm using 4G network.

## To Reproduce
1. Connect your computer to your mobile WiFi hotspot
2. Launch GD5 editor and check for an update
3. Wait for the editor to automatically start the download
4. The error will occur a few seconds after the download start or at initialization

## Other details
* GD 5.0.126
* Windows 10 / 21H1
* Android 10 / Huawei P40 ANA-NX9
* WiFi USB stick / D-Link DWA-125 Wireless N 150

**Comment by 4ian** [comment]
> GD is not the only software to have this issue, this seems quite common. SSL is a bit touchy while I'm using 4G network.

In this case, I think this is not a real issue for GDevelop.
It seems that your hotspot is not guaranteeing properly the validity of SSL certificates or has some issues like this. The fact that the download is not working means that things are working properly: your computer is refusing to do something considered insecure.

This being said, this bad "uncaught exception" is not super clear and we should probably catch the exception internally and issue a generic user error.

**Comment by timotheeficat** [comment]
I see, you may be right. I just realized that every software with this same issue is running using Electron or some JS.
Anyway, this is pretty random as well. I just successfully updated GD5 to the latest version.

Thank you for your thoughts, I'm closing this as it is indeed not really related only to GDevelop.
