### ISSUE TITLE
[$5 Bounty] Clean all unused resources

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3740]
## Description

I suggest adding "All" in the context menu of the unused resources.

![image](https://user-images.githubusercontent.com/1670670/157463402-693fc6e5-6b7c-4c44-baac-aa9dccb88727.png)

**Comment by Bouh** [comment]
Open to all contributors, except GDevelop employees.
Feel free to start working on it. I don't give advice on how to get started, it should be pretty easy.

**Comment by Oxey405** [comment]
Hey ! Can I try to fix it ?

**Comment by 4ian** [comment]
Sure go ahead! :)

**Comment by Bouh** [comment]
Wait for the bot scanning[ this issue ](rysolv)and mark it as Done on rysolv.com

**Comment by Oxey405** [comment]
@rysolv-bot please scan this again.
