### ISSUE TITLE
Allow re-ordering of effects (object/layers)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3749]
## Description

I recently learned that the way effects are ordered will change how the effects are applied.  

For example, "glow + outline" looks different than "outline + glow".

If users want to adjust the order of effects today, they need to delete and recreate the effects. 

## Solution suggested

Allow users to change the order that effects (both objects and layers) are listed.  

Preferred method: Drag and drop the effects to reorder

Alternative method: Add "Move Up" and "Move Down" in a right-click menu

**Comment by AlexandreSi** [comment]
Looking at it after the variables editor rework, I think other features could be implemented as well:

- Prevent renaming an effect to an already taken name (easy)
- Prevent setting an empty name for an effect (easy)

For other issues maybe:

- Add possibility to fold and unfold event content (medium)
  - When opening an Effects editor, fold all the effects
  - but I don't think it's necessary to store the state as for the events
- Add possibility to copy and paste effects thanks to a toolbar (medium)
- Visually, I find it difficult to distinguish a parameter line from an effect line, there's maybe something to do here (medium with a bit of research)
- Add a preview of the resource with the effects applied (difficult)
