### ISSUE TITLE
Java exception error

### ISSUE THREAD

**Issue by ThirstyTryhard** [4ian/GDevelop#3775]
I've downloaded the recent update for Gdevelop 
GDevelop-5-Setup-5.0.130

Everytime I try to download a resource for my game, it tells me that something went wrong with my javascript, I also cant edit items with piskel..Help?

**Comment by Silver-Streak** [comment]
Hello! In order for anyone to assist, you'll need to post a screenshot of the exact error, as there can be hundreds of permutations of the same error message.

After you post that, people may be able to better assist.
