### ISSUE TITLE
Editor is slow, when inserting a tilemap

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3793]
After a lot of conversation on Discord, to try to solve my problem, I decided to post it here so that some dev can try to help and find out what might be happening.

[Discussion link
](https://discord.com/channels/258623956158906368/258659467887902730/959188541433340014)

What I did and what I know so far:

- I formatted my computer
- I changed my SSD (to solve the doubt)
- Updated video driver
- O.S: Arch Linux x86_64 Gdevelop 130
- Web version works fine
- Only the editor is very slow (desktop), but when running the game, everything runs 100%
- **This only happens with tilemap**
- ctrl+shift+i  does not work, much less by the toolbar (View>toggle...)
- Debug via terminal: Only problem I could find was this: 

`18:59:04.600 › GDevelop Electron app starting...
[8033:0331/185908.218383:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
`

Game:
https://user-images.githubusercontent.com/23488207/161154913-5f40d45a-0be6-448c-9fcf-eabf29cc59cf.mp4

Editor when placing the tilemap:
https://user-images.githubusercontent.com/23488207/161155185-8811919b-788d-4d63-b923-674a4d3d3c94.mp4

**Remembering that, this is only happening in the desktop editor. But when running the game is 100%.
The WEB version of gdevelop, everything works.**

**Comment by 4ian** [comment]
> Web version works fine

Just to double check: did you try with the exact same tilemap?

**Comment by Silver-Streak** [comment]
@4ian: Yeah, they even tried with Not-a-vania on the web app and on the desktop. Works fine in the web app (readding the same tilemap object to the scene), crashes when on the desktop.

**Comment by willianholtz** [comment]
Today I did a test, on a PC inferior to mine (much inferior) without any offboard video card, 2GB of Ram and core2duo. A 2008 machine I have here. Impressively, everything worked 100%, without any kind of lag or frame drops, and the tilemaps didn't slow down Gdevelop, I even put many on the screen:

![Windows](https://user-images.githubusercontent.com/23488207/161267939-65fc9cfe-095c-46ba-8897-005f2f97626b.png)


Funny that a while ago, on my current machine, none of these things happened. It was even faster than on Windows. Now, a machine inferior to mine is able to run better.

What I'm thinking may be, because I use Arch Linux, a Rolling Release distribution, is that some dependency that Gdevelop uses may be causing this problem, such as the Electron version, nodejs or some other dependency that may have some code depreciated. I do not know.

**Comment by AlexandreSi** [comment]
Closing this as the next version (5.0.133) should fix this with Electron v18
