### ISSUE TITLE
Upgrade to Electron 18

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#3801]
It's a long time (1.5 year) since we last updated Electron. We're lagging behind several major versions now and it may be the reason for some performance issue on some OS.

We should:
- Upgrade to the latest Electron version
- Adapt code using `remote` to use `@electron/remote`...
  -  ...before migrating (in another PR, less urgent) to exposing just the necessary apis through the Electron preload.js script
- Adapt code using ipc (we have to expose ipc through preload.js too).
- Adapt code of the third party editor bridges
- Also upgrade the games runtime I think (can be done in a separate PR).
- Ensure "it works". Check on Windows/macOS/Linux, ensure auto update works.
  - Check if it works better with Flatpak (https://github.com/flathub/flathub/pull/2964)

I'm ready to open a large bounty to do that if someone wants to take this task :) 
Bonus point if you do the removal of `remote`/`@electron/remote` entirely in favor of an API exposed in preload.js - but I'm willing not to do that first to ensure we can release asap a version with a new Electron version without breakages.

**Comment by 4ian** [comment]
@nilaymaj You did the last update, would you be interested in taking this? Happy to open a large bounty if you're interested, let me know :)

**Comment by nilaymaj** [comment]
Sure, let me try this - it's much larger than the earlier upgrade (10 major versions!). I'll start with going through and summarising the Electron changelog, may take a couple of days.

**Comment by 4ian** [comment]
We're probably only interesting in the breaking changes ;) https://www.electronjs.org/docs/latest/breaking-changes

From a quick look, these are the changes we need to take care about:
- "Removed: remote module" => see my original message (we should use `@electron/remote` and in the long term move toward a "preload.js" approach, but this should be done carefully one feature by one).
- "Removed: app.allowRendererProcessReuse" => remove the related code and check there are no issues on Windows when loading/saving files (we had some issues with `fs` on Windows on Electron 8 with this flag).
- "Removed: BrowserWindow extension APIs" => should switch to using `session` object methods.
- "Deprecated: WebContents new-window event" => to replace with `setWindowOpenHandler`
- `contextIsolation` should be set to false (and nodeIntegration kept to `true`). In the long term this should be removed (in favor of the "preload.js" approach).
- "API Changed: shell.openItem is now shell.openPath" => quick update for us to do too.
