### ISSUE TITLE
Mistranslation or typo in the french language when publishing on liluo

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#3833]
## Describe the bug
I was publishing a game on liluo with the french language and I saw this.
![french](https://user-images.githubusercontent.com/61246500/163731401-197d77d6-7e7d-45e6-8bab-572c37943f45.png)
![english](https://user-images.githubusercontent.com/61246500/163731460-3478f92a-b58d-4639-aa69-c71235cd3270.png)

This is clearly an error.

Just signaling this issue to follow the convention but I will basically fix it on crowdin !

**Comment by Bouh** [comment]
Seem you did the fix on Crowdin, thank you!
