### ISSUE TITLE
Release note HTML tags

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3836]
## Describe the bug
HTML tags are not supported in the release note, until now markdown used works perfectly, if you need to reduce an image, crop it in your favorite tool.

![image](https://user-images.githubusercontent.com/1670670/163954578-ea15aab9-6ac3-4d4f-8544-2517c3f72138.png)

## Other details
* [5.0.132-beta1](https://github.com/4ian/GDevelop/releases/tag/v5.0.132-beta1)

**Comment by AlexandreSi** [comment]
I am not sure if this is a bug or if I failed at doing something for images.

**Comment by Bouh** [comment]
> I am not sure if this is a bug or if I failed at doing something for images.

Isn't not a bug, It was to let you know for the future releases ;)

Btw I fixed it.

**Comment by 4ian** [comment]
Good catch, we must indeed use the `![image](url)` Markdown format :)
