### ISSUE TITLE
[BUG] Names of animations and mouse clicks

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3845]
On linux, when we put an animation name equal to an existing one, the message appears but it is not possible to close it with the mouse click. Just pressing ESC:

https://user-images.githubusercontent.com/23488207/164463867-8bf6cab4-319b-4eee-98ce-45fa46f86943.mp4

This "bug" has been around for a long time!

**Comment by 4ian** [comment]
Probably an issue with the window manager/Electron. Let's hope the upgrade to Electron 18 solves this.

**Comment by Elairyx7301** [comment]
That's strange. On Windows, I can close the dialog just fine with "Ok", "x" or ESC (or RET).
Maybe there is an issue between electron and linux (if that ca neven be the case here)?
![image](https://user-images.githubusercontent.com/83909121/164896864-2fa94e22-162d-42f6-b6d9-689b87d49bd5.png)

**Comment by AlexandreSi** [comment]
Closing this as the next version (5.0.133) should fix this with Electron v18
