### ISSUE TITLE
[Asset Submission] Pixel Effects pack by CodeManu

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3846]
![cover](https://user-images.githubusercontent.com/73597906/164481463-5194b27b-d558-4422-9987-887dbda48ac0.png)

Author: CodeManu [https://codemanu.itch.io/]
License: Public Domain (CC0)

[Free Pixel Effects Pack.zip](https://github.com/4ian/GDevelop/files/8531922/Free.Pixel.Effects.Pack.zip)

**Comment by 4ian** [comment]
Very nice! @Bouh take a try if you have time, otherwise I'll add them :)

**Comment by Bouh** [comment]
It's on my to-do list for tomorrow.
