### ISSUE TITLE
Available easings cannot be seen

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3878]
When picking an easing, the first 25 easings are shown and the label "And 10 others" is visible at the bottom.
![image](https://user-images.githubusercontent.com/25978830/167250058-bc2484a8-7b01-4f73-bd7c-0e8d5689da12.png)

The problem is that the names are somewhat obscure and users have no way of accessing those 10 others, except coming here and checking the source code, or typing random letters to trim the list.
Considering that the list is fixed, it would be nice to see the full list of the 35 effects, or to be able to click on the "And 10 others" to expand the list.

On a side note, a forum user would like more tweens: for instance, there is a easeOutBounce but no easeInBounce.

[source](https://forum.gdevelop.io/t/some-tween-easings-gone-missing/39482/6)

**Comment by Silver-Streak** [comment]
> Considering that the list is fixed, it would be nice to see the full list of the 35 effects, or to be able to click on the "And 10 others" to expand the list.

Just to chime in on this, we see A LOT of people asking about this for all of the lists that are truncated. There really should be a way to expand results on lists like this, especially since in many cases users won't have any way to know what other options there are for most results like this (tweens, expression builder, etc)

**Comment by Bouh** [comment]
I agree with you and other people complaining on the forum.
The truncated list limits us :( even for the search in the instruction editor and expressions editor.

**Comment by 4ian** [comment]
I've done a fix for the expressions (so that it works for tweens but also for any completion in an expression editor).
For actions/conditions, we could indeed have something that does the same, or a button "Display the rest".
