### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by areperez** [4ian/GDevelop#3879]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of null (reading 'offsetWidth')
    at d (https://editor.gdevelop.io/static/js/0.925f0bef.chunk.js:2:1737653)
    at https://editor.gdevelop.io/static/js/0.925f0bef.chunk.js:2:1738265
    at https://editor.gdevelop.io/static/js/0.925f0bef.chunk.js:2:1738321
    at oa (https://editor.gdevelop.io/static/js/64.b7ed370b.chunk.js:2:439328)
    at Na (https://editor.gdevelop.io/static/js/64.b7ed370b.chunk.js:2:447029)
    at l (https://editor.gdevelop.io/static/js/64.b7ed370b.chunk.js:2:470189)
    at p (https://editor.gdevelop.io/static/js/64.b7ed370b.chunk.js:2:470817)
    at MessagePort.D.port1.onmessage (https://editor.gdevelop.io/static/js/64.b7ed370b.chunk.js:2:472517)
```

## Component stack (don't write anything here)
```

    in ForwardRef
    in ForwardRef
    in ul
    in ForwardRef
    in ForwardRef
    in div
    in div
    in r
    in H
    in div
    in div
    in div
    in ForwardRef
    in ForwardRef
    in J
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.132-fbeeb589a2f04d8e47a7c35a9b3c4130271e7b95
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 YaBrowser/22.3.3.852 Yowser/2.5 Safari/537.36,

**Comment by Bouh** [comment]
This `offsetWidth` is used in two places, one is an external library, and the second is the carrousel on the homepage.

![image](https://user-images.githubusercontent.com/1670670/167449479-febf3f89-2e6c-43fa-8b10-db24b84253e5.png)
