### ISSUE TITLE
Asset store submission (zaphgames: Xbox 360 Buttons)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#3881]
Trello card: https://trello.com/c/WVnNwLKM/97-zaphgames-xbox-360-buttons
Package: [Xbox 360 Buttons.zip](https://github.com/4ian/GDevelop/files/8651581/Xbox.360.Buttons.zip)

**Comment by Bouh** [comment]
I added the **xbox** tag.

This pack merged, it should be in GDevelop within 1hour in **Interface**.
Thank you (again)
