### ISSUE TITLE
Asset store submission (chasersgaming: Brawler Series)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#3882]
Trello card: https://trello.com/c/cRgi8cnw/75-chasersgaming-character-asset-packs
Package: [Brawler Series.zip](https://github.com/4ian/GDevelop/files/8651599/Brawler.Series.zip)

**Comment by Entr0py404** [comment]
I added the links to the card for opengameart to show licenses, I could not find the equivalent link for Soldier SMS

**Comment by Bouh** [comment]
> Brawler Series: https://itch.io/c/611394/sms-brawler-series https://itch.io/c/632311/nes-brawler-series
> 
> https://opengameart.org/content/brawler-asset-character-renegade-sms https://opengameart.org/content/brawler-asset-character-vigilante-sms https://opengameart.org/content/brawler-asset-character-ranger-sms https://opengameart.org/content/brawler-asset-character-soldier-nes https://chasersgaming.itch.io/brawler-asset-character-soldier-sms

Nice, thank you!
Opengameart.org is exactly what we need, they are clear, and the information is easy to find out. I think we should add these links or only the author profile in the license.txt file at the root.

In your case: https://opengameart.org/users/chasersgaming

> I added the links to the card for opengameart to show licenses, I could not find the equivalent link for Soldier SMS

[Isn't this one? 
](https://opengameart.org/content/brawler-asset-character-soldier-nes
)

**Comment by Entr0py404** [comment]
Yep that would be the correct one I will be more clear on the links next time around

**Comment by Bouh** [comment]
I made the changes to add links to the file.
We can add multiple links in license.txt file under the license (here CC0), the author profile, and author name.

It's now merged, thank you :+1:
