### ISSUE TITLE
Asset store submission (Hannemann: Virtual Joystick)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#3883]
Trello card: https://trello.com/c/6K2UVLHz/102-hannemann-virtual-joystick
Package: [Virtual Joystick.zip](https://github.com/4ian/GDevelop/files/8651652/Virtual.Joystick.zip)

**Comment by Bouh** [comment]
I added more tags, related to **mobile**, and **gamepad**.
Merged, should be in GDevelop within 1hour in **Interface > Virtual Joystick**.
Thank you ;)
