### ISSUE TITLE
Asset store submission (Darkvinter: Thumbstick)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#3884]
Trello card: https://trello.com/c/5Kg4Vtrp/96-darkvinter-thumbstick
Package: [Thumbstick.zip](https://github.com/4ian/GDevelop/files/8652532/Thumbstick.zip)

**Comment by Bouh** [comment]
I added the **mobile** tag.

This pack is merged, it should be in GDevelop within 1hour in Interface.
Thank you!
