### ISSUE TITLE
Two parameters without a name cause an error loop

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3888]
In the custom function configuration, adding two parameters without filling a name, and moving focus from one field to the other, triggers a warning loop. Pressing OK closes and reopens the window.
![image](https://user-images.githubusercontent.com/25978830/167717177-e7b458cb-a00f-4c23-b180-ea434e3ac692.png)

GD5.0.132 | Windows 10

[source](https://forum.gdevelop.io/t/function-parameter-locking/39657/2)

**Comment by Bouh** [comment]
I confirm the infinite loop.

**Comment by 4ian** [comment]
I've kind of fixed this by ensuring parameters have a proper name by default :)
