### ISSUE TITLE
"Locate file" in Resources gives error message

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3899]
## Describe the bug

![image](https://user-images.githubusercontent.com/8879811/168151078-3c4f4d36-880b-47e1-ae1d-7d59058d779d.png)

## To Reproduce

- Open Resources
- Click on 3 dots next to a resource
- Select "Locate File"
- Error message is displayed

## Other details

- Running GDevleop 5.0.133 (pre-release) on Windows 10

**Comment by AlexandreSi** [comment]
Works fine on Mac.
It looks like there is a problem with the `/` that should be `\` on Windows I think.
I don't have a Windows on which I can test a fix though. @ClementPasteau ?

**Comment by ClementPasteau** [comment]
I've managed to reproduce the issue on Windows.
It seems to only happen with the latest versions indeed, 132 is OK, 133-beta-2 isn't.
I went quickly through the commits to find a culprit, but not obvious one.
So we'll probably need to do a bisect.
