### ISSUE TITLE
New variable editor displays type select options white on white

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3927]
## Describe the bug
For a selected row, the select list of type is hard to read.
![image](https://user-images.githubusercontent.com/1670670/169288435-dc5b1239-0ce5-4f25-90e3-9d4b8af354da.png)

Only in White theme, Dark and Nord theme are ok.

## Other details
* 5.0.133, W10

**Comment by AlexandreSi** [comment]
I'm curious to see how it looks like with dark themes.
It looks like the text color set for selected row is also given to children on Windows.

**Comment by Bouh** [comment]
By themes in order:
![image](https://user-images.githubusercontent.com/1670670/169296542-33320465-8982-4ca4-9093-a0409a803be5.png)

**Comment by AlexandreSi** [comment]
Thanks!
