### ISSUE TITLE
Expression Builder - object variables not in drop-down list

### ISSUE THREAD

**Issue by convictedweirdo** [4ian/GDevelop#3932]
## Describe the bug

When using the expression builder, object variables do not show up on the drop-down list unless you open the object variable box first. 

## To Reproduce

use expression builder

go to object -> variables

select object - then on drop down, nothing shows up underneath.

Click on object variable dialog on right, and press close.

Drop down menu now populates.

![1](https://user-images.githubusercontent.com/25803863/169424462-c3f84c4b-a637-41f7-be6f-8916f5170f36.png)
![2](https://user-images.githubusercontent.com/25803863/169424470-e651d01e-f4d5-40c0-a456-91613222bbd2.png)
![3](https://user-images.githubusercontent.com/25803863/169424475-7bc7e664-c238-4a4b-8ade-c5344ee04d01.png)

## Other details
Windows 11 - 64bit
GDevelop 5.0.133 (was also happening on 5.0.132, not certain on earlier versions)

**Comment by jack-ii** [comment]
> GDevelop 5.0.133 (was also happening on 5.0.132, not certain on earlier versions)

I think already since b111, I reported it here on 20. Jan.
But since 133 the problem no longer exists for me. (win10)
