### ISSUE TITLE
Formatting wrong when editing properties of a behavior

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3935]
## Describe the bug

Using the extension editor, open a behavior and choose the "Properties" tab.  Everything is squished to the left half of usable area.

![Screenshot 2022-05-19 193407](https://user-images.githubusercontent.com/8879811/169539425-6a666e71-2224-4665-bb54-c3750c761b3a.png)

## Other details
* Windows 10
* GDevelop 5.0.133 (final)

**Comment by 4ian** [comment]
Yep, this went under the radar - fixed in 0502bd1f7acf79a05cd188ccf77a84943ebe1b37 :)
