### ISSUE TITLE
File manager no longer has focus

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3942]
With this new version of GD, when you click to add an image, when you open the file manager, it no longer has focus, making the user have to go look for the open dialog.

https://user-images.githubusercontent.com/23488207/169702637-59bed6cb-b8d7-42e8-b753-85191d00a67a.mp4

O.S: Arch Linux
GD: 5.0.133

**Comment by 4ian** [comment]
Surely yet another OS/window manager specific issue like what happened previously on Linux. Maybe the upgrade from Electron 18 to Electron 18.2 for next version will solve this!

**Comment by Bouh** [comment]
Note: 
This bug isn't on Windows 10, and GDevelop 5.0.134.

**Comment by AlexandreSi** [comment]
@willianholtz have you been able to test it on v134/135?

**Comment by willianholtz** [comment]
Hey @AlexandreSi , It started working normally again! I'll close with a comment!
