### ISSUE TITLE
Within 5.0.134 Can no longer click Save/Apply buttons in the Yarn editor 

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#3952]
## Describe the bug
Starting with 5.0.134 (And potentially .133) you can no longer save in the yarn editor.

Neither the Apply, nor the File > Save, nor the slide out menu save buttons will click anymore.

## To Reproduce
1. Create a new project, or open an existing one.
2. Add the action **Load a dialogue tree from a Json file**, or edit an existing one.
3. Click the **Create** button, or **Edit** if modifying an existing.
4. Make any change to the tree. 
5. Try to click **Apply** on the upper right. Or click the **>** and try to click Save. Or click the **File** menu then try to click **Save**. None are interactable, and Apply acts like you are clicking the tags button instead.

Reported by Carlosfruitcup on the forums, and they've included a video showing the issue: https://forum.gdevelop.io/t/cant-save-anything-in-yarn/39898

To confirm this wasn't with all bundled apps, tested the Piskel editor, it still saves normally.

## Other details
* WIndows 10 Pro 64 bit
* GDevelop 5 5.0.134

**Comment by ClementPasteau** [comment]
I've found that the issue comes from the bundled yarn build, which is probably relying on an electron version that is too old and thus not compatible.
I'm trying to change this from the yarn source code to rebuild a package for GDevelop.

**Comment by carlosfruitcup** [comment]
Just wanted to say that it does affect .133, I updated to 134 to see if the issue was fixed before sending the bug report
