### ISSUE TITLE
Apple Silicon (M1 Pro/Max/Ultra) native support?

### ISSUE THREAD

**Issue by CollinsVakayil** [4ian/GDevelop#3971]
Are there any immediate or future plans to have GDevelop support Apple Silicon natively without having to use Rosetta?

**Comment by 4ian** [comment]
Should be doable, we upgraded to Electron 18 recently so this might be a matter of checking if Electron builder can build a universal binary or something like this.

**Comment by arthuro555** [comment]
If we are going to add arm support, why limit ourselves to MacOS? Let's also make arm builds for other OSs to support devices like the Raspberry PI as well 👀

**Comment by CollinsVakayil** [comment]
> Should be doable, we upgraded to Electron 18 recently so this might be a matter of checking if Electron builder can build a universal binary or something like this.

Any idea regarding the timeline for Apple Silicon native support?

**Comment by 4ian** [comment]
Testing builds are available in https://github.com/4ian/GDevelop/pull/4031 :)
