### ISSUE TITLE
Multiple things 

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#3989]
This is a bug report and a list of thing to polish before the next update.

- [x] In Dark mode, Solarized and new GDevelop default Dark, when I move an event the revamped indicator have a bad contrast (@ClementPasteau fixed)
![image](https://user-images.githubusercontent.com/1670670/171935910-d8e99195-a668-47ab-8adb-449906887f80.png)
![image](https://user-images.githubusercontent.com/1670670/171936242-df69a4ca-f994-4545-94d2-1a5b4ce3cdb6.png)

- [x] With the new theme, panel have no more colors.
![image](https://user-images.githubusercontent.com/1670670/171936724-2decd137-f441-4e9f-a557-3abc03da7a40.png)

- [x] The bold font on the buttons bothers me, I feel like I'm squinting, it's nice, but I feel like it makes me more tired to read.
![image](https://user-images.githubusercontent.com/1670670/171937070-9ac72b40-476b-4b2a-86f1-7f86ce310f98.png)
![image](https://user-images.githubusercontent.com/1670670/171937082-943ec31f-5c14-462a-b865-1a561931be01.png)
![image](https://user-images.githubusercontent.com/1670670/171937095-2464e5a7-71c4-486e-9316-34b4e7d7f844.png)
![image](https://user-images.githubusercontent.com/1670670/171937124-c343f5f3-9d14-47e0-8735-d6c29eeb4550.png)

- [x]  Cancel is unuseable (@ClementPasteau fixed - cannot be canceled so removed button)
![image](https://user-images.githubusercontent.com/1670670/171937436-dcedb6b1-d8fc-4373-8752-778803ea3aab.png)

- [x] The cursor isn't consistent (@ClementPasteau fixed)
![image](https://user-images.githubusercontent.com/1670670/171938387-fe62f399-ddf8-4749-b708-b44b6a32121e.png)

- [x] Click on a tag, and you go to a list of all items with the tag, but this tag isn't in the search bar, or in filters. (@D8H fixed)
![tag](https://user-images.githubusercontent.com/1670670/171938809-41fe3c56-5f73-41e9-bef9-79a79aa958cd.gif)

- [x] I don't remember adding **Laser Shooter** and **Laser** in this **GDevelop Platformer** pack and after a check there is no sprite with this name in the folder. Maybe there is a problem in the asset store. (@D8H fixed)
![image](https://user-images.githubusercontent.com/1670670/171939186-34964eb2-6278-406b-b55f-8faa189c5c99.png)

Nothing more to said on the new DND, it works like a charm, CTRL+Z too, the new theme have nices new shapes :D 
And the Asset Store is just amazing!

**Comment by Bouh** [comment]
- [ ] Sharp corner 
![image](https://user-images.githubusercontent.com/1670670/171941346-90901040-742f-49b0-b878-fa9ddbd18747.png)
![image](https://user-images.githubusercontent.com/1670670/171941371-4a29cf7e-fc8f-4847-b028-bd8e89665202.png)

- [ ] Time to time on I got a the focus on the canvas. Focus which is visible by the orange border, this focus thing is purely a web-ish thing, and have no sense there.
![image](https://user-images.githubusercontent.com/1670670/171941615-f9b7a487-3c48-444c-b742-bca123837657.png)

**Comment by tristanbob** [comment]
- [ ] Can't drag an event "right" from outside a ForEach() event and into the ForEach()

https://user-images.githubusercontent.com/8879811/171982658-6a942b2d-ca9e-4e84-9fbe-1a391b8e99f1.mp4

**Comment by tristanbob** [comment]
- [ ] Cannot drag events "left" to the same level as parent Event Group (sometimes works though)

https://user-images.githubusercontent.com/8879811/171977917-bba9ae0e-0518-4475-aaad-23543d2d13a9.mp4

**Comment by ClementPasteau** [comment]
Regarding your 2 comments @tristanbob 

I believe it is slightly tricky to handle and create "drop zones" that match the behavior you're trying to achieve.
The feature works though, you just have to drop the event in the correct place.
I've highlighted the "drop zones" in my environment so you can see how to achieve this better.

- In order to drop inside a foreach that already has an event, your mouse has to hover at the beginning of the last even of that foreach loop.
https://user-images.githubusercontent.com/4895034/172145128-fceac38c-578c-4ef5-9568-e40ddbafdba6.mov

- In order to drop at the same level as an Event Group, you have to drop below the event group (as it contains other events, you technically cannot drop just below it, even if it is the only event)
https://user-images.githubusercontent.com/4895034/172145401-16ab04c8-438c-4d0d-a4d8-dd411bfccd87.mov

**Comment by 4ian** [comment]
On the remaining points for the theme:

- "With the new theme, panel have no more colors." => this is the same as the One Dark theme. I would keep them unless you have a better suggestion? 
- "The bold font on the buttons bothers me, I feel like I'm squinting, it's nice, but I feel like it makes me more tired to read."  => the rendering on Windows is not great it seems, I'll double check.
- "Time to time on I got a the focus on the canvas" => I can't reproduce even by calling `focus()` on HTML elements. I'll double check on Windows too.

**Comment by Bouh** [comment]
> * "With the new theme, panel have no more colors." => this is the same as the One Dark theme. I would keep them unless you have a better suggestion?

Ok go without color, not a big deal, just a new habit to get.

> * "The bold font on the buttons bothers me, I feel like I'm squinting, it's nice, but I feel like it makes me more tired to read."  => the rendering on Windows is not great it seems, I'll double check.

This may be because in dark mode, the bold white font may create a halo effect on the screen, which may disturb people & me.

> * "Time to time on I got a the focus on the canvas" => I can't reproduce even by calling `focus()` on HTML elements. I'll double check on Windows too.

This happened a lot of times when I go back and forth between two apps, and also by pressing tab in GD5.

**Comment by Bouh** [comment]
- [ ] **Function Configuration** panel is cropped
![image](https://user-images.githubusercontent.com/1670670/172477898-829edb99-8a8f-4eaa-90ec-fba66e91ea8e.png)

- [ ] I wonder if the arrow to expand the JSevent should be part of the event theme and not from the Monaco theme?
![image](https://user-images.githubusercontent.com/1670670/172478184-291b9a7d-5e7f-4664-b26a-07baf7765181.png)

**Comment by ClementPasteau** [comment]
The final points you've raised:
> Horizontal separators are smaller than the vertical ones and are harder to aim.
> Function Configuration panel is cropped
> arrow to expand the JSevent should be part of the event theme and not from the Monaco theme

are present on all themes, not just the latest one, so we'll probably fix them as separate issues

**Comment by 4ian** [comment]
Yep, I think we "hacked" a toggle but that should be built using something else than buttons.

**Comment by Bouh** [comment]
> "Time to time on I got a the focus on the canvas" => I can't reproduce even by calling focus() on HTML elements. I'll double check on Windows too.

See in this GIF where is enabled the focus.
![outline](https://user-images.githubusercontent.com/1670670/173012510-d4573011-0a4e-4d53-b89e-d4beefc6f50b.gif)

**Comment by tristanbob** [comment]
> * In order to drop at the same level as an Event Group, you have to drop below the event group (as it contains other events, you technically cannot drop just below it, even if it is the only event)

@ClementPasteau thanks for taking the time to explain this and provide videos.  I came back to this thread to vent my frustrations but I am able to accomplish my task.

Perhaps I am more affected by this because the old behavior was very intuitive for these types of changes.  ("Want to change indentation? Just drag left or right!").  If we ever come back to this feature, I'd love to get some of that back.

**Comment by tristanbob** [comment]
- [ ] In the extension editor, the "Condition" field is a static size, instead of being proportional (like the main event sheet).

https://user-images.githubusercontent.com/8879811/173199988-a7854a44-d686-4f48-93e3-01dad46b45a0.mp4

**Comment by Bouh** [comment]
> * [ ]   In yes/no toggles, there is an inconsistency on the outline of buttons:
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/81410437/172856741-07755910-18e1-4dad-a2c6-737617535a5e.png">
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/81410437/172856793-042a3167-8ea9-4031-b0c2-9756700b5ef3.png">

My 2 ct for better toggles:

![image](https://user-images.githubusercontent.com/1670670/173240603-c54c204e-48c9-464e-8dad-87ef5b9f0ca0.png)
