### ISSUE TITLE
Add new expressions: CameraLeft(), CameraRight(), CameraTop(), CameraBottom()

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3990]
## Description

The new `Object.BoundingBoxTop()` family of expressions has been very useful and saved me a lot of time.

The borders of cameras would provide a similar benefit.  These would allow users to replace this:

`CameraX("Layer", Camera) - CameraWidth("Layer", Camera)/2`

with this:

`CameraLeft("Layer", Camera)
`
## Solution suggested

Add new expressions for each side of the camera:

- [ ] `CameraTop("Layer", Camera)`
- [ ] `CameraBottom("Layer", Camera)`
- [ ] `CameraLeft("Layer", Camera)`
- [ ] `CameraRight("Layer", Camera)`

**Comment by 4ian** [comment]
Agree, let's add this, if someone wants to take this task!

**Comment by tristanbob** [comment]
@4ian Do you think `CameraCenterX()` and `CameraCenterY()` expressions should be added to this list?  

This would match the bounding box expressions and be more self-descriptive (even though it is the same thing as `CameraX()`)

**Comment by 4ian** [comment]
Maybe that's an idea, and we would hide the "old" CameraX/CameraY then to avoid confusion? 🤔

**Comment by tristanbob** [comment]
Yes let's do this.  Users Probably think It means too left corner like sprites.

**Comment by Elairyx7301** [comment]
I haven't quite figured out if "camera viewport" and the "camera 'frame'" you're talking about here are the same thing but I found these unimplemented expressions (and actions) in [/GDJS/GDJS/Extensions/Builtin/CameraExtension.cpp](https://github.com/4ian/GDevelop/blob/master/GDJS/GDJS/Extensions/Builtin/CameraExtension.cpp#L182-L219). If it is the same and I read that right, this is almost already what the suggested expressions should do.

```cpp
// X value of TopLeft
AddExpression("CameraViewportLeft", _("X position of the top left side
	point of a render zone"), _("X position of the top left side point
	of a render zone"), _("Camera"), "res/actions/camera.png")
		.AddCodeOnlyParameter("currentScene", "")
		.AddParameter("layer", _("Layer"))
		.AddParameter("expression", _("Camera number (default :0)"))
		.SetDefaultValue("0")
		.SetFunctionName("GetCameraViewportLeft");

// Y value of TopLeft
AddExpression("CameraViewportTop", _("Y position of the top left side
     point of a render zone"), _("Y position of the top left side point of a
     render zone"), _("Camera"), "res/actions/camera.png")
          .AddCodeOnlyParameter("currentScene", "")
          .AddParameter("layer", _("Layer"))
          .AddParameter("expression", _("Camera number (default :0)"))
          .SetDefaultValue("0")
          .SetFunctionName("GetCameraViewportTop");


// X value of BottomRight
AddExpression("CameraViewportRight", _("X position of the bottom right
     side point of a render zone"), _("X position of the bottom right side point
     of a render zone"), _("Camera"), "res/actions/camera.png")
          .AddCodeOnlyParameter("currentScene", "")
          .AddParameter("layer", _("Layer"))
          .AddParameter("expression", _("Camera number (default :0)"))
          .SetDefaultValue("0")
          .SetFunctionName("GetCameraViewportRight");

// Y value of BottomRight
AddExpression("CameraViewportBottom", _("Y position of the bottom right
     side point of a render zone"), _("Y position of the bottom right side point
     of a render zone"), _("Camera"), "res/actions/camera.png")
          .AddCodeOnlyParameter("currentScene", "")
          .AddParameter("layer", _("Layer"))
          .AddParameter("expression", _("Camera number (default :0)"))
          .SetDefaultValue("0")
          .SetFunctionName("GetCameraViewportBottom");
```

**Comment by 4ian** [comment]
The viewport was an old thing that was never implemented and that allowed camera to be displayed only on one part of the window (called the "render frame" or the "viewport"). 
If we add this again, it would rather be thanks to something called "Render to sprite" that would allow to render a camera on a sprite object or a "camera displayer" object.

So the CameraLeft/Right/Bottom/Top are still different and useful to have :)
