### ISSUE TITLE
Leaderboard: Tie scores are sorted differently based on "Only show players best score"

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4019]
## Description

Leaderboard: Tie scores are sorted differently based on "Only show players best score"

https://user-images.githubusercontent.com/8879811/173155244-d7fa9180-973e-48f7-bc55-63c5f3cec0f1.mp4

## Solution suggested

- [ ] Sort the leaderboard the same way regardless if "Only show players best score" is enabled or not

(this is a very minor detail, but it made me wonder why order of player names changed when toggling the checkbox)

**Comment by AlexandreSi** [comment]
I knew this issue would popup at one point!
This may seem counter intuitive but adding this stability would require quite some work and the gain is not that high.

**Comment by tristanbob** [comment]
@AlexandreSi thanks for considering this.  I agree that the benefit is very small, I was expecting the fix to be fast and easy.  Since it is not, I am closing this request.  Thanks!  :)
