### ISSUE TITLE
Clicking empty space > check box

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#4024]
![pop](https://user-images.githubusercontent.com/81715237/173236523-211fc669-9403-4c6f-a751-7b549db61f4f.gif)
Clicking in the empty spaces will always check the boxes near the clicks in the behavior options.

## To Reproduce
1. Open any behavior that have check box options in it (in my GIF its Particles object).
2. Click on the empty space beside the box.
3. The box will get check and uncheck while you are clicking in the empty place.

## Other details
* GDevelop offline version (Desktop).
* Latest GDevelop official version.
* Even if this is not a bug (built on purpose), it still feels wrong to check the box while you are clicking on empty places.

**Comment by Bouh** [comment]
It is all the more confusing that there is no hover on the input labels which does not show us that the empty area is linked to an input.
