### ISSUE TITLE
Large Tilemaps cut off Horizontally

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#4039]
## Describe the bug
When a tilemap is past a certain size, the map image will cut off horizontally both in the IDE and in previews. The map dimensions still render correctly in the IDE. This was reported by Discord member (78), and I was able to reproduce it.

## To Reproduce
1. Create a tilemap in Tiled (or in LDTK and export to tiled)
2. Ensure the map has at least one axis around ~8000 pixels large and another axis around ~5000 pixels large.
3. Export as JSON
4. Import as Tilemap object, add to scene.
5. The map will graphically be cut off (horizontally). This will be horizontal regardless of whether the map is larger vertically or horizontally. I'm assuming this is likely just due to how the json data orders data, but it still feels odd.

Attached is a project with both a horizontal and vertical map experiencing this issue.
[TileMapCutoff.zip](https://github.com/4ian/GDevelop/files/8915432/TileMapCutoff.zip)

Some examples:
Veritcal map in Tiled:
![image](https://user-images.githubusercontent.com/24237149/173985486-5a7a284b-4b71-4520-a9a0-5f23597650a6.png)

Vertical map in Editor (and preview):
![image](https://user-images.githubusercontent.com/24237149/173985523-14babc4a-0dbd-48cb-bd96-a000b6828a9e.png)

Horizontal Map in Tiled:
![image](https://user-images.githubusercontent.com/24237149/173985601-473ae313-0480-4391-a72a-3a344893791b.png)

Horizontal map in Editor (and preview): 
![image](https://user-images.githubusercontent.com/24237149/173985628-fb79664a-34c8-4268-9339-8eee5ea1c7c5.png)

Workaround:
You can split any map into ~4000x4000 smaller maps and create multiple tilemap objects, and it'll work fine. Based on how tilemaps work, this really shouldn't be required (Or should, I guess, be automated by the engine to split a larger map into smaller consumable maps).

## Other details
* Windows 10 Pro 64 bit
* Tested with both 5.0.135 and 136

**Comment by willianholtz** [comment]
normal for me..
![Screenshot_20220616_210628](https://user-images.githubusercontent.com/23488207/174197304-68b5bed0-db1f-4a61-936f-0ae3986386ad.png)

Linux: Arch

**Comment by Silver-Streak** [comment]
> Unfortunately I couldn't open your project, it says it's not a valid GD5 file.
> 
> I'd like to be able to test on Linux too, so I did my test and it works.

Hmmm.. I've now done a quick test on a linux mint bood disc with the project, downloaded from this github issue, and it opens fine. Still shows the same problem.
Were you opening game.json or one of the tilemap jsons?

**Comment by willianholtz** [comment]
> > Unfortunately I couldn't open your project, it says it's not a valid GD5 file.
> > I'd like to be able to test on Linux too, so I did my test and it works.
> 
> Hmmm.. I've now done a quick test on a linux mint boot disc with the loading the project, downloaded from this github issue, and it opens fine. Still shows the same problem. Were you opening game.json or one of the tilemap jsons?
> 
> What version of GD5?

I managed to open it, for some reason I had more than 10 gdevelop open and maybe that's why I couldn't load. Now with the tests in hand, yes, the same problem happens with your project.

**Comment by Silver-Streak** [comment]
> HUmm ~8000 pixels isn't within reason. 2048px is the maximum correctly supported by PixiJS (the rendering engine). I'm not sure this issue is a real concern. Split the sprite is the best workaround for now, and it will help to optimize your game.

Unless something has changed, tilemap objects aren't rendering a 2048px image (or shouldn't be). It is rendering dozens of smaller tiles.  It was also implemented partially to help avoid the image limit.

Also, this appears to be horizontal only, I can go thousands of pixels wide without issue, so I don't think it'd be related to the PixiJS/Electron image limit.

**Comment by Silver-Streak** [comment]
I've done more testing, it seems like this occurs if the rendered map size exceeds about 4million pixels total (even though the rendered map should actually be made up of smaller units) 

Looking at the issue I linked above, I'm wondering if somehow the maximum textures is set to 1 for this implementation, and the buffer is set too large?

@blurymind Does this ring any bells?

**Comment by D8H** [comment]
Actually the limit seems to be 2^14 tiles. I tried with 64x64 tiles and the limit is the same as for 16x16 tiles.

The good new is that big tiles can be used without reaching the limit too fast.

This is very probably a limitation from PIXI or its tile map extension.

**Comment by Silver-Streak** [comment]
> This is very probably a limitation from PIXI or its tile map extension.

This doesn't seem to match up with what I'm finding. There are numerous threads from Pixi V5 with 500k tiles or more using pixi-tilemap: 
https://www.html5gamedevs.com/topic/42741-fast-pixi-tilemap-renderer-trying-to-fix/

**Comment by Silver-Streak** [comment]
From what I can see, it looks like the compositing function may not be working correctly?

https://github.com/pixijs/tilemap/blob/master/src/CompositeTilemap.ts
Line 304 on

```
            // If no tileset contains the base-texture, attempt to add it.
            if (!tilemap)
            {
                // Probe the tilemaps to find one below capacity. If so, add the texture into that tilemap.
                for (let i = children.length - 1; i >= 0; i--)
                {
                    const child = children[i] as Tilemap;

                    if (child.getTileset().length < this.texturesPerTilemap)
                    {
                        tilemap = child;
                        child.getTileset().push(tileTexture.baseTexture);
                        break;
                    }
                }

                // Otherwise, create a new tilemap initialized with that tile texture.
                if (!tilemap)
                {
                    tilemap = new Tilemap(tileTexture.baseTexture);
                    tilemap.compositeParent = true;
                    tilemap.offsetX = settings.TEXTILE_DIMEN;
                    tilemap.offsetY = settings.TEXTILE_DIMEN;

                    this.addChild(tilemap);
                }
            }

```
