### ISSUE TITLE
Panel sprite Blur bug

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#4043]
## Describe the bug
Panel sprite is always blurring
In this simple project, you can see, using the same asset for 2 objects with the same size
• on Panel sprite:
![Blur](https://user-images.githubusercontent.com/81715237/174131514-96908e1d-eb35-4e05-8809-999fa15a7ca7.JPG)
• on Tiled sprite:
![Clean](https://user-images.githubusercontent.com/81715237/174131589-7f37166a-aca8-4e22-a1f9-40679da9443e.JPG)

as you can see, panel sprite is blurring, even though the project settings is set to (nearest)
and the resources do not have smooth checked. 
resolution doesn't matter the panel is always blurring, but in this project i used 640x360 (I also tried 800x600 and its still the same)
to better see this bug, use Lerp camera X at low speed and you will see the issue clearer, the slower the Lerp the cleanest you see the bug (I used 0.03 speed).

## Project file
[Project.zip](https://github.com/4ian/GDevelop/files/8921148/Project.zip)

## Other details
* Windows 10 / GDevelop offline version
* Latest GDevelop version
* The bug is reported 2 years ago #1774 , but the submitter didn't give much details, and from what I see in that topic, Devs thought this issue is from wrong settings, while its actually a blurring bug that cannot be fixed from the user side (no workaround found).

[Source](https://forum.gdevelop.io/t/panel-sprites-9-patch-anti-aliasing-issue/39661)

**Comment by Bouh** [comment]
Hi with the project I can't reproduce the issue.
Everything works well:
![image](https://user-images.githubusercontent.com/1670670/176460458-a53f9d2a-7ea7-4475-ac2c-d54e7864b00f.png)

**Comment by VegeTato** [comment]
> Hi with the project did you tried to enable the round pixel option? Like: ![image](https://user-images.githubusercontent.com/1670670/176460915-a5248b13-e23a-48a6-bca6-94f125aec2d8.png)
> 
> But I admit that if it works for the sprite, it should work for the other object too.

WOW
after checking the option (round pixels) it works perfect now...
(without the option the blur is always there)
I don't understand, what exactly is round pixels for ? and why its not ON by default when you pick (nearest no anti analyzing)
should i turn this option ON for all my pixel perfect games ? (even though must of my games have 0 blur because i use tile sprite object and round pixels option is off)
what are the cases i should turn this option ON and when to turn it OFF ?

Thank you <3

**Comment by VegeTato** [comment]
> > > Hi with the project did you tried to enable the round pixel option? Like: ![image](https://user-images.githubusercontent.com/1670670/176460915-a5248b13-e23a-48a6-bca6-94f125aec2d8.png)
> > > But I admit that if it works for the sprite, it should work for the other object too.
> > 
> > 
> > WOW after checking the option (round pixels) it works perfect now... (without the option the blur is always there) I don't understand, what exactly is round pixels for ? and why its not ON by default when you pick (nearest no anti analyzing) should i turn this option ON for all my pixel perfect games ? (even though must of my games have 0 blur because i use tile sprite object and round pixels option is off) what are the cases i should turn this option ON and when to turn it OFF ? and why while the option is OFF, tile sprite works perfect while the panel sprite is blurring ?
> > Thank you <3
> 
> Round Pixels was a feature added from a bounty of mine a while back. (#2504)
> 
> My understanding is that it is not on by default because it rounds _everything_. Positions, camera movement, hitboxes, etc. Some people don't like the setting because it impacts very low resolution games, especially with camera movement (since positions are always rounded, very low resolutions can look "stuttery" as it accurately reproduces old NES/SNES style games, e.g. no floating positions for the camera).

oh, but what if i want to use No rounding pixels(Off) and in the same time i want to use panel sprite without blurring just like the tile sprite object 🤷
doesn't that sounds like a bug ? that the panel sprite object does blur while the tile sprite object doesn't while rounding pixels option is off (just like the project I sent)

**Comment by Silver-Streak** [comment]
> I haven't looked into tile sprites, but maybe there is an automatic rounding somewhere that should not happen to be consistent?

As far as I know, PixiJS has had an issue related to rounding positions and Tiled Sprites for a few years now. Sometimes it leads to blurring, sometimes it leads to weird lines appearing: https://github.com/pixijs/pixijs/issues/7166
