### ISSUE TITLE
Google Drive not opens

### ISSUE THREAD

**Issue by GoodFaut** [4ian/GDevelop#4050]
## Describe the bug
Google drive dont loads the saved game

## Other details
Linux Debian (webapp)
webapp

**Comment by AlexandreSi** [comment]
Hi @GoodFaut 

Can you provide more details about how it happened:
Did you manage to save your game?
Can you see it on Google Drive?
If you are familiar with your browser's developer tools, can you provide the output of the console at the moment you try to open your game?
