### ISSUE TITLE
[$30.00 bounty] Allow shape painter objects to use anti-aliasing

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4055]
## Description

Drawing circles (and other curved shapes) with shape painters results in jagged lines.  This is true even with the default setting of anti-aliasing enabled for GDevelop projects.

## Solution suggested

Pixi does support anti-aliasing and the circles look much better with it turned on.

Pixi with anti-aliasing = FALSE
https://codepen.io/tristanbob/pen/VwQOrLP

Pixi with anti-aliasing = TRUE
https://codepen.io/tristanbob/pen/GRQaOJM

- [ ] GDevelop should offer the option to enable antialiasing on shape painter objects
 (and enabled by default, unless there are significant downsides)

**Comment by jposeyjr** [comment]
// Disable anti-aliasing(default) to avoid rendering issue (1px width line of extra pixels) when rendering pixel perfect tiled sprites.
@4ian Would you want a warning to pop up for this or is simply changing the props enough?

**Comment by Midhil457** [comment]
I would like to dabble into this. But first I have some doubt
After browsing thorugh the code a bit, I found that the setting in the project properties changes the rendering setting for the textures and the renderer's antialiesing option is always set to false (My understanding might be completely wrong). Is there a reason for this?  

After testing I did find that that the shape painter is being antialiesed, but not very well.

My idea is to completely use the renderer for antialiesing. I am worried if it might break some settings.

:)

**Comment by jposeyjr** [comment]
Yeah but they want it enabled and currently no way to do that. Adding it to the settings is just tedious due to how the client is formed. You have to find a good place to pass it down.

**Comment by Midhil457** [comment]
> Yeah but they want it enabled and currently no way to do that. Adding it to the settings is just tedious due to how the client is formed. You have to find a good place to pass it down.

I didn't understand. Could you clarify?

**Comment by Midhil457** [comment]
Hello? Is it ok if I go forward with my plan?

**Comment by Oxey405** [comment]
Hey ! I worked a bit on that issue and I implemented something that looks I'd say prommessing !
Sending a PR today :)

**Comment by D8H** [comment]
Antialiasing can be heavy. I guess, the `cacheAsBitmap` mode will be interesting to allow to render high quality still image and keep good efficiency.
https://pixijs.download/dev/docs/PIXI.Graphics.html#cacheAsBitmap

**Comment by Oxey405** [comment]
@D8H I'vhe worked on it can you maybe look at it later ?

**Comment by D8H** [comment]
> @D8H I'vhe worked on it can you maybe look at it later ?

I'm not sure what you mean. Do you want that I do a review?

**Comment by Oxey405** [comment]
> > @D8H I'vhe worked on it can you maybe look at it later ?
> 
> I'm not sure what you mean. Do you want that I do a review?

Yes you guessed it :)

**Comment by Oxey405** [comment]
@ClementPasteau so my PR closes this issue and thanks for the merge :)

**Comment by ClementPasteau** [comment]
Fixed in #4509

**Comment by Oxey405** [comment]
@rysolv-bot scan this please
