### ISSUE TITLE
Physics 2.0 collision bug from update 137 isn't properly fixed

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#4108]
Gdevelop is on update 138 and the bug from 137 remains or is slightly fixed.
From testing it appears after some time.
This bug in this game also didn't exist before the 137 update.

https://user-images.githubusercontent.com/98941240/179374960-ee47b8bf-ed37-49b2-8dbf-c28ec805781d.mp4

**Comment by willianholtz** [comment]
I believe version 139 fixes this! You could test the Nighyly version to see if the issue is resolved!

Look Here: [#4060](https://github.com/4ian/GDevelop/issues/4060#issuecomment-1176379585)

**Comment by ZachjuKamashi** [comment]
> I believe version 139 fixes this! You could test the Nightly version to see if the issue is resolved!
> 
> Look Here: [#4060](https://github.com/4ian/GDevelop/issues/4060#issuecomment-1176379585)

I took a look at it and it's different from my report slightly. I am not using any actions that change the objects size for physics 2.0 instead it's set in the object properties. And for me this bug is non existent for a little while and then just breaks all of the sudden from nowhere as shown in the video. Now I wish I could test the nightly version but the linux build isn't an appimage and seems to be not compiled, I don't have a clue on how to compile Gdevelop. So unfortunetly I don't know whether this is another separate issue or whether it's already been fixed.

**Comment by fannieyan** [comment]
Hello there!

Thank you for reporting this! :)
Could you provide us a project reproducing the issue? (Either a small new one or the one you are working on which you can send here or privately) I will run it with the latest version to see if it does fix the issue.

**Comment by willianholtz** [comment]
> > I believe version 139 fixes this! You could test the Nightly version to see if the issue is resolved!
> > Look Here: [#4060](https://github.com/4ian/GDevelop/issues/4060#issuecomment-1176379585)
> 
> I took a look at it and it's different from my report slightly. I am not using any actions that change the objects size for physics 2.0 instead it's set in the object properties. And for me this bug is non existent for a little while and then just breaks all of the sudden from nowhere as shown in the video. Now I wish I could test the nightly version but the linux build isn't an appimage and seems to be not compiled, I don't have a clue on how to compile Gdevelop. So unfortunetly I don't know whether this is another separate issue or whether it's already been fixed.


I believe that soon we will have the new build, but if you still want to test before releasing, get it here
[Linux](https://gdevelop-releases.s3.amazonaws.com/master/commit/7af0153ceb60689fa44b8831593c804b9ea6dbb8/GDevelop%205-5.0.138.AppImage)

**Comment by willianholtz** [comment]
> > I believe version 139 fixes this! You could test the Nightly version to see if the issue is resolved!
> > Look Here: [#4060](https://github.com/4ian/GDevelop/issues/4060#issuecomment-1176379585)
> 
> I took a look at it and it's different from my report slightly. I am not using any actions that change the objects size for physics 2.0 instead it's set in the object properties. And for me this bug is non existent for a little while and then just breaks all of the sudden from nowhere as shown in the video. Now I wish I could test the nightly version but the linux build isn't an appimage and seems to be not compiled, I don't have a clue on how to compile Gdevelop. So unfortunetly I don't know whether this is another separate issue or whether it's already been fixed.
I believe that soon we will have the new build, but if you still want to test before releasing, get it here

[Windows ](https://gdevelop-releases.s3.amazonaws.com/master/commit/55cc75e990ea7c3ffa646d5af34b82fb4c7cd365/GDevelop%205%20Setup%205.0.138.exe)

**Comment by ZachjuKamashi** [comment]
> > > I believe version 139 fixes this! You could test the Nightly version to see if the issue is resolved!
> > > Look Here: [#4060](https://github.com/4ian/GDevelop/issues/4060#issuecomment-1176379585)
> > 
> > 
> > I took a look at it and it's different from my report slightly. I am not using any actions that change the objects size for physics 2.0 instead it's set in the object properties. And for me this bug is non existent for a little while and then just breaks all of the sudden from nowhere as shown in the video. Now I wish I could test the nightly version but the linux build isn't an appimage and seems to be not compiled, I don't have a clue on how to compile Gdevelop. So unfortunetly I don't know whether this is another separate issue or whether it's already been fixed.
> 
> I believe that soon we will have the new build, but if you still want to test before releasing, get it here [Linux](https://gdevelop-releases.s3.amazonaws.com/master/commit/7af0153ceb60689fa44b8831593c804b9ea6dbb8/GDevelop%205-5.0.138.AppImage)

Looks like in the new build this bug is nonexistent so apparently it was the same bug even though for me it happened quite differently compared to the other report that I looked at

**Comment by Silver-Streak** [comment]
Thanks for reporting it solved.
