### ISSUE TITLE
Renaming scenes/external events creates duplicate files in the project directory

### ISSUE THREAD

**Issue by ghost** [4ian/GDevelop#4120]
## Describe the bug
When a project uses the 'multiple files' setting, and you rename a scene or external event from the UI, a new file is created in the project directory (as expected), but the old one remains too. This causes duplicates and confusion.

## To Reproduce
1. Create a new, blank project and set the 'Project file type' setting/property to 'Multiple files'
2. Create a scene and an external event (leave them with the default names
3. Save and verify the correct files are in the project directory
4. Rename the scene and external event
5. Save and check the project directory - note the old files are there along with the new ones

![image](https://user-images.githubusercontent.com/2385329/179917230-f5059eea-4566-4b06-8ade-1171a63ee929.png)

![image](https://user-images.githubusercontent.com/2385329/179917281-bbca53d5-36dc-48c8-80ac-cc3bdac99374.png)

![image](https://user-images.githubusercontent.com/2385329/179917595-879355d3-b176-4cab-aa69-5dfa0cb97fe8.png)

![image](https://user-images.githubusercontent.com/2385329/179917676-8eed4085-2096-4e41-9e21-4f4d56d86bdb.png)

## Other details
GDevelop v5.0.138 running on Manjaro Linux (KDE Plasma v5.24.6)

**Comment by willianholtz** [comment]
I noticed this a while ago too! I was going to report this, but I forgot! Now that you've commented, I can confirm that it happens to me too. I've noticed this since several builds ago! 

OS. Arch Linux 
GDevelop v5.0.139

**Comment by 4ian** [comment]
You can try but this will involve removing files which is risky - you'll need a strong and robust solution here :)
