### ISSUE TITLE
Physics 2 Behavior full crash in 5.0.139 when switching scenes with lots of objects with physics 2 behavior

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#4144]
## Describe the bug
There appears to be a bug somewhere in the Physics 2 Behavior that results in a full simulation crash with unending loop of box2d uncaught abort errors being thrown in the console log.
[phys2crash.txt](https://github.com/4ian/GDevelop/files/9184163/phys2crash.txt)
The two errors in that log repeat non-stop.

## To Reproduce
[issue-4144-min.zip](https://github.com/4ian/GDevelop/files/9184854/issue-4144-min.zip)
This issue appears to be a combination of:
- Having a lot of physics objects loaded from an external layout
- Loading and unloading a scene with lots of physics objects
If you load my example above and click the reload button a few times it will all come down.

Notes:
If you look at my external layout you will see a big boxed in section of objects.
That was the original size I tried to repro with.... it was not enough.
I added a lot more objects outside of that box in order to reproduce.
The "BlipScene" is not necessary to reproduce the issue, but it makes it happen faster (you can change it to just reload the main scene instead)
Wild guess: destroying an existing scene with lots of physics objects on it makes box2d angry... maybe reset the state of box2d if scene is changing and paused scenes are being destroyed?

## Other details
* Windows
* 5.0.139 Desktop

**Comment by tristanbob** [comment]
Do you happen to adjust the size of the physics objects?  When I was tweening object scale it caused occasional crashes in Box2d.  For me, the solution was to disable physics Behavior while tweening.

**Comment by krunkster** [comment]
It does seem to happen near a position tween of a physics object, but I believe the physics behavior is disabled while I'm tweening already... I'll double check though.

**Comment by 4ian** [comment]
If tweening is involved, maybe we reach something like a size of 0 and get a bug because of this.

**Comment by krunkster** [comment]
OK, managed to isolate the problem pretty well (If I do say so myself)
I updated the main description with repro zip.

**Comment by krunkster** [comment]
Ugh... I just had another box2d crash not related to loading scenes....  I'll capture a separate ticket later if I can repro again... it was after playing my game for like 20 minutes.  I honestly feel like the Physics behavior hasn't been stable since 5.0.130 :(

**Comment by krunkster** [comment]
Is there an un-baked version of the version of box2d.js that you are using? I'm trying to debug and it's kinda tough.
```
  gdjs.registerRuntimeSceneUnloadedCallback(function (runtimeScene) {
    if (
      // @ts-ignore
      runtimeScene.physics2SharedData &&
      // @ts-ignore
      runtimeScene.physics2SharedData.world
    ) {
      // @ts-ignore
      Box2D.destroy(runtimeScene.physics2SharedData.world);
    }
```
That Box2D.destroy() method is really what I want to know more about... That method doesn't seem to exist on the internet... Box2d javascript API docs are so hard to find, but in all the ones I have found, that method doesn't exist.

**Comment by krunkster** [comment]
I just used a simply beautifier on box2d.js and was able to step through it better.  I found the following error message was being generated but not logged:
> Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
Which leads me further to believe there is some memory or state in box2d that is not being freed when a scene is unloaded.

**Comment by 4ian** [comment]
Correct, this seems also the conclusion of @D8H when investigating this. We believe this is a limitation of the version of Box2D we're using (compiled without support for enlarging the memory) and we're looking at the WebAssembly version of the library, which seems to behave better.

FYI we're using version 2.3.1 of Box2d.js:
https://media.discordapp.net/attachments/940238129946845184/1001437348363522138/unknown.png

**Comment by krunkster** [comment]
OK, cool.

I found some potentially related articles, but I haven't completely grok'd them yet:
https://github.com/kripken/box2d.js/issues/27
https://github.com/Birch-san/box2d-wasm/issues/9

I forgot to mention earlier, but I definitely think I found a bug already (not that solves this issue) but the "gdjs.callbacksRuntimeSceneUnloaded" in RuntimeScene::unloadScene() does not seem to be called for paused scenes, which I think is why my reproduction example happens faster using the BlipScene that first pauses the scene before switching to a new scene. In this situation the registered unload callback only happens on the current scene (which has no phyics shared data to destroy) and is NOT called on the pause scene that shared data and lots of physics objects in it.

**Comment by 4ian** [comment]
> I forgot to mention earlier, but I definitely think I found a bug already (not that solves this issue) but the "gdjs.callbacksRuntimeSceneUnloaded" in RuntimeScene::unloadScene() does not seem to be called for paused scenes, which I think is why my reproduction example happens faster using the BlipScene that first pauses the scene before switching to a new scene. In this situation the registered unload callback only happens on the current scene (which has no phyics shared data to destroy) and is NOT called on the pause scene that shared data and lots of physics objects in it.

This is definitely an issue and can explain why the crash would happen quicker.

Note that the issue with Box2d.js is not necessarily a **memory leak**, but the fact that the asm.js version of this library is not able to grow its heap memory. So when it tries to uses more than 16MB that are hardcoded => it crashes. 
In these kind of game oriented library, it's usual to use a custom allocator in C++ that allocate memory but never deallocate it - it just recycle/reuse it. So you might have an impression of ever growing memory, but it's just that it's always  alloacting the maximum, and if you destroy everything, it mark the memory as free in its internal allocator but the heap memory is still allocated from the system point of view. (see https://github.com/Birch-san/box2d-wasm/issues/9#issuecomment-753330525)

This does not change the issue that the current version has an issue of not being able to grow the memory, and potentially a leak on our side with paused scenes (which IS a memory leak if that's true).

**Comment by krunkster** [comment]
I see the box2d wasm updates pending, so that's awesome.

On the callbacks not working... it's pretty easy to verify by setting a break point in the register unload callback code in physics2behavior.  Doing that with my repro will only ever show the callback for the "BlipScene" not the "PhysicsScene".

I also tried to create a Mocha test to verify it's not just an issue with the debugger not hitting the breakpoint:
[scenestack.diff.txt](https://github.com/4ian/GDevelop/files/9214614/scenestack.diff.txt)
The test I added there only passes in isolation, if run immediately after the first test, there are some funky side effects:
The PausedCallback is called on the second and third scene when they are pushed to the stack (lines 208, 215)
The UnloadedCallback appears to be called twice for scene 2 when scene 4 replaces and clears the stack (line 239)
I added a before each that deleted the runtimeGame object and reset it, and then the tests pass sequentially. So for sure the first (original) test is leaving the runtimeGame registered callbacks in funky state.

Hopefully, I'm not sending anyone here on a wild goose chase, but I wanted to share what I've found since I'm going to be unavailable for a few days.
Thanks again for everyone's hard work on this!

**Comment by D8H** [comment]
Indeed, a `beforeEach` is better to let people add tests more easily. We're always happy to extend our test coverage. Feel free to create a PR with test cases if you want to.

**Comment by tristanbob** [comment]
I found this 5-year old benchmark interesting:

http://olegkikin.com/js-physics-engines-benchmark/
```
All of the engines are single-threaded, some don't even max out one core
All of the engines are CPU-only, no GPU (WebGL/WebCL) option
Emscripten-compiled engines die after a certain number of boxes with something like Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value ..., even when there's lots of free RAM.
WASM seems to help. In case of Box2D it allows for ~500 more boxes at the same tick rate
```
