### ISSUE TITLE
Replacing an empty search field hangs GDevelop

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4149]
A forum user [reports](https://forum.gdevelop.io/t/search-replace-problem/41075) the following issue, that I confirmed on my side.

Reproduction steps:
Open any project,
Go to any events sheet,
Press Ctrl+f to open the search, 
Press Tab to access the Replace field,
Type anything,
Hit Return.

GDevelop 5.0.139 hangs indefinitely.

**Comment by AlexandreSi** [comment]
Thanks for reporting it!
As usual, really clear and straight forward, all the ingredients for a quick fix!
