### ISSUE TITLE
Remove unused JSON removes used JSON files

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4163]
A forum user [reports this issue](https://forum.gdevelop.io/t/remove-unused-deletes-dialogue-json/41154) and I confirmed it on my end.

Steps to reproduce the issue:
In an events sheet, add an action to load a dialogue file, 
Create a file with Yarn,
Close Yarn,
Go to Resources,
Locate the JSON file at the bottom of the list,
Right-click and select Remove unused JSON.
The JSON file has been removed from the list.

![image](https://user-images.githubusercontent.com/25978830/182050110-10d39f30-2716-4b4a-802c-86650eb11e6e.png)

**Comment by AlexandreSi** [comment]
Thanks for taking the time to report this bug!
