### ISSUE TITLE
Incorrectly building for web

### ISSUE THREAD

**Issue by RayanMadan** [4ian/GDevelop#4185]
## Describe the bug
sometimes while building in the same folder, the game json is appended to instead of replaced(i am guessing since the build size nearly doubles; refer attached zip file)

## To Reproduce
1) Export to HTML
2) Do another Export to HTML in same location
3) The game JSON file doubles in size (it appends the text)
4) The result of this is that the new changes are not reflected once the game is played

Note: it is highly inconsistent, after doing these steps several times, i got this issue twice

-I have attached a copy of the bugged build for reference.

## Other details
* One windows platform
* gdevelop5, application

* 
[Astroguard.zip](https://github.com/4ian/GDevelop/files/9271507/Astroguard.zip)

**Comment by RayanMadan** [comment]
[Astroguard.zip](https://github.com/4ian/GDevelop/files/9271546/Astroguard.zip)


attached is the working build

**Comment by 4ian** [comment]
This is not a bug, you've built once for HTML5 (which put the game in the folder directly) and once for desktop (which puts your game in a subfolder called "app").
GDevelop does not clear the directory before exporting to avoid you losing data.

Make sure to export for HTML5 in a directory and for desktop in another directory.

In the future, please ask first on the forum to get the validation of another community member that it's a bug before reporting it :) Thanks!
