### ISSUE TITLE
Gdevelop does not detect the touchpad correctly 

### ISSUE THREAD

**Issue by DeividHiGamboa** [4ian/GDevelop#4188]
Hello, I am using gdevelop without a mouse and they do not work correctly, if I zoom in what it does is make the scene down and if I zoom out it makes the scene down. Also if I do the downward gesture it brings the scene closer, and if I do it upwards it zooms out the scene, the gestures work inverted in gdevelop, I don't know if it's just my pc or it happens to others too

Here I leave an example to understand me
https://user-images.githubusercontent.com/109392555/183265776-ba1b2ea4-2202-4ac4-a411-3a0cd6e1e927.mp4

I am using windows 10 64 bit

I await your answers, I hope you can solve it, and thanks in advance

**Comment by 4ian** [comment]
This seems correct to me and just a matter of configuring your computer to reverse the mouse wheel orientation?

**Comment by DeividHiGamboa** [comment]
> This seems correct to me and just a matter of configuring your computer to reverse the "mouse wheel" orientation (which is what is used internally, even if it's a touchpad)?

But why in gdevelop does it work this way? you do not think that something uncomfortable to use, since the other programs work without inverting the gestures
