### ISSUE TITLE
Tilemap Index Mode Broken since 5.0.139

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#4247]
## Describe the bug
User Mastermind6425 was wanting to do different Z order of tiles on the forums. Tilemap layers *should* accomplish this, using a single tilemap file set up in multiple tilemap objects configured to use index mode and each layer selected.

Unfortunately, this appears to no longer work since 5.0.139. Switching to index mode on Tilemap objects will only display a layer if index 1 is selected, all other indexes will not display any of the tiles. The object works as expected in 5.0.138

## To Reproduce
1. Create a multi layer tilemap (or open the Not-A-Vania example)
2. Create the tilemap object.
3. Set the tilemap object to index mode and set any index other than 1.
4. Add the tilemap object to the scene.

Alternatively, open the Not-A-Vania example, go to the Stage scene, and change the display mode to index then select an index from 0 through 3 (other than 1).

Not-A-Vania examples
Index 2 in GDevelop 5.0.138
![image](https://user-images.githubusercontent.com/24237149/187403517-0682c10a-8aed-462d-b59c-fbe9f3e00a86.png)

Index 2 in GDevelop 5.0.140 
![image](https://user-images.githubusercontent.com/24237149/187403592-34d65574-36c5-4461-9fb3-8e733c4b43b5.png)
(Displays the same in 5.0.139)

## Other details
* Include any OS/browser version/smartphone that you're using - Windows 10 64 Bit
* Which version of GDevelop are you using? The desktop app or the web-app? GDevelop 5.0.140, I tested .140 in both desktop and browser. I tested .139 and .138 on desktop.

**Comment by willianholtz** [comment]
Really this happens, I thought it could be something related in Tiled in itself. I noticed this when I was making the game for JAM, in which I only used the index which was the paths for the player to pass!

So, in this case, I used "visible" so that I only used what I really wanted to appear, and of course, I left it hidden in the tiled!

**Comment by D8H** [comment]
Thank you for reporting this. It should be fixed in the next released.
