### ISSUE TITLE
Asset store submission (Playing Cards & Poker)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4262]
- Trello Card: https://trello.com/c/CkBDtflr/120-playing-cards-poker

- License: CC0
- Author: Mix of Authors
- Link to the original website:
https://opengameart.org/content/playing-cards-3
https://opengameart.org/content/asset-pack-pixel-poker
https://opengameart.org/content/playing-card-assets-52-cards-deck-chips
https://opengameart.org/content/jumbo-index-playing-cards
https://opengameart.org/content/2d-poker-pack
https://zxyonitch.itch.io/pixel-playing-cards-52-cards-card-back
https://opengameart.org/content/cards-set

- Zip file: [Playing Cards and Poker.zip](https://github.com/4ian/GDevelop/files/9986976/Playing.Cards.and.Poker.zip)

**Comment by Entr0py404** [comment]
I just notice the pack by mehrasaur is not ready I will upload later here if still open or separately and mark this issue

**Comment by Entr0py404** [comment]
Here is the package: 
[Playing Cards and Poker.zip](https://github.com/4ian/GDevelop/files/9934125/Playing.Cards.and.Poker.zip)

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/202728054-26082ba0-beff-44b8-b003-12abb1df938a.png)
![image](https://user-images.githubusercontent.com/1670670/202728134-92bd7d96-6c93-428a-86bf-caad39c7373d.png)

**Comment by Entr0py404** [comment]
Did you mean this weekend or this upcoming weekend? 🤔

No rush just asking

**Comment by Bouh** [comment]
I've other priorities in this beginning of the week. It will be added
before this WK for sure ☺️

**Comment by Bouh** [comment]
The pack has been added, thank you :)
