### ISSUE TITLE
Asset store submission (FoozleCC: Void Collection)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4264]
Trello card: Trello card: https://trello.com/c/bMuIg1iZ/115-foozlecc-void-collection
Package: [Void.zip](https://github.com/4ian/GDevelop/files/9484492/Void.zip)

**Comment by Entr0py404** [comment]
I think I should I have had these assets face the right, let me know if you want me to do that.

**Comment by Bouh** [comment]
> I think I should I have had these assets face the right, let me know if you want me to do that.

Spaceships in the asset store facing up and down, it's fine.

For some spaceships there are two objects with 3 animations, I think these assets can be one unique object with 3 animations.
What do you think? I see that for other objects too.

I fix all these objects for this assets pack, but can you look at the other packs you shared, please? 🙏

[See how looks like the asset pack for now.](https://streamable.com/e/nc2xeb)


![image](https://user-images.githubusercontent.com/1670670/189305589-a2c0f604-4709-4d48-b55b-ba134f196b29.png)

**Comment by Bouh** [comment]
- Some files (big stars) are are named with `Tiled`, but they don't display correctly in the editor, I'm not sure it's a good idea to put them as a Tiled objects, they'll be fine as a classic sprite.
- There is a lot of issue with ships in their animations name + idle, I think you made an error by renaming the assets with `Destruction` and `Ship` I fixed these.

I let you take a look back at the fixed folder:
[FoozleCC.zip](https://github.com/4ian/GDevelop/files/9535551/FoozleCC.zip)
