### ISSUE TITLE
Asset store submission (Wesxdz: Game Assets)

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4265]
Trello card: https://trello.com/c/9X3t6Xg8/98-wesxdz-game-assets
Package: [Game Assets.zip](https://github.com/4ian/GDevelop/files/9484481/Game.Assets.zip)

**Comment by Bouh** [comment]
Hello
As I told you yesterday, here is my feedback on how we adapted the files.

- We have mainly added a Props, Characters, and Nature folder.
- The root is Wesxdz Game Assets, inside there is skullcup, which seems to be the asset pack name on opengameart (in the URL).
- Added a few tags that were on [https://opengameart.org/content/skullcup](https://opengameart.org/content/skullcup)
- I give you back the folder to let you take a look. [Wesxdz Game Assets.zip](https://github.com/4ian/GDevelop/files/9491908/Wesxdz.Game.Assets.zip)


![image](https://user-images.githubusercontent.com/1670670/188509867-83691723-3407-4e3a-a7f4-76a044d17479.png)


![image](https://user-images.githubusercontent.com/1670670/188509869-84528be6-13da-454f-8572-59218cd4196f.png)

**Comment by Entr0py404** [comment]
Thank you Bouh I will try to package future assets accordingly

**Comment by 4ian** [comment]
Thanks a lot @Entr0py404!

**Comment by Bouh** [comment]
Thank you @Entr0py404 
I confirm the assets pack is live in the app :)
I move to the next packs 🐱‍🏍
