### ISSUE TITLE
Certain object (Tilemap) commands are not recognized

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#4275]
Some scaling and file checking commands are not recognized in Tilemap.

Look:

https://user-images.githubusercontent.com/23488207/189242336-ba54b2c2-4d5b-45e3-a1bd-4893f48e3e01.mp4

**Comment by D8H** [comment]
It was fixed by this PR in July:
* https://github.com/4ian/GDevelop/pull/4141

You should upgrade to the last version of GDevelop.
