### ISSUE TITLE
Particle emitter angle is is not updated correctly if particle maximum force is set to zero.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#4312]
If particle emitter "Maximum emitter force applied on particles" is set to zero it breaks particle angle setting and the particles are not following the angle setting of the object.
The particles will how ever for some reason stick to 0 and 180 degrees depending if the angle is pointing to the left or right side of the object.

If the emitter force is above zero you can change the angle of the particle emitter normally and the particle emitter turns as they should be.

This is the emitter used.
![image](https://user-images.githubusercontent.com/90930609/191427428-c436fa42-f160-48db-bedb-85e91e065044.png)

This is the code to test.
![image](https://user-images.githubusercontent.com/90930609/191427113-a6ad804c-fe7b-4619-a7ab-31830b60818d.png)

This is how it behaves when emitter force is set to zero and it points to either 0 or 180 degrees.
![image](https://user-images.githubusercontent.com/90930609/191426162-e4e634e7-24f5-4e4d-bbab-3b82ab04bfd8.png)

And this is how it behaves when the emitter is set to 1 or above so it points to the mouse cursor..
![image](https://user-images.githubusercontent.com/90930609/191426558-87a3af01-ae27-4c19-92c6-48bfbd4b204c.png)

Windows 10
![image](https://user-images.githubusercontent.com/90930609/191427887-6804f8ce-1585-4283-a138-9e31191f2d89.png)

**Comment by AlexandreSi** [comment]
Hi!
Thanks for taking the time to open this issue!
I think that the logic is that the particles are emitted thanks to the force applied on them as an initial condition.
So having an edge case when the force should be at most 0 isn't surprising.
What are you trying to achieve?

**Comment by VanCastar** [comment]
> 

Setting diminishing particles on the spot they are created without them moving anywhere after spawning.
