### ISSUE TITLE
Footsteps - Essentials (Audio)

### ISSUE THREAD

**Issue by NoxSound** [4ian/GDevelop#4318]
## Description

**Footsteps - Essentials** is a free sound pack with 397 quality sounds. This pack is here to help you in your projects.

.397 high-quality individual sounds recorded outside.
.13 different surfaces (DirtyGround, Grass, Gravel, Leaves, Metal, Mud, Rock, Sand, Snow, Snow Hard, Tile, Water and Wood).
.Mono, .Wav, 48kHz / 24bits.

[Footsteps_Essentials_NOX_SOUND.zip](https://github.com/4ian/GDevelop/files/9625646/Footsteps_Essentials_NOX_SOUND.zip)

- License: Creative Commons 0 License (CC0)
- Author: Nox_Sound
- Link to the original website: https://nox-sound.itch.io/essentials-series-sfx-nox-sound // https://assetstore.unity.com/packages/audio/sound-fx/foley/footsteps-essentials-189879
- Zip file: 24mb

**Comment by Bouh** [comment]
Hi @NoxSound 
Thank you for these audio files!
We have added your files into GDevelop, there should be available in a dozen minutes.

Thank you again!

**Comment by NoxSound** [comment]
Hi @Bouh !
You're welcome, with pleasure!
