### ISSUE TITLE
Character disappears when using PlatformCharacter with Tween.

### ISSUE THREAD

**Issue by ajotanc** [4ian/GDevelop#4321]
## Describe the bug
I was trying to do one of the Tween effects with my character and then the following problem happened. I added an "a" key press to perform the Tween (Scale) effect, and the result is that whenever I press the key my character disappears. So I did the test removing the behaviors (PlatformCharacter) and the Scale Tween effect worked correctly. Follow the video with an example.

I don't know if this is happening from this version or from earlier ones.

https://user-images.githubusercontent.com/47322034/191887925-2cfd1127-8a7f-4810-bfa0-065a1a49a91c.mp4

**Comment by D8H** [comment]
The character should not disappear, but it's not recommended to use tweens or forces with the platformer behavior. It can make ambiguous state that the platformer behavior handles as it can. For instance, teleporting a character inside a wall will allow a jump because it's better than risking to stick a character on a floor.

It's recommended to use an hidden object as hitbox and put object over it. This way effects doesn't change the hitbox.

**Comment by ajotanc** [comment]
> The character should not disappear, but it's not recommended to use tweens or forces with the platformer behavior. It can make ambiguous states that the platformer behavior handles as it can. For instance, teleporting a character inside a wall will allow a jump because it's better than risking to stick a character on the floor.
> 
> It's recommended to use an hidden object as an hitbox and put an object over it. This way effects don't change the hitbox.


I deduced that it could be this, would you have an example video on how I do this Hitbox in the character? Because I haven't found a current one. If possible, of course!

**Comment by D8H** [comment]
This example uses this method:
https://gdevelop.io/game-example/old-platformer

The red rectangle has the Platformer behavior and the animated character is only following it.

**Comment by ajotanc** [comment]
> This example uses this method: https://gdevelop.io/game-example/old-platformer
> 
> The red rectangle has the Platformer behavior and the animated character is only following it.

So in this case, everything I use as an extension, I'll need to put it in HitBoxPlayer, instead of the player's Animation, right?
