### ISSUE TITLE
Layer Time Scale is not affecting Physics objects or Object Tweens

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#4322]
When trying to change the Time Scale of a Layer object with Physics 2.0 behaviour and Object Tweens are not affected at all.

Make 2 layers
Make physics object that falls with gravity on both layers side by side
Make another object that has a tween for movement on both layers side by side
Make an object that is moved by something else but physics and tweens ie. forces on both layers side by side

This code tests the effect
![image](https://user-images.githubusercontent.com/90930609/191934762-31002de8-be7f-49fe-8085-4c96ed3ff3e2.png)

Only the objects moving (without using physics or tweens) are affected per Layer selected.

Windows 10
![image](https://user-images.githubusercontent.com/90930609/191935191-fabde306-07d7-4f98-acdc-f5b788d9fd45.png)

**Comment by Bouh** [comment]
The time scale on the layers has been thought for timers and classic movent with forces. This is not a bug.
