### ISSUE TITLE
ToJSON will cause error when array has missing keys

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#4327]
Calling ToJSON (GlobalVarToJSON, etc.) can cause a error, which will result in missing frame logic which can cause all sorts of bugs. An array really shouldn't have missing keys, but in Gdevelop it's really easy to cause this type of situation because keys are created dynamically just from checking them.

This error may seem contrived, but it happened to me on accident and it was quite difficult to debug and pinpoint the cause.

## To Reproduce
1. Create a Scene variable "blob" of type Struct
2. Add a child to "blob" called "list" of type Array
3. Add two boolean children to "list"
4. Call ToJSON on "blob" and it will work as expected
5. Now add a conditional to check if "blob.list[5]" is true... this will create a gap in the array.
6. Call ToJSON on "blob" and it will cause an error

Demo Reproduction:
[issue-4327.zip](https://github.com/4ian/GDevelop/files/9661363/issue-4327.zip)

What the "blob" looks like after checking blob.list[5] in condition:
![global-vars-after](https://user-images.githubusercontent.com/251967/192685239-b1b4b473-26e6-4e36-9280-ba43b1d9fa40.jpg)

## Other details
* Windows Desktop Version 5.0.145

**Comment by AlexandreSi** [comment]
Hi @krunkster,
Thanks for taking the time to debug and report this issue.
Looks like checking for value of `blob.list[5]` creates something in the array indeed that ToJSON does not support.

> Now add a conditional to check if "blob.list[5]" is true... this will create a gap in the array.
Could you provide the way you do this step? Via a JS event or a condition?

**Comment by krunkster** [comment]
Just via normal "graphical" condition in the IDE... maybe they are called Event Blocks in GD terms?
Check boolean of scene variable blob.list[5] is true

**Comment by krunkster** [comment]
I've attached a reproduction demo as well as a capture of the corrupted (i.e. un-ToJSON-able) variable

**Comment by AlexandreSi** [comment]
Thanks for providing the project, that was easier for me to fix!
This should be merged today and available in next release.
