### ISSUE TITLE
Extension icons colors is barely seeable

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#4365]
## Describe the bug
![111](https://user-images.githubusercontent.com/81715237/194411288-c6e2886b-7782-45b2-9c2a-a80efd8b9bbb.PNG)
as you can see in the Screenshot, I can barely see the extension icons in the theme (GDevelop default Light).

## To Reproduce
**1-** Create new extension.
**2-** Extension properties.
**3-** Select extension icon.

## Other details
Latest GDevelop release (5.1.147).
Windows 10
GDevelop Desktop app

It would be better to turn the icons colors to: 
• Black when the user is using White theme.
• White when the user is using Black theme.:

**Comment by tristanbob** [comment]
@AlexandreSi you might be interested in this.
