### ISSUE TITLE
Admob breaks Cordova for iOS

### ISSUE THREAD

**Issue by javinladish** [4ian/GDevelop#4376]
When I use `cordova platform add ios` on a game export that has Admob events, I get an unsuccessful build.

In the error log, this is one of the things that pops up:

```
Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code null Error output:
/Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon/curls/classes.rb:36: [BUG] Illegal instruction at 0x0000000102270000
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

```

Is there a workaround to get Admob to work for iOS games? I can successfully do a Cordova build without Admob events, but when I use Admob events it breaks and I get "build failed" when I open in XCode.

Thanks in advance for any help!

**Comment by ClementPasteau** [comment]
Hi @javinladish 

What machine are you using to build the app?
A previous MacBook or a new M1/M2 ?

I've found a few threads mentioning a similar issue on new M1 chips (see https://developer.apple.com/forums/thread/652822)

**Comment by javinladish** [comment]
@ClementPasteau I'm using an M1 MacBook.

I'll try one of the workarounds from the link you provided and maybe also try it on my partner's old MacBook to see if I can get it to work. I'll report back if it works or not. Thanks!

**Comment by javinladish** [comment]
I tried some of the workarounds but haven't gotten it to successfully build in Xcode yet.

When I run `arch -x86_64 pod install` in Terminal I get:
```
[!] CocoaPods could not find compatible versions for pod "GoogleUserMessagingPlatform":
  In snapshot (Podfile.lock):
    GoogleUserMessagingPlatform (= 1.4.0, ~> 1.1)

  In Podfile:
    GoogleUserMessagingPlatform (~> 2.0.0)

Specs satisfying the `GoogleUserMessagingPlatform (~> 2.0.0), GoogleUserMessagingPlatform (= 1.4.0, ~> 1.1)` dependency were found, but they required a higher minimum deployment target.
```

When I run in Xcode I get an error:
`No such module 'UserMessagingPlatform'`

The UserMessagingPlatform framework is in the files that get exported so I add it to the Frameworks in Xcode. That seems to solve the UserMessagingPlatform framework issue, but then I get this error:

`framework not found FBLPromises`

I can find some FBLPromises files in the folder but not the "framework" itself.

**Comment by javinladish** [comment]
Okay I think I got it to work.

Apparently you can't use the ".xcodeproj" file after doing all this, you have to run the ".xcworkspace" file instead.

This gives me a successful build. Hopefully this all works now!

**Comment by tristanbob** [comment]
@javinladish congrats on making progress!

What documentation did you use to accomplish your goal?  Was it this?  https://wiki.gdevelop.io/gdevelop5/publishing/android_and_ios_with_cordova

I want to make sure our documentation is accurate and helpful.  Are you willing/interested in helping improve our wiki on this topic? Thanks for considering!

Tristan

**Comment by javinladish** [comment]
@tristanbob 

I used the GDevelop wiki to create the initial Cordova build and get the XCode file. But if you use any AdMob events in your game, it will not build successfully.

I'm not 100% sure exactly what steps fixed my problem because I did a few things.

The steps that fixed the problem for me:

`sudo arch -x86_64 gem install ffi`
then
`arch -x86_64 pod install`
then I added the UserMessagingPlatform framework file to my project in Xcode.

Then I saw on Stackoverflow someone said:

> In your project's directory, you are still building the ".xcodeproj" file instead of running the newly created ".xcworkspace" from the pod install. Remember, after pod installing, you MUST do edits on and work with the .xcworkspace instead.

**Comment by javinladish** [comment]
Well, it turns out that you don't even need to do the `sudo arch -x86_64 gem install ffi` and `arch -x86_64 pod install`.

All you need to do is open up the .xcworkspace file instead of .xcodeproj and the build will succeed.

**Comment by ClementPasteau** [comment]
Thanks for the update!

I'm gonna close this issue, considering it fixed.
The steps you've described above should be enough for others to debug/fix such problem if they have it.

Feel free to re-open this issue if there's anything new 👍
