### ISSUE TITLE
Black rectangle (camera view) in the Scene editor is not updating when changes are made to resolution

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4379]
## Describe the bug

Black rectangle (camera view) in the Scene editor is not updating when changes are made to resolution

## To Reproduce

1. Open a game with default resolution (800x600)
2. Watch the size and shape of the black rectangle that represents camera view
3. Change resolution to 400x600 (or any other resolution)
4. Notice that the black rectangle does NOT change shape and size (previously this worked)

## Other details

* Windows 11
* GDevelop 5.1.147

**Comment by PihRealms** [comment]
the same issue is on Linux 20.04 as well. The camera view does update after restarting the scene, but also sometimes it updates to some weird resolution.

**Comment by Bouh** [comment]
I wonder if this is a regression or it was something not yet implemented?
![Animation](https://user-images.githubusercontent.com/1670670/195278073-e3055fe5-314b-4cb7-b877-5597d51e21ea.gif)
