### ISSUE TITLE
After fixing an expression in a mini-popup, the event sheet still shows red

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4380]
## Describe the bug

After fixing an expression in a mini-popup, the event sheet still shows red

![image](https://user-images.githubusercontent.com/8879811/195230009-534a3baf-f6ef-4695-8f8c-6d113b4867f3.png)

## To Reproduce
1. Cause an error in an expression
2. Notice the event sheet is red
3. Click into expression and correct the error 
4. Notice the red inside the expression mini-pop goes away, but the event sheet still indicates an error exists
5. Once you click away from the mini-popup, the event sheet updates and removes the red color
6. This can be very confusing to users! (even me sometimes)

## Other details
* Windows 11
* GDevelop 5.1.147

**Comment by tristanbob** [comment]
Yes, your video is showing the situation.  Doesn't it feel wrong to see the red error after fixing it?

Possible improvements:
- Update original expression while editing the mini-popup 
- Hide the original expression while editing the mini-popup

**Comment by ClementPasteau** [comment]
hmm, it doesn't really feel wrong to me, as the value is saved in the events only when you leave the mini-popup field.

- update while editing -> it would feel weird having 2 fields updating at the same time.
- hiding the original expression -> possibly, but at the same time, there's value in seeing what you had before while you're editing to a new value.

Personal opinion: I like it like this.

**Comment by tristanbob** [comment]
Thanks for the consideration and discussion.  I'm closing this issue.
