### ISSUE TITLE
Childen of structure variable cannot have numerical value as name anymore

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#4391]
Hello, bug spotted:

## Describe the bug

![Peek 14-10-2022 11-47](https://user-images.githubusercontent.com/8144048/195817652-641a7930-4b20-401b-aaec-0665c76ae4a4.gif)

As demonstrated in the gif, you can't anymore name a child var of a structure var with a numerical value, while only commas and dots should be forbidden.

I (use to) use a lot of structures variables childs with numerical names for a long time (in all my projects since 2014), mostly because previously arrays weren't existing, and also because arrays are not always the better choice ;)  

Old child variables are still working with numerical name (setted in the past), but it's not possible to declare new ones. 

## To Reproduce
Steps to reproduce the behavior: like in the gif !
1. Open a variable editor (global, scene or object vars)
2. add a variable, set it as structure
3. try to name the child var created with a numerical value
4. See error : the value is rejected

## Other details
* Linux Ubuntu based distro (Focal)
* Appimage version of GDevelop (not the flathub version)
* GDevelop 5.1.147

**Comment by AlexandreSi** [comment]
Hi @KinkGD 
Thanks for reporting this. I enforced too strict checks on the child variables names. I'll remove this.
