### ISSUE TITLE
Behaviors should automatically provide expression functions to access their properties

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4400]
## Description

When creating a behavior, extension creators must manually create expressions that return the properties of the behavior.  For complex extensions, this can be a lot of work (see image) and it has resulted in many copy/paste errors.  

![image](https://user-images.githubusercontent.com/8879811/196017934-b9b05906-819c-4a4e-a7b7-0005ebce5280.png)

## Solution suggested

- Automatically create expression functions for all behavior properties that are NOT hidden

**Comment by D8H** [comment]
This could be done with buttons to generate a skeleton for getter or setter.
When getters and setters already exist, the buttons could be used to update the name, description and sentence according to the property.
