### ISSUE TITLE
JSevent need Word Wrap

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4412]
## Describe the bug

JSevent need a Word Wrap option in the context menu of Monaco (the code editor).
Because in extensions editor and in other panels it's difficult to navigate and read.
![image](https://user-images.githubusercontent.com/1670670/196648628-6a34860f-e00b-4ce7-800a-10626f3e55bf.png)

## Other details
GD5

**Comment by 4ian** [comment]
We would almost need a prettier that reformats the code to fit in 80 columns. But yeah having a word wrap option is probably easier.

**Comment by 4ian** [comment]
I've activated wordWrap at the viewport width, or 80 columns max:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1280130/196690937-ebaed2ca-9155-41a0-90ff-930dcc9de03a.png">

Also fixed the text on top/bottom overflowing out of the window/area especially with languages having long translations.
