### ISSUE TITLE
Adding terrain to the existing pixel art asset pack by pixel frog

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4424]
The existing version of the asset pack in engine does not have the terrain art from the original asset pack.

This updated asset pack just adds a folder with terrain options in it:
-6 new 9patch panel sprites to use as platforms, walls, etc.
-3 new sprite objects to use as thin jump through platforms.

- License: CC-BY 4.0
- Author: Pixel Frog
- Link to the original website: https://pixelfrog-assets.itch.io/pixel-adventure-1
- Zip file: 
[Pixel Adventure Pack.zip](https://github.com/4ian/GDevelop/files/9841717/Pixel.Adventure.Pack.zip)

**Comment by Bouh** [comment]
One object terrain is called `9patch`.
It's maybe not the best name.
Would you think if I rename this `terrain`?
![image](https://user-images.githubusercontent.com/1670670/198026107-a9de5129-4d49-4d35-aca9-f29a93d1312f.png)

**Comment by HelperWesley** [comment]
I copied the format from the wiki page. 😕
![image](https://user-images.githubusercontent.com/72082749/198317461-6a1fe6bc-5723-4ead-9678-5e7194b63e95.png)

I don't see any object on the list that's just called "9patch". Everything begins with "9patch_" but then has a name associated with it along with the cardinal direction it's supposed to be placed in.

**Comment by Entr0py404** [comment]
This was a issue on my side sorry about that

**Comment by HelperWesley** [comment]
No worries, I'm just glad we don't have to rewrite the wiki or something.

I had also done this with another asset packs too, and I'm picking at a few others now, so I'm glad I don't have to go re-do any of it. 😅

**Comment by Bouh** [comment]
Done, sorry to be late, and thanks for the files!
