### ISSUE TITLE
Adding some alternative sprites and tiled sprites for 16x16 dungeon art pack

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4425]
Added a few things to increase the usability of this art pack:
-Added a new section of "full" sprites for wall pieces, to make setting up rooms easier for users.
-Added some tiled sprites for both the walls and UI, to give users more options.
-Added a few additional sprites that weren't added in originally from the asset pack.
-Created a separate ladder object so users can more easily find it, before it was a little hidden among animations of a floor object.

- License: CC0
- Author: Robert Norenberg (0x72)
- Link to the original website: https://0x72.itch.io/dungeontileset-ii
- Zip file: 
[16x16 Dungeon Tileset.zip](https://github.com/4ian/GDevelop/files/9842815/16x16.Dungeon.Tileset.zip)

**Comment by Bouh** [comment]
I fixed `Door All_Closed.png` and `Door All_Open.png` (on right) to same the same height as `Door All.png` (on left) 
![image](https://user-images.githubusercontent.com/1670670/197407406-38c1ea3f-f11f-466a-9647-2b8491fb5cb0.png)

**Comment by HelperWesley** [comment]
Ok. 👍
