### ISSUE TITLE
GDevelop platformer example had a sprite that was the wrong size.

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4427]
Noticed the red hero platformer character default size in the asset pack is way too big for the rest of the art in the pack.

So in order to retain the higher quality red hero artwork, and also give users a properly scales red hero for their game, I added a new folder with a "scaled red hero" sprite. Scaled to appropriately fit in the game space. This way users won't be stuck trying to rescale their red hero character manually and ending up with a blurry unappealing character.

- License: 
- Author: GDevelop
- Link to the original website: 
- Zip file: 
[GDevelop examples.zip](https://github.com/4ian/GDevelop/files/9842963/GDevelop.examples.zip)

**Comment by Bouh** [comment]
Moved into another repo for better tracking.
