### ISSUE TITLE
Units in GDevelop

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4452]
## Describe the bug
I wonder if this is a typo or not:

![image](https://user-images.githubusercontent.com/1670670/198552892-e5e14fdc-6dfb-4a1a-8931-f7fdd77b5b5b.png)

![image](https://user-images.githubusercontent.com/1670670/198553167-1474aa5b-034a-4cd1-a5b1-c300f758ce60.png)

![image](https://user-images.githubusercontent.com/1670670/198553133-e2d0a915-68bd-43f8-8d5b-4e6fb7b34975.png)

## Other details
GD 5.1.146

**Comment by 4ian** [comment]
Nope this is correct. 
- A "speed" is a "distance per second" (so pixel per second).
- An acceleration is how much speed you gain or lose per second. I.e, if you replace the word "speed" by "distance per second": An acceleration is how much distance per second you gain or lose per second

In yet other words, an acceleration unit is a distance per second per second, so pixels per second per second.

We should still rework stuff to show units in behaviors/effects and this will display `px/s` for speeds and `px/s²` for accelerations.
