### ISSUE TITLE
Rolling ball asset pack update

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4454]
This submission is a zip file containing two seperate folders with updates for the rolling ball asset pack.
This is not the usual submission format, but this should help prevent confusion.

Changes folder, things that need to replace existing artwork:
-Seperated platform objects with animations to individual objects with single animations.
-2 existing objects need to be combined in to 1 single object with 2 animations.

Additions folder, things that are added to the pack without needing to modify any existing art:
-A 9patch laser that can live alongside the existing laser object, but offers users better sizing options.

Zip file: 
[Rolling Ball Update.zip](https://github.com/4ian/GDevelop/files/9888997/Rolling.Ball.Update.zip)

**Comment by Bouh** [comment]
Hi

I merged the assets in replacement of the previous.
I wasn't able to merge the Laser, because 9-patch can be in a rectangle shape, the dimension must be in a square.
So I'll leave the laser as is as an classic sprite.
