### ISSUE TITLE
Regressions in the animation previews

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#4461]
## Describe the bug

- The preview is not taking the whole height of the window.
- The default zoom seems also broken (maybe linked to the previous bug)
- The loading should probably not be shown at all here.
- The looping seems also broken 

![image](https://user-images.githubusercontent.com/1280130/198836738-60afc1c6-b913-41f7-a75d-b995868b6cfc.png)

## To Reproduce

- Open the preview animation window.
- For the looping issue:
  <img width="778" alt="image" src="https://user-images.githubusercontent.com/1280130/198836800-077e268f-5cd2-48dc-857d-02c2edc11ca7.png">

## Other details

* Version 5.1.149, desktop

**Comment by ClementPasteau** [comment]
I've noticed some of those issues and started fixing them in another PR, but not merged yet.
We'll get it fixed ASAP, we'll see if we get a new release for this hotfix or wait for a bigger one later.
