### ISSUE TITLE
Tilemap objects aren’t recognized by their own actions

### ISSUE THREAD

**Issue by Pretauhi** [4ian/GDevelop#4474]
Hi everyone,
While using Tilemap I’ve encountered bugs with the actions:
- Set the Tilemap JSON file of “Tilemap Name” to “JSON File”
- Set the tileset JSON file of “Tilemap Name” to “JSON File”

The actions doesn’t recognize the “Tilemap Name” and throw an error “The object does not exist or can’t be used here” but I have used this exact object to create it in the first place.

I’ve tried to create a project on the Web version to confirm it by:
- Creating a Tilemap object (all of the Atlas and Tilemap JSON are optional to recreate the bug).
- Create an action in the event sheet to set the Tilemap or the tileset (“JSON File” is optional).
- And then “Tilemap Name” will be marked red with the error.

I don’t know if it’s a new bug with the latest version cause I didn’t used those actions before it.

No project files are needed due to the simplicity of it.
Version of GDevelop: 5.1.149 desktop version
Operating system: Windows 10 version 22H2
Browser: Google Chrome Version 107.0.5304.88 (Build officiel) (64 bits)
All drivers are up to date.

Thanks everyone for your time and have a nice day !

**Comment by PascalLadalle** [comment]
Confirmed on my side with the platformer tilemap example.
Works with tilemap collision mask objects, but not with the tilemap itself.
![image](https://user-images.githubusercontent.com/25978830/199286020-ecebfd82-26c4-491d-9166-8f9bb338cbf2.png)
