### ISSUE TITLE
Pixel platformer asset pack update

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4477]
This submission is a zip file containing two seperate folders with updates for the pixel platformer asset pack.
This is not the usual submission format, but this should help prevent confusion.

Changes folder, things that need to replace existing artwork:
-Changed a number of tiles in to tiled sprites.
-Broke up a single house object with multiple animations in to mutliple objects.
-The lamp on/off object were made for 2 different orientations, so those were broken in to separate objects.

Additions folder, things that are added to the pack without needing to modify any existing art:
-A larger UI tiled sprite version of the heart for lives.

Zip file:
[Pixel Platformer Pack Update.zip](https://github.com/4ian/GDevelop/files/9905563/Pixel.Platformer.Pack.Update.zip)

**Comment by Bouh** [comment]
If other packs come to be improved with updates like this let me know which pack you want.
I can send it to you, you can make the changes directly, it will avoid having "change folders", "add folders".

With Git as everything is versioned only the changes will be taken into account.
This includes deletions, name replacements, and new files.
