### ISSUE TITLE
Controller And Input Icons By ElDuderino

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4485]
- License: CC0
- Author: ElDuderino
- Link to the original website: https://opengameart.org/content/controller-input-icons
- Zip file: [Controller And Input Icons.zip](https://github.com/4ian/GDevelop/files/9934137/Controller.And.Input.Icons.zip)

**Comment by Bouh** [comment]
Thanks and sorry for the delay.
The pack is now live!
![image](https://user-images.githubusercontent.com/1670670/222161824-1a81c7a1-1a5c-4fea-bf6b-1e59115681a7.png)
