### ISSUE TITLE
Fantasy RPG character pack By Franuka

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4487]
- License: CC BY-SA 4.0
- Author: Franuka
- Link to the original website: https://franuka.itch.io/rpg-townsfolk-pack
- Zip file: [Fantasy RPG character pack.zip](https://github.com/4ian/GDevelop/files/9934188/Fantasy.RPG.character.pack.zip)

**Comment by Bouh** [comment]
This pack is now available in the asset store.
Thank you for your time on packaging this, it's like always, perfectly packaged.

![image](https://user-images.githubusercontent.com/1670670/208309459-f4077b78-d959-4fbd-8998-5e5f212fc036.png)
![image](https://user-images.githubusercontent.com/1670670/208309489-6c0521ca-f121-4aa5-adb7-4432123b0fa0.png)
![image](https://user-images.githubusercontent.com/1670670/208309493-acf11a79-b545-42e3-bb46-d02efa5e2888.png)
