### ISSUE TITLE
Pixel Art Spell Magic FX By ppeldo

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4488]
- License: CC0
- Author: ppeldo
- Link to the original website: https://ppeldo.itch.io/
- Zip file: [Pixel Art Spell Magic FX.zip](https://github.com/4ian/GDevelop/files/9934196/Pixel.Art.Spell.Magic.FX.zip)

**Comment by Bouh** [comment]
The pack will be added to public today!
A pleasure to work with your packages, sprite are all aligned 🤩
![image](https://user-images.githubusercontent.com/1670670/199967419-a50d9ed5-d3df-4190-9fce-495f1e5de704.png)

![image](https://user-images.githubusercontent.com/1670670/199967445-5ccbc3c8-851b-4a08-8c5a-e9a699243790.png)

![image](https://user-images.githubusercontent.com/1670670/199967481-3dca5828-9140-40be-ba5e-a5a61580e422.png)

![image](https://user-images.githubusercontent.com/1670670/199967513-a19eaeb0-e761-47ab-b524-cf719829403e.png)
