### ISSUE TITLE
Western FPS 2D By Pixel-boy

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4501]
- License: CC0
- Author: Pixel-boy
- Link to the original website: https://github.com/sparklinlabs/superpowers-asset-packs
- Zip file: [Western FPS 2D.zip](https://github.com/4ian/GDevelop/files/9940943/Western.FPS.2D.zip)

**Comment by Bouh** [comment]
I converted heath bar into panel sprite objects.

![image](https://user-images.githubusercontent.com/1670670/200836329-b0862a72-50d1-4ad7-b437-53a89a84bb82.png)

![image](https://user-images.githubusercontent.com/1670670/200836417-e773126d-ce47-4396-8d20-cc2e8df0db26.png)
