### ISSUE TITLE
Flat Social Media Icons By Wishforge

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4504]
- License: CC BY 4.0
- Author: Wishforge Games
- Link to the original website: https://wishforge.itch.io/3000-free-icons
- Zip file: [Flat Social Media Icons.zip](https://github.com/4ian/GDevelop/files/9941273/Flat.Social.Media.Icons.zip)

**Comment by Bouh** [comment]
I have only added images of 128px.
There is no need for smaller dimensions for now, maybe in the future we will be able to resize, maybe, nothing has been decided.
Anyway the smaller ones can be added later if needed.
The pack is now in the GDevelop Asset Store.
Thank you (again)!

![image](https://user-images.githubusercontent.com/1670670/200142250-6fc6af6b-9473-43e7-aff4-431b085cbea6.png)
