### ISSUE TITLE
Solarized dark theme issue

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4508]
A user on the discord asked how to close the group panel, They shared this screenshot and I double checked the Solarized Dark theme on my mobile device at the time and had the same issue.

It appears that the close x icon is the same color as the background or something to make it appear as though it is not there but it does work.

![image.png](https://user-images.githubusercontent.com/75917656/200132829-4f2d5ca9-c058-4c4c-b7dc-1a49036c710c.png)

Link to the conversation: https://discord.com/channels/258623956158906368/258659467887902730/1038497016034099200

**Comment by jakerosado** [comment]
![Screenshot from 2023-10-19 23-28-34](https://github.com/4ian/GDevelop/assets/32206266/f1599f70-f044-4578-9ecc-a3653c8dc889)

Preview of PR.

**Comment by jakerosado** [comment]
Updated after reassessment:
![Screenshot from 2023-10-20 13-02-18](https://github.com/4ian/GDevelop/assets/32206266/de78a634-1e8c-4423-ad13-0cdc95eb9298)
