### ISSUE TITLE
Add missing functions related to tiled sprite properties

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4519]
## Description

Tiled sprites are missing some functions to get and set their properties.

## Solution suggested

- Add action: `Set default width of tiled sprite`
- Add action: `Set default height of tiled sprite`

- Add condition: `Check the default width of tiled sprite`
- Add condition: `Check the default height of tiled sprite`

- Add expression: `MyTiledSprite.DefaultWidth()`
- Add expression: `MyTiledSprite.DefaultHeight()`

**Comment by D8H** [comment]
Can you explain in which context you need these functions?
The default dimensions are shared by all instances of an object. I'm not sure how this could be used.

**Comment by tristanbob** [comment]
My use-case is for making a resource bar.  I want to know how many pixels an individual unit is, so I can increase the tiling based on the unit-size.  I guess I have a couple of options:

- Add a property that represents the width of one-unit
- Assume that the current width of the bar instance is one-unit

I think I'll choose the first option; it will be the easiest for users to understand.

Thanks, I'll close this request.
