### ISSUE TITLE
Blurry pixels for 9 patch object

### ISSUE THREAD

**Issue by HelperWesley** [4ian/GDevelop#4523]
Blurry 9patch objects

## To Reproduce
1. Create a 9 patch object.

[My project56.zip](https://github.com/4ian/GDevelop/files/9962480/My.project56.zip)

@ClementPasteau

**Comment by HelperWesley** [comment]
Whatever the issue is, it seems limited to 9 patch objects. The object to the left is a tiled sprite, the floor the character is standing on is a 9 patch.

![image](https://user-images.githubusercontent.com/72082749/200609275-efb456ac-3e31-46c3-8bdc-4bfa0bae402e.png)

**Comment by Oxey405** [comment]
I worked on the renderer this week, maybe should I take a look ? :)

**Comment by D8H** [comment]
The isssue is that `cacheAsBitmap` uses `PIXI.SCALE_MODES.LINEAR` for the sprite in cache.(`this._spritesContainer._cacheData.sprite._texture.baseTexture.scaleMode`).
We will probably have to deactivate the optimization when the image smoothing is deactivated on the image used by the 9-patch.
