### ISSUE TITLE
Weird Swords By ARoachIFoundOnMyPillow

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4537]
- License: CC0
- Author: ARoachIFoundOnMyPillow
- Link to the original website: https://opengameart.org/content/16x16-swords-weird
- Zip file: [Weird Swords.zip](https://github.com/4ian/GDevelop/files/9987295/Weird.Swords.zip)

**Comment by Bouh** [comment]
Added 👍  thx u
