### ISSUE TITLE
RPG Weapons By Shade

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4540]
- License: CC0
- Author: Shade
- Link to the original website: https://opengameart.org/content/16x16-weapon-rpg-icons
- Zip file: [RPG Weapons.zip](https://github.com/4ian/GDevelop/files/9987309/RPG.Weapons.zip)

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/202425498-a3c6f5d4-1f3d-4d44-8605-8538c8ead5ce.png)
![image](https://user-images.githubusercontent.com/1670670/202425591-ac39c2b1-e543-4464-86e2-f0d352e74f71.png)
![image](https://user-images.githubusercontent.com/1670670/202425617-30c95478-d762-48db-8ddb-8e0351c1ae03.png)
