### ISSUE TITLE
After the new update 5.1.150 the scrolling of zoomed image in point, collision mask and physics collision mask editor broken.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#4547]
After the new update 5.1.150 the scrolling of zoomed in sprites in point, collision and physics collision mask editors are broken.

There are no slider available and the middle mouse button dragging does not work.

![image](https://user-images.githubusercontent.com/90930609/201890194-1da8ac3e-5eea-4af2-ae9e-f099b1afabc8.png)

GDev version 5.1.150
Windows 11

**Comment by ClementPasteau** [comment]
Thanks @VanCastar 
Definitely a regression from 5.1.150.
We'll fix that asap
