### ISSUE TITLE
Cannot scroll custom collision masks

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4577]
When editing a custom collision mask, there's no way to scroll down/up to add more vertices.
A workaround is to use the Tab key and press Space when the focus is on the _Add a vertex_ button.
Issue confirmed on Windows 10, GDevelop v151.

![image](https://user-images.githubusercontent.com/25978830/203789930-2f8ac78b-4ba3-4d7f-b939-4943b1a0e0a1.png)

[source](https://forum.gdevelop.io/t/cannot-scroll-in-sprite-collision-mask-editor/43322)

**Comment by ClementPasteau** [comment]
Thanks for reporting this @PascalLadalle - I reproduced the issue and we'll fix this
