### ISSUE TITLE
Game freezes when using an action to change the opacity on a custom button object 

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4596]
## Describe the bug

Game froze on a black screen when using an action to change the opacity on a custom button object. 

This error is shown in browser console:

![Screenshot_2022-11-28_170644](https://user-images.githubusercontent.com/8879811/204422245-674426e5-dbf9-4d45-9dfc-71204acb0e93.png)

https://user-images.githubusercontent.com/8879811/204422357-019185c1-c9cf-46f1-a5f4-3a6baae3c861.mp4

Credit: This bug was discovered by Entropy on Discord.

## To Reproduce

1. Add a custom button object from the asset store
2. Add an action to set the opacity of that object
3. Preview the game (it will never load and console will show errors) 

## Other details

- GDevelop 5.1.151 
- Windows 11

**Comment by D8H** [comment]
It only freeze because the opacity is set continuously.
It's easy to fix, I'll do a PR.
