### ISSUE TITLE
Selecting the boids extension crashes the editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4614]
Open any project, go to the extension library, search 'boids' and click on the first result.
Instant crash on my side, both on Windows and web app.
The description is somehow corrupted? It doesn't even get to the point where I install it.

[source](https://forum.gdevelop.io/t/boids-movement-extansion-bug/43475)

**Comment by danired** [comment]
In the same source davy wrote this:

> Sorry about this. The issue should be fixed. Only GDevelop 5.1.151 is compatible with it, make sure to clear the cache of the web-app with Ctrl + Shift + R or Shift + F5.

> Thank you all for reporting and helping with this issue.

Did that work?

**Comment by PascalLadalle** [comment]
All good now on my side.
