### ISSUE TITLE
Return should close editable fields instead of creating a new line

### ISSUE THREAD

**Issue by alexissantos** [4ian/GDevelop#4619]
## Description
Whenever I hit Return after entering a value in a field/input on the events tab, it creates a new line. I understand that's the technically correct function of Return, but it seems suboptimal for workflow/UX.

<img width="350" alt="Screen Shot 2022-12-03 at 9 33 28 AM" src="https://user-images.githubusercontent.com/211494/205446151-141fd663-351b-4508-984b-ea27bc56c1a1.png">

## Solution suggested
I propose that pressing Return while entering something into a field closes the field that was being filled out. Additionally, hitting Return + Shift should allow for a newline, as it currently does.

## Alternatives considered
I've been training myself to hit the Escape key instead of Return for the time being.

**Comment by 4ian** [comment]
Agree! Note that you can also Cmd/Ctrl+Enter. 
But for inline parameters we should probably do the same for just Enter.

**Comment by tristanbob** [comment]
I agree, I prefer using alt-enter for formatting new lines and the default “enter” to close the mini-editor.  

This is how data entry works inside spreadsheet cells, which has some similarities to editing events.

**Comment by alexissantos** [comment]
Thanks, all!
