### ISSUE TITLE
All new projects are automatically saved in the cloud.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4657]
## Describe the bug

Silver-Streak: 
> As a heads up, since the new update every project I create on the web app is automatically saved to the cloud. This is a net negative for me because I have to manually go through and delete them all with as much as I go through testing. On top of the fact I don't want to create projects on the cloud at all unless I actually choose to save there.

I agree with him.

I would also like to point out that the suppression of saves is not easy.
We have to type the project name, but once we type in the input the name dissapear.
Could we have a copyable input or a button to copy the project name like here:
![image](https://user-images.githubusercontent.com/1670670/206858612-8ec9208e-6d9c-4e94-a785-56fe1a3d61d7.png)

![image](https://user-images.githubusercontent.com/1670670/206858510-001f86fc-8d34-4c9b-8d4f-b838a9755549.png)

(Note the hover on the close button is oval, something wrong with the layout?)

## Other details
Source Silver-Streak on Discord

**Comment by UjjawalTyagi123** [comment]
As a beginner i'm able  to resolve the close button bug , can I do this.

**Comment by AlexandreSi** [comment]
Hi!
I think that the use that you and Silver-Streak have of GDevelop is quite uncommon (or maybe I'm mistaken): to create project to test things and help people and then discard it.
I guess it could be a user preference instead.

@UjjawalTyagi123 thank you for getting involved into this issue. You can indeed open a pull request for the particular issue of the hover on the close button for the `UI/Dialog` component if you want. I'll review it!

**Comment by 4ian** [comment]
I agree this can be a bit of a pain and also a bit uncommon. I think a user preference would be perfect for this :)

**Comment by Bouh** [comment]
I'm good with an user preference 👍

**Comment by Silver-Streak** [comment]
> I agree this can be a bit of a pain and also a bit uncommon. I think a user preference would be perfect for this :)

If not a preference, I feel like remembering whatever was last used would be a good solution.

**Comment by RobTD** [comment]
I started looking into this today, as a trial for a good first issue. As far as I can see, the preferences setting and remember last option have been implemented in [c74110c](https://github.com/4ian/GDevelop/commit/c74110c058db888ed847e0524716bbc789180e16). Correct?

**Comment by Bouh** [comment]
> I started looking into this today, as a trial for a good first issue. As far as I can see, the preferences setting and remember last option have been implemented in [c74110c](https://github.com/4ian/GDevelop/commit/c74110c058db888ed847e0524716bbc789180e16). Correct?

Indeed this has been improved now the last choice is memorized.
