### ISSUE TITLE
Shortcut for Renaming object in the Objects List Panel

### ISSUE THREAD

**Issue by danired** [4ian/GDevelop#4668]
Hi,

I'm working on a feature that adds a shortcut for renaming an object in the Objects List Panel. The default shortcut is F2 as in many other programs.
I never use the "Right click" -> "Rename" option in any program, I think a shortcut is faster.

![image](https://user-images.githubusercontent.com/21989259/207060821-f46d6c0a-f4b3-4e19-aec3-abdcded58032.png)

Do you think is this useful? Could I add it as a PR once is finished?

**Comment by AlexandreSi** [comment]
Hi @danired, thanks for suggesting that shortcut!

I'm unsure about this: is F2 a common shortcut for mac and linux users as well?

**Comment by danired** [comment]
Normally yes.

__In Mac__ using Finder: https://www.webnots.com/how-to-rename-files-and-folders-in-mac-single-and-bulk/#:~:text=Open%20Finder%20and%20select%20a,keyboard%20app%20shortcuts%20preferences%20section.

![image](https://user-images.githubusercontent.com/21989259/207063833-e8b86acc-973b-4838-9d79-b95fe4f322d0.png)

__Linux__: 

![image](https://user-images.githubusercontent.com/21989259/207063897-04772ed5-d29d-491d-9b3b-a29924744bf6.png)

**Comment by danired** [comment]
I asked someone now with a Mac and told me that "Enter" key is for renaming, but in some sites they say F2 as well...

**Comment by Bouh** [comment]
F2 is a commun shortcut yes, and this is a great one to have to rename, wonderful idea here!

Please do not hardcode this, because in user perferences we can set the shortcut, think to add it inside 🙏 .

**Comment by danired** [comment]
Hi @Bouh ,

Yes, I added in the user preferences and can be changed / reseted as others shortcuts.
I only have 1 (hard) thing to finish the task, I will continue with it then!

I will add the PR soon this week.

Thanks for your feedback!

PS: Once finished and merged, if you hace any suggest adding other shortcuts ask me (Delete object? Rename objects group?)
