### ISSUE TITLE
Free Mini Interior Asset Pack: Bed + Bath 

### ISSUE THREAD

**Issue by h0ndred** [4ian/GDevelop#4686]
A small 16x16 based asset pack with general interior furniture like bedroom items and bathroom items.

- License: CC-BY *only valid within video games*

1 Free to use for both commercial and personal games.
2. Free to modify the assets.
3. Cannot resell/redistribute assets, even if modified. 
4. Give attribution/credit, even if modified.

- Author: H0ndred 
- Link to the original website: https://h0ndred.itch.io/mini-interior-asset-pack-bedroom-bathroom
- Zip file: 
[Mini Interior Asset Pack Bed + Bath Exports by H0ndred_GDevelop.zip](https://github.com/4ian/GDevelop/files/10248172/Mini.Interior.Asset.Pack.Bed.%2B.Bath.Exports.by.H0ndred_GDevelop.zip)
-This zip file contains most of the images used for Itch screenshots & cover image, not sure if you needed the source files of it so I put them in there.

-This is the assets for the downloader/user, without most of the screenshots or cover image.
[Mini Interior Asset Pack Bed + Bath Exports by H0ndred_Itch.zip](https://github.com/4ian/GDevelop/files/10248177/Mini.Interior.Asset.Pack.Bed.%2B.Bath.Exports.by.H0ndred_Itch.zip)

**Comment by arthuro555** [comment]
You seem to be missunderstanding the ND clause of the Creative Commons license: The ND (NoDerivatives) **doesn't** disallow reselling or redistributing your original unmodified assets. It only disallows to share work *based on* those assets. Therefore, users would not be allowed to share their games if they used assets under this license, and resellers may still sell them as long as it is the original work...

What you may want to do instead is give the CC-BY license but only for games. You do not have to have a single license for every use, just say that your CC-BY license is only valid for usage within games; if someone wants to use them in another way (e.g. sell them), then they'll need to contact you for getting another license under other terms (e.g. You must get a cut of all sales).

**Comment by h0ndred** [comment]
@arthuro555 Yes, I was reading the CC4 license and I did see that they could still sell the original assets, I was unsure of what to really do as I was very unfamiliar with creative commons licenses. I'll edit that in all my files!

**Comment by arthuro555** [comment]
The CC-BY still allows selling of assets, but all you need to do is say "I only grant the CC-BY license for usage in video games only" or something alike. That way, people can use the CC-BY license to sell their video games with your assets as long as they give attributions, but the CC-BY license cannot be used to sell your assets directly.

**Comment by h0ndred** [comment]
@arthuro555 Perfect, sounds about right to me. I'll update this in my license section.

**Comment by Entr0py404** [comment]
I repackaged your assets let us know if you are okay with these changes

[Mini Interior Asset Pack Bed And Bath.zip](https://github.com/4ian/GDevelop/files/10299533/Mini.Interior.Asset.Pack.Bed.And.Bath.zip)

**Comment by h0ndred** [comment]
@Entr0py404 
Everything seems good to me!
The only thing I'd point out is the CC-BY 4.0 could be a little more specific in the the read me.
Just as Arthuro suggested. "CC-BY 4.0 is valid only within video games" or something akin to that. 
Not sure if it is possible but that'd be nice to have. I am sure the user's can just look at the itch page to get clarification.
Otherwise, I appreciate the time you took to package them.

**Comment by Entr0py404** [comment]
that file is used by the asset store to show what license that assets are in, so added information isn't possible on our part

**Comment by h0ndred** [comment]
@Entr0py404 
I suspected, well, there is nothing else to add so no worries.
Just post it to the store when you're ready.

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/215612076-5b52fad3-005e-4a75-9dcf-28bc1721f985.png)
![image](https://user-images.githubusercontent.com/1670670/215612073-d0c4a78b-35be-4065-86c7-46cd9e61dfcc.png)

Thank you again guys for the work on this new pack!

**Comment by h0ndred** [comment]
@Bouh 
I sincerely apologize for my lack of oversight.
I did not recheck the files to make sure all the objects where named correctly. I checked them when Entropy made them...before I knew about and how to use the asset tool.
Tiled Objects have been incorrectly labeled, they are named "Tiled" rather than tagged with "Tiled_". As well as the profile of the asset is incorrect > it is just the combination of images of example rooms you can create with the asset rather than the thumbnail I made for it.


I already have a (hopefully) corrected version of the asset file > as far as the file name validator and asset store preview is concerned via Entropy's Asset Store Tool.

Let me know if any of these assets are incorrect.
Sorry Entropy and so sorry Bouh, you guys are very helpful and this was my fault for not recently checking the files to correct them before pushing them into the store.

[Mini Interior Asset Pack Bed + Bath Exports by H0ndred.zip](https://github.com/4ian/GDevelop/files/10542848/Mini.Interior.Asset.Pack.Bed.%2B.Bath.Exports.by.H0ndred.zip)

**Comment by Bouh** [comment]
@h0ndred You say this because you have seen "Tiled" on some objects?

![image](https://user-images.githubusercontent.com/1670670/215713865-72df8774-0139-4054-abcd-3ff8163f22c0.png)

There is two things that I also missed:
- The filename starting by `Tiled_` for generating a Tiled Sprite object is wrong. The prefix should be in small case. The tool made by @Entr0py404 doesn't make the difference, so I missed it in the filename validator. It's my bad.
- Like the filename is wrong, `Tiled` is recognized as the object name, and the rest of the filename as animations.
I fix all these things, and

**Comment by h0ndred** [comment]
@Bouh 
Yes. 
There also some minor things I'd change for better organization
For example, I renamed assets, moved some assets into animations rather than as individual objects > like for example the desk should have 3 animations and not 2. 

In which I hope the new zip file I provided should update as well as all the corrections for those tiled objects (I took the time to rename those tiled objects from "Tiled_" to "tiled") and the correct Thumbnail.

[Mini Interior Asset Pack Bed + Bath Exports by H0ndred.zip](https://github.com/4ian/GDevelop/files/10544800/Mini.Interior.Asset.Pack.Bed.%2B.Bath.Exports.by.H0ndred.zip)

Let me know if this file can help you or at least... do less work. I feel pretty bad about this since you spent the time to send them to the store. I am really sorry.

**Comment by Bouh** [comment]
I can't use your zip.
Here is the folder we've on the asset store for your pack, could you make the change inside then reupload the zip here please?
[Mini Interior Bed And Bath.zip](https://github.com/4ian/GDevelop/files/10544900/Mini.Interior.Bed.And.Bath.zip)

**Comment by h0ndred** [comment]
@Bouh 
Of course, Let me do that for you.
Hopefully this works :D
[Mini.Interior.Bed.And.Bath.zip](https://github.com/4ian/GDevelop/files/10544976/Mini.Interior.Bed.And.Bath.zip)

**Comment by Bouh** [comment]
> @Bouh Of course, Let me do that for you. Hopefully this works :D
> 
> [Mini Interior Bed And Bath.zip](https://github.com/4ian/GDevelop/files/10545010/Mini.Interior.Bed.And.Bath.zip) (updated)

Thx, you are so fast!
Could you check your pack witht Entropy's tools please:
Be sure to click on all objects, then check the name, and the animations of these objects.

The Entropy's tools: https://github.com/Entr0py404/GDev-Asset-Store-Tool/releases/tag/v1.4.1

### How to use
Open it and click **Tools**
![image](https://user-images.githubusercontent.com/1670670/215727178-b4c1cb3a-bf44-40fd-bc12-d16329db25d4.png)

Then **Asset Store Preview**
![image](https://user-images.githubusercontent.com/1670670/215727266-f7ad8e75-efec-493d-9398-8efee0b79191.png)

Open the folder, and visualize, click on object to see their animations.
![image](https://user-images.githubusercontent.com/1670670/215727610-e4d0df0c-7093-4566-8887-cb6e6a18c92a.png)


And make adjustement in the folder if needed.

**Comment by h0ndred** [comment]
@Bouh 
I rechecked them again and everything looks good!
Thank you for responding to me quickly!

**Comment by Bouh** [comment]
Alright, I merged the changes, I hope everything is good :)

**Comment by h0ndred** [comment]
@Bouh 
It's perfect, you are amazing for being so quick. And I apologize for my over sight! 

And thank you @Entr0py404 for taking the time to package my files the first time around. Your tool is a life savor!
