### ISSUE TITLE
please just undo the ui changes to the ide

### ISSUE THREAD

**Issue by Noah12317** [4ian/GDevelop#4694]
Its very painful to look at, and i dont know what im looking at anymore. the ui looks like wingdings. ✋︎⧫︎ ●︎♓︎⧫︎⧫︎♏︎❒︎♋︎●︎●︎⍓︎ ●︎□︎□︎🙵⬧︎ ●︎♓︎🙵♏︎ ⬥︎♓︎■︎♑︎♎︎♓︎■︎♑︎⬧︎. We need the old ui back, or maybe make it toggleable. either way this really hurts my productivity, and i greatly need the old ui back

**Comment by Bouh** [comment]
Thank you for sharing your concerns about the new user interface of the app. We understand that it can be frustrating to encounter changes to an interface that you are used to. However, we want to assure you that the new interface was implemented with the intention of improving the overall user experience. We apologize if the transition has caused any difficulties for you.

We understand that some users may prefer the old interface, but unfortunately, it is not currently possible to toggle between the two or to revert back to the old interface. We have closed the issue related to this matter as it is not something that can be implemented at this time. We hope that you will continue to use the app and give the new interface a chance.

If you have any further feedback or suggestions, please don't hesitate to let us know on [the forum ](https://forum.gdevelop-app.com/)or on the [github discussion](https://github.com/4ian/GDevelop/discussions)s, we try to keep the Github for the technical issues.
Thank you for your understanding and for using our app.
