### ISSUE TITLE
Loading a non-existing storage breaks storage features

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4699]
More hours wasted on the simplest things... If someone knows why I'm such a bug magnet, I'll be happy to know! 
This simplified snippet never creates any storage:
![image](https://user-images.githubusercontent.com/25978830/208166799-13bae302-6251-4f85-829f-05886e89ae04.png)

Expected result: loading fails because the named storage doesn't exist, but the write action should still execute... no?

GDevelop v153

**Comment by 4ian** [comment]
Once the storage is loaded in memory, you must use the action to actually write permanently, "to the disk" your changes. Otherwise, things will stay in memory.
Have you used it? If not give it a try.

Or simpler: don't use the first action, which seems not to do what you expect.

**Comment by PascalLadalle** [comment]
So the loading doesn't fail. Once I call it, it is created+opened if it doesn't exist, like variables (but unlike timers, since the somewhat recent change).
I expected the storage to be visible in the dev tools if it had been created, even if empty, but it remains hidden in some buffer until it's "closed". All much clearer now. 😌 
I guess the terminology didn't help my confusion, storage/memory, load/open, write/close...
Either way, thanks! 🙏
