### ISSUE TITLE
Cannot change the opacity (alpha) of grid on an external layout

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4700]
## Describe the bug

Cannot change the opacity (alpha) of the grid on an external layout

## To Reproduce

Try to change the alpha (opacity) of the grid.  I will revert back to the previous setting (0.8).

https://user-images.githubusercontent.com/8879811/208245570-c7b59e3f-b399-41dc-88d2-f7ee692b1318.mp4

## Other details

Windows 11
GDevelop 5.1.153

**Comment by AlexandreSi** [comment]
Hi @tristanbob!
Thanks for reporting that!
PascalLadalle already spotted this (https://github.com/4ian/GDevelop/issues/4702), it was fixed earlier this week and will be available in the next release!

**Comment by tristanbob** [comment]
We did not report the same problem.  Mine only affected external layouts and it was the opacity value that didn't change. (I will verify the next build fixes this)

**Comment by AlexandreSi** [comment]
Sorry I meant those 2 issues share the same root cause.
I just tested it with my fix and it works. Unless I missed something, I'll let you check!
