### ISSUE TITLE
Close project and exit GDevelop labelled incorrectly - MacOS

### ISSUE THREAD

**Issue by Declan-Reid** [4ian/GDevelop#4708]
## Describe the bug
In the hamburger icon menu in the top left, the options Close Project and Exit GDevelop (at least on mac) appear to have the incorrect key combos.

## To Reproduce
1. Go to the hamburger icon menu in the top left of the window.
2. Click on File
3. Find Close Project and Exit GDevelop
4. Notice the key combos are wrong

<img width="305" alt="image" src="https://user-images.githubusercontent.com/80745367/208270704-3be17700-333f-4c58-9e0a-f21b50839a77.png">

## Other details
- MacOS 13.0
- GDevelop 5.1.153 Desktop

**Comment by ClementPasteau** [comment]
Thanks for reporting @Declan-Reid 

To add more details:

- the shortcut CMD+Q closes GDevelop (and is labeled under "Close Project")
- the shortcut CMD+SHIFT+Q closes the MacOS Session (and is labeled under "Exit GDevelop")

Note that the default MacOS shortcut says CMD+Q = Exit GDevelop
![image](https://user-images.githubusercontent.com/4895034/208377568-5372aaa5-8e6e-41a0-b810-81b5a176d09b.png)
