### ISSUE TITLE
Objects invisible in Objects Editor - OSX 10.11.6

### ISSUE THREAD

**Issue by andreikru** [4ian/GDevelop#474]
Hi,

Can't see the objects in the objects editor. Objects are there as I can click on them and add to scene and edit them if I figure out where are, as I cant see them.

I've installed last Java, and I don't know what els to do, but I can work with GDevelop...

Thanks a lot!!!

![captura de pantalla 2018-04-20 a les 10 25 36](https://user-images.githubusercontent.com/38554688/39038851-b9909270-4484-11e8-82e9-88a43ebd3e37.png)

**Comment by 4ian** [comment]
That's really strange. Can you try to move/resize the window a bit? Is it working on the web app? (https://editor.gdevelop-app.com)

**Comment by andreikru** [comment]
Moving/resizing not fix the problem. And yes it is working well on the web app. Yeah is really strange...

![captura de pantalla 2018-04-20 a les 10 57 12](https://user-images.githubusercontent.com/38554688/39041476-1e51f722-4489-11e8-9dd2-cee296a6728d.png)

**Comment by 4ian** [comment]
Can you try with Chrome?

**Comment by andreikru** [comment]
The web app is working well in Firefox and Chrome, not working in Safari, cant even start a project.

![captura de pantalla 2018-04-20 a les 12 00 24](https://user-images.githubusercontent.com/38554688/39044977-f3c44a60-4491-11e8-9b91-699805d8048b.png)

**Comment by Nnarol** [comment]
The problem of GDevelop not working in Safari might very well be a different one from objects being invisible in the objects editor.

Could the problem in the topic have to do with theming? I couldn't help but notice you using the dark theme in those pictures where you refer to the issue.

If the issue still persists, would you mind trying to use the default light theme for a while and see if it changes things for you? Also: does this consistently happen or only a couple of times?

GD 5 has gone through a lot of changes in the last month - does the issue persist in the latest beta?

**Comment by andreikru** [comment]
Thanks! But using the light theme and latest version don't solve it. Thanks anyway!

**Comment by Silver-Streak** [comment]
@andreikru  This is a very old issue, just checking in if this is still occurring with the current released versions (or any version since b100, really). Is this still happening?

This thread will be closed in 30 days or if confirmation is received that it is no longer happening.

**Comment by 4ian** [comment]
Pretty sure this was a problem fixed a few dozens beta ago. Closing now! :)
