### ISSUE TITLE
Error when trying to download particle emitter objects from asset store [version 5.1.154]

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4743]
## Describe the bug

Error when trying to download particle emitter objects from the asset store. This affects 5.1.154 but does NOT affect 5.1.153.

## To Reproduce

1. Open Desktop install of 5.1.154
2. Open Asset Store and try to add a particle emitter object
3. See this error message:

![Screenshot 2022-12-24 231200](https://user-images.githubusercontent.com/8879811/209458770-5bfc4442-d514-465d-b684-9f84a434965e.png)

## Other details

* Windows 10
* GDevelop 5.1.154

**Comment by ClementPasteau** [comment]
Thanks for reporting @tristanbob this is now fixed 👍
