### ISSUE TITLE
Pinch extension hangs

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4748]
Using the Pinch extension in any project seems to hang the preview, but the same works fine in v.153.
This was the events sheet when I compared 153 and 154.
![image](https://user-images.githubusercontent.com/25978830/209547975-e6fa21c9-141a-4769-bb1a-a8ff7d418800.png)
It looks like the text scrolling pauses at the first pinch, resumes when I release the pinch, and the game hangs for good at the second pinch.

I don't know how to check the console of a network preview. 🤷 

[source](https://forum.gdevelop.io/t/pinch-extension-bug-or-maybe-just-with-the-update/43983)

**Comment by ClementPasteau** [comment]
Thanks for reporting this.
I believe this has been spotted and code that introduced the issue was reverted in #4746 
We'll publish a new release asap

**Comment by ClementPasteau** [comment]
I believe this is now fixed, closing this issue. If it's still the case, feel free to reopen it @PascalLadalle
