### ISSUE TITLE
Incompatibility with Node.js v17+

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#4756]
## Describe the bug
When running with Node.js v17+, we get `Error: error:0308010c:digital envelope routines::unsupported` when doing `npm start`.

## To Reproduce
1. Use Node.js v17+
2. `cd newIDE/app && npm install && npm start`

## Other details

* To workaround, we can replace: 
  `"start": "npm run import-resources && npm run make-version-metadata && react-scripts start",`
  by:
  `"start": "npm run import-resources && npm run make-version-metadata && react-scripts --openssl-legacy-provider --no-experimental-fetch start",`
  in `newIDE/app/package.json`.

* But we should upgrade create-react-app for a long term fix, because the problem is coming from webpack: https://github.com/facebook/create-react-app/issues/11562

**Comment by tristanbob** [comment]
Do you want to include the requirement to also have: `--no-experimental-fetch` on that same line?  This is what works for me:

`"start": "npm run import-resources && npm run make-version-metadata && react-scripts --openssl-legacy-provider --no-experimental-fetch start",`

**Comment by 4ian** [comment]
Updated, thanks!
