### ISSUE TITLE
Boom Asset Pack

### ISSUE THREAD

**Issue by RamPlayzTheEpic** [4ian/GDevelop#4761]
BEFORE opening a new submission, please make sure that you:

- You have packaged the asset pack according [these rules](https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store). Otherwise, your package may be rejected or we will ask you to do the changes.

## Description
[Boom.zip](https://github.com/4ian/GDevelop/files/10320087/Boom.zip)

- License: CC By Sa 4.0
- Author: RamPlayzTheEpic
- Link to the original website:
- Zip file: [Boom.zip](https://github.com/4ian/GDevelop/files/10320087/Boom.zip)

**Comment by Bouh** [comment]
Hello,
The pack is not of sufficient quality to be included in the asset store.
