### ISSUE TITLE
Colision not following the object position

### ISSUE THREAD

**Issue by Lufims** [4ian/GDevelop#4762]
## Describe the bug
When I use an event to change the position of an object to the border of a camera, the colision does not follow it

## To Reproduce
Use this events:
![events](https://user-images.githubusercontent.com/73536178/209973296-19c9325a-9269-444f-bc4a-fc109418c2dc.png)

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
Windows 7
Gdevelop Version: 5.1.155
* Add any other context about the problem here.

**Comment by AlexandreSi** [comment]
Hi @Lufims 
Thanks for taking the time to report this.
Would it be possible to save a minimal version of your project with the issue you're mentioning, and join it to the issue so that it's easier for us to debug?

**Comment by Lufims** [comment]
How do i save a minimal version of the project?

**Comment by Lufims** [comment]
> Hi @Lufims Thanks for taking the time to report this. Would it be possible to save a minimal version of your project with the issue you're mentioning, and join it to the issue so that it's easier for us to debug?

It's this?
https://liluo.io/games/32af8372-0c33-471a-96e1-f455b43581b3

**Comment by Lufims** [comment]
> Hi @Lufims Thanks for taking the time to report this. Would it be possible to save a minimal version of your project with the issue you're mentioning, and join it to the issue so that it's easier for us to debug?

Or this? (that's the project folder)
https://www.mediafire.com/file/v0cr1r4zba804mt/FiveNightsAtMultiFreddy.rar/file

**Comment by AlexandreSi** [comment]
The second one! I'll have a look in the next days thanks.
