### ISSUE TITLE
The rendering is making the game lag

### ISSUE THREAD

**Issue by Lufims** [4ian/GDevelop#4763]
## Describe the bug
The render engine (I think it's that, idk), is slow, at least on my pc (my pc sucks, so it's because of that), but, my pc can run 3d games like morrowind, star wars battlefront 2 (2005), star wars Kotor, terraria (2d), and other things, but for some reason with a 2d game engine, it runs slow.

## To Reproduce
Open the engine
![render](https://user-images.githubusercontent.com/73536178/209974857-3f3409e2-9fdb-4e90-b017-155b9f26e49f.png)

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
Windows 7
5.1.155

PC---------
OS: Windows 7
RAM: 4Gb
Video card: Doesn't have, just a integrated chipset that is: Intel(R) 82945G Express Chipset Family
CPU: Pentium(R) Dual-Core CPU E5300 @ 2.60GHz
Other things------
Opengl: 1.4
DirectX: 9
Shader Model: 2.0

**Comment by Silver-Streak** [comment]
Your screenshot contradicts your issue, unfortunately.

 1 frame in a 60fps game is 16ms. In your screenshot your rendee time for graphics is 0.49ms, less than 1/16th the time of 1 frame of a 60fps game.

At least from the screenshot you provided, the engine itself is performing at better than 60fps speed.

**Comment by Lufims** [comment]
> Your screenshot contradicts your issue, unfortunately.
> 
> 1 frame in a 60fps game is 16ms. In your screenshot your rendee time for graphics is 0.49ms, less than 1/16th the time of 1 frame of a 60fps game.
> 
> At least from the screenshot you provided, the engine itself is performing at better than 60fps speed.

So, why my game is laggy, i even tested it after I compiled, but it's laggy too, and it's just when have too much pixels of an imagem on the screen, and it's the same for sprites and tilesets

**Comment by Silver-Streak** [comment]
> So, why my game is laggy, i even tested it after I compiled, but it's laggy too, and it's just when have too much pixels of an imagem on the screen, and it's the same for sprites and tilesets

Sadly, I don't think anyone is going to be able to identify your game performance issues specifically. Your debugger is showing that the engine is running normally at full speed.

If I were to hazard a guess, I wouldn't be surprised if your GPU doesn't support WebGL fully (I believe that requires OpenGL ES 3.0 support), or is blacklisted to not allow WebGL in Chromium.  This means that your PC will fallback to Canvas mode, which is substantially slower and doesn't support things like the shaders/layer effects..

**Comment by Lufims** [comment]
> > So, why my game is laggy, i even tested it after I compiled, but it's laggy too, and it's just when have too much pixels of an imagem on the screen, and it's the same for sprites and tilesets
> 
> Sadly, I don't think anyone is going to be able to identify your game performance issues specifically. Your debugger is showing that the engine is running normally at full speed.
> 
> If I were to hazard a guess, I wouldn't be surprised if your GPU doesn't support WebGL fully (I believe that requires OpenGL ES 3.0 support), or is blacklisted to not allow WebGL in Chromium. This means that your PC will fallback to Canvas mode, which is substantially slower and doesn't support things like the shaders/layer effects..

yeah, I think that's it, my pc doesn't support Opengl ES 3.0, I think it supports only Opengl ES 2.0 (I think), and other thing that happened is when I put some lights on the scene and started the preview, the lights were wrong, I don't know how to explain, but, they were wrong and not working properly, so, I think is what you said.

**Comment by Bouh** [comment]
The lights use the shader of the graphics card, and indeed as your hardware does not support the right version there are problems.
I close the iisue because this is a hardware issue. And that the debugger shows that everything runs fine on the application side.
Thank you for your input @Silver-Streak !
