### ISSUE TITLE
Animated coin Pack by DanRockstreet

### ISSUE THREAD

**Issue by DanRockstreet** [4ian/GDevelop#4784]
Animated coin pack with coins in different materials (gold, silver, bronze, white) in three different resolutions (16x16, 32x32 64x64).
Modelled by myself and rendered in Blender.

- License: CC-BY 4.0
- Author: Dan Rockstreet
- Link to the original website: https://www.deviantart.com/danrockstreet/art/CoinPack-943911711
- Zip file:  [CoinPack.zip](https://github.com/4ian/GDevelop/files/10351298/CoinPack.zip)

![Overview_sml](https://user-images.githubusercontent.com/121951029/210758243-9fc6eca6-6fb5-4f78-88d9-69c0523185bf.png)

**Comment by Bouh** [comment]
Hello,
Thank you for this asset proposal!

- 4 elements is not much for a pack. 
This makes me think of a poker or casino pack (probably because of the green and yellow background).
It would be possible to extend the number of assets to create a more complete pack?

- You don't need to put several resolutions, the biggest one you have is enough for the asset store, the lower resolutions don't need to be included.

**Comment by DanRockstreet** [comment]
Hi Bouh,

I appreciate your fast response and explanations. Being my first submission, I will think about adding further assets.

Good to know about keeping one resolution only. I hope the 64x64 pixel size is acceptable - the upload information is not specific with recommendations.

**Comment by DanRockstreet** [comment]
Hi @Bouh 
I hope this is better..

Assorted set of animated coins, card suits, jetons (in 64×64 pixel size) and a couple of background tiles (in 128×128 pixel size).
Modelled by myself and rendered in Blender.

    License: CC-BY 4.0
    Author: Dan Rockstreet
    Link to the original website: https://www.deviantart.com/danrockstreet/art/GamePack-944104310
    Zip file: [GamePack.zip](https://github.com/4ian/GDevelop/files/10362731/GamePack.zip)

**Comment by h0ndred** [comment]
@DanRockstreet 
I was hoping to help package the files but I see that you already did!

I can only mention that your folders are plural > you should name all your folders with singulars.
Folders also act as tags themselves: https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store (in the tag section > green box)

Thank you for making the assets!

**Comment by Bouh** [comment]
Hi @DanRockstreet nice job on it!

To be able to add it into the Asset Store, we need:
- A name for this pack, choose a unique name not too common.
- A thumbnail, in 16/9, 1024x768 is fine.


On my side I need to fix few things:
- Remove the purials on tags and on folder names.
- Remove tags that are in double with the objects names.
- Add spaces in filenames (for instance from `CardSuitClubs` to `Card Suit Clubs`), same on all objects.
- Change the index of animations frames starting from 0 to 1.
- Add an underscore before the index.
- Removing useless 0 in index (for instance from `CardSuitClubs01.png` to `Card Suit Clubs_1.png` )


### What is correct
- METADATA.json files for objects are perfect!
- The use of `tiled_` in filenames for the objects.
- The animation loop well.
- The uses of tags.

**Comment by DanRockstreet** [comment]
Hey @Bouh / @h0ndred !

I appreciate your efforts to review the files :-)

Let' see if I got everything right...

- Name: "Casino Craze"
- Thumbnail included in ZIP file
- removed plurals from names and folder names
- added spaces in filenames wherever required
- changed starting animation index from 0 to 1 and removed preceding "0"

I hope you have now less work to do :-)

License: CC-BY 4.0
Author: Dan Rockstreet
Link to the original website: https://www.deviantart.com/danrockstreet/art/GamePack-944104310
ZIP file: [CasinoCraze.zip](https://github.com/4ian/GDevelop/files/10561859/CasinoCraze.zip)

**Comment by Bouh** [comment]
Hi the pack has been added!

Here how it looks like:

![image](https://user-images.githubusercontent.com/1670670/219951127-9ec5eef6-59c1-4e02-8162-1bfbbb80651a.png)
![image](https://user-images.githubusercontent.com/1670670/219951134-84539131-8b6e-40d2-9e62-93a1ada11555.png)
