### ISSUE TITLE
Group name with numbers on XML

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#479]
In native, overwriting a value in a group with a name starting with a number (e.g. "root/1st") causes the value not being replaced but duplicated, check it here: http://forum.compilgames.net/viewtopic.php?f=19&t=9876
I can't get the exact source of the problem, probably something internal in TinyXML, and I don't know if you can fix it or want to add a warning in the instructions (web versions works fine).

**Comment by 4ian** [comment]
So strange! Maybe something internal to TinyXML yes :/ Not sure what is going on.

**Comment by 4ian** [comment]
Closing as outdated.
