### ISSUE TITLE
Allow players to authenticate in-game option in new project is not usable offline.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4801]
## Describe the bug
When we're offline and as the new option 
`Allow players to authenticate in-game` is enabled when we create a new project, an error appear because the game template is fetched online.

Due to this line:
https://github.com/4ian/GDevelop/pull/4714/files#diff-ec6adc1283a0cb806b41410da495b45502d4acfe3f92085971d1942749e8f51fR62

![image](https://user-images.githubusercontent.com/1670670/211205413-02443b95-d3b1-4c75-bbe0-120984a243f3.png)

## Other details
5.1.155 (editor full version: 5.1.155-ecbafe60d1274b3a71429decd84400f26ba9fe56, core version: 4.0.99-0-release)

**Comment by ClementPasteau** [comment]
good catch @Bouh fixing it now
