### ISSUE TITLE
Text input z-order issue?

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4827]
I noticed that my fading to black doesn't work properly in a scene where I have the new text input object.
So I reproduced the issue in the example project, and indeed, the textboxes stay on top of my black tiled sprite, even though its z-order is higher.
![image](https://user-images.githubusercontent.com/25978830/212556788-a674ade0-c95a-4007-ba01-e08c93591af0.png)

GDevelop v155 Windows10

**Comment by 4ian** [comment]
This is indeed a limitation of the way text input works: 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/1280130/212632299-3f2b0d07-d992-4a7c-b95c-3b68a2941da0.png">

(I know it's not ideal, but there is no easy way to workaround this)

**Comment by 4ian** [comment]
Sounds good then 👍
