### ISSUE TITLE
Cannot close input box by clicking away in the Web app

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4828]
In the Web app, when you open any text box in the events sheet, the only way to close it is to press Escape or open another box.
Clicking elsewhere should close the box.
![image](https://user-images.githubusercontent.com/25978830/212557010-1398026b-ba9c-4092-afd0-01a4f15422b8.png)

Confirmed on Chrome.
[source](https://forum.gdevelop.io/t/event-value-input-box-gets-stuck-on-screen-web-ios/44215)

**Comment by 4ian** [comment]
> Confirmed on Chrome.

I've seen in the original thread that it was on iOS - this is important information to include here too. I've tried to reproduce this on Chrome but it seems to work correctly. Can you confirm your Chrome version, operating system and if this is a touchscreen device or not? :)

**Comment by PascalLadalle** [comment]
Ah. Windows 10 as usual, Chrome is up-to-date. No touch screen.
![image](https://user-images.githubusercontent.com/25978830/212568409-6d52220c-67d0-4037-86dc-1b8e6839f7e1.png)

**Comment by 4ian** [comment]
Interesting, I'm on Chrome 108. I'll update or try on Windows. I've been able to reproduce this on iOS anyway, but still good to understand where this difference in behavior is coming from!

**Comment by 4ian** [comment]
Interestingly, Chrome 109 did break indeed this popover.
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/1280130/212680517-a9702685-a481-4652-8765-338648114327.png">
