### ISSUE TITLE
update 33 object points are bugged for me (linux)

### ISSUE THREAD

**Issue by mdlsvensson** [4ian/GDevelop#484]
hi I screenshot the point bug here, this is how it shows for me on linux:
http://i.imgur.com/fA42zXL.png

**Comment by blurymind** [comment]
It looks like it's not finding the path to the icon for some reason

**Comment by 4ian** [comment]
No problem! Part of the benefits of working on GDevelop 5 is that I can release new versions very quickly compared to GDevelop 4, which is perfect to quickly iterate on new features or fix bugs like this :)
Thanks for getting a subscription! Much appreciated! 💝
