### ISSUE TITLE
Event “the device has a touchscreen” on a regular PC

### ISSUE THREAD

**Issue by NSobolew** [4ian/GDevelop#4856]
OS: Windows 10
Browser: Chrome, Vivaldi and probably all browser based on it, Firefox
GDevelop version: 156
On a regular PC with regular monitor without a touchscreen the “the device has a touchscreen” event determines the Touchscreen

![1](https://user-images.githubusercontent.com/7355002/213869984-e0e5765e-592c-4ce3-a1ef-a2ec39bf4dbd.png)
![2](https://user-images.githubusercontent.com/7355002/213869990-97446ff0-51c5-41c7-870d-530053ef55a7.png)
![3](https://user-images.githubusercontent.com/7355002/213869998-90fd5a9c-6ce0-4ef2-bdb0-fb01a67ad170.png)

**Comment by NSobolew** [comment]
I first wrote that this bug appears on the Chrome browser and everything based on it, but the next time I tried the Firefox browser, the bug also

**Comment by danired** [comment]
Hi @NSobolew ,
Personally I can't reproduce it. I attach you my demo project and a screenshot

[Demo Project.zip](https://github.com/4ian/GDevelop/files/10473296/Test.zip)

![image](https://user-images.githubusercontent.com/21989259/213891544-6ebde426-808d-4138-aaf1-a16b82e89064.png)

**Comment by NSobolew** [comment]
@danired In your demo, I also determine the presence of a touchscreen

**Comment by NSobolew** [comment]
I remembered that recently there was a Windows update and decided to check if it was the case, and yes, in the information about the system it showed support for the touchscreen, and after rebooting the PC it disappeared, but before that I had already turned off the PC for the night and the bug appeared after that, close the topic

**Comment by danired** [comment]
Good! My next suggestion was to tell you to try it in other Computer. Good you found it
