### ISSUE TITLE
the "use same points for all animations" switch is bugged on linux (at least)

### ISSUE THREAD

**Issue by mdlsvensson** [4ian/GDevelop#486]
http://i.imgur.com/qx1Zu90.png
all of the area that is screenshotted is clickable, which makes me hit these switches by mistake all the time. Each of the switches are clickable in a horizontinal line, for the length of the screenshot.

**Comment by 4ian** [comment]
It's a "feature" to be able to toggle a switch by clicking on their labels (same for checkboxes).
I think that if you're hitting them all the time, it's maybe that there is a better interface or layout to find for this window. :)
