### ISSUE TITLE
IOS Keyboard

### ISSUE THREAD

**Issue by Akokoni12** [4ian/GDevelop#4867]
Hi there,
I built a game in Gdevelop 5 and wanted to get a keyboard to pop up on an IOS Phone.
But for some reason the coding isnt working for Apple.
Android has no issues. But i need the game to be Apple Friendly. 
How do i fix this issue so it can work on all mobile devices?

**Comment by Bouh** [comment]
Hi @Akokoni12 
You should probably use the **text input** object.

We would like to keep Github for technical issues.
To get help with the creation we advise you to search and post [on the forum.](https://forum.gdevelop.io/)
