### ISSUE TITLE
Zoomin in editor should zoom towards mouse pointer.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#4890]
When zooming in in collision and points editor as well as other editor areas like physics collisions.

the zoom should zoom towards mouse pointer instead of upper left corner as it does now.

This is a common way on zooming in majority of software around and especially since the GDevelop Editor itself zooms towards mouse pointer so it would be consistent with functionality as well as a proper working mechanic.

**Comment by AlexandreSi** [comment]
I think I'll change the whole strategy about zoom in this part using css `transform` with `translate` and `scale` rather than the current strategy that positions the image relatively to the parent.
