### ISSUE TITLE
TileMapMask doesn't work with Tiled (1.9.2) exports

### ISSUE THREAD

**Issue by Dotrar** [4ian/GDevelop#4900]
Hey all. I don't know if I'm using this incorrectly or if it's broken. The wiki doesn't seem to be much help, so i will update that if it's missing anything.

Using GDevelop 5.1.157

I've made a map using tiled editor, both a tileset and tilemap. I can import this into GDevelop using the **TileMap** Object just fine:
![image](https://user-images.githubusercontent.com/1199335/216798768-e26785b5-dd5c-4c52-8374-6e921ca3f12f.png)

But I also want collisions; If I try to use the **TileMapMask** object with my original map file, I get a form validation error, but without the error message:

![image](https://user-images.githubusercontent.com/1199335/216798846-67249a31-b1cb-4520-aa29-2260c4268910.png)

I can copy the files, _then_ use them (this seems wrong, but no more error message)

![image](https://user-images.githubusercontent.com/1199335/216798913-d464a593-e0c4-4c68-9282-224d2b58931f.png)

and it still doesn't work ( I get red 'x' symbol on the scene).
![image](https://user-images.githubusercontent.com/1199335/216798968-4e90058c-516d-4b75-96f9-054e921aa994.png)

I have set the tile property (in the tileset) 
![image](https://user-images.githubusercontent.com/1199335/216799021-cf32f0fb-841c-4d77-a9ef-da1a82958b6a.png)

At this point i don't know what I'm missing. The TileMapMask says it only works for the tiled editor, but then it says that the tileset is optional, which is odd, considering the tileset is what encodes the tile classes.. besides that, I don't know what else I'm doing wrong?

Any help is appreciated.

**Comment by Silver-Streak** [comment]
Have you tried downloading the platformer with tilemap example and seeing if you can use those tilemap files in a new blank project? That may give an idea if something is going weird with your Tiled settings or the tilemap collision mask object.

**Comment by ReanimatorXP** [comment]
The same issue here. 
I've tried both: loading a tilemap with and without the embeded tileset - it's fine for a tilemap object, but a tilemap collision mask doesn't work (it's just highliting with red the "Tilemap JSON file" string and the string "This is the JSON file that was...")

As has been recommended, I've also tried the tilemap platformer example: while the downloaded project works as expected, when I create a new blank project and add a tilemap json-file from downloaded sample-project, the tilemap object works fine, but the tilemap collision mask doesn't.
![image](https://user-images.githubusercontent.com/24944063/217924692-5c44e189-4a45-4861-937b-afbfc60e7536.png)
![image](https://user-images.githubusercontent.com/24944063/217923358-ba2fafe4-d5da-4b5c-8a31-8cfd1f56acfb.png)
The version of GDevelop is 5.1.157

**Comment by Silver-Streak** [comment]
@D8H any insight on this one? I'm seeing rhis behavior to on tiled maps inserted as new objects. Seems to happen with whatever changes were made to the tilemap collision mask object that allows you to insert the tileset (which seems odd as it didn't used to need that info at all)

**Comment by D8H** [comment]
It doesn't seems linked to Tiled version. It's an issue with the cache system.

The issue seems to appear when the collision object doesn't have the same resource name as the tile map object.

**Comment by Dotrar** [comment]
Thanks so much guys! baller
