### ISSUE TITLE
Incorrect display of object positions in version 157

### ISSUE THREAD

**Issue by Jurfix** [4ian/GDevelop#4902]
Hello everyone, I found a very strange bug in the last update, for some reason, in the last update, the positions of objects are displayed incorrectly, i.e. some objects seem to have moved down a few pixels, I downloaded the 156 version, and everything is fine there, although before that I had already saved the project at 157. Now I will attach the screenshots.
![image](https://user-images.githubusercontent.com/64281856/216972764-a75a0f35-c453-4a94-917a-c1d826ffeedc.png)
![image](https://user-images.githubusercontent.com/64281856/216972773-7995c85b-56d8-4f3a-b846-ba142a31edd4.png)
The project file is fine, if I run it on the old version, the positions will be correct, although as I said, I already managed to save it on version 157

**Comment by Jurfix** [comment]
It seems that the problem is not in the position of the objects, but in their Z order, in version 157 they changed the overlay sequence, due to the fact that many objects were on the same coordinate

**Comment by D8H** [comment]
Yes, we changed the way z-order is sorted and it probably reversed the order for instances with the same z-order.
I think it's not a bug because if a game chooses to set the same z-order to instances, it means that the order doesn't matter.

**Comment by Jurfix** [comment]
> Yes, we changed the way z-order is sorted and it probably reversed the order for instances with the same z-order.
> I think it's not a bug because if a game chooses to set the same z-order to instances, it means that the order doesn't matter.

It’s just that before, when something was changed, then in old projects it remained the same so as not to break anything

**Comment by 4ian** [comment]
You're right that most of the time, we strive too ensure the game rendering and gameplay is not modified at all.
Here it turns out this is a rendering change but that was already "not guaranteed" in the past (in a sense, it worked out of luck). So you can "just" fix the Z order and it should work better.

Sorry for the time loss here! I think it's important we keep our change because this gives much greater performance for all games.

**Comment by Jurfix** [comment]
Yes, I already fixed it, lucky that only 3 sprites shifted, phew

**Comment by D8H** [comment]
I checked that there is no issue with the create action.

![image](https://user-images.githubusercontent.com/2611977/216980573-77051030-bf7e-446a-8fb8-125f607b307b.png)

The last instance created appears in front.

![image](https://user-images.githubusercontent.com/2611977/216980857-e0085b9f-4c3b-4e29-9361-e5408717882d.png)

**Comment by Jurfix** [comment]
> I checked that there is no issue with the create action.
> 
> ![image](https://user-images.githubusercontent.com/2611977/216980573-77051030-bf7e-446a-8fb8-125f607b307b.png)
> 
> The last created instance appears in front.
> 
> ![image](https://user-images.githubusercontent.com/2611977/216980857-e0085b9f-4c3b-4e29-9361-e5408717882d.png)

Yes it works correctly, but it forces old projects to change (adds new work in old completed work). For example, in my game about a submarine there is an explosion, an object is created under the explosion that can be picked up (this is how it worked in the previous version), and in the new version, this object is created on top of the explosion, but this is more logical from the side of events, because the last object is created after the first, but it's still annoying that I have to go through the whole game to find new visual bugs that weren't there before.
