### ISSUE TITLE
TileMapMasks Not being displayed in Gdevelop5

### ISSUE THREAD

**Issue by adibeu** [4ian/GDevelop#4924]
![Screenshot (61)](https://user-images.githubusercontent.com/77983157/218321541-7097ce3e-b8c6-4f5a-b018-3e3031fbf8a6.png)
 Tile map masks are shown as red error icons 
but they do work in game only and cannot be touched or moved except by going into the instances list 
(and they do not work as platforms if debug mode is enabled, but I think that is done by developers)
![Screenshot (62)](https://user-images.githubusercontent.com/77983157/218321612-86abf1c9-174a-4bd5-a967-c841a525cedf.png)
Although they do work in game
Tiled Version 1.9.2
Gdevelop is also on the latest version
and when I copy the files from the tiled example to a new project, the same problem occurs.

**Comment by D8H** [comment]
I'm closing the issue. Feel free to create a new one if you still have the issue.
