### ISSUE TITLE
Dual monitor fullscreen broken (possibly) 

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#495]
A review about Hyperspace Dogfights mentions an issue about running the game on a dual monitor setup where the game gets placed in between the monitors.

https://www.gamingonlinux.com/articles/hyperspace-dogfights-is-a-chaotic-challenging-and-fun-jet-combat-game-thats-now-out.11768

I don't know if it is related to GD or just the game and I can't reproduce it since I only have one monitor.
Can someone replicate this issue?

**Comment by Silver-Streak** [comment]
@4ian is this still an ongoing concern since it's for GD4, or are we good to close this out?

**Comment by 4ian** [comment]
Should be good as games are now on a different tech stack. Closing! :)
