### ISSUE TITLE
Add possibility to unset an object as global

### ISSUE THREAD

**Issue by AlexandreSi** [4ian/GDevelop#5065]
## Description

When one wants to use the same object in another scene (second level, menu scene), the first thing one thing might think is "Let's make this object global so that I can use it everywhere".

The user is then faced with a stressful alert "This action cannot be undone".
So one might think "That's a bad idea" or "What happens if I need it not to be global? Why would I need it not to be global? What are the implications?"
That might eventually end up in them thinking "I don't understand any of this, I suck at this"

## Solution suggested

Give the possibility to unset an object as global that would set the object as belonging to any layout/external layout/external events that refer to it.

## Alternatives considered

None that I see

**Comment by jack-ii** [comment]
+ show a warning/not allow making an object global during an object with the same name exists in another scene. That always causes problems.
