### ISSUE TITLE
Unintended tween behavior when scene is resumed

### ISSUE THREAD

**Issue by lhphr** [4ian/GDevelop#5097]
## Describe the bug
Resuming the scene changes some object parameters to the value of the last played tween which affected said parameters, even if the tween is already completed.

## To Reproduce
1. Tween some object parameter (object position is one visual way to see it).
2. Wait for the tween to finish, then change the object parameter to something else without using tweens.
3. Pause the scene and go to a different one.
4. Resume the scene by exiting the current one.
5. Object parameters are different.

[Small test project file showing the bug (uses position as example, but is replicable with other parameters)](https://github.com/4ian/GDevelop/files/10944749/oops.zip)

## Other details
OS: Windows 10 Pro 21H1
GDevelop version: 5.1.158, Desktop

**Comment by AlexandreSi** [comment]
Thanks for reporting this issue and thank you for the project, that was really helpful!

Here is the diagnostic:
- We store an object tween in a map:
https://github.com/4ian/GDevelop/blob/master/Extensions/TweenBehavior/tweenruntimebehavior.ts#L82
- When a tween finishes playing, we set the flag `hasFinished` to true.
  - Note that this flag is outside the Shifty instance.
  - Shifty itself stores a variable `_hasEnded` on its instance.
    https://jeremyckahn.github.io/shifty/doc/tweenable.js.html#line398

When we resume a scene, shifty is called to process all existing tweens. When doing so, shifty does not care if its tween instance has the `hasEnded` flag and processes it (See https://jeremyckahn.github.io/shifty/doc/tweenable.js.html#line120), making it take the target value of the tween.

I will check if this can be fixed/improved in shifty before trying to find a solution of our own.
