### ISSUE TITLE
Admob not working in direct android export

### ISSUE THREAD

**Issue by shadow4004** [4ian/GDevelop#512]
Hi, I'm using admob object in a game and exporting it through the one click android export feature. It doesn't show any kind of ads when I run the game. I've tried with both testing mode on and off. There are no other visible errors as I can see. What I'm thinking is that probably admob object doesn't work with direct android export. Is there anything I can do to fix this? Or should I export the game as a cordova project and build it through cordova manually? Also do you see ads or testing banner while previewing the game in gdevelop?

**Comment by 4ian** [comment]
For now you need to export through Cordova manually to add the admob plugin `com.google.cordova.admob`.
Sorry for the confusion! I have to add this to the one click android export.

**Comment by Lizard-13** [comment]
Can we close this one? :)

**Comment by 4ian** [comment]
Yes :D
