### ISSUE TITLE
Gdevelop Encountered an issue

### ISSUE THREAD

**Issue by LaserBeamerXX** [4ian/GDevelop#5141]
When I open Gdevelop it loads then goes a screen that says "Gdevelop Encountered an issue"

**Comment by AlexandreSi** [comment]
Hi @LaserBeamerXX,
thanks for taking the time to report this issue.
Could you open the developer tools, then the console and copy paste the errors that should have appeared?

**Comment by AlexandreSi** [comment]
Hi @LaserBeamerXX ,
Sorry for the inconvenience.
Could you give more info:

Were you logged in?
Were you working on a project and expected GDevelop to open the last project?
What is your GDevelop username?

**Comment by LaserBeamerXX** [comment]
It was my first time downloading it and when i launched the exe,  it
immediately went to the report screen

**Comment by Oxey405** [comment]
@LazerBeamerXX Can you tell me your config ? How much RAM do you have ? What's your CPU ? Do you have any other programs running in the background ? (anti-cheats or weird antiviruses may block GDevelop thinking it's a virus (while it's clearly not. You can even build from source if you do not trust the avaible build or just pass the app in virustotal). 
Do you have disk space left ?

**Comment by AlexandreSi** [comment]
@Oxey405 @LaserBeamerXX 
I think this will be fixed by #5170.
We will release the new version soon and this should disappear
