### ISSUE TITLE
Not able to redeem Fanatical 12 month purchase

### ISSUE THREAD

**Issue by ianwill93** [4ian/GDevelop#5209]
It seems like my 12 month code was initially accepted with the 1 month code I also purchased. Now that my 1 month is about to run out, I tried just canceling and adding my 12 month so I didn't forget to do it later. 

Well, Gdevelop won't accept my 12 month code anymore. Here's all it says: 
"This code was valid but can't be redeemed anymore. If this is unexpected, contact us or the code provider."

I reached out to Fanatical as well, but any ideas what's going on? I didn't see any support tab on the website so I'm putting this here.

**Comment by 4ian** [comment]
Hi! Please send your email and codes to hello@gdevelop.io and we'll sort that out :)
