### ISSUE TITLE
Stuck in a guided lesson.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#5210]
## Describe the bug

An user tell me he can't continue the **Improve background and camera** guided lesson.
He is on mobile.

He follow the highlighted instruction, but after doing the lesson is stuck, nothing more.
If he add a new condition or something else the same thing is asked, but he already did it.

(Note also the button android bar over the GDevelop interface)

![image](https://user-images.githubusercontent.com/1670670/230598565-5bcacdf4-906b-4dff-a152-41bdaff8a643.png)

Same He was stuck in the lesson: Scene multiplier at this step:
![image](https://user-images.githubusercontent.com/1670670/230598533-b32640e7-868f-42f9-bb57-96afc744d1ab.png)

## Other details
* Mobile app
* Realme 8, 5G
* Language in app: Polish

**Comment by lolakQ** [comment]
> ## Describe the bug
> 
> 
> An user tell me he can't continue the **Improve background and camera** guided lesson.
> He is on mobile.
> 
> He follow the highlighted instruction, but after doing the lesson is stuck, nothing more.
> If he add a new condition or something else the same thing is asked, but he already did it.
> 
> (Note also the button android bar over the GDevelop interface)
> 
> ![image](https://user-images.githubusercontent.com/1670670/230598565-5bcacdf4-906b-4dff-a152-41bdaff8a643.png)
> 
> 
> Same He was stuck in the lesson: Scene multiplier at this step:
> ![image](https://user-images.githubusercontent.com/1670670/230598533-b32640e7-868f-42f9-bb57-96afc744d1ab.png)
> 
> 
> 
> ## Other details
> * Mobile app
> * Realme 8, 5G
> * Language in app: Polish
> 
> 

![Screenshot_2023-04-29-13-31-10-25_f796d0b73ae29d70f704572c96be9923.jpg](https://user-images.githubusercontent.com/129084846/235300269-d13883b7-3a67-4305-b057-8518e5aca763.jpg)

After the latest update the app broke resolution/screen fit where it was fine before

**Comment by lolakQ** [comment]
> ## Describe the bug
> 
> 
> An user tell me he can't continue the **Improve background and camera** guided lesson.
> He is on mobile.
> 
> He follow the highlighted instruction, but after doing the lesson is stuck, nothing more.
> If he add a new condition or something else the same thing is asked, but he already did it.
> 
> (Note also the button android bar over the GDevelop interface)
> 
> ![image](https://user-images.githubusercontent.com/1670670/230598565-5bcacdf4-906b-4dff-a152-41bdaff8a643.png)
> 
> 
> Same He was stuck in the lesson: Scene multiplier at this step:
> ![image](https://user-images.githubusercontent.com/1670670/230598533-b32640e7-868f-42f9-bb57-96afc744d1ab.png)
> 
> 
> 
> ## Other details
> * Mobile app
> * Realme 8, 5G
> * Language in app: Polish
> 
> 

![Screenshot_2023-04-29-13-31-10-25_f796d0b73ae29d70f704572c96be9923.jpg](https://user-images.githubusercontent.com/129084846/235300269-d13883b7-3a67-4305-b057-8518e5aca763.jpg)

After the latest update the app broke resolution/screen fit where it was fine before

**Comment by lolakQ** [comment]
@Bouh everything works This turns out to be a translation error, what is in one language I have to look for in the other

**Comment by lolakQ** [comment]
@Bouh everything works This turns out to be a translation error, what is in one language I have to look for in the other
