### ISSUE TITLE
Tutorial Stuck on "Search for layer"

### ISSUE THREAD

**Issue by CRAWLER-V** [4ian/GDevelop#5238]
## Describe the bug
TUTORIAL STUCK on 56%: "Search for layer" and do not go over. The user cannot finisch the tutorial.

## To Reproduce
1. Go to 'Create and Publish a Fling game' Tutorial
2. Click on 'second box: 'enhance and public your game'
3. go to Event step, you have to create collision event for show "You win layer" so add action and
4. the tutorial remain STUCK on "Search for layer", the % of the tutorial is the 56%.
5. even if you select a layer action for yourselfe the turorial remai stuck on "Search for layer" and do no go over.

* SCREENSHOT:
https://snipboard.io/A8etIc.jpg

## Other details
* Windows 11 64bit with all last offical microsoft update
* GDevelop 5.1.160

**Comment by tristanbob** [comment]
I wonder if this is related to recent changes made to layer selection? @ClementPasteau

**Comment by 4ian** [comment]
I believe this is because the action "Show layer" was translated into your language and so does not show in your result. @ClementPasteau will take a look

**Comment by saierXP** [comment]
The problem still exists, the language is Simplified Chinese and in online editor  version.
`layer` in Chinese is `层` or `图层`.
![msedge_QrG3hK7xuw](https://github.com/4ian/GDevelop/assets/45038185/7e69bcf7-297e-4f93-a925-eb41a6537111)
![msedge_cSONdKLdII](https://github.com/4ian/GDevelop/assets/45038185/6891dfda-6c0d-42c7-a316-9eaa7f476ccc)
