### ISSUE TITLE
GDevelop Site encounters a bug when loading.

### ISSUE THREAD

**Issue by S133025828besd** [4ian/GDevelop#5258]
### Describe the bug

When I load up the site, it shows the interface for a brief second, then says it encountered an issue.

### Steps to reproduce

Load the site
[Screen recording 2023-04-25 10.36.20.webm](https://user-images.githubusercontent.com/117935328/234344222-5a505259-37cc-408a-8a40-a64706441317.webm)

### GDevelop platform

Desktop

### GDevelop version

Web Version

### Platform info

OS: ChromeOS
OS Version: Latest?
Browser(For Web): Chrome
Device(For Mobile): Chromebook

**Comment by AlexandreSi** [comment]
Hi,
Your browser might be using old resources that not compatible with the current version.
Try hard refreshing the page (with CTRL + F5 on Windows or Cmd + Shift + R on Mac) or opening the editor from a private window.
Please keep us informed if the issue persists.

**Comment by AlexandreSi** [comment]
Having no news from you, I'm closing your issue.
Thanks for taking the time to report it.
