### ISSUE TITLE
GDevelop crashing when launching preview

### ISSUE THREAD

**Issue by tjv189** [4ian/GDevelop#5265]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As of about 1 hour ago from the time of posting this, I've started encountering a bug in which the GDevelop Desktop app will fail to load the preview of my game.  After trying again, I get an error message in the editor seen in this screenshot:

![Capture13](https://user-images.githubusercontent.com/132099309/235235134-bd28a2eb-2c90-4300-8d3f-9ec3e9657b7d.PNG)

When I check the console, I see the following text:

![Capture14](https://user-images.githubusercontent.com/132099309/235235210-86b814b7-6e0e-4c23-b662-dae747851745.PNG)

I've tried uninstalling and reinstalling to no avail.  Again, everything worked perfectly fine with the engine until about an hour ago.

### Steps to reproduce

1. Open scene you wish to preview
2. Click on 'Preview' at the top of the screen
3. Nothing will happen, and the circle loading icon will usually get hung up or freeze on the screen.  No preview loads.
4. Error message (screenshot above) is displayed

### GDevelop platform

Desktop

### GDevelop version

5.1.160

### Platform info

OS: Windows
OS Version: Windows 10

### Additional context

As I said above, this error only started happening on my end about an hour before I submitted this bug report.  The engine has worked perfectly fine up to this point.

**Comment by ClementPasteau** [comment]
Hi @tjv189 thanks for reporting the issue and sending your files via mail.
I am suspecting that you have created an infinite loop in your events.

You may be "importing External Events" in a Scene and at the same time "importing events from the Scene" in your External Events.
Meaning that the engine keep sending the ball from one to the other, causing a crash.
You shouldn't need to "import events from the Scene" in your external events.

Can you check this is the issue?

**Comment by ClementPasteau** [comment]
Glad to hear you fixed it 👍 
We could prevent those kind of mistakes by giving a warning in the editor in case it happens.
But for the moment, I'll close this issue

**Comment by tjv189** [comment]
That would be a good little addition, to give a warning when this mistake is made and the game is trying to be previewed.  But for now, thank you and the issue is now closed!
________________________________
