### ISSUE TITLE
Editor encountered problem 

### ISSUE THREAD

**Issue by lokesh6651** [4ian/GDevelop#5289]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

"While using the GDevelop editor, I encountered a problem where something went wrong and I received an error message telling me to backup my game file and save my game. This issue occurred when I was trying to [insert the specific action you were performing when the bug occurred]. The error was automatically reported, but I wanted to report it on GitHub to make sure it's fixed."

### Steps to reproduce

![github issue](https://github.com/4ian/GDevelop/assets/128339551/00fe9c79-e990-451f-9f7d-0c198345733d)

### GDevelop platform

Desktop

### GDevelop version

5.1

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by AlexandreSi** [comment]
Hi, are you using the latest version (5.1.161) ?

**Comment by AlexandreSi** [comment]
Closing this issue since it most likely was due to the bug present in the 5.1.161 version.
