### ISSUE TITLE
Keyboard closes when modifying the map editor's grid alpha option 

### ISSUE THREAD

**Issue by rBok6** [4ian/GDevelop#5315]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When you try to change the alpha value of the grid on grid options the keyboard closes itself.

### Steps to reproduce

1. Tap on grid option
2. Tap on alpha value
3. Keyboard attempts to open but fails
4. The same happens with other values of the grid settings.
5. This only seems to happen on landscape mode but not on portrait mode.

### GDevelop platform

Mobile

### GDevelop version

5.1.162-mobile

### Platform info

<details>

*OS (e.g. Windows)
> Android 

*OS Version (e.g. Windows 10, macOS 10.15)*
> Android 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> 

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> Realme 7i

</details>

**Comment by AlexandreSi** [comment]
I tried to fix it giving more space to the dialog content.
Let's see if it works and keep this issue open until we find out.

**Comment by AlexandreSi** [comment]
The new version is out, if you have time to check it and see if the keyboards now opens in landscape when editing the color, it would be of a great help!

**Comment by rBok6** [comment]
> The new version is out, if you have time to check it and see if the keyboards now opens in landscape when editing the color, it would be of a great help!

I just tested the latest version and It seems everything is working correctly. Well done ✅.
