### ISSUE TITLE
If you place some 3D object, it will color the drop shadow effect on the 2D object.

### ISSUE THREAD

**Issue by Kyogo-5** [4ian/GDevelop#5316]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug
If you place some 3D object, it will color the drop shadow effect on the 2D object.
I thought it was due to fog, so I turned it on and off in the layer effects, but it didn't change, so it must be a bug.
I have changed the color of the lights and turned the effect on and off, but it does not change.

### Steps to reproduce

https://gd.games/games/b5ca557c-e788-45a1-8594-91bad92a6d33

### GDevelop platform

Desktop

### GDevelop version

5.1.162

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by AlexandreSi** [comment]
Hi @Kyogo-5,
Thanks for reporting this issue.
It should be fixed by https://github.com/4ian/GDevelop/pull/5314
We will release a new version this week.
