### ISSUE TITLE
[Update] Lucid Icon V1.2

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#5323]
## Description
+ Adds flat icons
+ 10 new icons

##Info
- License: CC0
- Author: Leo Red
- Link to the original website: https://leo-red.itch.io/lucid-icon-pack
- Zip file: 
[Lucid-V1.2-GDStore.zip](https://github.com/4ian/GDevelop/files/11525204/Lucid-V1.2-GDStore.zip)

![Preview-Flat](https://github.com/4ian/GDevelop/assets/73597906/91295954-3611-4a01-9578-dbf2b4ae9ab0)

**Comment by Bouh** [comment]
Hi,
Thanks, the files are now updated!
