### ISSUE TITLE
add export extention button to web editor

### ISSUE THREAD

**Issue by gabrielzv1233** [4ian/GDevelop#5345]
## Description

my problem is that i cant export an extension i made on the web version

## Solution suggested

add the export extension button to the web version of the editor

## Alternatives considered

i currently have to go to a friends house to export the extension, which is inconvenient

**Comment by AlexandreSi** [comment]
> i currently have to go to a friends house to export the extension, which is inconvenient

GDevelop is getting friends to see each other, that's an accomplishment!

Jokes put aside, that's indeed something that we should add, thanks for the idea!
