### ISSUE TITLE
Pac Man Free Asset Pack

### ISSUE THREAD

**Issue by TharunVigneswarPS** [4ian/GDevelop#5361]
BEFORE opening a new submission, please make sure that you:

- You have packaged the asset pack according to [these rules]([Pac Man.zip](https://github.com/4ian/GDevelop/files/11596444/Pac.Man.zip). Otherwise, your package may be rejected or we will ask you to make the changes.

## Description

- License: CC0 1.0 Universal
- Author: TharunVigneswar
- Link to the original website: http://creativecommons.org/publicdomain/zero/1.0
- Zip file:

**Comment by Bouh** [comment]
Hello @TharunVigneswarPS 

I'm not sure we can add this to the GDevelop asset store without a license from Namco Bandai how own the brand Pac Man.
