### ISSUE TITLE
Adding author UI/UX is non-optimal

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#5400]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Adding an author without typing fast enough results in the impossibility to finish typing due to the selector taking all of the screen size and not updating whilst the user is typing. See GIF for example :
![example of the bug](https://github.com/4ian/GDevelop/assets/61246500/34b2ba6c-8fa9-4def-b2a2-4a180620cb38)

The following behaviour is clearly non optimal.

### Steps to reproduce

1. Open any popup where you can enter someone else's GDevelop username as author
2. Type any username with a slow enough typing speed so that the selector shows up
3. You can't type the rest of the username anymore until you close and reopen and type fast enough...

### GDevelop platform

Desktop

### GDevelop version

5.1.164

### Platform info

<details>

System : Windows 11 22H2

CPU : i7 11th gen

RAM: 16Go

GPU : RTX 3060
</details>

### Additional context

I can make a PR to fix this no worries (but please acknowledge it anyways)

**Comment by tristanbob** [comment]
@Oxey405 I agree this is something that needs fixed.  

What is your plan? Limit the size of the pop-up modal?

If you fix this, you might look for other fields (such as Extension authors) that have a similar problem.

**Comment by AlexandreSi** [comment]
Oh yeah I noticed that but I forgot it right away, thanks for the reminder!
