### ISSUE TITLE
Sore Silk

### ISSUE THREAD

**Issue by bouddourachid** [4ian/GDevelop#5418]
#@BEFORE opening a new submission, please make sure that you:

- You have packaged the asset pack according [these rules](https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store). Otherwise, your package may be rejected or we will ask you to do the changes.

## Description

- License:
- Author:
- Link to the original website:
- Zip file:

**Comment by AlexandreSi** [comment]
Hi @bouddourachid, I'm closing this issue since it does not respect the suggested template.
You can open a new issue and fill out the different fields.

**Comment by bouddourachid** [comment]
hi alexandre all want is download gdevelop pleas who is download gdevelop

**Comment by AlexandreSi** [comment]
The download page is here: https://gdevelop.io/download
