### ISSUE TITLE
Platformer character climbing wall bug

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#5448]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

https://github.com/4ian/GDevelop/assets/81715237/84737567-3932-445b-88b2-ce750668f9c8

As you can see in the video, changing the platformer character (Width) while he is beside a platform object, and holding Right arrow (the wall direction), and holding Space to jump, the platformer character will jump again !
Even though he is not on the floor.

**My guess:**
Changing the platformer character width OR angle will cause this bug, because the platformer character object will collide with the platform (walls) and then the engine thinks the object is now on the floor and allow it to jump once again.

**To fix this:** simply by adding Empty condition, Action: separate Player object from floor object.

So my question is, why the engine don't have this action already running in its codes for the Platformer character behavior and the platform behavior ?
Having that will fix this bug.

### Steps to reproduce

1- Change platformer character object width continuously.
2- Add another platform object (wall).
3- In the preview, go to that wall and hold Right or Left arrow (wall direction), and hold Space to jump.

### GDevelop platform

Desktop

### GDevelop version

Latest released version

**Comment by VegeTato** [comment]
@D8H What you think ?

**Comment by D8H** [comment]
The issue is that the animation behavior change the collision mask and teleport it inside the wall.
An hidden object should be used as hit box.
