### ISSUE TITLE
The value modifier does not work as expected in the `Change the position of an object action`

### ISSUE THREAD

**Issue by st-Wook** [4ian/GDevelop#5456]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

In the action to change the X, Y position of an object, when I put a modifier in the part where the X, Y values are entered, it does not work as expected.

### Steps to reproduce

1. Create an object
2. Move the X position to 20
3. Create an action in the event to change the X, Y Position of the object created
4. Set the Modification's sign to -(subtract) for the X position
5. Enter 10 + 5 for the X position

![image](https://github.com/4ian/GDevelop/assets/88178296/af1047bc-52be-4cd0-9e87-8ae0d42672ac)

Expected result:
The X position moves by subtracting 10 + 5 from 20.

Actual result:
The X position moves by subtracting 10 from 20 and then adding 5.

### GDevelop platform

Web

### GDevelop version

5.2.166

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
> Windows 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Edge

</details>

**Comment by AlexandreSi** [comment]
Thanks for spotting that bug!
