### ISSUE TITLE
Bad collision bounds

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#548]
## Bug Description
On web platform, the fast bounds check before the real SAT collision algorithm fails if the Centre point is not at the center of the object. Sometimes (at certain angles) the collision gets discarded by the bounds.

## To Reproduce
1. Modify the Centre point of any sprite object, placing it far from the center
2. Add events to rotate the sprite and detect collisions with other objects
3. At specific angles the collision will fail

Test project:
[boundsBug.zip](https://github.com/4ian/GD/files/2166881/boundsBug.zip)

## Other details
* Web version only.
* Not sure why it happens in web only, the native code looks the same, maybe SFML does some background transformation to give the correct positions and sizes.
* To fix it we could increase the bounding width and height by a factor of 2 (the logical maximum offset, if the Centre is placed at e.g. (0;0) ). We could transform the Centre by the angle to get the real center position, but it would add two `sin` and a `cos` calculation on every collision check. PIXI and Cocos have the sprite bounds option, but doesn't seem very reliable.

EDIT: Please check my example project (I can't do it now), because I think the bug doesn't discard collisions only but also detect collisions when there aren't. If so the bug is present in the SAT algorithm too, using the same bad offset as polygon center.

**Comment by 4ian** [comment]
Thanks for the report!

> To fix it we could increase the bounding width and height by a factor of 2

That could be the solution, but I still wonder why it's not opening in native game engine. Could it be an issue like a mismatch/bad use of `getX` instead of `getX+getCenterX` or getDrawableX?
Or indeed an offset badly applied to SAT or generated collision polygons.

**Comment by blurymind** [comment]
The collision boxes seem to stop working when the object has been scaled

**Comment by 4ian** [comment]
Pull request incoming that should fix issues with collisions hitboxes. Includes tests, test game and benchmarks for performance :)
