### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Sleepyguygithub** [4ian/GDevelop#5480]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

when ever i download a behavior it crashes if possible please fix this bug

### Steps to reproduce

1.go to the project
2. download a new behavior 

### GDevelop platform

Desktop

### GDevelop version

5.1.159

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by AlexandreSi** [comment]
Hi @Sleepyguygithub 
Thanks for taking the time to report your issue.
You seem to be using an outdated version of GDevelop. Would it be possible to download the last version and try if you can download a behavior?
Here is the download page: https://gdevelop.io/fr-fr/download
