### ISSUE TITLE
Download / Update URL broken

### ISSUE THREAD

**Issue by GreyFrogGames** [4ian/GDevelop#5496]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

OS Downloads on website and updates within the app appear to be broken due to a bad URL.  From the website, when trying to download, you are given a github page with the broken URL - https://github.com/4ian/GDevelop/releases/download/v5.2.167/GDevelop-5-Setup-5.2.167.exe.  
The link should be 
https://github.com/4ian/GDevelop/releases/download/v5.2.167/GDevelop.5.Setup.5.2.167.exe.  This is a very subtle difference.  There is a dash after the word setup and it should be a period.    

### Steps to reproduce

Go to the website
Select any OS download
Observe the error
![broken_URL](https://github.com/4ian/GDevelop/assets/108141057/a3289f1b-168c-4f06-b427-8530be7102e6)

### GDevelop platform

Desktop

### GDevelop version

5.2.167

### Platform info

OS (Windows, Linux )
Website

**Comment by 4ian** [comment]
Thanks for reporting it! Seems like the latest binaries have indeed not been uploaded properly. This should be fixed now!
