### ISSUE TITLE
Music doesn't auto-play when opening a gd.games link, but does when using Preview

### ISSUE THREAD

**Issue by rbrammen** [4ian/GDevelop#5511]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello,

The bug is music doesn't auto-play when opening a gd.games link, but does when using Preview. The action I'm using is "{"000kind":"GDEVELOP_EventsAndInstructions_CLIPBOARD_KIND-jsBdHbLy912y8Rc","content":{"eventsList":[],"eventsCount":0,"actionsList":[{"type":{"value":"PlaySoundCanal"},"parameters":["","OpeningGameTheme.mp3","1","","GlobalVariable(MusicVolume)",""]}],"actionsCount":1,"conditionsList":[],"conditionsCount":0}}"

This works perfectly fine when I use preview and the music plays correctly when I navigate from my starting screen to any other screen, however it should auto-play to start. This was working fine until the latest GDevelop upgrade.

Regards!

### Steps to reproduce

1. Make a new scene.
2. Add an event to play sound on any channel, do trigger once.
3. Preview the game inside GDevelop to make sure it auto plays
4. Publish it to gd.games and open the link
5. Observe that the music doesn't auto-play as it should

### GDevelop platform

Desktop

### GDevelop version

5.2.168

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Hi @rbrammen.

First of all, if you could share with us a sample project to reproduce this issue, that would help us a lot.
Second, do you have the gd.games link so we can see the problem in action?

I created a simple project with 2 scenes, redirecting to the next one with a button, and starting the sound at beginning of scene.
This works fine.

Here are the events:
![image](https://github.com/4ian/GDevelop/assets/4895034/bf9bab34-3eea-4e51-8504-6a5aa06dc202)
![image](https://github.com/4ian/GDevelop/assets/4895034/05d5cb5a-56c1-4819-91b7-82ca2f1ac7bb)


Here is the link for my game:
https://gd.games/clem/taboo-veil?dev=true


How do you navigate from the first scene to the second? I suspect you do that before any interaction from the user (click on something) the music will not start. This is a global limitation from the web. (see https://developer.chrome.com/blog/autoplay/#new-behaviors)
This would explain why it works in preview and not on gd.games.

**Comment by rbrammen** [comment]
Oddly enough, it actually works now. Not sure what changed, but yeah the music plays on load now. 

Game link: https://gd.games/instant-builds/ade39aa6-af33-47e5-9cb4-562f84e43635

I think you can prob close this!

**Comment by ClementPasteau** [comment]
Thanks for the link @rbrammen.

I suspect that you have the problem I mentioned above.
You are playing the music as soon as the scene loads, which can be blocked sometimes by the browser if there hasn't been any interaction beforehand. (click, press..)
This will work sometimes, but not always.
If you want it to work 100% of the time, I'd recommend adding an intermediary step to force the user interacting with your game before playing the music.

I'll close the issue
