### ISSUE TITLE
Renaming Scenes and opening them gives errors

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#5518]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello! Me and my friend from Team6X6 the makers of "Golf Adventures!" have found a bug with renaming scenes that only exists on one of our projects, and unfortunately it's for the sequel of the game. We're unsure as to what causes this, as we couldn't pinpoint this to the file size nor the amount of scenes because we've had a project which has more scenes and a bigger file size compared to our current one.

Since we'd rather keep the project safe from potential game stealers as it is a huge game that we are working on, please send your email so I can send it to you. As a side note, Bouh has confirmed the bug is existing on his end as well and mentioned it might have something to do with refreshing.

Here is a video showcasing the bug:
https://github.com/4ian/GDevelop/assets/98941240/a8d4051f-4ef1-41bd-ba9c-92856dc7aa04

### Steps to reproduce

Renaming the scene and pressing Enter "doesn't change" the scene name, and opening the "scene" sends you to a non-existent scene with the message "No layout called (scene name) found!". The Project Manager and Save project buttons may show up twice.
Renaming the scene and immediately trying to rename it again will visually update the name of the scene, but you'll have to press the Rename button again if you want to rename it.

### GDevelop platform

Desktop

### GDevelop version

5.2.168

### Platform info

Windows 10
Version 10.0.19044 Build 19044

**Comment by Bouh** [comment]
Thanks for having report the bug here!
@team I have the project files if needed.

**Comment by ZachjuKamashi** [comment]
Renaming scenes now work as expected in this project, this was probably correlated with #5524 as we did have empty layers which are used for masking only
