### ISSUE TITLE
Extension behaviors (!) icon, is barely visible in light theme

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#5538]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As the title says, the extension behaviors are barely visible in GDevelop light theme,

In Dark theme, everything looks good.
![2023-08-04 16_46_30-Window](https://github.com/4ian/GDevelop/assets/81715237/f7e5d933-0aae-4032-afdd-0bea6bec0a35)

In Light theme, it's hard to see both, the (!) icon and the author names.
![2023-08-04 16_47_05-Window](https://github.com/4ian/GDevelop/assets/81715237/17395e77-20fb-4142-80eb-9bf506832713)

### Steps to reproduce

1- Open object behaviors.

### GDevelop platform

Desktop

### GDevelop version

Latest

**Comment by AlexandreSi** [comment]
Hi @VegeTato,
Thanks for taking the time to report this issue.
On my side, I see (i) icon in purple, that's weird you're seeing it in white:
<img width="492" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/1cdbd386-1db9-4e41-ae86-96698561dbb6">
(Don't mind the empty names, it's "normal")
Is there something appearing in the console?
If you switch to another theme and come back to the light theme, is it still displayed as white?

**Comment by VegeTato** [comment]
> Hi @VegeTato, Thanks for taking the time to report this issue. On my side, I see (i) icon in purple, that's weird you're seeing it in white: <img alt="image" width="492" src="https://user-images.githubusercontent.com/32449369/258771322-1cdbd386-1db9-4e41-ae86-96698561dbb6.png"> (Don't mind the empty names, it's "normal") Is there something appearing in the console? If you switch to another theme and come back to the light theme, is it still displayed as white?

> Is there something appearing in the console?

I don't understand, like windows notification ? Nothing showed, everything is normal.

> If you switch to another theme and come back to the light theme, is it still displayed as white?

https://github.com/4ian/GDevelop/assets/81715237/9744dc6b-64bc-46d9-9891-0333fdfa6ecc

**Comment by AlexandreSi** [comment]
Oh it's already fixed by @D8H, I'm closing this issue then
