### ISSUE TITLE
Missing character for color on theme template

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#5540]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Thanks to Entropy for finding this typo.

Current: 
```
      "even": {
        "background-color": {
          "value": "252525"
        }
      },
```

Should be:
```
      "even": {
        "background-color": {
          "value": "#252525"
        }
      },
```
Reference:
https://github.com/4ian/GDevelop/blob/075cc5a7aa838b3682a0cb990ef8daa6c0d7a05b/newIDE/app/scripts/theme-templates/theme.json#L566

### Steps to reproduce

See above.

### GDevelop platform

Desktop

### GDevelop version

5.2.169

**Comment by ClementPasteau** [comment]
@tristanbob can you open your PR on this repository so we can merge it? :)
