### ISSUE TITLE
Collision not working after deleting frame

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#5541]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As the title says, The collision does not work after deleting the sprite Frame and leave the animation empty.
It shows an empty collision mask.

Steps (uploading video is not possible as the size limit in here is so tiny for any video):
1- Create new sprite 
2- Add asset from hard drive
3- open collision editor
4- Use custom collision mask
5- edit the mask a lil bit
![1-402](https://github.com/4ian/GDevelop/assets/81715237/21147be0-b740-4415-b202-51700db91027)
6- Right-click on the animation frame and select (Delete selection:
![2-527](https://github.com/4ian/GDevelop/assets/81715237/acd057fd-4ff7-408b-b9ba-43fef3b3b8f4)
7- Add the asset again
8- The new collision mask will be completely wrong
![3-719](https://github.com/4ian/GDevelop/assets/81715237/7783901f-6f1a-4a79-b02f-9e570c7ff41f)

Now this sprite is bugged forever, even if you removed the entire animation (not just the frame) and hit apply
and then open that sprite and add another asset, it will always get the same wrong collision showing in the SS above

### Steps to reproduce

Mentioned in the description.

### GDevelop platform

Desktop

### GDevelop version

Latest

**Comment by ClementPasteau** [comment]
Thanks for reporting @VegeTato 

Actually, this is not a new behavior, it's always been like this.
The collision masks are unique per image, meaning that if you delete all the images of a sprite, then you are losing the custom collision mask you've created. (even if the checkbox "share same collision mask" is ticked)
We will improve the interface to warn when deleting the last frame.

If you want to keep you mask, you need to either create a new frame or a new animation before deleting this one.

**Comment by VegeTato** [comment]
> Thanks for reporting @VegeTato
> 
> Actually, this is not a new behavior, it's always been like this. The collision masks are unique per image, meaning that if you delete all the images of a sprite, then you are losing the custom collision mask you've created. (even if the checkbox "share same collision mask" is ticked) We will improve the interface to warn when deleting the last frame.
> 
> If you want to keep you mask, you need to either create a new frame or a new animation before deleting this one.

Oh, I understood, thanks for explaining ❤️
