### ISSUE TITLE
Correct dropdown copy for "Mouse button pressed or held"

### ISSUE THREAD

**Issue by LuniMoon** [4ian/GDevelop#5556]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

This is not a bug but rather a UX improvement on a UI component.

On the dialog for "Mouse button pressed or held" the dropdown component says "Choose an option" while the it's equivalent on the Event sheet says "Choose a mouse button":
<img width="936" alt="Screenshot 2023-08-11 at 12 54 42" src="https://github.com/4ian/GDevelop/assets/103995399/1270088f-06d8-4614-a7af-890edbee8466">
<img width="542" alt="Screenshot 2023-08-11 at 12 54 57" src="https://github.com/4ian/GDevelop/assets/103995399/050f82a7-7bef-4b76-9d73-df42158b4b63">

This is a Component consistency requirement for UX copy: 
Replace the text "Choose an option" on the dialog by "Choose a mouse button" (which action is easier to predict by the user).

### Steps to reproduce

N/A

### GDevelop platform

Desktop

### GDevelop version

5.2.165

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ZeroAlvein** [comment]
Im all in for "Chose a mouse button"
That is absolute indicator i can pick at least one from two mouse button
"Choose an option" can mean anything
I would still click it from being curious what is there
But i would only hope there are mouse buttons to select from and not expect
