### ISSUE TITLE
Gamepad support not working in Edge Browser. 

### ISSUE THREAD

**Issue by Cognitae** [4ian/GDevelop#5567]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Gamepad works on GD.games only when using the Chrome browser. When using Edge browser the controls go undetected. Unsure if this is Gdevelop-side or Edge-side. Have not tested the Mozilla browser or anyothers yet.

### Steps to reproduce

1.) Conncet Gamepad to port 1
2.) Go to GD.games and pick a game with gamepad support and try it on ### Chrome(Google) browser. In this case, I used the game https://gd.games/cognitae/astroduck-alien-quackdown - Note: **controls work perfectly**
3.) Go to GD.games and pick a game with gamepad support and try it on###  Edge(Microsoft) browser. In this case, I used the game https://gd.games/cognitae/astroduck-alien-quackdown - Note: controls **do not** work.

### GDevelop platform

Web

### GDevelop version

5.2.169

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>Edge

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by Silver-Streak** [comment]
I just tested your links in Edge, with a Dualshock 4 and a Xbox Series X gamepad. Both work great for me. Unfortunately I cannot reproduce your issue, but others may have better success.

**Comment by tristanbob** [comment]
@Cognitae I also tested your game on my generic Xbox One controller and it worked great.
Can you try your gamepad on sites like this: https://gamepadtest.com/

BTW - Your game looks good, is fun to play, and the custom music is hilarious! :)

**Comment by Cognitae** [comment]
Others can't reproduce the issue. There must be some setting on my end causing the issue. Closing out issue.
@tristanbob Thank you for looking into it! I also appreciate your feedback!
@Silver-Streak Thank you for looking into it. There Must be some setting on my end others aren't reproducing the issue either.
