### ISSUE TITLE
google play store target SDK 

### ISSUE THREAD

**Issue by deftrashu** [4ian/GDevelop#5578]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Exported AAB **target SDK** version is Android 12 (API-level: 32).
From 2023.aug. 31 In Play store must be:  Android 13 (API-level: 33).
[Target SDK:](https://developer.android.com/google/play/requirements/target-sdk)

thx for update it

### Steps to reproduce

https://play.google.com/store/apps/dev?id=8700583200006058031

### GDevelop platform

Desktop

### GDevelop version

5.2.169

### Platform info

<details>

*OS (Android,Windows, iOS)*

**Comment by ClementPasteau** [comment]
Thanks for reporting, we're working on it asap and should have a fix released during the week.
cc @4ian

**Comment by ClementPasteau** [comment]
This is fixed
