### ISSUE TITLE
Web link NOT working

### ISSUE THREAD

**Issue by mrWONDERFULguy** [4ian/GDevelop#5597]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I am trying to generate a web link for my game but get the following error. 

**_Error while downloading the game resources. Check your internet connection and that all resources of the game are valid in the Resources editor.

Error invoking remote method 'local-file-download': TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters_**

this week I added a few .mp3 files.   Some files had spaces so I renamed the file in the folder and re-uploaded the file but still the error persisted.  I took out all the new .mp3 files and reinserted them but the error still persisted.   I downloaded the project to my local drive and tried to create a link and then the link WORKED...  so I am not sure what is going on.  I have quit gdev, restarted my computer,  changed the files but nothing worked unitl it was on my local drive.  Any ideas?

### Steps to reproduce

I am trying to generate a web link for my game but get the following error. 

**_Error while downloading the game resources. Check your internet connection and that all resources of the game are valid in the Resources editor.

Error invoking remote method 'local-file-download': TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters_**

this week I added a few .mp3 files.   Some files had spaces so I renamed the file in the folder and re-uploaded the file but still the error persisted.  I took out all the new .mp3 files and reinserted them but the error still persisted.   I downloaded the project to my local drive and tried to create a link and then the link WORKED...  so I am not sure what is going on.  I have quit gdev, restarted my computer,  changed the files but nothing worked unitl it was on my local drive.  Any ideas?

### GDevelop platform

Desktop

### GDevelop version

 5.2.169

### Platform info

<details>

mac os 13.5 (22G74)

### Additional context

I was working last week, all I did new was add about 10 .mp3 files.  I have used .mp3 files in the project and it worked fine.

**Comment by 4ian** [comment]
Hi! Any chance you could share your email and project name to hello@gdevelop.io (with a link to this thread and "Information about ERR_UNESCAPED_CHARACTERS issue")?
We'll fix this then.

**Comment by mrWONDERFULguy** [comment]
Sure thanks

***@***.***


Little Chicken goes to the moon

**Comment by mrWONDERFULguy** [comment]
Thank you that works… but I have noticed that when using GDEV… I would change a file and it would not update…it seems to use the initial graphic even if I update the graphic…

Thank you for your help.
