### ISSUE TITLE
Leaderboard on Mobile

### ISSUE THREAD

**Issue by Mccesar18** [4ian/GDevelop#5624]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The leaderboard opens on Windows, HTML but on the apk it doesnt work.

### Steps to reproduce

![Screenshot_20230901-194550_Till Death Do Us Part](https://github.com/4ian/GDevelop/assets/82612079/2f86ffa2-9255-4686-a9f3-42a638d79ea9)

### GDevelop platform

Mobile

### GDevelop version

5.2.171

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

On mobile only.

**Comment by Mccesar18** [comment]
Hello, you sent me a Email, My user is mccesar18, and the Issue is #5624,
about a Leaderboard problem, I am at my regular work now and don't have
access to our project, but it was made all on Gdevelop, I didn´t use
Cordova after to made it mobile. But here is what I found about the problem
of Leaderboards on Mobile, after the player ends the game and should the
Leaderboard show up, it never happens, even if the player plays 50 times.
But when he closes the game and starts all over it shows the Leaderboard,
don´t know why. And our game is on playstore at the moment. But we lose
players that don't see the Scoreboard.
https://play.google.com/store/apps/details?id=com.goldenrocketgames.dontletdeathmakeusapart

   1. This is the Game.

Thanks for all the support!

Em seg., 4 de set. de 2023 05:01, AlexandreS ***@***.***>
escreveu:

**Comment by AlexandreSi** [comment]
Hi @Mccesar18,
I changed my message since, could you check it?
I tried your game and I couldn't reproduce the issue: the leaderboard were correctly displayed. Is it still an issue?
We had an outage I think 3 weeks ago, it impacted you for sure but it has been fixed since.

**Comment by Mccesar18** [comment]
I gave you acess to my Google Drive Folder, to Download it.
