### ISSUE TITLE
Verified Publisher Issues

### ISSUE THREAD

**Issue by VulpineVortex67** [4ian/GDevelop#565]
Hello, 
         When I export my game to test my game, my antivirus always flags it and blocks it. I don't want this to be a possible problem when people download my game. I was wondering if there was either a function in GDevelop, or something online, that would be able to make it so my game won't be randomly flagged on a PC that downloads it? Thanks, I want to publish the game, I am just worried about antiviruses that may accidentally flag it as malware.

**Comment by rikazukun** [comment]
I think it is only flagged on your end, I didn't get any of that on mine.

**Comment by 4ian** [comment]
What is the file that was flagged? Is that the exported Windows game as a .exe or the .zip file (or both)?

**Comment by VulpineVortex67** [comment]
Only the .exe was flagged and only when I tried to run the game. It leaves the .zip and other files alone. It just targets the .exe for the game (or the installer if I export it as an installer).

**Comment by KinkGD** [comment]
Today, while installing https://github.com/4ian/GD/releases/download/v5.0.0-beta50/gdevelop-setup-5.0.0-beta50.exe, i had to disable Windows Smartscreen to install Gdevelop... The setup was blocked. Didn't have the issue with previous builds.

**Comment by 4ian** [comment]
It might be either because the binary is new, so Smartscreen as to see more downloads before becoming less picky.. or because internally Electron was updated to a newer version and Smartscreen is now more concerned about the app.

**Comment by Silver-Streak** [comment]
This is an old thread, so I just want to add some clarity here (did some research on this recently):

In general, unsigned apps will _always_ be caught by smartscreen in windows and most antivirus software.

_Newly_ signed apps will be caught by smartscreen for the first hundred or so runs on different machines, until Microsoft updates their database.

I'm going to close this out, although this can be reopened if there are still questions/other causes.
