### ISSUE TITLE
Tileable Ground Textures By Cethiel

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#5652]
- License: CC0
- Author: Cethiel
- Link to the original website: https://opengameart.org/users/cethiel
- Zip file: [Tileable Ground Textures.zip](https://github.com/4ian/GDevelop/files/12574303/Tileable.Ground.Textures.zip)

**Comment by Bouh** [comment]
The PR is ready, I have to review it in dev, and I merge, Consider that like done.
Sorry for the delay I'm busy IRL.
