### ISSUE TITLE
Get Star

### ISSUE THREAD

**Issue by Evausuf** [4ian/GDevelop#5664]
BEFORE opening a new submission, please make sure that you:

- You have packaged the asset pack according [these rules](https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store). Otherwise, your package may be rejected or we will ask you to do the changes.

## Description

- License:
- Author:
- Link to the original website:
- Zip file:

**Comment by ClementPasteau** [comment]
Hi @Evausuf please avoid creating duplicate issues.
Your request is empty, so I assume it's a mistake and will close this issue.
