### ISSUE TITLE
The engine crashes when changing scenes

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [4ian/GDevelop#5688]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

An issue that came up in one of my games is that for some reason when changing the scene the game just crashes, I checked the events but there is nothing causing a crash when changing scenes, as far as I can tell it is problem by GDevelop

### Steps to reproduce

It doesn't seem to happen to everyone, but it seems to only happen when using the "Go to Scene" action.

### GDevelop platform

Desktop

### GDevelop version

5.2.172

### Platform info

Linux

**Comment by ClementPasteau** [comment]
Hi @QuetzalcoutlDev

As this is not happening to everyone, like you mention, could you share with us a simple project reproducing this issue?
You can save it locally and upload the archive here.
Otherwise, we'll not be able to help.

**Comment by QuetzalcoutlDev** [comment]
@ClementPasteau It doesn't happen with other projects, I don't know if it's because I have too many effects (Shaders), but it only happens specifically with a game I have now.

**Comment by QuetzalcoutlDev** [comment]
@ClementPasteau I don't know if the message that the terminal sends at the end is useful.
![imagen](https://github.com/4ian/GDevelop/assets/102568894/2b29d177-d63a-4549-b2f4-e95b6102f7c9)

**Comment by QuetzalcoutlDev** [comment]
Closed #5688 can't repro
