### ISSUE TITLE
Video playback is broken in GDevelop 5.2.173

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#5711]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Video playback is not working, it just shows a amall pink square instead of a video to be played.
This happens on projects that has had a working video playback for years up to 5.2.172.

### Steps to reproduce

Make a video to playback in a project and try to run it.

### GDevelop platform

Desktop

### GDevelop version

5.2.173

### Platform info

OS: Windows 10

**Comment by ClementPasteau** [comment]
Thanks for using 173 & reporting @VanCastar - may be an issue with Pixi upgrade.
We're looking into it

**Comment by ClementPasteau** [comment]
Keeping this issue opened until we deploy the fix to the new version.
This will be fixed soon, thanks for reporting again.
