### ISSUE TITLE
An error occurs when placing a tilemap object in GDevelop cloud.

### ISSUE THREAD

**Issue by katakurikodot** [4ian/GDevelop#5712]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The Tilemap object was working fine until now, but after updating to GDevelop version 5.2.173, an error occurred. It's the same Tilemap object, but it works fine in the desktop version of GDevelop.

![image](https://github.com/4ian/GDevelop/assets/146889363/b470fb2e-35a5-4e50-849e-f46dcd676703)
![image](https://github.com/4ian/GDevelop/assets/146889363/099fa94e-36ec-4861-80eb-9f1b0cd67739)

### Steps to reproduce

1. Create a new project
2. Create a Tilemap object
![image](https://github.com/4ian/GDevelop/assets/146889363/528b1760-a518-4a0f-a023-d184ecb36f40)
3. Place in scene

※Attach the Tilemap data.
[TestData.zip](https://github.com/4ian/GDevelop/files/12799188/TestData.zip)

### GDevelop platform

Web

### GDevelop version

5.2.173

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
>Windows 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>Chrome

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

Since we are developing on both the desktop version of GDevelop and the web, we would like to be able to make it work on the web as well.

**Comment by ClementPasteau** [comment]
Thanks for using 5.2.173 and reporting this problem @katakuriko7 
We're looking into it

**Comment by ClementPasteau** [comment]
We've spotted the issue, this was introduced by the upgrade to Pixi 7 and of Tilemap.
This fill be fixed in next release (5.2.174) which should come shortly
