### ISSUE TITLE
The simplified way to use variables in expressions does not work on grouped objects.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#5719]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

simplified way to use variables in expressions do not work with grouped objects.

If I have 2 objects with set variables in them.
I combine them in to an Object Group.
I can't point to their names directly but I have to use Variable(VariableName) again if I try to address them via Grouped Objects.

### Steps to reproduce

![image](https://github.com/4ian/GDevelop/assets/90930609/3f13804b-d938-4c9b-b20a-9f5b5eb371bd)
![image](https://github.com/4ian/GDevelop/assets/90930609/6e585e52-e66d-4dba-b9d1-b1cd46727adc)
![image](https://github.com/4ian/GDevelop/assets/90930609/101b938d-bfb4-4b4e-a5fd-2fcf77e839b5)
![image](https://github.com/4ian/GDevelop/assets/90930609/01773dad-b9a5-4679-8d67-6b0ec721ce69)

### GDevelop platform

Desktop

### GDevelop version

5.2.173

### Platform info

Windows 10

**Comment by VanCastar** [comment]
![image](https://github.com/4ian/GDevelop/assets/90930609/e6b0f3f3-31a5-4b82-9a66-0b96aeb6062a)
It does read so in the release notes.
I just didn't see it even when I read and reread it several times through.
Closing this as irrelevant.

**Comment by 4ian** [comment]
Hi! This will be supported in the next version :) A variable declared on all objects of a group will be accessible on this group in an expression.
