### ISSUE TITLE
"Start Emissions" functionality in effects of particles is not using the specified parameter

### ISSUE THREAD

**Issue by abooo96** [4ian/GDevelop#5722]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I am using particles to create effects in my game. Therefore I am hiding the particles at the beginning of the scene and then try to start a new emission when a certain logic happens (like for example enemy collision).

When I start the function, and choose the object to emit from, GDevelop does not replace it correctly and rather puts _paramo_. Therefore there is not way right now to start emissions correctly.

Surprisingly, the "Stop Emissions" functionality works as expected, as it correctly displays the chosen object as you can see in the screenshot below.

![Bildschirmfoto 2023-10-05 um 13 00 05](https://github.com/4ian/GDevelop/assets/39586071/afdbc790-876d-422d-8dfd-80b5e1b29044)

Is there a workaround for this right now?

### Steps to reproduce

1. Go to the Scene Events and choose any Particle Object you like.
2. Click on "Start Emission"
3. As you can see, the parameter is not correctly chosen.

![Bildschirmfoto 2023-10-05 um 12 57 57](https://github.com/4ian/GDevelop/assets/39586071/4b490f5a-c60e-4e30-a94b-e2faf6a3dda8)

### GDevelop platform

Desktop

### GDevelop version

5.2.172

### Platform info

<details>

*Operating System (OS): macOS*
>

*OS Version: 13.5*
>

</details>

**Comment by ClementPasteau** [comment]
Hi @abooo96 

This is just a wrong translation (was using "0" instead of "0" (zero)) :) the action works correctly.
You can check the translations, and contribute here: https://crowdin.com/project/gdevelop

I've updated this action's translation to properly use the parameter
