### ISSUE TITLE
I can't test my game

### ISSUE THREAD

**Issue by PlayingGamesCG** [4ian/GDevelop#5727]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

hi

I have 2 scenes and I can play the first scene, but if I want to change the scene via the events, it blocks and I have to restart the website.
If I then want to open the scene that I cannot open via the events, it does not load and If I close the HTML site, the online web blocks and I have to restart it

i need help

Greetings playinggames

[Screen recording 2023-10-06 10.55.05.webm](https://github.com/4ian/GDevelop/assets/147143779/c0b314d1-7c8d-4686-be78-edeb581b4628)
[Screen recording 2023-10-06 10.56.51.webm](https://github.com/4ian/GDevelop/assets/147143779/ee10eb21-63f7-4950-8472-d6a673ad4e2d)

### Steps to reproduce

![Screenshot 2023-10-06 11 03 15](https://github.com/4ian/GDevelop/assets/147143779/70670551-0091-4795-805f-8864324934cb)

### GDevelop platform

Web

### GDevelop version

(editor full version: 5.2.174-a7ef02f1c13974c2c864ed20970917385b4cf890, core version: 4.0.99-0-release)

### Platform info

<details>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*

</details>

**Comment by AlexandreSi** [comment]
You seem to use the Top Down RPG example. Is the error happening without you making a single change? Or did you change something?
In the preview window/tab, you should be able to open the developer tools using Ctrl + Shift + i. Can you open the Console tab and see if there are any errors?

**Comment by PlayingGamesCG** [comment]
Hi 

there are a few errors in the console.
I use the game example but I have a completely self maked new scene 
![16966991082164915910896291814216](https://github.com/4ian/GDevelop/assets/147143779/f8916384-62b2-40ca-b246-21a3e0dc23c5)
![16966991534822274678242247902039](https://github.com/4ian/GDevelop/assets/147143779/be91670c-5b80-4743-b6e2-d1ca84c89382)
![16966992235312167082660171490782](https://github.com/4ian/GDevelop/assets/147143779/ad030b77-fc60-414e-a6f0-1c6d90f7c6e5)

**Comment by AlexandreSi** [comment]
Hi @PlayingGamesCG,
it looks like your device/browser might not be compatible with GDevelop.
How old is your computer?
Could you try with Firefox?

**Comment by PlayingGamesCG** [comment]
Hi
it is a recent chromebook 
but I can play 1 scene but not the other 
Pls help

**Comment by AlexandreSi** [comment]
Can you check the scenes?
My guess is that the first scene is 2D only and the second scene contains some 3D, triggering the need of a WebGL2 context that your device seem to lack.
Have you tried on Safari?

**Comment by AlexandreSi** [comment]
Are you using the built-in 3D features or the With3D extension?

**Comment by AlexandreSi** [comment]
I see you closed the issue. Did you manage to find where the bug came from?

**Comment by PlayingGamesCG** [comment]
Yes,

apparently there was a problem with the repeat event i entered too many numbers
