### ISSUE TITLE
Keep sorting of sprite animations in events

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#5732]
Keep the sorting of animations in conditions/actions as they are sorted in the sprite object, instead of sorting them alphabetically. As it is already for scenes, layers, objects.
![02](https://github.com/4ian/GDevelop/assets/81538128/fc8b1aaf-40c3-4d76-8050-2ed32cbfbf34)

**Comment by AlexandreSi** [comment]
Solved by #5754
