### ISSUE TITLE
Dynamic circular border for scroll-to-top

### ISSUE THREAD

**Issue by SrishtiSonam** [4ian/GDevelop#5736]
BEFORE opening a new feature request, please make sure that you:

-   Understand the implications of your feature with the help of [the Forum](https://forum.gdevelop.io/c/gdevelop-general/feature-requests/35), OR
-   Peer-reviewed it with other users on Discord,
-   Consider commenting on the [Feature Request Forum](https://forum.gdevelop.io/c/gdevelop-general/feature-requests/35) if something is important for you

AFTER opening the feature request, the issue will be closed by a maintainer (@4ian or someone else) and a card will be added in [the public roadmap](https://trello.com/b/qf0lM7k8/gdevelop-ideas-box) if it's relevant and does not exist yet :)

## Description

Is your feature request **related to a problem**? Please describe.
Current Limitations:
> Lack of visual feedback for scrolling direction.
> Difficult to track scrolling progress accurately.

## Solution suggested

**Describe the solution**
Enhance the existing scroll-to-top button by implementing a dynamic colored border that gradually transforms into a full circle while the page is scrolled downward.
Create a design like the image below but customized for this website.
![image](https://github.com/4ian/GDevelop/assets/113123593/9a0ab4c1-eccc-49d5-988a-963a9c408548)

## Alternatives considered
Could you please consider assigning me to this task as part of Hacktoberfest if it meets your requirements for this project?

**Comment by 4ian** [comment]
Just to better understand before assigning: when you say "Enhance the existing scroll-to-top button", which button are you referring to?

**Comment by SrishtiSonam** [comment]
Here, I wanted to share my idea of integrating a scroll-to-top button featuring a dynamic circular border. 
This addition would enable users to effortlessly return to the top of the page with a single click after scrolling down towards the footer. 
My apologies for not specifying this earlier.

**Comment by 4ian** [comment]
I'm not sure exactly where you would add this - in this case, a detailed explanation or a mockup is easier. 
In most cases though I find these buttons to be low value (nobody has really any problem scrolling, you can just scroll in one swipe) - unless a page is really long.

**Comment by SrishtiSonam** [comment]
I would like to explore the possibility of implementing a scroll-to-button on the website that will directly take users to the specific section of the page where they can find the "Try it online" and "Download" buttons. 
This button would feature a dynamically adjusting circular border that corresponds to the relevant portion of the page.
