### ISSUE TITLE
"Help > About" section is not displaying on non-Mac devices

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#5739]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I wanted to add an "About GDevelop" section to the "Help" toolbar menu to make it easier for users to find out which version they are using.  Fortunately, it seems that the code for this already exists!  The bad news is that this section is NOT being displayed on my Windows build:

https://github.com/4ian/GDevelop/blob/4d8b39df9554384ed613292ecebf7cd6384c6581/newIDE/app/src/MainFrame/MainMenu.js#L344-L352

FYI - Here is where Mac OS devices get this functionality:

https://github.com/4ian/GDevelop/blob/4d8b39df9554384ed613292ecebf7cd6384c6581/newIDE/app/src/MainFrame/MainMenu.js#L366-L374

My first guess is that the "isApplicationTopLevelMenu" is never true because this is inside the sub-menu of "Help".  Perhaps this section needs to copy the pattern used here?

https://github.com/4ian/GDevelop/blob/4d8b39df9554384ed613292ecebf7cd6384c6581/newIDE/app/src/MainFrame/MainMenu.js#L183-L216

Do you think I identified the root cause?  If so, is this the correct resolution?

### Steps to reproduce

See above.

### GDevelop platform

Desktop

### GDevelop version

5.2.175

### Platform info

Windows 11

**Comment by AlexandreSi** [comment]
Hi @tristanbob,
thanks for spotting this!
It might be the root cause for this indeed.
Do you want to fix it yourself? I can help if you need!

**Comment by tristanbob** [comment]
> Hi @tristanbob, thanks for spotting this! It might be the root cause for this indeed. Do you want to fix it yourself? I can help if you need!

Thanks for the help!  I have attempted to fix this in the PR above. It seems to work great but I'd love a review.
