### ISSUE TITLE
Bug - tween opacity object (Panel Sprite) from 0 to 255 - Objects remain transparent

### ISSUE THREAD

**Issue by AlexMasterbober** [4ian/GDevelop#5761]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

After the last two updates, the action stopped working: tween opacity object (Panel Sprite) from 0 to 255. Objects remain transparent. But their transparency property shows 255. If you hide this object and then just show it, then its transparency is restored to normal. 2 days ago everything was fine. This happened after the penultimate update.

### Steps to reproduce

set Behaviors to PanelSprite object - Tween.
1. Create PanelSprite object on the screen
2. set opacity to 0
3. tween opacity to 255 "linear" 250ms
4. see what happens - opacity looks like 100
5. see my tests: ![image](https://github.com/4ian/GDevelop/assets/147695106/cfb38f3a-86d8-431d-9138-868ee7a392cd)
![image](https://github.com/4ian/GDevelop/assets/147695106/5f7d4355-a60c-4b82-af06-43a195eac02f)

### GDevelop platform

Desktop

### GDevelop version

5.2.176-3923641988c0222e523bee9045e1ef3e66be05e3, core version: 4.0.99-0-release

### Platform info

<details>
Windows 10 (21H2)
</details>

**Comment by ClementPasteau** [comment]
Hi @AlexMasterbober, thanks for reporting the issue and the detailed explanation.

Can you open the action "Tween opacity" to see the full parameters and share a screenshot?

**Comment by AlexMasterbober** [comment]
![image](https://github.com/4ian/GDevelop/assets/147695106/0df71c76-f02f-4512-b3d4-b1f73dba345c)

**Comment by AlexMasterbober** [comment]
This problem only on PanelSprite object.

**Comment by ClementPasteau** [comment]
I can't reproduce your problem.
I have a PanelSprite that either appears directly or with tween and result is the same.

<img width="1226" alt="image" src="https://github.com/4ian/GDevelop/assets/4895034/ad524bf0-e8f9-4faf-be54-3160635e7aa1">
<img width="804" alt="image" src="https://github.com/4ian/GDevelop/assets/4895034/591a1aa3-b93f-47bf-99be-d63d2c2bb9e2">

Here is the test project I used. 
[Tween Test Project.zip](https://github.com/4ian/GDevelop/files/12879041/Tween.Test.Project.zip)

Are you able to share your projet or a test projet where you can reproduce this problem?
Otherwise I can't really help.

**Comment by AlexMasterbober** [comment]
[test_proj.zip](https://github.com/4ian/GDevelop/files/12879189/test_proj.zip)
I understood the reason. Your project works for me. I opened it and created a new object through the internal editor. And the bug appeared. I'm attaching it.

**Comment by ClementPasteau** [comment]
Thanks I can reproduce it indeed.
Did you use the in-app Piskel to create image?

**Comment by AlexMasterbober** [comment]
Yes. 
![image](https://github.com/4ian/GDevelop/assets/147695106/37a9599c-7875-4faa-8b59-49e110bffe36)
![image](https://github.com/4ian/GDevelop/assets/147695106/8bf837e9-dc99-40e6-ae02-b56865f90e3a)

**Comment by ClementPasteau** [comment]
Thanks for that, I can reproduce the problem easily and found the root cause.
We're working on a fix

**Comment by ClementPasteau** [comment]
Thanks for submitting the issue, it's now fixed and will be available in the next release
