### ISSUE TITLE
Spine support

### ISSUE THREAD

**Issue by malec-palec** [4ian/GDevelop#5775]
Please, add Spine output files support and runtime animations playback in GDevelop.

Spine is a de-facto industry standard and needs no introduction as a 2D skeletal animation tool. It is mature, feature-rich, and production-proven.

There is already a card in Trello roadmap - https://trello.com/c/8HKpJgYC, 
and an open discussion on the forum - https://forum.gdevelop.io/t/support-for-spine-spriter/12570/8.
The only thing left to do - make it happen!

PixiJS v7.x supports Spine runtime - https://github.com/pixijs/spine, so integration with the GDevelop runtime should be straightforward.
But there was no progress for a long time.

Do you guys have plans to integrate Spine in the near future or a technical vision for such integration, so anyone who tries to do this will be aligned with you?

**Comment by 4ian** [comment]
> Do you guys have plans to integrate Spine in the near future or a technical vision for such integration, so anyone who tries to do this will be aligned with you?

Thanks for asking! The core team currently is busy on other projects so no immediate work on this will be made, but we're happy to support this in the long term if there is a contribution!

> PixiJS v7.x supports Spine runtime - https://github.com/pixijs/spine, so integration with the GDevelop runtime should be straightforward.

I also see this: https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-ts/spine-pixi
Which one should be used?
Note that we need a maintained version so that we don't delay adoption of PixiJS V8 with its performance improvements and WebGPU support.

**Comment by malec-palec** [comment]
> we're happy to support this in the long term if there is a contribution!

Glad to hear that!

> Note that we need a maintained version so that we don't delay adoption of PixiJS V8 with its performance improvements and WebGPU support.

Noted. In this case, I would prefer the one from the [Official runtimes](https://esotericsoftware.com/spine-runtimes#runtimesOfficial) list, rather than "third-party runtimes" developed by the gaming community.

Though `spine-ts/spine-pixi` is still under development - https://github.com/EsotericSoftware/spine-runtimes/issues/2305
the approach this library uses looks more promising.
