### ISSUE TITLE
Gdevelope issue

### ISSUE THREAD

**Issue by kkurbahns** [4ian/GDevelop#5786]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

A error window pops up everytime i try to use gdevelope

### Steps to reproduce

just opening the app

### GDevelop platform

Desktop

### GDevelop version

5.1.60

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by 4ian** [comment]
Closing the issue as no more information reported.
