### ISSUE TITLE
Crash at GDevelop opening

### ISSUE THREAD

**Issue by PixelMartian** [4ian/GDevelop#5788]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

![Gnotworking](https://github.com/4ian/GDevelop/assets/131309935/053867fb-3e67-452d-9c8e-1043b4fba494)

### Steps to reproduce

N/A

### GDevelop platform

Desktop

### GDevelop version

5.2.176

### Platform info

<details>

*OS (Windows 10 Pro)*
>

*OS Version (22H2)*
>

*Browser(For Web) (Chrome)*
>

</details>

### Additional context

black screen , unable to run a preview , unable to load my project

**Comment by AlexandreSi** [comment]
Hi,
Thanks for opening this issue.
Could you click on the button and open a new issue?
![image](https://github.com/4ian/GDevelop/assets/32449369/34e8fab1-3dac-432a-a7cc-44fd10398ea0)

**Comment by 4ian** [comment]
Closing the issue as no more information reported.
