### ISSUE TITLE
Character Pack 8 By GrafxKid

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#5822]
- License: CC0
- Author: GrafxKid
- Link to the original website: https://grafxkid.itch.io/sprite-pack-8
- Zip file: [Character Pack 8.zip](https://github.com/4ian/GDevelop/files/13063372/Character.Pack.8.zip)

This adds to the current character packages by GrafxKid

**Comment by Entr0py404** [comment]
I think I might have packaged these ones differently from his other packages, it's been a while let me know if it's an issue and I'll fix it if so

**Comment by Bouh** [comment]
Hi
Thank you, I added these new files into the existing free pack by GrafxKid.
