### ISSUE TITLE
GDevelop encountered an issue

### ISSUE THREAD

**Issue by TomKingUK** [4ian/GDevelop#5826]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

GDevelop encounters an issue when launching first time/every time after installation.

![image](https://github.com/4ian/GDevelop/assets/59918804/4e837151-874f-4826-bc11-f27c49457d42)

### Steps to reproduce

Run GDevelop
Error comes up

### GDevelop platform

Desktop

### GDevelop version

5.2.176.4663

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows 
*OS Version (e.g. Windows 10, macOS 10.15)*
>11 22H2 (OSbuild 22621.457)

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Edge

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> N/A

</details>

**Comment by AlexandreSi** [comment]
Hi @TomKingUK,
This error should have been fixed, the version is not yet available automatically but will be soon.
In the meantime, you can download it from here https://github.com/4ian/GDevelop/releases/tag/v5.2.178

**Comment by TomKingUK** [comment]
Thank you Alexandre,

I will try it and let you know if it is resolved.

Tom

Kind regards,

Tom King
________________________________

**Comment by TomKingUK** [comment]
I installed 5.2.178, but this also had same error when launching the application.

Please advise any other information I can get or anything I can try to resolve?

Thanks.

Tom

Kind regards,

Tom King
________________________________

**Comment by AlexandreSi** [comment]
Ok, it might need for intense problem solving!
Could you click on the `Report the issue on GitHub` button and open a new issue? This will contain more data to work with.
