### ISSUE TITLE
Gdelevope bug

### ISSUE THREAD

**Issue by WorstBlockGame** [4ian/GDevelop#5827]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

It says this whenever a pen the browser version

### Steps to reproduce

!.Lauch the browser form

### GDevelop platform

Web

### GDevelop version

5.1.160

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

![Screenshot 2023-10-17 113323](https://github.com/4ian/GDevelop/assets/132005176/45046687-b16c-4ae8-ad88-c510cb467096)

**Comment by AlexandreSi** [comment]
Hi @WorstBlockGame,
This error should have been fixed, the version is not yet available automatically but will be soon.
In the meantime, if you use the desktop version, you can download it from here https://github.com/4ian/GDevelop/releases/tag/v5.2.178
