### ISSUE TITLE
Cannot add behavior to object

### ISSUE THREAD

**Issue by roboisaac11** [4ian/GDevelop#5829]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Whenever I try to add a behavior to an object, I get this error:
![image](https://github.com/4ian/GDevelop/assets/88291918/9e27379d-2f9c-45e5-b71f-a6ff075d9e60)

### Steps to reproduce

1. Double-click on any game object
2. Go to the behaviors tab
3. Hit "Add Behavior"
4. See Error

### GDevelop platform

Desktop

### GDevelop version

5.2.176

### Platform info

<details>

OS: Windows

OS Version: Windows 11 Home, 10.0.22621 Build 22621
</details>

**Comment by AlexandreSi** [comment]
Hi @roboisaac11 ,
Could you download the next version here https://github.com/4ian/GDevelop/releases/tag/v5.2.178 and see if the bug is still present? We will soon release version 5.2.179 and if this bug is still present in 5.2.178, we could have time to fix it for the next version.
