### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by PlasmaFlash30XX** [4ian/GDevelop#5841]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The editor crashes for no reason

### Steps to reproduce

1. Go on the editor
2. See error*

### GDevelop platform

Web

### GDevelop version

5.1.160

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>
All Platforms

### Additional context

q

**Comment by AlexandreSi** [comment]
Your GDevelop version is really old, try to do a hard refresh (Ctrl + Shift + R or Ctrl + F5), it should fix theses crashes.
