### ISSUE TITLE
Crash after adding image from text/plain data url to scene

### ISSUE THREAD

**Issue by radlotus** [4ian/GDevelop#5845]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The Scene Editor crashes if you add a sprite with an image from a data url that is "text/plain" instead of the corresponding image MIME type. In this case "image/webp"

### Steps to reproduce

https://github.com/4ian/GDevelop/assets/95962222/827f2a2b-d12f-4d6f-a175-76bf914e0af9

1. Create new sprite, add animation, add sprite from data url i provided below.
2. Attempt to add sprite to scene -> nothing happens
3. Switch tab from Scene Editor to something else (Events, for example) 
4. Switch back to Scene Editor

data:text/plain;base64,UklGRl4UAABXRUJQVlA4WAoAAAAgAAAAfwIA3wEAVlA4IEAUAAAwrwCdASqAAuABP/3+/3+/v7+7shsLu/A/iWRu2RCRy2FpyCBv9oFd/0F/nF7uqB/8v0wH+bX14//f9z0p+Pxd/0nkv/gP//nS///U37/sgXlvNnX/z2HnExFUYoxRijFGKMUYoxRijFGX5IrC3pR43KKwx6MXf1hrDWGsNYaw1hrDWGsNYaw2ZTTyDHoxfe1aKu/rDWGsNYR1ZbDVq/ic0+XBBZUZj1ZNivjYFHUjx60dT1oIBIzADW9GMvdYajg+WbjRvCBuh1X2E2rfjXfuuwwkSbSlzLqw1mC6y2TeHP0UM7HYNrS7+sS6s4y1uKBJ7qnO6Fiv0AAHsnADruRUIQK/m9HUwKxsbW9hAaOSLh2XA0wVn421JOOODyCkI6PxOt/YAFs0/7Q3mzWPpxokmMfc0girJL/ZDPHFOrXw2JfAFH1RGElIfdcpOSEmL30gbhnwEoHcWUnXgFxHeTxvDPZNVfMu68uijyt9L9/ckIWz8rufnRRw3puUQXKIK3pR5aWxlRO+49kixjFVHun8mpaNQFGyImZyENYbBOqb+xQKxIfm/eoV+zDGYqWIwFpBe9hVaXQ0c4okzx8s23lhXQTTVjGqKAdVeQyfOgANFndRtVJTYSiNnefbXn2CmQ5yj3otGVTcM2HYZ8ne/MBEftQ9S2OSOHGDrxwbIdh3f3g+MnGNFt6avS6lB8PNGV0AHhYXXARE4IKkehbE1y4BHLCRxrw0JvS5udLnfI/DATo+fLq2eFLW/YAqvtTyUhGWyYRl8rvcj5BIQv/yk4275doKzQHroi9WWZYN2PcUe+/dFuGUDsicnoa9NTH9ItKuCQaqRZCCNZIlBLciPvq6NN3I83fpCFQLl/iqs3Ax6LhHtaHPkP2eGe/qN3ky3Tkj86NLVOF0OMclaKDsanhXzSEnY+KwI/SFES484AUsh0QcVqYc7U2VddiWb2sNhg85GYdVxsUNbOoD+mluvMHTAcK+7B1MPfidKSgzNA3rA/ydtmt5dOGBzwAhfDDlxfQu0nHlAXavH4AjlUg8spx9gNldDW9DOlbZ8Yyvcb7ZlTtVrWT2ox40Mi9clgcSVRUoFHEdKMj1diLFPTHZcH2ATI2j1+bPJvykQ2EMGWQ8Vap2Swj2bJN41T0qojNQze5WC/Xd3VYZuigDgAARPC0CoXd7S60enOAQe9VSuhDvyzWAenF7hnYnw31RgIqATAJfgwzaZwGyqYhjdRYAPRG+LZVToAeUaKeFenOfMqctM7wROw1m1QDqv5zCM1BvmQgdVQCPPq94iHwKge4M0OWjI2pR9Ap704qtFnUdCmXUDABHmgqJqLkdHkHsb0eYbAKLOlA0W0k6hl2i5iCbEZHitwuB8K/tYZbo/2GAXha3JCk9cEgB9GPEj6L7dAGV2GhcoSckHFiwCW3saUoL8Hu5bor2CDEQ0AAV6k5mFNtp8JroPnbr7lbNAKeDG4KhAEC8aPGt0vTfYLoKhCX3daUdwYTvBnyVo20WJuwfAELkcXt9jAJM/OQavAF4hL0KsAADhCIAhUAb8mdFaQS3mxy0EgiOnRlScoC6jCg3yynCVdUQ4AEXYu7yMBYO9lK+REpresNUIqQR2g8dgadsCXhiXvvKGBgwanSuAT/HGVCAqL6JxFrgLVzFWhgKFBGz3gAJiMrYQKg0kotZ+CmQcL2IdLZe7OZDx/C5nN5KiF2qwAS+xWKxJN1gBn01Y2Zf+pkzU6RNwvAUb0Y8YYOHepwDw3OFu/SGbkeAAYOBouuiMgAEpACFAAYL9+aLtUPDW/rqABAf7QAI3rsxFn2kxZDRlZQwwEXnliK5lMxEWfAXUUHcIAF50G1AOwLwUDCj0UAFyiMwChokR0n1lHO8EK1B6AAA/sJ0nF0v+XUdzYeigN6ItgC6xzANG+VwM0nVEEuJZ0qZsNSMay2heQOxAx6AyQHEui+gpK9AAAAO5Dh4ZnqrP4F5tAACbhta0Fa/GwirWKB2ZOxWyO92CsQbBgHjsQQ7KoKwmyrgAADuCethlp1CzSicgih8YNe7MPqIDR5UwGUpB84rY+N9xyRBgLu/D89aAGLw5ZcIA2J1RgpAvVsDQBV8+5L0f0x+8YwAkKw4ZwdG2NxAGKuJAmdx7zoHBuZZggdnSCGC0vXYCRR8QWaHUYaeE5KRPoR6eNvu8D3GLxS8VYtgnuRdsO0JKOiTbu5JKuG0e7IAOexDQar4CRCEBr8+vddRFhgYD6K9JAFdfYfb5M5q9zAyTIOpPWusD2LkjM1dqOnN39fD0tdNmSQaAo4Jn0LgBHyd4Ja1E1y3CLRxrvuqouaxw+vhic1pB6ArKk6q8fpueqmYrXpe1NfiikN55Zd0ztz15XgrqCLdVoW+49c5x1JvMKP1Oi6X+oRiH6jQAKfx1tYCi99E8qn4Cw7yzcNBzjI3q6iIAEIkE3IgAR/5BSI8qi6L6w/SJk1wjlEiNeIs2W4wsQniebyGEK3xDWK5bx9xFzmJZi1Hd3tltzNvw6FVzrmjwrXR5a0xstHFaA2mg4Wc0wC/a3uJED/0TOM3FzfeQhZjNYhQ8NZAAsoU43uv/bTli2pm5mPDGExemom7WK4oAZQABQAro9hespeQhT1WNK3tp4kh7g3YYr5TCiWcAYc6YA6MLlKyVysxNn6zq0/uesCyfkDUZ7krbhUhJg2tjXFZqoOxm3ecohwEI+qE1AP+ZiY9Xmk/lC3PgPmwoFVPDnTP34E7YnaZm6qg2J9qu6YSxlVci7101KnmTEcXIjJHMu6+angJqR8kDOG2rZx2zwMuGbCiOYEDg/BJxwEhtHB/kA8p/LkDDcHxFol1hrvKPznbEazXj413xKHrtmItCE14EyOux7XJdRuENaoHAAwaimA1LjVeoVXjlR/BxlTjsdu9Spd2VCO+VHNUk6JkKxAaLeXnzYNgP9Wzr3I4f7Jv7KJ+MEFYZOY8TgONJOGFZFouPX4rWLfe1Zn/ZBBib2mLSrMqRyp6I0up+DPL++wIgb1Vaq8gOo/CxtlAYSN3VJ5ND/O5NNTeGoxaKjextcRSSjqZf/K/WkN6A2WwRY4buBSS8CMW5jprhC9HbEv8ttbqoGOd5dn2Zpjp424dsNTShrRodh9qfH7ltJrWGp7WyrSw5661cBQjY+/qvAZHpnTLRdpPMPE1b4wQv/SbexjvtNxiHOFt1Zh77S3JevdoFtxr1gddsl+ORYusKeYkrpPKh3hLUe3UWTtTUdcSuBHsg3y/rHHf1owcGhxPmvhmNqs3IZGiO4kVzhiA6WsvSI/6BNJqVg15jjJ44VJNcmElaB4jyhI697YP+L+0kAEHDWaMVP7FfEho4E234FJ5zIq8YMnrdMU2QRx1kAkQcu24nAlTlIc7ULMl2j0zoA4egJSndI2W128/mUEhZeCF7NkaiGT5O88XNCY6jRe0DrUUIQA2uQEnNpuh12JEwbOjucJ9XRQXHu+qlfa/EqQeAyggd+kJBRnZaxfTGyZA75bZWXxZamyKLl7vNcxiEzpQ0Bl5mG0Z06yAGfLVXkIStM1htt4Pn1Ia445QC1Ge3tPm42h4epkR9gkTrod0YACy5EtCo8AE4fHRpbRPyaJGLrdt/GT8VzzDwv3jaGccxxIy2VwXK0S/4d7APA9M8ugpgEPhzX/H6ID7LNnPFRZUkyvkYEHBCCWKvdPrheoqW+GuK2+1A1/PSaDuVTC08h8MeLfDcu+qKXdJsmVMh3cCkXyWBnCWiwzbus9mC0SvhVni12Xzknnm/slMcnGOVNoSXTIbTtdAaaUSEjmsnc0Z1fqHGv2Ik0F9HPUZw0TWlRuxEeEkrJfE332hg5ymNnq9t0I3BOlHcF9oK4R4fFvKUKA1kffZutLgLd5OZgWj4BYnteJukbL0Ixt+z7zZJvfBuXVZiPfyStnHOsW+QlSxMhDfJf3oL3TajrCq0JR6ssY4URq+VQ40yynSKdSC2M4Vcvm+PYZiU1hFXvtRUqpr1E1wIf8m5/cQCSdOvgXrYSrKMyxydG0Tgnfad+OsRb0Ke6Hf4NCw7NJgjCST+jyr/UdqmVtekGwqvQ1g2sdYIUyOw7OVm72Xwag1srp4jmprJv7gFfOb+SLHCCEcekGrBQpsoJr1MDNSEN+uvroTNRDW9xVyRFcpBZ2B+AoxGT5YAIcIwQ2H8pKap8iem385I6HTyL1RPwgrGoB5MJJ4obNmDrrliZt+4l8sDXOVph2DHELk9hvnxMLKD/mG5ai88xABYDMLS5PiOuQrKxeZTVX14Yfc2/PmLQI5ssiuDZxA13YSZ29niKzf3Q/leZjL4pZMv1s5jjeQCNRvhaX4wO97cPeBI/uQXPGkz6xsLjzPloURRnfIUeByR1VwO0r6YWrh8vcgzO2ReBoJq2yWST8Z0VWwabGqtAnbwC2QmG+J4ZWxce8jZCwjSJEdGlm9MUNYPKftlQqFILzHGrZE+jLndihFlGBrrxtyMTmdnRzFB1fyvQ/nPIa3tOWp9mW/pis7qQsLZKb6Fp/wCvkDAHSFqAcOcaDJMdKtEc0Lgd7rjCbwPU+rjnYxVj5HnJoOL8IfgW+fgjEoPBEanBkaYAB+2hdfpxVXP15EpwysOK8xmVNOu8dht2oadb5xEdyaNOd+hbcG2fD4BfcWoi45J47/G9dCU9Tss34tUnnF2eKwYJFfgMidRaM87Kptaxf/HsKjjqH5i62p8Vi6iraGNDNaT4VLi4l1eflw4XeHzNYbC+MfEoaV/uzvYSgQdnZbUEEVdufSyqJ0ajRsOF92i9mJoR/81EgSIMK9yBgc/qcBvRZLTU8vKE7BCptI9NWTIXP1jCDpIZ9dEsw/9ZBmO9woTN7kaMRG+WPtYekmYd8QH0X9vbnOSGy/JZi5vqcMlAGVLg9OACVjWxp6IXkTXhzrJN7Mr3yu1qsYiZXnSY2PpSBsZQQdTNcLWbbD2kvzzEP7MPFDqP24fGDhP7eiG6ZUAeaEeyBLHK39SX0R4zdm8I6YrJHzsz6H1ivg9laNB3lkRzIEC1fxDC8nY4P6iC3fIP+PNmqgFnz8rEUVpZxC0SeaUCNfi3n/KS7Afibi1SlX+WMDSHJolbNG2WEHvqkCIvtL8tgb0eiOmAQKmpT6/RCveRzLXLMcs7+wRCmW3Ff14PBz2MF8SaTa7MGplqMYGfiEHuym+3fTeqwJvLBb7xYwR21k95Q3D4Plmd3nisRvMQ4YLS2rawzW/yGX9mtz8lfQsQm/eFgZhJ/yTfDPzHQz6NU/3gArtvvD1omAY2mCrbQ18gh5fJbsrbaToEep05VoEBFEh7qaSU6/xOmOeO77duYEv2x2VmjCbrJNCJm9QPDJCB9jrq82DyWUcjsvRWLmonnoMqZYazFK1mN5Z3NPFraHTEU69tJIJOEYtDyP6oo3umd3boMndIoUFBPkua3e0uIZra/Nu1um1YKW2R6uUk8PArzdR4xtDbZIQiiR6wNuM7mmRe4MTTvZa8dXX+VyEWmG92kAqhGb/SZrmAee1JYwmqosaip/MiJ2gI00C24FlAu+Lp+v67cmr+LJT5uKbDb5Vd/KVC41POMFObV+KAfw5QjFqWjmH6DZC3a4Hn/D1ElvyrJ4iqHsaiXjiGuo0Uz4LREB3ZHbT27fPqEL93K/7JIT7HGL5zsDaA/FZPU6NNsnytdcg+oNmhtsDdc/SjnIRa7T0BnnZGzWLSYTBzWbkeMAE6MkF396gOT9e+kMc+6EyVBFRo0IrunhfbKC9W38kwzhC9pIJjBWT1uq01E3n6FzSu9muu9qN6AIEWSgcdvqHezCkUJ9GtdjDc95Cu8Yfnq8L4sYYj65pqSU8G1fDP2c1p0mITWJF4In5jAyZL6UjOl+jd2NcKplN874RfNN2mbbGVj0tmFkDj6qSUVKtgUrjInnpSzGajnOm/fBmO1idJI+3HK/62K1Qgc+RFT5o/TvoRXuYLD5VQ1IYnk+HDCdvvbqZOSiGxpmUWv+eXG4Yby/ASbZgmxNjpa06KbMWW1iWZf8YeP3ncy8xiscA7da5Rbr36jJIbUphGjDo+0aXDIDTxzd+Mp63t0rBUVQj5v0wvuGodLiwhJIT17xZ5YugZ+qb2/REpQEZf/IkkOTZrbLgrgyDOyvxu29bcGFsPS5gLhJkH6hg/zjBQ3eyYZ1IqNAbTZLS9HJvjdO+PkGZ62KHJoQFI9gCb409pXrChEGHlx80LHEdp5u2NdkVmAXCSTaLLRAoW6iBzoDEZVCIsLl0Ax8ySg+CLto3to7WY4t9QVA9CFb3jINbAr2ugScR32eRsHZ6HZwQK4m9HWAaAVSiZs4ZUj3KGyO5jC59PbLpu1cD2yb61jljPXKQuxbMguQN4RK03X4cZ8xQuzfphmeOdV1eDmKBuF2f0rC4+p5FwsW2yZ9gMufzPLC1F1dDoSI24ru0osDKrKMUEJSVeYQR7we+2sAH/Dyjz0d/n0jKnaP9zqYDjSuR3BVuM2hgwmn/V+zBEZp+CaEB00AfLG8yVlwZXQeHQWNitdVh1A3Rbq5oNcFUoPwkDOZmlnMtfOdcO76hU+8M5Duby0FwQ/yfd4m2wpv3iyiNwO5GZXnKc+1YijHWElb9CKFfSfPgEaFeqDFSOi+sg4virt/PzkK+hg+p7UQ52aTe3spVMKy14Uk9EBrarXpvYw+dilfeAVHFZUcpB1kPTNxd73HMFto0yDL/dGm9AlHMvPm3ODXPlJc6r1miXAMfyrMejQwYOGCZhOdkY/tmZ9rhxUcSOsF2YsQSpLKMGQjKB0x9kz2fuYS4ARVoYAMByw4pTCfRunoZnIcdj+vKGVv6xBhwClttMaP8JvRQVHXNi+dmG9a7G7w55WRtpO+nJhs03PSn21kkClgK22mWVhqJ+5zfXnfhyRfp1HJBHgUxBewUjEi+zt5y+HKoAA=

### GDevelop platform

Web

### GDevelop version

5.2.176 (editor full version: 5.2.176-3923641988c0222e523bee9045e1ef3e66be05e3, core version: 4.0.99-0-release)

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
> 10 LTSC

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Chrome 118.0.5993.118

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> Lenovo Ideapad 3

</details>

**Comment by AlexandreSi** [comment]
Hi @radlotus,
Using data urls is not supported by GDevelop. It might have worked in the past but was never officially supported.
So I'm not sure we will fix that.
