### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by albertoig6668it** [4ian/GDevelop#5856]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

it says to back up my game file so i wont lose anything and i just opened it.

### Steps to reproduce

go on gdevelop then game crash.

### GDevelop platform

Desktop

### GDevelop version

5. 1

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

no other problem.

**Comment by AlexandreSi** [comment]
Hi @albertoig6668it,
You use a quite old version of GDevelop, please update GDevelop to get the newest version here: https://gdevelop.io/download
