### ISSUE TITLE
Search in Objects Pane Caused a "Problem"

### ISSUE THREAD

**Issue by JasonLBlair** [4ian/GDevelop#5862]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I click into "Search Objects" and the cursor appears. I start typing and--no matter what I type--I get "editor encountered a problem" immediately and have to restart the engine.

### Steps to reproduce

1. Open Scene
2. Click into "Search Objects"
3. Press any key

### GDevelop platform

Desktop

### GDevelop version

editor full version: 5.3.179-e0df9b0ff39dcea7a28e6baeb1de814b8acd3399, core version: 4.0.99-0-release

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by Bouh** [comment]
I can reproduce on web and desktop, here the console log.
[1editor.gdevelop.io-1698857402645.log](https://github.com/4ian/GDevelop/files/13229544/1editor.gdevelop.io-1698857402645.log)
