### ISSUE TITLE
Gdevelop 5.3 stopped my game from working

### ISSUE THREAD

**Issue by RoelSpierenburg** [4ian/GDevelop#5876]
### Describe what you were doing when the crash happened

My Gdevelop project no longer works since the new 5.3 update. 
I think it might have something to do with the JSON files I used for tilemaps.
Once i clicked on a scene the following appeared.
When I try to preview the game, I get a black screen.
I tried reinstalling Gdevelop but it did not work.

### GDevelop version

5.3

### Platform info

Microsoft 10

**Comment by AlexandreSi** [comment]
Hi @RoelSpierenburg,
Sorry for the inconvenience.
Could you send us your project so that we can check your resources?

**Comment by AlexandreSi** [comment]
Closing this issue for being stale.
