### ISSUE TITLE
Crash after editing sprite (Manual Report link didn't work)

### ISSUE THREAD

**Issue by GalaxyGaming2OOO** [4ian/GDevelop#5877]
### Describe what you were doing when the crash happened

SORRY IF THIS REPORT SUCKS SINCE THE LINK DIDNT WORK SO I HAD TO SUBMIT THE ISSUE THROUGH MY REPO FIRST TO GET THE CONTENTS

(PLEASE CHECK IF YOU ARE REFRENCING THIS AUTOMATIC CRASH REPORT CATEGORY) (in link ofc)

1. Made an object
2. Created Sprite
3. added logic to make it point towards the cursor
4. changed sprite
5. crash in editor

### GDevelop version

5.3.180.0 (MS store)

## Other details
* IDE version: 5.3.180-8dbf9c99ce5a0fe0417c0cb09302abcbc974d172
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19045,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.180 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of null (reading 'width')
    at n.value (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/5496.6be983ec.chunk.js:1:1953923)
    at e.getUnrotatedInstanceSize (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/5496.6be983ec.chunk.js:1:1340287)
    at Object.getUnrotatedInstanceSize (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.a...
```

## Component stack (don't write anything here)
```

    in e
    in div
    in s
    in f
    in e
    in div
    in s
    in div
    in s
    in div
    in ForwardRef
    in ck
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Ff
    in ForwardRef
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in y
    in t
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in aI
    in div
    in n
    in Na
    in div
    in xL
    in Unknown
    in mt
    in f
    in u
    in v
    in m
...

**Comment by AlexandreSi** [comment]
Hi @GalaxyGaming2OOO,
Sorry for the inconvenience.
Is this error happening consistently?
You can try to go to your preferences and deactivate this setting:
<img width="549" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/c263294f-42b0-4c69-bd11-f051f695d06e">
Let me know if that helps.

**Comment by GalaxyGaming2OOO** [comment]
It seemingly happens randomly usually after an our or so of using the editor
i will try that fix and let you know if it works

**Comment by ClementPasteau** [comment]
Also @GalaxyGaming2OOO could you give more details about what you were doing?

What do you mean by: 
- `2. Created sprite` -> using Piskel? using a local image?
- `4. changed sprite` -> using Piskel? ...?

The more details the better, thanks.

**Comment by GalaxyGaming2OOO** [comment]
yeah just with piskel

sprite was called something like armempty
and was a simple rectangle with red and blue at the sides

i changed it to a more detailed one and then it crashed every time i tried to edit the sprite
i could edit it with piskel outside of gdevelop so i dont think it was corrupted and it happened yesterday a few times too

Found the image for the old one
![emptyarm](https://github.com/4ian/GDevelop/assets/110449790/6a4cc022-e23a-4951-9052-a767f86b3ef4)

again it happens randomly (for the past 3 days i have been getting it)

**Comment by ClementPasteau** [comment]
A fix has been implemented that should take care of this crash. It will be available in the next release.
If this is not fixed by then, feel free to re-open the issue!

Thanks again for taking the time to create this issue (despite the report issue button not working well!)
