### ISSUE TITLE
A crash or error happened in the game

### ISSUE THREAD

**Issue by TamDreams** [4ian/GDevelop#5884]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The cause of the error is when the number of hearts must reach 2. However, I can't find the error.
However, I never got the error in previous versions of the engine.

### Steps to reproduce

![adasdasdasd](https://github.com/4ian/GDevelop/assets/150205244/3c5e54e7-4c03-4bf9-940e-766677987843)

Video
`https://drive.google.com/file/d/1vaDzNfxDq5zpqZYZPlJCyClBx4SO-WU0/view?usp=sharing`

### GDevelop platform

Desktop

### GDevelop version

5.3.180

### Platform info

Windows 10 64 bits

### Additional context

I have found the cause of the error, it is when the number of hearts must reach 2. However, I cannot find the error.
![image](https://github.com/4ian/GDevelop/assets/150205244/580fd1b8-53fd-44ae-9796-69324c53eb80)
![image](https://github.com/4ian/GDevelop/assets/150205244/a02f5318-a330-4c28-931a-9aa436d1b10b)
![image](https://github.com/4ian/GDevelop/assets/150205244/27d88049-2fd6-444a-b97f-a7af4c29a1ed)

**Comment by arckmr** [comment]
can i work on this issue please

**Comment by TamDreams** [comment]
> ¿Puedo trabajar en este tema?

of course, although I can't figure out why the error appears

**Comment by TamDreams** [comment]
> ¿Puedo trabajar en este tema?

It's a bug that appears randomly, and it usually crashes the game for me. It appeared to me since version 5.3.180
Unfortunately I can't find out the cause.

**Comment by TamDreams** [comment]
> ¿Puedo trabajar en este tema?

I have updated the situation. There I put the video that reproduces the steps for the error. And I put the events I'm using as additional content.

**Comment by TamDreams** [comment]
Solved. What I did was leave all the collision masks on automatic. It turns out that I had the first heart animations on automatic and the rest manual. I left everything on automatic and I no longer have the error.
