### ISSUE TITLE
Add sprite bug

### ISSUE THREAD

**Issue by SukarshG** [4ian/GDevelop#5888]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When i clicked create a new sprite it said report on github/

### Steps to reproduce

Click on object then click on create a sprite

### GDevelop platform

Desktop

### GDevelop version

5

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by 4ian** [comment]
Hi, you need to include the screenshot otherwise we can't debug the issue. Thanks!

**Comment by JAdeRency** [comment]
![BUG](https://github.com/4ian/GDevelop/assets/141286066/e6232db2-4e41-4167-aa7f-f81928582c9e)

**Comment by JAdeRency** [comment]
> Hi, you need to include the screenshot otherwise we can't debug the issue. Thanks!

When I click new object this prompt appears and I could not add a new sprite or anything...

**Comment by 4ian** [comment]
Closing as duplicate: https://github.com/4ian/GDevelop/issues/5958
