### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by ParkerLynch27** [4ian/GDevelop#5890]
### Describe what you were doing when the crash happened

I pressed on the GDevelop icon and when it started up, it said this "GDevelop encountered a issue. Please backup your game file and save your game to ensure that you don't lose anything. To help up fix this issue, you can create a GitHub account then report the issue with the button below."

how do I fix this?

I am using a Windows 10.

### GDevelop version

GDevelop 5 (I think)

**Comment by 4ian** [comment]
Closing as there is no information for debugging.
