### ISSUE TITLE
Editor crash - Manipulating a Pixi object after it being destroyed (reading 'valid')

### ISSUE THREAD

**Issue by MgamingRblx** [4ian/GDevelop#5896]
### Describe what you were doing when the crash happened

i clicked in one of the button of my game and the screen popped up

### GDevelop version

5.3.180-4f98ffa9ab98b751f6526f4d8ac28cef0c16ed1e

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

TypeError: Cannot read properties of null (reading 'valid')
    at new n (https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:1946700)
    at n.value (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1963341)
    at new n (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1962325)
    at Object.createNewInstanceRenderer (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1985233)
    at https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1980574
    at mapReverseFor (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:2350186)
 ...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in Nk
    in $k
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in PI
    in div
    in n
    in Ga
    in div
    in _L
    in Unknown
    in mt
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in Re
    in n
    in ut
    in vt
    in t
    in Unknown
    in Unknown
    in v
    in It
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
Tracking this issue, it looks like it is coming from this line of PixiJS library (on the commit of 7.3.0, the version we're using)

https://github.com/pixijs/pixijs/blob/10e3bea3357c04855ef0211f30de4fcc82abbb6f/packages/core/src/textures/Texture.ts#L223

A Texture is being created, but the baseTexture is null.

The trace says this is coming from a PanelSprite: https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L101

So it means that the PixiResourcesLoader is not able to load the Texture right away https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L89-L91

Not sure how this can happen, a texture is properly created by without a baseTexture?

**Comment by ClementPasteau** [comment]
I'm wondering if those changes to the `getPixiTexture()` could be the reason https://github.com/4ian/GDevelop/commit/967033c407beb7394f2c21484000ad3a930ce589

**Comment by ClementPasteau** [comment]
Possible related issue => https://github.com/pixijs/pixijs/issues/9481

We may be manipulating a texture that's been destroyed, but cannot find how this is happening.
