### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Nanoyayay** [4ian/GDevelop#5908]
### Describe what you were doing when the crash happened

Taking pictures

### GDevelop version

5.3.180-8e668db6ea495f9cc36dcb49910d6fdce9043dfd

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

TypeError: Cannot read properties of undefined (reading 'destroy')
    at n.value (https://editor.gdevelop.io/static/js/5496.8bd264f9.chunk.js:1:1401064)
    at https://editor.gdevelop.io/static/js/main.aae1936b.js:2:501337
    at hs (https://editor.gdevelop.io/static/js/main.aae1936b.js:2:501378)
    at bs (https://editor.gdevelop.io/static/js/main.aae1936b.js:2:503647)
    at Fu (https://editor.gdevelop.io/static/js/main.aae1936b.js:2:516823)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/main.aae1936b.js:2:546759)
    at Ko (https://editor.gdevelop.io/static/js/main...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in Fk
    in Jk
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in kI
    in div
    in n
    in Ga
    in div
    in RM
    in Unknown
    in mt
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in Re
    in n
    in ut
    in vt
    in t
    in Unknown
    in Unknown
    in v
    in It
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
There's been an attempt to fix part of this issue in https://github.com/4ian/GDevelop/commit/d39cfd16a2f01bcad3f12e22d0c17581bdfef364

Looks like the InstancesEditor sometimes get unmounted without the elements inside having been initialized (how is this possible?)
I'll add more checks in this unmount to prevent such crashes, but I feel that there's another cause we're not seeing

**Comment by ClementPasteau** [comment]
Fix has been introduced and will be released in next version.
If it happens again please re-open an issue
