### ISSUE TITLE
Cannot read properties of null (reading 'getDrawableX')

### ISSUE THREAD

**Issue by TylerYale15** [4ian/GDevelop#5924]
### Describe what you were doing when the crash happened

1. Launched preview of game
2. "Slash" object collided with "Enemy" Object multiple times until enemy died
3. When "Enemy" object dies, creates particles
4. Crash happens

![image](https://github.com/4ian/GDevelop/assets/73211535/41238203-75ee-422f-8686-a404ccba968f)

These are the events used for the collisions:

![image](https://github.com/4ian/GDevelop/assets/73211535/7cf4b7c2-91f4-451b-87b7-f7f6b7cc035c)

### GDevelop version

5

### Platform info

Windows 11

### Additional error context

I was getting this crash before but with a different "Enemy" object and was able to fix it by following advice from the forums to use custom collisions for my "Enemy" and "Slash" object. This worked until now.

**Comment by 4ian** [comment]
Thanks @TylerYale15 for reporting this. We're hunting a similar problem and it would be super useful if you were able to share your game project either here if it's public, or to hello@gdevelop.io

We would then be able to fix the issue (unfortunately, just the screenshot and the partial events don't allow us to debug the problem directly).

**Comment by TylerYale15** [comment]
Than you @4ian for getting back to me on this issue! I will gladly send you the email containing the project file. At work currently so it will be a few hours before I can send it, but I appreciate the quick response! Will comment here as well when I am able to send it for extra notification.

**Comment by TylerYale15** [comment]
@4ian - Game file has been sent! :)

**Comment by 4ian** [comment]
Thanks! Your game file was super useful.

This will be fixed in next version. In the meantime, be careful not to use "Put an object around another" action with a target object that would have been deleted in the meantime (which can happen if you use "wait" for example).
