### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by furiouslebg4** [4ian/GDevelop#5957]
### Describe what you were doing when the crash happened

I was searching in the "behavior of the object" for the making the inventory

### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0, Platform: Win32

### Additional error context

uniqueErrorId: 200f7aea-7705-4c5d-9d40-acff4f937ce5

fu@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:508174
enqueueForceUpdate@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:466955
41113/_.prototype.forceUpdate@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:538892
value@https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:1291272
80227/yr/g</<.children<@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:407056
80227/Ig/<@https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:823137
fs@https://editor.gdevelop.io/static/js/main.d34efb95.js:2:500993
ds@https://editor.gdevelop.io/static/js/main.d...

### Additional component context

    in Ig
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in yr
    in div
    in s
    in f
    in Lg
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in Ag
    in div
    in s
    in iy
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
 ...

**Comment by ClementPasteau** [comment]
Closing as duplicate
