### ISSUE TITLE
Editor crash - manipulating a null texture (PixiJS)

### ISSUE THREAD

**Issue by NEJAG** [4ian/GDevelop#5997]
### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.22631, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 68b5cd27-df52-4b54-9331-54f9096ecda8

TypeError: Cannot read properties of null (reading '_batchEnabled')
    at n.value (file:///C:/Users/colin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:1924354)
    at n.value (file:///C:/Users/colin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:1926519)
    at n.value (file:///C:/Users/colin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:1926939)
    at e.value (file:///C:/Users/colin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247....

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
Error coming from Pixi renderer when trying to get `_batchEnabled` out of a `null` texture
https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/core/src/batch/BatchRenderer.ts#L452

Not sure how we ended up manipulating a null texture. Maybe a destroy that should not have happened?

**Comment by 4ian** [comment]
Closing as should have been fixed in the meantime in the latest versions.
