### ISSUE TITLE
Error while start project

### ISSUE THREAD

**Issue by TannicArcher** [4ian/GDevelop#5998]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

All time i gain 
![Снимок экрана_2023-12-04_09-29-49](https://github.com/4ian/GDevelop/assets/113786861/4d840b20-ea22-473d-8882-4244c28633d9)

### Steps to reproduce

Just start importing open projects that are available to the user any

### GDevelop platform

Desktop

### GDevelop version

5.3.181

### Platform info

Linux 23.10 Nantic

### Additional context

**Comment by AlexandreSi** [comment]
Hi @TannicArcher,
I see your interface is in russian. Are you located in Russia? There might be an issue with network restrictions.
Which example are you trying to open?
(We don't restrict opening game examples based on subscriptions.)

**Comment by TannicArcher** [comment]
If there were restrictions on the Internet, then half of the project files would simply not be downloaded at all

**Comment by TannicArcher** [comment]
![Снимок экрана_2023-12-04_12-24-12](https://github.com/4ian/GDevelop/assets/113786861/773a1f8c-fbda-4790-ab72-8a0d65c2d2c3)
 in web editor same problem

**Comment by AlexandreSi** [comment]
How is your internet? The error says that the server took too long to respond.

**Comment by TannicArcher** [comment]
I won't say that the Internet is bad.
As for me the results are normal.

![Снимок экрана_2023-12-05_14-13-44](https://github.com/4ian/GDevelop/assets/113786861/831699fa-e27d-49f5-b6dd-f72e5ef224f9)

**Comment by AlexandreSi** [comment]
Could you open the developer tool (Ctrl + Shift + i), go in the Network tab, try to open an example and see all the requests that fail.
You could try to pick one of those failed requests, copy the url and try to open it in a new tab, maybe there will be more details about why it failed?

**Comment by TannicArcher** [comment]
It’s strange, but now I checked the project, it downloaded without problems, not a single error appeared.
Most likely the problem was on the Internet, although mine is fine

**Comment by AlexandreSi** [comment]
Ok, it's likely it was due to a network error.
We also changed some things around examples ressources urls but it wouldn't have resulted in time out errors.
I'm closing this issue, feel free to re-open it if you encounter the problem again.
