### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by bigMacha1** [4ian/GDevelop#6008]
### Describe what you were doing when the crash happened

I went to edit an abject/sprite and tried to add a behavior and it said I should because of a memory error, now i can edit the sprite without it saying that

### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36, Platform: Linux x86_64

### Additional error context

uniqueErrorId: 64f780eb-5f65-4491-b83f-6186817947d6

RuntimeError: memory access out of bounds
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:wasm-function[3556]:0xaf7c3
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:wasm-function[3416]:0xa728f
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:wasm-function[3139]:0x918b4
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:wasm-function[2453]:0x6671a
    at https://edi...

### Additional component context

    in Ag
    in div
    in s
    in iy
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in xy
    in n
    in t
    in Unknown
    in by
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in pM
    in div
    in n
    in Ga
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
...

**Comment by ClementPasteau** [comment]
Closing this without more info
