### ISSUE TITLE
[Blocked] Replace old variable icons with new brand icons

### ISSUE THREAD

**Issue by LuniMoon** [4ian/GDevelop#6041]
> Note:
This change to update to today's icons has resistance and I do not have any user testing that brings any evidence on which is best (it's the kind of thing that requires A/B testing in app which is not possible today).
I've marked it as blocked for now.

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Brought to my attention after seeing [this issue](https://forum.gdevelop.io/t/different-color-icons-for-variable-per-type/51539)*.

Current icons are the old icons
![image](https://github.com/4ian/GDevelop/assets/103995399/63e88087-d5f1-4352-bc96-b609a2adf729)

Please replace them with today's Icons (refer to the Figma file "App Icons".
<img width="622" alt="Screenshot 2023-12-08 at 13 58 16" src="https://github.com/4ian/GDevelop/assets/103995399/7113cd08-fd06-49ce-8af6-783f818b0a89">
You can press Ctrl+F to find the following images: "World", "Scene", "Box".

**Note: Changing text colour depending on the Variable type was suggested by the user. However I won't request it because I am not sure about the implications of assigning different colour to each Condition/Action variation on the engine.*

### Steps to reproduce

N/A

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

N/A

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ZachjuKamashi** [comment]
This change may not be as good, as it's harder to differentiate between 3 different types of variables due to the new ones using only the same color.

**Comment by BigChalkGames** [comment]
I agree with ZachjuKamashi. Whilst the icon changes will be a nice addition, I think colors are going to go a lot further when it comes to differentiating between the types.

Colors should be added to the below choices as well so you know at a glance what is a obj, scene or global.
![image](https://github.com/4ian/GDevelop/assets/150500902/21ac31d7-17e6-47c0-9de0-0e01f5ad4f5e)

**Comment by LuniMoon** [comment]
Thank you for sharing your opinion regarding the architecture colours.
However, I won't require any colour change yet because it requires more thinking: If each architecture notion has a colour they would have to apply to all elements that have "global, scene, object" notion and I'd like to make sure that they're accessible.
Also, an internal ticket has been created to explore work to simplify that list (which might cancel the need for differentiating the list with colours).
> Core team, please refer to "AAU I see a more digestive list of Variables whenever I am working on my Events" on the "Product backlog" internal Notion.

I am keeping this ticket "icon change" only, and not request further changes.
Nevertheless, I'll keep an eye about colour conversations on the [Feature request topic](https://forum.gdevelop.io/t/different-color-icons-for-variable-per-type/51539/2).

**Comment by ZachjuKamashi** [comment]
> I am keeping this ticket "icon change" only, and not request further changes. Nevertheless, I'll keep an eye about colour conversations on the [Feature request topic](https://forum.gdevelop.io/t/different-color-icons-for-variable-per-type/51539/2).

I view this icon change as a downgrade rather than upgrade. Currently the old ones are much more distinct due to them having different colors in their icons, like white within the scene icon and black within the object icon. This icon change removes those entirely and then they would all be the same color. This makes it more difficult to look at a glance on what variable you are dealing with. 

I wouldn't push this change upon all users unless a solution to this issue is solved.

**Comment by LuniMoon** [comment]
I was thinking more about round, rectangle, prism shape for recognition by stripping the colours.

Note:
This change to update to today's icons has resistance and I do not have any user testing that brings any evidence on which is best (it's the kind of thing that requires A/B testing in app which is not possible today).
I've marked it as blocked for now.
