### ISSUE TITLE
Changing the focus on a button

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#6065]
## Description

When deleting an animation a popup of confirmation open up, the focus is not set correctly.

![Animation](https://github.com/4ian/GDevelop/assets/1670670/338db406-21fd-4def-a7e1-6cbe081e2821)

On this GIF I'm pressing Enter when the popup come, then left and right arrows, then Escape.
But nothing happend because the binding is unknown.
Worse the popup blink, it closed and reopened quickly, maybe because the focus is on the Trash icon that I clicked ?

## Solution suggested

Focus by default on the delete button.
And allow to use the arrows to switch from a delete to cancel, and bind escape key as shortcut to cancel.

**Comment by ClementPasteau** [comment]
I'm not sure about the blinking, this is odd and doesn't happen on mine.
Regarding arrows, this is not common in accessibility. The way to navigate buttons is to use "Tab" and "Shift+Tab" to move from one button to the other I believe.

I agree with the rest, we forgot to add the ability to cancel/confirm on those dialogs, I'll add them

**Comment by Bouh** [comment]
The main request on this issue has been fixed, the other things are anecdotic and can be forget.
Thanks for the change.
