### ISSUE TITLE
Editor crash - error while reading currently running in-app tutorial

### ISSUE THREAD

**Issue by StarShapedTriangle** [4ian/GDevelop#6066]
### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36, Platform: MacIntel

### Additional error context

uniqueErrorId: 6f390253-b859-4568-a273-75ea02f69183

TypeError: Cannot read properties of undefined (reading 'length')
    at https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1803008
    at ea (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:475626)
    at La (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:483610)
    at Ss (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:524116)
    at Eu (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:514598)
    at wu (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:514523)
    at gu (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:511525)
    at h...

### Additional component context

    in ForwardRef
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c...

**Comment by ClementPasteau** [comment]
It seems to be coming from getting the length of the flow of an in-app-tutorial, and looks like the flow was undefined.
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/InAppTutorial/InAppTutorialOrchestrator.js#L455

**Comment by ClementPasteau** [comment]
Possibly an unexpected response from an endpoint leading to this (or from reading the file locally)
