### ISSUE TITLE
3D Animations don't work

### ISSUE THREAD

**Issue by TheAvIGOLD** [4ian/GDevelop#6081]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hi, in the latest update, 3D models stopped seeing animations. If the object was added before the update, then you will not see animations in the editor, but you can select them by number (this does not work for new objects)

### Steps to reproduce

![image](https://github.com/4ian/GDevelop/assets/19785639/7985b5c2-fcb7-45b9-8b70-b2668ed76067)
![image](https://github.com/4ian/GDevelop/assets/19785639/ad8ad164-ebd2-4f9e-a31e-3eaae80b24fa)

### GDevelop platform

Desktop

### GDevelop version

5.3.184-465e9346053202130bb4942e66d84bca2570cc5b

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GDevelop/pull/6080 - thanks for the report
