### ISSUE TITLE
The Easing Tween tips are missing

### ISSUE THREAD

**Issue by TheAvIGOLD** [4ian/GDevelop#6084]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Before the update, when focusing on the easing field, a selection of prompts appeared. Now it's gone.

### Steps to reproduce

![image](https://github.com/4ian/GDevelop/assets/19785639/0962b25c-6481-4604-a739-4fe22d4b402d)
![image](https://github.com/4ian/GDevelop/assets/19785639/829d775a-6e36-4174-8f26-e0bdb58f574e)

### GDevelop platform

Desktop

### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Thanks for reporting, a fix is being worked on

**Comment by ClementPasteau** [comment]
Reopening issue for visibility. We'll close it when a new release it out

**Comment by ClementPasteau** [comment]
Fixed in 5.3.186
