### ISSUE TITLE
Editor crash - geometry is null but still rendered by PixiJS after deleting instance

### ISSUE THREAD

**Issue by SweatyGoblinStudios** [4ian/GDevelop#6111]
### Describe what you were doing when the crash happened

The volume slider assets from in-store did not work in one of my scenes. The sliders had a white X over them with a red background. 
![errorrrrr](https://github.com/4ian/GDevelop/assets/154453669/e5dffafc-b116-4617-94d9-f50d870b2416)
I deleted them, and then I was prompted with an error.

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 478b48b8-d635-4196-8b51-70a8f3b3a3c7

TypeError: Cannot read properties of null (reading 'buffers')
    at e.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1971849)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1924099)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1925007)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/3533.17e31c2f.chunk.js:2:1925394)
    at e.value (file:///C:/Program%20Files/GDevelop/resources/...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in mw
    in Mw
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
Thanks for reporting the issue.
Just to be sure, which slider are you talking about exactly?
Have you been manipulating the folders of your project which may have caused the texture of the slider to be not found?

The error is coming from Pixi, when trying to update the geometry and it actually doesn't exist anymore: https://github.com/pixijs/pixijs/blob/132fcb9cea07a869340d99fc8b96a47db2126aa9/packages/core/src/geometry/GeometrySystem.ts#L206

**Comment by 4ian** [comment]
Closing as texture handling should be safe now.
