### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by magicalbathmat** [4ian/GDevelop#6124]
### Describe what you were doing when the crash happened

Every game I try and start it keeps telling me this when I go to add behaviors.  Please help.

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: e985ebaa-653e-4492-88a6-ed7c6d319158

RuntimeError: null function or function signature mismatch
    at wasm://wasm/00b41e4e:wasm-function[4194]:0x1cc732
    at BehaviorMetadata.GetRequiredBehaviorTypes.BehaviorMetadata.GetRequiredBehaviorTypes [as getRequiredBehaviorTypes] (file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1248064)
    at file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/2198.9b9e32d9.chunk.js:1:932166
    at file:///C:/Users/alans/AppData/Local/Programs/GDevelop/resources/app...

### Additional component context

    in ax
    in div
    in s
    in Ay
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Wy
    in n
    in t
    in Unknown
    in Yy
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
...

**Comment by ClementPasteau** [comment]
duplicate
