### ISSUE TITLE
Particle emitter has a huge memory issue

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#6125]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As the title suggests, there is a huge memory issue regarding the particle emitter where it acts as it doesn't get deleted, even though it should resulting in huge amount of ram usage. This doesn't also go away if you reload the scene or go to another, the ram usage stays the same.

![Screenshot (649)](https://github.com/4ian/GDevelop/assets/98941240/cfb8da44-f83f-4684-8e09-b7deee401d43)

[MemoryLeakFoundPartThree.zip](https://github.com/4ian/GDevelop/files/13762886/MemoryLeakFoundPartThree.zip)

### Steps to reproduce

1. create a simple particle emitter
2. use the particle emitter many times
3. Observe results after a little while

Instructions also included in test project

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.3.186

### Platform info

Windows 10 LTSC 21H2 (OS Build 19044. 1288)

**Comment by VanCastar** [comment]
Could this be a related issue that was reported in here?
#3496

**Comment by ZachjuKamashi** [comment]
> Could this be a related issue that was reported in here? #3496

Maybe? but really high ram usage was never mentioned or talked about in it. though a memory leak is indeed mentioned. I opened the project of that issue and the ram usage does indeed increase about as much as this one if maybe a little slower so it is related. It would also appear this memory issue also leaks into the editor as I left it running until it consumed 5GB of ram, closed the preview and now it's staying at 1.2GB of ram usage versus before where it was around 80mb for that process.

**Comment by D8H** [comment]
Was the issue with the 3D particle emitter or the 2D one?

**Comment by ZachjuKamashi** [comment]
> Was the issue with the 3D particle emitter or the 2D one?

This specific issue is for the 2D particle emitter. Refer to the test project included in this post alongside the screenshot

**Comment by ZachjuKamashi** [comment]
After leaving the bug report test project running on background for half an hour, I can confirm that this bug has indeed been fixed

**Comment by D8H** [comment]
Thank you for testing it
