### ISSUE TITLE
Tweening the scale of an object to 0 is instantaneous (plus some other oddities)

### ISSUE THREAD

**Issue by lhphr** [4ian/GDevelop#6135]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Attempting to tween an object's scale to 0 will cause it to become a scale of 0 instantaneously.
Attempting to tween an object's scale if the scale already is 0 will change the scale to NaN.

This bug is nonexistent when scaling the object via "Tween object height" or "Tween object width".

### Steps to reproduce

Admittedly self-explanatory, but:

1. Tween the scale of an object to 0, say, by using "Tween object scale".
2. *poof*

For the other bug:

1. Tween the scale of an object to something that would make it visible.
2. So... where is it?

[Here is a test project file showing the odd behaviour.](https://github.com/4ian/GDevelop/files/13795605/oops.zip)

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.3.186

### Platform info

Windows 10 Pro 21H1

**Comment by ClementPasteau** [comment]
Thanks for reporting and for the test project @lhphr 

I don't remember exactly how tweens are implemented but I do remember this is kind of an "expected" behavior and that 0 cannot really be used for tweens.
Am I getting this right @D8H ?

**Comment by lhphr** [comment]
I'm assuming this was forgotten open so I may as well close this, as the former issue isn't really an issue (it's just the way it's implemented) and the latter one has been fixed.
