### ISSUE TITLE
Renaming a layer causes objects in external layouts to become invisible 

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#6136]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Renaming a layer causes objects in external layouts to become invisible 

### Steps to reproduce

1. Create a new layer
2. Create an external layout
3. Add objects to the external layout on the new layer
4. Rename that layer
5. Objects instances in the external layout become invisible because they are still assigned the old name of the layer

Notes:
- You can still select these instances in the editor, although the selection boxes are always at 0,0
- In the game, the objects appear at 0,0 on the base layer
- Changing the layer of the instances to the new name will make the objects reappear

![image](https://github.com/4ian/GDevelop/assets/8879811/882ac9ed-1559-4dcc-aa4e-8cb88908e133)

### GDevelop platform

Desktop

### GDevelop version

5.3.186

### Platform info

Windows 11

**Comment by ClementPasteau** [comment]
I can confirm I reproduce this.
Closing and reopening the layout doesn't solve it either, so it's indeed a renaming of the layer in the external layout that is not happening.

(Note that renaming the layout in the external layout will rename it in main scene, so it works the other way)

**Comment by ClementPasteau** [comment]
Thanks for the report @tristanbob this will be available in next release
