### ISSUE TITLE
Editor crash - using a non-existing structure property in an expression

### ISSUE THREAD

**Issue by doug13579** [4ian/GDevelop#6137]
### Describe what you were doing when the crash happened

Added ammo[1].max for the value of anything. In this case opacity. If the variable isn't defined it crashes when you click away from the field by doing something like clicking the background or another property box. It seems to be related to arrays of structures. It seems to be in the lost focus part. It happens in the app and while using the online version

app:
https://github.com/4ian/GDevelop/assets/113511006/a61d3fab-ac83-47b2-9d93-0386fbbb4ceb

web:
![image](https://github.com/4ian/GDevelop/assets/113511006/db7b3666-ee90-4d70-a166-b11804c40cda)

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: ecd1a66a-9f87-4481-a709-225f78b1cb62

RuntimeError: memory access out of bounds
    at wasm://wasm/00b41e4e:wasm-function[832]:0x495ee
    at wasm://wasm/00b41e4e:wasm-function[1266]:0x7cc81
    at wasm://wasm/00b41e4e:wasm-function[2561]:0x18aae7
    at wasm://wasm/00b41e4e:wasm-function[2590]:0x18bc10
    at wasm://wasm/00b41e4e:wasm-function[3968]:0x1c16c8
    at Function.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor [as getCompletionDescriptionsFor] (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster...

### Additional component context

    in n
    in ForwardRef
    in div
    in s
    in f
    in div
    in div
    in s
    in div
    in ForwardRef
    in t
    in ForwardRef
    in div
    in div
    in a
    in Jg
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in dx
    in t
    in Unknown
    in px
    in t
    in div
    in n
    in l
    in n
    in ForwardRef(Em)
    in n
    in t
    in Unknown
    in QM
    in di...

**Comment by ClementPasteau** [comment]
Thanks @doug13579 I can reproduce this consistently, we'll fix it
