### ISSUE TITLE
iOS does not open URLs

### ISSUE THREAD

**Issue by konguele** [4ian/GDevelop#6154]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Good Morning,

I've noticed that when I publish my app on iOS, it can't open the links. I have social media links (to try to open the app or the browser) and links that require the browser because it is a website. 

Apparently they don't work for iOS and there aren't many options to open the links. Does the URL have to contain a specific format?

<img width="996" alt="Captura de pantalla 2024-01-08 083213" src="https://github.com/4ian/GDevelop/assets/64000046/07885b26-84c2-41de-9b64-20d6037c3733">
<img width="1223" alt="Captura de pantalla 2024-01-08 083301" src="https://github.com/4ian/GDevelop/assets/64000046/a57b79d3-603f-4efc-92a2-d1fd8a0841b2">

Thank you for your help.

### Steps to reproduce

Click on an image and access to the URL. Only doesn't work for iOS

### GDevelop platform

Mobile

### GDevelop version

5.3.186

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
This is the code being used to open URLs in this action.
https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.ts#L853-L867

It is possible the combination of ios/cordova makes window.open() not work as expected (I've seen other complain on the web about this, possibly linked to a native ios popup blocker)

I don't have a solution for this though as it's quite specific and cumbersome to test, you may need to experiment using custom JS events and try different ways of opening a URL until you find one that works.

**Comment by josephspagnuolo** [comment]
I am currently facing the same issue. Do you have any update on this or any workarounds you have used? @konguele

**Comment by konguele** [comment]
Hello @josephspagnuolo ,

For mi it's solved. I'll explain step by step what I'm doing:

1- In the config.xml file I add the cordova-plugin-inappbrowser plugin:
<plugin name="cordova-plugin-inappbrowser" spec="6.0.0">
</plugin>

2- I modify the code in the files code0 www and code0 staging.
a) I deleted the old code:
```
if (isConditionTrue_0) {
{gdjs.evtTools.window.openURL("https://www.instagram.com/stiluproject/", runtimeScene);
}}
```
b) I added this code:
```
if (isConditionTrue_0) {
        var url = "https://www.instagram.com/stiluproject/";
        if (typeof window.cordova !== "undefined") {
            var target = "_system";
            var options = "location=yes";
            cordova.InAppBrowser.open(url, target, options);
        } else {
            window.open(url, "_blank");
        }
    }
```

**Comment by josephspagnuolo** [comment]
Great stuff man!!!!! This worked for me thanks a lot. I also had to run cordova build to install the plugin. @konguele

**Comment by konguele** [comment]
@josephspagnuolo Since we are exchanging information, it has nothing to do with this problem, but you wouldn't happen to be working with the IAP extension, would you? I need help with that.
