### ISSUE TITLE
Edit with pixel option nit available and cant move or locate in the scene please fix

### ISSUE THREAD

**Issue by muid12** [4ian/GDevelop#6173]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Edit with pixel option nit available and cant move or locate in the scene please fix

### Steps to reproduce

Double click on sprite and edit with pisel not available

### GDevelop platform

Mobile

### GDevelop version

Latest version 

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>app

### Additional context

Please fix

**Comment by ClementPasteau** [comment]
Missing information from this issue. Please share screenshots or videos of what you're seeing.
