### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Astr092** [4ian/GDevelop#6176]
### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.15.7, Arch: x64, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: darwin

### Additional error context

uniqueErrorId: 3bf22ad4-6d75-49c9-b5dd-a8e604aa1f2d

RuntimeError: null function or function signature mismatch
    at wasm://wasm/00b41ea6:wasm-function[4194]:0x1cc732
    at BehaviorMetadata.GetRequiredBehaviorTypes.BehaviorMetadata.GetRequiredBehaviorTypes [as getRequiredBehaviorTypes] (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js?cache-buster=5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b:9:1248064)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/3611.839c7dea.chunk.js:1:844421
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/3611...

### Additional component context

    in qg
    in div
    in s
    in Cy
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Ay
    in n
    in t
    in Unknown
    in Ry
    in t
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in UM
    in div
    in n
    in Ji
    in div
    in VA
    in Unknown
    in Qe
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
...

**Comment by ClementPasteau** [comment]
Duplicate
