### ISSUE TITLE
Add CTRL+D shortcut to duplicate

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#6194]
## Description

Please add the CTRL+D duplicate on the object list.
![image](https://github.com/4ian/GDevelop/assets/1670670/0ab542af-2065-42b0-81c1-9a03a1f853e6)

**Comment by JohhnSmithh** [comment]
I am a first time contributor wondering if I could help with this issue for a class assignment. I think I may be able to help with this issue. 
Before I am able to get started, however, I am having some issues with setting up the development environment. Specifically, when I run npm start to start the development server as outlined in the README I get errors that I cannot resolve extensions. If this is an easy fix to get started maybe someone can help

**Comment by Ceebox** [comment]
Is this a great idea? I got this to work and found out that CTRL+D is also the key that bookmarks pages.

**Comment by Bouh** [comment]
This default Chrome or brownser behavior can be prevent by a Javscript code like:
[https://stackoverflow.com/questions/46106766/detecting-control-d-in-my-code-also-triggers-add-bookmark-keyboard-shortcut-in](https://stackoverflow.com/questions/46106766/detecting-control-d-in-my-code-also-triggers-add-bookmark-keyboard-shortcut-in)

**Comment by Ceebox** [comment]
I was more suggesting that we don't do that anywhere else in the codebase (to my knowledge), would it perhaps be better to change the keybind?

**Comment by osmaneTKT** [comment]
Hi @bouh, I'm going to take your advice and tackle this issue to pass my course

**Comment by 9Amit** [comment]
document.addEventListener('keydown', (e) => {
  const { key, ctrlKey } = e;
  if (ctrlKey && key.toLowerCase() === 'd') {
    console.log('Ctrl+D');
    e.preventDefault();
  }
});

**Comment by osmaneTKT** [comment]
hello @9Amit i am on this issue

**Comment by osmaneTKT** [comment]
Hi @Bouh , I've fixed the problem
