### ISSUE TITLE
Extensions editor crash when accessing object groups list (global)

### ISSUE THREAD

**Issue by gabrielzv1233** [4ian/GDevelop#6230]
### Describe what you were doing when the crash happened

[Screen recording 2024-01-20 7.34.10 PM.webm](https://github.com/4ian/GDevelop/assets/77300296/e5df0e9b-94c6-4804-a844-5423a0911527)
just before the crash I right clicked and instantly it crashes, happens 100% of the time

### GDevelop version

5.3.187-7fbe1bd23dfee19829f238048afd4c7ac84a00cf

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36, Platform: Linux x86_64

### Additional error context

uniqueErrorId: b6408299-0c4c-47fb-a497-3ab024739fd9

TypeError: Cannot read properties of null (reading 'map')
    at e.value (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:2499450)
    at children (https://editor.gdevelop.io/static/js/283.9734dfe9.chunk.js:1:2501588)
    at t.value (https://editor.gdevelop.io/static/js/main.14977905.js:2:244866)
    at Wa (https://editor.gdevelop.io/static/js/main.14977905.js:2:491872)
    at za (https://editor.gdevelop.io/static/js/main.14977905.js:2:491665)
    at Ss (https://editor.gdevelop.io/static/js/main.14977905.js:2:527409)
    at Eu (https://editor.gdevelop.io/static/js/main.14977905.js...

### Additional component context

    in t
    in ForwardRef
    in ForwardRef(nb)
    in div
    in t
    in div
    in t
    in div
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Fh
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in ForwardRef
    in n
    in div
    in s
    in n
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Fh
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in k
    in t
    in div
    in div
    in t
    in div
    in t
    in n
    in l
    in n
    in div
    in n
    in t
    in Unkn...

**Comment by ClementPasteau** [comment]
Thanks for the report @gabrielzv1233 

Looks similar to #6258 - we're looking at it

**Comment by AlexandreSi** [comment]
Closing this as it should have been fixed by #6263
