### ISSUE TITLE
Crash while using extension editor - can't add or edit sprites for custom objects

### ISSUE THREAD

**Issue by doug13579** [4ian/GDevelop#6258]
### Describe what you were doing when the crash happened

I added a custom object
clicked the [children] tab,
clicked add object and selected sprite
it crashes immediately

### GDevelop version

5.3.187-9eb721662f404d9cc215467ab132bf977fb24121

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.187 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: b4c21804-0498-440a-8a8f-858be84b1475

TypeError: Cannot read properties of undefined (reading 'createDisplayName')
    at children (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/static/js/283.8113e3ca.chunk.js:1:2156475)
    at t.value (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/static/js/main.69f282b5.js:2:245124)
    at Wa (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/static/js/main.69f282b5.js:2:492130)
    at za (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/static/js/main.69f282b5.js:2:491923)
  ...

### Additional component context

    in t
    in zt
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in T
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in PZ
    in n
    in t
    in Unknown
    in IZ
    in t
    in n
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Fh
    in FZ
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in k
    in t
    in div
    in div
   ...

**Comment by ClementPasteau** [comment]
Thanks for the report @doug13579 - probably linked to the changes we've done in the objects structure. we're looking at it

**Comment by D8H** [comment]
Thank you for reporting this. It should be fixed in the next release.

As a workaround, the sprite child is actually added before the crash, so if you go back to the custom object, you should see it in the list.

**Comment by doug13579** [comment]
thanks for the quick response

**Comment by doug13579** [comment]
> Thank you for reporting this. It should be fixed in the next release.
> 
> As a workaround, the sprite child is actually added before the crash, so if you go back to the custom object, you should see it in the list.

While it does still add a sprite I still can't open the properties by double clicking on it or selecting "edit" from the right mouse button popup. I can select "behaviors", "variables" or "effects" but clicking on the properties tab causes it to give the same error.

![image](https://github.com/4ian/GDevelop/assets/113511006/320abc98-b7be-4d37-b68f-1e08e156c05f)

**Comment by ClementPasteau** [comment]
This should be fixed in the 5.3.188
