### ISSUE TITLE
Opacity is missing in conditions/actions for Button object 

### ISSUE THREAD

**Issue by LousyMolars** [4ian/GDevelop#6272]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Can not find opacity action/condition for Button object. If there are some technical limitations/reasons for this, then why tweening opacity works correct? 
![image](https://github.com/4ian/GDevelop/assets/141857198/7abbc692-de8c-4dc2-adf2-a3e40380b3b8)

Sorry, if this is known and explained ages ago, could not find anything.

### Steps to reproduce

1. Create Button object.
2. Search for action that lets set opacity for this object. Or condition to check current opacity level.

### GDevelop platform

Desktop

### GDevelop version

5.3.187

### Platform info

<details>

*Win 11*
>

</details>

**Comment by 4ian** [comment]
@D8H is on it :)

**Comment by 4ian** [comment]
Actually this should have been fixed by https://github.com/4ian/GDevelop/commit/3568a58019672e6546c0e569f8894ea3c663ff5f - right @D8H?

**Comment by D8H** [comment]
Indeed
