### ISSUE TITLE
Undo and Redo doesn't work in the event sheet at all

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#628]
## Describe the bug
It seems that it's not implemented yet - you can't actually undo an action in the event sheet. I am not sure if we actually have it. Need to check

## To Reproduce
Delete an event, then hit ctrl+z - it doesnt work
Move an event, ctrl+z - doesn't work
Change parameters of an event - ctrl+z doesn't work

Try using undo from the menu - doesn't work

## Other details
This is possibly a missing feature. We do have undo/redo in the scene editor, but not in the event sheet. I wonder if using undo in the event sheet actually triggers an undo in the scene editor. It is worth investigating how its implemented in the scene editor

**Comment by 4ian** [comment]
Strange, I've tested and was able to Ctrl+Z a drag'n'dropped move of an action.
I'm on macOS, maybe it's related? What is your GDevelop version and OS?

**Comment by blurymind** [comment]
I will try again later today after work. 
I am on Windows 10, running the latest release - beta51

**Comment by zatsme** [comment]
Works fine here, Windows 10 Latest GDevelop compiled from source. I can ctrl+z and ctrl+y to undo anything you can copy and paste...   On this track and from the Discord chat last night it would be very nice to be able to copy/paste/drag etc groups and also multi selected items, not yet implemented I think.

**Comment by 4ian** [comment]
> copy/paste/drag etc groups

It should be possible to copy/paste them (as well as any event) and drag them too.

> multi selected items

Yep it's not supported for now. I created a card for this: https://trello.com/c/h927zcDM/155-support-dragndrop-for-multiple-events-like-actions-conditions to track the need for this.

**Comment by 4ian** [comment]
Ok so I guess there is possibly something wrong with shortcut handling on Windows?
If someone has the development version running, can you try adding `console.log("hello world")` in `newIDE/app/src/EventsSheet/index.js` inside the function `undo = () => {` and `redo = () => {` (just before `if (!canUndo(this.state.history)) return;` and `if (!canRedo(this.state.history)) return;`) and then see if the "hello world" messages are appearing when you press Ctrl+Z or Ctrl+Y?

**Comment by zatsme** [comment]
I'm out on the road all day so cannot test, but when I try to right click a group on win 10 the menu pops up for a brief moment, maybe 0.1 seconds and then disappears.  I guessed it wasn't supported yet?

**Comment by blurymind** [comment]
@4ian I will give this a try at home later :)

**Comment by 4ian** [comment]
@blurymind Thanks let me know how it goes :)

**Comment by zatsme** [comment]
If you right click on a Comment or Group event after you have given it input focus you get the very brief menu popup.  If you are not editing it then the menu works as it should.  Probably correct behaviour but would be better if the menu doesn't appear at all.

Events are definitely not generating change history on Windows 10

**Comment by blurymind** [comment]
@4ian very strange, when I run a build  from git, undo/redo works on:
- deleting an event
- moving an action/condition
- Moving an event row seems to trigger two undo steps (try deleting a condition, them moving the event row it was on, then when you undo once- gd will move it back to where it was, but also bring back the condition you deleted)
... however it scrolls the event sheet to the top  

It doesn work on:
- adding a condition/action 

The hello message gets printed. On the actual compiled release build here on git -it doesnt work at all

**Comment by 4ian** [comment]
> I've noticed moving events doesn't generate changes history

Correct! I've fixed this. :)

> Moving an event row seems to trigger two undo steps

This is because moving events does not generate changes history as Lizard-13 mentioned, so it looks like there are two steps done in once (but in reality, there was no step registered).

>It doesn work on:
>adding a condition/action

Could you double check this? I think you may have been confused by moving events that is not registering a step? I've been able to add an action and undo/redo it.

I've also fixed the case where you drag an action/condition while pressing Ctrl (or Cmd) to duplicate the action/condition (this would not register a step, like moving events, so undo/redo will go like "2 steps" backward/forward).

**Comment by 4ian** [comment]
Ok turns out that I fixed shortcuts for events sheet a while ago after beta 51 was out! So should be fixed in beta 52 :D Sorry for the confusion!

**Comment by blurymind** [comment]
Thank you @4ian 
I think we can close this now :)
