### ISSUE TITLE
In App Purchase is stuck after the purchase

### ISSUE THREAD

**Issue by konguele** [4ian/GDevelop#6311]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello,

I have created an in-game purchase, it works correctly, but when the in-game purchase message appears on any consumable item 2 things happen:
- If it is the first purchase, it is duplicated
- If it is the second purchase, the game freezes and stops working.
![4](https://github.com/4ian/GDevelop/assets/64000046/bf0b8a1c-959b-4e45-97cd-fdaa34279342)

It is all in the same position as in the example in Gdevelop (https://gdevelop.io/game-example/free/in-app-purchase).

At the beginning of the scene:
<img width="1219" alt="SS1" src="https://github.com/4ian/GDevelop/assets/64000046/8e1a0cbb-a10a-4382-bd27-d62869d9efb2">

Inside Store is ready:
<img width="1128" alt="Captura de pantalla 2024-02-01 a las 15 51 28" src="https://github.com/4ian/GDevelop/assets/64000046/e30d3dc4-8837-4248-9d44-60a309ba0c51">
<img width="1128" alt="Captura de pantalla 2024-02-01 a las 15 51 28" src="https://github.com/4ian/GDevelop/assets/64000046/914edb45-8bf0-462a-bb5e-aebc72d96619">

I don't understand if it's a bug, if there's a loop or what's going on, could you please help me with this error? I don't see where the problem could be.

### Steps to reproduce

1. I add all the details of the purchase
2. Compile the game and run it on an iOS device
3. I make a purchase, even the coins are loaded and I see the OK
4. IAP failure

### GDevelop platform

Desktop

### GDevelop version

5.3.187

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Hello, as explained in the other issue you've opened (https://github.com/4ian/GDevelop/issues/6226#issuecomment-1900641184), the in-app-purchase extension is on the extensions repository https://github.com/GDevelopApp/GDevelop-extensions so your issue is best to be created there.

This extension has some flaws and would need a rewrite, you're welcome to contribue by submitting a PR.

**Comment by konguele** [comment]
Sorry, I will post it on the other side. Thanks for your comments.
