### ISSUE TITLE
GDevelop exports corrupted AAB file

### ISSUE THREAD

**Issue by fizzingpop** [4ian/GDevelop#6339]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

This has happened to me a few times now where GD exports a faulty AAB file that gets rejected by the Play Store while the APK file works perfectly fine on my device. The only fix is to restart GD and export again. A curious difference is the working AAB is slightly bigger than the corrupted AAB with no changes in the editor.

### Steps to reproduce

Unknown but maybe having the GDevelop editor open for too long because restarting the editor seems to fix exporting corrupted AABs.

### GDevelop platform

Desktop

### GDevelop version

5.3.189 but has happened on earlier versions

### Platform info

<details>

Windows 11
>

</details>

**Comment by 4ian** [comment]
Hi! Thanks for reporting this.

> that gets rejected by the Play Store

It would be useful to know what is the error message, to see what could go wrong?

**Comment by fizzingpop** [comment]
According to Google:

Issue found: Violation of Broken Functionality policy
Your app contains content that isn’t compliant with the Broken Functionality policy.

App installs, but doesn't load.

Restarting the editor and re-exporting fixes the issues. I believe some files are not being packaged properly because the working export is larger even though I made no changes before exporting again. Take a look:

![0](https://github.com/4ian/GDevelop/assets/133285547/27f76b77-bd66-4ef3-8856-804194871755)
