### ISSUE TITLE
Equally named sprites conflict

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#635]
## Describe the bug
A sprite resource doesn't save its relative location but only the filename. This causes trouble when multiple images share the same name but are located in separate sub folders.

## To Reproduce
See attached example project: [equal_named_sprites_bug.tar.gz](https://github.com/4ian/GDevelop/files/2374290/equal_named_sprites_bug.tar.gz)
- The redparrot sprite object has a red square (idle.png) assigned which is located in the "redparrot" subfolder
- The blueparrot sprite object currently has no image attached. Choose the idle.png from the blueparrot subfolder.
- Eventhough you have chosen the blue square the sprite object now displays the red square.

## Suggestion
Save the relative file path underneath the project folder as part of the resource identifier (~~mygame/~~**images/blueparrot/idle.png**) and only display the part behind the last "/" as the image name like ~~mygame/images/blueparrot/~~**idle.png** in the resources list.

**Comment by 4ian** [comment]
> Save the relative file path underneath the project folder as part of the resource identifier (mygame/images/blueparrot/idle.png) 

This is a good solution.

> only display the part behind the last "/" as the image name like mygame/images/blueparrot/idle.png in the resources list.

No, this will only confuse users. If resources have different names, then they should be displayed with different names :)

**Comment by blurymind** [comment]
I will try to do a fix pull on this - this week, while I am at it. It affects my pull.
Is it ok to use "." instead of "-" to replace the "/"?

ide/sprite.png --> idle.sprite.png ?

**Comment by zatsme** [comment]
Surely the / makes it obvious it's a relative path.  Why change to "." ?

**Comment by blurymind** [comment]
@zatsme using a "/" inside filenames is prohibited, but for resource names could be ok?
@4ian what do you think? Should the "/" be replaced?

**Comment by Wend1go** [comment]
On the other hand "." is a valid character in a filename and folder name. So if for some reason the string is needed to locate the image it could cause trouble.

**Comment by 4ian** [comment]
Let's use "/". Using another character will cause more confusion I think.
Resource names are strings, not filenames, so "/" should work.

**Comment by blurymind** [comment]
I think I can tackle this in my pull here
https://github.com/4ian/GDevelop/pull/634

**Comment by blurymind** [comment]
bug fixed and merged now. This can be closed I think. Feel free to test and report if it's still there :)

**Comment by 4ian** [comment]
Should make things less confusing in case of using folder yeah :) Closing this now!
