### ISSUE TITLE
iOS crash "evaulating new THREE_ADDONS.EffectComposer"

### ISSUE THREAD

**Issue by arow102** [4ian/GDevelop#6352]
### Describe what you were doing when the crash happened

![IMG_1151](https://github.com/4ian/GDevelop/assets/101535997/f5d4d7d8-d660-4226-8b92-968b85ece77b)

### GDevelop version

On iPad newest update

**Comment by arow102** [comment]
No I do not think that it has been happening anymore but thank you

-- 


*This email is sent from an address issued by Cleveland City Schools. All 
communications sent to and received from this address are subject to 
monitoring, inspection, and filtering. All emails are logged.*

**Comment by AlexandreSi** [comment]
Closing this issue as it seems to have been a one shot crash, maybe due to the recent release 5.3.190.
