### ISSUE TITLE
Typo for 3D stuff

### ISSUE THREAD

**Issue by Thunderblt57** [4ian/GDevelop#6368]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Instead of gravity on the 3D Jump, it says "gavity"

### Steps to reproduce

Install the 3D Jump extension and then try to find gravity and instead it will show "gavity"

### GDevelop platform

Web

### GDevelop version

5.3.189

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by AlexandreSi** [comment]
Thanks for spotting it and taking the time to report it!
