### ISSUE TITLE
Number of builds available not decreasing leading to a 403 error...

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#641]
Windows 10, current public build BETA 52

I can still only build 2 times before this error, but the GUI should decrease builds available and not allow you to try to build over your limit... I'm sure it used to?!

https://ibb.co/czDmfU

On restarting GDevelop builds show 0 builds left correctly :)

**Comment by zatsme** [comment]
after the two builds last night it seems to have not reset today so I cannot build, also if you click see all my builds you can only see time and date, it would be much better if you put the name of the game from properties in the start of the build So you have:-  'GameName'-cordova-build

I just going to work so not in dire need of a build I'm trying to test some strange sound issues I have with android...  will probably get an indie subscription later so I can use the Live Preview :)

**Comment by 4ian** [comment]
> On restarting GDevelop builds show 0 builds left correctly :)

Yep, so there seems to be a problem of refreshing, but build count should be properly done by the build service :)

> after the two builds last night it seems to have not reset today so I cannot build

This is the count is on a rolling 24hours basis. This means that you dont "get" 2 builds at midnight, but that if you do a build at 9am and then 10am, you will get 1 build more on 9am the day after, then you'll be back at 2 builds on 10am the day after :)

I agree that having a name for the build would be good - for now build don't have names stored.

**Comment by KinkGD** [comment]
Same report than #612 so i think this one can be closed too ?

**Comment by 4ian** [comment]
In theory there is a fix to be done somewhere to ensure that the build are properly refreshed.
In practice it's not high on my priority list as long as the build service have the right count :P
