### ISSUE TITLE
It is not possible to change the location of all windows (Objects, groups of objects, layers, etc.)

### ISSUE THREAD

**Issue by TheAvIGOLD** [4ian/GDevelop#6443]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

It is not possible to change the location of all windows (Objects, groups of objects, layers, etc.)

### Steps to reproduce

When I try to move a window, it simply opens as much as possible, but does not drag. Because of this, the organization of the workspace suffers greatly.

### GDevelop platform

Desktop

### GDevelop version

5.3.194 (editor full version: 5.3.194-292b23ea174c7919a135bf3a7099c9a2ad34b6e4, core version: 4.0.99-0-release)

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Hi @TheAvIGOLD thanks for reporting, I can reproduce this issue.
We'll look into this asap

**Comment by ClementPasteau** [comment]
Fixed in #6444 this will be deployed in the next version (this week I believe)
