### ISSUE TITLE
Latest comit regression - gdevelop fails to load project

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#645]
## Describe the bug
After this pull
https://github.com/4ian/GDevelop/pull/640

When you open a project file on windows, gdevelop's editor crashes  

There is some error about
`Uncaught Error: SimpleDropTarget(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

## To Reproduce
Open a project file example

## Other details
Windows 10

**Comment by 4ian** [comment]
For for fixing this! 👍
