### ISSUE TITLE
Simpler way to center origin sprite point

### ISSUE THREAD

**Issue by LousyMolars** [4ian/GDevelop#6472]
## Description

Origin point of sprite by default set to 0,0 and most often it is what I want. But from time to time I need to set it to center of sprite, just for visual reasons. Sure, I can add/subtract width divided by 2 in event sheet, to emulate this, but sometimes it's just more convenient to move point to center. The problem is, that there is no easy way to do it now, if you need precision. Coordinates of center point are hidden by "(auto)" and can not be copied.

![image](https://github.com/4ian/GDevelop/assets/141857198/f528e257-fc65-4c41-836c-c7978259341b)

My workflow currently is to open sprite in Piskel or other software to see sprite size, then divide width and height by 2 and then paste these values. This is quite a lot of time/actions.

I searched for similar discussion, found this https://forum.gdevelop.io/t/copy-origin-point-from-another-object/41088

**1. In my opinion, simplest solution:**
![image](https://github.com/4ian/GDevelop/assets/141857198/9ddd5c8b-0628-42e5-ba67-a2128ea97086)
_Instead of "auto" show the value and let user select and copy it. Parentheses should help to show that it's calculated value, not something that user can change. Also grey color can be used instead._

**2. More difficult solution, but also covers other cases:**
![image](https://github.com/4ian/GDevelop/assets/141857198/595292c1-a9da-49a5-b7fd-1e7ff99578fb)
_Add copy and paste buttons that will work for both X and Y._

**3. If both suggested are difficult to implement, there is also this option:**
![image](https://github.com/4ian/GDevelop/assets/141857198/55e22123-b89b-42c9-8711-0de16bf1a7d7)
_Button that pastes center values._

**Comment by 4ian** [comment]
The simplest solution is probably the best way to do it now - and we can always improve it later or have a simple setting that would be "Origin position" that could be set to "Top left (default)" or "Center" (or custom). But this would need some UI/UX thinking. Putting the actual number is hopefully the easiest and simplest solution.

**Comment by 4ian** [comment]
I went for something simple and always show the center coordinates, but in a disabled field when it's set automatically:
<img width="400" alt="image" src="https://github.com/4ian/GDevelop/assets/1280130/e497c70f-d4fe-45d3-a6b3-62e5ab29cd8a">

This makes it a tad better (two select+copy/paste) to center the origin :)

**Comment by LousyMolars** [comment]
This is great, thank you!
