### ISSUE TITLE
Platformer Deacceleration shows the wrong tooltip

### ISSUE THREAD

**Issue by MTSyntho** [4ian/GDevelop#6490]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I was trying to figure out what number to use for deacceleration however I noticed it has the same tooltip as Acceleration.

Acceleration:
![image](https://github.com/4ian/GDevelop/assets/56017038/e5f25652-d9f8-4d1d-9c98-9b0ba43d7314)

Deacceleration:
![image](https://github.com/4ian/GDevelop/assets/56017038/664c85d6-30f6-45e7-8554-f51db52e4f6b)

### Steps to reproduce

1. Open any object's behavior panel in their _edit properties **window**_
2. Create a new behavior and select 'Platformer Character'
3. Scroll to 'Walk', it shows 2 text boxes named Acceleration & Deacceleration.
4. Hover your cursor over 'px • s-2' and it should show a tooltip (i think it's called)
![image](https://github.com/4ian/GDevelop/assets/56017038/464a90bd-95e1-4ea3-bbe8-d9bdc04a7766)

### GDevelop platform

Desktop

### GDevelop version

5.3.195

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
> Windows 11

</details>

**Comment by D8H** [comment]
A deceleration is a negative acceleration. They both share the same unit of measurement.
