### ISSUE TITLE
Toggle switches don't work in 5.3.196

### ISSUE THREAD

**Issue by miwalder** [4ian/GDevelop#6494]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

There's an issue with the toggle switches in the version 5.3.196. In Games using them, they can't be switched on or off, on the previous version I didn't have this problem. It occurs on the Desktop and Webversion.

### Steps to reproduce

1. Add an Object of the type toggle switch.
2. Drag it on your game canvas.
3. Start a preview and try to switch the toggle

### GDevelop platform

Desktop

### GDevelop version

5.3.196

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows, Linux

*OS Version (e.g. Windows 10, macOS 10.15)*
> Windows 10, PopOS 22.04

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Chrome

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Should be fixed now
