### ISSUE TITLE
libgconf-2.so.4 not included

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#653]
## Describe the bug
Ubuntu 18.04 (I think 17.04+) doesn't include `libgconf-2.so.4` library by default, making it impossible to launch GD5. Reported here: http://forum.compilgames.net/viewtopic.php?f=18&t=10678#p68148

## Other details
It can be fixed installing it with `sudo apt-get install libgconf-2-4` (confirmed).
Maybe it should be included with the AppImage?

**Comment by 4ian** [comment]
I wonder if it's an issue with Ubuntu not including this library by default 🤔
Or if it was something that is added in latest version of Electron / electron-builder - so upgrading electron-builder could fix this.

> Maybe it should be included with the AppImage?

Well I remember including libraries with GD4 and it was generally a bad idea for compatibility on Linux. I would rather try to find why an Electron app (GD5) is not running as is without installing extra libraries on Ubuntu 18.04, which seems strange!

**Comment by blurymind** [comment]
I think thats a gnome library. Didn't ubuntu recently move back to using gnome-shell?
If you are only with Unity desktop you might not have it

**Comment by 4ian** [comment]
Yeah that's the issue of this missing library. I wonder if other software got the same issue?

**Comment by blurymind** [comment]
@4ian it's very common on linux :)

**Comment by Lizard-13** [comment]
Yeah, an advice and the command to install the lib in the download section should be enough.

**Comment by 4ian** [comment]
Added this when the Linux button is hovered or clicked :)

![image](https://user-images.githubusercontent.com/1280130/45937152-83032b00-bf72-11e8-8717-58486b5ebe70.png)

**Comment by 4ian** [comment]
Closing as this should be enough to inform new Linux users about this! :)

**Comment by probonopd** [comment]
Please provide an AppImage, and please bundle libgconf2-4 inside it. Thank you very much.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

**Comment by 4ian** [comment]
If you want to try it by yourself, you can give it a go by following the setup instructions from the README (https://github.com/4ian/GDevelop/blob/master/newIDE/README.md#installation) and then building the app package: https://github.com/4ian/GDevelop/blob/master/newIDE/README.md#desktop-version

The packaging is done using `electron-builder`, you can try appimage by launching:

```
cd newIDE/electron-app
npm run build --linux AppImage
```

I don't have much time to test this on Linux, so any help if welcome :)

**Comment by probonopd** [comment]
libgconf-2.so.4 definitely needs to be bundled __inside__ the AppImage so that users won't have to install it.

**Comment by probonopd** [comment]
Also, the AppImage seems to be missing from https://gdevelop-app.com/download/?

**Comment by 4ian** [comment]
> Also, the AppImage seems to be missing from https://gdevelop-app.com/download/?

It was never distributed ;) I still distribute a .tar.gz for now. https://trello.com/c/ySX0iU8t/172-package-gdevelop-5-as-an-appimage-for-linux is the feature request. Any help is welcome to test that this works on a variety of distributiosn.
