### ISSUE TITLE
[5-5.3.200 bug] (PLATFORMER OBJECT) is on platform (PLATFORM OBJECT) condition no longer works

### ISSUE THREAD

**Issue by EthanBoiLol** [4ian/GDevelop#6537]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

GDevelop 5-5.3.200 has a bug that doesn't make the (PLATFORMER OBJECT) is on platform (PLATFORM OBJECT) work.

However, when I test again in 5-5.3.199, the condition works as intended without any change or issue

### Steps to reproduce

1. Create platformer object
2. create platform object
3. set condition (platformer object) is on platform (platform object)
4. set action to whatever to test it

### GDevelop platform

Desktop

### GDevelop version

5-5.3.200

### Platform info

<details>

*Linux
>

*Pop! OS 22.04
>

</details>

**Comment by AlexandreSi** [comment]
Hi @EthanBoiLol,
Thanks for taking the time to report the issue. It is fixed by #6538 and will be released soon.
