### ISSUE TITLE
Icons can not be generated when project is a cloud project

### ISSUE THREAD

**Issue by Bluntvloei** [4ian/GDevelop#6549]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Generated Icons from image does not work when the project is a cloud project

### Steps to reproduce

Create a cloud project
Go to Game Settings -> Icons and thumbnail
And click Generate Icons from a file. 

Nothing happens

### GDevelop platform

Desktop

### GDevelop version

5.3.201

### Platform info

<details>

OS Windows 11 23H2 Build 22631.3527
</details>

**Comment by AlexandreSi** [comment]
Hi @Bluntvloei,
Thanks for taking the time to report this issue!
Indeed this isn't working, we'll fix that for the next version.
