### ISSUE TITLE
Tilemap editing support 

### ISSUE THREAD

**Issue by devchenli** [4ian/GDevelop#6554]
I have been using GDevelop for a week and it feels good. The only problem is that I cannot edit Tilemap directly. I wonder if there are plans to add this feature.Thank you！

**Comment by AlexandreSi** [comment]
Hi @devchenli,
Thank you taking the time to suggest a new feature!
This idea is already being discussed here: https://github.com/4ian/GDevelop/discussions/2352
Please add your insight to this discussion so that it can go further.
