### ISSUE TITLE
Grid size not remembered

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#659]
It would be nice to have the grid size per scene or even just per project saved.  When turning on and off the grid, it's forgotten.

**Comment by Bouh** [comment]
This is an suggestion, we regroup all of this on Trello.
Github is for an issue about problem or bug.
I added a card about grid size on Trello.

https://trello.com/c/qxpR26jr/160-grid-size-saved-by-project

**Comment by zatsme** [comment]
It is, yes, but I also believe it should at least be saved between scenes as at the moment you have to keep setting grid size over and over as you work.

**Comment by BWPanda** [comment]
It'd be nice to have a UI option to remember this (both the on/off setting as well as the cell width/height), but in the meantime you can edit the game.json file as follows:

```
layouts:
  uiSettings:
    grid: true
    gridHeight: n
    gridWidth: n
```

Then the grid will be turned on by default and set to the appropriate size (for that project).

**Comment by blurymind** [comment]
https://github.com/4ian/GDevelop/pull/892 has now been merged, implementing this feature.
The next build will have this feature and your grid settings will be stored every time you save your project.

**Comment by zatsme** [comment]
👍
