### ISSUE TITLE
when panning around scene, there is slight jitter and distortion

### ISSUE THREAD

**Issue by ghost** [4ian/GDevelop#664]
## Describe the bug
when panning around a scene with the middle mouse button, it's jittery and not smooth
i am using a 144hz monitor btw, that may be why. if so, it should be smooth for all monitor refresh rates imo =] ty for reading.

## To Reproduce
create new project, select any example
- hold down middle mouse button to pan around scene

## Other details
windows 10 64-bit

**Comment by 4ian** [comment]
Can you post a video of the issue? :)

**Comment by girng** [comment]
> Can you post a video of the issue? :)

yeah. but it will be hard to notice in the gif cause it looks normal, u might need a 144hz monitor to really see it.

https://i.gyazo.com/203dd9abc72c43a68a7bf8eb270009d9.mp4

i mean, it's nothing game breaking... but it's not smooth and makes it feel like it's laggy (when it's really not)

**Comment by blurymind** [comment]
I think this is more of a performance issue, rather than an actual bug. It is also very subtle - if you are having trouble presenting it in a noticeable way

**Comment by girng** [comment]
is the editor pan code using requestAnimationFrame for updating? if not, that could be related around the issue

**Comment by Silver-Streak** [comment]
I experienced this recently, but only after getting my new 240hz monitor. The updated in B112-114 about forcing the editor to 60hz has fixed this. Due to the age of this thread and now seeing it reoslved, I'm closing this out. 

If any of the posters above still experience this in b114, please feel free to reopen.
