### ISSUE TITLE
( new guided lesson: Platformer ) It does not work and the application crashes 

### ISSUE THREAD

**Issue by Nader-B10** [4ian/GDevelop#6644]
### Describe what you were doing when the crash happened

( new guided lesson: Platformer ) It does not work and the application crashes @AlexandreSi @D8H @4
![GIF 6-10-2024 9-44-28 AM](https://github.com/4ian/GDevelop/assets/113104542/499b7953-6194-449b-a299-53472e6fa27b)

### GDevelop version

5.4.202-beta

### Platform info

PC-windows

**Comment by 4ian** [comment]
Thank you for reporting this! It's indeed broken and will be fixed for next version (#6647).
