### ISSUE TITLE
An object related to a behavior is not recognized in an action

### ISSUE THREAD

**Issue by Nader-B10** [4ian/GDevelop#6648]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug
@4ian @AlexandreSi @D8H 
There is an error in the latest beta version of the guided lesson: Timer, which is that a warning appears in the event panel that the key object is missing some behavior, but this is not true, and you can see the video. The warning is not supposed to appear.

![GIF 6-10-2024 5-49-32 PM](https://github.com/4ian/GDevelop/assets/113104542/690b4c9d-3b8b-4c73-a0d7-ca2b625602ab)

### Steps to reproduce

1. open guided lesson: Timer
2. go to GameScene (Events)
3. Expand the event group ( Game management )
4. You will find the action with the problem under the note (Winning the game)

### GDevelop platform

Desktop

### GDevelop version

5.4.202-beta

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Thanks for reporting @Nader-B10 
This has been fixed and will be available in the next beta release

**Comment by AlexandreSi** [comment]
Thanks for spotting it @Nader-B10 
I'm closing this issue, feel free to re-open it if needed.
Please keep in mind that we check the issues every working day so no need to tag us on it.
