### ISSUE TITLE
extreme flickering in car physics example

### ISSUE THREAD

**Issue by girng** [4ian/GDevelop#665]
## Describe the bug
when viewing the car physics example scene, I see extreme flicking of textures

https://i.gyazo.com/517344c29bd983104dbca3d75a51682f.mp4

## Other details
GTX 950  (latest drivers)
windows 10, 64-bit

i know godot has an issue with their black tile flickering behavior only under nvidia drivers. not sure if this is related, but that issue is: [#9913](https://github.com/godotengine/godot/issues/9913) (possible info there could help)

**Comment by 4ian** [comment]
It's just Z fighting (https://en.wikipedia.org/wiki/Z-fighting).

Changing the Z order of one of the two object will fix the issue :)

**Comment by girng** [comment]
@4ian nice one. lol thought it gfx issue 

thanks!!
