### ISSUE TITLE
Add new Event row commands are hard to discover

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#666]
## Describe the bug
It seems like I am not the only one who has trouble finding that menu, because it is hidden between buttons that trigger actions. It also feels a bit detached from the event sheet itself:
![hardtofindgd](https://user-images.githubusercontent.com/6495061/45999476-ab3b7880-c09d-11e8-88e6-bd2b184e7452.PNG)

## To Reproduce
Watch somebody new use gdevelop for the first or second time - you will see that they struggle to find how to make a javascript event row or a group event row. They just dont look for it there. First thing they do is scroll to the bottom of the event sheet, where they find nothing - no button to add a new row. The button is instead outside of the event sheet and is mixed with buttons for other things.

## Suggestion
The most intuitive place to find this menu IMO is at the bottom of the event sheet. Here is a crude mockup:
![addrow](https://user-images.githubusercontent.com/6495061/45999710-58ae8c00-c09e-11e8-8b69-164304239947.png)

:)

I can try to implement this change if you like the idea. Check out the number of this issue :p its the number of the 😈

**Comment by zatsme** [comment]
Another intuitive place would be in the right click menu, unless it's already there and I've not noticed 😁

**Comment by blurymind** [comment]
Here is a second mockup that makes more sense:
![mockup2](https://user-images.githubusercontent.com/6495061/46041406-9ea13980-c10a-11e8-9076-195cda9b8e95.png)

**Comment by zatsme** [comment]
What about in right click menu as I suggest?  On windows tablet it's a long press so just as intuitive to me?

**Comment by blurymind** [comment]
the right click menu is context sensitive, so it would be a great opportunity to add a command to insert a new event or sub-event below or above first/last selected

**Comment by 4ian** [comment]
I think a context menu showing when you're clicking outside any event would be the way to go :)

**Comment by blurymind** [comment]
@4ian The problem with that proposition is that when you scroll down to the end of an event sheet - there is no pixel space left to click on at the very bottom.
![botrow](https://user-images.githubusercontent.com/6495061/46215417-36826b80-c335-11e8-99d4-6f8b20a6746e.PNG)

If we add pixels space, then why not just as well add these buttons or some of them:
![mockup2](https://user-images.githubusercontent.com/6495061/46041406-9ea13980-c10a-11e8-9076-195cda9b8e95.png)

- It will allow the user to add an event with two steps less (point and click instead of point, right click, point, click )
- It will be easier to discover than just empty space to right click on

**Comment by 4ian** [comment]
Why not try adding two buttons: One "Add event" and one "Add other" that when clicked open a context menu with the same content as the one in the toolbar.
(Let's forget about the add subevent/add comment to avoid cluttering the interface - especially because these buttons are targetted at people that begin).

About the design, I don't know if we should go with the design in your mockup or keep using `<FlatButton />`, without icon, for consistency?

**Comment by blurymind** [comment]
Ok I added the 'Other' commands to the menu. Pull request coming later today :)

**Comment by 4ian** [comment]
Good job! This "Add Other" will be perfect there :)
