### ISSUE TITLE
cotillonas2.1

### ISSUE THREAD

**Issue by sebamendoza** [4ian/GDevelop#667]
Hi!
  
  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.
  
  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by blurymind** [comment]
there is no link

whats with all the spam :)

**Comment by sebamendoza** [comment]
Sorry. it´s an error
