### ISSUE TITLE
Apply the Spine Runtimes license to the Spine extension

### ISSUE THREAD

**Issue by NathanSweet** [4ian/GDevelop#6679]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello! My name is Nate, founder of Spine and Esoteric Software.

I noticed that GDevelop contains pixi-spine in its Spine extension:
https://github.com/4ian/GDevelop/tree/master/Extensions/Spine/pixi-spine

pixi-spine comes from here:
https://github.com/pixijs/spine

pixi-spine uses Esoteric Software's Spine Runtimes and so the Spine Runtimes license applies:
https://esotericsoftware.com/spine-runtimes-license

Will you please add our Spine Runtimes license to your Spine extension?

It is not allowed to discard the Spine Runtimes license from our Spine Runtimes and apply the MIT license instead. GDevelop must apply the Spine Runtimes license to its Spine extension. That means users who publish apps containing the Spine Runtimes (via pixi-spine in the GDevelop Spine extension) need a Spine license.

Also please note in Spine 4.2 we now support an official Pixi runtime:
https://github.com/EsotericSoftware/spine-runtimes/tree/4.2/spine-ts/spine-pixi
You may want to switch to that!

### Steps to reproduce

n/a

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

all

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by NathanSweet** [comment]
Thank you, that sounds perfect!

**Comment by NathanSweet** [comment]
BTW, if you're interested in switching from pixi-spine to our official spine-pixi runtime, we just published this documentation today:
https://esotericsoftware.com/spine-pixi
This section talks about the differences between the two runtimes:
https://esotericsoftware.com/spine-pixi#Differences-to-pixi-spine

**Comment by 4ian** [comment]
I've made the changes in https://github.com/4ian/GDevelop/pull/6701 @NathanSweet. Let me know if I missed something or if the license should be somewhere else.

Very cool that you maintain your own spine-pixi runtime. I'm pinging @f0nar who built the original Spine extension. I guess moving to it would not be super difficult, though this is not an absolute priority (but PR always welcome of course!).

**Comment by f0nar** [comment]
Hi all!

You would not belive me if I said I was thinking last week about migration and that it would have been great to check status of official spine pixi repo. Because last time I checked it was in active review state.

As I know it is not so general as unofficial one. It means that you will be able to use it only with specific spine version. I heard about check button to transform output of one spine version to anothet.

Anyway let me check and think more about it. I will share my foundings later.

And sorry for missing license in PR. I did not do it on pupose.

**Comment by NathanSweet** [comment]
No worries about the licensing, it's easy to miss and was hopefully easy to fix. It's one of those silly legal things that once it comes to our attention then we have to nag about it, else we could lose our copyright or ability to enforce our license. At any rate, it seems all resolved now, thank you all!

I believe the pixi-spine extension supported loading multiple Spine data versions by including multiple spine-ts runtime versions. This isn't a great idea for a number of reasons. IMO the benefits are not worth the extension complexity and larger runtime size. Also it's usually best not to map all Spine skeleton bones and attachments to scene graph nodes. It's more efficient for a single scene graph node to render the whole skeleton, with some mechanisms to support inserting scene graph nodes into that rendering.

Spine's standard approach for all game toolkits is to require exporting projects using the editor version that matches the runtime version:
http://esotericsoftware.com/spine-versioning#Synchronizing-versions
This simplifies many things, ensuring the runtimes stay lightweight and streamlined. It does mean that users need to re-export their Spine projects when moving to a newer Spine runtime, but with a little organization that should not be onerous. We provide some scripts that can help:
https://github.com/EsotericSoftware/spine-scripts/tree/master/export
