### ISSUE TITLE
"GDJS-for-web-app-only/Runtime" folder not being copied to correct location

### ISSUE THREAD

**Issue by zachThePerson** [4ian/GDevelop#668]
## Describe the bug
During cloning and installation, the "GDJS-for-web-app-only/Runtime" folder is being copied to my "Documents/folder" instead of to the directory "node_modules/GDJS-for-web-app-only/" This lead me on a confusing search when trying to start the app and getting an error saying it couldn't find the resources contained in the folder.

It's a simple workaround to copy the folder into the correct location, but because it was simply named "folder," I only found it through pure luck. 

## To Reproduce
1. Clone repo
2. navigate to newIDE/app/
3. npm install / yarn

## Other details
* Windows 10
* Powershell
* Node v8.12.0
* npm v.6.4.1

**Comment by zatsme** [comment]
I'm not 100% sure but after uninstalling nodejs and python, then installing node-v8.11.4-x64.msi and python-3.7.0-amd64-webinstall.exe the error disappeared.

I have a sneaky feeling I had a version of python that didn't work with nodejs properly?!

**Comment by zachThePerson** [comment]
Thanks, I will check that out when I get home. I tried completely re-installing node already and that did not fix it, but I didn't think to check python.

Also glad to hear I'm not the only one with the problem

**Comment by 4ian** [comment]
Python should not be needed for this, the version of Node.js you have looks recent enough. 
Is that always happening? Can you try with a fresh clone of GDevelop repository?

Sounds like a Windows only issue, maybe the script CopyRuntimeToGD.bat being called with bad arguments, but that looks strange though.

**Comment by zachThePerson** [comment]
I'll do some experimenting tomorrow and let you know. At least I now know the .bat file to look at

**Comment by blurymind** [comment]
what do you get in console?

**Comment by zachThePerson** [comment]
Ok, after some messing around I figured out the problem. It only happened when I cloned the repository to "Documents/Folder Of Death" (my main folder for programming projects, long story), and being that the Runtime folder was misplaced as "Documents/Folder," I figured out that it was some kind of error resulting from there being spaces in the folder name "Folder Of Death."

I renamed the folder to use underscores and now it works flawlessly.

**Comment by zachThePerson** [comment]
I'll try fixing it, maybe that will be my first commit :)

**Comment by 4ian** [comment]
Sure let me know if you have a fixed version of the script :) I think it can be fixed with extra quotes somewhere (batch programming is full of trap like this ^^)

**Comment by zachThePerson** [comment]
Yeah, it was an easy fix. When the directory was passed as an argument to the batch file in import-GDJS-Runtime.js a space causes it to be split into 2 or more separate arguments, and the batch file will only use the first.

Fixed and submitted a PR. It's my first commit to an open source project, so let me know if I did it right.

**Comment by 4ian** [comment]
Thanks for taking the time to do this! Your PR looks good :) I commented about checking if the script still works without argument. Apart from this it will be good to go!
