### ISSUE TITLE
( new guided lesson: Top-Down RPG Pixel Perfect) It is broken and cannot be opened

### ISSUE THREAD

**Issue by Nader-B10** [4ian/GDevelop#6685]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

( new guided lesson: Top-Down RPG Pixel Perfect) It is broken and cannot be opened
![GIF 6-19-2024 9-20-09 PM](https://github.com/4ian/GDevelop/assets/113104542/ba06add5-4c83-41cb-9cac-b14a5c66d73f)

### Steps to reproduce

There are no Steps. Just try to open it. It never opens. It is broken

### GDevelop platform

Desktop, Web

### GDevelop version

5.4.203

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by ClementPasteau** [comment]
Thanks for reporting @Nader-B10 - this has been fixed in #6681 and will be available the next release in the upcoming days
