### ISSUE TITLE
Dropdown selection for Platform type action

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#6694]
In the "Platform type" action, the 3 possible types should be selectable in a dropdown instead of having to write the full words.

- [ ] Add a dropdown menu for the Platform type action

![5](https://github.com/4ian/GDevelop/assets/81538128/03306842-9f2a-4331-b905-9ba4952c1e37)

**Comment by tristanbob** [comment]
@jack-ii Thanks for the feedback! I agree; it should be a drop-down selection.

I'll try to see if I can do this by copying an action of a similar behavior.

**Comment by tristanbob** [comment]
I did a quick search but could not find any Extension.cpp that uses a drop-down input selection.  
It's possible there is no existing interface built for C++ extensions, or did I miss one?
