### ISSUE TITLE
Object-variable expression missing for Number variables

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#6697]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

If I want to fill a global/scene variable with the declared type _Text_ with an object variable, there is an entry for it in the expression editor. But if it is a variable with the type _Number_, the entry is missing.
The same e.g. with Storage save actions.
![1](https://github.com/4ian/GDevelop/assets/81538128/4b15d273-668a-47cb-b21f-79034e9fb3e5) ![2](https://github.com/4ian/GDevelop/assets/81538128/17e074ec-b96d-4bf2-88c4-1ce038d32c72)

_________

Another problem, it is not possible to pass a boolean value from a scene boolean variable to a global boolean variable because boolean variables do not allow expressions.

_________
### GDevelop version
5.4.204

**Comment by D8H** [comment]
Thank you for reporting an issue.

Indeed, we forgot to remove `VariableString()` for objects.

A new system has been introduced fro variables in the 5.4.203. Please take a look to the release note:
- https://github.com/4ian/GDevelop/releases/tag/v5.4.203

You can also find more details on the forum:
- https://forum.gdevelop.io/t/new-unified-variables-and-variables-declaration-in-gdevelop-5-4/58723

> Another problem, it is not possible to pass a boolean value from a scene boolean variable to a global boolean variable because boolean variables do not allow expressions.

This has never been possible with expressions. Boolean values can be copied using conditions and actions.

**Comment by jack-ii** [comment]
> Indeed, we forgot to hide `VariableString()` for objects.

Ah okay I thought so. That mean we should use autocomplete?
Maybe it would still be good to have an entry in the expression editor. If you don't know the name of the object, you get a clean easier to read list of object-variables and above all you can create an object-variable there, without having to switch to the scene editor first.
For everything else there is also an expression menu, I wouldn't remove it specifically for variables, there is no disadvantage to leaving it there.

> This has never been possible with expressions.
Would be good if this works in the future :)

**Comment by D8H** [comment]
> That mean we should use autocomplete?

The variable must be declared and its name directly used in expressions (without `Variable()`).
