### ISSUE TITLE
Android app dont know the multiplayer commands

### ISSUE THREAD

**Issue by KoningPendragon** [4ian/GDevelop#6698]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

App dont recognize the new update.  App is up to date.

![Screenshot_20240621_091601_GDevelop](https://github.com/4ian/GDevelop/assets/90870910/d68759ad-defc-4278-97ca-031c10a144d2)

### Steps to reproduce

Open app go to a project that has the new multiplayer functions

### GDevelop platform

Mobile

### GDevelop version

53200

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by Zac0511** [comment]
Oh multiplayer got added in 5.4, you're on 5.3, so thats normal. Just update the app.

**Comment by KoningPendragon** [comment]
Hello zac

Yeh that seem to be the case because now there is an update available
