### ISSUE TITLE
[Bug] Dragging event while at 200% or more indent scale.

### ISSUE THREAD

**Issue by cyraid** [4ian/GDevelop#6705]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

The indent scale isn't applied to the drop container. This would be fixed in [this](https://github.com/4ian/GDevelop/pull/6702) Pull Request.

### Steps to reproduce

Using the below screenshot as reference (create the conditions):

![image](https://github.com/4ian/GDevelop/assets/7562753/09feb9a4-5792-4d5b-887a-42094012412b)

At 200% or more indent scale, you cannot drag the top inner event, but you can drag the bottom two for example.

### GDevelop platform

Desktop

### GDevelop version

5.4.204

### Platform info

*OS Version (e.g. Windows 10, macOS 10.15)*: Windows 11

**Comment by 4ian** [comment]
I merged your fix, many thanks! :)
