### ISSUE TITLE
"Wait" causes permanent alteration to local variable declaration if another's value is set

### ISSUE THREAD

**Issue by Granshmeyr** [4ian/GDevelop#6706]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Setting the value of local variable `foo` in any event can permanently alter the declared value of local variable `bar`. The declaration of `bar`, even if the setting of `foo` is thereafter bypassed, will be permanently altered. Note that this only occurs if there is a "Wait" event after the declaration of `bar`.

### Events preview

<img width="850" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/f4e2a439-d3b7-4e23-8b4b-38d03b39354a">

### Steps to reproduce

1. Clone https://github.com/Granshmeyr/GDevelop-LocalVariableOverwrite-MRP
2. Run game
3. Press space to display the value of `foo`
4. Wait for the "Wait" event to elapse (2 seconds)
5. Press space and wait again
7. Notice how the value of `foo` is still `"Hello World!"`
8. Press enter to enable `bar` setting
9. Press space and wait again
10. Notice how the value of `foo` is now equal to the set value of `bar` in the event sheet
11. Press enter to disable `bar` setting
12. Notice how `foo` is now permanently declared with the value of `bar` for this runtime

### GDevelop platform

Desktop

### GDevelop version

5.4.204

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
Windows
>

*OS Version (e.g. Windows 10, macOS 10.15)*
Windows 11 Home (22H2)
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
Not applicable
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
Not applicable
>

</details>

### Additional context

The variable being overwritten only gets overwritten after the "Wait" event finishes.

**Comment by D8H** [comment]
Thanks a lot for reporting this issue and for the great reproduction explanations and project.
It should be fixed in the next release.

**Comment by Granshmeyr** [comment]
I suppose I can close this because I can confirm it is fixed in the latest update (5.4.205).
