### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by MAFLIXD** [4ian/GDevelop#6707]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Good

### Steps to reproduce

Good

### GDevelop platform

Desktop

### GDevelop version

Good

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>
Food

### Additional context

Good

**Comment by MyNameIsRinax** [comment]
Huh?

**Comment by cyraid** [comment]
> Huh?

He must really like the product.

**Comment by MyNameIsRinax** [comment]
> > Huh?
> 
> He must really like the product.

He put "Food" on the details, wdym??? 😭

**Comment by Silver-Streak** [comment]
Github is for reporting issues or working on technical enhancements. Not for spam.

Feel free to submit a new issue if you have something to actually report.
