### ISSUE TITLE
Gdevelop multiplayer server thinks you are still in a lobby if you don't use the "back to lobbies" button

### ISSUE THREAD

**Issue by TheRealSoloLeo** [4ian/GDevelop#6709]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

If you press the ![image](https://github.com/4ian/GDevelop/assets/161608114/865a4166-fe4b-4f43-8137-0678022ea71a) button (go back to previous page button) and you're in a multiplayer lobby that hasn't started you are sent back in the "game name - Lobbies" menu, but the server thinks you are still in the lobby until you reload the page.

### Steps to reproduce

1. Create a simple game with the new multiplayer features
2. Export it in a gdevelop test build
3. Open the test build in a browser
4. Join a lobby
5. Click on the ![image](https://github.com/4ian/GDevelop/assets/161608114/865a4166-fe4b-4f43-8137-0678022ea71a) button (go back to previous page button) (it's next to the refresh page button)

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.4.204

### Platform info

<details>

*Windows 11*
>

*Works on chromium browsers (and probably firefox)*
>
</details>

### Additional context

It probably works on html and published gd.games games too because they're the same type of export.

**Comment by ClementPasteau** [comment]
Hi @TheRealSoloLeo 
Thanks for reporting the issue. I can indeed confirm I reproduce the problem with those steps, it's a really strange behavior!
We'll work on a fix.

**Comment by ClementPasteau** [comment]
Fix has been pushed, this should not happen anymore

**Comment by deftrashu** [comment]
please add cursor/D-pad or Enter/return button support while online lobby.

Example: accept to READY by Enter or Arrows.
thx
