### ISSUE TITLE
store

### ISSUE THREAD

**Issue by CjFlypuffin369** [4ian/GDevelop#6710]
BEFORE opening a new submission, please make sure that you:

- You have packaged the asset pack according [these rules](https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store). Otherwise, your package may be rejected or we will ask you to do the changes.

## Description

- License:
- Author:
- Link to the original website:
- Zip file:

**Comment by Silver-Streak** [comment]
There is nothing attached to this submission, and the required template is not filled out.

Feel free to create a new submission with the required info and attachments
