### ISSUE TITLE
Update Layer panel icon components for better comprehension

### ISSUE THREAD

**Issue by LuniMoon** [4ian/GDevelop#6755]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

> Based on TheQuirkyGamer [feature request on the forum](https://forum.gdevelop.io/t/locked-objects-and-unlocked-look-too-similar/59224)

The user reports that it is hard to distinguish which are the locked or unlocked instances on the instance list. Specially when the list is long.
![image](https://github.com/4ian/GDevelop/assets/103995399/ba6b52c1-b818-4653-9633-17d8f7c259b4)

### Suggested solution:

<img width="844" alt="Screenshot 2024-07-05 at 14 53 33" src="https://github.com/4ian/GDevelop/assets/103995399/497ea205-a5a7-4d5d-a0b9-052231ad45e6">

Update the layer panel with an updated icon button.
Look for the specifications on the file "Components" and search for "Clickable-Icon"
<img width="80" alt="Screenshot 2024-07-05 at 14 43 37" src="https://github.com/4ian/GDevelop/assets/103995399/2145beb3-f519-466f-8ca0-a02be6fdb7cb">

This design should allow the eye to make a distinction between default state (Placeholder in the Component) and Active (Enabled)

### Steps to reproduce

Long list of objects in the instance panel

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.4.204

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by tristanbob** [comment]
How about placing the controls to the left of the object name?

**Comment by LuniMoon** [comment]
I've placed them on the right so it's easier to reach with the thumb on mobile.

**Comment by jack-ii** [comment]
Good mockup :)
But this is the Instances List Panel, not the Layer Panel
Hide/Show is not yet available for objects in the editor
1 of 6 titles as an icon doesn't fit so well, especially because the panel and column are much wider in reality than on the image

**Instances List Panel:** Angle
**Properties Panel:** Rotation
I think "Angle" would be correct so that it fits the events

**Comment by LuniMoon** [comment]
Update:
- The typo on the original issue was corrected. Now it says "instance list" instead of "layers list".
- Note on hide/show: this is an equivalence on the Figma file "Editor Panels" -> Sandbox Layers. That's the main reason why this mockup has a hide/show icons but we do not need to add them on the first iteration.
- Regarding icons as titles: we keep the 'layers" icon, and we'll replace "Angle" with its icon
- As for the icon for angle... we used "icon/Angle" (see Icon file on Figma) in the 1st design, but we later changed it to the "Rotate Z" icon to align it with the 3D icon set... probably we'll have to change the tooltip title to "Rotation (Z)".

**Comment by k-vijay-05** [comment]
@LuniMoon can i work on this?

**Comment by LuniMoon** [comment]
@k-vijay-05 go on :)
This is the final image 
<img width="797" alt="Screenshot 2024-11-28 at 17 06 25" src="https://github.com/user-attachments/assets/55972b94-73e4-471d-b29a-cc894f2667c4">

**Comment by LuniMoon** [comment]
Discussion continues here https://github.com/4ian/GDevelop/pull/7207
