### ISSUE TITLE
Behaviors Tab on a sprite Called PlatformerObject

### ISSUE THREAD

**Issue by BrownTroutYT** [4ian/GDevelop#6772]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

one morning i just wanna work on my game, pixel pirates. So I just wanna play test it jsut in case something goes wrong and the whole PlatformerObject in behavior tab has reset to the original options now when i try to set it to the normal its doing the same thing. 
Btw love the engine and hope u guys can fix it! 

### Steps to reproduce

![Screenshot 2024-07-13 080539](https://github.com/user-attachments/assets/bbf88f6d-daa7-4b9f-9f6f-0d7879db2c27)

### GDevelop platform

Desktop

### GDevelop version

5.4.205

### Platform info

<details>

Windows

</details>

### Additional context

Just Resets The Platformer object now its gone all funny and werid and very slidy

**Comment by ClementPasteau** [comment]
Hi @BrownTroutYT there's not much we can do here without reproduction steps.
It looks to me as if you haven't saved your project correctly before closing it.

I will close this issue.
If you have clear reproduction steps on how this happens, then feel free to re-open the issue with them.
