### ISSUE TITLE
Make autocompletion case insensitive

### ISSUE THREAD

**Issue by LuniMoon** [4ian/GDevelop#6811]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

> Based on Keith_1357 https://forum.gdevelop.io/t/behavor-names-shouldnt-be-case-sensitive-in-autocomplete/60014 forum request

They report that because of the fact that the behavior search on the events is case sensitive, they struggle to find what they need on the list.
<img width="452" alt="Screenshot 2024-07-29 at 13 44 25" src="https://github.com/user-attachments/assets/2b26fe7d-d0df-4755-bf4d-42bdd763e97d">

They suggest removing the case sensitivity parameter.

### Steps to reproduce

Use the search functionality on the Event sheet

### GDevelop platform

Desktop, Web

### GDevelop version

N/A

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by 4ian** [comment]
100% should not be case sensitive.

**Comment by 4ian** [comment]
Fixed in b2c953a31d9afc8fbf7bf6033e2a19d8cbd9cf87 :)
