### ISSUE TITLE
(New GDevelop version 5.4.206) The global object disappears in the scene editor, whether in previous projects or in a new project, it will not appear in the scene editor

### ISSUE THREAD

**Issue by Nader-B10** [4ian/GDevelop#6824]
### Describe what you were doing when the crash happened

There is a problem in the latest update that was released today.. which is that the global object disappears in the scene editor, whether in my previous projects or when trying to make an object as a global object in a new project, it will not appear in the scene editor, it will disappear, but will only appear in the preview

https://github.com/user-attachments/assets/19af5741-1761-403b-be91-a7e956e08b97

![Screenshot 2024-07-30 180505](https://github.com/user-attachments/assets/b9148844-c5fc-4f32-945c-b67af533bfbc)

### GDevelop version

5.4.206

### Platform info

windows

**Comment by Nader-B10** [comment]
@4ian @D8H @AlexandreSi

**Comment by 4ian** [comment]
We're on it

**Comment by AlexandreSi** [comment]
This is fixed by #6822.
Please do not ping contributors in issues.
