### ISSUE TITLE
Lights Example

### ISSUE THREAD

**Issue by eugene719** [4ian/GDevelop#683]
Hi!
  
  I'd like to submit a new example to be added to GDevelop. This is an example for lights in GDevelop.
[Lights Example.zip](https://github.com/4ian/GDevelop/files/2434302/Lights.Example.zip)

  
  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by blurymind** [comment]
gd5 doesnt yet support lights, right?
Is this a gd4 example?

**Comment by zatsme** [comment]
No it's GD5 fake lights if it's the same as the discord zip file he posted. 🤔

**Comment by Bouh** [comment]
There is a light object since [beta 99](https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta99)
[I example is bundled with GDevelop ](https://editor.gdevelop-app.com/?project=example://lights)
