### ISSUE TITLE
Objects cant load properly in new version

### ISSUE THREAD

**Issue by jayare5** [4ian/GDevelop#6833]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

**-----Old version:** 

![image](https://github.com/user-attachments/assets/7e8cb58a-3247-48fd-a56b-deb0a59afe8d)

**-----New version:**

![image](https://github.com/user-attachments/assets/45b2cb70-e280-4e03-ad3b-ebf4e50a0f1c)

### Steps to reproduce

UPDATE: I just figured out that this happens if the object is a Global object.
So... 
1. Make a new sprite object
2. Make it a global object
3. Put it in the scene. It will be invisible.

Another user in Discord (sigmatoileta) reported the same thing in Help / english just some minutes ago at this time, luckily, so I know it's not just me.

- Desktop
- GDevelop: 5.4.206
- Windows 10

**Comment by AlexandreSi** [comment]
Hi @jayare5,
thanks for taking the time to report this issue!
It's been fixed with version 5.4.207.

**Comment by jayare5** [comment]
@AlexandreSi  I'm happy to report that I'm not having this issue now! :D Thanks so much.
As an extra, there was another issue I was having with another project, where loading a project would freeze GDevelop if it tried to load on a certain scene that was busy with objects. I was never sure what exactly was the threshold to cause that to happen, but I used to have to save my project while looking at an empty map so that GDevelop could load properly, and THEN it could load other maps even the ones that would freeze it at launch. This new version has fixed that too :O I am ever so glad!!!!
