### ISSUE TITLE
"Something went wrong :( Please try again)"

### ISSUE THREAD

**Issue by joaovictordejesus** [4ian/GDevelop#6845]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello! Goodnight! I've been having a serious problem with the compilation for a week now. Every time I try to compile the project for Android, the message "Something went wrong :( Please try again).

### Steps to reproduce

Every time I try to compile the project 

### GDevelop platform

Desktop

### GDevelop version

5.4.207

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

 I'm finishing a project but I can't solve this problem. Please help me. Thank you!

**Comment by Silver-Streak** [comment]
No duplicate posts, please. 

Closing this onr as you have another issue open for the same thing. #6843
