### ISSUE TITLE
Command to invert condition in event sheet condition context menu

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#685]
Right now to invert a condition in the event sheet, you have to click on it to edit it

## Description
Adding a Command to invert condition in event sheet condition right click context menu will greatly speed up workflow Imo :) 

## Solution suggested
I can try to add it in another pull if you guys think it will be useful to have it in the menu like I do :)

**Comment by 4ian** [comment]
Sounds good! Technically you might have to  use `getSelectedInstructionsContexts` and check if the instruction are conditions (`isCondition`) when building the context menu :) Apart from that, don't see any warning or major things that would not work :)

**Comment by blurymind** [comment]
Ok Will give this a try in the next pull :) Might as well do it while working on the event sheet menus

**Comment by blurymind** [comment]
Ok this was surprisingly easy to implement :)
New pull request coming later after work. Here is a teaser:
![invertconditionsgd](https://user-images.githubusercontent.com/6495061/46347034-122ed380-c642-11e8-8781-68854cc2fd32.gif)
It can invert on multiple selected. It can detect if selection contains conditions - if so apply the operation only on conditions. If none are selected it wont appear in the menu.

**Comment by 4ian** [comment]
Great! The behavior looks good :)

**Comment by blurymind** [comment]
will do a pull after I sort out the other one actually :) 
It's quite fun to use

**Comment by blurymind** [comment]
@4ian I noticed that you can disable entire events atm, but not individual conditions/actions. Is that something that is available, but not exposed to the newIde?

**Comment by 4ian** [comment]
No, it's something that is not available in the way that instructions (conditions/actions) don't have a way to be marked as disabled. If it was the case, this would still requires changes in code generation to skip these instructions. Not impossible but more work that simply switching a boolean :)

**Comment by blurymind** [comment]
Ah I see. Thank you for clarifying :)

**Comment by blurymind** [comment]
I have this working great, but I need to move some of the code to selectionHandler and add flow checking to it before doing the pull :)

**Comment by blurymind** [comment]
This got merged now, so we can close the issue 👍
