### ISSUE TITLE
Cant scroll certain pages on mobile

### ISSUE THREAD

**Issue by giannpls** [4ian/GDevelop#6860]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Have observed some pages do not scroll on the  iOS mobile app which limits their functionality. So far seems to affect custom object properties and function parameters, which effectively limits the number of properties or parameters which can be created/updated.

See also [my forum post](https://forum.gdevelop.io/t/can-t-scroll-custom-object-properties/60624) and [another similar one](https://forum.gdevelop.io/t/cant-scroll-function-parameters-on-mobile-version/56237) which seems to indicate this has been broken since at least April. Hopefully this is an easy fix.

### Steps to reproduce

1. Create an extension
2. Edit the extension and create a 2D object
3. Go to properties tab and add two properties (possibly more depending on phone), then try to scroll

### GDevelop platform

Mobile

### GDevelop version

5.4.207

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>iOS

*OS Version (e.g. Windows 10, macOS 10.15)*
> 17.5.1

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> iPhone 2020 SE

</details>

**Comment by giannpls** [comment]
I was able to find a workaround to this issue on iOS which is not horribly painful. So far it seems to work in Brave browser but not Chrome or Safari:
- Load the web app
- In browser settings, request the desktop app
- In browser settings, select Page Zoom
- Zoom out to 50%
- Load extensions functions or object editor 

The layout should now look similar to desktop and allow scrolling of parameters and properties.

**Comment by AlexandreSi** [comment]
Thanks for reporting this issue, it should be fixed in the next version.
