### ISSUE TITLE
Workflow improvements for tilemaps

### ISSUE THREAD

**Issue by Elairyx7301** [4ian/GDevelop#6863]
## Description

The new tilemap editor is so incredible and I think many will agree. Thank you!
While working with it, I got some (probably) simple but powerful ideas to improve the workflow. Some of those would feel really natural to me and I wanted to request those features to hopefully help improve this new feature.

This is my own perspective but I would really love to see any of those items added/implemented.

## Really wishing for

- Being able to delete tiles with right mouse button (while in the tilemap painter/editor)
- Being able to move the scene canvas using middle mouse button (while in the tilemap painter/editor)

## Nice to have

- Having the tilemap painter be an inline scroll section so "flip" options etc. stay on top/in reach
- Being able to select and move (multiple) tiles (while in the tilemap painter/editor)
- Having middle mouse button and right mouse button not set tile hitboxes (while configuring tilemap object)
- Wide tilemaps require to make the properties panel bigger to see all tiles. Always setting width to properties panel width can solve it
- Replace all tiles with a specific ID with another tile with another ID (in events/tilemap actions)

**Comment by Silver-Streak** [comment]
Hey Elairyx! Just as a heads up, Alexander started a discussion thread about enhancements to the native tilemap object over here: https://github.com/4ian/GDevelop/discussions/6809
