### ISSUE TITLE
Broken notification

### ISSUE THREAD

**Issue by Zac0511** [4ian/GDevelop#6876]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I wanted to update GDevelop since i noticed `5.4.209` was out, but the notification that was supposed to say "New version available" said "object [Object]".

It then later showed a normal notification saying the update was installed, i restarted GDevelop, and it was correctly updated, so its just the notification which is broken.

### Steps to reproduce

1. Wait for a new GDevelop update (or install an older build which will tell you its not up to date)
2. Wait for the notification to appear

### GDevelop platform

Desktop

### GDevelop version

5.4.208

### Platform info

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
> Windows 11 23H2 (build 22631.4037)

### Additional context

Screenshot of the notification :

![Capture d'écran 2024-08-21 202144](https://github.com/user-attachments/assets/534f3ebd-9d77-4470-a8f1-4be24936b69e)

**Comment by AlexandreSi** [comment]
Thanks for taking the time to report this issue, it will be fixed in the next version
