### ISSUE TITLE
100 euros for Reward Video Ad in GD5

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#690]
Originally I have posted this on trello but then realised it is not going to happen just because I request it so I decided to offer 100 euros to anyone who willing to implement it in to GD5 and because all the devs are here, I decided to post it here as well:

Request: Reward Video Ad (AdMob, Amazon, Chartboost)

Would be nice to see an object and events to display reward/video ads in our game.
We would need the following features for the reward ad:

- Option to Cache reward ads to avoid any lag and freezes due to slow connection
- Is reward ad pre-loaded: condition return true if a reward ad is pre-loaded and ready to display, in some case ad provider may run out of ads or our configuration is wrong, so in case there is no ad to display this is return false and we know there is no ad to show.
- Action to show reward ad video.
- Condition to check if a reward video event is happening now so we know if it not before executing the action to show reward video and can pause the game while it happening..etc
- Condition to check if a reward video event just finished so we know we can reward the player, would be nice to make sure this condition return true only once as we don't want to reward the player 60 times, only once / video
- On the top of this, we also need an option to ask the user if it ok to collect data and display personalised ads or not to collect data to comply with new law.

Among all ad types, personally I find reward ads the only one that actually worth something because it is optional, not forced on the players and both party get something out of it if the player accept it. I make revenue and the player get some in-game item for free. The ads also very short and sometime even really useful I have discovered really cool apps and games through reward ads. In some games I'm looking forward to watch reward ads while there are many games and apps I have uninstalled straight away only because it was pushing ads in to my face all the time. I personally hate them and for that reason I never consider to use them. Reward Ad is the only one I do consider using.

I'm currently working out the details of a project that I would love to make in GD5 but reward ads would be key part of the game for making revenue. Would be awesome if someone could throw this in to the doing section right now.

If it motivate someone I have 100 euros to pay anyone who willing to implement this. I pay only through PayPal or a service accept PayPal like itch.io or Gumroad. To contributors ever implemented a complete feature in to GD I'm willing to pay 30 euros up front and 70 when deliver. If it happens to be @4ian  itself I'm willing to pay the full amount up front to you. To people jumping out of the blue I pay only when deliver. It need to be done in a way to assure compatibility with future versions of GD5 and if it would also compile with the online build service so we do need the approval of @4ian  first and then we can talk money.

Let me know here if anyone interested in the paid part this way I know if you are a contributor or someone out of the blue. We can discuss payment in email once 4ian conformed if he willing to maintain this once implemented.

Thanks in advance.

**Comment by bil-ash** [comment]
https://www.google.co.in/url?sa=t&source=web&rct=j&url=https://github.com/ratson/cordova-plugin-admob-free
The above link points to a cordova plugin which supports admob rewarded videos. If this is to be used the current admob plugin used by build system has to be replaced by this one. I believe that apart from this reason there is another reason why the plugin should be replaced-it seems to be outdated(not updated for many months)

**Comment by 4ian** [comment]
This may indeed be a matter of adapting a new/updated/upgraded plugin for Admob (or other) :)

**Comment by 4ian** [comment]
I added a card on the roadmap for this: https://trello.com/c/RTYnNXUd/169-add-support-for-reward-video-ads

**Comment by 4ian** [comment]
@ddabrahim You should consider opening a bounty here: https://www.bountysource.com/teams/gdevelop/issues?tracker_ids=3677421

$100 might put enough visibility to have new programmers looking at it. It could also allow other people to add money to the issue.

**Comment by oussama-HA** [comment]
@4ian Gdevelop depends on Cordova plugin called "cordova-plugin-admobpro" this plugin is Not Free. The plugin will automatically take 2% off revenue once your app makes more than $1000. If you do not want to take 2% revenue you can buy a license for $20. You can read more about the license.

As Google AdMob does not disclose how much revenue an app has made. This plugin will estimate when your app will make $1000 and then take 2% revenue. All of this sounds very unclear to me. Also, there is no saying if the revenue will be increased from 2% to 10$?

On the other hand, there is a very good alternative Free and open source plugin with a lot of great features and best of all with no hidden fees or any sort of revenue deductions, check it out on the following link: https://github.com/ratson/cordova-plugin-admob-free

It will be great to replace the current plugin with this one

**Comment by 4ian** [comment]
Indeed, cordova-plugin-admob-free seems the best choice and we should move to it. It should not be too hard, mainly change API calls in [`admobruntimeobject.js`](https://github.com/4ian/GDevelop/blob/master/Extensions/AdMobObject/admobruntimeobject.js), update comments.
My help could be needed to have the plugin inserted automatically for Cordova when building online. Otherwise, anyone can implement this by installing Cordova tools (https://cordova.apache.org/)

It's also supporting the video reward, which could be implemented quickly after!
I've created a card for tracking the update to `cordova-plugin-admob-free`: https://trello.com/c/obmkZH0Q/170-update-admob-object-to-use-cordova-plugin-admob-free

@blurymind @Lizard-13 @Wend1go @Bouh Pinging you in case anyone is interested to look at this :)

**Comment by oussama-HA** [comment]
> EDIT: Thanks @oussama-HA for letting me know about this plugin :)

You welcome @4ian  :) I am the one who should thank you million times for this wonderful game engine.

> My help could be needed to have the plugin inserted automatically for Cordova when building online. Otherwise, anyone can implement this by installing Cordova tools (https://cordova.apache.org/)

@4ian Can you please share with us a simple tutorial on how to get this done while building locally with Cordova CLI

**Comment by ddabrahim** [comment]
> @ddabrahim You should consider opening a bounty here: https://www.bountysource.com/teams/gdevelop/issues?tracker_ids=3677421

Looks interesting but it is unclear to me how it is works? Is Bountysource going to charge me up front for the money and then pay it to a developer claim to have done the job that all contributors need to accept? This is what it seems to me when I try to post a bounty on the issue it takes me to paypal to charge me up front.

Unfortunately I can't afford to give this money away up front and only hope someone take it one day, I need this feature now. I need to know if someone with reputation willing to do it now and then I'm willing to pay either X% up front or even the full amount depends on who that person is. Active contribution on GitHub to any project is a must.

Anyone can register at Gumroad and get paid by direct bank transfer, or register at itch.io and get paid through PayPal. If anyone interested, throw me a link to an itch.io page with a donate button or PayPal link or Gumroad account or any other option prefer where I can pay with PayPal and after agree either publicly here or privately in email when the feature will be delivered I'll pay the money. If no one show up very soon, I need to move on and go with something that either has reward add support already, or I can implement it myself. Unfortunately I can't implement it myself in to GD that's why I thought I make this offer.

Thanks.

**Comment by oussama-HA** [comment]
@ddabrahim That's why I asked @4ian for a simple tutorial that explains to us how we can get the advantage of the cordova plugin "cordova-plugin-admob-free" (this plugin has a reward video Ad feature)

Because when you build locally using Cordova CLI you can add whatever plugin you want the only thing that is not clear for me is how to implement that in my GD exported project. Hope @4ian will help us here

**Comment by Lizard-13** [comment]
@ddabrahim Seems that nobody else is on it so I can give it a look, a good opportunity to check if the admob extension is actually broken as some users say. I don't promise anything yet.

**Comment by oussama-HA** [comment]
@Lizard-13 The current admob extension it's not broken, it lacks s lot of features + the developer show his ads on your apps, that's why we want to adapt another plugin call cordova-plugin-abmob-free. Can you please help us with a simple tutorial that show how we can implement this plugin in our Gd project?

**Comment by Lizard-13** [comment]
A tutorial for the current plugin?, never used it, but I'm digging and can write a tutorial (maybe update the wiki) if I get it to work :)

**Comment by oussama-HA** [comment]
@Lizard-13 Thanks a lot for that; but I asked a simple tutorial or wiki not for cordova-plugin-abmob-free not current plugin, as @4ian  said in the previous comment:

> My help could be needed to have the plugin inserted automatically for Cordova when building online. Otherwise, anyone can implement this by installing Cordova tools (https://cordova.apache.org/)

**Comment by bil-ash** [comment]
@ddabrahim I am working on implementing the features you need. I started with cordova-plugin-admob-free but its rewarded ads implementation is outdated and also requires mediation. So I have moved to admob-plus(written by the same author). Its android implementation will have some problems for gdevelop. I shall try to make the necessary changes and then implement the extension. Hopefully, I shall be able to develop the extension by Monday. I haven't made any PR till now so may be you or someone else might need to help me with the PR after I finish development on my local system.
@4ian The current admob extension for GDevelop 5 depends on C++ code to a great extent. So I shall leave it untouched and implement the new admob extension as a jsextension with the name CdvAdmob or CordovaAdmob,so that after it is ready the old extension can be removed from GD5 and the new one can be renamed to Admob. Is it OK?

**Comment by oussama-HA** [comment]
@bil-ash That's will be great, I can't wait for it :)

**Comment by 4ian** [comment]
> The current admob extension for GDevelop 5 depends on C++ code to a great extent. So I shall leave it untouched and implement the new admob extension as a jsextension with the name CdvAdmob or CordovaAdmob,so that after it is ready the old extension can be removed from GD5 and the new one can be renamed to Admob. Is it OK?

Yeah depending on how changes are important you can create a new JsExtension.js file, following https://github.com/4ian/GDevelop/blob/master/newIDE/README-extensions.md :) It will be ok to then remove the old extension when we have the new one ready :)

> Its android implementation will have some problems for gdevelop

What kind of problems?

**Comment by 4ian** [comment]
@bil-ash Can the variable be added to Cordova `config.xml` file instead? Or any other file that could be generated during export?

**Comment by bil-ash** [comment]
Yes it can be added to the config.xml file.
I tried showing ads using the plugin(a particular release),banner and interstitial ads work fine but video ads do not. I created an issue regarding this(although there was already a similar issue to which the author hasn't replied).The author has made some commits recently, I shall check if  now the video ads are shown properly.
The plugin which I am using is-
https://github.com/admob-plus/admob-plus

**Comment by 4ian** [comment]
> Yes it can be added to the config.xml file.

Sweet :)

Good idea to open an issue. If the rest is working, it's probably that something is broken in the plugin - unless you made a mistake somewhere. 

Let me know if you get something working, I can then provide help for integrating the extension and modifying the export to have the variables declared.

**Comment by oussama-HA** [comment]
@bill-ash Hi bill, any updates about the new admob plugin?

**Comment by bil-ash** [comment]
@ddabrahim @4ian Till now I could not get the admob rewarded video ads to work, banner and interstitial ads work fine though.Also the issue which I created for the same hasn't been answered.
I could implement unity rewarded video ads using a different plugin-
https://github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2
What should I do?Wait for the next stable release of admob-plus plugin(hoping that it solves the rewarded video problem) or implement rewarded video ads using unity ads or do something else(suggestions welcome)?

**Comment by ddabrahim** [comment]
@bil-ash first off all, I'm really appreciate the efforts you are making. It seems to me the developer of the admob plugin ignoring the problem with reward video ads, or simply did not figured out a way how to solve it because you are not the only one facing problems and asking questions but get no reply. So this admob plugin is definitely a no go because we need something that is actively maintained and taken care of. If ads does not work in your app only for a week it could be a horror as the point of this add is to get paid if watched and reward the player for watching and the reward need to be something that players do need in order to enjoy the game and to be motivated to watch ads. If the ad doesn't work the game may just become unplayable and kill the game.

To be honest I'm not sure if I can trust any cordova plugin as even Construct users experiencing the very same problem right now simply because of the cordova plugin used under the hood even though it is part of the core. Best scenario would be to make a custom plugin that would be maintained by 4ian but of course I don't expect that to happen.

An other possibility that I mentioned on the forum and probably everyone is against it is that @4ian could make a deal with the developer of the admob plugin. The developer is currently looking for monthly donation to support the development of the plugin. It would be possible to make this feature exclusive to subscribers only in GD and 4ian could make a deal to pay X% revenue share from the subscription and it may encourage the dev to pay more attention to the reward video ad problem and to also maintain it for us. But it is down to 4ian to make this decision and contact the dev of the admob plugin with this offer and also depends on if the problem is being ignored for financial reasons.

The unity plugin is something I have never considered and I don't really know right now if I would be interested to use UnityAds. I need to look in to it. The ones I would be interested is AdMob, Amazon and Chartboost but feel free to discuss about Unity, is it worth it? Would that work? Did anyone use it before?

I'm going to consider UnityAd but until then I would say to wait and see if the dev of the admob plugin going to fix it and I also would like 4ian to consider what I just mentioned about subscription because ad networks constantly changing, evolving, even if you get it working today, tomorrow it may going to fail so it would be very important to be maintained this is why I don't personally mind to spend money on it to get it implemented but also after to keep it maintained...

Thanks everyone.

**Comment by oussama-HA** [comment]
@bill-ash I think we can adept this plugin since banner and interstitial ads works fine, for rewarded videos we can reach the developer for more insight about the issue

**Comment by ddabrahim** [comment]
Could also try Cocoon for reward video ad
http://ludei.github.io/atomic-plugins-docs/dist/doc/js/Cocoon.Ad.html

But then we need to use the Cocoon build service and their Ad plugin.

**Comment by bil-ash** [comment]
@ddabrahim Most probably striking a deal with the admob plugin author would be the best solution. But that depends a lot on the plugin author and @4ian

Nevertheless, I shall try and see if it is possibe to use the cocoon plugin in plain cordova.

**Comment by bil-ash** [comment]
@ddabrahim Most probably striking a deal with the admob plugin author would be the best solution. But that depends a lot on the plugin author and @4ian

Nevertheless, I shall try and see if it is possibe to use the cocoon plugin in plain cordova.

**Comment by 4ian** [comment]
I'm away and have not read everything, but if there is an issue with
https://github.com/admob-plus/admob-plus, best solution is still probably
to see with the author how to fix it. Should not be that difficult and the
rest of the plugin looks good?

**Comment by ddabrahim** [comment]
@bil-ash Not sure what the licensing is, but I think the Cocoon Ad plugin is restricted to be used with Cocoon build service only. In the other hand, Cocoon seems broken as well. I tried a build yesterday and the build is still going, also many people on the forum complaining about ads and other Cocoon plugins does not work many even started topics about Cocoon is dying.

I think the best solution is to wait and see if the dev of the admob plugin show up and reply something but there are issues with reward video ad been posted months ago and the dev did not replied to them, It is not a good sign at all considering the developer is active on GitHub. Definitely ignoring the problem and I hate that.  I don't trust this guy and his plugin.

Thanks for trying anyway.

**Comment by oussama-HA** [comment]
@ddabrahim in this case I suggest to fork this plugin and we will hire a freelancer to fix the issue of video reward ads and the community of gdevelop will take of the plugin. What you think?

**Comment by oussama-HA** [comment]
@4ian @ddabrahim @bil-ash You can reach the dev via this email: contact@ratson.name 
his website: https://ratson.name/

**Comment by ddabrahim** [comment]
@oussama-HA 
I'm not much of a Java and JS coder, have no clue how this plugin works under the hood so me forking this plugin to maintain it, well, maybe one day but I don't have the skills right now, But yeah, would be nice if someone could do it if the original developer won't.

Paying a freelancer to fix it, well... GD is not my project nor the plugin and I'm not forced to use any of them, only because I love GD and would like to use it for my project I offer100 bucks to anyone able to get reward video ad working in GD all together IF 4ian also agree to maintain it and make it work with the build service. But realistically 100 bucks is barely enough to pay a freelancer to fix the plugin and implement it in to GD but this is all I have to offer....

**Comment by rikazukun** [comment]
As far as I remember for the reward video to work,
don't you need to connect it to firebase on the admob dashboard to make it work?

**Comment by ddabrahim** [comment]
@rikazukun Firebase is optional, you can use it to import the SDK but you can also do it manually.

**Comment by oussama-HA** [comment]
@ddabrahim I guess the best solution here is to build a costume plugin for GD based on cordova-plugin-admob-plus

**Comment by ddabrahim** [comment]
>  best solution here is to build a costume plugin

Agree but I don't think 4ian would be interested to maintain it and it would become broken quickly.

@4ian Since no one seem to have time or able to get this working at the moment but I do need assurance now to make sure it will be there when I need it so I can start working on my project, I am considering to drop this offer and do my project in an other engine so you might want to delete the ticket from trello. I'm sort of making the last call to anyone interested then I'm going to remove the offer from the title....

Of course as I don't trust everyone I understand if most people do not trust me either and wondering is there anyone here who would be interested but want to see the money first? Would that help if I would post the bounty on Bountysource? I would be get charged up front and you only need to claim the money, you can also mark the project you are working on it I believe. So the money would be sitting there and you just need to claim it when you have the job done.

I understand bounties normally going for a long time until someone get the job done but unfortunately I can't afford to leave the money and the offer hang in the air for weeks and months. I need to know now if someone is out there.

@bil-ash on trello @Lizard-13 mentioned he got reward video ad working ounce and told going to check again to make sure it still works but then when I offered him money to get it implemented he did not get back to me maybe because you were first trying and he/she did not want to take your opportunity or he/she is busy with studies or may feel offended by my offer or I don't know. But in case not even Lizard-13 got it working after all and the dev of the plugin ignoring the problem I'm simply not interested using that plugin by that person not even if someone get it fixed at this very moment. As I mentioned I don't want to risk reward video ads stop working following an update especially not if the dev is so ignorant about it. Banner and clickable ads I don't care but reward ads must work all times. I'm really appreciate the attempt though.

So last call everyone, with three questions:
1. Is the plugin works on Android at this very moment?
If it not, then I am not interested waiting for someone to fix the plugin also because it would work only until the next update and it doesn't seem to be maintained.
2. If the plugin works, is there anyone right now willing to implement it for 100 bucks?
3. If the answer to 1. and 2. is yes, would you prefer me to hand the money over to Bountysource first would that create any trust or if it not that what other option is there?

Thanks everyone.

**Comment by rikazukun** [comment]
The plugin works on android and the rewards, just need the updated stuff to be implemented. I haven't checked the whole process or how stuff works behind the scenes on GD so I can't totally add or do stuff yet, but I tested it only with cordova stuff.

**Comment by Lizard-13** [comment]
@ddabrahim I get it working, and doing the extensions right now, here is the pull request: https://github.com/4ian/GDevelop/pull/702
Let's wait until I finish it and that we can confirm it indeed works, you know I'll be around so I can update it if needed, even switch to another plugin :)

**Comment by ratson** [comment]
Hi, `cordova-admob-plus` author here, it seems you guys have gone quite far.
No one has emailed me for this :(

As I am still evolving the plugin and its APIs, I would like to know what is missing to be used in this project.

I think collaboration of this should reduce the maintenance effort and result in higher quality of the plugin. Just want to know if there are any interests on accepting PR for this.

**Comment by 4ian** [comment]
Hey @ratson thanks for writing here 😄 
@Lizard-13 has started implementing a PR here: https://github.com/4ian/GDevelop/pull/702
It's using your plugin `cordova-plugin-admob-free` though for now, I think he'll be able to tell you what or if there is missing with cordova-admob-plus.

I think he spotted a bug in `cordova-plugin-admob-free`: https://github.com/4ian/GDevelop/pull/702/files#diff-03c63f1e1a520376be2d142301cd5e06R233

Again I think I'll be able to tell you more, apart from this from what I'm seeing it's working well :) When it's ready I'll merge the PR, remove the old GDevelop extension for Admob and people will be able to start adding ads in their games with the new plugin.

**Comment by Lizard-13** [comment]
@ratson Hi, sorry for not emailed you, the plugin is working great so far :smile: 
I'm used to workaround bugs when it isn't my code, and when open an issue I try to give possible reasons/solutions, but had not the time to view your code (and never worked with cordova plugins before), also the bugs where already reported.

I've explored two options, yes, your two plugins:
* cordova-plugin-admob-free: There is a bug about banners OPEN and CLOSE events never getting called (reported here: https://github.com/ratson/cordova-plugin-admob-free/issues/249 although it's failing in Android here). I've workaround it with some extra variables and checks, nothing fancy and works great.
What is concerning me a bit is the mediation plugin, the test ads are working so far using the test id's from google: https://developers.google.com/admob/android/test-ads , and I was wondering if I need to install the mediation plugin, I'm almost sure I'll have to do it, just want to make sure :smiley: 
It would be as easy as add the plugin to the cordova config file around here: https://github.com/4ian/GDevelop/pull/702/files#diff-57da99d748dc41b6e9c429e7f99adad9R233
* cordova-admob-plus: This one has a problem when installing it, as it doesn't add some information to the android manifest file (reported here: https://github.com/admob-plus/admob-plus/issues/13). I can fix it manually editing the file myself as it's suggested in the issue comments (and everything seems to be working nicely :D ), but it's impossible to use with the online service, that's the reason to use the first plugin so far (although I haven't used it a lot because the bug).

**Comment by Lizard-13** [comment]
Thanks for the info!

So I think we will stick with cordova-plugin-admob-free for now, as I can't make the admob-plus to work again :expressionless: , it crashes on startup although the application id is correctly added to the manifest file now. Also I can't make it to install the plugin remotely (adding the plugin data on the cordova config file) because a missing variable definition, even if I define the old ADMOB_APPLICATION_ID and the new APP_ID_ANDROID and APP_ID_IOS ones.
Will follow the new plugin and try to help you if needed :)

**Comment by 4ian** [comment]
This will be supported in next version! Thanks @Lizard-13 for implementing it and thanks @ratson for your formidable Cordova plugin and for your support here!

**Comment by 4ian** [comment]
GDevelop 5 beta 56 includes the new AdMob actions, as well as an example.
I've written a page explaining how to use it on the wiki: http://wiki.compilgames.net/doku.php/gdevelop5/all-features/admob

**Comment by 4ian** [comment]
@ddabrahim Can we close the issue now that the support is added?

**Comment by 4ian** [comment]
👌
And thanks @ratson for your Cordova plugins :) Hope this will be used a lot by GDevelop users!
