### ISSUE TITLE
Hide window border function

### ISSUE THREAD

**Issue by mousekkkss** [4ian/GDevelop#6903]
Please add an option to hide the window borders.

Please add an option to make the background transparent

Please add an option to keep the window fixed to the front

I discovered these features when I was planning to use gdevelop to make Vpet.

These features can realize some specific game styles and concepts.

If you read this request, thank you very much. I am grateful to the developers, this engine has infinite vitality.

These features can make the game better.
❤

**Comment by ClementPasteau** [comment]
Hi @mousekkkss 
Thanks for the kind words, please open your request on the forum as this is where we gather all the feature requests.
https://forum.gdevelop.io/c/gdevelop-general/feature-requests
