### ISSUE TITLE
Object properties cannot be set to 0

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#6932]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

![after](https://github.com/user-attachments/assets/24beb11b-d11a-4353-aa97-e80e82aadcf6)

![after](https://github.com/user-attachments/assets/55775469-1f1e-4202-a53e-a06e12a1db56)

### GDevelop platform

Desktop, Web

### GDevelop version

5.4.210-e9b4de2ca9fc5e520ec99d0a9084becd5e0226a9,

**Comment by ClementPasteau** [comment]
We're working on a fix and will release a new GDevelop version asap.
