### ISSUE TITLE
Pixel Art looks bad when resizing the game in windowed mode

### ISSUE THREAD

**Issue by YounesSamatta** [4ian/GDevelop#6947]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

It looks fine when in fullscreen 
![GDevelop_e7diopszR0](https://github.com/user-attachments/assets/3b16c3a3-bd27-4203-aade-9d6f407c0407)
But in windowed mode it gets deformed when moving, it more noticable when looking at the character's face

https://github.com/user-attachments/assets/4bbb0101-41cf-4d83-889a-f0ec073a2411

### Steps to reproduce

1. Resize the window 
2. See the pixels get deformed

### GDevelop platform

Desktop

### GDevelop version

5.4.211

### Platform info

</details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
>Windows 10

</details>

### Additional context

The resolution of the game is 464 x 261

**Comment by D8H** [comment]
This is not really a bug. For pixel art, you need to choose the pixel size and scale in linear, not nearest neighbors.
Take a look at this example:
https://gdevelop.io/game-example/free/platformer-with-tilemap

**Comment by YounesSamatta** [comment]
yep i managed to fix it by changing the resolution to 720p and zooming the camera
