### ISSUE TITLE
Update Twitter Icon to X Icon

### ISSUE THREAD

**Issue by tanish0912** [4ian/GDevelop#6991]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Update Twitter Icon to X Icon

**Description:**

The current social media icon for Twitter is outdated and should be replaced with the new "X" logo as per the rebranding of Twitter to "X". This update will ensure consistency with the new branding of the platform.

**Expected Behavior:**

- The Twitter icon should be updated to the new "X" logo across all instances on the website, in the footer.

**Screenshot:**
<img width="1440" alt="Screenshot 2024-09-27 at 12 20 36 AM" src="https://github.com/user-attachments/assets/05dd02fb-af81-4ef7-85e4-d1cf7077541e">

### Steps to reproduce

1) Go to the website footer.
Look for the social media section.
Observe the outdated Twitter logo, which should be replaced with the "X" logo.

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.4.213

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by tanish0912** [comment]
@triptych @brylie @dejw @dos1 
The twitter icon needs to be updated to the new 'X' logo, Please assign this issue it to me.

**Comment by 4ian** [comment]
Please don't tag people on an issue, especially if they are not directly related to this. There is also no need to be assigned to anything. Thank you!

**Comment by AlexandreSi** [comment]
This update should be available soon.
