### ISSUE TITLE
Extensions with parameters that require placing an object are not displayed in the GDevelop action selector

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [4ian/GDevelop#7003]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I'm having problems with GDevelop, I install or try to make an extension that requires an object as a parameter and it is not shown in the action selector of the game events

![imagen](https://github.com/user-attachments/assets/bf704059-e66a-49a6-ae80-a43a3c69a047)

That extension that is in the screenshot requires an object as a parameter, but it is not shown in the action selector

![imagen](https://github.com/user-attachments/assets/3f783a17-96c6-42ac-a72f-2c7be77da555)

The extension that I installed should be shown in the "Game Mechanic" section but it doesn't show up

![imagen](https://github.com/user-attachments/assets/5b05d3bd-6f96-4b78-a6b2-0f97970b4215)

The extension that I installed should be shown in the "Game Mechanic" section but it doesn't show up

![imagen](https://github.com/user-attachments/assets/33e65417-16b7-4140-b148-7dff3ee3fc79)
![imagen](https://github.com/user-attachments/assets/61254d11-5451-4895-8aa0-c5b1dd470f40)

And I change the parameter to something other than "Objects" then it does show up

What could be happening?

### Steps to reproduce

Install an extension that requires a scene object as a parameter, it can be the same one that I installed

### GDevelop platform

Desktop

### GDevelop version

5.4.213

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

I hope I'm not the only one this happens to.

**Comment by D8H** [comment]
This is expected, Actions and conditions that apply to objects are in the list for objects. You need to either select an object or find them with the search.

![image](https://github.com/user-attachments/assets/f9cbab3f-999a-4a4f-abfb-e65928c0fb66)
