### ISSUE TITLE
3D sprite extension - receiving shadows and got light influences from point lights etc.

### ISSUE THREAD

**Issue by H4banero1** [4ian/GDevelop#7006]
I`m trying to change the 3D sprite extension to cast and receive shadows. I got shadow casting to work using a alpha value for the material but i have no clue to got this work with entropy 3D extension or pandako`s builtin Advanced 3D Features Extension.

I think there is a need to change the material at all to something else (threejs standard material or something) to make it work.
I myself am apparently unable to do so.

Therefore, I leave the request here.

**Comment by D8H** [comment]
This is not an issue in GDevelop. You should probably move it to the extension repository:
- https://github.com/GDevelopApp/GDevelop-extensions/issues
