### ISSUE TITLE
Let's make the complete translation of Gdevelop 4 into Portuguese !!!

### ISSUE THREAD

**Issue by RodolfoJF767** [4ian/GDevelop#703]
Hi, my name is Rodolfo Franco, I live in Brazil !!! I really want to develop my own android games but I do not understand English yet, you could help me by putting the translation of Gdevelop 4 totalmete in Portuguese !!! I even paid !!! Thank you in advance, and I am waiting for the response!!!

**Comment by 4ian** [comment]
Hey @RodolfoJF767 - thanks for your message. GitHub is only for bugs and technical discussions.

Translations are not part of GD5 for now but you can help translate the existing ones that will be used once GD5 supports multi language here: https://crowdin.com/project/gdevelop

**Comment by RodolfoJF767** [comment]
I just translated to Portuguese, how do I download the complete translation now and put it in my Gdevelop 4 ???

**Comment by RodolfoJF767** [comment]
Are you forecast when will you leave Gdevelop 5 with the Portuguese translation ???
