### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by RodolfoJF767** [4ian/GDevelop#704]
I just translated to Portuguese, how do I download the complete translation now and put it in my Gdevelop 4 ???
Are you forecast when will you leave Gdevelop 5 with the Portuguese translation ???

**Comment by 4ian** [comment]
Please ask these questions on the forum please :) Again this is only for technical discussions.
You can vote for translations on the roadmap: https://trello.com/c/xsPblY6l/52-translations-for-gdevelop-5 - unfortunately I don't know when I'll have time to do this, it's a few weeks of work.
