### ISSUE TITLE
 Error while downloading

### ISSUE THREAD

**Issue by hiarlyalves** [4ian/GDevelop#7080]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Olá,

Estou enfrentando um erro ao tentar empacotar meu jogo no GDevelop para Android. O erro ocorre durante o download de um recurso de áudio e o status do erro é 403 (Forbidden). Abaixo estão os detalhes:

- **Mensagem de erro**:  
  Could not download 1 files: Error while downloading "https://resources.gdevelop-app.com/examples/calcopus-spine-demo/assets/bubble_appear.wav?gdUsage=export" (status: 403)

- **Contexto**:  
  Estou tentando exportar meu jogo para APK via o serviço de exportação do GDevelop, mas recebo a mensagem de erro ao tentar baixar esse recurso específico. Estou usando uma conexão de internet estável (200MB), então não acredito que seja um problema de conectividade.

- **Versão do GDevelop**:  
Esta versão do GDevelop é: 5.4.215 (editor full version: 5.4.215-0a85fd3814aec1f0e373f3263987151e1903d922, core version: 5.4.215-0)

- **Sistema Operacional**:  

Windows 11 - 16GB Memória HD 1T

- **Passos já realizados**:  
  - Testei acessar o link do arquivo diretamente, mas recebi o erro 403.
  - Verifiquei minha conexão com a internet.
  - Tentei exportar para Android APK e Android App Bundle, mas o erro persiste.

Agradeço se alguém puder ajudar a entender e resolver esse problema.

Obrigado!

### Steps to reproduce

![image](https://github.com/user-attachments/assets/b0d901cb-fbe8-482a-b51a-b3ad13adea9b)
![002](https://github.com/user-attachments/assets/05d61378-a313-493a-ba27-66fa32befc23)
![001](https://github.com/user-attachments/assets/b414cbf0-a009-4dfb-906a-4b830b4cddf2)

### GDevelop platform

Desktop

### GDevelop version

5.4.215-0

### Platform info

<details>

* Windows 11
>

>

*Browser(For Web) (e.g. Chrome)*
>
Android
>

</details>

### English translation

Hello,

I am facing an error while trying to package my game in GDevelop for Android. The error occurs during the download of an audio resource, and the error status is 403 (Forbidden). Below are the details:

- **Error message:** Could not download 1 files: Error while downloading "https://resources.gdevelop-app.com/examples/calcopus-spine-demo/assets/bubble_appear.wav?gdUsage=export" (status: 403)

- **Context:** I am trying to export my game to APK via GDevelop's export service, but I receive this error message when trying to download this specific resource. I am using a stable internet connection (200MB), so I don't believe it is a connectivity issue.

- **GDevelop Version:** This version of GDevelop is: 5.4.215 (full editor version: 5.4.215-0a85fd3814aec1f0e373f3263987151e1903d922, core version: 5.4.215-0)

- **Operating System:**

Windows 11 - 16GB Memory, 1TB HD

- **Steps already taken:** I tried accessing the file link directly but received the 403 error. I checked my internet connection. I tried exporting to both Android APK and Android App Bundle, but the error persists. I would appreciate any help in understanding and resolving this issue.

Thank you!

**Comment by ClementPasteau** [comment]
Hi @hiarlyalves, thanks for reporting.
This error usually means it's trying to download an asset that doesn't exist.
Indeed, the example is trying to use a sound called `bubble_appear.wav` which doesn't exist in the project. 
You can try to remove that line in the example for a quick fix. 
![image](https://github.com/user-attachments/assets/466dfbb0-a464-4adf-8d07-751acde4a830)


I'll update the example accordingly to fix that issue in the meantime

**Comment by ClementPasteau** [comment]
The Spine example has been fixed and now points to the right path for this sound.
I'd suggest to re-open it, or download the sound here https://resources.gdevelop-app.com/examples/calcopus-spine-demo/assets/sound/bubble_appear.wav and use it in place of the red line in my previous screenshot
