### ISSUE TITLE
Even if the parameter type is audio, the input interface is just a text field.

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [4ian/GDevelop#7085]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Even though I set the parameter type of the action in the extension to audio, the input interface is just a text field.
Therefore I am not able to select an audio file.

This problem does not occur with behavior properties.

![image](https://github.com/user-attachments/assets/3ea4c464-7fb6-469e-92e6-8ba897856832)
![image](https://github.com/user-attachments/assets/846fb796-6d15-4fde-83fa-9866a3480854)

This is the ideal interface.
![image](https://github.com/user-attachments/assets/70076c5c-d946-4f2a-9948-e6a849ae7b55)

### Steps to reproduce

1. Create a new extension.
2. Add an action to it.
3. Add a parameter of resource type audio to it.
4. Use the action in an event.
5. Verify that the interface is problematic.

### GDevelop platform

Desktop

### GDevelop version

5.4.216

### Platform info

Windows 11

**Comment by AlexandreSi** [comment]
Thanks @PANDAKO-GitHub for raising this issue, the fix will be available in the next release.
