### ISSUE TITLE
Minor English Language Corrections to "My Profile" in GDevelop5

### ISSUE THREAD

**Issue by ValiantCuriosity** [4ian/GDevelop#710]
Please see the included image to view some possible English Language corrections for the "My Profile" popup in GDevelop5. Changes are noted in red.

![myprofileenglishcorrections](https://user-images.githubusercontent.com/38298990/47274426-09069780-d55a-11e8-831a-79db422e554a.png)

**Comment by 4ian** [comment]
Closing as all suggestions have been integrated :) Thanks for reporting this!
