### ISSUE TITLE
When trying to run GDevelop Electron Desktop get error related to firebase file

### ISSUE THREAD

**Issue by ValiantCuriosity** [4ian/GDevelop#711]
I've been attempting to use GDevelop on the desktop. I've followed all of the steps to get it running, but I keep receiving the following error. Any help would be appreciated. TIA

![rungdelectrondesktop](https://user-images.githubusercontent.com/38298990/47274653-37857200-d55c-11e8-83a9-12ff726b7012.png)

**Comment by 4ian** [comment]
Closing this as duplicated with https://github.com/4ian/GDevelop/issues/712
