### ISSUE TITLE
A splash screen "bug"

### ISSUE THREAD

**Issue by stuffbymax** [4ian/GDevelop#7145]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### in GDevelop in json file. the 
```
"showGDevelopSplash": true,
"showProgressBar": true  
```
### can be disabled both in json and of course no subscription needed :) 

![Screenshot_2024-11-10_22-36-47](https://github.com/user-attachments/assets/e196c71a-ccfa-49fe-9f80-a303b0b5f7ef)

### Steps to reproduce

      "showGDevelopSplash": false,
      "showProgressBar": false
![Screenshot_2024-11-10_22-36-47](https://github.com/user-attachments/assets/e196c71a-ccfa-49fe-9f80-a303b0b5f7ef)

### GDevelop platform

Desktop

### GDevelop version

5-5.4.217

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Arch Linux

</details>

**Comment by Bouh** [comment]
Hello,

Thanks for the report. This is known by the team and isn’t a bug; it’s designed this way. The team will consider changing this approach if any abuse is observed.
