### ISSUE TITLE
Thoughts and bugs about the new Functions

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#717]
I tried out the new "Function" function and would like to share some thoughts.
First of all I'm really impressed about this new feature. This is really awesome and will make the logic of my games a lot easier to maintain. Its almost like creating an extension right inside of GDevelop.

But I noticed some (smaller) issues:

# 1) Wrong focus when creating a new function

## To Reproduce
- Create a new project
- Click on "Add a new function"
- Fill out its head and click on "Add a new empty event"
- Click on the event to focus it.
- Click on "Add a new function"
- Fill out its head and click on "Add a new empty event" --> Nothing happens
- Click on your first function and see that the empty event got inserted there.

# 2) The parameters are hard to differentiate
Especially with the dark theme it is hard to determine where the properties of one parameter end and the properties of the next one start. Maybe you could adjust the lightness of every second row a little bit via CSS or add a coloured delimiter in between.

# 3) Arguments with quotation marks
The `GetArgumentAsString("ID")` uses quotation marks. This differs from the way other keys are used to access a certain variable for example `Object.VariableString(id)`.
Since GD5 doesn't warn you when you use quotation marks (or forget them) in the wrong place, it makes the whole thing even more confusing.

# 4) Function variables
What do you think about adding a third scope of variables that is tied to functions?
That way one wouldn't have to use scene/global variables in a function when all you need is a small temporary variable to store some calculated value or the ID of an object that doesn't need to be stored long term.
When functions get published and later exchanged between users it could cause trouble / hard to find bugs when for example a function creates a scene variable "i" for iterating over something and the users who imported that function are also using the same variable name in their logic.

**Comment by 4ian** [comment]
> Wrong focus when creating a new function

I'll take a look, thanks for writing the steps :)

> The parameters are hard to differentiate

Yeah, I'm not entirely satisfied of the UI here, will try to come up with something better.

> Arguments with quotation marks

Yeah it's a pain, I think in general the expression in GDevelop would need improvement to have warnings when such errors (forgotten quotes) are detected.

> Function variables

That's also something very interesting indeed. I'll take a look at how it could integrate with what we already have :)

Thanks for sharing this, glad to see that functions will be useful! 

> This is really awesome and will make the logic of my games a lot easier to maintain. Its almost like creating an extension right inside of GDevelop.

Exactly :) In fact under the hood functions are converted and loaded like normal extensions - so you're effectively extending GDevelop ;)

**Comment by zatsme** [comment]
Function variables would make this much more robust when reusing code 👌

Also, it would be awesome if you could export a function or group of functions into an 'proper' extension package and share but also potentially expand gdevelop's functionality 🤔

**Comment by 4ian** [comment]
I've added Function Variables/scoped variables to the roadmap: https://trello.com/c/DInLxb44/176-support-for-functions-variables-or-variables-scoped-to-an-event-and-its-subevents

Sharing functions is something that I want to work on later too (there are a few nice things to do), added a card too: https://trello.com/c/3NUXOaG6/177-add-support-for-exporting-importing-sharing-functions - I'm also thinking of things like searching inside a set of functions shared by the community.

I've fixed focus for next version and reworked parameters UI to be shown in a way similar to other parts of the IDE - should be better/clearer :)
For "Arguments with quotation marks", it can be part of an improvement to the way expressions are written.

I'll close this as bug are fixed/feature added to the roadmap :) (even if discussion can continue)
