### ISSUE TITLE
Two audio files with the same name, in different folders, the second added doesnt work on playtest

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#720]
## Describe the bug
This seems to be an obvious issue with audio files specifically - but could affect other file types. I am attaching an example project with the issue.

It happens when two files with the same name exist in different folders, their resource names are different in the project (resource names are relative paths)
(same file names, different paths, different resource names)

When you apply the sound file in the event sheet, the second one does not play during playtest.

Some times (rarely) the issue doesnt happen for some reason 

## To Reproduce
1. add a resource jump.wav, resulting in name 'jump.wav'  (try with jsfx)
playtest (it works)
2. add a resource in subfolder player/jump.wav resulting in name 'player/jump.wav'
playtest (sound doesn't play at all)
3. go to the resource manager and remove jump.wav
playtest (player/jump.wav starts working)

If it doesnt initially happen, try changing in the event sheet between the two files by navigating to them

or
Open the attached project, playtest (jumping sound doesnt play)
[twoFilesSameNameBugExample.zip](https://github.com/4ian/GDevelop/files/2519231/twoFilesSameNameBugExample.zip)

remove the other audio file with the same file name from resource manager,
playtest (jumping sound plays)

Further inspecting this when playtesting , the console shows no error message related to the sound (ctrl+shift+i), when you look at the sources tab - you can see that neither of the jump.wav files were added

This occurs on the latest released version too actually:
https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta55

but it can be in all prvious versions (haven't tested)

**Comment by blurymind** [comment]
@4ian thank you for looking into this

**Comment by 4ian** [comment]
Should be fixed in https://github.com/4ian/GDevelop/commit/569adc150047dc4cd3ea5d11510c4cae89d15bd9 :) 

Files (in different folders or not) but with the same filename will be copied during export but renamed properly (extension will stay the same, only the base name will be updated to be unique).

Just updated libGD.js with this, as usual remove public/libGD.js and relaunch yarn start/npm start.

Let me know if this works so that we can close this :)

**Comment by 4ian** [comment]
Let's close this if you have time to confirm that this is working better :) I've tested with jfxr and it seems ok now :)

**Comment by blurymind** [comment]
@4ian sorry it takes me a while to test this one. Yes please close it :)
Thank you again for the fix
