### ISSUE TITLE
"Drag and Drop the object..." message is cut off in browser and desktop GDevelop5

### ISSUE THREAD

**Issue by ValiantCuriosity** [4ian/GDevelop#722]
## Describe the bug
When loading the initial screen, the help message is not fully displayed.

Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Click "Create a new project" button.
2. Click "Platformer" template
3. Click on a Scene Object
4. See message box. The message is cut off on the right side. 

This happens in full screen on a larger monitor for desktop. If I resize the entire application down, it shows the entire message across the bottom of the screen.
Doesn't work on larger monitor:
![desktopmessagecutoff](https://user-images.githubusercontent.com/38298990/47669346-fd256180-db67-11e8-86b7-cbd0ac855177.png)

Works on resize down:
![screenresizeddown](https://user-images.githubusercontent.com/38298990/47669362-04e50600-db68-11e8-8800-2b7a52b7bd08.png)

**Comment by blurymind** [comment]
I wonder how this can be fixed

It would be nice if the text size shrinks in that case, or at least `...` are added to signify that part of it is cut off. On hover over- show the complete message as a tooltip?

**Comment by 4ian** [comment]
I think the best way to fix it is to reduce the length of the message ^^

The message is displayed in a "Snackbar" provided by Material-UI, but it seems that there is no support for longer text (or at least not in the version being used right now by GDevelop)

**Comment by AlexandreSi** [comment]
After testing it, it appears that the version of material UI we now use wraps the text.
![image](https://user-images.githubusercontent.com/32449369/135231399-166be212-35ae-4566-8a8d-3c256433c87e.png)
