### ISSUE TITLE
Question Related to Properties empty message: "instance"

### ISSUE THREAD

**Issue by ValiantCuriosity** [4ian/GDevelop#723]
This may not be anything to address, but I am wondering about the term "instance" in the help message. Since GDevelop is for people who don't know about coding, I wondered if this term might be confusing. Would "object" be more clear to people who are new to coding? 

I understand that you are talking about an instance of an object as is defined in programming. I admit, though,  that when I first saw the help, I had to think about it for a minute or two for it to make sense to me.

I know this is a little thing. and you have more important work to do in GDevelop. Just thought I'd mention it. If I am not submitting properly, please tell me. TIA

![screen shot 2018-10-30 at 2 50 58 pm](https://user-images.githubusercontent.com/38298990/47753232-0ee43300-dc54-11e8-92f7-36cc18b32c27.png)

**Comment by Lizard-13** [comment]
The term is used in other places, as the Instances list panel. Having said that, I've to admit calling the instances "instances" in the scene editor but call them "objects" in the events editor can be a bit confusing.

**Comment by zatsme** [comment]
IMHO I think that Instances and Objects are quite core terms to understand and without this basic idea users will always be confused.

Maybe we are better off making sure the docs are very clear on the basic concepts, after all it might be easier, but it's still programming!

**Comment by 4ian** [comment]
I admit this can be a bit confusing, but on the other hand that's the proper term to designate "instances" of objects that are living on the scene. And "Objects living on the scene" would be vague.

> IMHO I think that Instances and Objects are quite core terms to understand and without this basic idea users will always be confused.

Yes I agree.

In very first versions, I did not make the distinction in docs but I think it was creating more confusions than anything else.

**Comment by ValiantCuriosity** [comment]
> distinction in docs
> 
I think adding an explanation in the docs would take care of the confusion for non programmers/beginners. Read the docs and learn. ;-)

Also, let me know when/if you need any additional help on the English docs. I don’t really understand GDevelop well enough yet to create some of the documentation related to certain aspects of the inner workings, but I am happy to look at the English grammar. I don’t claim to be a scholar in English, but I do have a little background in technical writing, etc.

BTW, I’m having a lot of fun learning and creating the themes. Thanks for your help on that.

-R

**Comment by blurymind** [comment]
It would be cool if in the hint that gdevelop shows, the text 'instance' is actually a link to the doc that explains what an instance is :)

**Comment by 4ian** [comment]
We could indeed have a `<Link>` component that would open the doc :)

**Comment by 4ian** [comment]
Closing as we'll keep referring to "Instance" to make things clear, even if it's more terms to know for the first time user.
