### ISSUE TITLE
Using custom hitbox for physic behavior

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#724]
I tried to use the custom hitbox of the sprite for his physic behavior but couldn't make it.
I remember that we could do it in GDevelop4, also with none-convex polygons.
Now we have a warning message when the custom hitbox is none-convex and we can't use it for the physic behavior even if it is convex.
Is the correction of this regression planned?

**Comment by timotheeficat** [comment]
That's a good idea, thanks !
I'll close this issue then. I hope this feature will be back in the future :)

**Comment by 4ian** [comment]
I've added it to the roadmap so we can track it: https://trello.com/c/rzomYC61/181-support-custom-hitboxes-for-physics-engine ;)

**Comment by timotheeficat** [comment]
Cool! Thank you very much!
