### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [4ian/GDevelop#725]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by 4ian** [comment]
Can you be a bit more specific? :)
What is the number of people using? Is it really popular? What is the added value? There are tons of feature requests on the roadmap https://trello.com/b/qf0lM7k8/gdevelop-roadmap so I have to be aware of the value of everything before doing something, especially if this means maintaining it in the future for every release

**Comment by LeandroStanger** [comment]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak

**Comment by 4ian** [comment]
Thanks for the link. How many users are using this? What is the "market share" of this compared to other alternatives like AppImage?

**Comment by blurymind** [comment]
I dont think many at the moment. Ubuntu users probably?
If there is such interest,perhaps someone could contribute a 'cooker' script that fetched gdevelop from this tracker and builds it on another as a flatpak?

**Comment by LeandroStanger** [comment]
Here is the list of Linux distributions compatible with Flatpak: https://flatpak.org/setup
You can host GDevelop Flatpak in Flathub a popular repository for Flatpak applications: https://github.com/flathub/flathub/wiki/App-Submission
You can see all about Flatpak on the official Flatpak website: https://flatpak.org

**Comment by 4ian** [comment]
I've added a card to the roadmap https://trello.com/c/oI3Wimzp/183-package-gdevelop-as-a-flatpak-package so that people can vote on it. As usual, any contribution is appreciated for this :)

Closing the issue now as we're only keeping bugs in Issue and keeping features/improvements in roadmap. Discussion can still continue here :)
