### ISSUE TITLE
Custom font not changing size

### ISSUE THREAD

**Issue by SnailMail1** [4ian/GDevelop#727]
I am using a custom font with the sizes changed to red 60 and the black 35. They all appear to be maybe 20 in the IDE window. If I run the preview the size remains the same.

![ideview](https://user-images.githubusercontent.com/44212084/47926201-62de5a00-de96-11e8-806a-9863c9d46e80.PNG)

![fontsize60](https://user-images.githubusercontent.com/44212084/47926208-6b369500-de96-11e8-91c0-bfd851ade154.PNG)

![fontsize35](https://user-images.githubusercontent.com/44212084/47926220-725da300-de96-11e8-93d0-b7e4549d9fc4.PNG)

![fontsize](https://user-images.githubusercontent.com/44212084/47926233-77baed80-de96-11e8-9bdd-93333a3b6cd7.gif)

**Comment by rikazukun** [comment]
I believe that is the default font. Import your font without the quotation marks ("") and by specifying it's extension. ex: 8-bit pusab.ttf

**Comment by SnailMail1** [comment]
That did it, thank you!
