### ISSUE TITLE
Search an object then drag and drop : wrong object placed on the scene

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#739]
## Describe the bug
If you search an object in the object list, then only this object (or objects with similar names) will display (wich is normal), but if you try to drag and drop on scene object form this sorted list, it's not the good object that is created.

## To Reproduce
1. take a project with a lot of object on a scene
2. search in object list or one object in particular
3. Try to select and drag drop it to the scene
4. See error : the wrong object is picked

Last GD version 5.56

**Comment by 4ian** [comment]
Indeed, will have to fix that. Thanks for reporting this!

**Comment by 4ian** [comment]
Better late than never right? Fixed in 01b854b :)
