### ISSUE TITLE
Export to Windows/linux/MacOS : desktop icon doesn't work

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#740]
## Describe the bug
If you put a desktop icon for the project, then export to windows, the exported project returned by the builder doesn't have the icon.

## To Reproduce
1. open a project
2. pick an icon 512x512px for "desktop icons"
3. Export for windows
4. See error : the .exe is still with Gdevelop logo icon

I did'nt tested for MacOS (i don't have  mac), but same problem occures on linux.

**Comment by KinkGD** [comment]
+1
I'm about to release a demo, the customs icons for Android works well, but desktop versions still don't use the icons : 

![image](https://user-images.githubusercontent.com/8144048/51793896-0609eb80-21c8-11e9-8946-c15650c39902.png)

It's the Gdevelop logo instead.

**Comment by KinkGD** [comment]
News from the front:

The icons aren't working if they are done manually and/or if their path isn't the root path: 
- All my icons, at each dimension, were created manually by me, and added in the project manager : when exporting for windows/linux/mac => **this is not working**, the gdevelop icon is used instead. The path of all the icons was /projectfolder/images/icons/*.png
- If you use the button "generate the icons form a file": all the image icons are created by gdevelop and created at the root folder of the project. When you export for desktop => **It works, icons are applied properly** !

@4ian maybe the issue can be closed, but i suppose/suggest a disclaimer on the icons panel : 
- If you don't use the "generate icons from a file" button, make sure your icons files path is the root folder of your project, or the Gdevelop icon will be used instead.

:)

**Comment by PawBud** [comment]
We can close this issue then @KinkGD @4ian
