### ISSUE TITLE
Destroy a Joint

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#749]
As far as I can tell, the only way to destroy/remove a physics joint from two objects is to disable to physics behaviour of one of the objects.

Whilst this works, it will destroy all physics for the object so if you have more than just the one joint it's a pain.

The solution is to expose Destroy(jointID) but of course this brings us back to the problem in my other request #747 as we would need to be able to save jointID's for this to work properly.

Zat.

**Comment by 4ian** [comment]
What would be needed here would be to be able to attach a name or a number to the joint so that you can remove it later indeed

> in my other request #747

Joints are not GDevelop objects so it's a different issue :)

**Comment by zatsme** [comment]
Yes, I meant if I want to remove a joint from a specific instance of an object, I'd need the jointID and the instanceID which you'd already have in a code based engine when you created them.

**Comment by KinkGD** [comment]
+1 for the feature, remove a hinge might be really useful.

**Comment by 4ian** [comment]
Added here: https://trello.com/c/PE9OpJ9f/189-allow-to-remove-a-joint-created-on-physics-engine :)

Will close this to keep only bugs in issues. Conversation can continue here
