### ISSUE TITLE
Allow to save project in multiple files 

### ISSUE THREAD

**Issue by srluccasbrandao** [4ian/GDevelop#758]
Allow to save project in multiple files (one for each scene, external scene, external events) to ease collaboration.

 That was the main reason I still had not migrated from Construct 2/3 to GDevelop! I need to work as a team! Thanks for the work!

**Comment by 4ian** [comment]
Hey! There is exactly this card on the roadmap: https://trello.com/c/E5x4JUVt/113-allow-to-save-project-in-multiple-files-one-for-each-scene-external-scene-external-events-to-ease-collaboration => You can vote for it :)

It's an interesting feature indeed, and Iwould like to add this if more people are voting/asking for it :)

Note that if you're in a team and used to source control programs like git, it's a good way to share your work (GDevelop files are json, so they can be merged by git if you are careful).
But yeah obviously everything would be easier for collaborating with multiple files. 

I'll close this issue to keep the list of issues clean, but discussion can continue here :)

**Comment by 4ian** [comment]
> I need to work as a team!

I'm interested by your use case: how many are you (or would you be)? What would be your main use case? Something like working on different levels at the same time? Thanks!

**Comment by BWPanda** [comment]
I'd like this feature. In fact I thought that when I created an external event that it would be saved as a separate .json file in my project folder. I was surprised that it's still saved as part of the main .json file...

**Comment by 4ian** [comment]
Make sure to vote for it on the roadmap then ;)
