### ISSUE TITLE
Inline comments

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#759]
It's great we have groups, which I use to separate and describe the next section of code, and comments which is an absolute necessity in any program!

But to comment thoroughly, which is very useful for tutorials and if you are debugging/helping others you need to be able to comment on an action by action basis IMO.

My suggestion is this..... as I have no clue about electron I don't know how easy or even if it's possible to do?!

On the right click menu you have 'Add Comment'

![2018-11-21 1](https://user-images.githubusercontent.com/17770123/48864170-a6582400-edc3-11e8-9a96-1c1d915a4ab5.png)

and after adding the comment you will get a popup when hovering over the code....

![2018-11-21 2](https://user-images.githubusercontent.com/17770123/48864210-c4258900-edc3-11e8-9e65-2ece7be5d539.png)

Zat. 🤔

**Comment by 4ian** [comment]
Technically it's feasible :)

But I'm not sure that comments would be really discoverable if you actually have to hover the mouse on the action. Not sure that people would get use to do this. Could also create problems like if you copy an action, you copy the comment and end up with invisible comments that are wrong at multiple time in your event sheet.

**Comment by zatsme** [comment]
In excel and google sheets they put a small graphic in the edge of the cell so you could do that to signify a comment is embedded...

But I take your point, I guess I'm used to 'real' coding and being able to comment anywhere I like which is useful when you've not looked at some code for a while... 😄

**Comment by blurymind** [comment]
Ok now I see that the request is to also be able to add comments between conditions/actions - not just between events

**Comment by zatsme** [comment]
Yes, as I noted above, excel does just that. But if I'm the only one who thinks it's useful then it's not worth doing 😔

**Comment by blurymind** [comment]
This would be a cool feature to have, but I personally feel that there are more important usability features that the event sheet can do with right now.
For example we still cant drag and drop multiple selected actions/conditions

**Comment by zatsme** [comment]
Closing...
