### ISSUE TITLE
Project Comments window - to use comments as bookmarks

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#760]
## Description
GD's newIde has no way of bookmarking parts of the event sheet to go back to and work on. Very often when implementing things in a game, parts of code/features are left in a WIP state and is useful to put a little todo comment on them. We can already put a comment, but we still have to scroll through different event sheets to discover them. It would be very useful if we could see all comments in one place and navigate to their event sheet + location by clicking on their item in the list

## Solution suggested
It would be cool to have a list of all comments of the project in one place- so we can use comments as TODO bookmarks to get to parts of the event sheet or multiple event sheets. Basically a window that shows a list of all comments in all event sheets. Clicking on a comment in it navigates to the comment's event sheet and scrolls to and selects the comment in the event sheet. This will really help in projects where multiple people are working on or even just for keeping track of what needs to be worked on in a project

**Comment by 4ian** [comment]
Can you add this as a labelled card in the roadmap, in the IDE column? Thanks :)

**Comment by blurymind** [comment]
trello entry here
https://trello.com/c/g9yJfixI/194-comments-list-window-to-use-comments-as-todo-bookmarks

closing this

**Comment by 4ian** [comment]
Thanks :)
