### ISSUE TITLE
Memory corruption in JavaScript event objects variable

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#766]
## Describe the bug
For unknown reasons I have Chinese letters in the object field of a JavaScript event.
Even overwriting them doesn't make them go away.
![strange_characters_jsevent](https://user-images.githubusercontent.com/7413059/48969207-d1c55380-effb-11e8-8f20-65c8c08b025d.gif)
Here is the strange thing. If I open my project.json in a text editor, replace the Chinese text and save it, the Chinese letters still show up in GD5 when I open up the project again. But when I search for it in the text again after saving the proejct in GD5 the letters are still gone.
![chinese_characters_projectjson](https://user-images.githubusercontent.com/7413059/48969252-9b3c0880-effc-11e8-9b3e-5ce3c9e5cc01.png)

I have no idea how this happened and I cannot reproduce it in other projects but somehow it is now tied to my Sakawochi project and appears even on another PC

**Comment by 4ian** [comment]
The patient will survive for sure, but still make backup of your json file from time to time ;)
I can't seem to reproduce it now, that's strange...

**Comment by 4ian** [comment]
No in fact I found the issue ;)

**Comment by 4ian** [comment]
Fixed in aa16e90aac5d0f58e73074e7dd2db283e9cb4dbf (reason was an improper binding between what was declared in GDevelop.js bindings (reference) and what was returned in C++ (object by value)).

For now, try to modify as little as possible this parameter and always save before.

**Comment by Wend1go** [comment]
Thanks :)
What do you mean with "try to modify as little as possible this parameter"?
Should I not modify the objects variable of the JS event until the next update of GD5 is out?

**Comment by 4ian** [comment]
> Should I not modify the objects variable of the JS event until the next update of GD5 is out?

Yes basically. 
If you want to modify them, save before and after the change is made. If unwanted characters appear, close GD and open it again to be sure to start from a clean state.
