### ISSUE TITLE
GDevelop 5 won't start on Fedora 29

### ISSUE THREAD

**Issue by zgolus** [4ian/GDevelop#769]
## Describe the bug
GDevelop 5 won't start on Fedora 29

## To Reproduce
1. Download and extract Linux version (gdevelop-5.0.0-beta55)
2. Try to run gdevelop binary
3. See error: [1]    3091 segmentation fault (core dumped)  ./gdevelop

**Comment by Wend1go** [comment]
I tried it in a VM, GD seems to be looking for libXss.so.1 which it can't find.
`sudo dnf install libXScrnSaver` solved the issue for me.

@4ian How about favouring the [AppImage](https://trello.com/c/ySX0iU8t/172-package-gdevelop-5-as-an-appimage-for-linux) for Linux distribution? npm/yarn should be able to create AppImages automatically.

**Comment by 4ian** [comment]
We can give a try to AppImage. Build for Linux could be done with this, you should be able to try with `yarn build` and passing the right parameters to electron builder

**Comment by probonopd** [comment]
As long as it can be built on, say, Ubuntu 14.04 (the oldest currently still-supported distribution), it should be easy to make an AppImage. Let me know if you need some help.

**Comment by zgolus** [comment]
Thank you for having a look into the issue. However libXss.so.1 was present in present in my system and the error still occurs. What fixed the issue was the newest build - gdevelop-5.0.0-beta57. So I can still reproduce the error with build 55, but 57 runs without problems.
