### ISSUE TITLE
24 hours have passed and the counter still has not reset!

### ISSUE THREAD

**Issue by Shineonline** [4ian/GDevelop#784]
24 hours have passed and still no reset, i am not happy about this.
![image 2018-12-02 at 5 31 16 pm](https://user-images.githubusercontent.com/43916207/49342849-97306c00-f636-11e8-8643-e3eff109aefe.png)

**Comment by 4ian** [comment]
You get a new build everytime you pass 24 hours after a build.
Example: if you made build 1 at 1pm and build 2 at 5pm, you have to wait 1pm the day after to get 1 build and 5pm to get the other build back.

To inspect your builds, click on "See all my builds".

**Comment by Shineonline** [comment]
Close this, the counter already reset
