### ISSUE TITLE
Android export with Phonegap

### ISSUE THREAD

**Issue by FerrLui** [4ian/GDevelop#788]
Something is wrong.  i Have this error on PhoneGap site
Error - An icon or splashcreen specified in your config.xml could not be found. Make sure all images specified in your config.xml exist in your app package

**Comment by blurymind** [comment]
When no icon is specified, it could use gdevelop's instead?

**Comment by 4ian** [comment]
Ideally yes. It's was a bit more complicated to do because it required changes to the export and an extra dependency toward these pre-generated icon so I ditched that for now and added a warning telling to add icons.

**Comment by 4ian** [comment]
I'll close this as there is no bug, and the warning message is added for next version

**Comment by 4ian** [comment]
(I was mistaken about the warning message, there will be a default icon which is the one of Cordova - a kind of robot head :) GDevelop icon would be ideal but would be more work.)
