### ISSUE TITLE
Piskel Editor has no close option 5.0.0-beta58

### ISSUE THREAD

**Issue by Baylissimo** [4ian/GDevelop#792]
## Describe the bug
In the latest release of GDevelop (5.0.0-beta58) on MacOS there is no option to close the Piskel editor. On Windows you can go through Piskel options and save then close the window, but there is no way to close the editor on MacOS.

**Comment by 4ian** [comment]
There are Save and Cancel button on the top right, right?

![image](https://user-images.githubusercontent.com/1280130/49793641-9e8a0080-fd2d-11e8-805a-ad7fc2d833ab.png)

**Comment by Baylissimo** [comment]
I've updated both on my Mac and PC and those buttons aren't appearing any
more.

**Comment by 4ian** [comment]
Can you poste a screenshot for me to see the interface?

**Comment by 4ian** [comment]
Was able to reproduce, it's happening indeed but not during development. Will take a look. For now, better downgrade to the previous beta.

**Comment by 4ian** [comment]
Yes you can entirely remove the current app and install with the previous installer.

**Comment by Baylissimo** [comment]
Cheers

**Comment by blurymind** [comment]
Sorry I missed this. I don't have a way to test on Mac

**Comment by 4ian** [comment]
@blurymind The issue is not specific to Mac, the buttons and the folder/filename are not showing at all after building GDevelop it seems

**Comment by Baylissimo** [comment]
1 minute ago
Details
I can't see the buttons on the PC either.

But I can close the window.

**Comment by blurymind** [comment]
Ok, I will try to fix it later today. Apologies for the inconvenience

**Comment by blurymind** [comment]
@4ian I reverted it to the old initialization approach. Will test tonight and submit a fix 👍 

Sorry again for the inconvenience

**Comment by blurymind** [comment]
@4ian it looks like the electron version of the build refuses to execute setInterval. I am currently trying to find a workaround

**Comment by 4ian** [comment]
Is setInterval not launched at all? If so, could we use setTimeout to emulate it? (you set a timeout, then in the timeout function, if pskl is still null, you set a new timeout for the same function)

**Comment by blurymind** [comment]
@4ian I figured it out, then slapped myself on the forehead.
It's in the html index file - the way I load the module is not using your new method- gdide.

**Comment by blurymind** [comment]
@4ian pull here:
https://github.com/4ian/GDevelop/pull/795
I made the init procedure of piskel more similar to the one that jfxr uses

Sorry it took me ages- rebuilding and testing is really slow when a bug it only in builds

**Comment by 4ian** [comment]
Good catch - I totally missed that during the review

**Comment by 4ian** [comment]
Published beta59 with the fix! Thanks for your quick fix! Appreciate it :)

**Comment by Baylissimo** [comment]
You guys are awesome. Thanks again for Gdevelop.

**Comment by blurymind** [comment]
Can you guys test and confirm the fix works for you as well?

**Comment by Baylissimo** [comment]
Works on both Mac and PC for me.
And the layers and locate buttons work well too.

Cheers

**Comment by blurymind** [comment]
Glad to hear that! Thank you for submitting the bug report. Really happy that we caught it early after release
