### ISSUE TITLE
No image in the Piskel editor

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [4ian/GDevelop#796]
When i try to edit a sprite with piskel, nothing appear in the edit windows of Piskel.

![issue-piskel gif](https://user-images.githubusercontent.com/19731340/49832714-b8602d80-fd97-11e8-928f-ca3135c60604.gif)

**Comment by 4ian** [comment]
You're on beta59?

**Comment by blurymind** [comment]
I just fixed this in beta59. Please download the latest release and confirm if you still have the issue

**Comment by Jacques-Olivier-Farcy** [comment]
You're right, it works fine with beta59 thanks.

**Comment by 4ian** [comment]
Great, thanks for confirming and thanks blurymind for the follow up :)
