### ISSUE TITLE
Do not have INSTANT / PERMANENT option 

### ISSUE THREAD

**Issue by homarox** [4ian/GDevelop#799]
## Describe the bug
Do not have INSTANT / PERMANENT option in force movement <linux and window version>

## To Reproduce
1. Add ACTION
2. Click on MOVEMENT option
3. Select ADD A FORCE

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Window, Linux version
* gdevelop-5.0.0-beta57

**Comment by 4ian** [comment]
This is in beta 59 :) I forgot to update the website download links - this is fixed now.

GDevelop will automatically download the update if you restart, or you can download it from the website.

Thanks for reporting this and following the error template :)
