### ISSUE TITLE
Android version is not being set

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#804]
## Describe the bug
The project version is not being passed to the config.xml file, it's fixed to "1.0.0".

## To Reproduce
1. Create a new project
2. Set a custom version in the project settings
3. Export to cordova locally
4. Open the "config.xml" file, the version will be "1.0.0"

## Other details
* Reported here: http://forum.compilgames.net/viewtopic.php?p=69486

**Comment by 4ian** [comment]
Not sure how I did not catch this before oO Fixed in f29cc503bfcc3f26214191da09d5b3b7ae6fffb7 :)
