### ISSUE TITLE
Platforme Ceaseless aerial fall and Invisible platform

### ISSUE THREAD

**Issue by gogdu** [4ian/GDevelop#805]
## Describe the bug
1 .If an object with the 'Platform' attribute uses a custom hitbox, the 'Platformer character' will not land and will continue to fall into place

2. The platform object that is deleted when it collides with an attack object seems to disappear at first, but if you destroy the platform by creating an attack object for several, some of them can not move as if there is an invisible wall

## To Reproduce
1) 
![h1](https://user-images.githubusercontent.com/45917152/50055021-91856b00-018c-11e9-8502-cd33904c21cc.png)
Using the default hitbox

![h1-1](https://user-images.githubusercontent.com/45917152/50055025-acf07600-018c-11e9-851c-e566bd2a548a.gif)
There seems to be no problem like this.

![h2](https://user-images.githubusercontent.com/45917152/50055032-be398280-018c-11e9-8142-48cf6b1c2062.png)
But if you use a custom hitbox

![h2-1](https://user-images.githubusercontent.com/45917152/50055042-ce516200-018c-11e9-81cd-f40fe93a481b.gif)
You'll see a character trying to land on the bottom of the floor.

Probably because of the character's origin, but when you used the floor object's default hitbox, you did not see that problem.

![h3](https://user-images.githubusercontent.com/45917152/50055061-02c51e00-018d-11e9-87c9-275784f8897f.png)
Maybe the hitbox is bigger than the character's landing point, so I reduced the hitbox to that.

![h3-1](https://user-images.githubusercontent.com/45917152/50055079-2be5ae80-018d-11e9-85b0-c03a62b009d9.gif)
But it is the same.

It is a very short time, but when you land on the hit box set on the floor object, the character will jump to the top of the floor object sprite

Again, the problem with the character's origin is that the same problem should be encountered when using the default hitbox

I solved it temporarily by creating a separate player hitbox object as shown in the example

2)
![invisivle](https://user-images.githubusercontent.com/45917152/50055121-b62e1280-018d-11e9-85fe-2436c1a28507.gif)
I took the same phenomenon described above

I have removed an object with the 'Platform' setting but there is an invisible platform

Even that object is a character that gets stuck even when using the default hitbox

When gif capturing, the character also created a separate object for the heatbox

I think this is probably a minor problem for both the platform player and the platform.

I am neither a professional programmer nor an English speaker.

So I can not explain this phenomenon in detail

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.

## Other details
* Include any OS/browser version/smartphone that you're using
* Add any other context about the problem here.

**Comment by 4ian** [comment]
Hey, the game you did looks really nice :) 

So a few things:

* When dealing with hitboxes, I highly recommend staying as much as possible with the default hitbox, or at least **an hitbox that is exactly the same for all sprites**.
* I also recommend to use the **exact same sprite size** for all sprites, to avoid these issues of the player being "resized" during the game, making it fall/be in the air again.

The platformer engine should handle changes in size, but only for default hitboxes. An improvement would be to handle change in the hitboxes too, but it's more complex/performance sensitive so for now stick with same size sprites as much as possible (in particular, all sprites should have same height) and same hitboxes.

> I have removed an object with the 'Platform' setting but there is an invisible platform

For this issue, can you check in the instances list if there is not an extra object that is hidden somewhere? Something on another layer?
If you think it's a bug, copy your game in another folder, remove everything from the game that is not related to the bug, then send me this minimal game so I can see if it's a bug.

Thanks and good luck with the game :)

**Comment by MungMoongYi** [comment]
I used free assets because it was an exercise project.

1) Is it possible that the size of the sprite can affect the sprite origin or the hit box as you say?
I do not understand about improvement.
As you say, it would be better to make the material in the form of a sprite sheet.
It was nice to have the player create an object for the hitbox, but the same instance monster was thinking about how to create the hitbox object

2)I did both
![a1](https://user-images.githubusercontent.com/45917152/50083741-02359180-0238-11e9-9628-2c32d93b93ac.png)
[프로젝트들 - 복사본.zip](https://github.com/4ian/GDevelop/files/2685736/-.zip)
I'm new to github, so I do not know how to attach files like this

**Comment by zatsme** [comment]
The problem seems to happen because the origin points are different, setting both anim origin points to 0 and using same for all anims fixes this issue.  It's an odd problem though and probably need @4ian to investigate further, but for now this seems to work.

![platformissue](https://user-images.githubusercontent.com/17770123/51708945-12057a00-201d-11e9-882e-f8e79b70edaa.gif)

**Comment by MungMoongYi** [comment]
> The problem seems to happen because the origin points are different, setting both anim origin points to 0 and using same for all anims fixes this issue. It's an odd problem though and probably need @4ian to investigate further, but for now this seems to work.
> 
> ![platformissue](https://user-images.githubusercontent.com/17770123/51708945-12057a00-201d-11e9-882e-f8e79b70edaa.gif)

Oh, I remember I deleted the object.
You mean, I just replaced the sprite.
And that's because the origin of the animation is different.

**Comment by Silver-Streak** [comment]
I'm going through older issues to clean them out or bring attention back to them. 

This appear to have been an issue with sprite sizes + custom origins + custom hitboxes that are different per frame.

We have numerous examples with custom hitbox platforms now and they function normally, so I'm going to close this out.

@gogdu if you're still having this issue, please feel free to reopen this issue.
