### ISSUE TITLE
newIde 1.0 is a bad default value for frame duration, also duration should be set in the animation previewer

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#809]
## Describe the issue
Right now in the newIDE when you create a new animation, the default value for frames duration is 1.0
This results in an extremely slow default playback, which almost always the user will need to change to something like 0.02- 0.05

I suggest to change this value to 0.05 or something that is more likely to be used by default. 
Having a better default should help make workflow smoother - taking one step less to set up each animation in most cases

The other thing is that when you want to set the playback speed, you also need to be able to preview it. It would make much more sense if the user is able to set it in the preview animation window.  So another suggestion is to add that to the animation player :)  I will make a pull on that part tonight.

Just the thoughts of an ex-animator here

**Comment by blurymind** [comment]
I am assuming that the default is actually set here:
https://github.com/4ian/GDevelop/blob/15773bca85cb6892a466b1d3f30477fd27ec6a5b/Core/GDCore/Extensions/Builtin/SpriteExtension/Direction.cpp#L18
but I am not completely sure

**Comment by Lizard-13** [comment]
I think so, do you know what that means?, yes, recompile libGD.js >:)

**Comment by blurymind** [comment]
hehe yes. Come to think of it, the default value should be even lower!

0.05 or below

**Comment by blurymind** [comment]
I've started adding an input field to change the time in the preview dialog - it's much more intuitive now- but need to sort out its css

**Comment by blurymind** [comment]
Pull coming tonight :)
![gd-setframerateinpreview](https://user-images.githubusercontent.com/6495061/50088625-6b4ae400-01fb-11e9-9553-7d18d3ec8d89.gif)
I also made the input field lest wasteful vertically

**Comment by Lizard-13** [comment]
Wonderful!

**Comment by blurymind** [comment]
ok this can be closed now :)
@4ian thank you for changing the default value as well as reviewing the changes
