### ISSUE TITLE
"foobar" + "bar" string expression cause compilation failure

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GDevelop#81]
"foobar" + "bar" string expression cause compilation failure : 

```
invalid operands of types 'const char[6]' and 'const char[3]' to binary operator 'operator+'
```

**Comment by 4ian** [comment]
Yup, in fact the parser of strings and mathematicals expressions would need a complete rewrite (it was written in a quite hacky way) using the same pattern at the one used for VariableParser (it is an "LL(1) parser", see http://en.wikipedia.org/wiki/LL_parser).

Not sure when I'll do it but it is definitely something to do!

**Comment by victorlevasseur** [comment]
In the meantime, why not convert GDevelop strings literals to std::string("...") instead of just "..." to avoid this bug ? (Can it cause performance issues ?)

**Comment by 4ian** [comment]
Mmmm can't remember why this is not already done, maybe for performance issues but not sure. This should be tested!

**Comment by arthuro555** [comment]
@4ian maybe consider closing this as this is dead and GDevelop 4 is not supported anymore

**Comment by 4ian** [comment]
Yes sounds fair!
