### ISSUE TITLE
Deleting Objects

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#816]
## Describe the bug
When deleting objects and are warned about deleting related events, the object and events are removed even if you click "cancel".
![clickok](https://user-images.githubusercontent.com/45985516/50196911-11d5d880-0313-11e9-81bd-1530f76b52da.png)
![cancel](https://user-images.githubusercontent.com/45985516/50196785-88bea180-0312-11e9-82f8-d3450af0c7f4.png)

Please double check that the bug is not already reported in the issues list.

## To Reproduce

1. Go to 'Object' 
_Preferably one with some events, also imagine them being more complex and that you're a GD noob..._
2. Click on 'Delete'
3. Click on 'OK' for the first dialog "are you sure you want to remove this object?"
4. Click on 'Cancel' for the second dialog pertaining to events & conditions
5. Object and events are still removed

* Please include a link to a game if possible! 

No link, sorry. It is happening within the program anyway, not the game itself.

* If applicable, add screenshots to help explain your problem. 

Captures of dialogs have been provided

## Other details

* Include any OS/browser version/smartphone that you're using

Windows 8.1 laptop. Browser N/A

* Add any other context about the problem here.

Sometimes I only need to delete and replace a particular object, but not all of the events/conditions. 

If the object I'm going to add is of a different type (i.e., if I used an animated sprite and want to swap it for a tiled sprite) the animated sprite can be deleted, but events may still be useful for the new tiled sprite if they are left intact. This is why I think it should be an option to delete events along with the objects, not done anyway even if you click "cancel" on that second warning dialog.

**Comment by Bouh** [comment]
Problem here ?
https://github.com/4ian/GDevelop/blob/ff496c65a5ac9cef2da65b03f53a0ca22a88bb2e/newIDE/app/src/SceneEditor/index.js#L606
This is missing i guess :   `if (!answer) return;`

**Comment by 4ian** [comment]
In theory this should be fine because answer is passed to ObjectRemovedInLayout or GlobalObjectRemoved (see https://github.com/4ian/GDevelop/blob/b3b7f181fa990348226971a05e44243ab1b65836/Core/GDCore/IDE/WholeProjectRefactorer.h) as the last parameter, which is called "removeEventsAndGroups" and that should remove events and groups only if it's true.

**Comment by Lizard-13** [comment]
It seems that events are removed even on Cancel, I haven't tested it, though.

**Comment by zatsme** [comment]
Can you not have one dialog with a checkbox for event removal?   Yes and No should be the responses for the second dialog, and would also make sense on the first one also 🤔

**Comment by Phenomena3** [comment]
> It seems that events are removed even on Cancel, I haven't tested it, though.

That's right.

Wish I could record a video for longer than 15 seconds...

**Comment by PascalLadalle** [comment]
(bump)
I was about to post a bug report asking to replace the second OK/Cancel by a Yes/No.
![image](https://user-images.githubusercontent.com/25978830/60551772-ac848a80-9d2c-11e9-82cb-a0de439392ed.png)

**Comment by keshavg2** [comment]
I think It is working fine in Ubuntu 18.04.
