### ISSUE TITLE
Add the ability to debug/output a string to the console

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#836]
## Description

With the limited function of the debugger you have to resort to using the developer tools window to do in-depth debugging of your code.  This is not ideal, especially for beginners who will almost definitely not have a clue how to use the developer tools.

## Solution suggested

Provide a DEBUG to console action so we can output useful debugging information especially in loops where using a text on screen or the current debugger is almost useless.

## Alternatives considered

In the long term hopefully the debugger can be much more useful but until then I can't think of a better way to bridge the gap 😄

**Comment by 4ian** [comment]
I agree it would be useful. Added a card for this on the roadmap: https://trello.com/c/ZKdhR1Lb/227-add-action-to-print-output-a-debug-string-in-the-debugger

Technically, this would need to:
* Add a new command "printString" in the debugger client in the game engine: https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/websocket-debugger-client/websocket-debugger-client.js
* Handle it here: https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/Debugger/index.js#L178 and store it somewhere
* Display it in the DebuggerContent component.
* Create a Js Extension with one action.
* Have the action call `printString` (using `_debuggerClient` which is in `gdjs.RuntimeGame`, accessible from the `runtimeScene`).

**Comment by 4ian** [comment]
Closing as there is a card for it on the roadmap. Anyone wanting to try to implement this is welcome to do so :)
