### ISSUE TITLE
Middle mouse button was released or is down : not working conditions

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#838]
## Describe the bug
The conditions **mouse button was released** and "mouse button is down" with button _Middle_ are not  working.

## To Reproduce
Try to trigger something with conditions **mouse button was released** and "mouse button is down"

## Other details
Desktop games(ofc), windows 10, GD 5beta61.

**Comment by KinkGD** [comment]
I suppose this issue can be closed @4ian ?

Also, i notice a non optimal behavior with mouse clicks in general (not middle button only) (left/right/midddle clicks are impacted) in previews of the games : If the mouse cursor touchs the window border, it always trigger the 3 kinds of clicks.. i think you know about this "issue", i'll open a new issue on it.

**Comment by 4ian** [comment]
> : If the mouse cursor touchs the window border, it always trigger the 3 kinds of clicks.. i think you know about this "issue", i'll open a new issue on it.

Are you sure? That should instead trigger the release of all the buttons. Can you confirm this?

**Comment by 4ian** [comment]
Closing this issue, we'll open a new one if there is another bug
