### ISSUE TITLE
Glitch when rendering Shape Painter line with thickness of 1px

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#844]
## Describe the bug
When using the Shape Painter object to draw lines via an event, the lines render with varying thickness, despite the setting to draw them all at 1px wide. When resizing the game window, the line thickness changes (a line which was 1px changes to 2px, and vice versa), and some lines disappear altogether:

![Line thickness issue](http://forum.compilgames.net/download/file.php?id=4192)

This was originally mentioned in the GDevelop forum: http://forum.compilgames.net/viewtopic.php?f=19&t=11094

## To Reproduce
See this demo: [game.json.zip](https://github.com/4ian/GDevelop/files/2728138/game.json.zip)

**Comment by Lizard-13** [comment]
Note that GD is drawing rectangles for vertical lines, hence the extra thickness. And drawing polygons for the rest of the lines, maybe we can use `PIXI.Graphics.lineTo` instead?

**Comment by 4ian** [comment]
This might improve in next version thanks to this fix: https://github.com/4ian/GDevelop/commit/2558052a61378fa4edfc9ad53c75d51984eac7e9

**Comment by BWPanda** [comment]
> This might improve in next version...

Nope, opening the above example in that latest version (beta64) still shows the issue.

**Comment by Bouh** [comment]
I have added a month ago an actionon Shape painter for Line instead a Rectangle for draw a line.
This new action is by default since months now.
This issue is solved :)
