### ISSUE TITLE
Popup windows missing button and freeze system

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#856]
## Describe the bug
When I create an object with a hyphen (-) in the name and press Apply, I get a popup window stating that the name contains forbidden characters. That's fine and all, but it freezes my whole system. I can't close the popup window, can't close GDevelop, can't even open any other window (I had to login to a terminal session using Ctrl-Alt-F1 and kill the GDevelop process to 'fix' it).

## To Reproduce
1. Create a new, empty project, add a scene and open it
2. Add a new Sprite object
3. Enter '-1' after 'NewObject' in the Object Name
4. Click Apply
5. Note the popup window and the inability to do anything else now

![screenshot from 2019-01-08 22-21-53](https://user-images.githubusercontent.com/2385329/50856998-f64f7200-1394-11e9-9057-c6bbbae050c4.jpg)

## Other details
I'm running GDevelop v5.0.0-beta61 on Linux Mint 19 Cinnamon (can provide further details as necessary).

**Comment by blurymind** [comment]
Wouldn't it be better if the input field simply didn't allow for such
characters to be entered in the first place? I already do that on the path
editor via a simple regular expression

**Comment by 4ian** [comment]
It's a good idea, could be a better user experience

**Comment by BWPanda** [comment]
Yes, there seems to be at least two issues: missing button and freezing (interested to see if others can reproduce either one).

As for not allowing certain characters in the first place, I disagree. I think someone who types object names one way but has them appear a different way would be more confused. I like the notification as it explains what I need to change (so then I can think about and plan better my object names). Just need the notification working properly :-)

**Comment by zatsme** [comment]
You're both right, check the name and provide a red text like the expression parser to signify the error and grey out the apply button until illegal chars removed, no need for a popup, I guess modal window?

**Comment by Wend1go** [comment]
Just tested and I can confirm that it also happens on Linux Mint 18.3 Cinnamon edition.
In the frozen state GD seems to grab all mouse clicks, independent from the application you click on. Moving the pointer and typing on the keyboard still works.
You can actually close the confirmation box and continue working by hitting ESC.
I wonder if this is just a problem with displaying the Ok button. Hitting TAB and ENTER didn't work. But I don't know if this behaviour is even implemented.
Is the dialog a standard one in React or can it be manually customized?
When run from the terminal it displays this message at the moment I hit "Apply":
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
The message only appears when I add a "-" to the name. When I hit "Apply" with a valid name the message is not shown.

**Comment by BWPanda** [comment]
> You can actually close the confirmation box and continue working by hitting ESC.

Didn't try that... :grinning:

**Comment by blurymind** [comment]
I personally have never been a fan of pop ups. They just break the flow.

My suggestion is to make the input field reject any illegal characters. The name you see entered in it will always be the same as the name the game engine gets

**Comment by BWPanda** [comment]
This just happened to me again, but this time with the "Another animation with this name already exists. Please use another name." popup. Thanks to @Wend1go I just pressed ESC to keep working without closing everything. But shows that this issue isn't just limited to illegal characters...

**Comment by 4ian** [comment]
I've made a fix for next version (https://github.com/4ian/GDevelop/commit/37c3a6d38abbcf4a1af83de20664be9069446033) - hope it works :)

**Comment by BWPanda** [comment]
This is still an issue in beta64 - the dialog box now has an OK button, but it still freezes and requires pressing Esc to close.

**Comment by 4ian** [comment]
Well in this case I'm not sure what is happening, I properly specified to have a OK button, seems that it's working on macOS and Windows - seems to be a bug of the window manager :/ Maybe updating Electron will fix this.

**Comment by Bouh** [comment]
Close with commit https://github.com/4ian/GDevelop/commit/37c3a6d38abbcf4a1af83de20664be9069446033
And the multiple updates of Electron package.

**Comment by BWPanda** [comment]
This is still happening for me in v5.0.138:

![Peek 2022-07-14 15-38](https://user-images.githubusercontent.com/2385329/178907891-aabc20a6-4c9c-4029-b6c6-b8d344b01eb8.gif)
