### ISSUE TITLE
New rope example for Physics2

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#862]
Hi!
  
 New example of my rope demo taking advantage of the new physics functions in physics 2, including breaking a joint and a polygon shape.  New GFX to make it look nice (I hope 🤔 lol)

[Rope Example.zip](https://github.com/4ian/GDevelop/files/2747224/Rope.Example.zip)
  
 I confirm that any assets can be used freely by anybody, including for commercial usage.
 
I used filterforge to create the wood, and finished the editing in embedded Piskel 😄

**Comment by 4ian** [comment]
Looks nice 😄 Will replace the old demo with this one 👍
Good job!!

**Comment by 4ian** [comment]
Replaced the example with this new version, thanks a lot 👍
