### ISSUE TITLE
New Physics2 example - Ragdoll

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#866]
Hi!
  
New Physics2 example - Ragdoll.  Hope you like it 😆 

[RagDoll.zip](https://github.com/4ian/GDevelop/files/2751880/RagDoll.zip)

Edit: Added touch/mobile controls.  Will make them work better later today :)

**Comment by 4ian** [comment]
Adding it :) I've tweaked a bit the particles and set the text to 
```
Click/touch to add a force toward the cursor/touch.
Press c to Reset scene
Press g mode "Special mode 15+"
```

**Comment by zatsme** [comment]
Whatever works for you :)

**Comment by 4ian** [comment]
Nice job, it's fun ;)

**Comment by 4ian** [comment]
Closing as it's added for next version! 👍
