### ISSUE TITLE
'Instances' tab/window doesn't show last item

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#877]
## Describe the bug
When the list of item in the 'Instances' tab/window is longer than the window height, the last item gets cut off and it's not possible to see it by scrolling down.

## To Reproduce
1. Create a project, add a scene and create a sprite
2. Add the sprite a few times to the scene (e.g. 4)
3. Open the Instances tab/window and note the 4 sprite instances listed
4. Resize the GDevelop window so that the Instances tab gets a scrollbar and you can only see, say, two items
5. Scroll down and note that you can only see 3 instances (the last one is cut off)

![peek 2019-01-15 20-36](https://user-images.githubusercontent.com/2385329/51201844-d294aa80-1905-11e9-8369-e706d882cbc0.gif)

**Comment by Bouh** [comment]
Close it works fine.
Test with beta 103

![to_delete](https://user-images.githubusercontent.com/1670670/104966079-5ba4b780-59e0-11eb-9a0e-377d745119db.gif)
