### ISSUE TITLE
Project manager : All can be have the same name

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#881]
## Describe the bug
In the project manager there can be several scenes with the same name, it's same for external events, external layouts and functions/extentions.

I create two scenes, scene_one and scene_two, i rename scene_two by scene_one, and now we can't open the second scene. 
And more painful, we can't rename the scenes with the same name.
Even after reboot the soft.

Nothing is erase in the .json but maybe we need alert user when he give twice the same name.

In the Functions list inside the functions/extentions an alert exit already
## Other details
* Win10 64bits, GD61 and 62

**Comment by Bouh** [comment]
This issue can be closed, it good for me

**Comment by 4ian** [comment]
Thanks for fixing it ;)
