### ISSUE TITLE
Allow setting sprite animation by name in Properties panel

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#883]
When you click on a sprite in the scene, the Properties panel displays from which you can set the animation of the sprite. You need to enter the number of the animation currently, but I'd love to see the ability to enter either the number or the name of the animation. I figure you can just test whether the entered value is a number or a string and then load the appropriate animation that way (i.e. use the one field for both numbers and strings)...

**Comment by 4ian** [comment]
Thanks for the clearly written title. I've added it to the roadmap cards: https://trello.com/c/90Nqdw06/234-allow-setting-sprite-animation-by-name-in-properties-panel

I'll close the issue here (even if discussion can continue) as the idea is to have every new feature request on the roadmap :)
