### ISSUE TITLE
Screen shake example based on platformer code.

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#891]
There was a few requests on Discord so I though a small example would help,
  
[Screen Shake.zip](https://github.com/4ian/GDevelop/files/2775883/Screen.Shake.zip)
  
 I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by blurymind** [comment]
Nice..

It would be awesome if gdevelop  has an example that covers all of the elements noted in this talk:
https://www.youtube.com/watch?v=AJdEqssNZ-U

These are small things but they really add up to the game 'feel'

**Comment by MercurioC** [comment]
Really useful! Thanks for sharing 👍

**Comment by zatsme** [comment]
Added to examples, so closing 👍
