### ISSUE TITLE
Sprite/Text objects : color picker is half out of the screen

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#896]
## Describe the bug
When changing the color of a sprite or text objects, the color picker panel is not totally displayed, a part is outside screen/window border.

![image](https://user-images.githubusercontent.com/8144048/51445180-8d57ea80-1d02-11e9-8384-3ef53a16bf84.png)

## To Reproduce
Use the actions to change the color of a text object, or the global color of a sprite, and try to pick a color.

## Other details
Windows 10, GD5 b62
Screen resolution : 1920x1080 (+ second screen same resolution)
Using GD5 with maximized windows or fullscreen

**Comment by zatsme** [comment]
Same, and changing window size seems to make no difference.

**Comment by Bouh** [comment]
Close with PR https://github.com/4ian/GDevelop/pull/917
Tested with beta 103.

The color picker have a scollbar if needed.
![image](https://user-images.githubusercontent.com/1670670/104965432-fe5c3680-59de-11eb-8b48-8a2bbf1491ae.png)
