### ISSUE TITLE
Platform Character cannot more left and right on a platform going up.

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#897]
I've been working on a new advanced platformer example with new animations and state machine with lots of comments which I hope to finish and then make into a full tutorial 😄 

Unfortunately I found a bug which I don't think has been mentioned before....

In this GIF you see the platform going down and character moving left/right no problem..  Going up however and the player cannot go left/right.. Sometimes a jump then allows the left/right movement, but usually not.

![platform bug](https://user-images.githubusercontent.com/17770123/51497646-a4a6de80-1dbb-11e9-9e3d-21eb7b1b945d.gif)

Here is the small example...

[PlatformerBUG.zip](https://github.com/4ian/GDevelop/files/2780446/PlatformerBUG.zip)

**Comment by PascalLadalle** [comment]
Bumping this as I noticed a related issue: when the platform is moving up, GDev detects the platformer as falling. Maybe it explains the issue above.
![ezgif com-crop](https://user-images.githubusercontent.com/25978830/65256560-001e9d00-db00-11e9-94d0-30301f6efbfd.gif)
This fixes the animation issue: 
![image](https://user-images.githubusercontent.com/25978830/65256582-0a409b80-db00-11e9-8c08-610b8c1ae17a.png)

**Comment by PawBud** [comment]
A similar issue has been reported by `Kappa` a GDevelop user. He asked me to report this on behalf of him @4ian, as seen over here https://gofile.io/d/sic5IO. After discussing it on [Discord](https://discordapp.com/channels/258623956158906368/258623956158906368/740180306824265738), a solution could not be determined. The things that kappa tested:- 
1. Not moving the hero at all, just having them sit on the platform and move the platform up - Leads to jittery movement.
2. Moving the hero along with the platform - Leads to the jittery Movement.

The above-mentioned method worked in the previous release of GDevelop.

**Comment by D8H** [comment]
I guess this issue is solved by this PR
* https://github.com/4ian/GDevelop/pull/3009

**Comment by 4ian** [comment]
Yep! Finally! 🤩
