### ISSUE TITLE
Performance profiler : Crash and clicking "report the error on github" lead to an error "414 Request-URI Too Large"

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#900]
## Describe the bug
i'm using preview with performance profiler : sometimes, when stopping the profiler, i have a message that it has crashed, that the issue was automatically reported... But if i click the button "Report on github" to give more information about the crash, my browser opens a new tab but leads to this error : 

![image](https://user-images.githubusercontent.com/8144048/51566568-27e83300-1e95-11e9-83e2-7a601ec5d3cb.png)

Did you get any auto report from me or about this error ?

It's totally random when using the profiler (but it occures really often so i don't use profiler that much).
Note that the game is running pretty smoothly (strong 60fps, but it's doesn't stress a lot my CPU(Ryzen 1700x)), but it's annoying to work on optimization of the events.

This is a copy/paste of what is in the URL : 
`https://github.com/4ian/GDevelop/issues/new?body=%0A%3D%3E%20Please%20write%20here%20a%20short%20description%20of%20when%20the%20error%20occured%20and%20how%20to%20reproduce%20it.%0AYou%20also%20may%20have%20to%20create%20an%20account%20on%20GitHub%20before%20posting.%0A%0AWhen%20you%27re%20ready%2C%20click%20on%20%22Submit%20new%20issue%22.%20Don%27t%20change%20the%20rest%20of%20the%20message.%20Thanks!%0A%0A%23%23%20Error%20stack%20(don%27t%20write%20anything%20here)%0A%60%60%60%0ATypeError%3A%20n.time.toFixed%20is%20not%20a%20function%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555667)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A684035%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648384)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A117096)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1623040)%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555847)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A684035%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648384)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A117096)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1623040)%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555847)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A684035%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648384)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A117096)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1623040)%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555847)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A684035%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648384)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A117096)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1623040)%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555847)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A684035%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648384)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A117096)%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1623040)%0A%20%20%20%20at%20t.s._convertToDataRows%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555847)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A1555885%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Flocal-app.c161b4b5.chunk.js%3A1%3A648411%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A683905%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2FMoi%2FAppData%2FLocal%2FPrograms%2Fgdevelop%2Fresources%2Fapp.asar%2Fwww%2Fstatic%2Fjs%2Fmain.83769261.js%3A1%3A294344)%0A%60%60%60%0A%0A%23%23%20Component%20stack%20(don%27t%20write%20anything%20here)%0A%60%60%60%0A%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20s%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20DragSource(t)%0A%20%20%20%20in%20DropTarget(DragSource(t))%0A%20%20%20%20in%20n%0A%20%20%20%20in%20_%0A%20%20%20%20in%20div%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20g%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20a%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20s%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20y%0A%20%20%20%20in%20div%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20div%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20n%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20DragDropContext(t)%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%20%20%20%20in%20t%0A%60%60%60%0A%20%20%20%20%20%20%20%20&title=Crash%20while%20using%20an%20editor`

## Other details
Windows 10x64 GD5 b62
Firefox 64.0.2

**Comment by 4ian** [comment]
Still an issue of profiler that get too much data. Could you send me the game with the instructions to reproduce? Surely an object sending too much data

**Comment by KinkGD** [comment]
Sent to your gmail adress.

**Comment by 4ian** [comment]
Closing as this is fixed for next version (beta63)
