### ISSUE TITLE
Build service down?

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#902]
The build service might be down again. I can't check this currently since I'm not at home.
 [Error: unexpected end of file.](http://forum.compilgames.net/viewtopic.php?f=19&t=11176)

**Comment by 4ian** [comment]
I've double checked and I can successfully build a windows executable and also a macOS app. Both builds went without issues. Worker seems healthy when I look at the metrics and the latest logs don't show anything wrong.

**Comment by steveang9999** [comment]
I posted both in the forum, i will post it again here, the build failed screen shot and error log.

This is the log file : https://ufile.io/7nkrg
and 
This is the screenshot of the message saying failed to build: https://imgur.com/a/9JqFRvS

**Comment by 4ian** [comment]
@steveang9999 Can you try with another game, like an example game, to see if it's related to your game or not? If it seems to be working with another game, then send me your by email (see my GitHub profile page for me email) and I'll check what's wrong

**Comment by shinobirozs** [comment]
@4ian, I tried building a package for Android twice today (after the update) and it seems it can't build properly.  I can't download the logs as well. Thanks.

![image](https://user-images.githubusercontent.com/29979672/60069601-13f77480-9746-11e9-9eee-2124ce850fe2.png)

**Comment by shinobirozs** [comment]
@4ian, I tried to build my other projects and still hitting the same issue.

![image](https://user-images.githubusercontent.com/29979672/60069739-a4ce5000-9746-11e9-8a3e-82032aff243f.png)

Thanks in advance.

**Comment by 4ian** [comment]
I tried both the Platformer and Space Shooter example with beta 75 and both were successfully compiled. Can you click on See Logs and send here the content of the file?

**Comment by shinobirozs** [comment]
The button seems to be disabled and no logs downloaded upon clicking it.

**Comment by 4ian** [comment]
Can you retry and give me the exact hour you started the build (click on the Package for Android button)?

**Comment by shinobirozs** [comment]
Here it is

![image](https://user-images.githubusercontent.com/29979672/60086644-0d7cf300-976e-11e9-87de-5254925042c6.png)

I tried building on my other Macbook and it seems to be fine now. 

![image](https://user-images.githubusercontent.com/29979672/60086715-2d141b80-976e-11e9-9b52-cf5ef938d3d8.png)

I'll try to uninstall-install the application on the other Mac facing the issue.

**Comment by 4ian** [comment]
I've checked and the worker ran out of space for your two first builds. I've fixed the potential cause of this, should be better in the future :)

**Comment by shinobirozs** [comment]
I'm not encountering the issue anymore. Thank you.
