### ISSUE TITLE
New example: Endless runner up (platformer jump)

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#906]
Hi!
  
  I'd like to submit a new examp... blah blah blah :laughing: 
  Here is the example, one of these classic endless jumping up games, it can turn a bit unfair sometimes too!: 
[EndlessRunnerUp.zip](https://github.com/4ian/GDevelop/files/2797167/EndlessRunnerUp.zip)
![endlessrunnerup](https://user-images.githubusercontent.com/9782647/51762445-7fadb680-20ae-11e9-916f-a6e96f38d23f.png)

I can't develop a lot right now but get some time to do it, it even has a mini tutorial. You can tune the values if you want, also the background color. Also, I didn't resist, there is a "falln't" that you can change to the correct text using the previous animation number on the object

  Some of the assets are bundled with GD (player and platforms) and the others were made by myself so they can be used freely.
  

By the way, there's a small bug with the platformer behavior, instead jumping over a platform and then fall on it, sometimes the character suddenly stops on the platform. You can see the effect in the video on discord.

**Comment by Lizard-13** [comment]
I've seen some users asking how to put the things together, menus and everything. So I did it, platformer behavior, objects management, camera movement, layers handling, custom mechanics (spring jump and warping), customizable values and a mini tutorial, all working together but in an organized way, easy to read and update.

**Comment by zatsme** [comment]
Cool, was doing similar but will have a look at this later 😁

**Comment by 4ian** [comment]
Nice! Surely something that should be a starter game too in GDevelop, like the Downhill Bike demo. Would need nice and fancy graphics though.

Will check that later this week-end, good job!! Such tutorials/examples are very useful for the community and will help GD to grow.

**Comment by Lizard-13** [comment]
I can do new graphics, yes. Any style in mind?

**Comment by 4ian** [comment]
Nothing specific in mind, can be pixel-art or not... anything else that looks nice that you find or create :)

**Comment by zatsme** [comment]
Really nice to play, great example! 👍

**Comment by blurymind** [comment]
Very fun too. Thank you 😄 

here is a nice free sprite set
https://openpixelproject.itch.io/opp2017jungle

itch is full of them https://itch.io/game-assets

**Comment by Lizard-13** [comment]
Nice graphics indeed!

**Comment by 4ian** [comment]
Yep, nice graphics. What would be basically needed are a nice background (tiled sprite with some offset applied on the Y axis as we progress), as well as platforms, rocks and spring jump in the same style as the character :)

**Comment by 4ian** [comment]
A custom font too, and should be looking awesome ;)

**Comment by 4ian** [comment]
Added in latest version! With more consistent graphics and some background, this could be an awesome starter project. Great job!!

**Comment by Lizard-13** [comment]
Will upgrade the graphics asap :)

**Comment by blurymind** [comment]
this one has a good looking bike in it
https://moonstar2d.itch.io/free-paid-vehicle-car-sprites-
for the bike demo
![preview](https://user-images.githubusercontent.com/6495061/52654902-eb838200-2eea-11e9-84d0-167a9d742e2c.png)

**Comment by 4ian** [comment]
@blurymind Let's post in the right issue then ;)

**Comment by Lizard-13** [comment]
Sorry, closed this one by accident :P

> Let's post in the right issue then ;)

@4ian Are you sure it isn't related?
![1550003526755](https://user-images.githubusercontent.com/9782647/52752596-2e6c5500-2fd2-11e9-9ca9-449c86cc58d1.png)

Now, seriously, I've already switched all the graphics to the ones linked by @blurymind (from Open Pixel Project) like two weeks ago, but I want to make a nice rock rolling animation, would be a work doable in one hour or so, but don't have a lot of free time so I'm doing it slowly :)

**Comment by blurymind** [comment]
Hahaha that's fantastic xD I would play that game

**Comment by 4ian** [comment]
Hahahah! Would play it too ;)
More seriously, look forward to see the improved version 💪

Unrelated note, I've added a card about having a curated list of links to assets, or even an asset store: https://trello.com/c/DkzlD5MJ/252-add-a-list-of-links-to-assets-asset-store

**Comment by blurymind** [comment]
+1 for an asset store with option to sell assets or offer for free (similar
to itch)

**Comment by arthuro555** [comment]
It seems like this issue is dead. It should be closed.
