### ISSUE TITLE
Classic Invaders example

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#907]
I made this with my daughter ages ago and forgot about it, but might be useful as an example.

@4ian What do you think?

[Invaders.zip](https://github.com/4ian/GDevelop/files/2798234/Invaders.zip)

**Comment by 4ian** [comment]
Looks good, added on my todo list to add it as an example :)

**Comment by 4ian** [comment]
Added in latest version! Thanks again! :D
