### ISSUE TITLE
Sprite with PlatformObject behaviour does not collide correctly with a jump thru platform when it is low enough to run into it.

### ISSUE THREAD

**Issue by ghost** [4ian/GDevelop#909]
## Description
This bug relates to how the platform character interacts with a jump thru platform. If the platform is at the same height level as the character, instead of just running through it, he enters a jittery state as if the animations are triggering incorrectly. I'm using the same events and animations from the platform tutorial on the website.

## Steps to reproduce

1. Set up a scene as described in the tutorial, with the following events:

![screenshot 13](https://user-images.githubusercontent.com/23426634/51793491-3302d200-21b9-11e9-8511-c2338937ecca.png)

2. Make sure the Player has the PlatformerObject behaviour and the jump thru platforms have the Platform behaviour with the type set to Jump thru.

3. Place a platform at a height level so a player would run straight through it along the ground, as shown below with the platform to the left of the player:

![screenshot 14](https://user-images.githubusercontent.com/23426634/51793547-dfdd4f00-21b9-11e9-991f-0660882a931a.png)

The player should start flickering rapidly between what appears to be Idle and Jump when he collides with the platform.

## Other details
I am using GDevelop 5.0.0-beta62 based on GDevelop.js 4.0.97-0-release.
I am using Windows 10 Home version 1803 build 17134.523.

**Comment by rexbyte** [comment]
Thanks for your quick response.

I added the once condition to jumping and falling, as you suggested:

![platformer](https://user-images.githubusercontent.com/23426634/51795419-1c6d7280-21db-11e9-8e43-3c49cc2236eb.png)

However, this not appear to have fixed the problem. As shown below:

![platformer](https://user-images.githubusercontent.com/23426634/51795453-9ef63200-21db-11e9-810e-5c3fdf5a7912.gif)

**Comment by zatsme** [comment]
This doesn't happen for me, are you using custom hitboxes?  If you can zip your game folder and attach here I'll see if I can work out hats wrong for you 😄

**Comment by rexbyte** [comment]
I don't think so. I did not change the hitboxes from the default as far as I can tell.

I'll attach the game folder below. 

[rexbyte_platformer.zip](https://github.com/4ian/GDevelop/files/2800377/rexbyte_platformer.zip)

Thank you :)

**Comment by zatsme** [comment]
Issue 805 though is even stranger as the object still appears to be there for the platform character behaviour even though the platform object is deleted?!  I 'fixed' it by making the origin point 0,0 for all the platform anims even though they were different sizes.

**Comment by rexbyte** [comment]
Thank you for your clear explanation and examples. 

Works perfectly now :)

**Comment by Silver-Streak** [comment]
I'm reviewing older issues on the github to clean some up. This issue *appears* to be fully resolved, at least in the most recent build.

I can move one of the jumpthru platforms in the platformer template, to be player height, and just walk through it without issue. Even stacking them doesn't cause an issue.

Here's an example with that set up: https://game-previews.gdevelop-app.com/1627171398019-99842/index.html

As the ghost user is no longer active on Github, I'm going to close this issue out.
