### ISSUE TITLE
Linked events/layouts don't show disabled status

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#913]
## Describe the bug
If you disable a linked event/layout, it's impossible to see that it's disabled as there's no visual indication.

## To Reproduce
See example: [game.json.zip](https://github.com/4ian/GDevelop/files/2817417/game.json.zip)

**Comment by KinkGD** [comment]
+1, i've forgot to report this one, but i tihink it's here since GD5 is out.

Also, the "link" event aren't really beautiful with the dark theme, maybe it has never been skinned for this theme ?

**Comment by 4ian** [comment]
Yeah background color is hardcoded. Should be fairly easy to read the theme (using ThemeConsumer) and use an existing color,  so that it will adapt automatically to the theme. And strike through the Link text when it's deactivated like other events and groups :)

**Comment by KinkGD** [comment]
First time commiting something for gdevelop and on github... the pull #914 fix (or try to :p) the colors for dark and default theme.
I would like to go further and fix the disabled status, but i have no idea how...

**Comment by 4ian** [comment]
@KinkGD See how it's done for a GroupEvent: 

https://github.com/4ian/GDevelop/blob/26dd33854f60a27e85d46ead656ffeda7b2546d4/newIDE/app/src/EventsSheet/EventsTree/Renderers/GroupEvent.js#L93-L99

The interesting part is `[disabledText]: this.props.disabled,`. 
disablesText is the CSS name that is applied when the event is disabled (this.props.disabled). It's the way we connect CSS to JavaScript.
(disabledText is imported earlier in the file:

https://github.com/4ian/GDevelop/blob/26dd33854f60a27e85d46ead656ffeda7b2546d4/newIDE/app/src/EventsSheet/EventsTree/Renderers/GroupEvent.js#L9-L10
)

So for Link, which is in LinkEvent.js, you can try to import disabledText and insert `[disabledText]: this.props.disabled,` at the right position ;) Hopefully should work

**Comment by KinkGD** [comment]
@4ian & @BWPanda : this issue can be closed i guess ?

**Comment by 4ian** [comment]
Right! :) Thanks for working on this @KinkGD.
