### ISSUE TITLE
 Call GDevelop Function from JS Code Event?

### ISSUE THREAD

**Issue by apedemak** [4ian/GDevelop#925]
I have a question, and couldn't find an answer or example. But I was looking to see if there is a way to call a GDevelop function directly from javascript code.

I'm referring to the custom functions you create, are they accessible via Javascript?

example:

runtimeScene.callFunction('myCustomFunction', Param_1, Param_2);

I asked the same question on the forums here:
http://forum.compilgames.net/viewtopic.php?f=19&t=11247

**Comment by 4ian** [comment]
I'm going to close this as GitHub issues are for bugs only, or sometime technical discussions related to GDevelop development itself. It's important to keep this properly organized. Thanks!

**Comment by Lizard-13** [comment]
@4ian By the way, when I answered that, noticed that the function names are converted to lowercase, easy to break I thought and yes, if you create two lists/functions with the same name but different case GD breaks as two functions generate the same object at the end.

**Comment by 4ian** [comment]
Right I think we can either keep case when "mangling" function names or disallow functions with the same name (case insensitive) in the editor?
