### ISSUE TITLE
[Feature Request] Asynchronous HTTP request

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#928]
Hello,
I saw that you just added asynchronous reading for files.
Is there a way to do the same for HTTP request by just changing a variable when the request is done ? :smiley:

**Comment by 4ian** [comment]
That would be a good idea!
I've added it here: https://trello.com/c/HJAjVJGz/249-action-to-send-asynchronous-requests-http-requests-with-results-stored-in-variables on the roadmap. 

This should be fairly easy to do for an external contributor, but might require adding the action to the Network extension, which is in C++.

**Comment by timotheeficat** [comment]
Thanks for adding it!
