### ISSUE TITLE
Destroy outside: Extra border not applied to new instances

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#935]
## Describe the bug
Even with an extra border, instances created at runtime are beeing deleted right after they got created if they were placed outside of the screen but within the extra border.
This doesn't apply to instances that were placed in the scene editor before starting the game.

## To Reproduce
1. Create a new project and add a sprite object
2. Set an extra border in "at the beginning of the scene"
3. Create an instance outside the screen but inside the extra border via "create object" action
4. According to the debugger, the instance gets deleted immediately (while instances that were created in the scene editor before running the game stay alive)

![image](https://user-images.githubusercontent.com/7413059/52858644-ffb5c200-312a-11e9-8789-0f6f7d88154b.png)

**Comment by 4ian** [comment]
Additional border is per instance, it's not a global setting. So you have to apply it to objects that you create

**Comment by 4ian** [comment]
To avoid this confusion, I think having the additional border in the settings of the behavior would help. You can create a card for it on trello if you wish

**Comment by Wend1go** [comment]
Thanks for clarification ... Done:
https://trello.com/c/77rCdzuA/253-show-additional-border-property-in-the-behavior-editor-of-destroy-outside
