### ISSUE TITLE
New Example - Geo Dash

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#937]
Yes, another one, suggestions welcome!

![2019-02-16 4](https://user-images.githubusercontent.com/17770123/52905529-6b835200-3233-11e9-9768-29f3204d82c8.png)

No prizes for guessing what type of game this is 😄 

Newer zip below

**Comment by 4ian** [comment]
You're creating examples faster than I can add them 😄
Will add it! :)

**Comment by Wend1go** [comment]
I haven't managed to jump over the three spikes in a row but somehow I can't stop trying. ^^
Very nice game.
I'm currently adding tween animations to it, the Title scene is perfect for this.

**Comment by zatsme** [comment]
I'll add a few more levels and I knew about the three spike issue planning to fix that.  Post the tween change here so I can add to that version 👍

**Comment by zatsme** [comment]
New version, 3 levels and can now jump 3 spikes... if you're good :)

[GeoDash.zip](https://github.com/4ian/GDevelop/files/2873269/GeoDash.zip)

Once tween is merged I'll add @Wend1go tweens to it!

**Comment by zatsme** [comment]
Five levels now, 3 spikes can be jumped which allows a trickier route to be made and a pdf with instructions how to add and edit levels without breaking the game 😄 

[GeoDash.zip](https://github.com/4ian/GDevelop/files/2882334/GeoDash.zip)

I Think it's good enough to add to the next release now 👍

**Comment by 4ian** [comment]
Sweet, will add it to next release!

**Comment by 4ian** [comment]
The music is really huge 7 megabytes 😬Could we work to reduce it? Something around 1/2 megabyte would be great... I believe it's doable. Also the PDF is huge, not sure if it's worth adding it? At least would be nice if it was around 100kb rather than 1mb 😄

**Comment by zatsme** [comment]
I'll see what I can do with the music tomorrow, just used it raw from the free music archive, maybe I can reduce it a bit 😄.  The PDF doesn't matter to me, just thought it was useful for a beginner... and it's never going to be on a mobile or part of the game package so.... whatever you think!

**Comment by 4ian** [comment]
I guess it's images inside that are quite heavy. Take a look at things like https://tinypng.com
For the music, pretty sure that changing the bitrate/encoding will allow to reduce it to maybe even less than 1mb.

**Comment by zatsme** [comment]
Sure I'll run it through my audio editor tomorrow and take a quick look at the pdf too👍

**Comment by zatsme** [comment]
[GeoDash.zip](https://github.com/4ian/GDevelop/files/2921524/GeoDash.zip)

 Down to just over 1Mb, ditched the pdf as I already deleted the source files 😄

**Comment by 4ian** [comment]
Added to latest version. Thanks a lot ;)
