### ISSUE TITLE
New example- betabox-basics-learning-experience

### ISSUE THREAD

**Issue by Jmlannan** [4ian/GDevelop#942]
Hello, I made a slightly more advanced version of health bar for a small education company that I work with. We are using it to teach kids some basics of gaming and programming. Id like to share it with the community and also make it a bit easier for us to install!

Thanks!

Here is the link to download it: 

[betabox-basics-learning-experience.zip](https://github.com/4ian/GDevelop/files/2891080/betabox-basics-learning-experience.zip)

  
  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by Jmlannan** [comment]
More compact (1.5 MB) version, removed some unused resources
[betabox-basics-learning-experience.zip](https://github.com/4ian/GDevelop/files/2891309/betabox-basics-learning-experience.zip)

**Comment by Marichalazo** [comment]
Thanks!! I will take a look.

**Comment by Jmlannan** [comment]
TY!

**Comment by 4ian** [comment]
Thanks for doing this :) I'll add it on my To Do list of examples to add to next version! :)

**Comment by 4ian** [comment]
Added to latest version. Thanks a lot!
