### ISSUE TITLE
1280 pixel width Project being treated as 1380 width?

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#944]
## Describe the bug
I have set my project's resolution to 1280x720. When I completely fill the created scene's boundry/have my assets set to 1280 pixel width, there is still ~100 pixels of empty space displayed when I preview it. 

This is treated as if it is usable space (if I place a platforming character there and set up platforms, they can run and jump off that empty space in the game), as if the project is set up for 1380 width instead of 1280. 

You can also have your assets set to 1380 width and have it treated as if it is the full screen, or reduce the project width to 1180 and have it fit the 1280 width assets.

## To Reproduce
1. Create a project with a width of 1280 and a height of 720
2. Create a scene
3. Add tiled assets (or any assets) with a width of 1280 and place it in the scene.
4. Preview scene. There will be a empty grey box to the right of your assets.

Screenshots:
Project settings: https://postimg.cc/n9XcmBhP
1280 width project with 1280 width assets, scene editor: https://postimg.cc/yDygshgm
1280 width project with 1280 width assets, preview mode: https://postimg.cc/hhXdT76n
1280 width project with 1380 width assets, scene editor: https://postimg.cc/svqdxbSy
1280 width project with 1380 width assets, preview mode: https://postimg.cc/qzzHkpNj
Game Files: [CastlePlat.zip](https://github.com/4ian/GDevelop/files/2908040/CastlePlat.zip)

## Other details
OS: Windows 10 - 64 Bit
* Include any OS/browser version/smartphone that you're using
* Add any other context about the problem here.

**Comment by Lizard-13** [comment]
It should be fixed for the next version: https://github.com/4ian/GDevelop/pull/924 :smile:

**Comment by Silver-Streak** [comment]
Thanks for the heads up. Couldn't quite find the right search term. Thanks a bunch!

**Comment by Silver-Streak** [comment]
Hey all, sadly this appears to be back in the current release.

However, the preview works fine now....it's built packages that have the issue.

Preview:  https://postimg.cc/G9rLPPMG
Built package: https://postimg.cc/mzWb57Tx

I tried both cloud build, and building locally using Electron Builder, no change.
Project Files: [Not-A-Vania.zip](https://github.com/4ian/GDevelop/files/3114733/Not-A-Vania.zip)

**Comment by 4ian** [comment]
Indeed, preview was fixed but not exported game. I should have fixed this now in https://github.com/4ian/GDevelop/commit/6d92430e769b02d4aaec96e018127cb7e670a78a

If you want to try locally, export and modify main.js to add [this line](https://github.com/4ian/GDevelop/commit/6d92430e769b02d4aaec96e018127cb7e670a78a#diff-537269e4c35a9570f85247f91ede922fR17) before packaging manually.
