### ISSUE TITLE
Copy an object between Scenes and paste it over a Global Object --> Object automatically becomes Global

### ISSUE THREAD

**Issue by MercurioC** [4ian/GDevelop#945]
## Describe the bug
As the title stands, pretty annoying bug. Here it is in action:

![zmxep2o](https://user-images.githubusercontent.com/17031164/53498067-db040780-3aa5-11e9-9210-a0ae7bcf2877.gif)

## To Reproduce
1. Copy an object in a scene
2. Paste it into another one, hovering on a Global Object

## Other details
* Latest Win10, GDevelop 5.0.0-beta64

**Comment by PascalLadalle** [comment]
I noted this too.
If there was a clearer separation between normal and global objects, I guess it could be a feature rather than a bug...

**Comment by blurymind** [comment]
So is the problem that an object is not indicated as global clearly enough in the list?

**Comment by Lizard-13** [comment]
No, a common object is turned into a global one automatically on pasting, very annoying as scene > global object conversion can't be undo.

**Comment by zatsme** [comment]
I assumed this was working as designed as once you paste the object from one scene to another it has to be global..... 

If this isn't the case then Scenes can have objects with same name as other scene but not same object which could be quite confusing.
This could become complicated! 😄

**Comment by 4ian** [comment]
This is indeed a feature :) A clearer separation would I guess do the trick?

**Comment by blurymind** [comment]
Maybe a yes/no prompt waning the user that the object will become global?

**Comment by blurymind** [comment]
I can try to add the prompt tonight, if you guys think it would be a sufficient solution :)

**Comment by 4ian** [comment]
Not sure if a prompt is really useful. If you made the mistake of clicking on the button to paste as a global object, you can remove the object.

I think a good first step would be to make things more obvious: if the object will be pasted as a global object, the context menu could display "Paste as a global object" instead of "Paste".

**Comment by blurymind** [comment]
@4ian that's a fantastic idea!

**Comment by 4ian** [comment]
Let me know if you give it a try or have questions :)

**Comment by blurymind** [comment]
I'll try to add it tonight :) seems like another easy one to tackle

**Comment by blurymind** [comment]
Ok I looked at this and now I am not sure if this is a bug or not.
@4ian have you removed the feature?

When you copy a normal object and paste it in another scene- you dont get a global object. It's another local object!

When you copy a global object and paste it in another scene - your pasted object is global again.

If I get this right- this report says that copying a local object from one scene and pasting it into another scene makes both the object and its copy in the other scene a global object. This is not happening for me

**Comment by 4ian** [comment]
You have to paste on a global object to get it as a global object :)

**Comment by blurymind** [comment]
@4ian I see. Will try again tonight :)

Btw the current context menu is a bit flawed. For example you cant get the menu until you create at least one object in the scene. To paste objects from another scene, you have to create an empty object. To paste them as global, you need to create one empty object and make it global

**Comment by blurymind** [comment]
made a pull here
https://github.com/4ian/GDevelop/pull/997
![pasteAsGlobalHint](https://user-images.githubusercontent.com/6495061/55255958-cd33d480-5253-11e9-879a-dfc86ea5ad18.gif)

**Comment by MercurioC** [comment]
Seems a great solution! Thanks for your work 👍

**Comment by blurymind** [comment]
I also made it show the name of the copied object. Hope that is ok
![displayClipObjName](https://user-images.githubusercontent.com/6495061/55259231-06bd0d80-525d-11e9-973b-1b4a5ec829e2.gif)

Makes it even clearer imo

**Comment by blurymind** [comment]
@MercurioC  thank you  :)
Now that this has been merged, can you close this issue please

**Comment by 4ian** [comment]
What you've done should make things more intuitive. Closing this for now :)

**Comment by PascalLadalle** [comment]
Bumping this as I had to do it three times today:

> @blurymind  
> 
> Btw the current context menu is a bit flawed. For example you cant get the menu until you create at least one object in the scene. To paste objects from another scene, you have to create an empty object. 
>
