### ISSUE TITLE
My new game LIMO

### ISSUE THREAD

**Issue by Marichalazo** [4ian/GDevelop#946]
Hi guys. After a few months I have finally finished my game. I have it free for 8 days in case you want to download it. It is a platform game and some puzzle. My wish is to be able to help all those who have offered their help for free. I hope you like it.

https://play.google.com/store/apps/details?id=com.apsindie.LIMO.apk

**Comment by blurymind** [comment]
@Marichalazo do you have a trailer video somewhere? I can include it to gdevelop's sizzle video

**Comment by 4ian** [comment]
Looks great! Can I add it to the website? :)

**Comment by Marichalazo** [comment]
4ian. You have to take the cages with your finger and jump on them. Once you jump over them, they will disappear. The dynamics of the game goes like this.

**Comment by Marichalazo** [comment]
@blurymind. I don't have any video. I have not had time and I have been saturated.

**Comment by Marichalazo** [comment]
This is a small video of the first Stage in case it works

https://youtu.be/Z7kXtXrS4vk

**Comment by blurymind** [comment]
@Marichalazo thank you for sharing this. Please keep it online. I will try to add it to the sizzle video next time I edit it

**Comment by Marichalazo** [comment]
@blurymind Thanks!!

**Comment by 4ian** [comment]
Added on showcase. Thanks!

**Comment by Marichalazo** [comment]
The link works again.

**Comment by DavideGalilei** [comment]
Why you have deleted LIMO from PlayStore?
