### ISSUE TITLE
"Center" point not recognized unless spelled "Centre"

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#954]
## Describe the bug
When referring to a sprite object's "Center" point (as labeled in the list of points), it is ignored as an invalid point. Using "Centre" instead will return the "Center" point.

## To Reproduce
1. Create an object. (e.g. 32 by 32 square)
2. Calculate the center of the object (16x 16y)
3. Refer to that Center point in an event ( e.g. move another object'sX to Object1.PointX("Center")
4. Preview the game. It will not be moved to the center point.
5. Update your event to use Object1.PointX("Centre").
6. Preview the game. It will be moved to the correct location.

## Other details
Created from the translation thread: https://github.com/4ian/GDevelop/issues/927#issuecomment-469195741

**Comment by zatsme** [comment]
I remember talking about this months ago... What spelling should we use 8n the IDE? , as a UK English native I'd vote Centre, but should it stay as is and add Centre to the sprite runtime?

**Comment by Silver-Streak** [comment]
The response from 4ian in the other thread made it sound like both spellings should be accepted. I think either being rendered in the sprite point list is fine as long as events accept both.

**Comment by zatsme** [comment]
Simple fix seems to work fine https://github.com/4ian/GDevelop/pull/955

Does this look good to you @4ian ?

**Comment by 4ian** [comment]
Yeah that looks like a proper fix :)

**Comment by 4ian** [comment]
Closing as this will be fixed in next version :)
