### ISSUE TITLE
Project manager disappears when using the mouse to rename

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#957]
## Describe the bug
When renaming a scene, if the mouse is used on the name, the panel disappears (which in turn, triggers another bug).

## To Reproduce
Open the Project manager, click on the dots next to a scene name, choose rename, and click on the name.

## Other details
Windows 10

**Comment by 4ian** [comment]
Fixed this by preventing the scene opening when you're clicking on the item (scene, external layout, external events or extension) while renaming it.
(Note that the field is auto focused, so you don't need to click on it to renaming the scene).

Will be in the next version :)
