### ISSUE TITLE
Not changing a scene name triggers an error

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#958]
## Describe the bug
If I hit Rename by mistake or if I change my mind, leaving the same name triggers an error.

## To Reproduce
Open the Project manager, click on the dots next to a scene name, choose Rename, and hit Return. The message says "**Another** scene with this name already exists.", which is confusing.

## Other details
Windows 10
Related to https://github.com/4ian/GDevelop/pull/888 ?

**Comment by 4ian** [comment]
You're right! Fix should be fairly easy, just return early if `newName === oldName`

**Comment by 4ian** [comment]
Fixed this for next version :)
