### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#961]
If you open: [http://compilgames.net/forum/](http://compilgames.net/forum/)

This error is shown:
```
General Error
SQL ERROR [ mysql4 ]

mysql_connect function does not exist, is mysql extension installed? []

An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
```
Are you doing maintenance right now?

**Comment by 4ian** [comment]
=> https://forum.gdevelop-app.com ;)

I put a redirection on forum.compilgames.net but forgot about this. Will add a redirection

**Comment by 4ian** [comment]
Redirection added :)
