### ISSUE TITLE
GDevelop crashes when opening a project

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#962]
## Describe the bug
Random bug that causes GD5 to freeze when opening a scene events after loading a project.
The whole system gets very slow. I can open the task manager (takes me a minute to do so), but I'm unable to close the three GDevelop.exe instances, and I have to hard reset the computer.

## To Reproduce
!Random!
Open GD5, load a project, and open a scene. Click on the events tab. If the events don't show up and the page remains gray, you're screwed!

## Other details
Windows 10
I would say it happened to me about 5 times in a month. So far, it only happened during the initial loading of the software/project.

**Comment by blurymind** [comment]
its possible that something in your project is causing this. Is it a big project somehow? Can you share it if it's not?

**Comment by 4ian** [comment]
Can you also share the details about your system (RAM, CPU)?

> three GDevelop.exe instances

That's a lot! :) If you have multiple instances all editing large/medium games, you could en up using a lot of RAM/CPU

**Comment by PascalLadalle** [comment]
Well, 99% of the time, my project opens fine. But I've noted bugs every now and then after messing with my game components (renaming, duplicating, moving around...), ghost-type bugs, and I suppose such ghosts would be a potential cause? 
Does GD come with some sort of a "clean-up" feature that would clean the game.json from potential junk?
I'm doing minigames, but I've got ten of them, so the project is getting big 😄 


Sorry @4ian I meant "processes" not "instances".
Only one instance of GD, but three actual processes (one main process, one type "gpu-process", and one type "renderer"). When it gets stuck, I'm unable to close these, they keep running and I get an 'error: process is being terminated' when I try again (through a task manager software called "Process Hacker").
CPU is hexacore Athlon FX6300, with 8GB RAM and SSD system drive.

**Comment by blurymind** [comment]
does this happen with any of the example projects that come with gdevelop?

**Comment by PascalLadalle** [comment]
As I said, it happens rarely. It hasn't happened since I reported the bug.
I don't think it has happened to me while looking at the examples.

**Comment by blurymind** [comment]
You have no example or steps to reproduce the issue.
If we can't reproduce it, we can't find the source of the problem.

**Comment by PascalLadalle** [comment]
I know, I simply posted the bug because it was happening for the 5th time or so. The problem could be linked to my own project, or my computer (hardware, drivers, etc.). But maybe someone encountered that issue too.

My project has 20 scenes, a dozen external layouts and about 20 external events. I'm not going to count lines 😀 
As I said, it happened during the initial loading, so GD wasn't using much RAM. From memory, I'd say one process was at 300MB and the two others at less than 100MB.
I **think** that when it happened, the objects were not showing up on the graphical scene editor tab. Not sure if it did that each time though.

I'll post an update if the bug shows up again.

**Comment by 4ian** [comment]
Sure, if you can include the screenshot (even if it's a gray screen) or the whole app window it would help too :)

**Comment by PascalLadalle** [comment]
*bump* 
Today, it kept crashing and crashing...
I open GD and load a project (the platformer example on which I created the back_and_forth extension). The project loads, the background is visible on the scene, the text object is visible, but the textures are missing, sometimes all of them, sometimes not all.
At the fourth or fifth reboot, before opening GD, I opened the file explorer and checked that I could access the project files (it's on a secondary HDD). I did. Then I opened GD, and the project loaded fine...
I tried to take a screenshot, but the computer won't do anything, it's all frozen. I was able to open the snipping tool and grab a screenshot, but I was never able to save it.

**Comment by 4ian** [comment]
Would you be able to open the task manager to see if:
* there is a suspicious amount of RAM used?
* there is a high usage of CPU?

Also, can you tell about your system configuration? This could be related to buggy graphics driver.

**Comment by PascalLadalle** [comment]
I was able to open the task manager, though it would take up to 30 secs to open, but I was unable to locate any issue. Every time, the CPU load seemed fine, and the RAM too. 
Other apps like Firefox were running quite smoothly if my memory serves me right, but GD and explorer.exe were completely unusable.

My specs: AMD FX6300 (6-core), 8GB RAM, SSD system drive, 7200RPM HDD as secondary drive, and GPU is Radeon R7 260 2GB DDR5.

I'll reset my system soon to install a new SSD. I'll install the latest drivers, I'll move 'MyDocuments' to my C: drive, and hopefully that'll fix it.

**Comment by PascalLadalle** [comment]
This hasn't occurred again. Might have been due to a failing hard drive.
