### ISSUE TITLE
Dragging objects causes a freeze

### ISSUE THREAD

**Issue by Frontrider** [4ian/GDevelop#963]
## Describe the bug
Grabbing buttons causes the editor to freeze, and the grabbed object gets stuck on the part of the screen where it was dragged to, above all applications.

## To Reproduce

1. Go to the events screen
2. Create an event
3. Drag it.

the white line with the dark end is the dragged event, that is still above my browser as I'm writing it.
![image](https://user-images.githubusercontent.com/6755034/53983289-2efe9400-4117-11e9-89ed-7481537bafc3.png)
![image](https://user-images.githubusercontent.com/6755034/53983506-9d435680-4117-11e9-9b3e-dc91523d7de9.png)

Can be removed by closing the frozen app.

## Other details
* Gdevelop 5
* manjaro linux

**Comment by elgabo86** [comment]
I have the same problem on Archlinux..

**Comment by elgabo86** [comment]
add the --disable-gpu parameter works

**Comment by Frontrider** [comment]
Manjaro is arch.

**Comment by kadogo** [comment]
Same issue on Debian Buster (it was working on Stretch with my old kernel 4.9). The argument --disable-gpu make it work.

By electron we see some issues about drag / drop too (https://github.com/electron/electron/issues/12820)

**Comment by 4ian** [comment]
Might need an update to latest Electron, flagging as good first issue.

**Comment by Silver-Streak** [comment]
Hello, I'm going through older issues to bring attention to them or close them out if resolved.

I am not able to reproduce this on the current beta release. Are you still experiencing this on b113 or newer?

I'll close out this issue if I receive confirmation that it is reolved, or if no response is received within 30 days of this post.
