### ISSUE TITLE
Inserting sprites traditionally sometimes corrupts the image file or deletes it.

### ISSUE THREAD

**Issue by SomeWeirdo** [4ian/GDevelop#966]
I always want to insert images traditionally in GDevelop 5 as the image quality turns out much better then inserting an image through Piskel, but whenever I insert in image traditionally (not using Piskel) and I save the game and open it later, all the images inserted with Piskel have no issue at all, but all the images inserted with the traditional way become corrupted or delete themselves. I'm on the latest version of GDevelop 5 on MacOS,  I'm not sure how to recreate this issue.

[![Screen-Shot-2019-03-09-at-10-56-00-AM.png](https://i.postimg.cc/zXQYDxYZ/Screen-Shot-2019-03-09-at-10-56-00-AM.png)](https://postimg.cc/rK5PQCpQ)

**Comment by blurymind** [comment]
Can you share a minimal project that has this issue? Just zip the folder and drag and drop it here

**Comment by 4ian** [comment]
Yeah please share an example project so that we can see what can go wrong :)
I'm developing GD on macOS and don't have this issue so it's very weird

**Comment by blurymind** [comment]
@SomeWeirdo are these images by any chance stored outside of the project folder?
the two dots in `../endd.png` would suggest that

**Comment by blurymind** [comment]
@4ian perhaps I can add a warning yellow colour to resources stored outside of the project folder? Or maybe even a non-intrusive warning can also show up at the bottom whenever a user does that

**Comment by 4ian** [comment]
> @SomeWeirdo are these images by any chance stored outside of the project folder?
the two dots in ../endd.png would suggest that.

Just want to note that this should work fine (as long as you do not move the game file or the images).

> @4ian perhaps I can add a warning yellow colour to resources stored outside of the project folder? Or maybe even a non-intrusive warning can also show up at the bottom whenever a user does that

Yeah, though someone could have a structure like this:

```
mygame/
  - project/
    - game.json
  - assets/
  - otherstuff
```

and it should be valid, so not sure if a warning is a good idea.

Though it's a recurring error that user do (adding images that are not in the project folder, so that when they move the project everything is broken).
So we could:

* Do nothing
* Or add a warning
* And/or use absolute path for the resource if it's inserted from a folder that is not inside the project (so that the game does not break when you move it around) (but still break if moved/transfered to someone else)

**Comment by SomeWeirdo** [comment]
Ah, I assumed everytime I insert a sprite into GDevelop, it duplicates the image and puts it inside its own folder (this seems to be what Piskel does), so that would explain why it would go “corrupted” like that in the traditional way, as I moved the original file to a different location. The image should be duplicated into the folder it’s saved like Piskel, I didn’t use Piskel in this case though as for large sprites, Piskel reduces the resolution of the image by a ton.

Also I didn’t send an example file this time because I wouldn’t see how that would show the issue. I said I couldn’t figure out how to recreate the issue on command and sending an example project for an issue like this wouldn’t make sense.

**Comment by blurymind** [comment]
Piskel is there for pixel art, which has a smaller color palette. Use it to
create images, not import them. That's why the button says 'edit with
piskel'

**Comment by 4ian** [comment]
Will close the issue as there is no bug, though we can continue discussing how to improve the UX so that no confusion can happen.
