### ISSUE TITLE
copy feature stuck on enabled

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#967]
## Describe the bug
There seems to be a feature (or is it a bug?) where Shift+Ctrl enables automatic copy-paste. 
Once that feature is enabled, lines moved around will be copied instead of being moved (without holding Ctrl).
The user can't see any indication that the feature is enabled/disabled and it is quite confusing.

## To Reproduce
I'm having a hard time nailing it down, but it involves using Shift+Ctrl while using the mouse to select lines.

## Other details
Windows 10
If it is indeed a feature, a copy-paste symbol on the mouse cursor would be nice.

**Comment by 4ian** [comment]
It's a feature, keep pressing Ctrl (or Cmd on mac) before drag'n'dropping an action/condition to duplicate it. Though I agree it's a bit hard to use because Ctrl/Cmd has to be kept pressed BEFORE starting the drag'n'drop - and there is no visual indication.

**Comment by PascalLadalle** [comment]
I'm not sure you understood my message.
Sometimes, once I've pasted a line by drag-dropping with Ctrl, I don't need to use Ctrl anymore, it duplicates automatically the lines I move with the cursor alone (without Ctrl).
So far, I haven't been able to reproduce the bug/feature I'm talking about with the Ctrl key alone.

**Comment by Silver-Streak** [comment]
@PascalLadalle I'm going through old issues. Are you still experiencing this?

**Comment by PascalLadalle** [comment]
Nope, haven't seen that one in a long while.
