### ISSUE TITLE
Cannot click on certain parts of the color picker (scene properties)

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#978]
## Describe the bug
When editing the background color of a scene, the tickbox below the color picker remains active, so that it gets clicked instead of picking a color.

## To Reproduce
Open the scene properties
Open the color picker, try to pick a color near that tickbox.
![colorbugger](https://user-images.githubusercontent.com/25978830/54453422-9049e700-4757-11e9-9f5b-1c7339769aea.jpg)

## Other details
Win 10 / GD5b65

**Comment by PascalLadalle** [comment]
workaround: pick a color where it works and drag the cursor.

**Comment by KinkGD** [comment]
@PascalLadalle is it the only screen with this issue (bg color scene ?). I'll take a look on this.

**Comment by PascalLadalle** [comment]
@KinkGD There was a problem with another color picker being partly outside the screen, but I think that one has been fixed.
I haven't noticed it somewhere else.

**Comment by KinkGD** [comment]
It's why i'll take a look, i've corrected the previous issue, but maybe i created this new one ^^ :)

**Comment by KinkGD** [comment]
@PascalLadalle , is the problem corrected in the new release ? If yes (i hope), let's close this issue.

**Comment by PascalLadalle** [comment]
Fixed!

**Comment by 4ian** [comment]
Thanks for the follow up 👍
