### ISSUE TITLE
Default directory for opening a file

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#979]
## Description/Reproduction
Let's say you have a project opened and you want to add a sound. You select a sound action, click on "Choose a new audio file", and an explorer pops up.
This explorer always opens to the project's base directory. If you have a dozen files to load from the same folder, it's quite annoying to browse a dozen times to your sound folder. To me, it's "Non optimal behaviour", but I can understand if it's meant to work that way.
Where it gets really illogical, now: if you close GD, open it again and choose to open a project, then it shows up the most recently used folder (that sounds folder, in my example, instead of the base folder of the last opened project, which would be the logical choice).
Sorry for the not-so-concise description 😬 
Not a very interesting/troublesome bug, but it annoys me every day.

## Other details
Win 10 / GD5b65

**Comment by KinkGD** [comment]
+1, i'm feeling the same boredom for months on GD5! GD4 was acting exactly like you describe.

**Comment by 4ian** [comment]
For resources, the default folder is indeed the project folder (see:
https://github.com/4ian/GDevelop/blob/ec0b93455765b7c890ce7550f0841e1f8b2319ac/newIDE/app/src/ResourcesList/LocalResourceSources.js#L163
)

For project creation, picker are here:
https://github.com/4ian/GDevelop/blob/ac2867f1a741adc500192004213afeb03f90254a/newIDE/app/src/ProjectCreation/LocalStarters.js#L142
https://github.com/4ian/GDevelop/blob/2fa3bb7b1b78b6c28468179f3c9cf2644dcdccac/newIDE/app/src/ProjectCreation/LocalExamples.js#L76

They don't have indeed defaultPath, meaning that default path is decided by the OS, which is the last path opened in a dialog.

If anyone want to give it a try, the last path could be saved somewhere in the preferences, and used then in these `LocalFolderPicker`.
