### ISSUE TITLE
Minimum size is enforced

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#985]
The minimum size of panel sprites is awkwardly enforced. When a digit is typed in, it's replaced by the minimum size.

## To Reproduce
Create a panel sprite object.
Add margins of 20 px.
Default size values should be 32 px. Highlight 32 with the cursor and enter 600.
What do you read? -> 4000!
6 has become 40.

## Other details
Windows 10, GD5 b65

**Comment by 4ian** [comment]
Finally fixed for next version (in e210eb0ca2eabac79d5846fb8c6e4117975dc3ed) :) Other editors with "funny fields" having the same weird behavior have been fixed too.
