### ISSUE TITLE
Active tab changes when closing a tab

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#986]
## Describe the bug
When several tabs are opened, closing one moves the tabs to fill the gap, but the active tab remains at the same place, which changes the opened tab.

## To Reproduce
Open 4 tabs (two scenes, for instance).
Click on the third tab to make it active.
Close the second tab. The third tab moved to its spot, and the fourth tab has become the active tab.

## Other details
Windows 10
GD5 b65

**Comment by 4ian** [comment]
Marking good first issue as easy to fix

**Comment by gautamv95** [comment]
Can I work on this?

**Comment by 4ian** [comment]
Sure! Should be a bit of React/JavaScript to fix :)
