### ISSUE TITLE
Contextual options aren't greyed out when they can't be used

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#987]
## Describe the bug
Right-clicking on a Link event shows "Add Sub-event" although it cannot be used on this event.

## To Reproduce
Right-click on a Link event ("Include events from ...").
Choose Add Sub-event.
Nothing happens. 

## Other details
Windows 10 
GD5 b65

**Comment by blurymind** [comment]
I can look into that :) I added the command there after all

**Comment by 4ian** [comment]
Cool, let me know how it goes :) Events should have a `canHaveSubEvents` method.

**Comment by blurymind** [comment]
this one is quite simple. Will do a pull tonight

**Comment by blurymind** [comment]
made a fix here
https://github.com/4ian/GDevelop/pull/990

while at it, we shouldnt be able to toggle comments on/off

**Comment by 4ian** [comment]
For comments, you can use `isExecutable` :) (an event that is not executable is stripped when exported to code, so can't be disabled as it's "already" disabled)

**Comment by blurymind** [comment]
@PascalLadalle this is now fixed in the master branch. Can you try again and if it works as expected for you, close this issue?

**Comment by 4ian** [comment]
Let's close this as it should be fixed for next version :) Can re-open later if for some reason it does not work.
