### ISSUE TITLE
Tab key cannot be used everywhere

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#991]
## Describe the bug
The Tabulation key doesn't always allow to move on to the next field.

## To Reproduce
- Click on _Add condition_, and pick _Value of a scene variable_, for instance.
- Type the name you want or use the arrows.
- Press Tab twice to access the operator.
- Press down arrow to pick the operator.
- Press Tab to move to the next field. Nothing happens.

**Comment by blurymind** [comment]
this one is important to address in terms of making it possible to use keyboard only when setting the event sheet for example. Tabbing and shift-tabbing to previous/next focus neighbour can dramatically reduce the number of steps in setting things up.

When we tab to things, the hands stay at the keyboard and its one step to focus on next/previous.

**Comment by 4ian** [comment]
The specific example reported here seems to be fixed. Can we close this unless other buttons/fields are not "tab-accessible"?

In theory everything that is shown on screen and that is a proper component has support for being browsed with tab, and after opening a dialog you should always be able to press tab in case you don't have the focus to select the first element of the dialog.

**Comment by PascalLadalle** [comment]
not optimal, but seems fully functional. 👏 

In the same fashion, it would be nice if Alt gave access to the main menu as in most of Windows programs. And if ctrl-tab could switch between tabs, just how wonderous would it be! 🌈 😁
