### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [4ian/GDevelop#993]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ParticleSystemWrapper::Init](https://github.com/4ian/GDevelop/blob/97aeafc4c37f97f9784846c77b6d71f8c765b476/Extensions/ParticleSystem/ParticleSystemWrapper.cpp#L42 "ParticleSystemWrapper::Init function")
- [TileMapProxy](https://github.com/4ian/GDevelop/blob/97aeafc4c37f97f9784846c77b6d71f8c765b476/Extensions/TileMapObject/TileMapProxies.cpp#L32 "Destructor for TileMapProxy")
- [Tmx::Object](https://github.com/4ian/GDevelop/blob/97aeafc4c37f97f9784846c77b6d71f8c765b476/Extensions/TileMapObject/IDE/TMXImport/tmx-parser/TmxObject.cpp#L54 "Destructor for Tmx::Object")

**Comment by 4ian** [comment]
* ParticleSystemWrapper::Init is part of the TileMap extension for GD4 and is mostly not maintained for now. Might be re-introduced in GD5 but it's super low priority and unsure for now.
* Same for TileMapProxies.cpp, it is part of the TileMap extension for GD4 so it's super low priority and unsure for now if kept in the future.
* TmxObject.cpp is part of tmx-parser library, so improvement should go there and be imported in GD codebase :)
